### PR TITLE
fix: Fixed extra column space on smaller screen size

### LINKED ISSUE #4630: Extra column space in mobile view
### Description
There is a extra column that appears in mobile view at :  https://layer5.io/community/handbook/mentorship-programs

### Expected Behavior
There should not be a extra column in mobile view

please Assign it to me if it needs to be addressed.

### Screenshots

vasd

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**Description**

This PR fixes #4630

Fixed extra margin at: https://layer5.io/community/handbook/mentorship-programs. This space was due to larger images and text

***Before***

image

***After***

image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 57b1a472f13b96743d29a65439136ccbbb761c93 at: https://65afc4845f3984144a9ff496--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Hi @pateldivyesh1323  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by iArchitSharma — APPROVED** [review]
LGTM, thanks @pateldivyesh1323

**Comment by l5io** [comment]
🚀 Preview for commit d2b9f33269a310e6d1d1baf834c087bfcf2e71ff at: https://65b6711554edd86d0ccf0943--layer5.netlify.app

**Comment by pateldivyesh1323** [comment]
@saurabh100ni Sure, I have added this PR in doc.

**Pull request merged**
