### PR TITLE
updated member community member profile.

### LINKED ISSUE #4786: [Community] Member Profile: Aritra Majumder
**Current Behavior**

@Aritra8438  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aritra8438 s a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Aritra8438 
- Twitter: 
- LinkedIn: [aritra-majumder-juee23](https://www.linkedin.com/in/aritra-majumder-juee23 )
- Meshery Cloud:[1b462fee-7808-4a79-a504-9c4e986f32b9](https://meshery.layer5.io/user/1b462fee-7808-4a79-a504-9c4e986f32b9) 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by brijeshbhikadiya**
**Description**

This PR fixes #4786

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a0f9e7afbe1e320de80b9ebe2eff811b852dae6a at: https://64ec3ef917d1f35c6bf0dfb2--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
hey @brijeshbhikadiya Looks Good but changes to repository.js not needed!

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@brijeshbhikadiya, could you please undo the modifications you applied to the repository.js file?

**Comment by vishalvivekm** [comment]
> hey @brijeshbhikadiya Looks Good but changes to repository.js file not needed here!

@brijeshbhikadiya will you please undo not-required changes?

**Comment by brijeshbhikadiya** [comment]
done

**Review by abhijeetgauravm — COMMENTED** [review]
hey @brijeshbhikadiya this file shouldnt be deleted , you are supposed to undo the changes!

**Review by Aritra8438 — CHANGES_REQUESTED** [review]
Just modify the `index.mjs`. Don't delete or modify `repository.js`!

**Comment by brijeshbhikadiya** [comment]
okay

**Pull request closed without merging**
