### PR TITLE
Updated Images in Cloudevents How it Works See in Action Section

### LINKED ISSUE #4869: [Screenshots] Cloudevents under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/cloudevents) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Cloudevents](https://layer5.io/cloud-native-management/meshery/integrations/cloudevents) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Chay2203**
**Description**

This PR fixes #4869 

**Notes for Reviewers**
I have updated the images in the "How it Works See in Action" Section, please have a look at it ;D

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0a9b03a76bdf34c955e11f930e2a049d0ec33b8f at: https://65e4bda742cf7ebbce1f9651--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Chay2203 Let's discuss this on Websites's call today 6:30 PM IST. Let's add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by Chay2203** [comment]
Hey @vishalvivekm, I have made the necessary changes that we discussed in the GMeet, please have a look now :)

**Comment by l5io** [comment]
🚀 Preview for commit 9bdae94a0acaa24e2c740dff9bfc34cf8e5a9425 at: https://65e8b48b060ab9355b3879d0--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@Chay2203 images should only be present in the `src/collections/integrations/_images/cloudevents/` directory, remove them from other places

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
Please do the above

**Comment by Chay2203** [comment]
Sure will do it @iArchitSharma

**Comment by iArchitSharma** [comment]
@Chay2203 still working on it?

**Comment by Chay2203** [comment]
busy with other things @iArchitSharma, please assign it to someone else

**Pull request closed without merging**
