### PR TITLE
Added Event on Calendar

### PR DESCRIPTION
**Pull request by moazzam07**
Added Event On Calendar

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@moazzam07 seems like no files have been committed here.

**Comment by moazzam07** [comment]
@warunicorn19 i have tried a lot of time but idk why it is not committed

**Comment by moazzam07** [comment]
it shows some errors

**Comment by Zain-Muiz** [comment]
@moazzam07 , Could you comment the error here ? So @warunicorn19 and I can have a look.

**Comment by moazzam07** [comment]
I am committing the file, but after committing it is showing nothing to commit,working tree clean

**Comment by warunicorn19** [comment]
could you please do `git status` and send a SS.

**Comment by moazzam07** [comment]
image

**Comment by leecalcote** [comment]
Actually, the event calendar feeds from a Google Calendar. This event will need to be added on a Google Calendar in order to reflect here.

**Comment by moazzam07** [comment]
so do I have to use google calendar api or just add details on meetLinkData.js file

**Comment by leecalcote** [comment]
Hi @moazzam07, if its ok, let me take this task off your hands and replace it with this issue - https://github.com/layer5io/layer5/issues/2193. What do you say? Would you like to work on this issue instead?

**Comment by warunicorn19** [comment]
Closing this PR.

**Pull request closed without merging**
