### PR TITLE
Fixed button misalignment

### LINKED ISSUE #821: [Books] Buttons misaligned on service mesh book
**Description**
The book on [this webpage](https://layer5.io/books/the-enterprise-path-to-service-mesh-architectures) has buttons landing on the side of it. See screenshot. Source code for the page [is here](https://github.com/layer5io/layer5/blob/master/collections/_books/2018-06-11-the-enterprise-path-to-service-mesh-architectures.md).

**Expected Behavior**
Buttons should be beneath the book.

**Screenshots**
Screen Shot 2020-09-25 at 6 07 20 PM

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by knowyours**
Signed-off-by: knowyours <knowyours.cbe@gmail.com>

**Description**
Buttons realigned in service mesh book page

This PR fixes #821 

**Notes for Reviewers**
Hello, I have added a piece of code that helps realign the buttons on the service mesh book page. Also, this is my very first open source contribution :)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by knowyours** [comment]
Hello @leecalcote, I have added my first open source contribution as a pull request that fixes issue #821. Please check it out. Thank you :)

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Thank you for this @knowyours . Just a small change that you may want ro do is fix the responsive view of the page.
Screenshot_20200927-140745__01

**Comment by knowyours** [comment]
> Thank you for this @knowyours . Just a small change that you may want ro do is fix the responsive view of the page.
> Screenshot_20200927-140745__01

Yes sure. I'll check that out

**Comment by knowyours** [comment]
@Nikhil-Ladha The fix as been done. Please review the same.

**Comment by Nikhil-Ladha** [comment]
The page looks good now. But, few improvements can be done here.
The inline style can be moved to the external stylesheet, and the class name `issueFix` doesn't looks good, rather something like `bookImageGrp` something like that would be better.
Also, the padding between the button and the starting of the book summary can be reduced a bit.

**Comment by knowyours** [comment]
> The page looks good now. But, few improvements can be done here.
> The inline style can be moved to the external stylesheet, and the class name `issueFix` doesn't looks good, rather something like `bookImageGrp` something like that would be better.
> Also, the padding between the button and the starting of the book summary can be reduced a bit.

Yes sure, I'll change the class name as suggested. Can you please clarify a bit more about the padding between button with a screenshot preferably?

**Comment by Nikhil-Ladha** [comment]
This space here,  can be reduced a bit by 10px approx.
Screenshot_20200928-115258__01

**Comment by knowyours** [comment]
> This space here, can be reduced a bit by 10px approx.
> Screenshot_20200928-115258__01

Alright, noted.

**Comment by Nikhil-Ladha** [comment]
Looks good, just the DCO issue needs to be fixed, and if the `style` is moved to the external stylesheet which here is `materialize.css` is it would be better. :)

**Comment by knowyours** [comment]
@Nikhil-Ladha I made the move of the inline styles to materialize.css but I am still not able to fix DCO issue

**Comment by knowyours** [comment]
@Nikhil-Ladha All changes applied as mentioned

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good. Thank you @knowyours 👍🏼

**Comment by Nikhil-Ladha** [comment]
Yeaa! First contribution done ✅. Many more to come🎉

**Comment by knowyours** [comment]
> Yeaa! First contribution done ✅. Many more to come🎉

Thanks a lot for this experience @Nikhil-Ladha 
Can I have some guidance in moving forward from here?

**Comment by Nikhil-Ladha** [comment]
Of course, ping me in slack. Let's have a discussion there :)

**Comment by leecalcote** [comment]
Haha! So cool, @knowyours. 😎

**Pull request merged**
