### PR TITLE
[Fix] Sistent page UI bugs resolved (small devices)

### LINKED ISSUE #5677: [UI] Horizontal scrolling, Dropdown and Table of Content button issue on small devices
### Description
Horizontal scrolling issue (creating space on right side of screen), Dropdown not visible and Table of Content button not clicking/working on small devices

### Expected Behavior
There should be not any horizontal scrolling (no-space on right side of screen), Dropdown should be visible(with proper working) and Table of Content button should be clickable and working.

### Screenshots

https://github.com/user-attachments/assets/0da92dfa-27e6-4f46-a50c-5cc288ebb383

I will work on this issue.

### Environment:
- Host OS: Ubuntu
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Muhammed-Moinuddin**
**Description**
Resolved Horizontal scrolling, Dropdown and Table of Content button issue on small devices.

This PR fixes #5677

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e5b91da72cfb2353bc3a2a10a9838e9d2e587803 at: https://6694f6912cfa683cf4d8e6a8--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin 
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by Muhammed-Moinuddin** [comment]
As it is reviewed, kindly merge it.
@vishalvivekm @sudhanshutech

**Review by iamclintgeorge — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 2b37fa7fe086fd54eaf978c9ba64ca616859acab at: https://669a4e450171182229b7cd2c--layer5.netlify.app

**Pull request closed without merging**
