### PR TITLE
[Handbook] Recognition: Recognizing and Appreciating Community Members

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Description**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This could use a little more description regarding how we recognize publicly on social media platforms.

@tinniaru3005, you might like to review.

**Comment by tinniaru3005** [comment]
- A few Hyperlinks may be added to further highlight the recognitions. Example: [Member profile](https://layer5.io/community/members), [Layer5 website](https://layer5.io/)
- We can add this section:
### Recognizing your contributions on social media.
We highly encourage you to share your engagement and contributions to the layer5 community on social media like LinkedIn and Twitter. We support every contribution by liking your posts and retweeting them. Your contributions and engagement in different ways are what make us a successful and collaborative open-source community. We love celebrating your every accomplishment with Layer5 publicly and encourage you in every way we can.

**Comment by tinniaru3005** [comment]
Many of the Layer5 contributors and maintainers even get the opportunity to share their work at various conferences. Even that can be added as a recognition

**Review by eeshaanSA — COMMENTED** [review]
@leecalcote looks great.

**Comment by leecalcote** [comment]
@tinniaru3005, thanks. If you can add/commit your first comment (with Layer5 always capitalized), that'd be good. Your second comment is a maintenance nightmare. We have a hard time tracking all the talks and keeping them up to speed. The meshery/meshery readme needs this section deleted, because it is so far out of date. If you know of various talks, please add them to the list here - https://meshery.io/talks-and-presentations

**Comment by leecalcote** [comment]
@tinniaru3005 knowing that you might not be able to commit to this branch, I'll go ahead and merge and encourage you to go forth with a follow-on PR.

**Comment by tinniaru3005** [comment]
> @tinniaru3005 knowing that you might not be able to commit to this branch, I'll go ahead and merge and encourage you to go forth with a follow-on PR.

Sure @leecalcote I will update you on Tuesday.

**Pull request merged**
