### PR TITLE
solved the overflow for all screen resolutions - 5624

### LINKED ISSUE #5624: Page Header Section Content Overflow on Narrow Screens
### Description
When the viewport width is less than 788px, the content in the page-header-section overflows out of the container. This causes layout issues and negatively affects the user experience on smaller screens.

#### Steps to Reproduce
1. Navigate to: https://layer5.io/community/handbook/recognition
2. Resize the browser window to a width less than 788px.
3. Observe the page-header-section content overflow.

### Expected Behavior
The content should stay within the container boundaries on all screen sizes.

### Screenshots
Less than 789px

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by MUFFANUJ**
**Description**

This PR fixes #5624 

**Notes for Reviewers**
Earlier it was breaking for all the resolutions below 788px, made the changes in order to make it responsive for all the possible resolution from 375px to 788px, also checked the behaviour its working as expected.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fddafaaf56557e8ad999451bd086a72f3af47213 at: https://66853ee32b41ecf791db4862--layer5.netlify.app

**Comment by Ashparshp** [comment]
@MUFFANUJ Thanks for your initiative! Also, please note that we move in chronological order with issue assignments. Kindly wait to be assigned before working on an issue next time. We'll review your PR shortly. 🚀

**Review by Ashparshp — CHANGES_REQUESTED** [review]
Looks good! Could you shrink the font size a bit for smaller screens?

**Comment by MUFFANUJ** [comment]
> Looks good! Could you shrink the font size a bit for smaller screens?

Yeah sure will do it

**Comment by l5io** [comment]
🚀 Preview for commit 4919ca5da2accad889875cc2cfb565bc9ec63393 at: https://668abc71524ab7ba464c30e6--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@MUFFANUJ 
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by Ashparshp** [comment]
@MUFFANUJ, Anything to update?

**Pull request closed without merging**
