### PR TITLE
[Integration] show desc on hover

### LINKED ISSUE #3347: Show a brief description of integration on hover.
#### Current Behavior
No description on hover about the integration.

#### Desired Behavior
Show a brief description of integration on hover on page: /cloud-native-management/meshery/integrations.

#### Acceptance Tests

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
**Description**
Add a transition effect on hover showing integration name and a button to go to specific integration page.

image

https://user-images.githubusercontent.com/54144759/197153443-2d9810f3-996f-4f89-b761-8b6ee837a24a.mp4

**This PR fixes #3347** 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8240af830096a1f819e5b109e8598073debc4290 at: https://635262b6381fa01aca82843f--layer5.netlify.app

**Comment by sahilsuman933** [comment]
LGTM! 🚀

**Review by sahilsuman933 — APPROVED** [review]

**Review by sahilsuman933 — APPROVED** [review]

**Review by Nikhil-Ladha — COMMENTED** [review]
Looks good just a couple of items:
1. Always prefer to use `rem` instead of `px `.
2. The animation is something that I am a bit doubtful about if we should be showing that sudden jerk to the top and then scaling down slowly. It should rather be scaling down as soon as we hover, that jerk effect should be avoided.

**Comment by GaganpreetKaurKalsi** [comment]
@Nikhil-Ladha check if this looks good now.

**Comment by l5io** [comment]
🚀 Preview for commit 9826f8748444803ad37c10a220d02049c7ef5d8f at: https://63530291f605fc66be2e2889--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Not too shabby, @GaganpreetKaurKalsi 😄 And good feedback, @Nikhil-Ladha. I concur.

Please ensure that `cursor: pointer;` happens on hover of the cells. We seem to have lost this setting in this PR.

**Comment by GaganpreetKaurKalsi** [comment]
> https://63530291f605fc66be2e2889--layer5.netlify.app

Previously we had `cursor: pointer;` on cell because the whole cell/hexagon was wrapped in an anchor tag. Clicking on the hexagon led us to specific integration page. But now we have a **Learn More** button for that purpose. The cell doesn't have a click event now, **the button has**. 

So showing a cursor when we hover on the cell.....hmmm.

Am I making sense? Did I get the situation right? Or were you pointing something else? @leecalcote

**Comment by GaganpreetKaurKalsi** [comment]
> Not too shabby, @GaganpreetKaurKalsi 😄 And good feedback, @Nikhil-Ladha. I concur.
> 
> Please ensure that `cursor: pointer;` happens on hover of the cells. We seem to have lost this setting in this PR.

Previously we had `cursor: pointer;` on cell because the whole cell/hexagon was wrapped in an anchor tag. Clicking on the hexagon led us to specific integration page. But now we have a **Learn More** button for that purpose. The cell doesn't have a click event now, **the button has**. 

So showing a cursor when we hover on the cell.....hmmm. What say?

Am I making sense? Did I get the situation right? Or were you pointing something else? @leecalcote

**Comment by leecalcote** [comment]
Thanks for this explanation. The hyperlink on each cell should continue to be present. If not, and all that we are trying to do is to redirect the user to the full Integrations page, then the onhover animation should be disabled in this view, too.

**Comment by GaganpreetKaurKalsi** [comment]
> Thanks for this explanation. The hyperlink on each cell should continue to be present. If not, and all that we are trying to do is to redirect the user to the full Integrations page, then the onhover animation should be disabled in this view, too.

Maybe we can remove the **Learn More** button then and keep the hyperlink on the cell only. 
onHover the same animation can be present but just with the integration name, _NO button_. In future, when the API may support a description, then we can add a description here as well.

**Comment by leecalcote** [comment]
Your suggestion seems like it'll work, @GaganpreetKaurKalsi. Just prior to pressing forward: what to do about the stack of category filters? It would be nice to see more examples of what other sites have done in terms of providing an overview of their integrations.

**Comment by leecalcote** [comment]
https://layer5io.slack.com/archives/C015QJKUMPU/p1666441591395059?thread_ts=1655730260.479119&cid=C015QJKUMPU

**Comment by GaganpreetKaurKalsi** [comment]
> Your suggestion seems like it'll work, @GaganpreetKaurKalsi. Just prior to pressing forward: what to do about the stack of category filters? It would be nice to see more examples of what other sites have done in terms of providing an overview of their integrations.

I analysed some of the other sites with integrations. Most of them don't have categories, just a long grid of integrations with a search bar for ease. The ones which do have category list, don't have many categories. Most of them have the categories on the left side in form of list and the integrations on right side just like filters on any E-commerce platforms.

Below are some of the other examples that I could find which have similar implementation to the ones already explored. 
_You may click on the image to visit the respective site._

<a href="https://ghost.org/integrations/">image</a>
<a href="https://www.browserstack.com/integrations">image</a>
<a href="https://www.zoho.com/crm/integrations.html">image</a>
<a href="https://marketplace.zoho.com/app/crm">image</a>
<a href="https://www.pagerduty.com/integrations/">
image
</a>

I like the current UI of integrations though. If the category stack seems to be taking took much viewport space for you, we can reduce the margin between the category tabs or make the tabs smaller. The current category stack goes well with the Honeycomb structure. The category list won't get too long in future, right. For smaller screen we can give a dropdown of categories maybe.

Other approach that I could think of is showing only a few popular category filter tabs instead of all. We can have an other filter tab as well which can contain integrations from categories not listed in the filter tabs list(not popular categories).

P.S. Was this even the issue I was asked to put thoughts to. Feeling dumb.

**Comment by legendarykamal** [comment]
> > Thanks for this explanation. The hyperlink on each cell should continue to be present. If not, and all that we are trying to do is to redirect the user to the full Integrations page, then the onhover animation should be disabled in this view, too.
> 
> Maybe we can remove the **Learn More** button then and keep the hyperlink on the cell only. onHover the same animation can be present but just with the integration name, _NO button_. In future, when the API may support a description, then we can add a description here as well.

how about keeping the `Learn More` button + `cursor: pointer` on the cell too. I think that will prove to be a better approach considering the width of users .

**Comment by GaganpreetKaurKalsi** [comment]
> > > Thanks for this explanation. The hyperlink on each cell should continue to be present. If not, and all that we are trying to do is to redirect the user to the full Integrations page, then the onhover animation should be disabled in this view, too.
> > 
> > 
> > Maybe we can remove the **Learn More** button then and keep the hyperlink on the cell only. onHover the same animation can be present but just with the integration name, _NO button_. In future, when the API may support a description, then we can add a description here as well.
> 
> how about keeping the `Learn More` button + `cursor: pointer` on the cell too. I think that will prove to be a better approach considering the width of users .

Yeah! Datadog's site follows the same approach. So maybe we can too.

**Comment by GaganpreetKaurKalsi** [comment]
> So basically, the complete card should be clickable along with the `learn more` button, and that should be fine. (Check the card on the blog page for example).
> 
> Also, the scale-down animation that you implemented until this [preview](https://635262b6381fa01aca82843f--layer5.netlify.app/) should be retained but the jerk could be avoided (like the current one). It might not sound very clear, but I meant that we should be taking the better of both versions.

Will keep the `Learn More` btn. I am not very clear with the jerk you are talking about.

**Comment by Nikhil-Ladha** [comment]
When you hover over the card, the button, and the text pop suddenly and not smoothly. It should be smooth with the integration icon scaling down (slowly i.e, proportional to the speed of the text and button coming up) until it is invisible.

**Comment by l5io** [comment]
🚀 Preview for commit a306e82793f86e4163baeda3eecd73857e8dbf6c at: https://6363cb9fbcb51d0a5ebb0fe5--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Some great work here, @GaganpreetKaurKalsi. Let's see how this behavior feels in-action.

**Pull request merged**
