### PR TITLE
fixed text content issue

### LINKED ISSUE #5709: Visibility issues on What is Multi-Cluster Kubernetes?
### Description

There is some visibility issue on What is Multi-Cluster Kubernetes like this 
image

you can go to the page also 
'https://layer5.io/resources/kubernetes/what-is-multi-cluster-kubernetes' see the page in ``dark mode only``
This is specially for 

### Expected Behavior
Text Content should be visible in Dark becuase it is visible in ``light`` mode

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by akaBisht**
**Description**

This PR fixes #5709

**Notes for Reviewers**

In this PR, I fixed the syntax and explicitly added JSX tags to the k8s-multi-cluster.mdx file, which resolved the text color issue in dark mode.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cf8e2f50cac1d261955f2a989dd65a260227ae73 at: https://66a3b00fdab3a51817b19e1c--layer5.netlify.app

**Comment by akaBisht** [comment]
hey @sudhanshutech can you review this PR I just reworked on this issue.

**Comment by leecalcote** [comment]
Thanks, @akaBisht 😄

**Comment by l5io** [comment]
🚀 Preview for commit 8c138ff4210d4bede7695dbf0482611a7d4abaa4 at: https://66a4f2cc94ed98183fcd75f7--layer5.netlify.app

**Review by hargunkaur286 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit ad3c842f2d4a09c32df93f11c127667c0d0a126b at: https://66a5dcc69bd459dca6255f96--layer5.netlify.app

**Comment by Ashparshp** [comment]
@akaBisht Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by l5io** [comment]
🚀 Preview for commit 87b0d0533520bd9239a091168366b2f885101a5d at: https://66aaff26e7b358654f99bb15--layer5.netlify.app

**Comment by akaBisht** [comment]
hey @sudhanshutech can you review this PR.

**Pull request merged**
