### PR TITLE
feat: added meshery catalog badge to the  recognition section

### LINKED ISSUE #4209: [Add] Docker Extension & Meshery Catalog Badge on layer5.io
### Desired Behavior
Two new badges needed to be added to the [layer5.io](https://layer5.io/community/handbook/recognition) website, those are:

**Docker-Extension:**
- **Logo:** https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=13060%3A39569&t=BaXWaMzs5vb6MR88-1
- **Description:** awarded community members who make consistent and impactful contributions to the [Meshery Catalog](https://meshery.io/catalog) project in recognition and appreciation of their efforts.

**Meshery Catalog**
- **Logo:** https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=13060%3A39569&t=BaXWaMzs5vb6MR88-1
- **Description:** awarded community members who make consistent and impactful contributions to the Docker-Extension of meshery project in recognition and appreciation of their efforts.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**
Signed-off-by: Sambhav Gupta [sambhavgupta0705@gmail.com](mailto:sambhavgupta0705@gmail.com)

This PR fixes #4209 

**Notes for Reviewers**
- Added the meshery catalog bage on layer5.io

- image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [.] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 182fd4b11ff505918154135cd076324889e22d2b at: https://645df54281499666af8f6eb6--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Hi @sambhavgupta0705 , the PR looks good. Just follow the steps mentioned [here](https://github.com/layer5io/layer5/pull/4223/checks?check_run_id=13427701264) to fix the DCO issue.

**Comment by vishalvivekm** [comment]
@sambhavgupta0705 Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by sambhavgupta0705** [comment]
@vishalvivekm I have added it to the meetings-minute

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Comment by Nikhil-Ladha** [comment]
> Hi @Nikhil-Ladha ,resolved it but lighthouse test is failing

Yeah, that is a different issue and not related to this PR.

**Pull request merged**
