### PR TITLE
Added Community Member Vaibhav Malik

### LINKED ISSUE #4798: [Community] Member Profile: Vaibhav Malik
**Current Behavior**

@VaibhavMalik4187  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @VaibhavMalik4187 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @VaibhavMalik4187
- Twitter: 
- LinkedIn: [vaibhavmalik4187](https://www.linkedin.com/in/vaibhavmalik4187) 
- Meshery Cloud: [495185a6-7aa4-4c66-a7ff-2e5e7e7c9768](https://meshery.layer5.io/user/495185a6-7aa4-4c66-a7ff-2e5e7e7c9768) 
- Link to profile picture:[link](https://gitlab.com/uploads/-/system/user/avatar/10628053/avatar.png?width=400)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Layak-Ali**
**Description**
Added Vaibhav Malik's Profile as a community member

This PR fixes #4798

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6359bac912d09570548393039bf4b06d79c84347 at: https://64f25cf95cc9ab120445ab03--layer5.netlify.app

**Comment by VaibhavMalik4187** [comment]
LGTM

**Review by VaibhavMalik4187 — APPROVED** [review]

**Review by abhijeetgauravm — APPROVED** [review]
Looks Good @Layak-Ali 🚀

**Comment by Ghat0tkach** [comment]
@Layak-Ali 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Layak-Ali** [comment]
@Ghat0tkach i didn't see this so i was not able add the link before the meeting started. Can you merge it now ?

**Pull request merged**
