### PR TITLE
added call-out to layer5 discuss page

### LINKED ISSUE #1923: Add callout sections to join Layer5 Discussion Forum
**Current Behavior**
Currently, no indication to join the [Layer5 Discussion Forum](https://discuss.layer5.io/) is present on site.

**Desired Behavior**
Add a callout section to [Layer5 Discussion Forum](https://discuss.layer5.io/) (similar to Join the Community section present on [Community Page](https://layer5.io/community)), on the [Community Page](https://layer5.io/community) and [FAQs Page](https://layer5.io/company/faq).

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>
Thank you for helping with this @warunicorn19 

**Description**

This PR fixes #1923 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5a99bb15df97791b14ef7c93b217e4fb5f4a208b at: https://610e36e329cc91caaeba765c--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dd059d98cbade62cab1e8c5491653bcfb899d466 at: https://610e3edcf1508fd4939415e0--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
https://610e3edcf1508fd4939415e0--layer5ng.netlify.app/company/faq

**Review by Jashpatel1 — CHANGES_REQUESTED** [review]
@debo19 The section is not visible on smaller screens. Please make the required changes.
Screenshot from 2021-08-07 14-04-41
Screenshot from 2021-08-07 14-05-03

**Comment by warunicorn19** [comment]
@Jashpatel1 is the design okay?

**Comment by leecalcote** [comment]
> @Jashpatel1 is the design okay?
I am on my mobile as well and can’t tell yet.

**Comment by warunicorn19** [comment]
Yes we need to work on getting it mobile friendly.

**Comment by Tanuj22** [comment]
I am not sure about the design. It stands out from the rest of the site (especially the button) :sweat_smile:

**Comment by debo19** [comment]
@Tanuj22 okay any suggestions? we'll keep looking for something better meanwhile

**Comment by leecalcote** [comment]
@debo19 Given our past conversations, I think you're on the right track here. Let's give this a shot with the last couple of changes that we discussed on this past Monday's call.

**Comment by debo19** [comment]
@leecalcote yup I'm working on it, I'll get this done by today

**Comment by l5io** [comment]
🚀 Preview for commit eedc0a2b314dc8bb5ffa720c4500e5b746d040da at: https://6115872fbed032290eca480b--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
https://6115872fbed032290eca480b--layer5ng.netlify.app/company/faq

**Comment by leecalcote** [comment]
Thanks. this button presses downward, while the other buttons lift upward. this button cause other elements to move, jolting the page a bit. Will you reuse the same animation from the other buttons exactly, but replace it with the green that you're using instead?

The overall button itself has a white background, but the container that it is in has an off-white background.

**Comment by l5io** [comment]
🚀 Preview for commit 644862663319f8a752acbb7fe5fe0eedafcafc0a at: https://61163f2316db1ae0b4efd5db--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3546a3f0b8dd99fcad8e6ea9a81d35dea68132fe at: https://611654d67c273108ae750578--layer5ng.netlify.app

**Comment by debo19** [comment]
Hey @leecalcote I made the changes. I hope it looks better now .

**Review by Jashpatel1 — COMMENTED** [review]
@debo19 Please reduce this space, and then we are good to go.
image

**Comment by l5io** [comment]
🚀 Preview for commit 071a9d8797e8286129cbbadbb2404fb1172e12de at: https://611aa1502b1c681bcc2dac5d--layer5ng.netlify.app

**Comment by Tanuj22** [comment]
@Jashpatel1 ^^

**Review by Jashpatel1 — APPROVED** [review]
@debo19 We will go ahead with this for now. Please create another issue for adding a smaller version of callout to blog page.

**Pull request merged**
