### PR TITLE
fixed Slider Double Dot issue #4393

### LINKED ISSUE #4393: Fix Slider double dots in Blog Section
### Description

Another issue on [page](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma), is the bottom of the page in the related blog section slider dots on mobile have two dots for every li tag of dots. 

@8rxn 
- [X] I would like to work on this issue. 

### Expected Behavior

Screenshot (69)

### Screenshots

Screenshot (65)
Screenshot (64)

### Solution
adding code to `relatedPosts.style.js`
Screenshot (70)

### Environment:
- Host OS: Windows
- Browser: All

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vaibhav-xt**
**Description**

This PR fixes #4393 

**Notes for Reviewers**
Fixed slider double dot issue.

#### Screenshot 
Screenshot (72)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6547a3f95cc243f8846afb2dd0d22a36c3051658 at: https://648d86e578649d706ba5b9dc--layer5.netlify.app

**Comment by vaibhav-xt** [comment]
@8rxn @Chadha93 

please have a look at my small pr whenever possible 😜.

**Review by hirentimbadiya — APPROVED** [review]
Look Good to me 👍🏻 @vaibhav-xt

**Comment by leecalcote** [comment]
Thanks, @vaibhav-xt and @hirentimbadiya

**Comment by vaibhav-xt** [comment]
Thankyou @leecalcote.
It was my first pull request 😀 got merged.

**Pull request merged**
