### PR TITLE
feat: careers, programs and internships page made dynamic

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
We have more programs that needs to be added, right?
Also, the Full time opportunities section is missing only the header is there.

**Comment by Tanuj22** [comment]
> We have more programs that needs to be added, right?
> Also, the Full time opportunities section is missing only the header is there.

Yes. For both of them individual issues can be created.

**Comment by Nikhil-Ladha** [comment]
Means, the data has not been migrated yet?

**Comment by Tanuj22** [comment]
Yeah

**Comment by Tanuj22** [comment]
Can you give an example of the text color where is not correct?

**Comment by Nikhil-Ladha** [comment]
> Can you give an example of the text color where is not correct?

In the programs page, the text should be black, but in some places its still gray.

**Comment by Nikhil-Ladha** [comment]
Actually, not only there many places the text is gray, but it should be black, right? Like the Digital Marketing Internship page.

**Comment by Tanuj22** [comment]
Yes, it should be black. There might be some global style messing this up. Checking now

> Actually, not only there many places the text is gray, but it should be black, right? Like the Digital Marketing Internship page.

**Comment by Nikhil-Ladha** [comment]
It should be `Home > Careers`
Screenshot_20200929-203915__01

This part can be removed for this page and other consequent pages.
Screenshot_20200929-203857__01__01

**Comment by Tanuj22** [comment]
@Nikhil-Ladha Please take a look

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good ✅

**Pull request merged**
