### PR TITLE
Infinite Carousel : Partner images size fix

### LINKED ISSUE #3476: "Collaborating with" section logos overflowing.
#### Description
"Collaborating with" section logos overflowing.
Screenshot 2022-11-28 171221

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gurpreet-legend**
**Description**

This PR fixes #3476

In reference to PR: #3496 

**Notes for Reviewers**
The image size is now fixed. Now, the infinite carousel looks like this:

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@gurpreet-legend can you please take care of the merge conflicts so that we can have a deploy preview post that?

**Comment by gurpreet-legend** [comment]
> @gurpreet-legend can you please take care of the merge conflicts so that we can have a deploy preview post that?

@Nikhil-Ladha sure, will do asap

**Comment by leecalcote** [comment]
I resolved the conflict (hopefully, correctly).

**Comment by l5io** [comment]
🚀 Preview for commit fad875c607d31cd0f6204f2370cd7b5cb39c0ff0 at: https://63e8027616ba547715e66501--layer5.netlify.app

**Comment by leecalcote** [comment]
Uh-oh:

Screenshot 2023-02-11 at 3 06 38 PM

**Comment by l5io** [comment]
🚀 Preview for commit d810f679e308b6deb360a0354a4f24326c67f81a at: https://63e8996410adff4e33180df2--layer5.netlify.app

**Comment by gurpreet-legend** [comment]
@eeshaanSA , @leecalcote build is complete and conflicts have been resolved, you can check

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Increase the spacing to be the same as that of what we have now, such that only one iteration of a logo is visible at once.

**Comment by Chadha93** [comment]
// @gurpreet-legend

**Comment by gurpreet-legend** [comment]
> // @gurpreet-legend 

Will fix this @Chadha93 soon

**Comment by gurpreet-legend** [comment]
@Nikhil-Ladha, @Chadha93 Spacing fixed it is ready to merge :)

**Comment by l5io** [comment]
🚀 Preview for commit 4f7bb410609b20a2d6725c9d95ebe28bdba84aab at: https://63f66a568e45730080b2466c--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
COOL @gurpreet-legend :1st_place_medal:

**Pull request merged**
