### PR TITLE
Added Drawer section

### PR DESCRIPTION
**Pull request by NishantSinghhhhh**
Description

This PR adds comprehensive documentation for the Drawer component, detailing its purpose, usage, and various configurations. The documentation covers key aspects like types of drawers (Temporary, Permanent, Modal, and Mini-Variant), functionality, styling guidelines, and common use cases, providing developers with clear insights on how to implement and customize Drawer components effectively in the application.

Changes Include:

Explanation of Drawer types and scenarios for each.
Guidelines on content structure within drawers to ensure usability.
Example implementations for Temporary, Permanent, Modal, and Mini-Variant drawers.
Best practices for accessibility and consistency with other UI elements.
Notes for Reviewers Please review the usage examples and descriptions provided for clarity and accuracy. Suggestions for any additional use cases or adjustments in styling recommendations are welcome.

[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)

 Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit aa6263db1da0c05cae84110f96e74aab61dfa370 at: https://671e05d9fae585e97a1de7a6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1e2a4fb0c34f0ed536fe5a834681a1099c49ea5f at: https://671e13b9decd372fe435b7c4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c960d4586f5c8c5bcb8b33570891b2e71b060352 at: https://671e222c7288793ae1d0b1e4--layer5.netlify.app

**Comment by NishantSinghhhhh** [comment]
@nebula-aac , @SAHU-01

**Comment by l5io** [comment]
🚀 Preview for commit 09fbb9529ac331b55da2bd3118ed93b81220430f at: https://671e41ed92866d27759a0578--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@NishantSinghhhhh 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by NishantSinghhhhh** [comment]
@sudhanshutech @vishalvivekm z can you review the PR

**Comment by l5io** [comment]
🚀 Preview for commit cce9d9dd62a56e2810839546556967af3c6e84a1 at: https://6722257b3b8ac4955f7afd1f--layer5.netlify.app

**Comment by leecalcote** [comment]
Merge conflict

**Comment by l5io** [comment]
🚀 Preview for commit c78ed7b813aa6cbc52c8484cca76581e20b4b693 at: https://672f2313fd824ef52bf2a082--layer5.netlify.app

**Comment by NishantSinghhhhh** [comment]
@Sudhanshutech, @VishalVivekm, @SAHU-01

Sir/Ma'am, I've implemented the requested changes. However, further reduction of the code visible to fellow developers may compromise its readability and structure. I've optimized it as much as possible without impacting clarity.

Let me know if there's anything more specific you'd like me to adjust.

**Comment by l5io** [comment]
🚀 Preview for commit 1063b9d2661ed15b51effd8369bef2a2c28ded5d at: https://672f379e45d9fc18914651ce--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0d6b9978537e2522c220c419a8800779df366397 at: https://672f3fd3e3f33713fde4a32a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9d2d35fa2238cc6af94f2748a6afaef14231d7fa at: https://673b3ca0cbd35e1853a778a5--layer5.netlify.app

**Comment by Vidit-Kushwaha** [comment]
Hi @NishantSinghhhhh  Facing issues merging your PR in Sistent?

We are conducting a special tutorial on this Monday, December 16, 2024, at 7 AM Central (6:30 PM IST) in the website meeting. 

Get more information: [here](https://discuss.layer5.io/t/kickstart-your-open-source-journey-with-sistent-a-hands-on-tutorial/6304)

:busts_in_silhouette: Get involved:

- Explore the [Newcomers’ Form.](https://layer5.io/newcomer/)
- Check out the [meeting minutes.](https://bit.ly/2XK4eQV)
- Join the [community calendar](https://layer5.io/community/calendar#meetings).

Don’t miss out. 🚀

**Comment by sudhanshutech** [comment]
@NishantSinghhhhh please reopen them when you are back to complete them. Thanks

**Pull request closed without merging**
