### PR TITLE
Ealvarez968/event page

### PR DESCRIPTION
**Pull request by ealvarez968**
**Description**
Add CNCF Virtual Ambassador Day to the layer5.io/events page
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Nice work here. Thanks @ealvarez968 . Do you mind singing off your commits to just dodge the DCO checks?

**Comment by ealvarez968** [comment]
> 
> 
> Nice work here. Thanks @ealvarez968 . Do you mind singing off your commits to just dodge the DCO checks?

Thank you! I appreciate. I forgot to sign my first commit can you help me how to do that? Also I didn't have my signature verified maybe that was the problem.

**Comment by leecalcote** [comment]
@ealvarez968 thanks for giving the commit signing a try. Here are one-time instructions for commits in this PR - https://github.com/layer5io/layer5/pull/950/checks?check_run_id=1235612032. And here are instructions for [making signing an implicit activity while performing a commit.](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).

Let's not let the commit signing here stand in the way of your work getting merged, though.

**Comment by leecalcote** [comment]
@ealvarez968, please try again and even if your commits aren't signed off, we'll accept and move forward.

**Comment by ealvarez968** [comment]
Thanks @leecalcote , I appreciate the tip.

**Comment by leecalcote** [comment]
Absolutely, @ealvarez968. `git` is a pain in the rear.

**Pull request closed without merging**
