### PR TITLE
[Community] Added Hersh Dhillon's profile on member page

### LINKED ISSUE #2613: [Community] Member Profile: Hersh Dhillon
**Current Behavior**

@hershd23 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize hershd23 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: hershd23
- Twitter: 
- LinkedIn: 
- Link to profile picture: https://drive.google.com/file/d/1CJrziXlIT2RTdWOG0pRCcT8aVQMy1BXk/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sidd-oo**
Signed-off-by: sidd-oo <sahoosiddharth3@gmail.com>

**Description**
Added Hersh Dhillon's profile on a member page

This PR fixes #2613 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhijay007** [comment]
@hershd23 review required :)

**Comment by l5io** [comment]
🚀 Preview for commit 56654358ea2f7ce171b296118edf749bfbfc1511 at: https://6218bbb6868ca69e7dd12ef2--layer5ng.netlify.app

**Review by Abhijay007 — APPROVED** [review]
Code wise LGTM !! 

Content-wise waiting for @hershd23 review on it

**Review by hershd23 — APPROVED** [review]
LGTM thanks @sidd-oo !

**Review by warunicorn19 — APPROVED** [review]
Looking good, thank you @sidd-oo

**Pull request merged**
