### PR TITLE
Added new member - Vihas Makwana

### LINKED ISSUE #5215: [Community] Member Profile: Vihas Makwana
**Current Behavior**

@VihasMakwana has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @VihasMakwana as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @VihasMakwana
- Twitter: 
- LinkedIn: [/in/makvihas/](https://www.linkedin.com/in/makvihas/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by IrfanSalim**
**Description**

This PR fixes #5215 

**Notes for Reviewers**
Added the new member profile using the template.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yay, @VihasMakwana! 🎈

**Comment by l5io** [comment]
🚀 Preview for commit 3d8d852edb5f2af313956555998ccf98b78dc963 at: https://658362082473eb684c87ec52--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
@VihasMakwana you might like to review it!

**Comment by VihasMakwana** [comment]
LGTM brothers😄😄

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
