### PR TITLE
fix: add modified regex for the firstName and lastName

### PR DESCRIPTION
**Pull request by codingmickey**
Allows
- Multi-word names
- Names with -
- Special language characters like ā

**Description**

This PR fixes https://github.com/layer5io/layer5/issues/4498#issuecomment-1638881157 and https://layer5io.slack.com/archives/C01AFD2D547/p1690552378201349?thread_ts=1690550310.858499&cid=C01AFD2D547

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 85f005afb069901007ab6d82118b04b57667cf52 at: https://64c6c1bca105033636091be3--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @codingmickey 


Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Make sure to attend tommorow's website call for review

**Review by leecalcote — APPROVED** [review]
I like it. Good work, @codingmickey 👍 

Do you have a similar update inbound to play.meshery.io?

**Comment by leecalcote** [comment]
I'll see you on the Websites call this week.

**Comment by codingmickey** [comment]
> I like it. Good work, @codingmickey 👍
> 
> Do you have a similar update inbound to play.meshery.io?

Yupp sure, expect a PR by EOD

**Pull request merged**
