### PR TITLE
[Enhancement] Feat : Added inactive banner

### LINKED ISSUE #4621: [Enhancement] "Inactive" Ribbon On Inactive members profile.
Inactive member profiles need an “INACTIVE” ribbon and black and white version of their photo on <https://layer5.io/community/members>. 

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1690313706330899?thread_ts=1690313706.330899&cid=C015QJKUMPU)

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #4621

**Notes for Reviewers**
Added Inactive Banner for inactive member profiles
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
I sticked to using px instead of rem as the banner on HPE also preferred px .

**Comment by l5io** [comment]
🚀 Preview for commit 5536d54e0e48ce17aa8ad67df6866e54c5724988 at: https://64c0e087742e2d40f784b4d3--layer5.netlify.app

**Review by thisiskaransgit — COMMENTED** [review]
@Ghat0tkach, thanks for this, make the ribbon grayed out too, please.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach, thanks for this, make the ribbon grayed out too, please.

thank you @thisiskaransgit  , Actually I started with  the grayed out ribbon but it looked plain simple, that's why I switched to gradient. 
image

Shall I change it back to gray??

**Comment by thisiskaransgit** [comment]
@Ghat0tkach, yeah keep them grayed out.

**Comment by l5io** [comment]
🚀 Preview for commit 60ede47525df9c7aef1f11e2e174c474afa4e441 at: https://64c123a2a88d290d220ca93e--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
@thisiskaransgit  , done 🙌

**Comment by leecalcote** [comment]
Don't highlight their inactivity with a green ribbon. Make the ribbon gray as well.

In fact, please use a different ribbon, going horizontally across the card.

**Comment by leecalcote** [comment]
Looking good, @Ghat0tkach 👍 

How is working in mobile view? Just fine?

**Comment by leecalcote** [comment]
Kind, sir, will you also use the same gray filter on the single member page for inactive profiles with the same ribbon, too?

**Comment by Ghat0tkach** [comment]
> Kind, sir, will you also use the same gray filter on the single member page for inactive profiles with the same ribbon, too?

@Lee , yes its fully responsive

and I'll add the filter along with ribbon on the single-member profile as well Sir

**Comment by leecalcote** [comment]
Thank you. Moving forward with this first step...

**Pull request merged**
