### PR TITLE
Add program button hacktoberfest

### LINKED ISSUE #888: [Programs] Add button for hacktoberfest to list of programs
**Current Behavior**
On the front page of https://layer5.io is listed four program that Layer5 participates in (see screenshot)

**Desired Behavior**
The https://layer5.io/programs/hacktoberfest should be represented by a button as well.

**Screenshot**
Screen Shot 2020-10-01 at 7 52 45 PM

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by EdgeKing810**
**Description**

This PR fixes #888 

**Notes for Reviewers**

I'm not being able to find an svg logo however.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@EdgeKing810 if you could just fix the DCO issue, then we are good to go.

**Comment by jesuslerma** [comment]
Hi @EdgeKing810 the icon is not present in the preview, I'm not sure if this is an issue for the preiew or the image is missing. Can you confirm that this works fine on your local?

image

**Comment by EdgeKing810** [comment]
@Nikhil-Ladha I'll fix the DCO issue in some - minutes. @jesuslerma yes, my bad, I'll fix it in my next commit.

**Comment by EdgeKing810** [comment]
Made the required changes.

**Review by jesuslerma — APPROVED** [review]
LGTM!

**Review by leecalcote — APPROVED** [review]
Excellent. Thank you, @EdgeKing810. 👌

**Comment by leecalcote** [comment]
Haha! 🎖 @EdgeKing810

**Pull request merged**
