### PR TITLE
💄Nighthawk Cards Hover Box Shadow Improvements💄

### LINKED ISSUE #4988: Styling Inconsistency on Nighthawk Page: Cards Missing Green Layout and Hover Effect
### Description
Screenshot 2023-10-01 024015

The screenshot above is from https://layer5.io/. As you can see, for every card, there is a green color layout that changes to white on hover.
However, when you navigate to the Nighthawk page, the cards don't have the above colors.

#### Steps to Reproduce
- Navigate to https://layer5.io/projects/nighthawk
- Scroll down to "Distributed Performance Management"
- You can see the screenshot below

Screenshot 2023-10-01 024930

### Expected Behavior

- The layout should be green in color, and on hover, it should change to white color.

### Environment:
- Host OS: Windows
- Browser: Chrome, Brave,Edge

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ojasaklechayt**
**Description**
Added the hover shadow color

This PR fixes #4988 

**Notes for Reviewers**
Please consider this in Hacktoberfest 2023

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1e7b2c2154458d921ae7adbeca6f9065925851d2 at: https://6519436e58a2273386a47204--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dbc605eb74e49717199b722632ed7f1a7a477eae at: https://651948f92e43b23cc03939f4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7495c8f648347f55df46869a0034e8895e9f2e99 at: https://65194d6d08627f3c586722ad--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by Mohith234** [comment]
Closing as the issue is not planned.

**Pull request closed without merging**
