### PR TITLE
Improved typo mistakes

### PR DESCRIPTION
**Pull request by Dnyaneshvn**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 533e8ff9d852905fb5c1d30efd1e1d446c534e42 at: https://6484be2bf1e5e10b63fd98a5--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thanks @Dnyaneshvn.
Please avoid making direct PRs in future. Creating an issue first and then going ahead with the fix is ideal.

**Review by vishalvivekm — APPROVED** [review]

**Comment by Dnyaneshvn** [comment]
@vishalvivekm Yes, but last time I've been assigned to the issue that was created by me but someone came and directly created PR for that issue :)
from now onwards, I'll make sure to create the issue first!

**Comment by Shivam-AfA** [comment]
> @vishalvivekm Yes, but last time I've been assigned to the issue that was created by me but someone came and directly created PR for that issue :)

@Dnyaneshvn This is also not a good practice, someone must have pointed out this to that contributor. Let's not let such practices of other contributors affect our own practices. 😀

BTW, where do these typos appear on the website?

**Review by NavedtheDev — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]
Thank you @Dnyaneshvn

**Pull request merged**
