### PR TITLE
Gatsby: Updated the site to Gastbyv4

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Updated the site to the latest Gatsby version, i.e, `4.19.2`
Deferred Static Generation & Parallel Query Running are the highlights of this release which aims to reduce build time by a huge margin. Read more about it [here](https://www.gatsbyjs.com/docs/reference/release-notes/v4.0/)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c3e9a440cc4a9ab35ecd14562f0472d195448776 at: https://62e2e6bd62d6ee03e245c7e7--layer5.netlify.app

**Review by debo19 — COMMENTED** [review]
Some Blog posts are showing ([example](https://62e2e6bd62d6ee03e245c7e7--layer5.netlify.app/blog/istio/service-mesh-istio-patterns-for-multitenancy)) while some are not available ([example](https://62e2e6bd62d6ee03e245c7e7--layer5.netlify.app/blog/community/lfx-experience-at-layer5-pranav-singh)). Same for `resources`, `news` and `events`.

**Comment by Nikhil-Ladha** [comment]
Ok, I think I know what is happening let me check.

**Comment by Nikhil-Ladha** [comment]
So, the issue is that the pages that are not shown are actually deferred in build time and should be generated when the user queries for it. This is what DSG is, but the catch here is DSG requires `gatsby serve` running in a NodeJs env from where the site is hosted or Gatsby Cloud, otherwise, the deferred pages won't be rendered dynamically when the user requests them.

This means we won't be able to utilize the DSG feature in our site ☹️

**Comment by l5io** [comment]
🚀 Preview for commit 8672622ee21e2e4df3c4551bfa8b7072bcaeee78 at: https://62e37fc092136d4aa87cfc51--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Looking fine now @debo19

**Comment by leecalcote** [comment]
Deferred Static Generation primarily affecting the length of build time, right?

**Comment by Nikhil-Ladha** [comment]
> Deferred Static Generation primarily affecting the length of build time, right?

Yeah

**Review by debo19 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
