### PR TITLE
Updates for some projects

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #
I have updated following pages

1. /projects/image-hub
2. /projects/service-mesh-interface-conformance
3. /projects/service-mesh-performance
4. /service-mesh-landscape

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by chinmaym07** [comment]
@Nikhil-Ladha  please do check Join Community on /projects/service-mesh-performance . 
The comment & design of that page on figma both differ . So I have adjusted it .please do look.

**Comment by l5io** [comment]
🚀 Preview for commit 7df172f12f5794d4b564757ee2ecce45ed815925 at: https://604712e80b8a775c61cfe7e7--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
This is fine, just make the `max-width` to 100% only for this page.
Also, can you please add the CNCF logo, in the backdrop just above the youtube videos on the right end? As per the Figma design.

**Comment by l5io** [comment]
🚀 Preview for commit c5410d8a85f8466b9246c3823d4938324d4d5b3b at: https://604723e60b8a776edacfe60e--layer5ng.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
