### PR TITLE
Made changes in fronted for uploading Signed-off-by: Paramjeet Kaur p…

### LINKED ISSUE #5477: [Bug]: The community onboarding form has bugs on the profile picture and twitter profile section.
### Description
1. After the renaming of Twitter to X, the profile links now start with ‘x.com’ when you try to enter that in the form, it shows invalid. 
2. The profile picture component is a text input and should be changed to an upload component. 
### Expected Behavior
1. The twitter profile section accepts both twitter.com and x.com links
2. The profile picture component is updated to allow uploading of pictures

### Screenshots
IMG_2225

IMG_2224

### Environment:
- Host OS:
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by kauxp**
…aramjeetkaur4326@gmail.com

**Description**

This PR fixes #5477
This pr solves the second unsolved issue, which was about uploading images from the local system.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 31878102b88ec6478489c7c8ca9533e0e4147fc5 at: https://66b0c0d00e15abcbbb459b91--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@kauxp please see the comment in issue please. And also update the pr with proper message that what changes you have added or introduced. And please present this into website meet

**Comment by kauxp** [comment]
okay, I will do so

**Comment by Ashparshp** [comment]
@kauxp Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
@kauxp, Any luck?

**Comment by vishalvivekm** [comment]
Thank you for your efforts @kauxp.
We'll be sticking to what we have in place, for now.

**Pull request closed without merging**
