### PR TITLE
[NG] Added subscribe card

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Good to see this coming through. 👍 A few styling tweaks still in the works, I'm sure. Looking good so far.

**Comment by leecalcote** [comment]
Good to see this coming through. 👍 A few styling tweaks still in the works, I'm sure. Looking good so far.

Screen Shot 2020-09-24 at 1 26 23 PM

**Comment by Nikhil-Ladha** [comment]
I think in mobile view the crane's image size, can be reduced a bit. What say?

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good, but we may want to think about keeping the crane logo in the mobile view later on.

**Pull request merged**
