### PR TITLE
Added Rodolfo to the list of contributors

### LINKED ISSUE #1078: [NG] Community: Recognizing Rodolfo Martínez as a Contributor and Community Member
**Current Behavior**
@ramrodo has been a consistent contributor and community member.

**Desired Behavior**
A profile for @ ramrodo should be created and visible on `/community/members` on both the next-generation layer5.io site (`layer5-ng` branch).

- Github: https://github.com/ramrodo
- Twitter: https://twitter.com/ramrodo
- Profile picture: https://rodomar.mx/assets/images/profile-2.jpg	 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by shivam-51**
Signed-off-by: shivam-51 <shivamhere247@gmail.com>

**Description**

This PR fixes #1078

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Looks good to me. Thanks @shivam-51

**Comment by leecalcote** [comment]
@ramrodo, over to you for review. 👍

**Comment by ramrodo** [comment]
> @ramrodo, over to you for review. +1

@leecalcote Looks good! Thanks for this proposal

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈 Looking good, @ramrodo 😄

**Review by leecalcote — APPROVED** [review]
Thank you, @shivam-51. Good work. 💯

**Comment by leecalcote** [comment]
Pretty cool, @shivam-51 😎

**Pull request merged**
