### PR TITLE
Fix: #3922 Footer is hiding underneath the keyboard in mobile view #3922

### LINKED ISSUE #3922: Footer is hiding underneath the keyboard in mobile view
### Current Behavior

Footer is hiding underneath the keyboard in mobile view

https://user-images.githubusercontent.com/75848598/223537343-63cfebcf-ed05-4808-964a-ac62d5beb841.mp4

### Expected Behavior

 [discuss.layer.io](https://discuss.layer5.io/) Footer should be pushed up when keyboard is open

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ykumar1415**
**Description**

This PR fixes #3922

**Notes for Reviewers**
I made some changes so that when the input box will be active then it will increase the height and when the input box will be inactive then it will become as it previously was.
I have tested these changes in all below mobile screens : 
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4e89aa95f407507184bafc9b26e788cdadf282a1 at: https://6496dd2e93a1cb55d6b1497f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f5375602c459b90066b7ed18ae0b5def3412ce39 at: https://6496ea40991e3f5d66e56f5a--layer5.netlify.app

**Comment by duckling69** [comment]
@Ykumar1415 I think issue is specific to discuss.layer5.io not layer5.io could you please make changes [here](https://github.com/layer5io/layer5/tree/46933ab135682201ad61fb70c2d7be4ec40beeb9/src/assets/discuss) would be great if you can implement footer similar to layer5.io

**Review by duckling69 — CHANGES_REQUESTED** [review]
@Ykumar1415 I think issue is specific to discuss.layer5.io not layer5.io could you please make changes [here](https://github.com/layer5io/layer5/tree/46933ab135682201ad61fb70c2d7be4ec40beeb9/src/assets/discuss) would be great if you can implement footer similar to layer5.io

**Comment by Ykumar1415** [comment]
ok @duckling69 i will make the changes on discuss page and check for the same .

**Comment by vishalvivekm** [comment]
@Ykumar1415 Let's discuss thin on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would

**Comment by Ykumar1415** [comment]
> @Ykumar1415 Let's discuss thin on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would

@vishalvivekm I have added the topic.

**Comment by l5io** [comment]
🚀 Preview for commit ad30b5d24cf7e338f8474c5f815747843e8c293f at: https://649962b9991e3f231ae572a6--layer5.netlify.app

**Comment by leecalcote** [comment]
@Ykumar1415 it's great to see the diligence that you've put into this testing. 👏

**Comment by Ykumar1415** [comment]
Thanks @leecalcote i am making these changes to discuss page because the discussion page only shows this problem.

**Comment by vishalvivekm** [comment]
> I have tested these changes in all below mobile screens :

@Ykumar1415 do post a video showing the behaviour after the changes you've made.

**Comment by Ykumar1415** [comment]
@vishalvivekm i will post video here today.

**Comment by leecalcote** [comment]
@vedp will you help review?

**Comment by Ykumar1415** [comment]
@vishalvivekm @leecalcote @duckling69 the below is the video after my changes.
@duckling69 told me to make changes only in discussion page but when we go discussion page it donot run in local environment it go to https://discuss.layer5.io/ so i can't see the local changes on it. I was thinking that the same footer will be used in all pages that's why i have made changes on footer component of layer5.
[Screencast from 04-07-23 07:08:52 AM IST.webm](https://github.com/layer5io/layer5/assets/97088265/9b15fe70-7111-4e47-a754-496e120877f7)

**Comment by vednp** [comment]
> @vednp will you help review?

Yeah sure

**Review by vednp — CHANGES_REQUESTED** [review]
@Ykumar1415 Your changes are not reflected on discuss.layer5.io page. Please make changes on Layer5 community's [discussion forum](https://discuss.layer5.io)

**Comment by leecalcote** [comment]
@vishalvivekm can’t help explain how changes are migrated to the discussion forum

**Comment by Ykumar1415** [comment]
@leecalcote when i tried to produce this issue in discuss page then discuss page is working fine. the below is the video for different mobiles : 
[Screencast from 04-07-23 04:04:26 PM IST.webm](https://github.com/layer5io/layer5/assets/97088265/7f43038a-b4ba-4002-b50a-1b09ab2abd8d)
[Screencast from 04-07-23 04:05:33 PM IST.webm](https://github.com/layer5io/layer5/assets/97088265/5a394a45-1690-40fc-8f90-e4980db712a9)

**Comment by samyakshah3008** [comment]
@Ykumar1415  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by Ykumar1415** [comment]
> @Ykumar1415 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

@samyakshah3008 i have added.

**Comment by Chadha93** [comment]
@Ykumar1415 Merge conflicts to resolve....

**Comment by Ykumar1415** [comment]
> @Ykumar1415 Merge conflicts to resolve....

@Chadha93 this issue is not a valid issue. I also discussed about it in website meeting.

**Comment by thisiskaransgit** [comment]
@vishalvivekm, please check the validity of this PR, (forum-related changes)

**Pull request closed without merging**
