### PR TITLE
Cdk8s white logo changed as per requirement 

### LINKED ISSUE #3403: [Integrations Page] Need a better darkmode logo for CDK8S
#### Description

image
image

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sam1code**
**Description**

This PR fixes #3403

**Notes for Reviewers**

Screenshot from 2022-12-23 04-45-04

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 554aff9840fd983bff94728f998513c4152a376b at: https://63a4e8b5412ebc005fb53720--layer5.netlify.app

**Review by UtkarshMishra12 — CHANGES_REQUESTED** [review]
@sam1code  Can you please change the color of the K8s from blue to black? That will be best for maintaining similarity with others.

**Comment by leecalcote** [comment]
> @sam1code Can you please change the color of the K8s from blue to black? That will be best for maintaining similarity with others.

Generally, this ai a good ask, @UtkarshMishra12. In this case, since this version is the official white version of the cdk8s logo, we're probably best to stick with it (even if it isn't the prettiest).

**Review by leecalcote — APPROVED** [review]
Thank you, gents!

⚠️ Please note that unless this SVG is pasted into the Integrations spreadsheet, it will be overwritten by the daily update.

**Comment by sam1code** [comment]
👍

**Comment by leecalcote** [comment]
Let's merge after you've confirmed that the spreadsheet is updated.

**Review by eeshaanSA — APPROVED** [review]
Lgtm🚀

**Comment by leecalcote** [comment]
@sam1code we haven't heard back from you here. There's a real pattern of on and (mostly) off engagement in your activity. Please take a moment to complete the work here, by updating the source spreadsheet. Not hearing from you by end of day on Wednesday, let's go ahead and close out this PR. // @UtkarshMishra12 @Shivam-AfA

**Comment by sam1code** [comment]
Sorry @leecalcote I don't have any Idea where to update so I thought this might be some internal work and someone is doing those stuff. Sorry for that

**Comment by Nikhil-Ladha** [comment]
Please fix the merge conflict and we are good to merge this PR @sam1code

**Comment by eeshaanSA** [comment]
@sam1code its almost done :smiley: 99.9% to be precise. Get that 0.1%, and let's get this merged.

**Comment by l5io** [comment]
🚀 Preview for commit e925c29e3ab6ab0b5374bffb1c00ff2deab9895b at: https://63cc26000fb8da330302fb08--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 99a1253ad114a2f1f45ff6d323894c9607d9daca at: https://63d7cd57fde09a23f1cb573e--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b248993e26db8234b93cee6c373852864b276520 at: https://63d9600f0fe865149c16734c--layer5.netlify.app

**Comment by leecalcote** [comment]
PR abandoned. Closing.

**Pull request closed without merging**
