### PR TITLE
"Try Meshery" Button Alignment Fix 

### LINKED ISSUE #2386: [Navigation] "Try Meshery" button not middle-aligned vertically on window size larger than 1550px
**Description**
The primary call to action button in the https://layer5.io site is a "Try Meshery" button in the upper righthand corner. These screenshots document its behavior at different window sizes.

Window size < 1550px:
Screen Shot 2021-11-29 at 8 18 19 PM

Window size > 1550px:
Screen Shot 2021-11-29 at 8 16 09 PM

**Expected Behavior**
This button should be vertically-centered at larger window sizes.

**Environment:**
- Host OS: macOS
- Browser: Safari and Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**

i) I changed the default CSS style of Try Meshery Button. 
ii) Added round brackets around props (it was automatically done by the vs code extension)

This PR fixes #2386

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sahilsuman933** [comment]
@toth2000  Could you please review this pull request!

**Comment by l5io** [comment]
🚀 Preview for commit 3d9d9c59b605e7c810bfb21090ddc44ad57b348e at: https://61a646cbe1850a33b485fe62--layer5ng.netlify.app

**Review by toth2000 — APPROVED** [review]
Looks good to me. Thanks, @sahilsuman933 🚀

**Comment by sahilsuman933** [comment]
@toth2000  Okay Bhaiya <3

**Comment by leecalcote** [comment]
Thanks for this, @sahilsuman933 👍 and for the review, @toth2000 ✔️

**Comment by leecalcote** [comment]
MeshMate @Nikhil-Ladha, do you foresee any issue with the addition of the parenthesis here? Their use is divergent from the convention used in the rest of the site, is that right?

**Comment by Nikhil-Ladha** [comment]
> MeshMate @Nikhil-Ladha, do you foresee any issue with the addition of the parenthesis here? Their use is divergent from the convention used in the rest of the site, is that right?

There isn't any issue with it.
Yes, the usage is divergent from the rest of the site and I think it is better to keep it consistent.
So, please undo the parenthesis @sahilsuman933

**Comment by l5io** [comment]
🚀 Preview for commit f870b92d5dbb68a5a2899fb024486ece04b22e5f at: https://61a72bd431a862cbcaaae751--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 43f6d0a1a33a8af3e97a70b5341529e2caa645af at: https://61a72f8b17cf53f608b69f41--layer5ng.netlify.app

**Pull request closed without merging**
