### PR TITLE
Edited catalog section on MeshMap page

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR edits the catalog on the MeshMap page on the Layer5 website.
[https://layer5.io/cloud-native-management/meshmap/](url)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit edbbcb8ca3cc012c35efc1800010e971d5f24814 at: https://63dce75e2894de028f809307--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 776f29e233e22aac98bdfc798a6a2044aa0f583c at: https://63dcf974cdd7da17efa07d44--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9b2f7ed0f1f7ff8930a727723637893a3cecb3b6 at: https://63dd012e3ec9bc17e3c12eeb--layer5.netlify.app

**Comment by leecalcote** [comment]
A few padding / spacing issues in mobile view:

Screenshot 2023-02-03 at 3 32 53 PM



The line height / padding between lines is a bit too much in small to medium window sizes. Please reduce the whitespace.

Screenshot 2023-02-03 at 3 34 52 PM

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
I have opened https://github.com/layer5io/layer5/issues/3693 to ensure these items are addressed.

**Comment by Shivam-AfA** [comment]
@leecalcote I'll make sure this is taken care of.

**Comment by leecalcote** [comment]
Thank you

**Pull request merged**
