### PR TITLE
Update the Graphic for hacktoberfest 2022

### LINKED ISSUE #3175: [Site] Update date and new graphic for Hacktoberfest 2022
#### Current Behavior
Hacktoberfest is around the corner and https://layer5.io/programs/hacktoberfest this page shows last year's date with 2021 graphic. 

#### Desired Behavior
Update the date and add  new graphics
Hacktoberfest 2022 site: https://hacktoberfest.com/

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by eeshaanSA**
Signed-off-by: eeshaanSA <eeshaans1@gmail.com>

**Description**
Updated the graphic for Hacktoberfest 2022.
This PR fixes #3175 

**Notes for Reviewers**
This PR can be merged after merging #3196. (The date and text has been updated in there.)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@eeshaanSA The build preview is failing for this PR, Please check this error. It's related to the image path. 
image

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
The older image is not needed anymore.
Also, update the `permalink`, and folder name to have "2022".

**Comment by eeshaanSA** [comment]
Wasnt the image and date updated by @Chadha93 ? Can you check PR #3199 ?

**Review by legendarykamal — CHANGES_REQUESTED** [review]
This is the png that nikhil is rightfully saying needs to be removed src/collections/programs/hacktoberfest-2022/hacktoberfest2020.png

**Comment by leecalcote** [comment]
@debo19 @Nikhil-Ladha time is of the essence here. We need to complete this promptly in order to go forth with the event on Friday.

**Comment by eeshaanSA** [comment]
Got it, @Nikhil-Ladha. Will make the changes ASAP. 
@leecalcote dont worry, will have it merged in a few hours. 👍

**Comment by leecalcote** [comment]
@Nikhil-Ladha awesome. Thank you.

**Comment by eeshaanSA** [comment]
so just to be sure, only the hacktoberfest 2020.svg should be kept, and all others(2020.png , 2021.png) should be removed, along with their respective folders?

**Comment by eeshaanSA** [comment]
https://github.com/layer5io/layer5/pull/3207

**Pull request closed without merging**
