### PR TITLE
feat: fixed text-color-hover and errors

### PR DESCRIPTION
**Pull request by 4ddx**
Signed-off-by: Ishan Kumar [ishanakshar@gmail.com](mailto:ishanakshar@gmail.com)

Description

This PR fixes [#4706 ](https://github.com/layer5io/layer5/issues/4706)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

Fixed sign-off and color on hover to theme.white

### CODE REVIEW

**Comment by 4ddx** [comment]
@thisiskaransgit here, the sign-off is configured properly. I'm sorry for the earlier Pr's.

**Comment by l5io** [comment]
🚀 Preview for commit 40da8f4b5e88e58f095888476f5d3af670e01435 at: https://64e1b6c002c093391e5d1489--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @4ddx 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by 4ddx** [comment]
Hey @Ghat0tkach  this has already been discussed in the previous call.

There was a previous pr on this issue that i closed, due to rebasing/sign-off errors.

**Review by thisiskaransgit — APPROVED** [review]
Thanks @4ddx, this works 👍🏼

**Comment by 4ddx** [comment]
So, can we merge this please?

**Comment by 4ddx** [comment]
@thisiskaransgit @Ghat0tkach sorry to disturb, can we merge this?

**Review by Chadha93 — APPROVED** [review]
Thank you @4ddx

**Pull request merged**
