### PR TITLE
New Event added

### LINKED ISSUE #5483: [Event] Making the CNCF Landscape Interactive with Meshery
Please add the following event to layer5.io/events.

**Event:**
- Event Title: “Making the CNCF Landscape Interactive with Meshery”
- People: Lee Calcote, Saiyam Pathak
- description:
```
Join the Kubesimplify livestream for an engaging livestream where we dive into the dynamic world of the Cloud Native Computing Foundation (CNCF) Landscape and explore how Meshery, the collaborative cloud native manager, is revolutionizing it. In this session, we’ll demonstrate how Meshery not only simplifies the management of all Kubernetes-based infrastructure, but also makes the CNCF Landscape interactive, allowing for a more intuitive and hands-on experience.

Whether you’re a developer, an operator, or simply a cloud-native enthusiast, you’ll discover how Meshery’s powerful visualization and collaboration features can help you navigate the CNCF Landscape with ease. Get ready to learn about:
- Meshery’s role in the CNCF ecosystem
- Interactive features that enhance your understanding of EVERY CNCF project
- Real-time demonstrations of Meshery in action
- Tips and tricks for leveraging Meshery to its full potential

Don’t miss out on this opportunity to enhance your cloud-native journey with Meshery. Subscribe and set a reminder for our livestream to stay at the forefront of cloud-native technologies!
```
- Include an event registration form?: Yes
- Featured: No
- Event Link: N/A

---
<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by ritiksaxena124**
This PR fixes #5483

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9a7fed4427c95f32e290c4f88a82fbe44d97a181 at: https://661a1e20740ddc5124de1a25--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6cf7ad818a957cabdab3a8ef2572ec6124dbd3ad at: https://661a24b4adfe0954534afc28--layer5.netlify.app

**Comment by leecalcote** [comment]
Nice work. 👍

**Comment by leecalcote** [comment]
oh, there was an item that has been missed: a registration form. Please look to older events for examples of how this works or to the contributing.md, @riti

**Pull request merged**
