### PR TITLE
[commonForm.style.js] fixed issue #5232 #5242

### LINKED ISSUE #5232: [BUG] Options not visible in roles dropdown list on meshmap page
### Description
https://layer5.io/cloud-native-management/meshmap
Here at "join the beta" form "select role" options are not visible. 

### Expected Behavior
Text color should be changed

### Screenshots
Screenshot 2023-12-26 112840

### Environment:
- Host OS: windoes
- Browser: chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by kishore2k**
**Description**
Signed-off-by: Kishore contactkishore2000@gmail.com

This PR fixes #5232 #5242 

**Notes for Reviewers**
Fixed the options not visible in roles dropdown list on meshmap page under "Join the Beta Form"

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cf6cf785405f5a7aa792cc0f1f78db8a34afcabd at: https://658be0bf3098fa3873d5c025--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @kishore2k. We shouldn't need to mandate a white background and black text. They should invert based on current color mode.

Screenshot 2023-12-28 at 8 30 55 AM

**Comment by l5io** [comment]
🚀 Preview for commit 209bfef63549688937c74e018e055083fb53c605 at: https://658d8f779ab4710fb93be1b3--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Hey @kishore2k,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Comment by l5io** [comment]
🚀 Preview for commit d30b909940a6d0129942afbe29fdce26ab757b85 at: https://659633e4a034602f4f790f74--layer5.netlify.app

**Pull request closed without merging**
