### PR TITLE
[NG] Implemented table type of filtering #2

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR replicates #1195 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kishore007k** [comment]
@Jashpatel1 Which PR is this? I'm a little confused now.😅

**Comment by Jashpatel1** [comment]
> @Jashpatel1 Which PR is this? I'm a little confused now.

I thought you had problem resolving conflicts. So I added your commits here and resolved the conflicts. But I see you have recently force-pushed. If it works out, this PR can be closed.

**Comment by kishore007k** [comment]
Thank you @Jashpatel1 😅

**Comment by Jashpatel1** [comment]
Closing due to duplicancy

**Pull request closed without merging**
