### PR TITLE
Fix card heights across the project

### PR DESCRIPTION
**Pull request by aayushdutt**
Fixes: #403 
Signed-off-by: Aayush Dutt <aayushd100@gmail.com>

### CODE REVIEW

**Comment by aayushdutt** [comment]
See: 
1. https://deploy-preview-404--layer5io.netlify.app/books
2. https://deploy-preview-404--layer5io.netlify.app/projects
3. https://deploy-preview-404--layer5io.netlify.app/programs

**Comment by gunjanmimo** [comment]
@aayushdutt your changes look good to me. 
I have a small suggestion, may you add small hover effect on project and program section.
@leecalcote  sir, what do you think about this?

**Comment by leecalcote** [comment]
> @aayushdutt your changes look good to me.
> I have a small suggestion, may you add small hover effect on project and program section.
> @leecalcote sir, what do you think about this?

Good thought, @gunjanmimo. The small button was intentionally removed from the `program` and `project` cards so as to differentiation them from the other cards (to mix it up a bit).

**Comment by aayushdutt** [comment]
> @aayushdutt your changes look good to me.
> I have a small suggestion, may you add small hover effect on project and program section.
> @leecalcote sir, what do you think about this?

Great suggestion. I'll do it right away!

**Comment by aayushdutt** [comment]
> Well I have two points-:
> 
> 1. In the books link, inad of increasing the card size I think the size of cards should be reduced a bit. Like the size of the last book in red looks a bit stretched and others too.
> 2. In the projects link the cards are not of same size, the first one is a bit longer than others.

1. Good suggestion, I'll do it
2. Unfortunately, I am unable to reproduce your issue on Chrome 80, Ubuntu. The cards are all of exactly the same resolution for me.

**Comment by Nikhil-Ladha** [comment]
Here are the screenshots showing how it looks in mobile view and desktop view:
https://drive.google.com/file/d/1iOMHdM492QaJ4rfxXSN_PCqBrgY7NPFC/view?usp=drivesdk
https://drive.google.com/file/d/1iJZw-wBmQ-jF6jZC0opmzNNfkY38ZYeh/view?usp=drivesdk

**Comment by aayushdutt** [comment]
> Here are the screenshots showing how it looks in mobile view and desktop view:
> https://drive.google.com/file/d/1iOMHdM492QaJ4rfxXSN_PCqBrgY7NPFC/view?usp=drivesdk
> https://drive.google.com/file/d/1iJZw-wBmQ-jF6jZC0opmzNNfkY38ZYeh/view?usp=drivesdk
> It seems a bit stretched out.

Yeah, I can see your issue in point number 1 perfectly fine.

I meant for your point number 2 ("projects link the cards are not of same size") I can't reproduce that issue.

**Comment by Nikhil-Ladha** [comment]
> > Here are the screenshots showing how it looks in mobile view and desktop view:
> > https://drive.google.com/file/d/1iOMHdM492QaJ4rfxXSN_PCqBrgY7NPFC/view?usp=drivesdk
> > https://drive.google.com/file/d/1iJZw-wBmQ-jF6jZC0opmzNNfkY38ZYeh/view?usp=drivesdk
> > It seems a bit stretched out.
> 
> Yeah, I can see your issue in point number 1 perfectly fine.
> 
> I meant for your point number 2 ("projects link the cards are not of same size") I can't reproduce that issue.

That's interesting 🤔. But I think you can check the link in the mobile if possible for confirmation of the issue.

**Comment by aayushdutt** [comment]
@Nikhil-Ladha 
This is how it looks for me:
image

Same size for mobile too

**Comment by Nikhil-Ladha** [comment]
For the performance card the text comes in next line in my phone, don't know if it's coming only in my mobile. If @leecalcote sir can confirm too for the same?

**Comment by aayushdutt** [comment]
@kushthedude great eye! Thanks for pointing out these issues, I totally missed them.

**Comment by aayushdutt** [comment]
Fixed the bugs that @kushthedude mentioned and added hover effect to cards.

**Comment by leecalcote** [comment]
@aayushdutt the books listed on /books still appear to be stretched. Would you mind taking another look there?

**Comment by aayushdutt** [comment]
Sure @leecalcote 
The issue here is that the images in the book have largely different dimensions (especially height). So for making it look decent, I had to stretch a bit otherwise the other images had to shrink.
This can, however, be easily fixed if we use an alternative image (for O'REILLY one) with approximately the same dimensions.

image
image
image

**Comment by aayushdutt** [comment]
@leecalcote I have updated the cards, take a look now: https://deploy-preview-404--layer5io.netlify.app/books

**Comment by leecalcote** [comment]
Simply fantastic, @aayushdutt. Nice work.

**Pull request merged**
