### PR TITLE
Added member profile : Ayush Khandelwal

### LINKED ISSUE #1892: [Community] Member Profile: Ayush Khandelwal
**Current Behavior**

@Ayush-Khandelwal-007 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Ayush-Khandelwal-007 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Ayush-Khandelwal-007
- Twitter: N/A
- LinkedIn: ayush-khandelwal-741a88194
- Link to profile picture: https://drive.google.com/file/d/1wGvGN0uV_FLBKtT5At9fclXlaGiHyADD/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Added the Member Profile of Ayush Khandelwal

This PR fixes #1892 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fc9882c4fc9f1ab384adbb6f90e122170c19e610 at: https://60b65d1cc4a6b59c79f3b552--layer5ng.netlify.app

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks, @sayantan1413 for this. @Ayush-Khandelwal-007 Can you provide a short description and location to feature on your member profile?

**Comment by sayantan1413** [comment]
My pleasure to contribute @Jashpatel1  :)

**Comment by Ayush-Khandelwal-007** [comment]
@sayantan1413  @Jashpatel1 
Description : -
Hey there, I am a pre final year student at Indian Institute of Information Technology Allahabad ,India. I am passionate about software development, computer-science and open-source development. My Present domain includes wide range of fronted development tools like react, next, angular , etc. I like playing with CSS to create vivid animations. I look forward to Learn as much as I could.

Location:- 
Haryana, India

**Comment by sayantan1413** [comment]
Sure @Ayush-Khandelwal-007 am adding it in no time :)

**Review by Ayush-Khandelwal-007 — APPROVED** [review]
LGTM😀🎉.

**Comment by sayantan1413** [comment]
Congrats @Ayush-Khandelwal-007 :)

**Comment by Ayush-Khandelwal-007** [comment]
Thankyou @sayantan1413

**Comment by l5io** [comment]
🚀 Preview for commit 1f7c0888659005c47bfc3c019eee049bc835c81b at: https://60b66964e48ab200b595201d--layer5ng.netlify.app

**Comment by leecalcote** [comment]
yay, @Ayush-Khandelwal-007 🎈 😄

**Pull request merged**
