### PR TITLE
refactor(5589): image in View state management

### LINKED ISSUE #5589: fix imageInView state handling
### Description

- states are updated directly in the code without using useEffect hook
- to use inView flag new state is introduced and that new state is getting used in code to toggle CSS or images. but we don't need extra state just to keep track of inView flag, we can directly use that flag. 
image
### Expected Behavior

Directly use inView prop instead of creating new state and managing it in each code block

### Screenshots

We can format that code block as given:
image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by surajgjadhav**
**Description**

This PR fixes #5589

**Notes for Reviewers**
Refactored image in view state handling for css or image toggle

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 688173f9edf54e0635cd703f803f743d16a69aff at: https://6676d8f683621c96583739db--layer5.netlify.app

**Review by sudhanshutech — COMMENTED** [review]
Please explain the changes, in issue you are suggesting to use useEffect and here you are removing

**Comment by surajgjadhav** [comment]
HI @sudhanshutech ,
ideally that state should be in useEffect, but as I analyze the code, we are creating new state just to maintain status of inView state and using that in our code. so, instead of adding new state we can directly use inView state in our code.
So, I have removed that additional state management code and directly used inView state.
Thanks

**Comment by Deepak0320Singhal** [comment]
@surajgjadhav Thank you for your contribution.
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by iArchitSharma** [comment]
@sudhanshutech @vishalvivekm do we need this refactor?

**Pull request closed without merging**
