### PR TITLE
Home/partners

### PR DESCRIPTION
**Pull request by vineethvanga18**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2db43935a9a74dac0eb4098c6f27cf5590213c06 at: https://6057b0e033ba7988dc41bc87--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Getting closer, I think, but still needs some work. Screenshot from Safari: 

Screen Shot 2021-03-21 at 5 49 23 PM

**Comment by l5io** [comment]
🚀 Preview for commit 7cc30917f5bef560278df36d1f64bd6700b6d641 at: https://6058729026de52b3fe52d5a1--layer5ng.netlify.app

**Comment by vineethvanga18** [comment]
This took so long🙂

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
