### PR TITLE
MeshMap CTA

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
1) Added CTA to
- SMP page
- SMI page
- Docker extension page
- Projects page
2) Image enlarged on click for meshmap modes.
3) Removed Hover effect from catalog carousal.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c06e5d1d299926d25173eb6cbde7adc945f62271 at: https://62aae656624d2b529aa0eca4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 972244e2eaf8130fa846cde0c120d2fe1261071b at: https://62aaeed5203ba956bbf8e5dc--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Blank CTA in mobile view

**Comment by leecalcote** [comment]
https://user-images.githubusercontent.com/7570704/174160782-af4a1bb4-4d4b-4a07-be12-a583a05f088e.mov

**Comment by leecalcote** [comment]
Light mode vs dark mode issue?

**Comment by leecalcote** [comment]
@Nikhil-Ladha we'll have to get this CTA folded into your rotational framework.

**Comment by debo19** [comment]
@leecalcote I have no idea why this is happening. I'll show you how it looks though.

https://user-images.githubusercontent.com/85789734/174161022-67b73802-6caa-47ff-bef3-e10d9d26ed89.mov

**Comment by warunicorn19** [comment]
Okay seems to be a safari-specific issue, I can see it on chrome.

**Comment by debo19** [comment]
It's working now, found the fix 😅

**Pull request merged**
