### PR TITLE
Add margin to slide button

### LINKED ISSUE #4187: Overlap of slide button on meshmap page for mobile devices
### Description
Overlap of slide button on meshmap page for mobile devices.
Link: https://layer5.io/cloud-native-management/meshmap

### Expected Behavior
The slide icon shouldn't overlap instead have some padding below it.

### Screenshots
meshmapissue

### Environment:
- Host OS: Android 
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Saksham294**
**Description**

This PR fixes #4187 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Savio629** [comment]
Looks better @Saksham294 
Suggestion : The slide button appears to be too close to the next section (Design).
Try to add some padding between them or bring the sliding button a little up (close to images)
I guess removing margin from pagingDots class would be one solution 🤔

**Comment by l5io** [comment]
🚀 Preview for commit afaead00c470adfacdb73cf2fed8ccd256e9f0bd at: https://6458b5a6792bc909c2748bc1--layer5.netlify.app

**Comment by Saksham294** [comment]
@Savio629 Now check. Thanks

**Comment by l5io** [comment]
🚀 Preview for commit 0f83d1e03fdea936dc27fe0604eaf0ab615e3d51 at: https://6458bb0a792bc90d85748d7e--layer5.netlify.app

**Comment by Savio629** [comment]
LGTM 👍

**Review by hirentimbadiya — COMMENTED** [review]
LGTM

**Review by thoughtlessmind — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you for reviewing, @thoughtlessmind

**Comment by leecalcote** [comment]
(and per usual, @hirentimbadiya 🙂)

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
