### PR TITLE
Added handbook link to footer

### LINKED ISSUE #4917: [Programs] Representation of Writing Program
### Current Behavior
The site footer does not include a direct "[Handbook](https://layer5.io/community/handbook)" link under community. 

### Desired Behavior
It’d be good to have the Writing Program added to the Internship Program page and to then consolidate the footer links, making room for a Community Handbook link in the footer. 

Screenshot 2023-09-15 at 11 58 49 AM

### Screenshots / Mockups
__mockup for needed__

### Implementation
1. Consolidate "Internship and Writing Programs" into one line. If this combined text is too long, then shorten to simply "Internship Programs"
2. Add new section for Writing Program in the [Internships page](https://layer5.io/careers/programs)

### Acceptance Tests
1. layer5.io/community/handook is a new "Handbook" link in the footer under the Community section.
2. Writing program is represented on the Internships page.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ankushbhardwaj408**
**Description**

This PR fixes #4917 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f2a9af3a019d6b26e35fa7f7a55b20bc199a8be9 at: https://654a0a3b8a9c6b021605ad64--layer5.netlify.app

**Comment by sudhanshutech** [comment]
Thanks for this @ankushbhardwaj408 , but the ask is also to move the writing program to internship program page because of just remove the link then we will not have any direct way to go writing program page

**Comment by ankushbhardwaj408** [comment]
@sudhanshutech This is what I have suggested that #4918 which is assigned to @akshun-01 needs to be completed first.

**Comment by Akshun-01** [comment]
Hey, I have started working on it, I'll complete it soon.

**Comment by leecalcote** [comment]
Folks, this issue has been open for months. This PR doesn't solve the issue in-full. @ankushbhardwaj408 are you going to finish the other portion? Should we reassign?

**Comment by Akshun-01** [comment]
> Folks, this issue has been open for months. This PR doesn't solve the issue in-full. @ankushbhardwaj408 are you going to finish the other portion? Should we reassign?

Hey @leecalcote , actually i am working on adding the cards part. I will finish it soon.

**Comment by leecalcote** [comment]
> > Folks, this issue has been open for months. This PR doesn't solve the issue in-full. @ankushbhardwaj408 are you going to finish the other portion? Should we reassign?
> 
> Hey @leecalcote , actually i am working on adding the cards part. I will finish it soon.

Thanks. If you're able to finish by this time tomorrow - awesome. If not, let's toss in the towel here.

**Comment by Akshun-01** [comment]
Hey @leecalcote, added the card, now do I need to link it to the existing writing program page? Or should I make a page to just brief up the program and then there add a button to go to the original page with all details ? (LIke it has been done with other programs) 
image

**Comment by Akshun-01** [comment]
Also while I am at it, should I also add the card [here](https://layer5.io/community/handbook/mentorship-programs) as well ?
I think it should be updated as well.

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408 @Akshun-01 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Akshun-01** [comment]
@leecalcote if you could please explain what needs to be done for this issue, if not making a card. It would be helpful making progress with it!

**Comment by Akshun-01** [comment]
@ritiksaxena124 any ideas on how to move forward with this issue?

**Comment by ankushbhardwaj408** [comment]
> Thanks for this @ankushbhardwaj408 , but the ask is also to move the writing program to internship program page because of just remove the link then we will not have any direct way to go writing program page

@sudhanshutech I guess we can always go to writing program from the handbook.

**Comment by ankushbhardwaj408** [comment]
@Akshun-01 Check out video at 30:00 https://www.youtube.com/watch?v=hDv_5FCyCho&t=1246s

**Comment by Akshun-01** [comment]
> @Akshun-01 Check out this video at 30:00 https://www.youtube.com/watch?v=hDv_5FCyCho&t=1246s

Yeah, I already saw the meet recording, but in that, Lee mentioned he does not want to see writing programs as a separate card on the internships page. Instead, he wants to mention it in some other areas of the website, so that people are aware of it, but I am not sure where all we can add. Also if that's the case this issue needs to be updated as well I suppose as now we don't need a card anymore.
That's why I was asking if anyone has any idea on how to move forward with this issue. 
@ritiksaxena124 @Mohith234

**Comment by abhijeetgauravm** [comment]
Hey @Akshun-01 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
> > @Akshun-01 Check out this video at 30:00 https://www.youtube.com/watch?v=hDv_5FCyCho&t=1246s
> 
> Yeah, I already saw the meet recording, but in that, Lee mentioned he does not want to see writing programs as a separate card on the internships page. Instead, he wants to mention it in some other areas of the website, so that people are aware of it, but I am not sure where all we can add. Also if that's the case this issue needs to be updated as well I suppose as now we don't need a card anymore. That's why I was asking if anyone has any idea on how to move forward with this issue. @ritiksaxena124 @Mohith234

Hey @Akshun-01 Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Pull request merged**
