### PR TITLE
Kubernetes Architecture Diagram added

### PR DESCRIPTION
**Pull request by iArchitSharma**
NOTE: Images are to be updated

`<HOST-NAME>/cloud-native-management/generate-kubernetes-architecture-diagram`

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bab315921a1cb130352e5cb213d85e40a5ccf00b at: https://6593234281424802e352e912--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3d536610cfb39f4243ca02214fbc6a5bc703e153 at: https://6596cc2c3af717145d68e0d5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 759635e165baee638362a5126d8ad28cd6c26dce at: https://6596f0d9140fef1905964be5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 43a53eaedbe988a073763a82403ffc990d1ece75 at: https://6596f67ded6e7e1f226ffb56--layer5.netlify.app

**Review by ritiksaxena124 — APPROVED** [review]

**Pull request merged**
