### PR TITLE
[Area/UI]: Restructure Community Bridge Button

### LINKED ISSUE #461: Restructure CommunityBridge Button
**Description**
Currently the button of Community Bridge looks odd one out of The Buttons added on the site like GSOC 2020, GSOD 2020, Layer5 etc., As in all the buttons here there is logo and then text whereas for Community Bridge the logo itself have text.

**Expected Behavior**
All the buttons should look alike. So for that SVG needs to be updated for the Community Bridge logo. And the text should added to button with the logo.

**Screenshots**
Screenshot from 2020-07-04 14-03-10

---
[Optional] **To Reproduce**
1. Go to https://github.com/layer5io/layer5/tree/master/assets/images/programs 
2. Update the logo with the new SVG file of Community Bridge logo
3. Also Update the index.html for the same button.

### PR DESCRIPTION
**Pull request by NupurThakur27**
Fixes #461 

Screenshot from 2020-07-04 17-22-14

Signed-off-by: NupurThakur27 <nupur.s.thakur@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
@NupurThakur27, heads-up: CommunityBridge is one word.

**Comment by NupurThakur27** [comment]
> Thanks for this @NupurThakur27!
> 
> I'll toss in a quick update to make CommunityBridge one word.

@leecalcote I am really sorry I totally missed to push this commit yesterday.

**Comment by leecalcote** [comment]
No sweat. Teamwork!

**Comment by NupurThakur27** [comment]
@Nikhil-Ladha @leecalcote I hope the PR is alright now. Give it a look.

**Comment by Nikhil-Ladha** [comment]
I guess there's a DCO issue, @NupurThakur27 😬

**Comment by NupurThakur27** [comment]
> I guess there's a DCO issue, @NupurThakur27

I guess I missed that little -s here, Wait I will commit again. :disappointed:

**Pull request merged**
