### PR TITLE
Added Screenshots for Meshmap Consul Integration

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
**Description**

This PR related to #4873 

**Notes for Reviewers**
Added Screenshots for Meshmap Consul Integration

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yash-sudo-web** [comment]
@abhijeetgauravm please review

**Review by sandramsc — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution, it appears as though you have added the images, but haven't linked them in the appropriate index.mdx file. This might be the cause for this [failing check](https://github.com/layer5io/layer5/actions/runs/6465952947/job/17553041133?pr=5020).

**Comment by l5io** [comment]
🚀 Preview for commit ffbfe1dd0eb83642d64a21c151f3dc9c396affd0 at: https://652800c3b4d95821af2661cf--layer5.netlify.app

**Comment by Yash-sudo-web** [comment]
heyy @sandramsc, its done

**Review by sandramsc — APPROVED** [review]
Looks good @Yash-sudo-web , Great effort!

**Comment by saurabh100ni** [comment]
Thanks for raising PR, Let's discuss this in the Website call today at 5:30 PM IST.
Please add this as your agenda in [Docs](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

**Comment by Mohith234** [comment]
@Yash-sudo-web Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Pull request merged**
