### PR TITLE
fix: remove black color from white logos

### LINKED ISSUE #3425: [Integrations] white logos not completely white
#### Description
White logos for Minikube and Teller have black color in some areas.

image

image

#### Expected Behavior
White logos should have only white color and other parts should be see through.
image

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
Signed-off-by: Gaganpreet Kaur Kalsi <gagansinghkalsi4126@gmail.com>

**Description**
This MR removes the black color from the white logos for Minikube and Teller. 

**This PR fixes #3425** 

**Notes for Reviewers**
This issue doesn't affect anything currently because the white logos have a black background in dark mode. So the black color in white logos matches the background color. But in case we want to have a different background color like in case of integrations page for meshery.io, then black color looks odd. Below is a snapshot for your reference.

image
image

image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b7ef418afaddebd03813471b1a4ed58b13bc7784 at: https://635e3f5912f8e31e6297a4a2--layer5.netlify.app

**Review by legendarykamal — CHANGES_REQUESTED** [review]
A potential no , as the black that you are trying to remove is actually a cube  from the original logo hence the word `minikube` . Please see https://miro.medium.com/max/400/0*KzqL3xqmXzV5PPjX.png .

**Comment by leecalcote** [comment]
The thing is... the black color in these logos makes our integrations pages not look as pretty as they could look.

**Comment by legendarykamal** [comment]
agreed , lets remove them then.

**Pull request merged**
