### PR TITLE
fix unsubscribe page background color

### LINKED ISSUE #3714: Resubscribe hyperlink highlight color is not dark mode friendly
### Description
On the [unsubscribed page](https://layer5.io/unsubscribed), the resubscribe hyperlink needs dark mode friendly contrast.

### Expected Behavior
This particular css class should have a light and dark mode.

### Screenshots
Screenshot 2023-02-07 at 11 21 29 PM

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by moazzam07**
Signed-off-by: unknown <kmohdmoazzam70@gmail.com>

**Description**

This PR fixes #3714 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @moazzam07! Will you please also consider for light and dark mode support?

**Comment by l5io** [comment]
🚀 Preview for commit feada1150428bf840201e7927ce1225496ecd1bd at: https://63e54c17d3531a052090ad9a--layer5.netlify.app

**Comment by moazzam07** [comment]
I have did that for both for light mode

**Comment by moazzam07** [comment]
Screenshot_2023-02-10-02-11-08-724_com android chrome
Screenshot_2023-02-10-02-11-12-185_com android chrome
I think it looks fine for both

**Comment by moazzam07** [comment]
IMG_20230210_021401
IMG_20230210_021421
I think it looks good for both themes

**Review by leecalcote — APPROVED** [review]
Oh, @moazzam07, very good. I see now. Looks great. Thank you. 👏

**Comment by moazzam07** [comment]
Welcome @leecalcote

**Pull request merged**
