### PR TITLE
Fixed the Styling of the Community Members Page

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes the styling of the community members page.

**Notes for Reviewers**

Desktop View

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
The mobile view needs to be changed a bit
From this: 
Screenshot from 2020-09-24 21-21-31
To this:
Screenshot from 2020-09-24 21-22-36

**Comment by Nikhil-Ladha** [comment]
The extra CSS for breakpoints can be removed, that will do the trick.

**Comment by kishore007k** [comment]
Done👍 @Nikhil-Ladha

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @kishore007k 🙂

**Pull request merged**
