### PR TITLE
chore: changed meshmap-logo to 3d

### LINKED ISSUE #4295: [Visual Design] MeshMap hero: 3D logo
### Current Behavior
The [top-level MeshMap page](https://layer5.io/cloud-native-management/meshmap) has a large, flat logo visible in the right side of the hero.

### Desired Behavior
A large, 3D version of the same logo is displayed instead.

### Implementation
1. Generate a 3D rendering for prominent placement on this page.
2. Consider how to ensure that this design is responsive.

### Acceptance Tests
1. Design must relative small in footprint so as to not affect page speed.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Description**

This PR fixes #4295

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8c284842ae98f76dbfcac593edef852dbf87bce7 at: https://64c4b76503fc334520a9afb1--layer5.netlify.app

**Comment by leecalcote** [comment]
@Yana-Gupta too dark.

I appreciate this effort. Perhaps, it's more trouble than it's worth, though. Let's go ahead and close this request, giving you time back to ensure that you're successful in your other current assignments.

**Comment by Yana-Gupta** [comment]
@leecalcote I understand the previous icon was too dark.
Here is the updated version of previous logo. I have reduce the darkness.
meshmap-icon

It's preview on localhost.
Screenshot from 2023-07-29 21-07-30

If you find this one acceptable then maybe we could the previous with this one.

**Comment by leecalcote** [comment]
@Yana-Gupta I'd be curious to see what Five looks like in 3D. I wonder if you might play around with him a bit... He's available on the bottom of the page - https://layer5.io/company/brand.  @ritiksaxena124 will be interested to see, too.

**Comment by ritiksaxena124** [comment]
I am curious and excited to see Five in 3d

**Pull request closed without merging**
