### PR TITLE
Added Member Profile.

### LINKED ISSUE #2205: [Community] Member Profile: Zainuddeen Abdul Muiz
**Current Behavior**

@Zain-Muiz has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Zain-Muiz as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Zain-Muiz
- Twitter: Zain_A_Muiz
- LinkedIn: zainuddeen-abdul-muiz-36969b196
- Link to profile picture: https://pbs.twimg.com/profile_images/1372458365113167873/IPIwqhCf_400x400.jpg

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by san-coding**
**Description**

This PR fixes #2205

Added community member profile for @Zain-Muiz 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Any chance you could signoff this commit? https://github.com/layer5io/layer5/pull/2208/checks?check_run_id=3662225688

**Comment by san-coding** [comment]
> Any chance you could signoff this commit? https://github.com/layer5io/layer5/pull/2208/checks?check_run_id=3662225688

Yes I will do it in sometime

**Comment by l5io** [comment]
🚀 Preview for commit 0517251c8d8666257ec71453e0b5d8dbc50f7f36 at: https://6149bcc287f488c0728b8f96--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
Umm, still doesn't seem to be signed-off.

**Comment by san-coding** [comment]
Is there a way to sign off commits through GitHub UI

**Comment by warunicorn19** [comment]
No, not really, I'll give you a free-pass on this one, considering you've had a long day figuring out how to setup locally. Also, I'm pretty sure @Zain-Muiz os quite excited for his profile😄. Please try to take care from next time. https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md ( some resources)

**Comment by l5io** [comment]
🚀 Preview for commit 68e3e9fec761091a8d5c8810a1f52728cb9be5d7 at: https://6149cb79dfad5412b03723ed--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thanks @san-coding.

**Comment by leecalcote** [comment]
@Zain-Muiz this is your profile. Let's make sure that you get a chance to review and approve before publishing.

**Comment by warunicorn19** [comment]
@leecalcote he gave me a LGTM on slack, that's why i went ahead with the merge.

**Comment by san-coding** [comment]
When did the DCO test pass, lol I am still working on it

**Comment by san-coding** [comment]
> No, not really, I'll give you a free-pass on this one, considering you've had a long day figuring out how to setup locally. Also, I'm pretty sure @Zain-Muiz os quite excited for his profile😄. Please try to take care from next time. https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md ( some resources)

I enabled auto signoff on vscode after the first commit, which resulted in the second commit getting signed off but not the first one 😓

**Comment by warunicorn19** [comment]
Aah okay, just something to keep in mind from next time I guess😅

**Comment by san-coding** [comment]
> Aah okay, just something to keep in mind from next time I guess😅

Yeah it is enabled now on vscode, won't be a problem for any commit in the future, thanks @warunicorn19

**Comment by san-coding** [comment]
what happens when one of the commits is not signed off ? will it have any effect

**Comment by warunicorn19** [comment]
well, all your commits should be signed off, but if the latter commit is signed off while the former is not, that shouldn't be an issue, the DCO should pass for that, your latest commit is the one that needs to pass the DCO.

**Comment by san-coding** [comment]
Ohh ok, do tag me in issues that you think I could work on, thanks

**Comment by warunicorn19** [comment]
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

some `help wanted` issues that you might want to take a look at.

**Comment by san-coding** [comment]
> https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
> 
> some `help wanted` issues that you might want to take a look at.

Sure, looking forward to contributing to layer5, won't bug you so much next time😅 , thanks @warunicorn19 @Zain-Muiz

**Comment by san-coding** [comment]
> 🚀 Preview for commit [0517251](https://github.com/layer5io/layer5/commit/0517251c8d8666257ec71453e0b5d8dbc50f7f36) at: https://6149bcc287f488c0728b8f96--layer5ng.netlify.app

Can someone explain how this works, how is it giving a preview for each commit, how to set this up 
@warunicorn19 , @leecalcote

**Comment by leecalcote** [comment]
@san-coding, there's no need to setup anything here. The automation is all configured and running on-task. ✔️

**Comment by san-coding** [comment]
@leecalcote I want to add this to my repo, how can I set up this automation, what is it called

**Comment by leecalcote** [comment]
GitHub Actions.

**Comment by san-coding** [comment]
Which action is it ? I am unable to find build preview action
image

**Comment by warunicorn19** [comment]
https://github.com/marketplace?type=&verification=&query=netlify+preview+, these might help, you'd have to have a netlify account. The easier way you'd just be to get a netilfy account and set up a netlify bot on your repo, it'll auto-build on each commit on every PR.

**Comment by leecalcote** [comment]
Please see https://discuss.layer5.io for further discussion.

**Pull request merged**
