### PR TITLE
[Blog-single]: Display published date in single blog post view

### LINKED ISSUE #2887: [Blog] Display published date in byline
**Current Behavior**
In the single blog post view, there is no published date visible.

**Desired Behavior**
It would be nice to see the published date in the byline adjacent to Category and Author.

**Screenshots / Mockups**
Screen Shot 2022-06-08 at 7 09 20 PM

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by indraantoor**
**Description**

This PR fixes #2887 

**Notes for Reviewers**
Screenshot from 2022-06-12 19-49-56

Now the published date is also displayed in the byline adjacent to Category and Author.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 351821ae4a5d91d11dfd96c86a05d585ff17a021 at: https://62a5fb3aaf906f7072619f22--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit daf39f345afde0e0ae06801790e94a7c189480b6 at: https://62a603b16ba27a7a2f37f1a6--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
Looking good. I updated the date label.

@indraantoor, will you do the same thing (add the date) to the single news view as well?

**Comment by l5io** [comment]
🚀 Preview for commit edaafb4733b1326188e26a6217a0aa876a578e89 at: https://62a60f94af906f7dd56199e3--layer5.netlify.app

**Comment by indraantoor** [comment]
@leecalcote Yes sure!

**Comment by l5io** [comment]
🚀 Preview for commit 74079c0337b8d92922a8e8d738fc9624b9f6160d at: https://62a6e7c453f2f17c8593452c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 35fe967f6ff6f28d65111d93bfc76e1bf4b547a3 at: https://62a6f1b2552b2d036f71939d--layer5.netlify.app

**Pull request merged**
