### PR TITLE
Newcomer form Typo Fixed

### LINKED ISSUE #4969: [typo] Newcomers Form
### Description

I was filling the newcomers form at https://layer5.io/newcomers and found that it has a couple of grammatical errors.
### Expected Behavior

- it should be 'simply ask to be partnered' instead of 'simple ask to be partnered'
- it should be 'aspect of a project' instead of 'aspect a project'

### Screenshots
Screenshot_2023-09-27_11-21-14

I'd like to work on this issue

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Jat1nSood**
**Description**
There was a Typo in New Comer form in<Web-based-form>
This PR fixes #4969 

**Notes for Reviewers**
This is my first PR

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5ee3e9a47d5938e0df0cf1eb27ac567e15202ab1 at: https://6514424d858f75009fb12a18--layer5.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@Jat1nSood, just a friendly reminder: before you create a pull request, make sure the issue is assigned to you.

**Comment by Jat1nSood** [comment]
> @Jat1nSood, just a friendly reminder: before you create a pull request, make sure the issue is assigned to you.

@hirentimbadiya Understood. Also is there any other issue in this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 7c95c4f432e79512b1a71c5528101526959556c5 at: https://65169c16e86e995dba23de16--layer5.netlify.app

**Pull request closed without merging**
