### PR TITLE
Added Meshery Extention into the project page grid

### LINKED ISSUE #2870: Add meshery docker extension
**Current Behavior**

Meshery docker extension is missing from the list

**Desired Situation**
Add meshery docker extension on [layer5.io/projects](https://layer5.io/projects)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>

**Description**Added Meshery Extention into the project page grid

This PR fixes #2870 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Poor formatting in mobile view
Screen Shot 2022-06-08 at 5 05 42 PM
.

**Comment by l5io** [comment]
🚀 Preview for commit 4545efe81c46b7234c8717170a2e23ad3c7debd0 at: https://62a1e22d63989d6d5ad20087--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 13a915948ca54604f5e82946cc005c64e8dcf6e0 at: https://62a1f288148db1019089bec8--layer5.netlify.app

**Comment by leecalcote** [comment]
Always be checking responsiveness.

**Comment by YashKamboj** [comment]
@leecalcote On it!!

**Comment by leecalcote** [comment]
@debo19, as a practice, let's avoid wrapping PNGs inside of SVGs - https://github.com/layer5io/layer5/blob/master/src/assets/images/docker-extension/Docker_animated.svg

**Comment by l5io** [comment]
🚀 Preview for commit 9dad3e709689200ef60dc81812be53171c599fe6 at: https://62a21e85af3a65005e968c64--layer5.netlify.app

**Pull request merged**
