### PR TITLE
Love to add Kamal Singh to community/member

### PR DESCRIPTION
**Pull request by sam1code**
Signed-off-by: Soumyakanta Pattanaik <samcse95@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
That is a sweet title thankyou @sam1code :heart:

**Comment by sam1code** [comment]
> That is a sweet title thankyou @sam1code heart

[❤️](https://emojipedia.org/red-heart/)

**Comment by l5io** [comment]
🚀 Preview for commit 3dd6ab5b152544e4bd002474b58ae902b186dcad at: https://631ba2be775c3417e795c96b--layer5.netlify.app

**Review by legendarykamal — APPROVED** [review]
LGTM nope ! Rather Looks Awesome to Me :smile: :confetti_ball:

**Review by Chadha93 — APPROVED** [review]
Cool :sunglasses:

**Comment by Chadha93** [comment]
Yay! @legendarykamal :balloon:

**Comment by legendarykamal** [comment]
Thankyou @Chadha93 and @sam1code this is dope :100:  a noteworthy moment :confetti_ball: 

none the less being close to @leecalcote makes it more special :laughing: 
image

**Comment by sam1code** [comment]
@legendarykamal I already seen it and waited to see your expression ❤️ 🎉🎉🎉

**Pull request merged**
