### PR TITLE
added Utkarsh Srivastava as a contributor

### LINKED ISSUE #1243: [NG] Community: Recognizing Utkarsh Srivastava as a Contributor and Community Member
**Current Behavior**

@utkarsh-pro has been a consistent contributor and community member.

**Desired Situation**

A profile for @utkarsh-pro should be created and visible on /community/members on the next-generation layer5.io site.

- Github: https://github.com/utkarsh-pro
- Twitter: 
- LinkedIn and Profile picture: @utkarsh-pro please can you provide a link to your LinkedIn, Twitter, and a profile picture

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by MaximeCoignus**
Signed-off-by: MaximeCoignus <maxime.coignus@gmail.com>

**Description**

This PR fixes #1243 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Hey @utkarsh-pro can you share your LinkedIn handle as well (if you have one)?

**Comment by leecalcote** [comment]
We need to update the member profile template as well given that new front matter variables have been defined:

- location
- badges
- bio

@utkarsh-pro can provide a brief bio and location. His badges should be: meshery (any others, @utkarsh-pro)?

**Comment by utkarsh-pro** [comment]
Ah... I missed this one.
Here are the details:

Image: https://sagacious.dev/pic.jpg
Location: New Delhi, India
Badges: Meshery
Linkerd: https://www.linkedin.com/in/utkarsh-srivastava-2310/
Bio: I am an undergraduate student at IP University majoring in Computer Science and Engineering. I am a curiosity driven developer having special interest in distributed systems. Co-founded Hackstrap Technologies to power networking, partnerships and sales at scale. Learnt everything from open source, trying to give back as much as possible.

**Comment by Jashpatel1** [comment]
@MaximeCoignus do you mind signing off your commits?

**Comment by MaximeCoignus** [comment]
@Jashpatel1, done!

**Comment by Jashpatel1** [comment]
> @Jashpatel1, done!

Cool, we will wait for @utkarsh-pro's review. All looks good to me.

**Comment by utkarsh-pro** [comment]
Looks good to me. Thanks! :smile:

**Review by utkarsh-pro — APPROVED** [review]

**Review by Jashpatel1 — APPROVED** [review]
Great work. Thanks @MaximeCoignus

**Pull request merged**
