### PR TITLE
ADD community member profile links on LFX Page

### PR DESCRIPTION
**Pull request by eeshaanSA**
Signed-off-by: eeshaanSA <eeshaans1@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b387ccd0095458bead56e849881c2cfc7b78e492 at: https://63e378c511888f0f5220bc5b--layer5.netlify.app

**Comment by eeshaanSA** [comment]
replaced. Have a look @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit b04cd0a40f05c297fbc173f1c5fee0880779879f at: https://63e404be0c341e1cca6d05d8--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
thank you

**Pull request merged**
