### PR TITLE
Added Dark Mode Theme to Layer5-NG

### LINKED ISSUE #972: [NG] Add dark theme to Layer5-NG.
**Current Behavior**

There is only a light theme present currently.

**Desired Behavior**

Add a dark theme to the layer5-ng website.

---
 **Alternatives**

Use this https://www.gatsbyjs.com/plugins/gatsby-plugin-dark-mode/.

 **Additional context**

You can add a dark theme in the theme folder in src.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by geraldmaboshe**
**Description**
Implemented dark mode functionality
This PR fixes #972

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@geraldmaboshe whoa! Pretty cool. Currently, the home page is the only dark-mode supported page, right?

**Comment by geraldmaboshe** [comment]
> @geraldmaboshe whoa! Pretty cool. Currently, the home page is the only dark-mode supported page, right?

Yep, it will easily be applied across all pages once home is nicely done

**Comment by Nikhil-Ladha** [comment]
Good effort here @geraldmaboshe , but I think the maximum of the changes done are not needed.....those are changes due to using a different config of linter (and might be due to prettier as well) which is not required. Please fix them.

**Comment by geraldmaboshe** [comment]
> Good effort here @geraldmaboshe , but I think the maximum of the changes done are not needed.....those are changes due to using a different config of linter (and might be due to prettier as well) which is not required. Please fix them.

Thank you @Nikhil-Ladha.  It could be Prettier because I did not use any different linter config. Could you give some tips on what Prettier configs I should change?

**Comment by Nikhil-Ladha** [comment]
I am not sure about the config....but it seems like we need to set that up as well. As many people do use `prettier` and we should be ready for that to avoid such situations in future.
There is a convenient going on for it on the websites channel, you could keep a check on that as well for any updates.

**Comment by geraldmaboshe** [comment]
> I am not sure about the config....but it seems like we need to set that up as well. As many people do use `prettier` and we should be ready for that to avoid such situations in future.
> There is a conversation going on for it in the websites channel, you could keep a check on that as well for any updates.

Okay, let me check that conversation out.

**Comment by leecalcote** [comment]
Considering the state of this PR and the nearness of going live with the new site, I'm assigning the "Post-go-live" milestone to this PR.

**Comment by geraldmaboshe** [comment]
> Considering the state of this PR and the nearness of going live with the new site, I'm assigning the "Post-go-live" milestone to this PR.

Sure

**Pull request closed without merging**
