### PR TITLE
Enhance learn-card at Learn page.

### LINKED ISSUE #4154: enhance the learn-card section
### Current Behavior

The learn-card section on https://layer5.io/learn page can be enhanced a bit to look better.

### Screenshots / Mockups

This is how it looks currently : 
image

### Example suggestion : 

[Screencast from 27-04-23 12:12:29 AM IST.webm](https://user-images.githubusercontent.com/114604338/234672718-35e914d0-9514-40ef-9ea4-9862b06601f9.webm)

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by 8rxn**
**Description**

This PR fixes #4154

**Notes for Reviewers**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 29a58649e8a452391d1cc6b6f5709fd42ec23a6a at: https://645f99180a414849ebb99d2d--layer5.netlify.app

**Comment by senali-d** [comment]
Suggestion:
Change background color when hover the card. (Ref: #4154)

**Comment by 8rxn** [comment]
> Suggestion: Change background color when hover the card. (Ref: #4154)

Thankyou For Your Suggestion @senali-d.
However I felt that the change in shadow color is enough for hover. 

Should I still make the Change?

**Comment by vishalvivekm** [comment]
@8rxn Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would.

**Comment by 8rxn** [comment]
> @8rxn Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would.

Sure.

**Comment by Nikhil-Ladha** [comment]
Closing out the PR, as the issue is irrelevant. Thank you much for your efforts and contribution here :)

**Pull request closed without merging**
