### PR TITLE
Created a new FAQ and answer

### LINKED ISSUE #1991: Add a FAQ for members of the community
**Current Behavior**
There is no FAQ that points out what is expected from contributors joining the community.

**Desired Situation**
Create a FAQ that answers the question "What is expected of me as a member of Layer5 organisation?"

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Anita-ihuman**
**Description**
Created a new FAQ and answer for members of the Layer5 org.
This PR fixes #1991

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cbf74a0f6f77d08e5b4f0ec8cea99b02428bd29e at: https://60eef503588a7948d5b394b5--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
Blazing fast speed, @Anita-ihuman. ⚡

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
I tossed in a few more. Thanks for this, @Anita-ihuman

**Comment by Anita-ihuman** [comment]
> I tossed in a few more. Thanks for this, @Anita-ihuman

Thank you @leecalcote

**Pull request merged**
