### PR TITLE
fix(form): add missing label text

### LINKED ISSUE #5994: T-Shirt Size "XXL" is missing from newcomers page
### Description

As present before, T-Shirt size XXL is not available after last radio button. Option is not available for both dark and light mode

[Newcomers Page](https://layer5.io/newcomers)

### Expected Behavior
There should be `XXL`  after last radio button

### Screenshots
image

### Environment:
- Host OS: Windows 10
- Browser: Brave

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by void-hr**
**Description**

Label Text was missing just added that. 

This PR fixes #5994 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5f72bebb654c0acc8194b3e05633becd23f3b346 at: https://670871306e59b6b1a61e4ca3--layer5.netlify.app

**Review by miacycle — APPROVED** [review]
Indentation is slightly off, but otherwise looks good.

**Comment by void-hr** [comment]
> Indentation is slightly off, but otherwise looks good.

Thanks for the feedback, am gonna fix indentation quickly!

**Review by hargunkaur286 — APPROVED** [review]
LGTM!

**Pull request merged**
