### PR TITLE
Adding Project Hamlet

### PR DESCRIPTION
**Pull request by subhamkrai**
Adding project Hamlet in landscape service mesh
and also in non-functional.

Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
fixes #232

**Comment by subhamkrai** [comment]
> Rename the PR and amend the commit. It is **Hamlet** not **helmet**

Ah..Good catch..will update soon.

**Comment by ashiscs** [comment]
@leecalcote sir, can you review this?

**Comment by kushthedude** [comment]
Commit is not updated !

**Comment by kushthedude** [comment]
Its good to go @leecalcote

**Comment by leecalcote** [comment]
Gents, thanks for this. Akin to SMI, Hamlet is a little hard to fit into the existing categories and may require one of its own. I'll give this some consideration.

**Comment by leecalcote** [comment]
We do need one that describes the [Service Mesh Performance Specification](https://layer5.io/performance) as well. SMI, Hamlet, and SMPS are all three service mesh abstractions.

**Pull request closed without merging**
