### PR TITLE
update screen shots

### LINKED ISSUE #4885: [Screenshots] Dapr under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/dapr) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Dapr](https://layer5.io/cloud-native-management/meshery/integrations/dapr) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShatilKhan**
**Description**

This PR fixes #4885

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sandramsc** [comment]
Hi @ShatilKhan there are two checks that are currently failing, taking a quick look at the changed files I noticed that you've removed the old images and added the new ones. This might be the cause. Consider taking a look at this [comment](https://github.com/layer5io/layer5/pull/4914#issuecomment-1734386234), which might give a bit more context.

**Comment by ShatilKhan** [comment]
Thanks @sandramsc !
I've restored the images!

**Comment by l5io** [comment]
🚀 Preview for commit 4c4230bc432c713aa75ce3e7b18e8feba62434fa at: https://6516f84d5ef5ac07873b34fb--layer5.netlify.app

**Comment by ShatilKhan** [comment]
Preview image:
image

**Comment by sandramsc** [comment]
@ShatilKhan  taking a look at the **vizualier** screenshot it appears that the icons are missing on the canvas. Consider retaking a new one.

**Comment by saurabh100ni** [comment]
Let's discuss this Item in tomorrow's website call, 
please add it as your agenda if you would: 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by ritiksaxena124** [comment]
Any update on this @ShatilKhan ?

**Comment by ShatilKhan** [comment]
Will submit updates by tonight

**Comment by ShatilKhan** [comment]
Guys, facing some issues
I only get the option to `clone`. The design isn't immediately appearing , is this some new feature update? I didn't see this before & don't understand how to initiate this design into my meshmap
image

**Comment by Harsha-10** [comment]
Change the filter in designs from published to public, then they will show up in canvas

**Pull request merged**
