### PR TITLE
To display unique Items in technology filter

### LINKED ISSUE #5298: Duplicate List Category Mesh
### Description

In the DropDown of Technology i found duplicates you can see it in below video 
### Expected Behavior

expected that there should be unique elements present
### Screenshots

[Screencast from 2024-01-18 17-37-56.webm](https://github.com/layer5io/layer5/assets/129654598/9179ed36-447e-4896-9287-5d4f2c3fb747)

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by JyothiSwaroopReddy07**
**Description**

This PR fixes #5298 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cd462ba380cd89194b12907577828b20f6f0cc99 at: https://65a9bd2ac548fc2404c82e24--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7180520abf15fed604e2dd407e31c8191929f5fe at: https://65aab6119663d606dcd9567c--layer5.netlify.app

**Comment by leecalcote** [comment]
@JyothiSwaroopReddy07 Thanks. Do you want to ensure that you have only your commits included in your pool request. You can do this by resyncing your fork with origin.

**Comment by JyothiSwaroopReddy07** [comment]
I just forgot it this time.But will handle it from next time.If its not mandatory

**Comment by l5io** [comment]
🚀 Preview for commit b9976dc16667f3979b979c9d72dd1e5fbc0f4d85 at: https://65abb4a0f5229e85a9ff5a17--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Hi @JyothiSwaroopReddy07  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by l5io** [comment]
🚀 Preview for commit 8bcec6727f063ba33fcbc6b070eec63ec88469e4 at: https://65ae328370a8271108649fa1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e3630c80fdd358080ebf62a09e8f3c2131ab1d2e at: https://65ae8be86530be164618ccff--layer5.netlify.app

**Comment by Yashsharma1911** [comment]
@JyothiSwaroopReddy07 checking in, you still working on this?

**Comment by leecalcote** [comment]
No, he's not.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
