### PR TITLE
Fixed the issue with Nighthawk project link issue:#3703

### LINKED ISSUE #3707: Service Mesh Landscape Link 404- Need to know where to redirect.
### Description

Within "Tools" Section of Service Mesh Landscape, the Nighthawk link is 404

### Expected Behavior

The redirect is to [https://github.com/layer5io/nighthawk](url). The question is where does L5 desire to be directed to?
Most of the other links go to source of project, in this case I would expect it to go to, [https://github.com/layer5io/getnighthawk](url) - ?  Unless the purpose is to redirect to 'envoyproxy/nighthawk' :repo
This is a quick fix, and I can do it, or it can be passed to a newcomer, as it is clearly defined in the screenshots, provided, L5 clarifies exactly where they want the link to go.  See SS below.

### Screenshots
Screenshot 2023-02-06 005708
Screenshot 2023-02-06 005809
Screenshot 2023-02-06 005843

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by The-Saras**
**Description**

This PR fixes #3707 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9fd201b3c0e1843b16d5d63d2067a532c19714e6 at: https://63e1219328c8530270112fb5--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
@The-Saras Please update the link as per the suggestion by @leecalcote 
[Link](https://github.com/layer5io/layer5/issues/3707#issuecomment-1419551575)

**Comment by The-Saras** [comment]
Alright I will make the changes...

**Comment by l5io** [comment]
🚀 Preview for commit 9378f56168607e6e2a3bfb859573462d3f84eb37 at: https://63e21e60f64ab9432ff613f6--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @The-Saras 🥇

**Pull request merged**
