### PR TITLE
Blog-sidebar. Make blog category and tag list scrollable.

### LINKED ISSUE #3154: [Blog] Make category and tag list scrollable
**Current Behavior**
With the ever-growing tags and category list for blogs, the sidebar is becoming too long and is overlapping with the footer.

blog-tag-issue

**Desired Situation**
Give the tag and category list a fixed height on the page but make both the the lists scrollable.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by zwwang98**
Signed-off-by: ziweiwang98 <wang.ziwei2@northeastern.edu>

**Description**

This PR fixes #3154 

**Notes for Reviewers**
1. Now the `max-height` is hard-coded. Do we need to make it dynamic to some variable such as the height of the inner`<Link>` component?
2. In the categories scroll list, there is no space between the numbers and the right scroll bar. I think adding some space could look better. For now, I added hard-coded `padding-right: 10px` for the `ul` list.
3. Add dark mode for the scroll bar. I tried this one, but it turned out customized `scrollbar-color` is not supported yet in chrome and most browsers ([reference on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color#browser_compatibility)).
screenshot on MDN scrollbar-color

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0363cec3adfcc9a3a0bfea8b75162f4531d91232 at: https://63282ab2c049e47deaf947dd--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Let's use webkit-scrollbar and scrollbar-color/width in combination. That would cover all the browers.

**Comment by Nikhil-Ladha** [comment]
Just update the scrollbar width, no need to update the color.
And, set the `max-height : 45rem`

**Comment by leecalcote** [comment]
> Let's use webkit-scrollbar and scrollbar-color/width in combination. That would cover all the browsers.

Slowly, but surely, you're coming around. 😁

**Comment by l5io** [comment]
🚀 Preview for commit 237ddb95d2aee6f554e38d402aafdeca9d7a0d8a at: https://632a42c995aa6631f13b364a--layer5.netlify.app

**Comment by debo19** [comment]
@zwwang98 will you share your update on today's websites call?

**Comment by l5io** [comment]
🚀 Preview for commit 03a155b00eefba546bf427d9c3ad059d04b1fd07 at: https://63314ed5b515e8303aa32078--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
The scrollbar width is not yet customised. Try this:
```
ul.scroll::-webkit-scrollbar-thumb {
    background: #a9a9a9;
    border-radius: 1rem;
}
ul.scroll::-webkit-scrollbar-track {
    background: #f0f0f0;
    border-radius: 1rem;
}
ul.scroll::-webkit-scrollbar-button {
    display: none;
}
ul.scroll::-webkit-scrollbar {
    width: 6px;
    display: block;
}

ul.scroll {
scrollbar-width: thin;
}
```

**Comment by Nikhil-Ladha** [comment]
@zwwang98 can you knock-off this small update quickly?

**Comment by zwwang98** [comment]
> @zwwang98 can you knock-off this small update quickly?

Thank you for covering that for me! I really appreciate it!

**Comment by Nikhil-Ladha** [comment]
> > @zwwang98 can you knock-off this small update quickly?
> 
> Thank you for covering that for me! I really appreciate it!

No problem 😄

**Pull request merged**
