### PR TITLE
Deleted service mesh interface

### PR DESCRIPTION
**Pull request by Satakshijain**
**Description**
Deleted service mesh interface from the Partners Page

This PR fixes #10391

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit dc0992524a0720bc27927afd6ab740be13cb3047 at: https://65d970954e6242a4a7b34910--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM. Thank you, @Satakshijain 👍

**Comment by leecalcote** [comment]
Be sure to add the "fixes #" issue number so that the issue auto closes upon merge, @Satakshijain

**Comment by iArchitSharma** [comment]
This issue has already been resolved with this PR - https://github.com/layer5io/layer5/pull/5421/files

**Pull request closed without merging**
