### PR TITLE
Removed duplicate filter button.

### LINKED ISSUE #3151: Duplicate filters on patterns page
#### Description

Two duplicate filters exist  on patterns page from area I section.

image

#### Expected Behavior

 remove one of them.
#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by tiger-yash**
Signed-off-by: Yash Raj <tigeryashraj@gmail.com>

**Description**

This PR fixes #3151 

**Notes for Reviewers**
pattern_filter

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit dcd43b60288fde62f6a036ced3c3eda80339d2aa at: https://634f166147ba243ad7b81137--layer5.netlify.app

**Comment by tiger-yash** [comment]
@legendarykamal @Chadha93 please review....

**Review by legendarykamal — APPROVED** [review]
LGTM 🔹

**Comment by l5io** [comment]
🚀 Preview for commit 324e9288ee31a4a5d48e2e3721cb32da2ab654e1 at: https://6357eb3afc1e4c700a8232bd--layer5.netlify.app

**Pull request merged**
