### PR TITLE
Updated the contacts page design

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR updates the contact page design and a few small changes.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote check the contact form, you won't be able to identify if that's an iframe 😆

**Review by Jashpatel1 — COMMENTED** [review]
The width of the form can be increased in the mobile view.

**Comment by leecalcote** [comment]
What's that saying? A taste of your own medicine... ?  😉

**Comment by leecalcote** [comment]
The form looks super. The whole page does.

I don't seem to be able to submit the form though. Perhaps, this is expected while deploying on netlify.app, though.

**Review by leecalcote — DISMISSED** [review]

**Comment by Nikhil-Ladha** [comment]
> The form looks super. The whole page does.
> 
> I don't seem to be able to submit the form though. Perhaps, this is expected while deploying on netlify.app, though.

I just tried and was able to submit it. Not sure, what failed for you 🤔

**Comment by Nikhil-Ladha** [comment]
There you go @Jashpatel1 💯

**Review by Jashpatel1 — APPROVED** [review]
I haven't checked filling the form. If it's good, we are good to go.

**Comment by Nikhil-Ladha** [comment]
Let's merge and check. It works for me, though 😅

**Comment by Nikhil-Ladha** [comment]
I had wanted to have 2 updates in the brand page:
1. The font-weight of the subtitle can be increased, the same that's mentioned in the figma design.
2. Why are we not using the 'Container' component to wrap the content?

**Comment by Tanuj22** [comment]
> I had wanted to have 2 updates in the brand page:
> 
> 1. The font-weight of the subtitle can be increased, the same that's mentioned in the figma design.
> 2. Why are we not using the 'Container' component to wrap the content?
> 
> @Jashpatel1 , @Tanuj22 if you both also agree on the same, I will push the changes in this PR itself.

Yeah, I agree.

**Comment by Tanuj22** [comment]
Also on the brand page, I noticed that that the download assets point to an URL of the old site. The files should be local to the current branch. Can you fix that also?

**Comment by Nikhil-Ladha** [comment]
> Also on the brand page, I noticed that that the download assets point to an URL of the old site. The files should be local to the current branch. Can you fix that also?

Sure.

**Comment by Nikhil-Ladha** [comment]
Done!
Not used `Container` as the increased width for this page looked better to me 😅

**Review by Tanuj22 — APPROVED** [review]
LGTM

**Pull request merged**
