### PR TITLE
[Content] Architecture Diagramming pages content update

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
- [x] Kubernetes Architecture Diagram page
- [x] AWS Architecture Diagram page
- [x] GCP Architecture Diagram page

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 00334aaf7c238759a629ea4172bc730753670d33 at: https://659d39dd8f8da0a93b2eea6a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 32fede0edbb6bbdc91f738929e1bfbea30bf736a at: https://65a18fe448eafc2e1ba3a1ac--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b15b28f8b56ac778650bb7d0403e50f4301a7e1e at: https://65a19b54cede74388ccbf796--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4166c331d8fbf47e4d35ed90483b7c26d3105461 at: https://65a93dde677b8617aa65e864--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@ritiksaxena124 are we going with that size of gif?

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 are we going with that size of gif?

Yupp

**Comment by l5io** [comment]
🚀 Preview for commit 020232fac3d78e4eb7ba2b29ab686a396d5f5bde at: https://65ae22b170a827059e64a050--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@ritiksaxena124 conflicts..

**Comment by l5io** [comment]
🚀 Preview for commit 0728e666ef4c9029cb4799dccdb16f28b40a45be at: https://65b2697c0768567eea09f502--layer5.netlify.app

**Pull request merged**
