### PR TITLE
made the text transformation smoother on careers cards'

### LINKED ISSUE #5533: Carrers card issue
### Description
When hovering over cards on the website, the text transformation appears to be glitchy and not smooth. This issue is affecting the user experience negatively.

### Expected Behavior
I expect the text transformation on the cards to be smooth and seamless when hovering over them.

### Video

https://github.com/layer5io/layer5/assets/150526286/fb0ee4dc-3e02-4529-bae1-c4dfe88e0e51

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #5533

**Notes for Reviewers**
@Ashparshp can you have a look at it?

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bb34460adca4adeef6074a078d4616d3e6933784 at: https://664f23acef295109d4c4499b--layer5.netlify.app

**Comment by leecalcote** [comment]
Thank you, @hargunkaur286!

**Comment by Ashparshp** [comment]
@hargunkaur286,

Great job on making the text transformation smoother on the careers cards. I've reviewed the code and tested the changes on the [preview link](https://664f23acef295109d4c4499b--layer5.netlify.app/).

**Review by sudhanshutech — COMMENTED** [review]
@hargunkaur286 i can see only the text part is seems glitchy so can you just add smooth transition only for the alignment of text because other part seems fine and they are smooth

**Comment by vishalvivekm** [comment]
Thank you for your contribution @hargunkaur286, 
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by l5io** [comment]
🚀 Preview for commit 7b1ecebadf595b44044e5606ca6d802d3d437bb4 at: https://665701dc601e8b8f1216ad5c--layer5.netlify.app

**Comment by hargunkaur286** [comment]
@sudhanshutech Can you have a look at it? As discussed in Monday's meeting, I have made the content in the centre of the card and added the smooth transition only for the text part.

**Review by sudhanshutech — APPROVED** [review]
lgtm

**Pull request merged**
