### PR TITLE
made some changes in contributing.md file

### LINKED ISSUE #3165: [PR] Add a section to file on how to open new PR for newcomers
**Current Behavior**

As dicussed in the previous meet, many newcomers face the issue of getting started . So this will help them in getting started.
**Desired Situation**

1> A small section needs to be added on how to open your first PR. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

file -> https://layer5.io/community/handbook/contribution
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by nik132-eng**
add icons, and images, and rephrase some sentences for a better understanding

Signed-off-by: nik [77881638+nik132-eng@users.noreply.github.com](mailto:77881638+nik132-eng@users.noreply.github.com)

**Description**

This PR fixes #3165 

**Notes for Reviewers**
try to make the contributor file as helpful and attractive as I can.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fc936d59531a9bea9bb5d65c96f7c54018defb8a at: https://6327125278b23e1f542168ca--layer5.netlify.app

**Review by legendarykamal — CHANGES_REQUESTED** [review]
Can't comment on these changes but these were not intended from the issue and did not involve changes for this file. 

They were for the handbook.

**Comment by nik132-eng** [comment]
ok ok understood


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Nikhil-Ladha** [comment]
Please update the PR with the appropriate changes @nik132-eng

**Pull request closed without merging**
