### PR TITLE
[Home] Banner: MeshMap Video Short

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR adds a new Banner for the homepage that contains an embedded, autoplay video.

**Notes for Reviewers**

In its current state, the PR has bugs:

1. lack of margin on responsive view
1. lack of vertical middle alignment of columns

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Bugs:

Lack of margin in responsive mode.
Lack of vertical middle alignment.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha any issue with putting the video files under `/src/assets/` as versus `/static`?

None, in fa t it should be added under `src/assets` only.

**Comment by l5io** [comment]
🚀 Preview for commit 13b2f252b0d2f23ef8ac6b764f28b52bb3786b3c at: https://62cdeb4ff345e61c93ac3e21--layer5.netlify.app

**Comment by leecalcote** [comment]
@Nikhil-Ladha how do you feel about the new Banner? About the video? Please don't be nice. We already know that you bleed green, MeshMate. Please be critical.

**Comment by l5io** [comment]
🚀 Preview for commit 3b8a485cf172ad3aebd9773a2f6fc196d08d5579 at: https://62cf0d1901cad71caa104568--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ea0c5b984e5cbb125b60affa1f97aa0a12324a76 at: https://62cf24399951cf353d283e00--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
Thank you. Let's see how it goes!

**Pull request merged**
