### PR TITLE
Recognition Programs link added

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**
Recognition Programs link added to both header navigation and footer

image
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8c0f042b624ec1ac3fce1f4f8e5ddd7c2f52993f at: https://6574c11e60517d1a15c11f5c--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @iArchitSharma  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by l5io** [comment]
🚀 Preview for commit 50ea41bbf1f308020a88e9d049552f36da205ed3 at: https://657d2018ad30d46e828e64a0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2f349dda16fdb541545dc4df4da06e04a6f6ed6b at: https://657db3d270b5413da0804587--layer5.netlify.app

**Pull request merged**
