### PR TITLE
[Integrations] Fixed Safari hover animation flicker/shadow cutoff issue  #3359

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes: #3359 

flicker

Added "-webkit-transform: translateZ(0)" to container CSS in the Integration.style.js file

with_translatez

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 03e30c6c152df280984280b6fc8026121ab79865 at: https://6402553b40fadc17b354a56b--layer5.netlify.app

**Comment by leecalcote** [comment]
@divz-codess, please offer review.

**Comment by leecalcote** [comment]
Thank you, @randychilau 👍

**Comment by divz-codess** [comment]
Sure, I'll review it. @leecalcote

**Comment by GaganpreetKaurKalsi** [comment]
Hey @leecalcote, I remember facing this issue in Safari when I worked on the Honeycomb revamp. But now I don't see the issue. Can it be related to Safari version? Just curious. I am using **Safari v16.2**.

**Comment by randychilau** [comment]
@GaganpreetKaurKalsi, to add another data point regarding this issue being related to the Safari version,  I was using v15.6 and seeing the issue. After I updated to Safari v16.3, I no longer see the issue occurring. Thanks.

**Comment by divz-codess** [comment]
Hi @leecalcote and @randychilau I just ran the code locally and found no significant flickering also while viewing the website the flickering isn't there. Maybe the flickering is a versions problem as said by @randychilau which is limited to the safari v15.2 and not on v16.3 on which I tested.

**Comment by leecalcote** [comment]
I suppose this leaves the question of whether inclusion of @randychilau has any negative ramification. It would seem that in merging this PR is helpful is for others that might not have the latest version of Safari.

**Comment by GaganpreetKaurKalsi** [comment]
> I suppose this leaves the question of whether inclusion of @randychilau has any negative ramification. It would seem that in merging this PR is helpful is for others that might not have the latest version of Safari.

I don't see any issues with the PR. Good to merge 👍

**Comment by leecalcote** [comment]
🚀

**Pull request merged**
