### PR TITLE
Updated meshes.yml, non-functional.yml, and added osm.png for OSM Update

### PR DESCRIPTION
**Pull request by phillipgibson**
**Description**

Updated landscape with OSM information

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @phillipgibson 👍

**Comment by Nikhil-Ladha** [comment]
The changes look good, wonder why the netlify build failed 🤔.
Also, @phillipgibson if you could just amend your commit by signing off, then we can have a rebuild. And move ahead.

**Comment by phillipgibson** [comment]
> The changes look good, wonder why the netlify build failed 🤔.
> Also, @phillipgibson if you could just amend your commit by signing off, then we can have a rebuild. And move ahead.

Done.

**Review by leecalcote — APPROVED** [review]
Excellent. Looking good, @phillipgibson. 👍

**Review by leecalcote — APPROVED** [review]

**Comment by PluckyPrecious** [comment]
Fixes #591

**Pull request merged**
