### PR TITLE
layer5 blogs tag and tagcloud

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by gunjanmimo** [comment]
@leecalcote sir, when I am trying to add all the tags in blog.html, is not working with is defined in the archive.html

**Comment by leecalcote** [comment]
@Silvyre do you have any feedback here, by chance?

**Comment by Silvyre** [comment]
> 
> 
> @Silvyre do you have any feedback here, by chance?

I think it's great to have a tagging system! I wish I knew enough to help out @gunjanmimo with the implementation details, but I can at least offer styling feedback.

<hr>

I think delimiting each tag name with commas might improve the look (and enable multi-word tags to be used unambiguously), e.g. 

image

Also, I feel that a bit more white space placed between the blog post content and the tags would be beneficial. A horizontal rule would work, too.

**Comment by gunjanmimo** [comment]
sir i completed the coding part. but i am getting some error. I will discuss with you in slack, may you check my code ?

**Comment by ishita-kumar** [comment]
@gunjanmimo I see that there are conflicts you need to resolve before I can merge your commit. Are you having trouble with that?

**Comment by leecalcote** [comment]
@ishita-kumar i believe @gunjanmimo hs shifted priorities for the time being. Will you proceed with this PR?

**Pull request closed without merging**
