### PR TITLE
change the url for single book, workshop, news pages

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — COMMENTED** [review]
The redirect at line:35 in gatsby-node.js file needs to be changed. It was intended for the service-mesh-labs page, if I am not wrong. Could you please update that as well?

**Comment by Tanuj22** [comment]
> The redirect at line:35 in gatsby-node.js file needs to be changed. It was intended for the service-mesh-labs page, if I am not wrong. Could you please update that as well?

There was no such URL in the old website. Though I have created a redirect for `labs`

**Comment by Nikhil-Ladha** [comment]
> There was no such URL in the old website. Though I have created a redirect for `labs`

Hmm....is there a page on learn/service-mesh in the old site?

**Comment by Tanuj22** [comment]
> > There was no such URL in the old website. Though I have created a redirect for `labs`
> 
> Hmm....is there a page on learn/service-mesh in the old site?

No

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
> > > There was no such URL in the old website. Though I have created a redirect for `labs`
> > 
> > 
> > Hmm....is there a page on learn/service-mesh in the old site?
> 
> No

That's the thing, it was not for the old site, bur only made for the new site. But, since rhe page was changed to service-mesh-labs rhe change in redirect was missed.

**Pull request merged**
