### PR TITLE
Added member profile Alero Awani

### LINKED ISSUE #5586: [Community] Member Profile: Alero Awani
**Current Behavior**

@Alero-Awani has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Alero-Awani as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Alero-Awani
- Twitter: 
- LinkedIn: 
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**

This PR fixes #5586 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8a127f743b7387d5437a3138870cb8daaf38b77d at: https://666de85384039e17e2444dd5--layer5.netlify.app

**Comment by jameshorton2337** [comment]
Ready for review, @Alero-Awani

**Comment by l5io** [comment]
🚀 Preview for commit acab9fec39110a1df49e707c6745b8b0fabadd33 at: https://666e8e4a45ad5fadc76ab488--layer5.netlify.app

**Comment by Deepak0320Singhal** [comment]
@iArchitSharma Thank you for your contribution.
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) .

**Pull request merged**
