### PR TITLE
Added Course-list

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #

**Notes for Reviewers**
I have added Course-list & improved service meshes you learn section.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9df839765e7bc744d225ee81b0b75e9fa7a37379 at: https://60d4ac0b5c0ad22d8b39140b--layer5ng.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Wrap the section within a `Container` for the courses list page.

**Comment by l5io** [comment]
🚀 Preview for commit 1e6191f66b6376fc3f8c777d9f5e625af53228c1 at: https://60d4e57fb6a42870d492c736--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
@Nikhil-Ladha's feedback incorporated. 👍

**Comment by leecalcote** [comment]
Thank you, @chinmaym07!

**Pull request merged**
