### PR TITLE
Testing..

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
So, we are getting the preview now https://603e6c1b8106ee12ec128840--layer5ng.netlify.app/

**Comment by Nikhil-Ladha** [comment]
Without the use of build minutes...

**Comment by Nikhil-Ladha** [comment]
But, there seems to be some issue with commenting back...looking into it

**Comment by leecalcote** [comment]
If the commenting back issue gets solved and we have an automated cleanup process when related PR is merged, this will solve our preview deployment challenge.

**Comment by Nikhil-Ladha** [comment]
Cleanup of the artifacts will happen after 1 day (that's the minimum duration they provide)

**Comment by Nikhil-Ladha** [comment]
> If the commenting back issue gets solved and we have an automated cleanup process when related PR is merged, this will solve our preview deployment challenge.

We don't need to take care of any other cleanup, only the artifacts.

**Comment by Nikhil-Ladha** [comment]
Done!
No credit to me, it's all copy-paste the real development is by them: https://github.com/tiangolo/fastapi 👏🏼

**Comment by Nikhil-Ladha** [comment]
Let's merge

**Review by Tanuj22 — APPROVED** [review]
💥 🎉

**Pull request merged**
