### PR TITLE
[FEATURE] added cursor animation

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6907621cdeb069beb4a05e0ae4793575ce8df019 at: https://657ece46c7a0a558f093a4ac--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Looks good @captain-Akshay  🔥, Great work,  just a small change will you move the cursor only over the image container and not over the whole card because the cursors are hindering the text when they move over the text?

**Comment by AbiodunVlad** [comment]
The feature really looks great.

**Comment by l5io** [comment]
🚀 Preview for commit c2f133cd3642824ed7eea2896a45e034bef6d450 at: https://6580bbe8ad30d422718e7703--layer5.netlify.app

**Comment by leecalcote** [comment]
Whoa, I didn't see this earlier. So, this is pretty neat. It is also slightly distracting. I wonder what we might do to tame it a little; to have it show in another portion of the screen (down lower in addition to around the second section). I wonder if we can have these be a z-index lower than the section information sits, so that the cursors go behind the information that we're presenting instead of in front of the information.

**Comment by l5io** [comment]
🚀 Preview for commit 9e22a1a90c6183071530287d1ac202a1f0db63d2 at: https://6582910d318f7a3c8bc26dd6--layer5.netlify.app

**Review by ritiksaxena124 — APPROVED** [review]
Looks good 🔥

**Comment by leecalcote** [comment]
There's some finesse on display here, @captain-Akshay. Very nice.

**Pull request merged**
