### PR TITLE
Adjust padding/margin of "Image Hub" text

### LINKED ISSUE #2840: Responsive Issue: Adjust padding/margin of "Image Hub" text
**Description**
On the main page, the following text is not responsive:

Screen Shot 2022-05-27 at 4 01 17 PM

**Expected Behavior**
Text should stay within container in small browser sizes.

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by prasanta10**
Signed-off-by: Prasanta Chettri <prasantachettri10@gmail.com>

**Description**

This PR fixes #2840 

https://user-images.githubusercontent.com/91861864/170812935-cb2698fd-d408-40f0-888b-d89ead291a99.mp4

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6a8c1ddc978c837bc45ec22b7196b111280033c9 at: https://6291c08b0b6966443b578287--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6a8c1ddc978c837bc45ec22b7196b111280033c9 at: https://6291c13ab66922467bc92457--layer5ng.netlify.app

**Review by Akshit42-hue — COMMENTED** [review]
Hey @prasanta10, Please sign-off your commit

**Comment by l5io** [comment]
🚀 Preview for commit 6a8c1ddc978c837bc45ec22b7196b111280033c9 at: https://62926a925ebee329c8176bbb--layer5ng.netlify.app

**Comment by Chadha93** [comment]
@prasanta10 try sign-off commits using these commands mentioned here https://github.com/layer5io/layer5/pull/2842/checks.

**Comment by prasanta10** [comment]
@Chadha93 Do I have to submit the pr again after signing-off the commit?

**Comment by Chadha93** [comment]
> @Chadha93 Do I have to submit the pr again after signing-off the commit?

Nope, you can sign-off you commit in this pr also.

**Comment by prasanta10** [comment]
Is it okay if I send another pr with the correct sign-off
> Nope, you can sign-off you commit in this pr also.

**Comment by Chadha93** [comment]
> Is it okay if I send another pr with the correct sign-off
> 
> > Nope, you can sign-off you commit in this pr also.

Let's get you covered this time on DCO. :)

**Comment by prasanta10** [comment]
@Chadha93 Thanks a lot.

**Review by Chadha93 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
