### PR TITLE
[Home] Added new hero: 5 icon

### LINKED ISSUE #1542: [Home] Hero: Create alternative hero: 5 icon
**Current Behavior**
The home page has a single hero created. 

**Desired Behavior**
Ideally, a few versions of the hero section are available to rotate through. There is a hero design with a large "5" icon in the design mockups that would be ideal to have.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by EmperorYP7**
Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>

**Description**

This PR fixes #1542 

**Notes for Reviewers**
- It actually looks nice! 😄 

Screenshot 2021-02-19 at 12 27 00 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @EmperorYP7. Does this include the semi-transparent, overlapping circles as well?

**Comment by leecalcote** [comment]
Oh, I see. This is in a draft state. Carry-on!

**Comment by EmperorYP7** [comment]
> Does this include the semi-transparent, overlapping circles as well?

@leecalcote I wasn't able to access the Figma project you referred to. However, I can replicate it with CSS. But, I would still need the exact color shades and size for it. So, may I get the access to Figma project by any chance?

**Comment by leecalcote** [comment]
Invite on its way...

**Review by leecalcote — CHANGES_REQUESTED** [review]
This is to be a second, additional hero to rotate users through randomly. 

@vineethvanga18 is working on a randomizer.

**Comment by EmperorYP7** [comment]
> This is to be a second, additional hero to rotate users through randomly.
So do I need to preserve the previous hero? 🤔

**Comment by leecalcote** [comment]
Right, yes. 

More context - https://github.com/layer5io/layer5/issues/1543

**Comment by leecalcote** [comment]
Yes, please do create this as a separate component/html from the current banner.

**Comment by EmperorYP7** [comment]
Aye aye captain @leecalcote!

**Comment by EmperorYP7** [comment]
Closing this. (Just realised the base branch should be `master` 🤦🏻 )

**Pull request closed without merging**
