### PR TITLE
Update blogSidebar.style.js issue #3231

### LINKED ISSUE #3231: padding required between email input label and subscribe button this breaks responsive on small screen
#### Description

on the blog route, there is no padding between  subscribe button and the input email label which makes it looks weird and it is breaking responsiveness on small screens 
#### Expected Behavior

there should be some padding to separate them and fix responsiveness on small screen 
#### Screenshots

image

image

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AbhishekTiwari23**
Signed-off-by: Abhishek Tiwari <97469132+AbhishekTiwari23@users.noreply.github.com>

**Description**
Solved issue #3231 by changing the padding of the left and right sides of subscribe button

This PR fixes #3231 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 87c013664327d4222b04acd1170a9ba5c5b1033a at: https://634053d61db6052263785777--layer5.netlify.app

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 please update the description with the before and after ss 👍 .

**Comment by Nikhil-Ladha** [comment]
Interestingly, I don't see this issue at all. Can you share the resolution at which you are seeing this issue?

**Comment by legendarykamal** [comment]
> Interestingly, I don't see this issue at all. Can you share the resolution at which you are seeing this issue?

exactly me too I couldn't replicate, that's why I asked for before and after ss. Maybe I am missing something 🤔

**Comment by AbhishekTiwari23** [comment]
> Interestingly, I don't see this issue at all. Can you share the resolution at which you are seeing this issue?

Actually someone else created this issue, #3231

**Comment by Nikhil-Ladha** [comment]
And, you made a fix without checking the reproducer? 🤦🏼‍♂️

**Comment by AbhishekTiwari23** [comment]
@Nikhil-Ladha and @legendarykamal, sir, I want a suggestion from your side. Please guide me, I want to be a regular contributor to layer5, and till now, I only fixed 1 or 2 padding and margin-related issues. Now I can read the code of this repo, and I want to know which stuff I should learn to be an excellent open-source contributor.
And Thanks to both of you from the bottom of my heart

**Comment by AbhishekTiwari23** [comment]
> And you made a fix without checking the reproducer? 🤦🏼‍♂️

I apologise for this

**Comment by legendarykamal** [comment]
No worries @AbhishekTiwari23 I wasn't in the loop otherwise would have unassigned you 💭.

There are some `help wanted` issues that you should target to achieve in as you see they really need some help and focus.
The site runs on `Gatsby` and knowing about it will help you go forward.

**Pull request closed without merging**
