### PR TITLE
Two KubeCon Press Releases

### PR DESCRIPTION
**Pull request by debo19**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @debo19 🙂

**Comment by l5io** [comment]
🚀 Preview for commit 50ccb7a3f135d4abb6c1b581fc54e2c812906b75 at: https://6162f3e4c3dcde5c4407e29b--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@leecalcote good to merge?

**Comment by leecalcote** [comment]
update

**Pull request merged**
