### PR TITLE
Much spaces between contribution and General contribution flow 2

### PR DESCRIPTION
**Pull request by sarkartanmay393**
**Description**

This PR fixes #

Issue: #4636

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@Ghat0tkach There's new code with no extra indentations

**Comment by Ghat0tkach** [comment]
@sarkartanmay393 
I think this will solely fix the issue isnt it 
https://github.com/layer5io/layer5/issues/4636#issuecomment-1654649633

**Comment by sarkartanmay393** [comment]
@Ghat0tkach I don't see so. If only decrease the margin-top -46, it will fix in mentioned pages but destroy already looking good pages.

https://github.com/layer5io/layer5/assets/84321236/29b2b401-ecb6-42bf-8e50-ee34c37b726b

Yeah, sure. Sorry for my behaviour though. 🙏🏼

**Comment by l5io** [comment]
🚀 Preview for commit 9fb56ffcb648ef7d6757c4c2ecf15b8688605802 at: https://64cd348129c95438bffdbd4b--layer5.netlify.app

**Review by Mohith234 — APPROVED** [review]
@sarkartanmay393 Agree with the mentioned point. It may change the layout of other pages

Meanwhile, the changes you've made solved the issue. I feel the preview is as expected.

**Comment by Ghat0tkach** [comment]
Hey @sarkartanmay393 


Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by l5io** [comment]
🚀 Preview for commit 369bf63d6f3de40168e70d8a9a56af1332db0951 at: https://64d0b22a8bc4d050a865142c--layer5.netlify.app

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
@sarkartanmay393, we will be needing to update the current style not introduce new ones

**Comment by Chadha93** [comment]
> @sarkartanmay393, we will be needing to update the current style not introduce new ones

@sam1code, thoughts?

**Pull request closed without merging**
