### PR TITLE
chore : Added whitespace on community page

### LINKED ISSUE #2408: Missing whitespace
**Description**
There's a missing whitespace between "Map" and "the" on https://layer5.io/community.  
Screenshot 2021-12-10 at 12 13 52 PM

**Expected Behavior**
Add space. 

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Added missing white space on the community page between 

This PR fixes #2408 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — APPROVED** [review]
LGTM. Good work @Abhijay007 🎉

**Comment by l5io** [comment]
🚀 Preview for commit 467678e934448790f26a1b4185dfb6141b505ea6 at: https://61b4633e874cf8ae696e59ef--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, thank you @Abhijay007

**Comment by Abhijay007** [comment]
thanks, @warunicorn19 @sayantan1413, I want to contribute more in layer5. org, can you please suggest to me some more issues and projects contribute to !!

**Pull request merged**
