### PR TITLE
Added Designer Page and hyperlink to UX Badge

### LINKED ISSUE #4107: [Community] Writing Badge needs hyperlink to Writing Program page
### Description
Each community member has the opportunity to earn a badges for display on their profile. Each badge is linked to their respective project.

The writing badge is missing such a link.

### Expected Behavior
Need to link to https://layer5.io/community/handbook/writing-program

### Screenshots

Screenshot 2023-04-18 at 4 42 57 PM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Description**

This PR fixes #4107
The issue was with ui/ux'er badge, not the writers' badge 

**Notes for Reviewers**

- Added Description about UI-UX contribution  under newly made designer section
- Added hyperlink to UX badge

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 03f6668617c107b922401ab7ff375fa3d4604d06 at: https://64676fc1e3954f08760b2919--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f789db195c0feef2e3213eeffa1561d06a0cb67b at: https://646a2fdb4c94eb0865fd3a4f--layer5.netlify.app

**Comment by ayushthe1** [comment]
@thisiskaransgit  Let's discuss this on websites call. Add this as an agenda item in meeting minutes if you would :).
I'll add this item for you if it's ok.

**Review by Chadha93 — APPROVED** [review]
Good work @thisiskaransgit . Thanks for the demo on today's call.

**Pull request merged**
