### PR TITLE
Add spacing above the heading #5648

### LINKED ISSUE #5648: Add spacing above the heading
### Current Behavior

Open Source Internship Program heading with it's title needs alignment.

Screenshot from 2024-07-08 04-31-36

### Desired Behavior

Heading should have some space on top as well as on bottom (check with headings of other pages like https://layer5.io/projects)

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by r-kundan**
**Description**

This PR fixes  #5648

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@r-kundan merge conflicts

**Comment by l5io** [comment]
🚀 Preview for commit 34e575f65b8dc4b8faa8a6c1afd1af82b04d231d at: https://66a11424c0cd8e42f184f855--layer5.netlify.app

**Comment by Ashparshp** [comment]
@r-kundan Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by sudhanshutech** [comment]
Hey @r-kundan it is great you are contributing but it will also be good if you can join and present in the meetings unless we will not able to give you correct feedback you needed.

**Comment by Ashparshp** [comment]
@r-kundan Any luck?

**Comment by sudhanshutech** [comment]
@r-kundan closing this pr since i didn't heard from you and you are not available to any calls to share your progress. Feel free to reopen the pr when you are present. Thanks

**Pull request closed without merging**
