### PR TITLE
Grid/list consistency in Blogs  

### LINKED ISSUE #4288: making the list/grid view consistent.
> 
> Let's make the list/grid view consistent.
> We are not showing the sidebar after a certain resolution is Grid view and also have a `max-width` property 
> defined for the search bar. 
> Please check the stylesheet of grid view and update the list view CSS  accordingly.

_Originally posted by @Nikhil-Ladha in https://github.com/layer5io/layer5/pull/3923#pullrequestreview-1334222505_

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Description**

This PR fixes #4288 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cb59d6734680b8b37b9762e2fecd1a0ea35e97f1 at: https://646e6b0f2be5f216d28c2e73--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for this, @thisiskaransgit. Given the potential number of times that these styles were used, let's exercise some diligence by identifying which blog posts are affected, so that we can visually inspect and ensure their presentation remains intact (isn't negatively impacted). Will you itemize the blogs affected by listing them by URL?

**Review by Nikhil-Ladha — COMMENTED** [review]
Looks good overall, though some change needed.
The search bar is not consistent from 576px-574px, please fix that.

**Comment by thisiskaransgit** [comment]
- @leecalcote, these changes will not affect the individual blogs, the scope of the changes is fixing the inconsistency of styles between the content layout for list view and grid view.
- @Nikhil-Ladha, thanks for pointing it out, have done the required changes.
- @Chadha93, I've added the top margin in the grid view as asked by you in the meeting.

Please take a look now.

**Comment by l5io** [comment]
🚀 Preview for commit dc398e5293228549d61770f14f0ff310966861c9 at: https://6478c3eef0c150259abd07e4--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@thisiskaransgit Thanks for this. Let's merge!

**Pull request merged**
