### PR TITLE
replaced dark github logo to light logo

### LINKED ISSUE #3785: [UI] The GitHub logo should be replaced with light-version when site in dark-mode
### Current Behavior
when in dark mode the GitHub logo is in black on https://layer5.io/cloud-native-management/meshery/operating-service-meshes

logo-error

### Desired Behavior
The GitHub logo should be replaced with the light version of it when the site is in dark-mode 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hirentimbadiya**
**Description**

This PR fixes #3785 

**Notes for Reviewers**
replaced light and dark logo for both light and dark mode.

https://user-images.githubusercontent.com/86219935/232466059-b09640ea-bdd1-43c9-a24e-a185792ae7b6.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c2f5e4e2b8bddfbbfdf99a2c0d7f4bf9b90eacd5 at: https://643ba082eb3dc20361598a01--layer5.netlify.app

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
a logo like this should be displayed in dark mode 

image

**Comment by hirentimbadiya** [comment]
> a logo like this should be displayed in dark mode
> 
> image



> a logo like this should be displayed in dark mode
> 
> image



> a logo like this should be displayed in dark mode
> 
> image

Should It be only in dark mode or for both light and dark mode

**Comment by hirentimbadiya** [comment]
> a logo like this should be displayed in dark mode
> 
> image

Should it be only in dark mode or for both light and dark modes ?

**Comment by Udit-takkar** [comment]
@hirentimbadiya only in dark mode. you already have light_githubLogo to display in light mode

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya only in dark mode. you already have light_githubLogo to display in light mode

hey @Udit-takkar can you review PR now!

**Comment by l5io** [comment]
🚀 Preview for commit e050e400754ddbdc230a71bb580d59dca56ba5ed at: https://643d2ba162bd4b009cabf264--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Udit-takkar** [comment]
@hirentimbadiya looks great now

**Pull request merged**
