### PR TITLE
Pricing page fixes

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
- Changed Teams: Contact Sales, Enterprise: Coming Soon
- Fixed responsiveness on large screen
- Updated few icons to use filled svgs

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
⚡ 💪

**Comment by debo19** [comment]
@leecalcote To add pricing, I added some other links on the footer so that the number of items is uniform. However, this is making the footer quite big. Should I push or hold off from including the page now?
Screenshot 2022-06-28 at 3 02 59 AM

**Comment by leecalcote** [comment]
Thanks for asking. This amount of largeness is 👌

**Comment by leecalcote** [comment]
@debo19 please remove "Service Mesh Landscape" from Projects to make room for "MeshMap".

**Pull request merged**
