### PR TITLE
new section in meshmap collaboration page

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Description**

This PR fixes # new  section of create, repeat and iterate in meshmap collaborate page

**Notes for Reviewers**
1. Changes need for mobile-view

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Shivam-AfA — COMMENTED** [review]
@sudhanshutech, here are some changes that can be worked upon:
- adding transition animations to the description text.
- change the color of the three terms to the white for dark mode and black for light mode.
- instead of the blur effect we, can use the scaling, i.e the active term could be scaled a bit bigger (on hover).
- You can remove the background gradient, then on hover, the active item will be scaled as well as a transition would take place to green color. (#00d3a9)
- Increase the font size for the description and header would be nice.
- a graphic can be added to accomodate the extra spacing and present a connection beween the three terms.

**Comment by Shivam-AfA** [comment]
@sudhanshutech any updates here?

**Comment by Chadha93** [comment]
@sudhanshutech  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by sudhanshutech** [comment]
@Shivam-AfA removing background gradient making it odd because it is keeping it unique from other components or sections .
Secondly can you suggest some graphics like arrows between terms how we can implement here because i having difficulties in putting svg paths and all

**Comment by l5io** [comment]
🚀 Preview for commit 95f591931225602f696579ae814f91cdab73c51b at: https://64232b8295c5f20c560309a7--layer5.netlify.app

**Comment by leecalcote** [comment]
merge conflict...

**Comment by sudhanshutech** [comment]
I am closing this pr because it is having merge conflicts and local error which will create errors in master branch. I will raise another pr for this section.

**Pull request closed without merging**
