### PR TITLE
Duplicated filters on patterns page

### LINKED ISSUE #3151: Duplicate filters on patterns page
#### Description

Two duplicate filters exist  on patterns page from area I section.

image

#### Expected Behavior

 remove one of them.
#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Nawaz027**
Signed-off-by: Nawaz027 <nawazsiddiqui27@gmail.com>

**Description**
removed one of the duplicated filters on patterns page from area I section.
Link of the webpage:
https://layer5.io/learn/service-mesh-books/service-mesh-patterns

This PR fixes #3151

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @Nawaz027

**Comment by l5io** [comment]
🚀 Preview for commit 22ee6cf40e66a8234eeda570c7451886a5f8e99d at: https://631810e038c781471e74316a--layer5.netlify.app

**Comment by legendarykamal** [comment]
@Nawaz027 the git-police has arrived , please fix the dco :smiley:

**Comment by leecalcote** [comment]
Even better, here are instructions to amend your sign off - https://github.com/layer5io/layer5/pull/3157/checks?check_run_id=8226220403

**Comment by Nawaz027** [comment]
Thanks, I am doing it😃

**Comment by Nawaz027** [comment]
I guess I messed things up. Closing this PR and creating a new one.

**Comment by leecalcote** [comment]
Hint: make sure your fork is synced.

**Comment by Nawaz027** [comment]
😅😅 sure

**Pull request closed without merging**
