### PR TITLE
Displaced Image Hub with Nighthawk

### LINKED ISSUE #2741: [Homepage] Displace Image Hub with Nighthawk
**Current Behavior**
Nighthawk is a project in need of representation on the homepage.

**Desired Behavior**
The card for Image Hub can be replaced with one for Nighthawk.

**Screenshots / Mockups**
Screen Shot 2022-04-28 at 5 20 51 PM

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by prasanta10**
Signed-off-by: Prasanta Chettri [prasantachettri10@gmail.com](mailto:prasantachettri10@gmail.com)

**Description**
Screenshot 2022-05-27 020801

This PR fixes #2741 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by prasanta10** [comment]
@leecalcote could you please review it. Thank you!

**Review by Akshit42-hue — COMMENTED** [review]
Hey @prasanta10, DCO is failing, please signoff the commit

**Comment by leecalcote** [comment]
Let me grease the wheels of progress here and bypass this requirement on this PR.

**Comment by leecalcote** [comment]
Thanks for picking this one up, @prasanta10 👍

**Pull request merged**
