### PR TITLE
[LHCI] Proposal to move audit tests to use categories in “warn” mode 

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR is a proposal to update Lighthouse CI (LHCI) check to pass for running the tests and creating reports successfully, but keep contributors, maintainers, and performance monitors aware of any serious site performance issues and where/how to resolve them.

This PR depends on what Layer5 wants this failure messaging to mean:

image

- If the desire is to have this check fail as long as the site pages are not passing the LHCI preset benchmarks, then improved messaging can be provided to contributors on what to expect when submitting PRs.

- If the desire is to have the check reflect successfully running the LHCI tests and uploading the audit report for review by the contributor and others, then this PR provides that option.

image

image

image

[sample uploaded report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1687216647726-21217.report.html)

image

---

**Notes for Reviewers**

First off, thanks to the extensive ongoing work by [@ayushthe1](https://github.com/layer5io/layer5/pulls?q=is%3Apr+is%3Aclosed+author%3Aayushthe1+lighthouse), @Udit-takkar, and others in resolving LHCI reported issues and improving the site's performance and LHCI scores. 

---

Each submitted PR runs through a series of checks, one of which is the LHCI workflow, which currently always results in an error:

image

image

The PR author will also receive an email regarding the failed check:

image

---

I believe the error is mainly due to two reasons:

- Target urls are not loading correctly for testing
- Using the [assert preset `lighthouse:no-pwa`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#preset) that does not allow warn mode, and automatically fails the check on any failed test.
image

The url issue is resolved by changing the CI variable for the `npm run build` command in the LHCI workflow (more information in PR #4397).

The assert preset issue is that it sets all the tests to be run in `error` mode by default, and you have to configure each individual test if you want otherwise (no ability to set all tests at once):
>error - The audit result will be checked, the result will be printed to stderr, and failure will result in a non-zero exit code.

The same tests in `lighthouse:no-pwa` can be run by [using categories](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#categories) which allow setting all tests in that category to `warn` mode:
>warn - The audit result will be checked, and the result will be printed to stderr, but failure will not result in a non-zero exit code. 

`warn` mode testing will allow the LHCI to show a green check for successfully running the tests and uploading an audit report for each url in the test scenario.

---

It is important to know about the LHCI issues on Layer5 pages, however it can be confusing to contributors to understand why the LHCI check is failing when the PR they submitted may or may not involve the pages failing the LHCI audit.

I look forward to your comments and discussion on this.

Cheers,
Randy

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e5516e2a3919109968864894f46b8811fcfff5cc at: https://6490df9573a33f402bc9dfd0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 163a696d20e311e1a9513f75b22d12244d672e53 at: https://6490e9cf03357648b368d456--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 76d8f10508c59dec72dc22cf513a3952162add65 at: https://64915c523457c605610cb24f--layer5.netlify.app

**Review by ayushthe1 — COMMENTED** [review]
Thanks for the work @randychilau .Getting the lighthouse report on a page would help a lot in solving the error. I think we should increase the `.minScore` to `0.9` for all categories.

**Comment by randychilau** [comment]
Hi @ayushthe1,

Thanks for going through this PR and the feedback.

As mentioned, the mobile audit configuration file has been updated with all categories set to have a `minScore` of `.90`.

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 4db1c23f901a86a6c8626f2a077718f349a99521 at: https://64987a6f1428002c21eb46f5--layer5.netlify.app

**Review by ayushthe1 — APPROVED** [review]
Thanks for the changes @randychilau .It should now be good to go.

**Comment by leecalcote** [comment]
Randy, Randy, Randy. 😍

**Comment by leecalcote** [comment]
@Nikhil-Ladha do we have your ✅ on this one?

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm, this would be a better approach.

**Pull request merged**
