### PR TITLE
Add Use-Cases Page

### LINKED ISSUE #5190: [UI] Implement the Use cases page
### Current Behavior
We don't have a page on the layer5.io site where we list all the use cases of our product

### Desired Behavior
Implement the new page for use cases. 
- URL can be _layer5.io/use-cases_
- Reuse the already available component for creating the page

### Screenshots / Mockups
**Figma mockup** [link](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=22614%3A2202&mode=design&t=e0WXbkXFLIZht76u-1)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Akshun-01**
**Description**
Add the frontend for the UseCases Page

This PR fixes #5190 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Hi @Akshun-01  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by Akshun-01** [comment]
Hey @saurabh100ni, really sorry. 
But I am not available for today's meeting.
Can I attend and share this issue in some other meet this week?

**Comment by saurabh100ni** [comment]
Thanks for sending the word @Akshun-01,
We will go through this in today's meet for the feedback, You can also share your updates in Slack and we can have your agenda next week.

**Comment by iArchitSharma** [comment]
As there is no updates from the Assignee

**Pull request closed without merging**
