### PR TITLE
Dynamic Imports of Component in Sistent documentation 

### LINKED ISSUE #6065: Enable Dynamic Imports in Sistent Documentation to Improve the Component Addition Process.
### Current Behavior

Currently, adding a new component to the Sistent library documentation requires modifying eight separate files, which includes navigating through dynamic pages and manually setting up each component. This process is repetitive and prone to errors.

image

### Desired Situation

The goal is to dynamically add new components without modifying multiple files. This change would streamline the process, reduce boilerplate, and allow for faster and more reliable updates.

- [ ] Refactor code to support dynamic loading of new components in the documentation.
- [ ] Update navigation to detect and list new components automatically.
- [ ] Test dynamic component imports to ensure compatibility with existing structure.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Vidit-Kushwaha**
**Description**

This PR fixes #6065 by refactoring the dynamic page creation logic. The code now includes improved modularity, better error handling, and reduced redundancy, ensuring a cleaner and more maintainable implementation.

**Notes for Reviewers**
 - dynamically generate individual pages for each component using the `createPage` API in `gatsby-node.js`.
 
Please review and suggest improvements if necessary. Thank you!

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
image

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@Vidit-Kushwaha checks are failing...

**Comment by Vidit-Kushwaha** [comment]
Let me see

**Comment by l5io** [comment]
🚀 Preview for commit e60b96521498e64c07593a7845692cdbd1e42c0e at: https://673b0017a0fc2e03025db33d--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Vidit-Kushwaha 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST

adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
