### PR TITLE
Page jumps to about halfway down the page on load

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
This behaviour is taking place after [this](https://github.com/layer5io/layer5/pull/2628/files) update. Testing to see if this fixes the problem.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you

**Comment by l5io** [comment]
🚀 Preview for commit 60ac89ec71490b0c841dbe15dfd0fab8236b97ad at: https://62333a97a1e8440e25aba413--layer5ng.netlify.app

**Comment by debo19** [comment]
@leecalcote this is working. We're good with the downgrade in version right?

**Comment by leecalcote** [comment]
> @leecalcote this is working. We're good with the downgrade in version right?

@debo19, yes, although, inevitably dependably or another contributor will intentionally or inadvertently attempt to upgrade this package and the maintainer will forget that about this behavior, merge, and land us back in the same situation that we're in.

We can downgrade now and open a new issue to track this as an incompatibility issue that needs addressed. An issue can be opened on the package or a new package can be sought.

**Review by warunicorn19 — APPROVED** [review]
@debo19 merging for now, if you could look into if we need a new package or not.

**Pull request merged**
