### PR TITLE
Improved the UI of meshery page

### LINKED ISSUE #627: Improve the UI of meshery page
**Current Behavior**
There are a lot of things in the [meshery](https://layer5.io/meshery) page that might need to be changed. 

- Go to the meshery page - https://layer5.io/meshery
- Scroll down the page & see.

**Screenshot** 
Layer5-Meshery

In reference to the screenshot above, we can refine the following marked items.

- Align the contents `Baseline, Measure, and Assess` card properly (align-center).
- Fix the padding of the embed YouTube video in center.
- In the `Community` section, those icons needs to be properly scaled & aligned.
- I think the `Fork me on Github` ribbon doesn't look good on `Community` & `Service Mesh Performance Specification` section. We may remove one from the community section.
- The svg in the subscribe section needs to be magnified a little bit.

@leecalcote @chandrashritii 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**
Improved the UI of meshery page! Fixed unoptimized media queries and scaling. Fixed visible errors in responsive mode.

This PR fixes #627 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@Nikhil-Ladha @leecalcote there you have it :rocket: :smiley:

**Comment by leecalcote** [comment]
Ha! Good deal, @Neilblaze. 

An item to take a look at (I'm using Safari):

Screen Shot 2020-08-18 at 4 22 10 AM

**Comment by Neilblaze** [comment]
> Ha! Good deal, @Neilblaze.
> 
> An item to take a look at (I'm using Safari):
> 
> Screen Shot 2020-08-18 at 4 22 10 AM

Yeah I saw that one in the first deploy preview 😅
But I fixed that [here](https://github.com/layer5io/layer5/pull/639/commits/c5bd4855dae2631757374cbd64531d530029c5b9)! :smile:

**Comment by Nikhil-Ladha** [comment]
Everything looks good, just one more item that you would like to tick-off over here is this one:
Screenshot_20200818-150034
After this we will be good to go.

**Comment by Neilblaze** [comment]
@Nikhil-Ladha maybe the change you are saying to do is device dependant. I opened that deploy preview on my smartphone, I couldn't see anything to be changed. I am attaching one here for the reference

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha maybe the change you are saying to do is device dependant. I opened that deploy preview on my smartphone, I couldn't see anything to be changed. I am attaching one here for the reference

Have you uploaded the image?

**Comment by Neilblaze** [comment]
@Nikhil-Ladha check now

**Comment by Nikhil-Ladha** [comment]
Aahh! You need to click on `click here` under Kubernetes User to see that.

**Comment by Neilblaze** [comment]
Oh my bad 😅

**Comment by Neilblaze** [comment]
@Nikhil-Ladha maybe we can remove the popup modal and keep it as it is? What say?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha maybe we can remove the popup modal and keep it as it is? What say?
> like what's there in the `bash & brew user` part!

Even then the issue would come up. My suggestion would be to think for a solution in the current design like it's done for the above ones and also you can take some design inspiration from the meshery.io site. A similar thing was done there too.

**Comment by Neilblaze** [comment]
> > @Nikhil-Ladha maybe we can remove the popup modal and keep it as it is? What say?
> > like what's there in the `bash & brew user` part!
> 
> Even then the issue would come up. My suggestion would be to think for a solution in the current design like it's done for the above ones and also you can take some design inspiration from the meshery.io site. A similar thing was done there too.

Okay lemme see what tweaking can be done

**Comment by Neilblaze** [comment]
@Nikhil-Ladha how is it now?

**Comment by leecalcote** [comment]
Looks much improved to me. 👍

**Comment by Neilblaze** [comment]
@leecalcote Glad you liked it 😄

**Pull request merged**
