### PR TITLE
issue/remind label updates for PRs

### LINKED ISSUE #2149: [CI] Updates label `issue/remind` for PRs
**Current Behavior**
Currently, the label `issue/remind` doesn't work for PRs

**Desired Situation**
The label should work for PRs as well.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by MukulKolpe**
**Description**
Updated issue/remind label for the PRs
This PR fixes #2149 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 90093d6599189ae6642b009b19a8c812cbe0de67 at: https://6136870d57b42a75290ab477--layer5ng.netlify.app

**Comment by Tanuj22** [comment]
@MukulKolpe can you update it according to this https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml

**Comment by warunicorn19** [comment]
That is, @MukulKolpe if you could add the label-commenter to work for `issues` as well

**Comment by MukulKolpe** [comment]
Hey @Tanuj22, @warunicorn19 I noticed that there are no line spaces between 'action' and the name of the other label in https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml but they are in https://github.com/layer5io/layer5/blob/master/.github/label-commenter-config.yml can that be the reason behind label-commentator not working for the issues??

**Comment by warunicorn19** [comment]
@MukulKolpe Ummm🤔, no that shouldn't cause a difference.

**Comment by l5io** [comment]
🚀 Preview for commit 5ec94236ed53943f7a60a3910634e7426328027c at: https://6137b1041aa24814fb26bd91--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, thanks @MukulKolpe

**Review by Tanuj22 — APPROVED** [review]
Thank you @MukulKolpe

**Pull request merged**
