### PR TITLE
Meshmap text cutting issue resolved

### LINKED ISSUE #3222: BUG : Text cutting after the animation in Meshmap site
#### Description

I have noticed that the animation of the mesh map site ends up with the text which looks to be cut.

https://layer5.io/cloud-native-management/meshmap

#### Expected Behavior

Full view of the text

#### Screenshots

Screenshot 2022-09-30 at 9 23 35 PM

#### Environment:
- Host OS: MacOS, Windows
- Browser: Chrome, Safari, Brave

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sandeepB3**
Signed-off-by: Sandeep Pillai [sandeepxpillai@gmail.com](mailto:sandeepxpillai@gmail.com)

**Description**
Text cutting after the animation in Meshmap site resolved, unnecessary addition of class 'designer-img' inside img tag.

This PR fixes #3222

**Notes for Reviewers**
Screenshot 2022-10-13 at 1 53 45 AM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a597eecc9dcf1a8b54fcbeeda4248c7f4eb7769c at: https://6347f30e879b6a1d1bef7d63--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Well, that class is not "unnecessary", it adds a bit of margin if not the shadow and radius. So, a better fix would be to reduce the margin or set the height to something around 40rem (instead of using relative height, i.e, vh)

**Comment by sandeepB3** [comment]
Hey @Nikhil-Ladha, thank you for your help. Actually the class "designer-image" was only used inside the img tag for Meshmap Designer and not inside the img tag for Meshmap Visualizer. Now I understood my silly mistake. Thankyou.

**Comment by sandeepB3** [comment]
Made the required changes. Please verify! Thank you.

**Comment by l5io** [comment]
🚀 Preview for commit 2ab25992abcf473f0d4826ac278138edf0f46f20 at: https://634834e8872b940401e2ec1b--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good

**Pull request merged**
