### PR TITLE
New Products page implementation 

### LINKED ISSUE #4742: [Site] Implement New Products Page
### Current Behavior
Implement a new products page, replacing the current product/project page.
https://layer5.io/projects

### Desired Behavior
Use the below Figma Mockup to implement the products page.
Note - Don't delete the current products/projects page, archive it (move it to legacy).

### Screenshots / Mockups
Figma - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=17471-2842&mode=design&t=QJuEVUIqDSZd1CIC-0

### Acceptance Tests

- Reusable components.
- Reusable styles.
- Follow design colors and Qanelas Soft font. 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #4742 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
hii @ShravaniAK and @Modern-artist  , 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Chadha93** [comment]
Build is failing.... @Modern-artist @ShravaniAK

**Comment by dibyendu02** [comment]
Are you guys done with the product page implementation?

**Comment by l5io** [comment]
🚀 Preview for commit 8c51777c6e082a698116d8460e2d54d4b93d3da4 at: https://64f444d52d475576f3afcdb8--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ad0e11f795e64dd8fd3e07f581bceb4cd9e904ed at: https://64fc73c9cef1e1645514555f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bf08a5a9c606084628dff4e4273e0e0981e3f344 at: https://64fc95a6db4b097489a18544--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4a956ea51494088d72aad8a1f62c327076daf618 at: https://64fcc0c2ece3551ae4c203aa--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 057ea78958b6f9c225a7a6ca4f9dadfad5283c81 at: https://64fd301fecfe8350655869a9--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
uh-huh @ShravaniAK @Modern-artist 
DCO check is failing

**Comment by l5io** [comment]
🚀 Preview for commit 7e3f1c2ce103c87cfc4e4345db7fa7928c18f8b9 at: https://64fe933e2ec0d9189fcd0341--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 20b0bebb4e382ea39241459995dce1ad411f9aa4 at: https://64fed26a2ec0d93f1ecd02c0--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Hey, @ShravaniAK will you update the buttons component in the first two sections of the page similar to what is used in the "explore" button

Screenshot 2023-09-11 143538

**Comment by l5io** [comment]
🚀 Preview for commit 2646f0d7df206bac56a2dae2df194d0b71337eec at: https://6500021cecfe832706586f14--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0a854f8df4c1aebda3f04eb60f4155d4a432e23b at: https://65013f1adb0ad0374a7223ce--layer5.netlify.app

**Comment by sudhanshutech** [comment]
https://github.com/layer5io/layer5/pull/5097

**Pull request closed without merging**
