### PR TITLE
Hero images leave much whitespace #3221

### LINKED ISSUE #3221: Single Pages: Hero images leave much whitespace
#### Current Behavior
Hero images on single page entries across many of the collections (like blog posts, events, resources, news, and so on), don't fill the space afforded to the image, but instead leave a smaller image with extra, unused whitespace.

The current CSS with `object-fit: contain;` _should_ work, but seems to not be having the desired affect given conflicting(?) CSS.

#### Desired Behavior
It would be nice to have the images fill the empty space.

#### Screenshots / Mockups
example: https://layer5.io/community/events/hacktoberfest-prep-easing-into-cncf-open-source-projects

Screen Shot 2022-09-30 at 12 21 47 PM

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AbhishekTiwari23**
Signed-off-by: Abhishek Tiwari <97469132+AbhishekTiwari23@users.noreply.github.com>

**Description**
Solved issue #3221 by adding some lines of code that will remove unwanted white space.
This PR fixes #3221 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a9b12541a396d622712535cb0ced8e65579a7228 at: https://63544f94b1df72612c909884--layer5.netlify.app

**Comment by AbhishekTiwari23** [comment]
@Nikhil-Ladha, sir, please look at this one. If you want any changes or anything else, please let me know. I am waiting for your advice.
Thanks.

**Comment by debo19** [comment]
@AbhishekTiwari23 Will you discuss your PR on the websites call today?

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 Will you discuss your PR on the website call today?

I joined the meeting, but I was late. Any issue regarding the PR?

**Comment by leecalcote** [comment]
@AbhishekTiwari23 I believe that an asset of the difficulty in getting the appropriate amount of whitespace assigned is that of separate handling of SVGs by the Gatsby image component. There is some additional investigation needed in the case of SVGs, I believe.

**Comment by leecalcote** [comment]
I think this is a good update for PNGs, though.

**Comment by l5io** [comment]
🚀 Preview for commit 5502a1e9338edb72bcf763427381838db8aa18ff at: https://6356a85d1f0a1e53a96328ef--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @AbhishekTiwari23

**Comment by leecalcote** [comment]
> @AbhishekTiwari23 I believe that an asset of the difficulty in getting the appropriate amount of whitespace assigned is that of separate handling of SVGs by the Gatsby image component. There is some additional investigation needed in the case of SVGs, I believe.

@AbhishekTiwari23 it'd be great if you will follow up on the styling (trimming whitespace) around SVG-based featured images.

**Comment by AbhishekTiwari23** [comment]
> > @AbhishekTiwari23 I believe that an asset of the difficulty in getting the appropriate amount of whitespace assigned is that of separate handling of SVGs by the Gatsby image component. There is some additional investigation needed in the case of SVGs, I believe.
> 
> @AbhishekTiwari23 it'd be great if you will follow up on the styling (trimming whitespace) around SVG-based featured images.

Ok, sir.

**Pull request merged**
