### PR TITLE
Animation update on Prdouct pages

### PR DESCRIPTION
**Pull request by iArchitSharma**
**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d3eaa23b0e452ecd78a4b65430279b692b39b53a at: https://65cf75a3a9cba410b37a79ef--layer5.netlify.app

**Comment by leecalcote** [comment]
Looking...

**Comment by iArchitSharma** [comment]
@leecalcote no, AWS, GCP, Kubernetes one are -
https://65cf75a3a9cba410b37a79ef--layer5.netlify.app/cloud-native-management/generate-aws-architecture-diagram

**Comment by leecalcote** [comment]
@iArchitSharma can I ask that this animated gif be re-recorded?

**Comment by leecalcote** [comment]
The copy / paste of IDs feels not good and all the red doesn't either.

**Comment by leecalcote** [comment]
> The copy / paste of IDs feels not good and all the red doesn't either.

@ritiksaxena124 or the long pause.

**Comment by vishalvivekm** [comment]
@iArchitSharma 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit 4643c3033406e7f5af357edf9175345842c92425 at: https://65dde78cf20ab91873c09fd5--layer5.netlify.app

**Pull request merged**
