### PR TITLE
new member added Amit Amrutiya

### PR DESCRIPTION
**Pull request by Dip-Gyawali**
**Description**

This PR adds a new member, Amit Amrutiya, to the member list. The member details have been added to the list, and the changes have been verified.
Screenshot 2024-08-27 180424

Fixes: #5838 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [yes ] Yes, I signed my commits.

### CODE REVIEW

**Comment by hargunkaur286** [comment]
Please sign off your commits. you can refer the [contributing guide](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) to learn how to do it.

**Comment by l5io** [comment]
🚀 Preview for commit 1827efb0969d5747b0abc389d48f684e87671767 at: https://66cdcd046d5a2cfa6c09b821--layer5.netlify.app

**Comment by amitamrutiya** [comment]
Nice work @Dip-Gyawali. Thanks for making this PR 🙂.

**Comment by Dip-Gyawali** [comment]
@amitamrutiya your welcome it was my pleasure working on this.

**Comment by hargunkaur286** [comment]
Thank you for working on this, @Dip-Gyawali you can also add Amit's cloud profile link and then I think we will be good to go!

**Pull request merged**
