### PR TITLE
[Blog] Blog on my Open source journey with Layer5

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
This is my first ever blog. 

This PR fixes #

**Notes for Reviewers**
Please read it thoroughly and suggest any suggestions like catchy headlines, subheading, or anything you like, I would like to hear your thoughts before publishing, This is the first time I have written a blog!!, 
Can I add emojis to make it look more attractive?

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 46f3f38ca0bdde04948bb2e40cafe8b004e76880 at: https://61d32a6f90dfde1fea6a3fdc--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@gauravchauhan2403 I hit the merge button on the wrong PR! Apologies. Will you open a new PR for this post?

**Comment by warunicorn19** [comment]
@leecalcote you tagged the wrong @Chadha93

**Comment by leecalcote** [comment]
oops (again)

**Comment by Chadha93** [comment]
@leecalcote Sure I'll open a new pr for this.

**Pull request merged**
