### PR TITLE
brighter vmware logo 

### PR DESCRIPTION
**Pull request by Srinja333**
**Description**
I make vmware logo brighter in dark mode

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Srinja333** [comment]
@leecalcote  please check it out

**Review by leecalcote — APPROVED** [review]
Nice!

**Comment by l5io** [comment]
🚀 Preview for commit b562b879b84d8a1470a82298f7cef3572464c8ce at: https://641f3ce9960c8a721e62551d--layer5.netlify.app

**Comment by Srinja333** [comment]
@Nikhil-Ladha please check it out

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Chadha93** [comment]
Yay @Srinja333 :balloon:

**Pull request merged**
