### PR TITLE
[DRAFT] Add workflow for converting .jpg/.png to .webp

### LINKED ISSUE #4301: [CI] Make a workflow to update all `.jpg/.png` images to `.jpeg`
### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ayushthe1**
**Description**

This PR fixes #4301 

**Notes for Reviewers**
This shouldn't be merged until it's in a draft state.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3403342386f1f78fe3316bcb9d88886030167fca at: https://647dc917b3574c0c04effda7--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@ayushthe1 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Chadha93** [comment]
@ayushthe1.....

**Review by suhail34 — CHANGES_REQUESTED** [review]

**Comment by Chadha93** [comment]
@suhail34 @Udit-takkar what's the call here?

**Review by Udit-takkar — COMMENTED** [review]
@Chadha93 i am not sure about this because 

If i understood this correctly using https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#formats we can pass in options to automatically convert images to webp.

**Comment by sudhanshutech** [comment]
Closing this pr due no activity and active participation. Lets reopen this issue so the new contributors can bring there work here

**Pull request closed without merging**
