### PR TITLE
Issue

### LINKED ISSUE #4336: [Home Page] Slider dots not visible in Brands carousel in dark mode
### Description
There is a slider on the home page of https://layer5.io/ that features the partner brands. The slider dots are visible in light mode but not in dark mode. The color "#CCC" can be used for inactive dots in dark mode.

image

image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Manish254252**
**Description**

This PR fixes #4336 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by HetviSoni** [comment]
Hey @Manish254252 there are some merge conflicts. Please resolve them.

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@Manish254252 please write meaningful PR title related to issue that you solved that will help the maintainers to go through it.

**Comment by leecalcote** [comment]
Thank you, @hirentimbadiya ➕

**Comment by vishalvivekm** [comment]
@Manish254252 
conflicts still there. Please resolve them and write a proper PR title to facilitate the review

**Pull request closed without merging**
