### PR TITLE
Fix for #3790: Update Mentorship Programs page to be dark theme compatible

### LINKED ISSUE #3790: [Handbook] Use light version of the She Code Africa logo
### Description
The [mentorship programs](https://layer5.io/community/handbook/mentorship-programs) only has a light mode-friendly version of the She Code Africa logo.

### Expected Behavior
Would be good to have a logo that  is friendly to both darkmode and light mode on the handbook.
Find the various SVG files to the logo here

- https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T

### Screenshots
Screenshot 2023-02-20 at 10 00 28 AM

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes #3790 

Here is the current [Mentorship Programs](https://layer5.io/community/handbook/mentorship-programs) page with logos only compatible with the light theme:

[program_before.webm](https://github.com/layer5io/layer5/assets/90356410/2e2e4fc0-f93d-4c67-ac71-d596f2de3072)

Here is the page with fixes to logos and styling so it is compatible with both dark and light theme:

[program_after.webm](https://github.com/layer5io/layer5/assets/90356410/53ec5822-5a0b-44e8-82a2-a4f5733c8ffc)

---

**Notes for Reviewers**

- @Shivam-AfA as discussed in this [closed PR#4046 conversation](https://github.com/layer5io/layer5/pull/4046), here is the replacement PR.

- Thanks :pray: and credit to @HetviSoni and her [PR#4293](https://github.com/layer5io/layer5/pull/4293). Her PR included work to make theme compatible some of the same SVGs used on the Mentorship Programs page, so I copied 📋 her styling code for those respective SVGs in this PR.

- Edits to the following pages were to sync dark and light theme color transitions for text:
   - src/sections/Careers/Careers-Programs-single/ProgramsSingle.style.js
   - src/components/handbook-navigation/toc.style.js

- Edits to `external` values in numerous .mdx files are to clear the following warning appearing in the console during development:

  `Warning: Failed prop type: Invalid prop `external` of type `string` supplied to `Button`, expected `boolean`. 
   at Button `

cheers!

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2357624810b170f7c90a176aa0525ec9098128c0 at: https://648a55f2eadcfd1b63e42852--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
Thanks @randychilau for fixing the issue and the warning as well.

**Review by Shivam-AfA — APPROVED** [review]
LGTM. 🚀

**Review by Chadha93 — APPROVED** [review]

**Comment by randychilau** [comment]
Hi @Shivam-AfA and @Chadha93,

Thanks for taking the time to review and merge this PR.

Cheers,
Randy

**Pull request merged**
