### PR TITLE
Advanced istio service mesh chapter5-7

### LINKED ISSUE #2025: [Community] Member Profile: Joeseph Midura
**Current Behavior**

@josephmidura  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @josephmidura  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @josephmidura 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ujju20**
I have added Chapter 5 Just want to know Am I going right or I need to change something.

This PR fixes #2031 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Please fix the DCO check by following the instructions mentioned [here](https://github.com/layer5io/layer5/pull/2033/checks?check_run_id=3169322486)

**Comment by Nikhil-Ladha** [comment]
This is not how the chapters will be migrated, please check the MDX files for the existing chapter and update the code.
For example, this [chapter](https://github.com/layer5io/layer5/blob/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio/fault-injection.mdx) was migrated from this [lab](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-6) under the istio-workshop Github repo.

**Comment by ujju20** [comment]
> This is not how the chapters will be migrated, please check the MDX files for the existing chapter and update the code.
> For example, this [chapter](https://github.com/layer5io/layer5/blob/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio/fault-injection.mdx) was migrated from this [lab](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-6) under the istio-workshop Github repo.

Ok I will

**Comment by l5io** [comment]
🚀 Preview for commit e3424626dbe5118a58b5399e8738e06a5f1e2e42 at: https://61264c9a02c024c79fc09bd5--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Closing this PR as the respective chapters have already been added.
Thank you for the effort, Ujjwal.

**Pull request closed without merging**
