### PR TITLE
github-icon-color-fixed 

### PR DESCRIPTION
**Pull request by diksharai9**
Signed-off-by: Diksha Rai <maildiksharai9@gmail.com>
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by diksharai9** [comment]
Signed-off-by: Diksha Rai <maildiksharai9@gmail.com>

**Comment by asubedy** [comment]
Oops, I guess you forgot to signoff @diksharai9 please follow this link to add a signoff
https://github.com/layer5io/layer5/pull/2522/checks?check_run_id=4885974691

**Comment by diksharai9** [comment]
> Oops, I guess you forgot to signoff @diksharai9 please follow this link to add a signoff https://github.com/layer5io/layer5/pull/2522/checks?check_run_id=4885974691

yes

**Comment by diksharai9** [comment]
> Oops, I guess you forgot to signoff @diksharai9 please follow this link to add a signoff https://github.com/layer5io/layer5/pull/2522/checks?check_run_id=4885974691

do I need to create a new pr, because I think the one which I merged to mine without signing-off is creating problem?

**Comment by Abhijay007** [comment]
> > Oops, I guess you forgot to signoff @diksharai9 please follow this link to add a signoff https://github.com/layer5io/layer5/pull/2522/checks?check_run_id=4885974691
> 
> do I need to create a new pr, because I think the one which I merged to mine without signing-off is creating problem?

@diksharai9 you can resolve it via git rebase but it is quite complex sometimes, so I suggest you make a new branch and commit your changes to that and sign off that commit, if you still feel stuck somewhere ping me on slack: https://layer5io.slack.com/ssb/redirect#/shared-invite/email :)

**Comment by diksharai9** [comment]
> > > Oops, I guess you forgot to signoff @diksharai9 please follow this link to add a signoff https://github.com/layer5io/layer5/pull/2522/checks?check_run_id=4885974691
> > 
> > 
> > do I need to create a new pr, because I think the one which I merged to mine without signing-off is creating problem?
> 
> @diksharai9 you can resolve it via git rebase but it is quite complex sometimes, so I suggest you make a new branch and commit your changes to that and sign off that commit, if you still feel stuck somewhere ping me on slack: https://layer5io.slack.com/ssb/redirect#/shared-invite/email :)

okay, thankyou

**Pull request closed without merging**
