### PR TITLE
Add New Integrations

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b113d5b639919dde2462e1cf23c7d1616919c684 at: https://634cfdab9f59c7319d97a02e--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6f426251b95c007d84f11997d25fc55dae5e2b0b at: https://634d0a2447ed83360edf0ad9--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 063a16eeec9497f97b7a5c995c193c3dbe97893e at: https://634d3a059e2a30125a1412a7--layer5.netlify.app

**Comment by leecalcote** [comment]
Oh, my, my, my.

Leave it to @debo19 to make me look bad. Wow. Geez.

**Comment by leecalcote** [comment]
@sahilsuman933 ... just look at what you've started. 😁

**Comment by l5io** [comment]
🚀 Preview for commit 328d8bb19a08905fa470cf9d9e65103a65e66927 at: https://634da7ab8c273e12e2fc24a9--layer5.netlify.app

**Comment by sahilsuman933** [comment]
I was looking at that, and I am pleased to see my work is making an impact. 

// @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit e06463a931b29d0ad84e2e174158e52c779ff22a at: https://634e5bf18c273e21b2fc23b8--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit db1e81613eb30f3e04d6f54bc85b758537efe3a2 at: https://634e8cdf7ace375560173218--layer5.netlify.app

**Comment by leecalcote** [comment]
@debo19 there's a potential mismatch of project name to project details. See the Cloud Custodian page as an example.

@debo19 will you set `published` to `false` for any integration that does not have a value in the "CRDs" column?

**Comment by leecalcote** [comment]
@debo19 with this issue fixed, we're good to merge this set of integrations earlier that you otherwise might have - https://github.com/layer5io/layer5/pull/3373

**Comment by l5io** [comment]
🚀 Preview for commit bb8784590a44ff883593de24633e3165ddad47bd at: https://634f17c1c2e1a00061e3cdd6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 016c54ce0ce6643114cb887130b98870424f1d6d at: https://634f3b582abea8130374cc1a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 88c0bf20093629bc44650a90cb85c42f7c92347d at: https://6350330aab902d0c503fcd24--layer5.netlify.app

**Comment by leecalcote** [comment]
So, this is fantastic, however, we need to curtail the number of integrations displayed on the home page. The performance is something awful. // @Nikhil-Ladha

**Comment by sahilsuman933** [comment]
@leecalcote Fixed that issue through this PR https://github.com/layer5io/layer5/pull/3387. So, I guess we are good to merge this PR. 🚀

**Review by sahilsuman933 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 3d684af2cf06eaeb918ed4454e98fb8204ece8d6 at: https://635073b8fdfe14149063348a--layer5.netlify.app

**Comment by leecalcote** [comment]
> @leecalcote Fixed that issue through this PR #3387. So, I guess we are good to merge this PR. 🚀

Great work, @sahilsuman933. This hits the spot and is just what was needed.

**Pull request merged**
