### PR TITLE
Add Reviews on MeshMap and Pricing page

### PR DESCRIPTION
**Pull request by eeshaanSA**
Signed-off-by: eeshaanSA <eeshaans1@gmail.com>

**Description**
Added reviews
This PR fixes #

**Notes for Reviewers**
ready for review. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 35bdd523904af1f2224ec7cdd0c911892cc40e19 at: https://63ea0a493d8d3547fce7ef00--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b1c2a9439ec15ac2695fe7e854c520f8ce8b7c13 at: https://63ea101ab771b100aba1a89a--layer5.netlify.app

**Comment by leecalcote** [comment]
Adding do-not-merge label given the comments in the PR description. Please remove when ready for review.

**Comment by eeshaanSA** [comment]
@leecalcote ready for review

**Comment by leecalcote** [comment]
Where else are we using quotes? Let's ensure that these new quotes show up that page, too.

**Comment by leecalcote** [comment]
https://63ea101ab771b100aba1a89a--layer5.netlify.app/pricing - here.

**Comment by eeshaanSA** [comment]
@leecalcote the pricing page also has the reviews.

**Pull request merged**
