### PR TITLE
Fix: responsiveness of CTA widget solved (bug)

### LINKED ISSUE #2309: [Learn] Width of the call to action (CTA) is getting cut short
**Description**

The width of the call to action (CTA) is getting cut short.
Link:- https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/

**Expected Behavior**

If it is expanded the image should display nicely.

**Screenshots**

Screen Shot 2021-10-29 at 12 49 44 PM

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**
Worked on maintaining the aspect ratio of CTA widget contents
- improved responsiveness of CTA widget on learning paths
- improved responsiveness of Layer5 image

Demo:

https://user-images.githubusercontent.com/73700530/139586436-9bfc950e-130b-4c3a-9b72-604cdf46cf57.mov

This PR fixes #2309 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f266db16c2bcf82929e97801e542a95a8ab92c39 at: https://617e9f999159be4012e8ac03--layer5ng.netlify.app

**Review by vedant-kakde — APPROVED** [review]

**Comment by vedant-kakde** [comment]
LGTM 👍🏻 Great work @theBeginner86  👏🏻

**Comment by leecalcote** [comment]
I love seeing this recording, @theBeginner86. Very helpful in reviewing. 👍

**Review by leecalcote — CHANGES_REQUESTED** [review]
Two items to address:

1) need to adjust line height on the JOIN THE DISCUSSION line so that when it wraps, it keeps minimal space between itself, while still maintaining a healthy separation from the rest of the text.

2) the logo's aspect ration is still skewed when the window shrinks in size

**Comment by theBeginner86** [comment]
> Two items to address:
> 
> 1. need to adjust line height on the JOIN THE DISCUSSION line so that when it wraps, it keeps minimal space between itself, while still maintaining a healthy separation from the rest of the text.
> 2. the logo's aspect ration is still skewed when the window shrinks in size

ok 👍
I'll try fixing that 👨‍💻

**Comment by theBeginner86** [comment]
After new changes:

https://user-images.githubusercontent.com/73700530/139633139-83838392-e0b9-4ee1-8439-bf7f21af0d2c.mov

**Comment by l5io** [comment]
🚀 Preview for commit cf2f810293168de977e578587f157d6cc708900e at: https://617f915139ce6ff69aa2005e--layer5ng.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM 🎉

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Screenshot 2021-11-03 at 1 19 44 PM
Almost there @theBeginner86, the logo is still getting skewed in smaller views, could you please take a look.

**Comment by theBeginner86** [comment]
@warunicorn19 Ok I'll fix it. 
Just one doubt, the image needs to be bigger than it is currently (after my second fix: https://github.com/layer5io/layer5/pull/2313#issuecomment-955978992), right?

**Comment by warunicorn19** [comment]
Yeah bigger in the sense, that it should maintain its aspect ratio throughout all screen sizes

**Comment by theBeginner86** [comment]
What about now? Does the logo look good?

https://user-images.githubusercontent.com/73700530/140303759-8503a4c9-fcbf-46a0-824e-3bc39ab709a8.mov

**Comment by l5io** [comment]
🚀 Preview for commit 286d826a6f0301211c690b0813936469eec9f49e at: https://6183c160f753f9f54261e8ec--layer5ng.netlify.app

**Comment by theBeginner86** [comment]
@warunicorn19 can you please review the new changes. 😊
I increased the size of the logo in my latest push.

**Comment by warunicorn19** [comment]
@theBeginner86 umm, so we're still stuck with the aspect ratio. So the width of the logo should remain the same, if you check now, it's getting squished. Have a look at the callouts here: https://layer5.io/community and https://layer5.io/blog at different screen sizes.

**Comment by warunicorn19** [comment]
@theBeginner86 let's talk about this on the websites' call today. Will you be able to attend?

**Comment by theBeginner86** [comment]
Yeah, I'll attend 👍

Also, thanks for providing those additional examples of CTA on the layer5 website. I'm trying to solve that shrinking logo.

**Comment by l5io** [comment]
🚀 Preview for commit 0df35f8a5994bcb04cc704e62f1d0eb1f34326a9 at: https://61896d115c6b7520206d9489--layer5ng.netlify.app

**Comment by theBeginner86** [comment]
Demo:

https://user-images.githubusercontent.com/73700530/140797593-ca0c57da-e5c5-4546-9400-2d35adc31ec0.mov


Please have a look at the new changes. 
I've followed the guideline which was given to me in the today's websites meeting. It was about the use of constant width for the widget so that the aspect ratio of logo remains constant. Only at some break-points it was really necessary to decrease the length of the widget because otherwise the margin from right would eat up some part of the widget.

**Comment by Mr-DG-Wick** [comment]
> Does this one look better?

Nice one @theBeginner86 but when you reduce the size  after a threshold, the Layer5 icon and the `Discuss` text in `join the discussion`  icon squeeze a bit too much. So it may need fixing :)

**Comment by theBeginner86** [comment]
@Mr-DG-Wick just wanted to ask that does it look the same in preview: https://github.com/layer5io/layer5/pull/2313#issuecomment-963451288 
as it does in the recording? 
I believe that due to the screen recording thing the actual size of the widget is not coming through. I'll request you to please have a look at the preview as well and then if you could give feedback on whether the problem of squeezing size still exists or not? 😅

**Comment by Mr-DG-Wick** [comment]
> @Mr-DG-Wick just wanted to ask that does it look the same in preview: [#2313 (comment)](https://github.com/layer5io/layer5/pull/2313#issuecomment-963451288) as it does in the recording? I believe that due to the screen recording thing the actual size of the widget is not coming through. I'll request you to please have a look at the preview as well and then if you could give feedback on whether the problem of squeezing size still exists or not? 😅

@theBeginner86 I am afraid it still squeezez 😅 
Screenshot (1089)

**Comment by theBeginner86** [comment]
@Mr-DG-Wick Thanks for checking it 😁. I'll see how much more I can increase the width. 😅

**Comment by Mr-DG-Wick** [comment]
> @Mr-DG-Wick Thanks for checking it 😁 I'll try to increase the width even more 😅

Wondering if we could play with .svgs here. Vector images were created for the mere fact that they could increase or decrease in scale without having any loss in image quality.

**Comment by leecalcote** [comment]
I know that I've mentioned this a on a number of occasions, but it bears repeating: never specify both width and height.

ALWAYS maintain aspect ratio.

**Comment by leecalcote** [comment]
Thanks for seeing this through, @theBeginner86 👍

**Pull request merged**
