### PR TITLE
fixes issue no 4378 : Card Overflowing out of the main UI

### PR DESCRIPTION
**Pull request by saaagarsingh**
**Description**

fixes: #4378 

I've sighned off my commit

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e3376352bd3cf823f8794c6541b07ae57e259e86 at: https://6492a5037c6dcc26ae2773a3--layer5.netlify.app

**Review by samyakshah3008 — COMMENTED** [review]
Nice work @saaagarsingh 💪 
Please attach some screenshots of changes made in UI for better review experience.

**Review by Mohith234 — COMMENTED** [review]
### Attaching the screenshot of the preview  

image

- I would suggest aligning the image a bit upwards to make it on the same level as the description beside it.
- Also, can we align the items (description and image) to the center of the webpage? Currently, the left side has more space which might create a bad user experience.

Your thoughts? @saaagarsingh  @samyakshah3008

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@saaagarsingh card is not overflowing in less then 100% zoom l evel like 90% , but it is still overflowing in 100% zoom level it would be great if it is not overflowing with atleast 100% zoom level and you don't need to change the versions of dependencies so kindly change that also

https://github.com/layer5io/layer5/assets/86219935/2d598fc4-0daa-48d7-8639-7aef4861f998

**Comment by hirentimbadiya** [comment]
> Okay sure, reducing the width of the container might work for 100% zoom but then it might look alot smaller in 90%. What could be a better way to solve it @hirentimbadiya. Open to your suggestions.

I think most of the users will be in 100% zoom level but to your question we can prevent the container table from overflowing at 100% zoom while maintaining its intended size at 90% zoom, you can apply responsive design techniques. Here are a few suggestions:

Use CSS Media Queries: Apply different styles to the container table based on the viewport size. You can define specific rules for 100% and 90% zoom levels

**Comment by vishalvivekm** [comment]
@Mohith234 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
Dont change the dependencies please

**Comment by saaagarsingh** [comment]
@Ghat0tkach surely will do that and also will keep in mind for future contribution.

**Comment by leecalcote** [comment]
@saaagarsingh, a couple of merge conflicts have come up. As you resolve these, and attempt to remove the package–lock.json changes, if you're unsuccessful, you might just open a new PR.

**Comment by Chadha93** [comment]
@saaagarsingh Merge conflicts...

**Comment by abhijeetgauravm** [comment]
// @saaagarsingh

**Pull request closed without merging**
