### PR TITLE
 Much spaces between contribution and General contribution flow #4636 

### LINKED ISSUE #4636: Much spaces between  contribution and General contribution flow
### Current Behavior

There is much spaces between  contribution and General contribution flow [here](https://layer5.io/community/handbook/contribution)
Similarly , in Projects [here](https://layer5.io/community/handbook/projects) , Mentorship Programs [here](https://layer5.io/community/handbook/mentorship-programs) , Writing Program [here](https://layer5.io/community/handbook/writing-program) , UX Contributors [here](https://layer5.io/community/handbook/designer) , Code of Conduct [here](https://layer5.io/community/handbook/code-of-conduct) 
### Desired Behavior

The spaces should reduced between contribution and General contribution flow [here](https://layer5.io/community/handbook/contribution) .
### Screenshots / Mockups

image
image
image
image

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AbiodunVlad**
Much spaces between contribution and General contribution flow #4636 

**Description**

This PR fixes #4636 

**Notes for Reviewers**
I fixed all the excess spaces on all the pages in Handbook. All the pages had the problem and not just the listed pages.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a8c7fdac5234945bf63c34d2445d070ed907197a at: https://6553d4644d4d0108a2c9dde2--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
Change isn't visible @AbiodunVlad . Please make your commit creating a new branch!

**Comment by AbiodunVlad** [comment]
@abhijeetgauravm Please check now if the change is visible now.

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm Please check now if the change is visible now.

No @AbiodunVlad it's not visible!

**Comment by AbiodunVlad** [comment]
Hi @abhijeetgauravm push again and it says there is no conflict on my end. The changes I made in the code are also visible here. What could be wrong?
The changes are effected in my local server.

**Comment by ritiksaxena124** [comment]
There are 0 files changed @AbiodunVlad. When you clone the repository in your local machine make sure to create a new branch first -> make the changes in that newly created branch and then make a PR with that new branch to avoid this kind of issue. 
image

**Comment by leecalcote** [comment]
Duplicated by https://github.com/layer5io/layer5/pull/5125. Closing.

**Pull request closed without merging**
