### PR TITLE
Added validation for all required fields in docker-extension form

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added validation for at least one account in docker-extension form.
Also, added validation for `role` in both meshmap and docker-extension form.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote done and dusted ✔️

**Review by warunicorn19 — APPROVED** [review]
Looking good to me!

**Comment by l5io** [comment]
🚀 Preview for commit 9c9329b067811229c12f34d0a2dc1ed64af32293 at: https://627ceabc6071c35e3f8a1e36--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@warunicorn19 do check the validation in the preview also, for confirmation.
If it looks good, let's get this merged.

**Comment by warunicorn19** [comment]
Yup, it works!

**Pull request merged**
