### PR TITLE
 Improve search engine results' summaries (as well as social media post previews) for layer5.io/community/members/{member-name} page through react-helmet-async lib #5186 

### LINKED ISSUE #5186: Improve search engine results' summaries (as well as social media post previews) for layer5.io/community/members/{member-name} page through react-helmet-async lib
### Current Behavior

**Google search results:**
Perhaps pretty low priority, but couldn't help notice that when googling "meshery member {x member}" the Google result shows link to community member (i.e. https://layer5.io/community/members/mario-arriaga): 
CleanShot 2023-12-04 at 16 51 55@2x

but shows part of the page's footer, as description:
CleanShot 2023-12-04 at 16 50 58@2x

**twitter/x:**
For twitter, not sure what would be better but this is what a layer5 member page looks like today:
CleanShot 2023-12-04 at 17 05 48@2x

### Desired Behavior

It'd be nice if site could be tweaked as shown in [freecodecamp.org / How to Use React Helmet – With Example Use Case
](https://www.freecodecamp.org/news/react-helmet-examples/) to improve how search engines crawlers index these results by using [react-helmet-async](https://www.npmjs.com/package/react-helmet-async) lib to instead show member profile summary (or an excerpt of it)

Maybe something similar for twitter and other social media.

### Screenshots / Mockups

N/A

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AbiodunVlad**
Improve search engine results' summaries (as well as social media post previews) for layer5.io/community/members/{member-name} page through react-helmet-async lib #5186 

**Description**

This PR fixes #5186 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by AbiodunVlad** [comment]
search engine summary

**Comment by l5io** [comment]
🚀 Preview for commit a8c7fdac5234945bf63c34d2445d070ed907197a at: https://65997bf6d5ec3eeab2c89ced--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@AbiodunVlad 
what are the changes made here ?

Would you attend today's websites meeting to discuss this item please.

**Comment by AbiodunVlad** [comment]
@vishalvivekm Yes, I'll be at the meeting today.
The issue was that a part of the website foot was appearing in the members' meta description in search engines. I basically got rid of it. The React-Helmet prescribed did not do the work. Just needed to get rid of the meta for members.

**Comment by l5io** [comment]
🚀 Preview for commit 8ac600d2365080b760ef269f1f72650ba15ac212 at: https://65c1ee5e32bd8d4ea6190262--layer5.netlify.app

**Pull request closed without merging**
