### PR TITLE
fixed the issue on the newcomers section

### LINKED ISSUE #1480: [Community] Unwanted whitespace on right side of Newcomers section
**Description**
The /community page has unwanted whitespace on right side of Newcomers section.

**Expected Behavior**
Gray background should be edge-to-edge (full bleed)

**Screenshots**
Screen Shot 2021-02-04 at 12 17 22 PM

**Environment:**
- Browser: Safari... and others?

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Abiola-Farounbi**
Signed-off-by: abiola farounbi <farounbiabiola@gmail.com>

**Description**

This PR fixes #1480 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Tanuj22 — CHANGES_REQUESTED** [review]
@Abiola-Farounbi Thank you! This fixed the issue but is causing overflow in a smaller screen. Can you check that out? 
Screenshot from 2021-02-05 22-39-37

**Comment by Abiola-Farounbi** [comment]
hi @Tanuj22 
please what browser are you using, it works on Chrome, Firefox

**Comment by Tanuj22** [comment]
> hi @Tanuj22
> please what browser are you using, it works on Chrome, Firefox
I am also using Chrome 🤔

**Comment by Abiola-Farounbi** [comment]
> 
> 
> hi @Tanuj22
> please what browser are you using, it works on Chrome, Firefox



> 
> 
> > hi @Tanuj22
> > please what browser are you using, it works on Chrome, Firefox
> 
> I am also using Chrome 🤔

Thanks, I have seen it, I also noticed that the overflow only happens on chrome browser.
I haven't found a way to fix the issue so far.

**Comment by Nikhil-Ladha** [comment]
@Tanuj22 at what resolution are you finding this overflow? I have found the issue and it's not related to the newcomer's section but in a different one..... @Abiola-Farounbi if you don't mind would you like to check in the community slider and adjust the width of buttons and slides for responsiveness, and also make some other changes:
- Remove unwanted left padding and fix margins in mobile view for newcomer's map.
- The newcomer's section data and the map should be center-aligned in mobile ( though I think, fixing the above point would fix this one as well.)

**Comment by Nikhil-Ladha** [comment]
Also, the current change won't fix the issue, do revert it as well.

**Comment by Abiola-Farounbi** [comment]
> 
> 
> @Tanuj22 at what resolution are you finding this overflow? I have found the issue and it's not related to the newcomer's section but in a different one..... @Abiola-Farounbi if you don't mind would you like to check in the community slider and adjust the width of buttons and slides for responsiveness, and also make some other changes:
> 
>     * Remove unwanted left padding and fix margins in mobile view for newcomer's map.
> 
>     * The newcomer's section data and the map should be center-aligned in mobile ( though I think, fixing the above point would fix this one as well.)

@Nikhil-Ladha 
The responsiveness of the community slider works fine on the chrome browser but there's an issue with it on the firefox browser.
I suggest a new issue should be created to fix this.

**Comment by Abiola-Farounbi** [comment]
Hi @Tanuj22 
I have fixed the issue, can you check it again

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @Abiola-Farounbi

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
