### PR TITLE
Related posts bug

### LINKED ISSUE #3163: [Bug] Refine related post on news
#### Description

Related post should not include the current post.

#### Expected Behavior

Refinement needed.
#### Screenshots

image

image

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gurpreet-legend**
**Description**

This PR fixes #3163 

**Notes for Reviewers**
- I have added a filter at `line 46` in the file `NewsSingle/index.js`, which removes the currently opened news article.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gurpreet-legend** [comment]
Please review this, @UtkarshMishra12 @leecalcote 
The bug has been fixed :)

**Comment by leecalcote** [comment]
Running deployment preview...

**Comment by l5io** [comment]
🚀 Preview for commit 27672831fddc3974d80dd30f2bd74b15916572f6 at: https://63d1b29c96eece18b44ca2bd--layer5.netlify.app

**Comment by gurpreet-legend** [comment]
@Nikhil-Ladha please review :)

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
