### PR TITLE
Mesh book

### LINKED ISSUE #1171: Add Book Contents to a Page on Layer5 site and Layer5-ng site
**Current Behavior**
The website has book contents page at https://layer5.io/books/service-mesh-patterns.

**Desired Situation**
Add the [book contents](https://docs.google.com/spreadsheets/d/1sJAsBPAc08Pml5uBijHpb0AvJxe6IoVtzhwBFDiVLCw/edit#gid=1453706035) to the page.

---

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by lolyparty**
Signed-off-by: lolyparty <ololadeolayiwola01@gmail.com>

**Description**
Added the tabular book service mesh pattern book content to layer site

This PR fixes #1171 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
I think we might need some borders. Thoughts @leecalcote @Nikhil-Ladha @Tanuj22 ?

**Comment by Nikhil-Ladha** [comment]
Yes.
Also, the text is spilling on the right in Mobile view

**Comment by leecalcote** [comment]
@lolyparty is this PR still valid?

**Comment by lolyparty** [comment]
> @lolyparty is this PR still valid?

I've been asked to make some changes which I'll make soon

**Comment by leecalcote** [comment]
@lolyparty oh, ok. There was a related PR https://github.com/layer5io/layer5/pull/1246 that I thought might have subsumed this one. Sounds good.

**Comment by lolyparty** [comment]
> @lolyparty oh, ok. There was a related PR #1246 that I thought might have subsumed this one. Sounds good.

Oh, that was for layer5-ng, I've been asked to use react-table for that

**Comment by leecalcote** [comment]
Oh! I see. You might have to slow down. Clearly, I’m not able to keep up. ;)

**Comment by lolyparty** [comment]
> Oh! I see. You might have to slow down. Clearly, I’m not able to keep up. ;)

Oh yeah, I'm taking my time

**Comment by leecalcote** [comment]
Good call, @Jashpatel1. Given the impending publication of layer5ng, we can move ahead with nominal formatting here.

**Review by leecalcote — APPROVED** [review]
Thank you, @lolyparty. Much appreciated.

**Pull request merged**
