### PR TITLE
feat(collections/members): [Community] Member Profile: Aabid #4437

### LINKED ISSUE #4437: [Community] Member Profile: Aabid
**Current Behavior**

@aabidsofi19  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @aabidsofi19  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @aabidsofi19 
- Twitter: [codingaabid](https://twitter.com/codingaabid)
- LinkedIn: [aabid-sofi](https://www.linkedin.com/in/aabid-sofi)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Ykumar1415**
**Description**

This PR fixes #4437

**Notes for Reviewers**
I have added the details of Aabid Sofi in community members page.
Screenshot from 2023-07-03 14-55-29

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 214e35234c5551f1224b01ca7cc2d858a238af2a at: https://64a2988550d4bf67847df95c--layer5.netlify.app

**Comment by Ykumar1415** [comment]
@Chadha93 @vishalvivekm can you please review this pr.

**Review by Mohith234 — APPROVED** [review]
Looks good to me 🚀, Good work @Ykumar1415

**Comment by aabidsofi19** [comment]
Thanks @Ykumar1415 . Looks fine to me ..

**Pull request merged**
