### PR TITLE
Fixed Back Navigation to course overview page from chapter page

### PR DESCRIPTION
**Pull request by devartstar**
Fixed Navigation to course overview page from chapter page.

There was a typo in the back navigation Link.
Fixed the typo.

This PR fixes # [1959](https://github.com/layer5io/layer5/issues/1959)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sudo-NithishKarthik — COMMENTED** [review]
Great work @devartstar  🙌🏽 , just get that DCO pass and we would be good to go ✌🏽

**Comment by sudo-NithishKarthik** [comment]
Refer [community guidelines](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) if you need help ✌🏽

**Comment by devartstar** [comment]
Yes, I passed that DCO test.

**Review by sudo-NithishKarthik — APPROVED** [review]
LGTM 🎉

**Comment by l5io** [comment]
🚀 Preview for commit c6edcf9c21a134d03a52acfa618afe5cb81a4769 at: https://60e7149137119a2908e9d53b--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
