### PR TITLE
[Fix]Inter-page navigation

### LINKED ISSUE #5068: Transition of Inter page navigation should be smooth
### Current Behavior

- Currently, The inter-page navigation changes abruptly to the respective sections in this page - [https://layer5.io/community/handbook/community](https://layer5.io/community/handbook/community)

### Desired Behavior

- Smooth transition should be applied for the navigation ( Originally Posted by @sudhanshutech [#5017 (comment)](https://github.com/layer5io/layer5/pull/5017#issuecomment-1755311885) )

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ankushbhardwaj408**
**Description**

This PR fixes #5068 
Inter-page navigation on all pages of the Handbook has been smoothed out from abrupt behavior.
**Notes for Reviewers**

Old behaviour

https://github.com/layer5io/layer5/assets/93874580/4d2f0af4-7572-445a-8eb4-827728a23ce8

New behaviour

https://github.com/layer5io/layer5/assets/93874580/483f7cdd-1987-47db-a0f4-3e44857dad73

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408  Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by ankushbhardwaj408** [comment]
@abhijeetgauravm I missed the meeting because I was out. Apologies. Please review my PR. appreciate your help.

**Comment by sudhanshutech** [comment]
@ankushbhardwaj408 the transition not looking as smooth, you can see meshery docs how smooth that it is. Apply styling to get it smoother

**Comment by ankushbhardwaj408** [comment]
@sudhanshutech Can you tell me where I can find the docs.meshery.io code base so that I can take a look at it and implement the work here.

**Comment by sudhanshutech** [comment]
> @sudhanshutech Can you tell me where I can find the docs.meshery.io code base so that I can take a look at it and implement the work here.

no i am just referring you to the behaviour not the approach because docs is in other language

**Comment by l5io** [comment]
🚀 Preview for commit 0e8a7b86a7ca56f9519528e978664805d4053b3a at: https://653cca232de5725ffbe6eeb7--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408 Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by sandramsc — COMMENTED** [review]
@ankushbhardwaj408 Thanks for your contribution, this fix to me looks good as it implements the smooth transition requested in the initial issue. 
@sudhanshutech I see what you mean by having the transition match the smoothness which is in the [meshery doc website](https://docs.meshery.io/project/overview#meshery-is-for-developers-operators-and-product-owners), @ankushbhardwaj408 are you able to replicate this to maintain consistency throughout?

P.S It might be good to add this type of requirement to the issue description so the assignee knows what to expect before undertaking the task, as I understand the transition in meshery doc is written in a different language than that which this current PR is attempting to address?

**Comment by ankushbhardwaj408** [comment]
> **Description**
> 
> This PR fixes #5068 Inter-page navigation on all pages of the Handbook has been smoothed out from abrupt behavior. **Notes for Reviewers**
> 
> Old behaviour
> 
>  old.mp4 
> New behaviour
> 
>  new.mp4 
> **[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> 
> * [ ]  Yes, I signed my commits.

Hi @sandramsc i am not able to replicate the beahviour. Some help would be appreciated. But I think it fixes the irregularity as shown in the video.

**Comment by ankushbhardwaj408** [comment]
The main issue was in the id names given to the elements because some links do not have transition effects so I corrected the id names and now all have the same behavior.

**Comment by l5io** [comment]
🚀 Preview for commit dc4efc7b741ff6df8bb68fd9df2508c464fa9b8c at: https://6546144662a9b26575df61a5--layer5.netlify.app

**Review by sudhanshutech — COMMENTED** [review]
@ankushbhardwaj408 how are you making sure the  smoothness here, i see only `-` removal

**Comment by ankushbhardwaj408** [comment]
@sudhanshutech I thought we were talking about links as if some links are behaving differently than others. But I understand your point. I will look into it.

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by l5io** [comment]
🚀 Preview for commit 1f6d90ba8ed169d933694705195efd96abfe21e5 at: https://654b77bf7671831340086d6f--layer5.netlify.app

**Comment by ankushbhardwaj408** [comment]
@sudhanshutech I tried to make scroll like meshery docs site but it is not working, I tried to use scroll smooth behavior but still it is not working.

**Comment by sudhanshutech** [comment]
I think we are not getting here what we needed, @ankushbhardwaj408 i will recommend you to discuss this any website meet to get help

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
Merge conflict.

**Comment by leecalcote** [comment]
> I think we are not getting here what we needed, @ankushbhardwaj408 i will recommend you to discuss this any website meet to get help

Good call, @sudhanshutech

**Comment by balagowda** [comment]
is this a expected behaviour  ?????

https://github.com/layer5io/layer5/assets/111847375/3e2d52a8-3fba-45f1-b6a7-b8d4bc55ec06

**Comment by ankushbhardwaj408** [comment]
@balagowda I think you have the possible solution for it. If you don't mind can you please tell me how you fix it.

**Comment by balagowda** [comment]
I think it would be better to solve both the issues in one PR, so I have raised one #5123 , please take a look

**Comment by ankushbhardwaj408** [comment]
@balagowda Thanks for your contribution! but i am already working on this issue. Before creating a pull request, could you please get assigned to the issue to avoid duplication of efforts? Appreciate your understanding.

**Comment by balagowda** [comment]
Thank you, however my PR does also includes the solution for #5119, please do consider that as well!

**Comment by sandramsc** [comment]
> Thank you, however my PR does also includes the solution for #5119, please do consider that as well!

Hi @balagowda please take note of what @ankushbhardwaj408  mentioned about issue assignment. The issue this PR attempts to resolve has already been assigned to someone who asked first. And in line with our contribution guidelines I urge you to consider taking a look at other open issues after reading our [Contribution guidelines](https://layer5.io/community/newcomers) specifically the section "Finding an issue to work on".

**Comment by l5io** [comment]
🚀 Preview for commit 46ddeded0ba7b30cf8dd849f5b87f61cc2c9bf37 at: https://655379e39d19d2068d8ef421--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5cc4e9c6b2f83d1e73b951a6f7432f9a2c55626c at: https://655380a0f2ce64083a09653b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 060b974bc5c534f672538af6ca19d655615acf21 at: https://6555966c43d1113335045f56--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e8cc4d551e853d87a833a2ecee4e7845eefe91ee at: https://65576e8b260bab286118587a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c53518ff1b980766504c631f49b59a265df86ae6 at: https://655a32ad34e0764ce02c6d3e--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @ankushbhardwaj408 Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by l5io** [comment]
🚀 Preview for commit 1f932783a25965957424dc7a0bfc77232aeb23db at: https://655b71f25b5dda1e48603ee2--layer5.netlify.app

**Comment by ankushbhardwaj408** [comment]
// @vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit 86bed8f9b81faa543ed0a6338e001f132372108e at: https://655b757185bcee23f6790bf0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f1ba9ad10bdbd3d3ced49d19c6c8e727429a359b at: https://655ddcc320c2130ff20f6e7c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d240e06b1f567758bfebc262db776d4b3c4abba5 at: https://6575ec61a8508d40e8ee53a1--layer5.netlify.app

**Comment by saurabh100ni** [comment]
LGTM. 
@vishalvivekm 👀

**Pull request closed without merging**
