### PR TITLE
Updated the German and Indian flag in the current Layer5 site

### LINKED ISSUE #538: Update the German and Indian flag in the current Layer5 site
**Description**
In the current Layer5 site, German(3rd) and Indian(8th) flags are inappropriate. Replace them with proper flags.

**Screenshots**
Capture

 **To Reproduce**
1. Go to [https://layer5.io/]('https://layer5.io/')
2. Move to the languages section in footer.
3. See error.

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**
Updated the German and Indian flag in the current Layer5 site.

### Updates:-
- [x] Removed the inappropriate Indian & German flags
- [x] Added appropriate Indian & German flags

Since I replaced the old ones within the same directory, l don't need to update any change to the image(svg) routes in `languages.html`

This PR fixes #538 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

Signed-off-by: [Neilblaze](https://github.com/Neilblaze)

### CODE REVIEW

**Comment by Neilblaze** [comment]
@Jashpatel1 @leecalcote please review the above :)

**Comment by Nikhil-Ladha** [comment]
@Neilblaze if you can confirm there is a border present or not around each flag. If not then please add one to all of them as some flags are are not looking appropriate because of having the same color as background. For example the Russian flag.

**Comment by Neilblaze** [comment]
> @Neilblaze if you can confirm there is a border present or not around each flag. If not then please add one to all of them as some flags are are not looking appropriate because of having the same color as background. For example the Russian flag.

Yes, you are right! I did notice that yesterday but didn't commit the change as the task was assigned to update the German & Indian flag, thus I strictly replaced them only. But I would love to do the task that you just said. Should I create a new issue upon that or just create a new PR updating the flags?

@Nikhil-Ladha @leecalcote

**Comment by Neilblaze** [comment]
@Nikhil-Ladha I think we should replace the existing French, Italian & Russian flags with the bordered ones. Also the RHS of the Japanese flag doesn't seem to have any border. Please confirm the same, so that I can replace those with new ones :)

**Comment by Nikhil-Ladha** [comment]
> > @Neilblaze if you can confirm there is a border present or not around each flag. If not then please add one to all of them as some flags are are not looking appropriate because of having the same color as background. For example the Russian flag.
> 
> Yes, you are right! I did notice that yesterday but didn't commit the change as the task was assigned to update the German & Indian flag, thus I strictly replaced them only. But I would love to do the task that you just said. Should I create a new issue upon that or just create a new PR updating the flags?
> 
> @Nikhil-Ladha @leecalcote

You can open another issue, and reference that too within this PR itself.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I think we should replace the existing French, Italian & Russian flags with the bordered ones. Also the RHS of the Japanese flag doesn't seem to have any border. Please confirm the same, so that I can replace those with new ones :)

Having few bordered flags and few not, may look odd. So, it's better to add a border to all the flags to keep the consistency.

**Comment by Neilblaze** [comment]
@Nikhil-Ladha Okay, so apart from this PR in which I updated the German & Indian Flag(s), I am creating another issue for updating rest of the flags, & referencing that too within that PR itself.

**Comment by Neilblaze** [comment]
@Jashpatel1 @Nikhil-Ladha please review the above :rocket:

**Comment by Nikhil-Ladha** [comment]
Screenshot from 2020-07-30 21-56-15
I wanted you to do this ^^, adding a border to all of them.

**Comment by Neilblaze** [comment]
@Jashpatel1 The Japanese flag has got border in it, I just checked. @Nikhil-Ladha oh do you mean by - `border="2"` this? Okay, so since I already added borders to most of the flag svg's , should I add the border tag to the ones with no borders? like the English, German, Portuguese & Chinese flag? as if I add the border tag to the flags with existing borders, it might look dull.

**Comment by Neilblaze** [comment]
@Jashpatel1 The Japanese flag has got border in it, I just checked. @Nikhil-Ladha oh do you mean by - `border="2"` this? Okay, so since I already added borders to most of the flag svg's , should I add the border tag to the ones with no borders? like the English, German, Portuguese & Chinese flag? as if I add the border tag to the flags with existing borders, it might look dull.

**Comment by Nikhil-Ladha** [comment]
> @Jashpatel1 The Japanese flag has got border in it, I just checked. @Nikhil-Ladha oh do you mean by - `border="1"` this? Okay, so since I already added borders to most of the flag svg's , should I add the border tag to the ones with no borders? like the English, German, Portuguese & Chinese flag? as if I add the border tag to the flags with existing borders, it might look dull.

I would suggest not adding a border to svgs rather add them, in CSS that way it's an easier task to refine it in future. Yeah, I meant that only `border: 1px solid`. And, for the Japanese flag which border are you referencing to?

**Comment by Neilblaze** [comment]
@Nikhil-Ladha Okay, I am reverting the changes of adding the borders to those svg's & I'm adding `border: 1px solid` to the CSS & creating the PR. For the Japanese flag, when I viewed it in raw, I saw a border of `1px solid` around it. That's why I said so.

**Comment by Neilblaze** [comment]
@Nikhil-Ladha Okay, I am reverting the changes of adding the borders to those svg's & I'm adding `border: 1px solid` to the CSS & creating the PR. For the Japanese flag, when I viewed it in raw, I saw a border of `1px solid` around it. That's why I said so.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Okay, but for the [Japanese](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/flags/ja.svg) flag, when I viewed it in raw, I saw a border of `1px solid` around it. So, that means I have to replace that flag with the non bordered one & then apply the CSS. That's why I said so.
> 
> The latest deploy preview looks like this -
> flags
> 
> LGTM though :)

Screenshot from 2020-07-30 23-34-19
Well, that's not the case for me. That's the reason I insisted upon adding a border in CSS.

**Comment by Neilblaze** [comment]
So, now tell me what should I do? Revert those commits & add the border in CSS right?

**Comment by Nikhil-Ladha** [comment]
> Okay I'm on it :)
> 
> Just one more clarification, can I keep the committed svg's there & just add the border in the CSS file?

Yes, if I say no then I know for sure you would be cursing me badly😆.

**Comment by Neilblaze** [comment]
Finally work is done 😃

@Nikhil-Ladha @Jashpatel1 review the above please :racing_car:

**Pull request merged**
