### PR TITLE
[UI] loading animation for calendar

### PR DESCRIPTION
**Pull request by subhradwip01**
Signed-off-by: subhradwip01 <subhradwip01@gmail.com>

**Description**

This PR fixes is for loading animation for calender

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by subhradwip01** [comment]
Output:

**Comment by l5io** [comment]
🚀 Preview for commit b708ac12a42366e167fd622d5ec4dbfb1fc97751 at: https://6205451dc7389b21831b4952--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
> Cool! Any chance that we can get the page title included and an outline of the calendar (perhaps reduced opacity) to show with the spinner on top, so that visitors understand that they will see a calendar, but that entries are in the process of loading?

Ok...let me try 👍

**Comment by subhradwip01** [comment]
@leecalcote can you tell me from which component that calendar page is coming?..may that can be reused to make the change

**Comment by subhradwip01** [comment]
After changes, the output:

https://user-images.githubusercontent.com/88609894/153698519-759c423d-e96b-427b-b40f-29b6c432e9e6.mp4

**Comment by l5io** [comment]
🚀 Preview for commit d8abd551a4d815736d03f9fad485c07a3def8171 at: https://620749ac1bc5805c2d228f70--layer5ng.netlify.app

**Review by YashKamboj — APPROVED** [review]

**Comment by subhradwip01** [comment]
@leecalcote @YashKamboj  as per today's discussion should I make the loading spinner a little bit larger?

**Comment by subhradwip01** [comment]
After changing the size:
https://user-images.githubusercontent.com/88609894/154034482-bedfcedd-7d51-4e12-a96b-489c03f4af8a.mp4

**Comment by l5io** [comment]
🚀 Preview for commit 29296673dfcee49dadab4a6d9139e32e81b6357b at: https://620b75e89c9e75009f83358d--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
@YashKamboj @leecalcote could you please review the latest changes?

**Comment by asubedy** [comment]
@subhradwip01 yes this looks good, did you by-chance increase the load time?

**Comment by subhradwip01** [comment]
> @subhradwip01 yes this looks good, did you by-chance increase the load time?

No I haven't changed the load time....I just slowed down my network speed from chrom dev tool to show the demo only... 😅😅

**Review by Abhijay007 — COMMENTED** [review]
@subhradwip01 please revert the change for package-lock.json file :) as it is not needed.

**Comment by subhradwip01** [comment]
> @subhradwip01 please revert the change for package-lock.json file :) as it is not needed.

But I have not changed anything in that file...

**Comment by l5io** [comment]
🚀 Preview for commit 2650c8b7689c08cacfbe5a0673ff5e4d4110bfa2 at: https://621324a123a9464b9bb0ce00--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
@Abhijay007 I have reverted the changes of package-lock.json..can you please check once?

**Comment by l5io** [comment]
🚀 Preview for commit 5e8bf77a191726cef1af72906d62f67a563c9831 at: https://621328e8335c6a7cd7518eb5--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
Looks real good. Thank you @subhradwip01

**Pull request merged**
