### PR TITLE
added member profiles

### LINKED ISSUE #1916: [Community] Member Profile: Rudraksh Pareek
**Current Behavior**

@DelusionalOptimist has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @DelusionalOptimist as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: DelusionalOptimist
- Twitter: Del_Optimist
- LinkedIn: rudraksh-pareek
- Link to profile picture: https://media-exp1.licdn.com/dms/image/C5103AQGuolflyAvO1w/profile-displayphoto-shrink_200_200/0/1581578057823?e=1622073600&v=beta&t=zCCRnaDveJe4onPWVRS0H2xd_kcbcqnKno-QduOrlRU

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by kaushambisharma**
Signed-off-by: Kaushambi Sharma sharma.kaushambi@gmail.com
**Description**
This PR fixes #1916 and #1917 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@kaushambisharma Please revert the changes in package.json and package-lock.json

**Comment by l5io** [comment]
🚀 Preview for commit 4943b1bb31e0483a00715c74f1cf6631337f5c02 at: https://60c5d906e8a42b9f5a137183--layer5ng.netlify.app

**Review by Jashpatel1 — COMMENTED** [review]
@kaushambisharma Please add `published: true`, so it gets published to the site.

**Review by pranav-bhatt — APPROVED** [review]

**Review by DelusionalOptimist — APPROVED** [review]
Thanks! :heart:

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks @kaushambisharma

**Pull request merged**
