### PR TITLE
[CI] Lightouse issue: Add language property to html tag

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes one of many Lighthouse issues.

**Notes for Reviewers**

More fixes needed.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7ea8f09bce3b47b889852d442a23f90ea365fd27 at: https://63c9c6424f470e40552c5d6b--layer5.netlify.app

**Comment by leecalcote** [comment]
@ayushthe1

**Review by ayushthe1 — COMMENTED** [review]
The  changes are solving the `html lang` errors for all the files except [this](https://github.com/layer5io/layer5/actions/runs/3962878994/jobs/6790081639#step:6:156) as i mentioned on slack.      
Should we also add a `workflow_dispatch` option here for the workflow file ?

**Comment by leecalcote** [comment]
> The changes are solving the `html lang` errors for all the files except [this](https://github.com/layer5io/layer5/actions/runs/3962878994/jobs/6790081639#step:6:156) as i mentioned on slack.
> Should we also add a `workflow_dispatch` option here for the workflow file ?

What is this link? http://localhost:32893/googlea9b1e6fb98465659.html


Sure you can add workflow_dispatch. I don't know that we'll invoke lighthouse ci outside of a PR, but it doesn't hurt to have it in the workflow.

**Comment by ayushthe1** [comment]
@leecalcote ,oh I sent the wrong link. This is the [link](https://github.com/layer5io/layer5/actions/runs/3962878994/jobs/6790081639#step:6:156) I was referring to.

**Pull request merged**
