### PR TITLE
feat: add gsap scroll trigger

### PR DESCRIPTION
**Pull request by Udit-takkar**
**Description**

This PR fixes https://github.com/layer5io/layer5/issues/3811

As you can see in the video my cursor is outside of inner container and i am able to scroll the inner container content and the container is fixed and not stuck in between.

I am able to scroll back and forth.
 

https://user-images.githubusercontent.com/53316345/222953280-d4f20885-7f32-4eab-8902-b32ebf885352.mov

**Notes for Reviewers**
Some minor improvements are pending

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9452cb0d54dbafbeb244be86665aa91b88f82f46 at: https://64046948f086d479806afa09--layer5.netlify.app

**Comment by leecalcote** [comment]
@Udit-takkar this is a good step forward. 👏 

An aspect of this behavior that remains outstanding is that of the SVGs not positioning in the vertical middle of each section. Perhaps, this is a behavior that is most visible when visitors have "tall" windows.


https://user-images.githubusercontent.com/7570704/222978165-71cbe180-4082-4dcc-89cd-66b6ab58639d.mov

**Comment by Shivam-AfA** [comment]
@Udit-takkar nice work here 👍. Another suggestion is to slow down the scrolling a bit for the sections. Do consider mobile responsiveness as well, it isn't working the same as on desktop.

**Comment by Udit-takkar** [comment]
@Shivam-AfA okay thanks for reviewing

**Comment by l5io** [comment]
🚀 Preview for commit ad5015be622a9e5185d848e75d78b2a90e180fee at: https://6405f6342bd72c0812c3e009--layer5.netlify.app

**Comment by leecalcote** [comment]
@Udit-takkar @Shivam-AfA please ensure that the timeline gap makes sense for both desktop and mobile. Use different a different configuration based on whether visitors are scrolling or touching, if you can, or at least minimally, whether visitors are on desktop or mobile.

**Comment by leecalcote** [comment]
@Shivam-AfA let's get this merged, given the criticality of this page and the fact that it fixes most of the issue already.

**Comment by leecalcote** [comment]
@Udit-takkar, you can follow up with another PR. 👍

**Comment by Shivam-AfA** [comment]
@Udit-takkar The helping indicators need to be removed. They now appear on the live site. // @leecalcote 
image

**Pull request merged**
