### PR TITLE
Added contact form modal component

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added a component for ContactForm Modal.
Also, fixed a small issue with the thumbnail path in the navbar.

**Notes for Reviewers**
For testing, you can see the modal on the projects page. At the bottom, click the `Contact Us` button.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote here you go 🚀

**Comment by leecalcote** [comment]
Whoo-hoo!

**Comment by leecalcote** [comment]
This looks nice. I wish that we didn't have to display the Mailchimp logo.

**Comment by leecalcote** [comment]
The modal doesn't seem to work in Safari.

**Comment by leecalcote** [comment]
The console in Safari shows:

```
[Error] Failed to load resource: the server responded with a status of 403 () (hosted-contact-form.37b2ec51.css.map, line 0)
```

**Review by leecalcote — APPROVED** [review]

**Comment by Tanuj22** [comment]
In mobile, it's not letting me scroll to the top. So I can't click the cross and close the model

**Pull request merged**
