### PR TITLE
[Home] Banner: add button to playground

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Description**

This PR has a bug in which the new button icon is not being properly imported.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@shivam-afa, help needed, please.

**Comment by Shivam-AfA** [comment]
@leecalcote Looking into this.

**Comment by leecalcote** [comment]
> @leecalcote Looking into this.

@Shivam-AfA any luck?

**Comment by leecalcote** [comment]
@Shivam-AfA ok, yes.

**Comment by Shivam-AfA** [comment]
Alright, pushing and merging...

**Pull request merged**
