### PR TITLE
Add community member profile

### LINKED ISSUE #3749: [Community] Member Profile: Arunima Chaudhuri
**Current Behavior**

@tinniaru3005  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @tinniaru3005  as a contributor and community member by creating a profile on https://layer5.io/community/members.

GitHub: https://github.com/tinniaru3005
Twitter: https://twitter.com/arunimastwt
LinkedIn: https://www.linkedin.com/in/arunima-chaudhuri/
Link to profile picture: https://drive.google.com/file/d/1TWODLl6whWGhUdPeq81KVC1ReKoQ9VZ-/view?usp=share_link
Short Bio: I am a final-year undergrad student majoring in Computer Science Engineering. I love contributing to open-source projects. I have learnt a lot while contributing to projects at Layer5 and interacting with the community. My contributions are mainly in front-end projects. I also write blogs on Hashnode. I love sharing my knowledge and experiences with others and learning from their backgrounds and journey. I try to give my best in whatever I do. I love travelling and meeting new people from around the world. I also enjoy listening to music and reading books.
Location: Kolkata, India 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
Signed-off-by: Sheikh-JamirAlam <alamjamir15@gmail.com>

**Description**
Added community member profile.

This PR fixes #3749 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a8194d721da55f4995a58443dd491d7868df79e0 at: https://63ea3155be188d0b0a5c0e0d--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
Hey @Sheikh-JamirAlam, I appreciate your enthusiasm for contributing to the community 😄 . But please wait before you make any PR, wait for someone to get the issue assigned to you. This time I'm considering this PR but please keep this in mind for your future PRs.

**Comment by leecalcote** [comment]
Rounding off @UtkarshMishra12's message: the primary reason to try to secure issue assignment first is simply to avoid duplicative work and undue heartache for all contributors involved in the same effort. Outside of this, @Sheikh-JamirAlam keep up the good work! 👍

**Comment by Sheikh-JamirAlam** [comment]
@leecalcote Understood. Will keep that in mind.

**Review by tinniaru3005 — APPROVED** [review]
Looks great! :)

**Review by eeshaanSA — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit d26b68c0b6e67fcbab00c93fc61932d76a548ad8 at: https://63eb3c75f3e6c95745b7c13d--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @Sheikh-JamirAlam 🥇

**Pull request merged**
