### PR TITLE
fix: remove nested links and buttons

### LINKED ISSUE #2740: Wrong nested interactive element.
**Current Behavior**
Buttons(`<button></button>`) are descendants of Links(`<a></a>`).

**Desired Behavior**
There shouldn't be nested interactive elements. Having them is a bad practice according to:

- [this Reddit post](https://www.reddit.com/r/webdev/comments/ce4w59/is_it_bad_practice_to_wrap_a_button_in_an_a_href/)
- [stackoverflow](https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5#:~:text=It%20is%20illegal%20in%20HTML5,button%20element%20inside%20a%20link.&text=To%20whom%20it%20may%20concern,is%20social%2Dmedia%20type%20laziness.)

Ideally, it should either be a link to go to another page or a button to perform an action. [CSS-tricks post](https://css-tricks.com/buttons-vs-links/) might be of help to determine when to use either.

---
**Screenshots / Mockups**

Screenshot (437)_LI

**Alternatives**

On checking the [Button component](https://github.com/layer5io/layer5/blob/master/src/reusecore/Button/index.js), I noticed that this [mistake](https://github.com/layer5io/layer5/blob/98db95541b523d1e4b27d6363d6f42ad1ba41cc1/src/reusecore/Button/index.js#L34) occurs whenever there is a `href` attribute.
Styled-Components have an `as` attribute that can switch elements.
One solution is to use `as="a"` if `URL prop` is present, else `as="button"`. And there should be an `options` object that gets filled depending on whether URL is present or not.

So it might look like:
> let options = {
>    className: addClasses.join(" "),
>    ...props
> }
> if(props.url) {
>   options = { ...options, as: "a", target: "_blank", rel: "noreferrer"}
> } else {
>  options = { ...options, onClick: props.Onclick }
> }

> <BtnStyle { ... options}>
>  ....
> </BtnStyle>

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
Signed-off-by: Olaleye Blessing <Olayinkablexxy@gmail.com>

**Description**
Fix wrongly nested links and buttons.
This PR fixes #2740

**Notes for Reviewers**
Still needs to update components that're affected by these changes.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Olaleye-Blessing** [comment]
I was planning to fix some layouts affected by this change but I can't cause I'm having a weird error while trying to run the site locally. This started today.

Screenshot (556)

One obvious affected layout is the screenshot below: 

Screenshot (557)_LI

the paragraph/text in each article is shifted downwards

**Comment by Olaleye-Blessing** [comment]
@leecalcote

**Comment by leecalcote** [comment]
I missed your ping here, @Olaleye-Blessing. @YashKamboj will you have a look at this?

**Comment by l5io** [comment]
🚀 Preview for commit a9ba56f364409fb27dd58f4937d249796a199585 at: https://629e95ad8c09091969e7509b--layer5.netlify.app

**Comment by YashKamboj** [comment]
@Olaleye-Blessing Are you still facing the errors, as i can see that you are using windows, why don't you use git bash to use make commands or wsl

**Review by YashKamboj — COMMENTED** [review]
You did a great work , but i want to ask that why don't you use the simple solution like adding `<form>` around the button, it would a simple fix

**Comment by Olaleye-Blessing** [comment]
> @Olaleye-Blessing Are you still facing the errors, as i can see that you are using windows, why don't you use git bash to use make commands or wsl

I formatted my laptop some weeks ago. I will try again and see if the error is gone.

**Comment by Olaleye-Blessing** [comment]
> You did a great work , but i want to ask that why don't you use the simple solution like adding `<form>` around the button, it would a simple fix

I don't understand this. Could you explain further? I think what I'm trying to do is to prevent having a `<button>` being nested inside a `<a>`.

**Comment by YashKamboj** [comment]
@Olaleye-Blessing  i meant something like this
```
<form action="http://example.com/" method="get">
  <button>Visit Website</button>
</form>
```

I also found something else too , not sure if it will work , give this a try too
`<button type="button" onclick="location.href='http://www.stackoverflow.com'">ABC</button>`

**Comment by Olaleye-Blessing** [comment]
@YashKamboj true, the form will work. But don't you think screen readers are going to have a problem?

According to [css trick article](https://css-tricks.com/buttons-vs-links/), there should be a difference when using a `link` and a `button`. Using a button with onClick will show a button even for links.

**Comment by Olaleye-Blessing** [comment]
And I think my drafted pull request has fixed the issue, the only thing left is to correct the layouts that have been affected.

**Comment by Olaleye-Blessing** [comment]
@leecalcote @YashKamboj. Like I said earlier, the issue has been fixed but some layouts are affected. Should the layouts be fixed in this pull request?

**Comment by YashKamboj** [comment]
@Olaleye-Blessing  i gues @Nikhil-Ladha could give you a better review on this one

**Comment by l5io** [comment]
🚀 Preview for commit f54ac69ba7dbbae87c8cf700de5e3e8401d742d6 at: https://62a6d04434343a770f57aa70--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Everything else seems fine, just that `box-shadow` effect on the news section on the home page needs to be fixed.
Can you please take care of that @Olaleye-Blessing ?

**Comment by Nikhil-Ladha** [comment]
That is, adding a `box-shadow: none` after this [line](https://github.com/layer5io/layer5/blob/f54ac69ba7dbbae87c8cf700de5e3e8401d742d6/src/sections/Home/So-Special-Section/so-special-style.js#L92) will fix the issue.

**Comment by Nikhil-Ladha** [comment]
Please follow the instruction mentioned [here](https://github.com/layer5io/layer5/pull/2818/checks?check_run_id=6858173510) to fix the DCO check

**Comment by Olaleye-Blessing** [comment]
@Nikhil-Ladha done

**Comment by l5io** [comment]
🚀 Preview for commit 16fe50944fe378bb239a56e134b662df252c8ea3 at: https://62a759b38cadbf0651423acc--layer5.netlify.app

**Comment by leecalcote** [comment]
Uh-oh. There seems to be an adverse effect here of the Saffron (yellow) color button style going missing. Let's revert this PR to immediately get the styling returned and then look to have this PR's changes re-implemented.

**Comment by Nikhil-Ladha** [comment]
> Uh-oh. There seems to be an adverse effect here of the Saffron (yellow) color button style going missing. Let's revert this PR to immediately get the styling returned and then look to have this PR's changes re-implemented.

Where did you see this effect? I couldn't find it 🤔

**Comment by Nikhil-Ladha** [comment]
Ok, now I see what went wrong.
The buttons having internal link got affected. @Olaleye-Blessing can you take a look and fix it?

**Comment by Olaleye-Blessing** [comment]
ok, I'll look into it.

**Pull request merged**
