### PR TITLE
feat: tooltip for badges on the community member page

### LINKED ISSUE #3797: Add tooltip on hover effect on the badges in Individual member profile page.
### Current Behavior

Currently, there is no tooltip on hovering over badges in the individual pages of members on the page https://layer5.io/community/members.
image

### Desired Situation

Add the tooltip while hovering over the badges.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by roopeshsn**
**Description**

Implemented a tooltip for badges on the community member page. Also, refactored the code for the badges in src/sections/Community/Member-single/index.js

This PR fixes #3797 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by roopeshsn** [comment]
Still, two issues need to be addressed,
1. The badges become oval in shape on hover (which is not expected).
2. The tooltip of the first badge is not fully visible.

**Comment by l5io** [comment]
🚀 Preview for commit adf6e9e37c72f14c8f0e6e7db5a652b1d50a43a6 at: https://6406d4acfef9bd3cb97a8fa5--layer5.netlify.app

**Comment by leecalcote** [comment]
Heads-up, @roopeshsn. The first tool tip is accidentally being cutoff.

Screenshot 2023-03-08 at 5 52 52 PM

**Comment by Chadha93** [comment]
@roopeshsn  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 652986e0798a33ac2095839ae72727bd87a11507 at: https://64182dfc2a3b281811c924ed--layer5.netlify.app

**Review by divz-codess — CHANGES_REQUESTED** [review]
The tooltip obscuring the next item doesn't look good so it should be kept at bottom while ensuring that its not being clipped.
Screenshot (360)

**Comment by Chadha93** [comment]
> The tooltip obscuring the next item doesn't look good so it should be kept at bottom while ensuring that its not being clipped. Screenshot (360)

Ouch, the Meshery badge looks like an egg. :egg: A padding fix needed there as well.

**Comment by Chadha93** [comment]
@roopeshsn You there? Are you continuing this PR?

**Comment by roopeshsn** [comment]
> @roopeshsn You there? Are you continuing this PR?

Yes, @Chadha93! I need help with this. Tried multiple ways to rectify the shape of badges but none worked!

**Comment by leecalcote** [comment]
@chinu-anand perhaps, you can assist.

**Comment by chinu-anand** [comment]
Sure @leecalcote.

**Comment by l5io** [comment]
🚀 Preview for commit 96011a41a7c198b51b5db4f87f2db08c5f1c6f9a at: https://644400bf7111a44757e7624f--layer5.netlify.app

**Comment by roopeshsn** [comment]
I am closing this pull request because there are problems fetching the branch in my new machine. I'll open another PR.

**Pull request closed without merging**
