### PR TITLE
adjusted scaling of blog images

### LINKED ISSUE #581: Images in blog not properly scaled
**Description**
The images in the blog cards are not properly scaled in [here](https://layer5.io/blog) . So, it needs to be fixed.

**Expected Result**
All the blog cards should be equally scaled & aligned in the [blog](https://layer5.io/blog) page.

**Screenshots**
L5

---
[Optional] **To Reproduce**
1. Go to 'https://layer5.io/blog'
2. Take the screenshot as the reference & go through the page
3. See error

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**
Fixed the images in the [blog](https://layer5.io/blog) cards which were not properly scaled.

This PR fixes #581 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Well, the height of the images is now good. But, if we could also make the width of them to be the same then it would be better.

**Comment by Neilblaze** [comment]
> Well, the height of the images is now good. But, if we could also make the width of them to be the same then it would be better.

Well when I was making that PR, this came into my mind. But not every image will look good if I make that change since only one CSS class is applied to all of them for both `posts` & `news`

**Comment by Nikhil-Ladha** [comment]
It will not look good if its stretched to do so, but i stead if using CSS it could be adjusted to fit the width then it will be ok, I think so. For a better idea if you van make the change and share 1 or 2 ss of the page, then it will be easier to consider.

**Comment by Neilblaze** [comment]
So, at the moment, it looks -

Css unapplied

And after I did some tweaks to the css class, it now looks like - 

css applied


Now you say which is better :)

**Comment by Nikhil-Ladha** [comment]
Haha😆! Cool..

**Pull request merged**
