### PR TITLE
added service mesh pattern book content to layer5-ng site

### LINKED ISSUE #1171: Add Book Contents to a Page on Layer5 site and Layer5-ng site
**Current Behavior**
The website has book contents page at https://layer5.io/books/service-mesh-patterns.

**Desired Situation**
Add the [book contents](https://docs.google.com/spreadsheets/d/1sJAsBPAc08Pml5uBijHpb0AvJxe6IoVtzhwBFDiVLCw/edit#gid=1453706035) to the page.

---

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by lolyparty**
Signed-off-by: lolyparty <ololadeolayiwola01@gmail.com>

**Description**

This PR fixes #1171 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by lolyparty** [comment]
@Jashpatel1 Is this correct?

**Review by Jashpatel1 — COMMENTED** [review]
@lolyparty Looks good to me. Just revert the changes in package-lock.json.
@leecalcote https://deploy-preview-1246--layer5ng.netlify.app/books/service-mesh-patterns

**Comment by Nikhil-Ladha** [comment]
I would suggest using react-tables, it will even make the code cleaner.

**Comment by Nikhil-Ladha** [comment]
Also, doesn't this book have an image?

**Comment by lolyparty** [comment]
> @lolyparty Looks good to me. Just revert the changes in package-lock.json.
> @leecalcote https://deploy-preview-1246--layer5ng.netlify.app/books/service-mesh-patterns

I don't know what the problem is but I can't run the development area successfully with the old package-lock.json I keep getting errors then I did an `npm install`, that was what I got. So I can do the same to the layer5 site too?

**Comment by Nikhil-Ladha** [comment]
That's, fine. Just keep the changes in package-lock.json on your system, don't add it in the commit.

**Comment by lolyparty** [comment]
> I would suggest using react-tables, it will even make the code cleaner.



> Also, doesn't this book have an image?

No, it doesn't.

**Comment by lolyparty** [comment]
> That's, fine. Just keep the changes in package-lock.json on your system, don't add it in the commit.

Ok, noted.

**Comment by Nikhil-Ladha** [comment]
> > Also, doesn't this book have an image?
> 
> No, it doesn't.

Okay, but please update the code to use react-tables.

**Comment by lolyparty** [comment]
> > > Also, doesn't this book have an image?
> > 
> > 
> > No, it doesn't.
> 
> Okay, but please update the code to use react-tables.

Ok. I haven't used that before, but I'll learn it.

**Comment by Jashpatel1** [comment]
Duplicancy with #1265

**Comment by Jashpatel1** [comment]
@lolyparty You can continue with this for layer5-ng if you want, but please remove the changes in package-lock.json

**Comment by lolyparty** [comment]
> @lolyparty You can continue with this for layer5-ng if you want, but please remove the changes in package-lock.json

Yes,  I will

**Comment by Tanuj22** [comment]
@lolyparty any updates here?

**Comment by lolyparty** [comment]
> @lolyparty any updates here?

Took a break, will continue today. I'm finding it difficult to style the jekyll though

**Comment by lolyparty** [comment]
I'll do a new PR now

**Pull request closed without merging**
