### PR TITLE
Layer5 Community Code of Conduct

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

Adding Layer5 code of conduct on layer5.io.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Adeola-Adesoba — APPROVED** [review]
Awesome! @leecalcote I think it looks good from my end. I love the structur and langauge as it is.

**Review by rshivam08 — APPROVED** [review]
Looks good! @leecalcote I think we are good to go.

**Review by PluckyPrecious — APPROVED** [review]
LGTM

**Review by KarenEfereyan — APPROVED** [review]
Looks great @leecalcote this is an absolute welcome development

**Review by Ruth-ikegah — APPROVED** [review]
This looks great and simple. Nice work @leecalcote

**Comment by KarenEfereyan** [comment]
> LGTM

Whats lgtm? 🤔🤔🤔

**Comment by Annysah** [comment]
It looks good and simple 👍 @leecalcote .

**Comment by Ruth-ikegah** [comment]
> > LGTM
> 
> Whats lgtm? 🤔🤔🤔

It means Looking good to me 😊

**Review by Annysah — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, all. Merging...

**Pull request merged**
