### PR TITLE
Added member profile for Freedisch

### LINKED ISSUE #4435: [Community] Member Profile: Freedisch
**Current Behavior**

@freedisch has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @freedisch as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @freedisch
- Twitter: 
- LinkedIn: [thibaut-freedisch-batale-905843208](https://www.linkedin.com/in/thibaut-freedisch-batale-905843208/)
- Meshery Cloud: [a551897f-da39-4d4d-812e-6b299e82c457](https://meshery.layer5.io/user/a551897f-da39-4d4d-812e-6b299e82c457)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #4435 

**Notes for Reviewers**

- creates @freedisch's member profile on https://layer5.io/community/members.
- [Preview](https://649d30bf3b4966407e137a21--layer5.netlify.app/community/members/freedisch)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d181299987105052afadc7b1b7792252b3bcfa58 at: https://649d30bf3b4966407e137a21--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
@vishalvivekm and @Freedisch please have a look

**Comment by Freedisch** [comment]
> @vishalvivekm and @Freedisch please have a look

Hi @Ghat0tkach looks, just one thing the name it's: Freedisch Thibaut Batale

**Comment by Ghat0tkach** [comment]
> > @vishalvivekm and @Freedisch please have a look
> 
> Hi @Ghat0tkach looks good, just one thing the name it's: Freedisch Thibaut Batale

Done!🚀

**Comment by l5io** [comment]
🚀 Preview for commit 40566158879223326a80c7a1db99d664fe20acf9 at: https://649d47099d5b404fcc3d1e1d--layer5.netlify.app

**Comment by leecalcote** [comment]
LGTM

@Freedisch ✅ ?

**Review by leecalcote — APPROVED** [review]

**Review by vishalvivekm — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
