### PR TITLE
Convert all png of sections directory to webp

### PR DESCRIPTION
**Pull request by Mandeep56Singh**
**Description**

This PR fixes ##5854

**Notes for Reviewers**
it converts  all the png under src/sections directory to webP
and it resolves path 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Mandeep56Singh** [comment]
I am waiting for your feedback

**Comment by l5io** [comment]
🚀 Preview for commit b11dd869589131919ae05b23eef34595fd4f3f72 at: https://66f1dadb46884513f1110169--layer5.netlify.app

**Comment by Mandeep56Singh** [comment]
@sudhanshutech  looks like I maded a mistake 😅
is there a way to fix it  ?

**Comment by Mandeep56Singh** [comment]
@sudhanshutech  yes space has saved 
from 9.3mb to 1.4mb
Before 
Screenshot (485)

after
Screenshot (484)

**Comment by l5io** [comment]
🚀 Preview for commit d7d869903de83a77cc3bca1b1370c1e36d2315d3 at: https://66f451d19b40483e1f18f91c--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thank you for your contribution @Mandeep56Singh 
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Mandeep56Singh** [comment]
@vishalvivekm  sorry, I wasn't able to attend the meeting, please tell if this pr need changes. I am not able to see the changes requested by @sudhanshutech.

**Comment by l5io** [comment]
🚀 Preview for commit 01a808e5b46681b6e22d12de06bc30d235e518be at: https://66fd31a32515e4d7ee2ba398--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Mandeep56Singh you might have rebased the commit please revert those changes. Either you can create a new pr and closing this one and in the new pr update to webp in chunks and not every images in same pr.

**Comment by Mandeep56Singh** [comment]
> @sudhanshutech looks like I maded a mistake 😅 in commit history I forget to update the branch, and simply push the commit history
> 
> is it a problem ? is there a way to fix it ?

@sudhanshutech please tell me, how to fix the mistake I created.

**Comment by sudhanshutech** [comment]
you can create a new pr and create prs in chunks that is take lee number of file changes and in itertative way

**Comment by sudhanshutech** [comment]
please open a new pr at will

**Pull request closed without merging**
