### PR TITLE
Corrected images for dark theme on Projects page

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam-AfA <shivamsood634@gmail.com>

### **Description**

**This PR fixes # 3220**
- I have added functionality to set the same font color when dark theme is enabled on Projects page.
- Keeping in mind the previous look for the logos, I have kept the logo symbols as colored while the text appears white for all logos except **Open Application Model** ( I could not find a suitable image file for it).

The page appears as below in the **dark theme**:

image

and in the **light theme**:

image

**Notes for Reviewers**

Looking forward to working on any more changes if required.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Shivam-AfA thanks for submitting these fixes. Looking good so far. Are you setting new precedent here or is this the same approach that we've taken in other places with respect to #id-of-element-corresponds-to-image?

**Comment by l5io** [comment]
🚀 Preview for commit ca408cbd25bb5fc39a89e6d4b6cc5080c42f319a at: https://637400fc728d51235827f229--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA thanks for submitting these fixes. Looking good so far. Are you setting new precedent here or is this the same approach that we've taken in other places with respect to #id-of-element-corresponds-to-image?

@leecalcote I have assigned id's to image elements and then changed their source in the style component. So I imported the images for light and dark theme in the style component and used ternary operator to change the image source when the theme button is clicked.

**Comment by leecalcote** [comment]
Makes sense. I'm wondering if this is consistent with our approach in the rest of the site, though.

**Comment by Shivam-AfA** [comment]
I don't think it would cause any issues in other areas of the website.

**Comment by leecalcote** [comment]
@Shivam-AfA, it won't, you're right. That's not what I'm asking. This is a large site. In order to realistically sustain it, consistency in implementation is necessary. Take a moment to confirm the approach taken in on other pages and other components, so that site maintenance and defect escape rate remains as minimal as possible.

**Comment by Shivam-AfA** [comment]
Okay sure, I'll look into it.

**Comment by l5io** [comment]
🚀 Preview for commit 8188d66e6f2e9121de8b67f4de87c7ef5df3868e at: https://637524a56cf2ba23b5c49388--layer5.netlify.app

**Comment by leecalcote** [comment]
> Okay sure, I'll look into it.

Findings?

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
I don't think this is a consistent approach.
As of now, we import the images for the dark theme in the `.js` file itself (not the style.js file) and switch based on the `props.theme.darkTheme` value. We should be following the same approach here as well.

For reference, check the code of the landscape page.

**Comment by Shivam-AfA** [comment]
> Findings?

> I don't think this is a consistent approach.
As of now, we import the images for the dark theme in the .js file itself (not the style.js file) and switch based on the props.theme.darkTheme value. We should be following the same approach here as well. 
For reference, check the code of the landscape page.

I understand the difference in the approach I used and the precedent approach. I am working on the changes. @leecalcote @Nikhil-Ladha

**Comment by leecalcote** [comment]
Awesome. Thank you, @Shivam-AfA. 👍 

Oh, and, yeah... just as a small, tiny, little side note, thank you, MeshMate @Nikhil-Ladha.

**Comment by Shivam-AfA** [comment]
Hey @leecalcote @Nikhil-Ladha I have made changes to the code.

**Comment by l5io** [comment]
🚀 Preview for commit 7cd58f96d4bf4931853250f4980b32eef4533d37 at: https://637c6176799d534166ab6178--layer5.netlify.app

**Review by Nikhil-Ladha — COMMENTED** [review]
I just noticed how the rest of the icons on this page is being updated based on the theme.
Proposed change for all the icons:
Use SVG versions for all of them and switch the icon based on the theme instead of tweaking the color using CSS.
Also, name the icons (while importing) as `Icon` and `Icon_Dark`

**Comment by Shivam-AfA** [comment]
@Nikhil-Ladha Actually I have not made any changes to CSS. I have selected image source based on the theme of the page. I have done this by using the theme props. And since I could not find the suitable dark theme images for **Open Service Mesh** and **Service Mesh Interface** in the assets/images folder, I changed the text Color using photoshop and that's the reason they are imported as PNG.

> Also, name the icons (while importing) as Icon and Icon_Dark
Okay I'll do that.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Actually I have not made any changes to CSS. I have selected image source based on the theme of the page. I have done this by using the theme props. And since I could not find the suitable dark theme images for **Open Service Mesh** and **Service Mesh Interface** in the assets/images folder, I changed the text Color using photoshop and that's the reason they are imported as PNG.

I know that what I am trying to say is to update the other images in that component to render a dark/light image based on the theme value.
Currently, it is being done using CSS.

i.e, for example, consider the `Envoy` SVG, update the text in photoshop/Figma to have white color and export that as an SVG image, add it to the repo under the `assets` path (check the current path of the icons) and name it like `envoy-white-text.svg`. Similarly, do it for the rest of them and update all the images.

**Comment by Shivam-AfA** [comment]
> > @Nikhil-Ladha Actually I have not made any changes to CSS. I have selected image source based on the theme of the page. I have done this by using the theme props. And since I could not find the suitable dark theme images for **Open Service Mesh** and **Service Mesh Interface** in the assets/images folder, I changed the text Color using photoshop and that's the reason they are imported as PNG.
> 
> I know that what I am trying to say is to update the other images in that component to render a dark/light image based on the theme value. Currently, it is being done using CSS.
> 
> i.e, for example, consider the `Envoy` SVG, update the text in photoshop/Figma to have white color and export that as an SVG image, add it to the repo under the `assets` path (check the current path of the icons) and name it like `envoy-white-text.svg`. Similarly, do it for the rest of them and update all the images.

Okay I got it. You want me to use the theme value for already placed images as well like **Linkerd** and **CNCF**. I'm on it!

**Comment by Shivam-AfA** [comment]
Hey @Nikhil-Ladha @leecalcote I have made the required changes. I have updated all the logos so that they should change based on the theme rather than through CSS.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
We already have the meshery dark, cncf white, osm (open-service-mesh) white, and service-mesh-interface logo. No need to add those again, reuse them

**Comment by l5io** [comment]
🚀 Preview for commit 8f93924b4213e51a8fd7f863cc94aef22c323756 at: https://6383903d603c3c7f702c0037--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
> We already have the meshery dark, cncf white, osm (open-service-mesh) white, and service-mesh-interface logo. No need to add those again, reuse them

@Nikhil-Ladha  By dark do you mean the dark colored logo or the logo used for dark theme?

**Comment by Shivam-AfA** [comment]
> We already have the meshery dark, cncf white, osm (open-service-mesh) white, and service-mesh-interface logo. No need to add those again, reuse them

@Nikhil-Ladha Actually the meshery dark logo that was already present had a different size when I used it, so I edited the svg file and created a new logo.

**There is a difference in size of icon as shown below**

image

image



And for others, (cncf white, osm white and service-mesh interface) the white logo svg files had the logo symbols also as white. But as I had already mentioned in the previous comments, 

> Keeping in mind the previous look for the logos, I have kept the logo symbols as colored while the text appears white for all logos

So I edited the colored svg files to change only the text colour to white. Since other logos like **Linkerd** and **Envoy** also had the logo symbol as colored and only the text color as white.

So kindly confirm which logos do you want to be used.

**Comment by Nikhil-Ladha** [comment]
Ok, understood the reason for other logos.
But, for meshery we have one without background. Compare them and see if it works or not, I believe it should.
Secondly, that's nit much of a size difference we are concerned about. So, good to go around that.

**Comment by Shivam-AfA** [comment]
@Nikhil-Ladha  Okay I have changed the meshery dark logo.

**Comment by l5io** [comment]
🚀 Preview for commit d06f765ee3c814f45682669e14a0582e7b551ad8 at: https://6384579248c6550d7ef7925c--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
