### PR TITLE
bugFix [Component Styling] Fix <i> tags on home page

### LINKED ISSUE #5229: [Component Styling] Enhance FeaturesContainer to allow for selective styling
### Current Behavior
Unable to style words within the `descr` property of the FeaturesContainer component.

### Desired Behavior
It'd be great to be able to style words within the descriptions here - https://github.com/layer5io/layer5/blob/master/src/sections/Home/FeaturesContainer/index.js#L45-L46. Like putting italics around the word "and".

### Screenshots / Mockups

Screenshot 2023-12-22 at 2 25 25 PM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by horizenight**
**Description**

This PR fixes #5229

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 395716ff103da50f8c415074d41c3e597cc5a1b5 at: https://658697ee58d63a64e720bb2e--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
Looks good!

**Comment by saurabh100ni** [comment]
Hey @horizenight ,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Review by leecalcote — APPROVED** [review]
Thanks!

**Comment by leecalcote** [comment]
There’s a merge conflict that is in need of being addressed.

**Comment by l5io** [comment]
🚀 Preview for commit 1c642a1a7b749a815774ec63122b3a6ab28d62e9 at: https://662ea25b4c95ce0843d217fb--layer5.netlify.app

**Pull request merged**
