### PR TITLE
Updated GetNightHawk Logo on Project Grid

### LINKED ISSUE #1794: [Project] Getnighthawk Logo update for Project Grid
**Current Behavior**
The old logo of Getnighthawk is currently on the Project Grid page 

chrome_8GiA6JJjbW

**Desired Situation**
Update it to the new logo of getnighthawk. You can find the suitable files required for this at https://layer5.io/company/brand or simply link it with the already existing logo at https://github.com/layer5io/layer5/blob/master/src/assets/images/getnighthawk/icon-only/SVG/getnighthawk-logo.svg

The Logo already exists in the assets.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #1794
Updated GetNightHawk Logo at https://layer5.io/projects/

**Notes for Reviewers**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@vinayaksh42 Could you review this PR? 👀
Please do let me know if any changes are required :)

**Comment by vinayaksh42** [comment]
> @vinayaksh42 Could you review this PR? 👀
> Please do let me know if any changes are required :)

sure, waiting for the build preview.

**Comment by l5io** [comment]
🚀 Preview for commit 2097e61c7216ca135c514b6188c454eda5db7675 at: https://607d7c2478459a3db798d189--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2097e61c7216ca135c514b6188c454eda5db7675 at: https://607d7c134a11f6ba4b1008ad--layer5ng.netlify.app

**Comment by vinayaksh42** [comment]
Looks great @adithyaakrishna

**Review by vinayaksh42 — APPROVED** [review]

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
One thing, though can you confirm if we download the Getnighthawk asset from the brand page what do we get. If those are correct or not, currently I am on phone, otherwise I would have checked it.

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Yes, All the assets are downloadable as `.zip` files

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Yes, All the assets are downloadable as `.zip` files

It was downloadable, anyways. What I am asking is if the assets inside the zip files are the correct one or not. Check that.

**Comment by adithyaakrishna** [comment]
Ohhh, My Bad I hadn't read it properly, will check that 😶

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Yes, They have the old ones still
image
Will update those too 💯

**Comment by Nikhil-Ladha** [comment]
If you can please delete the old ones, as well.

**Comment by adithyaakrishna** [comment]
Yess, Will do that 😂

**Comment by l5io** [comment]
🚀 Preview for commit 892e5f7db41c967c926702580b8cc0e9e6240404 at: https://607d932aa4ca12d5ac773e33--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
You have replaced the files within zip, right and not created new ones?

**Comment by Nikhil-Ladha** [comment]
Also, you haven't replaced the zip files inside the src/assets for getnighthawk.

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha the `getnighthawk.zip` under `src/assets` already had new files
I've replaced the `brand-kit.zip` which had all the assets and also inside `static/brand`

**Pull request merged**
