### PR TITLE
Fixed Image Rendering Issue and Updated Makefile

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**
Fixed Image Rendering Issue and Updated Makefile

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e5dbfdd8db6ba4287fecc80b43b2ffb135713759 at: https://607c83701d8fad4db25fa80f--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e5dbfdd8db6ba4287fecc80b43b2ffb135713759 at: https://607c837f8a1939b672284271--layer5ng.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
But I will wait for other's review 😁

**Review by Tanuj22 — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
All, what issue was this PR fixing? 

After this PR was merged, a number of image links are broken. Let's revert this update to fix the broken links, and subsequently, incorporate the updates in this PR as needed.

**Comment by leecalcote** [comment]
See https://github.com/layer5io/layer5/issues/1798

**Pull request merged**
