### PR TITLE
Footer Updates

### LINKED ISSUE #699: [NG] Remove the left padding in subitems of Footer
**Current Behavior**
This issue pertains to layer5-ng site. The subitems in the footer have left padding making it look as indented.

**Desired Behavior**
Remove the left-padding to make it in line with its title. The changes have to be made in [styles of Footer section.](https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/Footer/footer.style.js) As it is a change to be made in layer5-ng branch, pull a request in the layer5-ng branch.

---
Screen Shot 2020-09-02 at 2 00 53 PM

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR fixes #699 

**Notes for Reviewers**
Also, I have reduced the size of Layer5 logo in the footer and added a short text description

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Looking good, @Jashpatel1. Do you mind bringing in the `#3c494f` color as the footer background color?

On the current layer5.io site, we have intentionally muted the colors of the language flags (as an infrequently used utility) as their full color draws too much attention and distracts users from what we want really want to draw them into (the twitter feed or other links). We can crack open a new issue on this change, if you like.

**Comment by Nikhil-Ladha** [comment]
Shouldn't this change also be done for the Mobile view?

**Comment by Jashpatel1** [comment]
> Shouldn't this change also be done for the Mobile view?

In case of left-padding, I think its looking nice for the mobile view. So I left it unchanged, if you feel it should be removed, I will do so.

**Comment by Nikhil-Ladha** [comment]
Well, it does look good. I was just asking if for the consistency we are gonna do that too or not?
/cc @leecalcote

**Comment by Jashpatel1** [comment]
> Looking good, @Jashpatel1. Do you mind bringing in the `#3c494f` color as the footer background color?
> 
> On the current layer5.io site, we have intentionally muted the colors of the language flags (as an infrequently used utility) as their full color draws too much attention and distracts users from what we want really want to draw them into (the twitter feed or other links). We can crack open a new issue on this change, if you like.

Screenshot from 2020-09-14 16-38-56
Screenshot from 2020-09-14 16-38-20

**Comment by leecalcote** [comment]
@Jashpatel1 thank you. I think the darker color provides a nice offset for the footer from the rest of the site as it is right now.

@Nikhil-Ladha, good call out. Let's be consistent between both views and have the section heading and list items flush.

**Review by leecalcote — DISMISSED** [review]
Good to merge after updating the mobile view.

**Comment by Nikhil-Ladha** [comment]
Just few things,  the blank space on the top of footer can be reduced a bit.
Also, is it just me or really, the `Community` and `Company` is a bit misaligned? The `Company` word is looking like its shifted a bit upwards.

**Comment by Jashpatel1** [comment]
> Just few things, the blank space on the top of footer can be reduced a bit.
> Also, is it just me or really, the `Community` and `Company` is a bit misaligned? The `Company` word is looking like its shifted a bit upwards.

I am unable to find what is causing it to lift the Company title. As all are defined under the same class.

**Comment by leecalcote** [comment]
Nice. This is a good improvement.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
