### PR TITLE
add shecodeafrica contributhon to programs page

### LINKED ISSUE #1774: [Program] Add SheCodeAfrica Contributhon Program to Open Source Programs Page
**Current Behavior**

Layer5 is participating in SheCodeAfrica Contributhon Program & [Programs Page](https://layer5.io/careers/programs) is missing card & details for it .  

**Desired Situation**

Add a Card & details for SheCodeAfrica Program .
Please refer to this doc for more details about the program 
https://docs.google.com/document/d/1_LUAqcCnAl-8lCZMKBSRUsZB1358SjHT3cPyej2wTcg/edit#

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Thea10**
Signed-off-by: Cynthia <olucynakin@gmail.com>

**Description**

This PR fixes #1774

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit aa539332c9b1c1c4269e3d3924933c533c633390 at: https://6072d89ec6f45d7487b515fd--layer5ng.netlify.app

**Review by Jashpatel1 — COMMENTED** [review]
Great work here. Looks good. Thanks, @Thea10 for this.
Just a small change. Can you come up with some other subtitle as the title and subtitle are the same on the page?

@leecalcote Any comments on content to be added?

**Comment by leecalcote** [comment]
A call to action to join the community would be great.

**Comment by leecalcote** [comment]
A call to action just under the description of the program and just above the page footer, that is.

**Comment by l5io** [comment]
🚀 Preview for commit 62fcb1c111f3db86a287c12c8ade7b772aa9a921 at: https://6075949a18fa27cca305257e--layer5ng.netlify.app

**Comment by Ruth-ikegah** [comment]
Hi, @Thea10 nice work on this! There are some details you left out from this doc: https://docs.google.com/document/d/1_LUAqcCnAl-8lCZMKBSRUsZB1358SjHT3cPyej2wTcg/edit. Please try to update it

**Comment by l5io** [comment]
🚀 Preview for commit 8f2f7bf5480907b2b15cd32c87acd89f290f015f at: https://6077abde5dd1673ff4c8014d--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Nice level of detail. 👍 I'm looking forward to the Mentee names on this list changing into hyperlinks. 😄 

Could we add a call to action at the bottom to either "Stay meshy and subscribe!" or to join the community? There are reusable components for such call to actions available in the code base.

**Comment by Thea10** [comment]
@leecalcote  Yes, I added a participate button to join the community on Slack.
 I think @Ruth-ikegah  is working on creating issues for getting the mentee's community member profiles.

**Comment by leecalcote** [comment]
Oh, I see the "Participate" button now. Ok, that'll do the trick.

Good - it takes a bit of time for community members to earn a profile on the site. Each of you are on your way. 💪 A milestone to reach before a member profile, is an invitation for your GitHub user to join the `layer5io` org. MeshMate Ruth is well-versed in the contributor journey and inflection points by which each of these milestones is triggered.

**Review by leecalcote — APPROVED** [review]
Looking good. 👍

**Pull request merged**
