### PR TITLE
Added a Form in index.mdx for 2nd book

### PR DESCRIPTION
**Pull request by Deepak-Choudhary0**
**Description**

This PR fixes #

This PR solves the issue https://github.com/layer5io/layer5/issues/4219
by adding a form at https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition.
This PR will successfully added a Form and respective UI as in https://github.com/layer5io/layer5/pull/4425
and this PR is recreated from https://github.com/layer5io/layer5/pull/4278

**Screenshot from 1st book**

original

**Screenshot of this PR**

mine

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c3386ecf3083dfc3064e81798d5da38901a93b50 at: https://64979442e8a77337e9b0c12f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a7b5865df852279bdde8923358581088e8d251e0 at: https://6497c5245380a24ab5cb979f--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Deepak-Choudhary0

**Comment by vishalvivekm** [comment]
@Deepak-Choudhary0
 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by vishalvivekm** [comment]
// @Ghat0tkach

**Comment by Savio629** [comment]
Let's get feedback in today's website meeting and make sure to complete it by today if possible...
@Deepak-Choudhary0

**Comment by l5io** [comment]
🚀 Preview for commit de3e97f801b0f58fb4aecd170fcb65558919324b at: https://649a3cf27e9b7627c9ba4a60--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 77c586632de2d1a22c4cb8b1b441d058157d3bb2 at: https://649a435ada0f4927df6c452e--layer5.netlify.app

**Comment by Deepak-Choudhary0** [comment]
@leecalcote please review it, i have simplified it as you have done in 1st book

**Review by leecalcote — APPROVED** [review]
Rock on, @Deepak-Choudhary0. Thank you for taking cue from the other page/PR's changes. 👍

**Pull request merged**
