### PR TITLE
Added profile for Colby Stoker

### LINKED ISSUE #3689: [Community] Member Profile: Colby Stoker
**Current Behavior**

@b0id has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @b0id as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @b0id 
- Twitter: 
- LinkedIn: <profilename> https://www.linkedin.com/in/colby-stoker/
- Link to profile picture: https://lh3.googleusercontent.com/a/AEdFTp4CZjjxz4hW0P_kBw7ZteyRGxQPFQiOd-F5Y6b1iGw=s288-p-rw-no

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ShuvamChatterjee28**
Signed-off-by: Deb Prakash Chatterjee <shuvamconcepts28@gmail.com>

**Description**

Added profile under members for Colby Stoker.

This PR fixes #3689 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ShuvamChatterjee28** [comment]
Hey @UtkarshMishra12, you can have to a look into this PR.

**Comment by l5io** [comment]
🚀 Preview for commit f4986192a8add549a6710c1718db0402bcc8d57d at: https://63df9cf048ae0763bb9ce6c1--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
@ShuvamChatterjee28 As of now, please mention only one position i.e Contributor. 
@b0id I can’t wait for you to earn the rest of the positions i.e (Maintainer, MeshMate, Community Manager) 👀 .

**Comment by ShuvamChatterjee28** [comment]
> @ShuvamChatterjee28 As of now, please mention only one position i.e Contributor. 
> 
> @b0id I can’t wait for you to earn the rest of the positions i.e (Maintainer, MeshMate, Community Manager) 👀 . 

Okay, will do in few mints.

**Comment by ShuvamChatterjee28** [comment]
Hey @UtkarshMishra12 and @b0id, it's done.

**Comment by l5io** [comment]
🚀 Preview for commit 1697d30d1d7144f60d6f8cb15fcc784c1b57249f at: https://63e003134e80012e9a29730a--layer5.netlify.app

**Comment by b0id** [comment]
Awesome, this is really nice. I appreciate all the Layer5 community.  I'm gonna be busy, that's for sure. -C

**Review by b0id — APPROVED** [review]
Looks great.  Thank you! (edit: I was looking on mobile, on desktop photo is low res.  I will upload a hi-res photo)

**Comment by b0id** [comment]
@ShuvamChatterjee28 Let me submit a better quality image.  After looking closer it is grainy.

**Comment by b0id** [comment]
It also does list me as a Maintainer and I definitely don't fill that role yet.  I could definitely volunteer as a meshmate, because I definitely feel familiar enough with the code base and developing on it that I could perhaps be of service.  I will leave it up to you guys or whenever you feel good about it.

**Comment by b0id** [comment]
@ShuvamChatterjee28 

https://1drv.ms/u/s!AliBWXvzVumVrXEcLvThibxiZHur?e=a6F7vE

**Comment by ShuvamChatterjee28** [comment]
Done @b0id and @UtkarshMishra12. You can have a look now. Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit e7bca121519e011e1803d945f74d3da1d8addeb5 at: https://63e0e64f6a21a843c20b108e--layer5.netlify.app

**Comment by b0id** [comment]
Much better, thank you so much @ShuvamChatterjee28

**Review by Chadha93 — APPROVED** [review]
LSTM. Looks smart to me @b0id :sunglasses:

**Comment by b0id** [comment]
@Chadha93 It should be immediately updated once merged, correct?  I don't see it live on the site.

**Pull request merged**
