### PR TITLE
Removed service mesh terms and corrected image width

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8a4d70e85e28d444325c5b1ce16678ca52947fa0 at: https://6445b7d003dc5f29462ded59--layer5.netlify.app

**Comment by leecalcote** [comment]
@Shivam-AfA the image in the popout card carousel are being skewed.
Screenshot 2023-04-24 at 5 21 17 AM

**Comment by Shivam-AfA** [comment]
@leecalcote Sorry for this. I'll fix it.

**Comment by leecalcote** [comment]
Thanks. !@

**Pull request merged**
