### PR TITLE
[NG] Common use by components

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR updates components and package-lock.json had some browser configs updates. Do we keep them in @leecalcote @Nikhil-Ladha @Tanuj22 ?

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Why these colors for the social icons?

**Comment by Tanuj22** [comment]
> Why these colors for the social icons?

The brand colors should be used i guess?

**Comment by Tanuj22** [comment]
Also why did `package-lock.json` change?

**Review by leecalcote — APPROVED** [review]
Approving in order to move forward iteratively...

**Comment by Tanuj22** [comment]
@Jashpatel1 remove the conflict

**Pull request closed without merging**
