### PR TITLE
[NG] Revived Brand Kit zip links

### LINKED ISSUE #1384: [NG] Links to brand kit zips broken
**Description**
The download links here are broken - https://layer5ng.netlify.app/company/brand

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by EmperorYP7**
**Description**

This PR fixes #1384 

ZIP links

**Notes for Reviewers**

- A considerable performance hit was observed.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM. I wonder if the performance hit is due to netlify hosting.

**Comment by Nikhil-Ladha** [comment]
Performance hit as in what kind?

**Comment by Nikhil-Ladha** [comment]
Merging it to move forward for the time being......

Thank you @EmperorYP7 for this 🥇

**Comment by EmperorYP7** [comment]
> Performance hit as in what kind?

The development build took too much of memory (almost 6 gigs at its peak) which was not ideal. Later I found it was due to the behaviour of "raw-loader" for zip files. So, I replaced it with "url-loader". Yet I noticed a slightly degraded performance. (May be due to placebo) You may test it well.

**Pull request merged**
