### PR TITLE
Added Service Mesh Patterns

### PR DESCRIPTION
**Pull request by Shivanshu97i**
Signed-off-by: Shivanshu97i <singhshivanshu97@gmail.com>

**Description**
Added Service Mesh Patterns in the Project list.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shivanshu97i** [comment]
@warunicorn19 Is this okay??

**Comment by debo19** [comment]
@Shivanshu97i can you please share a screenshot of the preview here?

**Comment by l5io** [comment]
🚀 Preview for commit 40bb410886a5d49844b365b81d43f2727ecaf800 at: https://614f25dd09f047229d7ab434--layer5ng.netlify.app

**Comment by Shivanshu97i** [comment]
mesh pattern
@debo19 Please check this

**Comment by debo19** [comment]
@Shivanshu97i The image address doesnt seem to correct. Can you refer to the other projects and add the image wherever necessary, then call it. You'll mostly have to add it in `.github/assets/images/`.

**Comment by Shivanshu97i** [comment]
dasd
@debo19 is this ok??

**Comment by debo19** [comment]
@Shivanshu97i yes looks good

**Comment by Shivanshu97i** [comment]
@debo19 Do I need to do anything else or will you be merging this??

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thank you @Shivanshu97i.

**Comment by Shivanshu97i** [comment]
Thanks @warunicorn19 , @debo19 for the help, looking forward to contributing more.

**Pull request merged**
