### PR TITLE
Fix 'How it Works See It in Action' Section

### LINKED ISSUE #4882: [Screenshots] Crossplane under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/crossplane) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Crossplane](https://layer5.io/cloud-native-management/meshery/integrations/crossplane) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by coder12git**
**Description**

This PR related to #4882

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 809ef210e148d01c982acc1f33316196316a75f6 at: https://650f3aadcb64f65eedb9faf9--layer5.netlify.app

**Comment by coder12git** [comment]
Hey @saurabh100ni  as I am new to Layer, that's why I was confused about what screenshots/videos need to be added, that's why I have added few of them that feels right to me. Please let me know if I need to do any changes.

**Comment by saurabh100ni** [comment]
@Rajdip019 can you review? 👀

**Comment by Rajdip019** [comment]
Screenshot 2023-09-24 at 10 56 19 AM

There is a little alignment issue for the preview screens on the right. It would be better if we align it it make it in the middle horizontally. @coder12git

**Comment by coder12git** [comment]
> Screenshot 2023-09-24 at 10 56 19 AM
> There is a little alignment issue for the preview screens on the right. It would be better if we align it it make it in the middle horizontally. @coder12git

Ok, I will do that, but the screenshots/videos that I have added, is it fine?

**Comment by Rajdip019** [comment]
Yes about that -

- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

**Comment by coder12git** [comment]
> Yes about that -
> 
> * Add both Dark Mode and Light Mode screenshots.
> * The screenshot should not be a snippet, take the full screenshot of your browser.
> * Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

Ok, so I have done all changes, also I didn't get any screenshot for crossplane integrations.

**Comment by saurabh100ni** [comment]
let's discuss that too on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Comment by coder12git** [comment]
> let's discuss that too on today's website meeting, please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

Done!

**Comment by coder12git** [comment]
> > let's discuss that too on today's website meeting, please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk
> 
> Done!
Hey @saurabh100ni I was wondering, when I will get demo video which will tell about crossplane integration, as discussed in the last meet.

**Comment by saurabh100ni** [comment]
@sudhanshutech //

**Comment by coder12git** [comment]
> @sudhanshutech //

Any update on this?

**Comment by l5io** [comment]
🚀 Preview for commit 9afa43663668046a62bbbc8967280bdbf7c6d74f at: https://6519b89d08627f7840672322--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c25f4cd73603b3958e22359241adc22d77e69965 at: https://6548f743bd633e0a6475101c--layer5.netlify.app

**Pull request merged**
