### PR TITLE
changes for overflowing text

### LINKED ISSUE #1961: Overflowing Text
**Description**
Overflowing text

**Screenshots**

https://user-images.githubusercontent.com/59086855/124177243-9487a300-dacd-11eb-8305-8e12b333aae5.mov

**Enviroment:**
- Host OS: OSX
- Browser: Google Chrome

---

**To Reproduce**
1. Go to 'https://layer5.io/careers/internships/'
2. Hover on "Software Engineer Internship" card.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by kaushambisharma**
Signed-off-by: kaushambisharma <sharma.kaushambi@gmail.com>

**Description**
changed the height of card.
This PR fixes #1961 

**Notes for Reviewers**
**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kaushambisharma** [comment]
@Ayush-Khandelwal-007 please review.

**Comment by l5io** [comment]
🚀 Preview for commit 86238c2eaaa290798c07d909f1e3beac2a65cc2d at: https://60e1c7c526405eefaa9a2cd2--layer5ng.netlify.app

**Comment by Ayush-Khandelwal-007** [comment]
https://user-images.githubusercontent.com/59086855/124390194-13682000-dd08-11eb-8169-f772f3049027.mov

The Effect of the cards appearing from the side is hindered. Please look into it.

**Comment by leecalcote** [comment]
It my be the slow speed of the preview deploy site, but when I hover on the card, I see the text rearrange, but do not see the "5" cards appear. I do see the "5" cards disappear on mouse out.

https://user-images.githubusercontent.com/7570704/124601197-2cb6bc80-de2d-11eb-99b7-0c76e6ac4135.mov

**Comment by l5io** [comment]
🚀 Preview for commit 950906dd71b287e681564fddc5f6ee9d054b1a1f at: https://60e4a3c1b003440e55b904e6--layer5ng.netlify.app

**Comment by kaushambisharma** [comment]
@Ayush-Khandelwal-007 @leecalcote please review the changes, files do unfortunately contain unnecessary spaces, will get rid of them if this looks fine, plus, do you think the increase in the height of the blocks on hover could be more smooth?

**Review by Ayush-Khandelwal-007 — APPROVED** [review]
Looks good to me!

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
The reason the cards had a fixed height because
1. The height of all the cards is not the same now.
2. When you hover on the card, at the center its height increases abruptly.

Please fix that.

**Comment by leecalcote** [comment]
You're _this_ close to the finish line, @kaushambisharma 😄

**Comment by l5io** [comment]
🚀 Preview for commit 3f4b273f9d03f6f9dcf1e7b69840d60a554e50c5 at: https://60f02cf6d6bb442d7fb27c91--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a5ebedfc95529f643c6f56bcbaf2336e546ce0a0 at: https://60f03e9965dc695063b1a5df--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 57cce7b5edf72f77cd28c8119431043b54086a43 at: https://60f1623745ca2ffa622e3099--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Changes made. Ready for another review @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
It looks good, but I am not sure if makes the whole content a lot "bouncy" considering the whole section below it also shifts down on hovering.

**Comment by Nikhil-Ladha** [comment]
@leecalcote any suggestion regarding the above comment?

**Comment by leecalcote** [comment]
@Nikhil-Ladha I see what you're saying now. It's not a desirable effect. If there's an alternative approach that avoids this behavior, that would be nice. 

Ultimately, it's not the end of the world if we don't figure something else out, but its worth a try.

**Comment by sudo-NithishKarthik** [comment]
@kaushambisharma , any updates here ?

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
