### PR TITLE
Enhance Value Prop of Writing Program

### PR DESCRIPTION
**Pull request by deepeshaburse**
Signed-off-by: Deepesha Burse <87636253+deepeshaburse@users.noreply.github.com>

**Description**

Enhance Value Prop of Writing Program

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6bc5a8dcd23046d939e376fb71a2388753f4b968 at: https://63c8300fe956d10334e0c8c8--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM 🥇

**Comment by UtkarshMishra12** [comment]
@leecalcote Can it be merged?

**Review by leecalcote — CHANGES_REQUESTED** [review]
The statement about byline is inaccurate and doesn't segregate resource article from blog post in this regard.

Use the "high-quality" is a little redundant between the two sentences.

**Comment by leecalcote** [comment]
Not what was asked for.

**Pull request closed without merging**
