### PR TITLE
[service-mesh-patterns-table] fixed sortBy bug

### PR DESCRIPTION
**Pull request by Oghene-kevwe**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Oghene-kevwe** [comment]
The build is successful on my machine, I don't know why isn't working here

**Comment by GaganpreetKaurKalsi** [comment]
> The build is successful on my machine, I don't know why isn't working here

Need not worry @Oghene-kevwe, we are facing some issue leading to failing build.... Will get it rectified soon.

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Works perfectly, thanks @Oghene-kevwe 👍

**Comment by leecalcote** [comment]
Awesome. 🙂

**Pull request merged**
