### PR TITLE
[commonForm.style.js] text color fix in dropdown

### LINKED ISSUE #5242: "Select your role" dropdown not visible in dark mode
### Description

LINK: https://layer5.io/cloud-native-management/meshmap

Enable dark mode and go to the form in Signup for
MeshMap Beta

Here dropdown options are not visible.

They only become visbible when we hover over each item
Note: It works fine on macos

### Expected Behavior

Here dropdown should be visible

### Screenshots

image

### Environment:
- Host OS: Windows 10 pro
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by prabhjeevnijjar**
**Description**

This PR fixes #5242 #5232

**Notes for Reviewers**
`The behaviour of styling <select > tag is not linear across browsers in different OS. 
This is also mentioned in the MDN docs.

### Mac OS
- Background color and text color is picked by default based on browser theme, This works perfectly

### Windows
- Shows white background all the time independent of the browser theme
- But text color can be changed by CSS,
-  We were using -> props.theme.primaryColor [It changes the text color to white in dark theme, Which was the exact issue]
- I changed it to -> props.theme.textColor [Now it stays in a shade of grey]`

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8c1d978c3ca33690b3e2bf936dfeccf5a0737247 at: https://658fb6c2541fd53898004ee5--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Hey @prabhjeevnijjar,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Currently:

Screenshot 2024-01-14 at 1 07 44 PM


With this PR's change:


Screenshot 2024-01-14 at 1 07 48 PM

**Comment by leecalcote** [comment]
@vishalvivekm @iArchitSharma @ritiksaxena124 please prioritize this fix.

**Comment by iArchitSharma** [comment]
Fixed
image
image

**Comment by l5io** [comment]
🚀 Preview for commit f943adf84e85cb13e54c2ec989a1ef31a0fb7064 at: https://65a45572e7ac41c3f4c32571--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @prabhjeevnijjar and @iArchitSharma

**Pull request merged**
