### PR TITLE
Add Member

### LINKED ISSUE #4556: [Community] Member Profile: Harsh Dobariya
**Current Behavior**

@HarshDobariya79 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @HarshDobariya79  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @HarshDobariya79
- Twitter: HarshDobariya79
- LinkedIn: harshdobariya79
- Meshery Cloud: 27ba20ed-4012-490e-ab2e-a937173283c4
- Link to profile picture: https://drive.google.com/file/d/1Mru2IfCGvXQ0sMV2u0XTN7DGQVMWFRK_/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by devarsh10**
**Description**

This PR fixes #4556

**Notes for Reviewers**
Added [@HarshDobariya79](https://github.com/HarshDobariya79) as a member.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits from visual studio code.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b1c211640a7b3fff8108fbb78fede83c31fa6773 at: https://64b4b7373071ba260f8786cd--layer5.netlify.app

**Review by HarshDobariya79 — COMMENTED** [review]
Thank you @devarsh10 for this PR. The image is currently cropped from the sides due to its dimensions. Maybe replacing it with a square image will fix it.

picofme

**Comment by devarsh10** [comment]
Okay. I will update it.

**Comment by l5io** [comment]
🚀 Preview for commit 54f15c99369952453db4bb154d350eab8b6ac90c at: https://64b4dd27c6485437ad359941--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@devarsh10 Please sign off on the commits and let's merge this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 106ed46a9fb27249993aeba469330eab9e096b3a at: https://64b52012985a640d46c80e0f--layer5.netlify.app

**Comment by devarsh10** [comment]
Hey @Shivam-AfA, I have made some blunders in this PR. And I created a new branch. May I raise a new PR so that it can be easily merged?

Regards.

**Comment by leecalcote** [comment]
> Hey @Shivam-AfA, I have made some blunders in this PR. And I created a new branch. May I raise a new PR so that it can be easily merged?
> 
> Regards.

Most certainly, @devarsh10. I'll close this one, so that you can open a new one.

**Pull request closed without merging**
