### PR TITLE
Added oraganizations logo in ServiceMeshCon EU, 2022 event

### LINKED ISSUE #2759: [Event] Update ServiceMeshCon EU 2022 talk description to include participating organization logos
**Current Behavior**
Speakers from multiple organizations are presenting MeshMark at ServiceMeshCon EU 22. Their respective organizations are not visually represented on event description.

**Desired Behavior**
Please update the event https://layer5.io/community/events/servicemeshcon-eu-2022 to include a "Participating Organizations" section with a small Intel logo and small Layer5 logo.

**Screenshots / Mockups**

Screen Shot 2022-05-03 at 5 55 11 PM

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added the participating organization's logo to the event description.

This PR fixes #2759 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Also, added `PARALLEL_SOURCING` into the gatsby-config. Hopefully, that should speed up the build process a bit.

**Comment by Nikhil-Ladha** [comment]
> Also, added `PARALLEL_SOURCING` into the gatsby-config. Hopefully, that should speed up the build process a bit. Related to #2773

I have undo that change. And, will send out a different PR with another flag that we could use for the performance part.

**Comment by l5io** [comment]
🚀 Preview for commit 957e5a3370542f22b1623b3912beeb0267fb7ca0 at: https://627b61efb6efcf3b682e99bd--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
Looking real good.

**Comment by Nikhil-Ladha** [comment]
> > 
> 
> The new flags coming out around caching and parallel processing sound promising. I don’t know if the two that were using for cashing today or causing me to run “clean “more often or not.

Yes, that is correct. The flag `PRESERVE_CACHE` seems to be not allowing updates to the md(x) files without a cache clear or a restart, which if I remember correctly wasn't the case earlier.

**Comment by Nikhil-Ladha** [comment]
But, I am not 100% sure, considering that I did try to disable the flag and try out the build, but it failed again.
Seems like more of an update in Gatsby itself.
I think we can plan to migrate to Gatsby4, and leverage some benefits from it.

**Pull request merged**
