### PR TITLE
fix: case study banner link

### LINKED ISSUE #4545: Link for the case study banner is broken
### Description
The link for the case study banner on the home page is broken, as it is still pointing to https://layer5.io/resources/cloud-native/hpes-adoption-of-meshery-and-meshmap

### Expected Behavior
It should point to https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap

### Screenshots

https://github.com/layer5io/layer5/assets/72399705/32bcb86c-36e0-459f-b467-d386d6866894

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
**Description**

This PR fixes #4545 

**Notes for Reviewers**
I have fixed the link to the case study banner.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 
@hirentimbadiya  please review the PR.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8751ab939c45ccfb08ad188f6a93cc401df8c533 at: https://64b234350268124e8f39e897--layer5.netlify.app

**Review by DarrenDsouza7273 — APPROVED** [review]
LGTM @vrinda-mahajan

**Review by hirentimbadiya — APPROVED** [review]
Looks Good to Merge, thanks for your contribution @vrinda-mahajan ✨

**Review by leecalcote — APPROVED** [review]
Thank you, @hirentimbadiya, @vrinda-mahajan

**Pull request merged**
