### PR TITLE
Correcting css style for layer5-collaboration-map.svg

### LINKED ISSUE #5046: [About] Change collaboration map SVG image to brand colors
### Current Behavior
The collaboration map on the about page is using blue and red coloring. https://layer5.io/company/about

Screenshot 2023-10-16 at 8 41 41 PM

### Desired Situation
Ideally, it is using colors from our brand color scheme --> https://layer5.io/brand

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Harsha-10**
**Description**

This PR fixes #5046 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 208b24ddc8404583a8f33794d8395f665fdba802 at: https://652e87da53e99113cddd80dd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 82fdbf3e69e75782cc8eee6f690a16a7396da157 at: https://652f779520001765e235bbfd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 33397d978bd064e6cffa071edaf2bfbac2e05741 at: https://652f811d6676866950e14719--layer5.netlify.app

**Comment by Harsha-10** [comment]
could you please review this PR @abhijeetgauravm

**Comment by Harsha-10** [comment]
Can i get anyone to review this PR.....

**Comment by Mohith234** [comment]
@Harsha-10 The map looks good in the dark mode. But in light mode, we are unable to see it. 

Can we use a dark color to fill the map in light mode? Just like the text that changes to black when in light mode.

**Comment by Harsha-10** [comment]
How about changing the stroke colour to dark jungle green as it's mentioned in the colour brand kit?

**Comment by Harsha-10** [comment]
image

image

This looks fine?

**Comment by Harsha-10** [comment]
image

image

Is it ok now? @Mohith234

**Comment by Mohith234** [comment]
Exactly 💯 Looks good now. Please do make these changes @Harsha-10

**Comment by Harsha-10** [comment]
Yeah, thanks for reviewing @Mohith234

**Comment by l5io** [comment]
🚀 Preview for commit 02ee85360474cafd66fc166e0e7b8177d1b1886a at: https://65315aaf56c43340bf6e681d--layer5.netlify.app

**Comment by Harsha-10** [comment]
Made required changes @Mohith234

**Review by abhijeetgauravm — APPROVED** [review]
Looks good to me @Harsha-10. Thanks for the contribution!

**Comment by abhijeetgauravm** [comment]
Hey @Harsha-10 Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Harsha-10** [comment]
Can this pr be merged as lee said it could be accepted in yesterday's meeting @abhijeetgauravm ?

**Comment by abhijeetgauravm** [comment]
> Can this pr be merged as lee said it could be accepted in yesterday's meeting @abhijeetgauravm ?

// @vishalvivekm @Mohith234 @sudhanshutech @ritiksaxena124

**Review by ritiksaxena124 — APPROVED** [review]

**Pull request merged**
