### PR TITLE
corrected grammatical mistakes

### LINKED ISSUE #3583: Fix grammatical errors
**Current Behavior**

**Link - https://layer5.io/cloud-native-management/meshery/operating-service-meshes**

image
image

**Desired Situation**

The highlighted text has some grammatical/sentence forming errors. Fix them.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Adi-ty**
Signed-off-by: Aditya <adityasinghboss1234@gmail.com>

Hey, I have made changes in the sentences to make them grammatically correct if you suggest any other changes in sentences you can tell me.

This PR fixes #3583 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@Chadha93 @leecalcote Please approve the workflow.

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks great 👍 Thanks @Adi-ty!

**Comment by Adi-ty** [comment]
Waiting for workflow approval

**Comment by leecalcote** [comment]
Workflow run approved. Deployment preview coming soon...

**Comment by leecalcote** [comment]
Looking over the changes now, though, a preview isn't needed.

**Review by leecalcote — APPROVED** [review]
Thank you, @Adi-ty 👍 and @GaganpreetKaurKalsi 👍

**Pull request merged**
