### PR TITLE
In footer "Subscribe to out newsletter" doesn't position well at some screen size #5148

### PR DESCRIPTION
**Pull request by Nasirahamad88**
**Description**
In footer "Subscribe to out newsletter" doesn't position well at some screen size #5148
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e90a39c33332bfa4e077d4eef6cb265f9dad4192 at: https://6561cc62af5aa3174498dc90--layer5.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@Nasirahamad88, please don't raise any PR if an issue is not assigned to you.

**Comment by abhijeetgauravm** [comment]
Hey @Nasirahamad88  We really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first. Please do take the time to read the Contributing guidelines.

**Review by abhijeetgauravm — COMMENTED** [review]
image
image
image
image


The inconsistency is still visible at different screen sizes(Edge/Chrome) browser.

**Comment by leecalcote** [comment]
Thanks for jumping in, @Nasirahamad88

**Comment by abhijeetgauravm** [comment]
@Nasirahamad88 any updates here?

**Comment by abhijeetgauravm** [comment]
Since there no updates from @Nasirahamad88 . Closing the PR!

**Pull request closed without merging**
