### PR TITLE
Resolves #65: added table sorting adjusted font colors on landscape page

### LINKED ISSUE #65: Enhance landscape table usability
Enhance landscape table usability with:

1. sorting by descending alphabetical order on the leftmost column by default)
 - This would be the ability for a user to click on the column name and have the table sorted by that column.
-  The ability to click to switch between asc/desc
2. alternating colors in rows

### PR DESCRIPTION
**Pull request by Silvyre**
Resolves #65:
- By default, all three tables on the [Landscape Page](https://layer5.io/landscape/) are sorted by descending alphabetical order on their leftmost column.
- Clicking on a column name on one of the aforementioned tables causes the table to be sorted by that column (toggling between ascending and descending order).
- The orange font color styling for links on the Landscape Page was removed, leaving the inherited blue font color.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Silvyre strikes again! :)

**Comment by Silvyre** [comment]
Sure, I can do that!

**Comment by leecalcote** [comment]
Oh, @Silvyre, a note regarding the first section of the landscape that contains four categories of technologies - the list of projects within those categories is alphabetical when viewed in a mobile-size browser, but are listed left-to-right when viewed in a desktop browser. The lists in these categories are easier to read when list s alhabeticwlly from top-down. We may want to open a separate issue to ensure they areisted top-down, in each column when in a wide browser

**Comment by Silvyre** [comment]
Agreed, this behaviour should be adjusted, and via a new issue.

**Pull request merged**
