### PR TITLE
fixed: typo experience , subscription , meaningfully

### LINKED ISSUE #4654: typo in community's blog and community's page
### Description

There is some typo in community's blog [here](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma)  (experience) and also   [here](https://layer5.io/blog/meshery/changing-meshery-release-channels) (subscription)  and community's page [here](https://layer5.io/community) (meaningfully)

### Screenshots

image

image

image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
**Description**

This PR fixes #4654 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d6c6c339cf58612d06d496390eff944e5fcd24ac at: https://64c615fb9e67f35d0b7adc11--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Looks Good to Merge @abhijeetgauravm 👍🏻

**Comment by Ghat0tkach** [comment]
Hii @abhijeetgauravm 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Make sure to attend tommorow's website call for review

**Comment by abhijeetgauravm** [comment]
@Ghat0tkach ok !

**Comment by l5io** [comment]
🚀 Preview for commit bd860dfd6219ec0db2cf3b3bf942c0607c7d936a at: https://64c81482c2aacd032fc5add7--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bd860dfd6219ec0db2cf3b3bf942c0607c7d936a at: https://64c814ce9e1ffe044b346627--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Looking good. Thanks, @abhijeetgauravm 👍

**Comment by leecalcote** [comment]
(and @hirentimbadiya)

**Pull request merged**
