### PR TITLE
added Helm v3/v2 scripts for Kubernetes user

### LINKED ISSUE #965: [DOC]The Helm v2 scripts in a wrong way and need to be fix
**Current State:**

Going to the https://layer5.io/meshery#getting-started and you can see that for kubernetes user the deployment way is deploy the `yaml`, but we need to add the other ways that we already have been haved 

**Desired State:**

Reference link:

https://meshery.layer5.io/docs/installation/platforms/kubernetes

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
Added the Helm v2/v3 scripts for the Kubernetes user at [layer5.io](https://layer5.io/meshery#getting-started) site.
This PR fixes #965 

screenshot: 
chrome_jycUKmZDWX

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — APPROVED** [review]
approve

**Comment by Aisuko** [comment]
@leecalcote May you have a look if there any change we need?

**Comment by Aisuko** [comment]
@vinayaksh42 Thanks for your contribution and welcome to our community slack channel to have a chat

**Comment by vinayaksh42** [comment]
@leecalcote can you review this pr and suggest changes if any?

**Pull request merged**
