### PR TITLE
community page maintainer section

### PR DESCRIPTION
**Pull request by last-saiyan**
**Description**
added the maintainer section in community page

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @last-saiyan. 👍 

Take a moment, if you will, to edit this PR's description to include the issue that it fixes, if you would. In this way, reviewers will have context for the changes in the PR and the associated issue will auto close when the PR is merged.

**Comment by Jashpatel1** [comment]
@last-saiyan Is the PR complete?

**Comment by leecalcote** [comment]
@last-saiyan, we'll be going live with the new version of the layer5.io site this week. Thank you for contributing here. Will you have time to wrap up this PR?

**Comment by leecalcote** [comment]
Hi @last-saiyan, thank you for this PR. Not having heard from you and with this new site soon-to-be published, we are clearing out stale issues and PRs. We'll go ahead and close this one out, but please don't let that discourage you from continuing to engage.

**Pull request closed without merging**
