### PR TITLE
corrected partners section

### LINKED ISSUE #2311: Overflow of logos in Collaboration section
**Description**
Some of the logos are overflowing on the website. They should be given proper width so that every logo looks well.

**Current Behavior**
image

**Expected Behavior**
image

**Environment:**
- Host OS: Windows
- Browser: Google Chrome

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by akshatnema**
Signed-off-by: AKSHATNEMA <20bcs022@iiitdmj.ac.in>**Description**

This PR fixes #2311 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
## Preview of the Changes
**Desktop View** 
image

**Mobile View**
image

## Description
This section is now fully responsive and can be viewed on any mobile screen without any overflow.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 65df2a042452af427089f2ee60533e854e99ded8 at: https://617ffe91f0301bb15e4707e0--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@leecalcote are we good to go forward with this design?

**Comment by Mr-DG-Wick** [comment]
139687418-94fbade2-b189-4ffd-8b51-9913b35a0446

can you reduce the size of  `engaging and collaborating with` and share a preview of how it looks?

**Review by shubham-tyagi — CHANGES_REQUESTED** [review]
Hey @akshatnema, for all the devices the code does work, great stuff. Just for the laptop width 1440px there is a slight adjustment required.

**Comment by leecalcote** [comment]
We can't skew the logos. Their aspect ratio must be maintained. Take care with the UEM logo.

**Comment by leecalcote** [comment]
Having said that, now I see that we are already skewing that logo in the production site. 🙁 

For the most part, the intention was for these logos to spill off the page and not be considered the fullset of engagements. For example, we also have engineers from VMware engaged and contributing, but don't have the VMware logo on the site.

**Review by leecalcote — APPROVED** [review]
Without a carousel for these logos, site visitors (like @akshatnema) might assume that the page isn't responsive (might not understand that the cutoff of logos is intentional). Without a carousel, what @akshatnema has implemented is probably for the best. Let's go forward with this proposal. Thank you, @akshatnema 👍

**Pull request merged**
