### PR TITLE
Implemented table type of filtering

### LINKED ISSUE #1184: [NG] Improve the Events Page on layer5-ng
**Current Behavior**
Currently, the [events page](https://layer5ng.netlify.app/community/events) on layer5-ng has a single list of events.

**Desired Behavior**
Divide the events into categories and show them into tabs layout. 
Add the "Attend an Event" section to the page.
Any improvements in design/layout will be heartily welcomed.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes #1184 

**Notes for Reviewers**
- [x] Implemented the filtering in the table format that is used in the [hashicorpSite](https://www.hashicorp.com/events?type=all) and added all the `meetups` that are occurred in 2020 till now.

- [x] Moved the `meetups` from `collection/meetups` to `collection/events` and added a `type: event` as a `frontmatter` to each of the `events`, `workshops` & `meetups`

- [x] Added `Docker Austin` and `Cloud Native Austin` tags to meetups.

- [x] Added `Upcoming events/workshop` to the top of the table.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by kishore007k** [comment]
I still need to implement the pagination to the `events page` for the `all` tab since it's showing only the 12 recent ones from all the topics.

**Review by Jashpatel1 — CHANGES_REQUESTED** [review]
Great work here @kishore007k 
Just a couple of things:
1) The tabs have some responsiveness issues on my device. Can you please check?
2) Can you make the entire event cards clickable?

**Comment by kishore007k** [comment]
> Great work here @kishore007k
> Just a couple of things:
> 
> 1. The tabs have some responsiveness issues on my device. Can you please check?
> 2. Can you make the entire event cards clickable?

Sure

**Comment by leecalcote** [comment]
@kishore007k when you make the cards clickable, will you also work toward a uniform shadow all the way around the card? These changes back be ported back to the core component for cards, since all cards should be clickable anywhere on the card and those there are using shadow should use it uniformly on all sides of the card.

**Comment by kishore007k** [comment]
> @kishore007k when you make the cards clickable, will you also work toward a uniform shadow all the way around the card? These changes back be ported back to the core component for cards, since all cards should be clickable anywhere on the card and those there are using shadow should use it uniformly on all sides of the card.
Yes Sir!

**Comment by leecalcote** [comment]
This is looking really good. We might eventually want to reduce the depth on hover. I'm not sure, though.

Two of the listed meetups are the Meetups themselves: Docker Austin and Cloud Native Austin. @kishore007k, will you remove these two and instead create an attribute on each meetup the affiliates the meetup event with one of these two? Then, we can show which Meetup (Docker Austin or Cloud Native Austin or others in the future) each event is affiliated with.

**Comment by kishore007k** [comment]
> This is looking really good. We might eventually want to reduce the depth on hover. I'm not sure, though.
> 
> Two of the listed meetups are the Meetups themselves: Docker Austin and Cloud Native Austin. @kishore007k, will you remove these two and instead create an attribute on each meetup the affiliates the meetup event with one of these two? Then, we can show which Meetup (Docker Austin or Cloud Native Austin or others in the future) each event is affiliated with.

Thank You, Sir.
I forgot to remove those two from the meetups.
And about creating the attribute for the meetups, So each meetup in the `events page` should show the `attributes` as that of the `tag` or `category` in the `blog page` is that about right?

**Comment by kishore007k** [comment]
I added this thumbnail to this meetup.
And the meshery Icon to the other meetup below.
Is this ok or should I remove it?

InkedCapture2_LI

**Comment by leecalcote** [comment]
@kishore007k the Meshery image will do the trick. Here's one for the DockerCon Live event - https://twitter.com/lcalcote/status/1265749153822408706

**Comment by leecalcote** [comment]
Looks like a conflict has arisen, @kishore007k. Should be quick to address.

**Comment by kishore007k** [comment]
> Looks like a conflict has arisen, @kishore007k. Should be quick to address.

Yes, Sir, I will try to fix it in the upcoming PR.

**Comment by Jashpatel1** [comment]
All looks good, just can you revert the changes in package-lock.json. This could solve the conflicts as well.

**Comment by kishore007k** [comment]
> All looks good, just can you revert the changes in package-lock.json. This could solve the conflicts as well.

Will deleting the `package-lock.json` file resolves the conflict.

**Comment by leecalcote** [comment]
@kishore007k here is what I get when I checkout this PR, run `make setup-libs` and `make site`:

```
 ERROR 

Cannot read property 'add' of undefined



  TypeError: Cannot read property 'add' of undefined
  
  - pending-page-data-writes.ts:16 pendingPageDataWritesReducer
    [layer5]/[gatsby]/src/redux/reducers/pending-page-data-writes.ts:16:27
  
  - redux.js:465 combination
    [layer5]/[redux]/lib/redux.js:465:29
  
  - redux.js:219 next
    [layer5]/[redux]/lib/redux.js:219:22
  
  - index.ts:72 
    [layer5]/[gatsby]/src/redux/index.ts:72:66
  
  - index.js:14 Object.dispatch
    [layer5]/[redux-thunk]/lib/index.js:14:16
  
  - start-webpack-server.ts:143 forEach
    [layer5]/[gatsby]/src/services/start-webpack-server.ts:143:21
  
  - Map.forEach
  
  - start-webpack-server.ts:135 
    [layer5]/[gatsby]/src/services/start-webpack-server.ts:135:43
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [layer5]/[tapable]/lib/Hook.js:154:20
  
  - Watching.js:98 Watching._done
    [layer5]/[webpack]/lib/Watching.js:98:28
  
  - Watching.js:73 
    [layer5]/[webpack]/lib/Watching.js:73:19
  
  - Compiler.js:499 Compiler.emitRecords
    [layer5]/[webpack]/lib/Compiler.js:499:39
  
  - Watching.js:54 
    [layer5]/[webpack]/lib/Watching.js:54:20
  
  - Compiler.js:485 
    [layer5]/[webpack]/lib/Compiler.js:485:14
  
  

npm ERR! code 1
npm ERR! path /Users/lee/code/layer5
npm ERR! command failed
npm ERR! command sh -c env-cmd -f .env.development gatsby develop

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lee/.npm/_logs/2020-12-08T02_41_19_346Z-debug.log
npm ERR! code 1
npm ERR! path /Users/lee/code/layer5
npm ERR! command failed
npm ERR! command sh -c npm run develop

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lee/.npm/_logs/2020-12-08T02_41_19_364Z-debug.log
make: *** [site] Error 1
```

**Comment by leecalcote** [comment]
@kishore007k, yes, you can try deleting the package-lock.json file, `node_modules`, `public` folders and rebuilding the site.

**Review by Jashpatel1 — APPROVED** [review]
Perfect. Thanks for taking this task. Good work here, @kishore007k

**Pull request merged**
