### PR TITLE
feat: add Qalenas Soft font

### LINKED ISSUE #1206: [NG] Integrate new font
**Current Behavior**

Layer5 uses Open Sans as our official font across all our sites, both for paragraphs as well as headings.

**Desired Situation**

We will now be using **Quanelas Soft** for headings and continue with Open Sans for paragraphs or in situations where Quanelas Soft cannot be loaded. The font is ready to be [installed](https://drive.google.com/drive/u/0/folders/1NfWLitxhb3l8zXz7jdGMEwE-lHim1k0h) on your system. 
This change should be reflected across the Layer5-ng site. 

---
**Contributor Resources**

[Layer5 Brand Guide](https://docs.google.com/presentation/d/12XWzUN3MqCm4jchV4RWgkqikPbgkKeTDhipVufNU2BU/edit#slide=id.g984d490928_2_634)

The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #1206
Also fixes the issue with `package-lock.json` file 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Issue referenced is incorrect.

**Comment by Tanuj22** [comment]
> Issue referenced is incorrect.

Fixed

**Comment by leecalcote** [comment]
I wonder why there's a difference in the look here.
[homepage-3.pdf](https://github.com/layer5io/layer5/files/5624774/homepage-3.pdf)

**Comment by leecalcote** [comment]
Does it have to do with the assigned font-weight?

**Comment by Tanuj22** [comment]
> Does it have to do with the assigned font-weight?

It looks like it's the font-weight. Can you tell me what the font-weight should be?

**Comment by leecalcote** [comment]
@Tanuj22 you betcha. Here we are - https://docs.google.com/presentation/d/12XWzUN3MqCm4jchV4RWgkqikPbgkKeTDhipVufNU2BU/edit#slide=id.gada3cd44ef_0_1 // @kishore007k

**Comment by Tanuj22** [comment]
This doesn't seem to be an issue font-weight as changing it is not causing any effect :thinking:

**Comment by Tanuj22** [comment]
I suggest we merge it PR for now as is it blocking progress for the homepage for @Jashpatel1

**Review by leecalcote — APPROVED** [review]
Merging to unblock

**Pull request merged**
