### PR TITLE
Project-home section removed

### PR DESCRIPTION
**Pull request by iArchitSharma**
**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 84706ee20d5dc5e2d2f9b084ef194ea6a6a6786e at: https://65eb2a1bf899fba890268b9a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4b5258aa93b9854ae2044443af9199760ea3f5ec at: https://65f08e4990c57b184879676d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit de38dcda4d0852eeb0f54af152c1fb0d31c7ae31 at: https://65f45489e62eac097bf56a01--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@iArchitSharma Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit 96438c75adcc99dc5a45d5e9ff66fe3d500d656d at: https://6606821f9a3fbb7d081d4a30--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0da1f844ec815f029c056f320aebe9e31637745b at: https://66068fa79a3fbb89551d4b24--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b846851d090c56049621d3436ab45ed4b717627c at: https://660692fbb604848cda7126d1--layer5.netlify.app

**Pull request merged**
