### PR TITLE
[Landscape] Added nofollow relation attribute for external links

### LINKED ISSUE #2634: [Landscape] External links on the service mesh landscape page should have the `rel="nofollow"` attribute
**Current State:**
The [Service Mesh Landscape](https://layer5.io/landscape) page has a lot of external links that point to the respective service mesh's site/GitHub repo and the site crawler will rank our site based on those links. This may hamper the SEO of our site.

**Desired State:**
All the external links on the site should have the `rel="nofollow` attribute so that the link is avoided by the crawler.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sidd-oo**
Signed-off-by: sidd-oo <sahoosiddharth3@gmail.com>

**Description**
Added `nofollow` relation attribute for external links for [Service Mesh Lanscape](https://layer5.io/service-mesh-landscape) page so that the site crawler stops ranking Layer5 site based on those external links. This will prevent hampering the SEO of the Layer5 site.

This PR fixes #2634

**Notes for Reviewers**
There is only one external link present for the above-mentioned page. But in the description of the issue, it is written a lot of external links are there. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sidd-oo** [comment]
Kindly review this PR and suggest if there is a need for any changes @Nikhil-Ladha 
Thank you.

**Comment by l5io** [comment]
🚀 Preview for commit f0fdcb43451503cd004e07808d479503129538a1 at: https://6224b47f165faaebe6e021ab--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
> **Notes for Reviewers** There is only one external link present for the above-mentioned page. But in the description of the issue, it is written a lot of external links are there.

Bcoz, that meant all the components on the page :)
And, not just the Button link. In fact, for the `Button` component you don't even need to add the `rel` attribute because the `external` prop does that in the Component code.

**Comment by sidd-oo** [comment]
> > **Notes for Reviewers** There is only one external link present for the above-mentioned page. But in the description of the issue, it is written a lot of external links are there.
> 
> Bcoz, that meant all the components on the page :) And, not just the Button link. In fact, for the `Button` component you don't even need to add the `rel` attribute because the `external` prop does that in the Component code.

Thank you for explaining. I made some new changes keeping the suggestions in mind, kindly review them @Nikhil-Ladha

**Comment by l5io** [comment]
🚀 Preview for commit 85b5cd898550b2ba70a65be3a62cda9314b55069 at: https://6225ac3e33f9112553bbc330--layer5ng.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
There are still links on different tabs of the table which don't have the `rel="nofollow"` attribute. Please check and update them as well, i.e `functional`, `non-functional`, `tools`

**Comment by warunicorn19** [comment]
@sidd-oo any updates on this PR?

**Comment by leecalcote** [comment]
I went ahead and tied this off.

**Comment by leecalcote** [comment]
Thank you for following up on it, @Abhijay007, @warunicorn19, and @Nikhil-Ladha

**Pull request merged**
