### PR TITLE
Newcomer

### PR DESCRIPTION
**Pull request by vinayaksh42**
**Description**
Web-based newcomers form for contributors as well as users. This form has different pathways which make it easy to handle the community onboarding process.

The form can be found at - **/community/webform**

Things remaining to be added in order to make this form fully functional
- backend connection with integromat
- storing all the fields data in the frontend 
- CSS fix for the progress bar/steps

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit febd2c4deeb825d2c296b3bea1efb9efe8d4f915 at: https://608009dd754c84f5e498b087--layer5ng.netlify.app

**Review by Nikhil-Ladha — COMMENTED** [review]
Looking good. Few things apart from the one already mentioned in the description:
 - The radius of the input box could be reduced or completely removed. Not sure.
 - Same applies to the dropdown.
 - The step's bar design could be improved, @austinogiza if you mind taking a look at it.
 - Optional: A backdrop image can be used for the form, something related to onboarding. A customer SVG. Thoughts @leecalcote @austinogiza ?

**Comment by vinayaksh42** [comment]
> Looking good. Few things apart from the one already mentioned in the description:
> 
> * The radius of the input box could be reduced or completely removed. Not sure.
> * Same applies to the dropdown.
> * The step's bar design could be improved, @austinogiza if you mind taking a look at it.
> * Optional: A backdrop image can be used for the form, something related to onboarding. A customer SVG. Thoughts @leecalcote @austinogiza ?

@Nikhil-Ladha we might have to make our checkbox and drop-down component cause it is rendering differently in safari and firefox. The step bar design in the Figma mockup is a bit different than what I implemented. Basically, I have got the structure ready for the whole webform so that this can be used as a base for all the other changes. 

As this page is not yet linked with the main website, we should merge this so that more contributors can get involved.

**Comment by Nikhil-Ladha** [comment]
> > Looking good. Few things apart from the one already mentioned in the description:
> > 
> > * The radius of the input box could be reduced or completely removed. Not sure.
> > * Same applies to the dropdown.
> > * The step's bar design could be improved, @austinogiza if you mind taking a look at it.
> > * Optional: A backdrop image can be used for the form, something related to onboarding. A customer SVG. Thoughts @leecalcote @austinogiza ?
> 
> @Nikhil-Ladha we might have to make our checkbox and drop-down component cause it is rendering differently in safari and firefox. The step bar design in the Figma mockup is a bit different than what I implemented. Basically, I have got the structure ready for the whole webform so that this can be used as a base for all the other changes.
> 
> As this page is not yet linked with the main website, we should merge this so that more contributors can get involved.

I think we don't need to hurry with it, i.e, we can complete this webform and then merge it. As, we have the google form link in place, which is getting used by new contributors. Though, a button is yet to be added on the community and newcomers page which links to that form.

**Comment by Jashpatel1** [comment]
> I think we don't need to hurry with it, i.e, we can complete this webform and then merge it. As, we have the google form link in place, which is getting used by new contributors. Though, a button is yet to be added on the community and newcomers page which links to that form.

Agreed.

**Comment by leecalcote** [comment]
There are a few items that @Lezette might be picking up here in a separate PR, including required fields and their behavior on error; how they inform the user of what input is expected (before the field is filled in).

**Comment by Nikhil-Ladha** [comment]
> There are a few items that @Lezette might be picking up here in a separate PR, including required fields and their behavior on error; how they inform the user of what input is expected (before the field is filled in).

So, @leecalcote do you suggest we should take this PR in and then let others make the changes on top of it?

**Comment by leecalcote** [comment]
@Nikhil-Ladha, considering that @Lezette will take the baton from here and that this page is yet to be linked to, yes, I think we might accept this first draft now. What do you say, @Lezette?

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Lezette** [comment]
I agree @leecalcote. I'll take it from here

**Pull request merged**
