### PR TITLE
[NG] Projects_Megamenu

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

**Notes for Reviewers**
If a project is to have other than "/projects/project-slug", it needs to have an attribute "link" in the front-matter.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
I think it is better to hardcode these in the mega menu. As creating src/collections/projects/meshery/index.mdx is creating an URL `/projects/meshery` which is not something we want

**Comment by vineethvanga18** [comment]
In future, do all the projects have other '/projects/....' . If this is the case it is better to not create pages for projects. If we have a mix of '/projects/...' and separate pages, it would be difficult to hardcode everytime

**Comment by vineethvanga18** [comment]
Also for community menu, all the posts are external links in collections. What should be done?

**Comment by leecalcote** [comment]
For now, in order to go-live, let's go with hardcoding both.

**Comment by Tanuj22** [comment]
> In future, do all the projects have other than '/projects/....' . If this is the case it is better to not create pages for projects. If we have a mix of '/projects/...' and separate pages, it would be difficult to hardcode everytime

yes. Can you do this? . Because `projects/meshery` is supposed to redirect and we do not want a separate page for it

**Comment by leecalcote** [comment]
⚠️  Assigning high priority label. This is a go-live blocker.

**Comment by leecalcote** [comment]
@vineethvanga18 will you consider advancing this PR instead - https://github.com/layer5io/layer5/pull/1489? This PR is derived from yours here.

**Comment by vineethvanga18** [comment]
Sure, @leecalcote

**Comment by Jashpatel1** [comment]
This can be closed. @vineethvanga18

**Comment by vineethvanga18** [comment]
Yes, @Jashpatel1. Doing it.

**Pull request closed without merging**
