### PR TITLE
Added So Special Section

### LINKED ISSUE #1425: Implementation of the Layer5 So Special section on homepage
**Current Behavior**
We currently have no implementation of the Layer5 So Special section on homepage 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

**Implementation**
- use react slick (see xxxx page as an example)

**Screenshots**
Group 1007

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #1425 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
😎

**Comment by chinmaym07** [comment]
What did I do wrong here sir.?

**Comment by leecalcote** [comment]
Nothing. That’s not you. It’s an issue that our workflows are having with Netlify at the moment.

**Comment by leecalcote** [comment]
Thank you, @chinmaym07. As we work to bring forward more items that make Layer5 special, we'll want to create a slightly more dynamic way of loading both pictures, brief descriptions, and a URL where people can read more.

Will you work on refactoring this to include an mdx data source? Let's use the news collection as that data source.

**Comment by chinmaym07** [comment]
Yes sir .. :+1:: grinning:

**Comment by leecalcote** [comment]
hot momma

**Review by leecalcote — APPROVED** [review]
@chinmaym07, let's get this merged and then move onto the effort of combining the sections...

**Pull request merged**
