### PR TITLE
[Blog] Add "Functional Testing with Cypress in Meshery UI" Blog Post

### LINKED ISSUE #1223: [NG] New Post Wanted: Functional Testing with Cypress in Meshery UI
**Current Behavior**
@ramrodo delivered a great presentation on Cypress and considerations for its use.

**Desired Behavior**
A follow up blog post accompanied with slides from [the presentation](url) would be a nice addition.

- Title: _Functional Testing with Cypress in Meshery UI_
- Ideal post content: 
  - What Meshery UI and the Meshery Provider UI are and why end-to-end testing is necessary
  - how Meshery UI and the Meshery CI process uses Cypress
    - anti-fragile test writing practices
  - what we like about Cypress; what we don't like about Cypress
  - one or more of the slides exported and provided for context
  - an invitation and call to action to join @ramrodo in the community and engage in Layer5 projects 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ramrodo**
**Description**

This PR adds a new Blog Post: **"Functional Testing with Cypress in Meshery UI"**

This PR fixes #1223

**Notes for Reviewers**
You can see the Preview fo the Blog Post [here](https://deploy-preview-1278--layer5ng.netlify.app/blog/development/functional-testing-with-cypress-in-meshery-ui)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Looks good to me in terms of preview. @leecalcote can you verify the content as well?

**Review by leecalcote — APPROVED** [review]
This is great, @ramrodo. Good of you to include links to the recording and slides. 👍

**Comment by leecalcote** [comment]
Great work here, @ramrodo. The next-gen version of the layer5.io site will be live in about 1 1/2 weeks. 👍

**Comment by ramrodo** [comment]
Great! Hoping to see the new site!

**Pull request merged**
