### PR TITLE
feat: migrate books page

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
Was going to be stuck with some personal work so did this. Will do #740 next. // @Nikhil-Ladha

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Few changes:
- There is unnecessary white space at rhe bottom of all the books content.
-  The authors name is repeated 3 times, only mention it at the bottom.
- The books image show issues in mobile view, and rhe image should also be center aligned.
- Check the alignment of buttons too, with the image of book

**Review by leecalcote — APPROVED** [review]
Excellent work, @Tanuj22. You addressed every piece of feedback given on today's call. 👍

**Comment by leecalcote** [comment]
@Nikhil-Ladha I neglected to check the mobile view of the initial PR, and so I'm not sure if all of the points that you highlighted have been addressed. Near as I can tell, the mobile view seems to be in top shape now...

**Comment by Tanuj22** [comment]
@Nikhil-Ladha any other changes needed in this?

**Review by Nikhil-Ladha — APPROVED** [review]
Perfect!

**Pull request merged**
