### PR TITLE
[LHCI] Resolve Lighthouse CI Performance Test Error and Added Desktop Audit

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes the following LHCI issue:

When LHCI runs during GitHub Actions check for PRs, it will show the following performance audit error on the pages `/[pagename].html` (except for 404.html).

[source](https://googlechrome.github.io/lighthouse-ci/viewer/?baseReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1686683403716-55575.report.html&compareReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1687122201217-5368.report.html)
image

[source](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1686683403716-55575.report.html)

image
image

Here is the LHCI after changes: 

image

---

This PR adds the following feature:

LHCI desktop audit

image

---

Here is the most recent LHCI workflow for this PR:
https://github.com/layer5io/layer5/actions/runs/5308808724/jobs/9608696217?pr=4397

[Report ](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1687159842519-95958.report.html)for mobile version of "/company/about/index.html":
image

[Report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1687159030321-54620.report.html) for desktop version of "/company/about/index.html":
image

---
**Notes for Reviewers**

The LHCI performance issue is caused by recent changes to resolve the [flickering trailing slash](https://github.com/layer5io/layer5/pull/4133) issue.

When the LHCI workflow runs `npm run build`, because it is taking place in Github Actions, the `env` variable `CI` is `true` which triggers a conditional to create pages with urls `[pagename].html` instead of  `[pagename]\index.html`. However, the Gatsby server on Github Pages is unable to serve the direct url (for an unknown reason), you can see this in action on the live site (test: https://layer5.io/about.html  or watch the video below):

[404_for_html_ext.webm](https://github.com/layer5io/layer5/assets/90356410/51d1c75e-363b-4fb5-b772-f303b84d3127)

This is **not** an issue for the live site, because the user and all page references use `/[pagename]` format to access pages instead of using the `/pagename.html` url. 

This is an issue for the LHCI tests since it attempts to reach `/pagename.html` for testing and sees a 404 page which is causing the error in the performance audit.

To resolve this issue, we set the env variable `CI` to `false` for the command `npm run build` in the LHCI GitHub Action:
image
and have it test pages with the `\[pagename]\index.html` format (which was how it was done before the trailing slash flicker changes were implemented).

---

Adding the desktop audit

LHCI can also audit the desktop version (the default is the mobile version). Updating the LHCI workflow to reference another config file allows an audit and upload reports of pages loading in the desktop.

While these tests are not as critical since pages perform generally well on the desktop, it is still useful to have a warning issued if pages fall below a performance metric (e.g. 90%). Currently the desktop audits only three pages (404, index, about), and will serve as an additional warning sign of serious site issues.

Cheers,
Randy

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6da5ba2f9b7e08687dd5c5230d3267de915fface at: https://648ff2539ea3322db5d1a352--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 28c65e8f90fd65c0cf6dd0be0eeeabbe08fb5623 at: https://648ff6a012fa58295740d8d8--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 29ffbfc89694883cfd021e2504fc11658fbd8d3a at: https://6490002c12fa582eec402148--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thanks @randychilau 
I'll add this as an agenda item in today's websites call to share with other.

**Comment by l5io** [comment]
🚀 Preview for commit 20a05ef9aa5d5c40846a8c3371f939036a853c0f at: https://6490ebf0b32a79444546655d--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @vishalvivekm,

Thanks for the message and adding it to the call, unfortunately I was not able to attend (hooray 🎉 for the [youtube uploads](https://www.youtube.com/@Layer5io/streams)).

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 139bfdfd9ecc07dcf7b9d05b1d2587a0ede30f4f at: https://6491c7b67dc74904d3808017--layer5.netlify.app

**Review by ayushthe1 — CHANGES_REQUESTED** [review]
Thanks for the changes @randychilau and giving such a detailed report. The performance audits are giving the correct results now.
For desktop audit ,could you please include all the other URLs also for testing.(which are commented currently). Also can we have a log output for desktop audit in a similar way as you have implemented for the default mobile audit (in #4405) as below : 
image
This will help anyone to just take a glance across scores for all pages and then correspondingly open the report for that page which has poor score.

**Comment by l5io** [comment]
🚀 Preview for commit ccc667aecb436f1d28f4a760cc1e17278b1ce6fe at: https://64986c69dd209720f6da657b--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @ayushthe1,

Thanks for the message and taking the time to look at the PR.

As mentioned, I've included the other URLs. 

Regarding the log output, the desktop audit is configured to report the same as the mobile audit in https://github.com/layer5io/layer5/pull/4405:

image

>note: pages generally perform better in desktop audits (due to omission of the network throttling used in [mobile audits](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md#network-throttling)), so there are usually less warnings in the desktop audit log output.

Look forward to any additional feedback.

Cheers,
Randy

**Review by ayushthe1 — APPROVED** [review]
Thanks @randychilau for the changes.

**Comment by l5io** [comment]
🚀 Preview for commit e95e2069ad427e42707665c3d13e5c134914f14b at: https://649e897b3d6e9940daef0cbc--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 387fbc3faf682921519aaacf96b8c4fd75da60b9 at: https://64ae35ad61d42a7ff9fbe387--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b13289ac89879a2020a0ec5a059b69b4cf3fe97c at: https://64af17cf37723720c0a929b8--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cebb00839911cdc5c1a918c44aacc48c7e5d7ccb at: https://64af24361109a406a75d4a15--layer5.netlify.app

**Comment by randychilau** [comment]
Hi All,

The CI Performance Test Error part of this PR overlapped with PR #4405, and when #4405 was merged it resolved the CI Performance Test Error.

<details>
  <summary>image example of Performance Test Error resolved</summary>

image

</details>

Please note that the "desktop audit" part of this PR is still valid for merge consideration. There should not be any issues with #4405 already merged since it was shared code, however if the Maintainers wish to create a separate PR for this, please let me know.

---

**re: `fix: svgoConfig from "cleanupIDs" to "cleanupIds"` [commit](https://github.com/layer5io/layer5/pull/4397/commits/cebb00839911cdc5c1a918c44aacc48c7e5d7ccb)**

I just noticed in the build that this warning began appearing over and over again, which I believe started with the `Bump @svgr/webpack from 6.5.1 to 8.0.1` [PR merge](https://github.com/layer5io/layer5/pull/4467):

```
warning You are trying to configure cleanupIDs which is not part of preset-default.
Try to put it before or after, for example

plugins: [
  {
    name: 'preset-default',
  },
  'cleanupIDs'
]
```
<details>
  <summary>image example of repeated warning</summary>

image

</details>

This build log ([view raw build log](https://pipelines.actions.githubusercontent.com/serviceHosts/36740549-7ef1-45c3-8079-8a9acfde0522/_apis/pipelines/1/runs/26275/signedlogcontent/2?urlExpires=2023-07-12T22%3A11%3A26.9701010Z&urlSigningMethod=HMACV1&urlSignature=QCo2Qachg%2FkQK7JIc81NJ2%2BcffA%2FgEOWUNVRdF8RS3s%3D)) happened on 7/11, the day before the PR merged, and did not show the warning .

This build log ([view raw build log](https://pipelines.actions.githubusercontent.com/serviceHosts/36740549-7ef1-45c3-8079-8a9acfde0522/_apis/pipelines/1/runs/26372/signedlogcontent/2?urlExpires=2023-07-12T22%3A15%3A26.0843232Z&urlSigningMethod=HMACV1&urlSignature=XVqaZVzMG6s5P%2FLKxw4Bj712jqogpcJf5Xr7a3Vny%2Fc%3D)) happens after the PR merged, where it shows the warning.

I believe the bump introduced case-sensitivity for configs, and that the plugin setting with "cleanupIDs" needed to be updated to "cleanupIds" ([as indicated here](https://github.com/svg/svgo/blob/main/plugins/preset-default.js)) which seems to have resolved the error ([view raw build log](https://pipelines.actions.githubusercontent.com/serviceHosts/36740549-7ef1-45c3-8079-8a9acfde0522/_apis/pipelines/1/runs/26391/signedlogcontent/2?urlExpires=2023-07-12T22%3A31%3A00.1238272Z&urlSigningMethod=HMACV1&urlSignature=glnjd0VDq2s1q88JkXWH0pZTHsPYXckEWr8imJxw6gs%3D)).

I added the change in this PR, but again if the Maintainers wish to create a separate PR for this, please let me know.

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 1db39205a74ea977cd724880170a8b44bc6018c8 at: https://64c197170eb4e619f6676058--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM, I'll wait for @Nikhil-Ladha's acknowledgment.

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
