### PR TITLE
Updated psmdb-db-color.svg to actual percona mongoDB logo in svg extension

### PR DESCRIPTION
**Pull request by crazyshrut**
updated logo image of perconaMongoDB

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 95899040a35df21bd33bdb81e2598089ddd286d5 at: https://66bc81d194302c6b1c44fa5b--layer5.netlify.app

**Comment by crazyshrut** [comment]
@Ashparshp kindly merge it, I have a PR for the issue.

**Comment by l5io** [comment]
🚀 Preview for commit 15f0b4dab3ba9a02f653277455901265e725485e at: https://66bc9d69be029a95cabee4cd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6a265ebcb7be418b34ca032f98fc45add16899a2 at: https://66bdf21e0e01631061105479--layer5.netlify.app

**Pull request closed without merging**
