### PR TITLE
[About] Rearrange order of text and images in mobile view

### PR DESCRIPTION
**Pull request by sarkartanmay393**
**Description**

Issue:  #4640 

As mentioned, interleave text and images one after the other is now desired behavior.

Screenshot 2023-07-29 at 11 28 52 PM

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for working on this, @sarkartanmay393. I would rather not hide resources in mobile view, but simply have them resized. Can you facilitate this?

**Comment by sarkartanmay393** [comment]
> Thanks for working on this, @sarkartanmay393. I would rather not hide resources in mobile view, but simply have them resized. Can you facilitate this?

As I used two of the same components there, you want me to use only one and somehow get the desired behaviour done. Right? 

To use the image in between the paragraphs, I needed to re-use the component.

**Comment by l5io** [comment]
🚀 Preview for commit af41b351283fa33e9575bbf6c6eddba62a3197f6 at: https://64c556f6b41ae112abade9c6--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Your changes don't seem to be interleaving the text and images.
Screenshot 2023-07-29 at 1 18 31 PM

**Comment by sarkartanmay393** [comment]
It's visible to me though. 
Okay let me commit some new code changes.

**Comment by Ghat0tkach** [comment]
@sarkartanmay393 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by sarkartanmay393** [comment]
@leecalcote It works as of now.

**Comment by sarkartanmay393** [comment]
@Ghat0tkach I added it. Hope to find a better idea.

**Comment by l5io** [comment]
🚀 Preview for commit dec9efdf7fcb7c9b5b92a60380fd5fc778a7d59e at: https://64c635e703fc336e31a9af43--layer5.netlify.app

**Review by thisiskaransgit — COMMENTED** [review]
@sarkartanmay393, the changes look good 👍🏼. Why were the formatting changes pushed alongside, please revert those and we're good to go.

**Comment by sarkartanmay393** [comment]
@thisiskaransgit I reverted all the unnecessary changes. Now it's ready to merge, I guess.

**Comment by l5io** [comment]
🚀 Preview for commit f6f0657a7896c643beb00f2fb0cf78749229be6f at: https://64d0b560be3d0c469b0eb73f--layer5.netlify.app

**Comment by leecalcote** [comment]
Not quite. Two of the text sections are still discern to one another while two image sections are still adjacent to one another as well. 
IMG_8690

**Comment by thisiskaransgit** [comment]
Closed as completed via #4640

**Pull request closed without merging**
