### PR TITLE
Centered the Careers "Internship Programs"

### LINKED ISSUE #3468: Align internship programs cards to center.
#### Description
Align internship programs cards to center.
Current'

#### Page Link:
https://layer5.io/careers

#### Expected Behavior
Screenshot 2022-11-19 134240

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by YarinDay**
**Description**

This PR fixes #3468 

# Before
image

# After:
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by YarinDay** [comment]
@leecalcote Please review this change :)

**Review by leecalcote — APPROVED** [review]
@YarinDay thanks much. 👍

**Comment by leecalcote** [comment]
Deployment preview building...

**Comment by l5io** [comment]
🚀 Preview for commit 58db06be47fec3c0e63d5a59c5710e073b33cdf6 at: https://63c9bbf996402a330719545d--layer5.netlify.app

**Pull request merged**
