### PR TITLE
chore: added quote to community page

### LINKED ISSUE #4536: Add a quote to the Layer5.io/community page
### Desired Situation
We want to include a comment by community member @priyanshu-kun in the [discuss forum](https://discuss.layer5.io/t/can-someone-explain-me-what-this-meshery-or-none-provider-mean-here/3107/2) as a quote in the [layer5.io/community](https://layer5.io/community) page.

> " Wow, you're incredibly helpful, I wish every open-source community is as friendly as yours."

Be creative and add it to a suitable position.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Yana-Gupta**
Signed-off-by: Yana Gupta [yanagupta897@gmail.com](mailto:yanagupta897@gmail.com)
**Description**

This PR fixes #4536

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9e92ce9b02b36f9282625c92650ca33905c376a2 at: https://64b0dcf59ebb561504361382--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6121dc9334582d4f2228fe0563dc67ac98b66871 at: https://64b109bbd03a70212eb3deff--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 6121dc9334582d4f2228fe0563dc67ac98b66871 at: https://64b10a8c2e28f72150ea709f--layer5.netlify.app

**Comment by Yana-Gupta** [comment]
@leecalcote Can you review the pr once.

**Comment by l5io** [comment]
🚀 Preview for commit 8a00d79b900468c2c787a685556148cd3e8b9887 at: https://64b1811b8137b2460db0c716--layer5.netlify.app

**Review by DarrenDsouza7273 — APPROVED** [review]
Good One @Yana-Gupta LGTM

**Comment by Yana-Gupta** [comment]
@vishalvivekm and @samyakshah3008 will you please review it once.

**Comment by l5io** [comment]
🚀 Preview for commit f1766e89362aba87edd023cf55d966d6cebf0ca1 at: https://64b3a2c52458f80b9943a16b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f1766e89362aba87edd023cf55d966d6cebf0ca1 at: https://64b3a382b828af103a884be8--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thanks @Yana-Gupta 

Let's discuss it on the websites call ( on Monday at 5:30 PM IST).
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by Yana-Gupta** [comment]
> Thanks @Yana-Gupta
> 
> Let's discuss it on the websites call ( on Monday at 5:30 PM IST). Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

I have added.

**Comment by l5io** [comment]
🚀 Preview for commit 97c540700ffafa5cb031044a657c3610ced38311 at: https://64b53ea40253a700974b5f93--layer5.netlify.app

**Pull request closed without merging**
