### PR TITLE
the screenshots have been updated with the new one's

### PR DESCRIPTION
**Pull request by santosh-sankranthi**
This PR fixes #
#4002 
the screenshots of the [introduction to service meshes-hands on ](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started) in getting started section, the screenshots and appropriate description of the steps have been made,
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 644da4a312fcdb112bb3d46ddecb4620a54d3627 at: https://642209702963990fa3a93676--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4b0b1dafcf10471c52e94a3d4d15f9a6168e90e7 at: https://64231a61facbb317a7627077--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Looking good, @santosh-sankranthi 👏 Thanks!

**Comment by santosh-sankranthi** [comment]
Happy to contribute! 😃 @leecalcote

**Pull request merged**
