### PR TITLE
updated the twitter icon and fixed the css

### LINKED ISSUE #4631: Twitter's logo has been changed to X
### Current Behavior
Twitter's logo has been changed to X .I was thinking if we need to update the logo on the layer5 website.
What are the views on this/Any comments?
@leecalcote 
I made some changes it will look somewhat as in the video.
It can be assigned to me if it needs to be changed.

### Screenshots / Mockups

https://github.com/layer5io/layer5/assets/91942072/fc24b4eb-2018-43b7-9f78-b30fe88340f1

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Description**

This PR fixes #4631 & #4755

**Notes for Reviewers**
added a better SVG for easy twitter 
my prettier changed the code that's why so many changes is being displayed.

### File Changed:-
- added a new svg file
- SocialLinks-Color/index.js made the svg to react component.
- SocialLinks-Color/sociallinkscolor.style.js to change the footer_twitter in css as the footer is always black in light/dark theme 
- Community/Handbook/connect.js made the twitter svg in the component 
- Community/Member-single/index.js made the changes for twitter icon

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by captain-Akshay** [comment]
@Mohith234 @ritiksaxena124 would you please review this !

**Comment by l5io** [comment]
🚀 Preview for commit a5f1b648f0911be7bf18377f5ba1ad642e4ef510 at: https://651d42a94b000d46d4868383--layer5.netlify.app

**Comment by captain-Akshay** [comment]
@ritiksaxena124 it would be great if you review the design and check if there are any error or anomaly i missed

**Comment by abhijeetgauravm** [comment]
Hey @captain-Akshay Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Pleasde add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Pull request merged**
