### PR TITLE
[Home] Add Citibank logo to list of "ENGAGING AND COLLABORATING WITH" section ✅

### PR DESCRIPTION
**Pull request by sarkartanmay393**
**Description**

Issue: #4648

This PR fixes #

1. Sourced a svg file.
2. Perfect with light/dark mode.

Screenshot 2023-07-30 at 4 04 31 PM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@leecalcote I see no activity in that issue from the last assignment. So, I did the job.

**Comment by l5io** [comment]
🚀 Preview for commit 59157b57d59706e8a1ac1a88e029e3c77eb67802 at: https://64c642ecf2526274641c1871--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @sarkartanmay393 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Make sure to attend tommorow's website call for review

**Review by leecalcote — APPROVED** [review]
Some good work here, @sarkartanmay393 👍 

I'll see you on the Websites call this week.

**Comment by leecalcote** [comment]
Yay, @sarkartanmay393! 🎈

**Pull request merged**
