### PR TITLE
deleted .vscode folder

### LINKED ISSUE #1040: [NG] Remove .vscode folder
**Current Behavior**

.vscode folder is used for local IDE config, it is something to be pushed upstream.
**Desired Situation**

Remove .vscode folder
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by jomefavourite**
**Description**

This PR fixes #1040

**Notes for Reviewers**
Deleted .vscode folder

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by kushthedude — COMMENTED** [review]
Hi @jomefavourite , please do `git commit --amend --signoff` and `git push --force-with-lease` it will be signed-off then

**Comment by jomefavourite** [comment]
Thanks @kushthedude I've followed your instruction but I didn't get a feedback that I understand. And I can't see any reflect on the PR

**Comment by Tanuj22** [comment]
@jomefavourite are steps working?  https://github.com/layer5io/layer5/pull/1041/checks?check_run_id=1328711089

**Comment by jomefavourite** [comment]
> @jomefavourite are steps working? https://github.com/layer5io/layer5/pull/1041/checks?check_run_id=1328711089

Yes I have followed the steps. But I'm not sure if it's working.

**Comment by Tanuj22** [comment]
@jomefavourite go ahead and open a new PR if you are having trouble fixing this

**Comment by jomefavourite** [comment]
Okay I'll do just that

**Comment by leecalcote** [comment]
@jomefavourite given your other PR, would you like to close out this PR?

**Pull request closed without merging**
