### PR TITLE
Resolve card size inconsistency in Contacts Page (#4768)

### LINKED ISSUE #4768: Fix the inconsistent Card Size in Contacts Page
### Description
[https://layer5.io/company/contact](https://layer5.io/company/contact)
Card sizes are inconsistent for mobile screens
### Expected Behavior
Card styles need to be updated to be consistent for all mobile screens

Ideally, we need to update the current variables and not introduce new ones

### Screenshots

</img>

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ashparshp**
Improves visual consistency by adjusting card sizes for a better user experience.

**Description**

Refactors card dimensions and alignment for improved visual consistency, enhancing the user experience, especially in mobile screens.

Before
After

For various devices testing results before and after:

Xiaomi Mi 11i Before: 
Xiaomi Mi 11i Before

Xiaomi Mi 11i After: 
Xiaomi Mi 11i After

Samsung Galaxy S20 Before: 
Samsung Galaxy S20 Before

Samsung Galaxy S20 After: 
Samsung Galaxy S20 After

This PR fixes #4768 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
> Improves visual consistency by adjusting card sizes for a better user experience.
> 
> **Description**
> 
> This PR fixes #
> 
> **Notes for Reviewers**
> 
> **[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> 
> * [x]  Yes, I signed my commits.

Hey @Ashparshp Please update your description with the issue it fixing like This PR fixes #4768. And We really appreciate your enthusiasm to contribute , please refrain from creating direct PRs without getting assigned first . also give the Contributing guidelines a read.

**Comment by Ashparshp** [comment]
> > Improves visual consistency by adjusting card sizes for a better user experience.
> > **Description**
> > This PR fixes #
> > **Notes for Reviewers**
> > **[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> > 
> > * [x]   Yes, I signed my commits.
> 
> Hey @Ashparshp, please update your description with the issue it fixes, like 'This PR fixes #4768.' We really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first. Please do take the time to read the Contributing guidelines.

Hey i have updated the description with screenshot before and after effect.

**Comment by l5io** [comment]
🚀 Preview for commit a4582506eb75ff061cb4504bd4d7803baa7d2921 at: https://6564516019313911afa74745--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]
lgtm

**Comment by saurabh100ni** [comment]
Hey @Ashparshp Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Pull request merged**
