### PR TITLE
deploy-service-mesh ui fix

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: vinayaksh42 <vinayaksh42@gmail.com>

**Description**

- Replaced the arrow with a bar 
- dynamic bar (fills up according to the form)
- range slider value on the left side
- blur the remaining questions
- book fix for mobile view (width is wrong (help required on this))

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 76016164b581e9fea8e43b78e53df09b8ba2a472 at: https://6068c61ed977d314e1b54afa--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Very cool.

**Comment by Nikhil-Ladha** [comment]
How does the filling of the horizontal bar works?
And, is it possible to have the numbers dynamic in the slider, i.e, change with a slide instead of change on mouse leave?

**Comment by Nikhil-Ladha** [comment]
Also, a lot of places in the code you are using `'id` and using the same id for different tags, is wrong. Id's should be unique, else always prefer to use `class`. Please update that.

**Comment by Nikhil-Ladha** [comment]
@vinayaksh42 I have fixed the book image, so once you make the other changes and we are good to go here..

**Comment by l5io** [comment]
🚀 Preview for commit 4934dc4ff8a8e6f3c8b18de0f161e3185c4ed186 at: https://606970bfaa1940517dc3418a--layer5ng.netlify.app

**Comment by vinayaksh42** [comment]
@Nikhil-Ladha thanks a lot for fixing it. I will push the required changes asap

**Comment by vinayaksh42** [comment]
The logic for the horizontal bar is basically that I add up all the slider values and then divide it by 800 which is the total sum of the maximum possible value. Then multiply it with 100. For rangeslider it is actually using `onChange` , will have to look into it

**Comment by l5io** [comment]
🚀 Preview for commit 14a5db67f6d84cafbbe82632f4d2d78864b1c805 at: https://606992876b4ca2086b90f6cd--layer5ng.netlify.app

**Comment by chinmaym07** [comment]
Hey @vinayaksh42 . Just a small thing to rectify .. If we hover beside the image col not on the image ..It is showing pointer cursor .. but it should be shown when someone hovers over the image 
Just remove ```display:block``` from the link tag

https://user-images.githubusercontent.com/44670961/113506574-46611300-9563-11eb-8249-53ea2c9aabd4.mp4

**Comment by Nikhil-Ladha** [comment]
> The logic for the horizontal bar is basically that I add up all the slider values and then divide it by 800 which is the total sum of the maximum possible value. Then multiply it with 100. For rangeslider it is actually using `onChange` , will have to look into it

The thing is the bar should be be not filled at all, when everything is moved to 0, but that's not happening.

**Comment by vinayaksh42** [comment]
> > The logic for the horizontal bar is basically that I add up all the slider values and then divide it by 800 which is the total sum of the maximum possible value. Then multiply it with 100. For rangeslider it is actually using `onChange` , will have to look into it
> 
> The thing is the bar should be be not filled at all, when everything is moved to 0, but that's not happening.

That might be because you might have not moved all the range sliders to zero. 
Check this screenshot:
chrome_Q8y9dyPElb
You might have not moved these sliders to zero.
chrome_mhZpQbmvb7

If required we can set the starting value of all the slider to zero in case if we want it to start from zero

**Comment by Nikhil-Ladha** [comment]
Ohh, I thought it doesn't consider the hidden values until they are visible. Can that be done?

**Comment by Nikhil-Ladha** [comment]
We want to start it with 50 only. But, take only those values which are `in-view`

**Comment by vinayaksh42** [comment]
> We want to start it with 50 only. But, take only those values which are `in-view`

yes, that can be done. We have a variable that checks if or not the email and name are filled

**Comment by vinayaksh42** [comment]
@Nikhil-Ladha fixed the loading bar
@chinmaym07 fixed the book link

**Comment by l5io** [comment]
🚀 Preview for commit 424c1d2b624bcee1b661226d343dd8f401a387c2 at: https://606ab51b33d1e7ac1ffa4a86--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Looks good, any reason for keeping the commented code?

**Comment by vinayaksh42** [comment]
> Looks good, any reason for keeping the commented code?

I had saved the Arrow css, just in case we ever wanted to implement an arrow-based loader.
I Will remove it and save it in my system

**Comment by l5io** [comment]
🚀 Preview for commit 25bc00ee7af60e754d2730f49ab2b3f0d1722614 at: https://606b11e54d92541530ad41b8--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Wow. What a great improvement in a number of areas. This is a big step forward. In fact, functionally, it might be ready for linking to. We're ready to fill in the rest of the content / questions, I believe.

**Review by leecalcote — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Cool, then let's merge this and later an enhancement and further linking of this page to different pages can be done.

**Pull request merged**
