### PR TITLE
Enhanced look of Partner Page

### PR DESCRIPTION
**Pull request by dDab-panda**
Signed-off-by: Aayush <aayush.bcode@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@dDab-panda good, good. Is this the preview page? https://deploy-preview-1029--layer5ng.netlify.app/partners

**Comment by dDab-panda** [comment]
> @dDab-panda good, good. Is this the preview page? https://deploy-preview-1029--layer5ng.netlify.app/partners

Yeah, that's what I could come up with playing around with HTML. Made the page more formal and removed unnecessary text.
Might make more changes if I get some design ideas with the help of Jash.

**Comment by Jashpatel1** [comment]
@dDab-panda can you just change the partners link in footer from /company/partners to /partners for ease.

**Review by dDab-panda — COMMENTED** [review]
Fixed small issues as required

**Review by Jashpatel1 — COMMENTED** [review]
@dDab-panda Looks good for now. We will hold some time to try new layouts.

**Comment by leecalcote** [comment]
@Jashpatel1 are we ok to merge this initial update, understanding that new design is likely in the future?

**Review by Jashpatel1 — APPROVED** [review]
Nice work here. Thanks @dDab-panda

**Comment by Jashpatel1** [comment]
@dDab-panda Can you just resolve the merge conflicts, then we are ready to go.

**Comment by dDab-panda** [comment]
> @dDab-panda Can you just resolve the merge conflicts, then we are ready to go.

Cool

**Comment by dDab-panda** [comment]
> @dDab-panda Can you just resolve the merge conflicts, then we are ready to go.

Done

**Review by leecalcote — APPROVED** [review]
Thank you, gents.

**Pull request merged**
