### PR TITLE
Fix Github icon on Discussion Forum

### LINKED ISSUE #3868: Github Icon not visible on discussion Forum
### Description
If we hover over the GitHub icon on the footer of the community forum ([discuss.layer.io](http://discuss.layer.io/))  this is what we are seeing, due to the inversion of color, when hovered over the icon it appears black.

### Expected Behavior

The GitHub icon should be glowing with its correct color, as same as other icons.

### Screenshots

Screenshot from 2023-03-01 23-51-55

### Environment:
- Host OS: Ubuntu
- Browser: Chromium

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Description**

This PR fixes #3868 

**Notes for Reviewers**
Fixed the hover effect for the GitHub icon on the discuss.layer.io
Screenshot from 2023-03-03 00-59-31

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @thisiskaransgit

**Comment by l5io** [comment]
🚀 Preview for commit 34426128edd7952a826ae99288252f3e4d83fd6b at: https://6400fd72a8023c1a8cc9653b--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
COOL. Thanks @thisiskaransgit

**Comment by money8203** [comment]
Hey @thisiskaransgit can you please recheck your changes as the issue still persists

Screenshot (273)

**Pull request merged**
