### PR TITLE
changed jpg/png images to webp

### LINKED ISSUE #4281: [Performance] - Replace all .jpg/.png to .webp images
### Current Behavior

Currently most of the images on layer5 website are in .png or .jpg format which significantly affect the loading and performance of website. 
### Desired Behavior

These images should be converted to .webp format and also be replaced in the image source.
### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4281 

Converted all images in jpg/png format to webp and made corresponding changes to the import statements on all pages, replacing .jpg/.png with .webp.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cce756c0a3a9e72046f269656c8f2db04d420527 at: https://646ec2ee8945ce3e614e91b3--layer5.netlify.app

**Comment by ayushthe1** [comment]
Thanks for the changes @AkashS20 . The changes look good and there is a good improvement in websites performance.

**Comment by l5io** [comment]
🚀 Preview for commit b3243b2a2bf36ceaafe6435f818e8ede374dfc4a at: https://647428fd5650442fafbef5a9--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@AkashS20 This PR creates an impactful change on the website. Is this ready to be merged? Care should be taken that there are no missing .webp images. // @ayushthe1

**Comment by AkashS20** [comment]
@Shivam-AfA Sure :+1:

**Comment by Shivam-AfA** [comment]
@AkashS20 Is this PR ready? // @ayushthe1

**Comment by ayushthe1** [comment]
@Shivam-AfA I have gone through most of the pages and didn't found any error. I think it's good to go.

**Comment by Shivam-AfA** [comment]
@ayushthe1 All right then! Merging this, and it would be nice if you could provide a brief about how much performance improvement this change has on the websites call.

**Comment by l5io** [comment]
🚀 Preview for commit 1657ef2f8e0941e61fd9bf5ff93a1e9b89623e02 at: https://647c4aebaf2e9e0aeb6f1bf1--layer5.netlify.app

**Pull request merged**
