### PR TITLE
[Features-Col] Feature Cards Not Responsive Fix

### LINKED ISSUE #2683: [UI] Feature cards not fully responsive
**Description**
In the following page https://layer5.io/service-mesh-management/meshery, the feature cards are not fully responsive. I looked at the code I think the CSS with responsiveness and the readability of the code can be improved.

**Expected Behavior**
Content inside the cards are responsive and don't collide with other elements.

**Screenshots**

Responsive Bug

**Environment:**
- Host OS: Windows 11
- Browser: Google Chrome

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

I would love to contribute and work on this issue under **Codeflow Openforce 2022.**

### PR DESCRIPTION
**Pull request by indraantoor**
**Description**

This PR fixes #2683 

**Notes for Reviewers**
Now the cards are fully responsive and also adapt to the height changes without the elements colliding on top of each other like they were previously. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@indraantoor please revert the changes in `package-lock.json` and `package.json` file.

**Comment by indraantoor** [comment]
Reverted

**Comment by l5io** [comment]
🚀 Preview for commit 39358d84b34f7907b57c4ac05c9d9e3a3ceb88cc at: https://6248b4e8294d107900da795b--layer5ng.netlify.app

**Review by Chadha93 — APPROVED** [review]
@indraantoor Good Work, LGTM :1st_place_medal: The cards now work smoother for responsiveness :100:

**Pull request merged**
