### PR TITLE
Add partners page

### LINKED ISSUE #1355: [NG] Interactive Partners page
**Current Behavior**
Layer5 has a number of partners, but in academia and technology.

**Desired Behavior**
A categorized (by type), alternating list of partners with expandable Learn More panel should be available at layer5.io/partners

**Mockups**
See https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=293%3A0

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by shubhank-saxena**
**Description**

This PR fixes #1355 

**Notes for Reviewers**
 - Kept away with learn more (had a bad week). Can totally pace up with some pair programming if that's okay!
 - This needs 256x256 images according to design spec

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Is adjusting the ratio using CSS, making the images skewed?

**Comment by shubhank-saxena** [comment]
> Is adjusting the ratio using CSS, making the images skewed?

Yes!

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
It's looking good in all views. But few tweaks are needed which are as follows:
- The unused CSS can be removed.
- Don't apply font-weights and font-sizes to heading tags, and prefer to use the centralised one. (Until and unless it causes a lot of difference)
- In mobile view, when all the partner data are in one column, we don't want the images to be alternated, keep it just above the partnership description.

**Comment by leecalcote** [comment]
Thank you, @Nikhil-Ladha and @shubhank-saxena. Feedback from today's call:

1. Review and ensure that the aspect ratio of SMI logo is retained.
1. Make alternating rows dynamic using modulus. 
1. Only set either the width or the height of the logos, so that images expand to fill the 250 x 250 (as much as they can depending on their shape).
1. Ensure that all logos are in SVG format.
1. Work toward a subsequent PR with the “learn more” expander.

**Comment by leecalcote** [comment]
Will merge this and open an issue for the remainder (@shubhank-saxena is good for it. 😉 )

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@shubhank-saxena do you mind opening an issue for the remainder item?

**Comment by shubhank-saxena** [comment]
> @shubhank-saxena do you mind opening an issue for the remainder item?

On it!

**Pull request merged**
