### PR TITLE
Made ebpf logo visible in dark mode

### LINKED ISSUE #5070: Dark mode version of eBPF logo on Meshmap Page
### Description
Currently, in the dark mode the "ebpf logo" is not visible accurately on the [catalog page](https://layer5.io/cloud-native-management/meshmap)

### Expected Behavior
A dark-mode friendly ebpf logo should be updated with the current one

### Screenshots
Screenshot 2023-10-21 233015

### PR DESCRIPTION
**Pull request by Shreyas0410**
**Description**

This PR fixes #5070 

**Notes for Reviewers**
Earlier the eBPF logo [on](https://layer5.io/cloud-native-management/meshmap) was not visible clearly.

Screenshot 2023-10-22 182412

Added a white shadow to make the logo visible

Screenshot 2023-10-22 182726

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d8b926dcb2b2d0405e2a29e538f57fed8193b007 at: https://65351fbbe7d3246c635462b9--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @Shreyas0410 Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Shreyas0410** [comment]
@abhijeetgauravm can you please review

**Comment by ritiksaxena124** [comment]
@Shreyas0410 thanks for taking this up. will you update the logo to what we have on the [catalog ](https://layer5.io/catalog) page for consistency and will you also make sure to use SVG?

**Comment by abhijeetgauravm** [comment]
Hey @Shreyas0410  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 do you want me add a white shadow around the eBPF logo on the catalog page similar to this? Also remove the dark mode logo?

I want you to use that same logo here as that one is the original logo that eBPF provided to be used on the dark backgrounds.

**Comment by Mohith234** [comment]
@Shreyas0410 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by sandramsc** [comment]
Adding any additional styling to the logo (whether its in dark or light mode) changes the logo i.e it becomes a different logo all together.

**Review by sandramsc — COMMENTED** [review]
Adding any additional styling to the logo (whether its in dark or light mode - however minor it is) changes the logo i.e it becomes a different logo altogether. With this said, unless there's an already designed logo designed specifically for dark mode (inquire with the UX contributors - CC:  ) I suggest holding off on making changes to this particular logo that arn't coherent with the logo in dark mode wherever it appears across all projects in  layer5

**Comment by abhijeetgauravm** [comment]
Hey @Shreyas0410  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by sudhanshutech** [comment]
any update @Shreyas0410 ?

**Comment by iArchitSharma** [comment]
As the contributor is inactive, and as mentioned by @sandramsc, I think we don't need these changes. Therefore, I am closing the PR

**Pull request closed without merging**
