### PR TITLE
Fix SVGs to be Responsive to Mobile View

### LINKED ISSUE #4119: Make SVGs responsive to media queries and changes from desktop to mobile.
### Current Behavior
Some recent files were changed from image type to SVGs for color mode transitioning. They are not resizing/responding to the media queries in the styled components.

svg_no_responsive

### Desired Situation

SVGs are responsive to media queries and changing from desktop to mobile.

Need to add "max-width" tag to SVGs.

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes #4119 

Before:
svg_no_responsive

image

------
After:
svg_responsive

image

**Notes for Reviewers**
The following pages/sections with SVGs that were modified in PR #4003 have been checked for mobile responsiveness:

- meshmap-design-banner.js, 
- operating-service-meshes.js, 
- src/sections/General/Navigation/index.js, 
- src/sections/Careers/Career-single/index.js
- src/sections/Projects/Nighthawk/index.js

Another PR will need to be submitted for another group of pages. 

Some of the checked pages above include color mode transition updates for uniform color change.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by randychilau** [comment]
Hi @Chadha93 

> The first section is looking too big in Desktop view now.
image


Thanks for your note in slack, can you please provide dimension/browser/os details for the screenshot so i can try to reproduce?

I am currently on a Mac OS and using Chrome (this is the [netlify preview](https://64463879586029158bad14df--layer5.netlify.app/cloud-native-management/meshmap/design)):
meshmap_designer_browser_resize

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 555cee80f6a825a60807520c9e0e3b00d2135a24 at: https://64481d8de8a02002ca93fdf6--layer5.netlify.app

**Comment by Chadha93** [comment]
> Hi @Chadha93
> 
> > The first section is looking too big in Desktop view now.
> > image
> 
> Thanks for your note in slack, can you please provide dimension/browser/os details for the screenshot so i can try to reproduce?
> 
> I am currently on a Mac OS and using Chrome (this is the [netlify preview](https://64463879586029158bad14df--layer5.netlify.app/cloud-native-management/meshmap/design)): meshmap_designer_browser_resize [ meshmap_designer_browser_resize ](https://user-images.githubusercontent.com/90356410/234034018-acaaa0aa-d870-47e2-a142-109bec616ff7.gif) [ ](https://user-images.githubusercontent.com/90356410/234034018-acaaa0aa-d870-47e2-a142-109bec616ff7.gif)
> 
> Cheers, Randy

@randychilau I'm on Linux: Ubuntu 20.04.4 LTS, Browser: Brave

**Review by Chadha93 — APPROVED** [review]
LGTM, 
Side note: We will be replacing the hero with a live cytoscape canvas, in the coming days/weeks.

**Comment by randychilau** [comment]
HI @Chadha93,

regarding the desktop screenshot:
image
> I'm on Linux: Ubuntu 20.04.4 LTS, Browser: Brave

Is the zoom setting on the browser at 100% or something else?

I was able to reproduce in Firefox which, like Brave, also uses open-source Chromium code with zoom set to 50%
image


If so, I will research browser zoom and SVG resizing methods.

I will also look into the menu issue you mentioned above.

Thanks,
Randy

**Comment by Chadha93** [comment]
Awesome, also thanks for taking care of the expand the close item. 3 fixes in a single PR. :rocket:

**Comment by l5io** [comment]
🚀 Preview for commit 01cf057bebaff16e8bfb7a34ca1534688fe9b3a3 at: https://64483630e50aff1bfd438985--layer5.netlify.app

**Pull request merged**
