### PR TITLE
feat: Sistent site 

### PR DESCRIPTION
**Pull request by lakshz**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d22a86ccf36104677708c06bfdf52426f58eadaf at: https://65c224ac65576f78f7c79a46--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 74de18a6b004e0430902cc151404766db043ddf1 at: https://65c2ddfa25eaba1675e95f6d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e4d263059d71432e4452b86aea33ddb50ad9d718 at: https://65c4369b0fef271989c75a4c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f5729a3db669865cbbedc0315c4ada39641c17bf at: https://65d9bea14e315fd608af169e--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d29fe3dcabef3fe62d5a639888677428622538f9 at: https://65d9e9360acc2cf2621f53ae--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c080c9f28cf14aa4729afa0bcb1fedeef9f2b585 at: https://65dae98f0ae7ed9a0e9db45a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ee5cd1cac311d6aa764075a4dd0a4ba51d75ac68 at: https://65db6a704e6242f4b9b34972--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d35d57ca757ddf8e04db0ac017a491f4cb3bb125 at: https://65dc2a004e62427524b351a4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 96ecf7280f24ece85a19abdac2d38994248c8e1d at: https://65e07ae5d2eef5097bef7f4e--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Merge conflicts

**Comment by l5io** [comment]
🚀 Preview for commit f4e236d4172b437a28c8d16cf5a87561f1779f1d at: https://65e8a9e476bd4a28178c0e6b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b6942606670429f6f496a6279fda70ff409a8e2c at: https://65e98d81877670d6f72338bb--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ac5b4139cc136260d42be56efc91a9aef3fbcc0a at: https://65eae94706603d727b7edac3--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f5bc7d5c256256ec8840b4b174a75c859b924254 at: https://65eaf06c9a57511056d74542--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b4d8e70a1c2a1c697bebb6ad359e43875ad69312 at: https://65ec3d7bd83a6d8e36751333--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8f50600557173cbebaca4994e5d547a9c6198e50 at: https://65f14f99f7389da27665f76a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c5f1c0053eff0986c6da3707232c526d6bcd6488 at: https://65f2e30137ffb2befd8e3c44--layer5.netlify.app

**Comment by leecalcote** [comment]
Let's merge this puppy once the conflicts are addressed.

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit c00d59b6675f7ced2aa3ec5ad4f84c04a6097396 at: https://65f49f7efbe72c19a752f204--layer5.netlify.app

**Comment by lakshz** [comment]
Ready for merge 🚀

**Pull request merged**
