### PR TITLE
Mobile issue fix

### LINKED ISSUE #3801: [MeshMap] Mobile issue
Currently, the https://layer5.io/cloud-native-management/meshmap page has some mobile issues as captured in the screen recording below:

https://user-images.githubusercontent.com/7570704/220343899-b2178add-2eaa-4ecd-8ab1-74df4c61998a.MOV

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/3784#issuecomment-1438390903_

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
**Description**

This PR fixes #3801 

**Notes for Reviewers**
I ran the `npm run lint` once thats why it fixed the indentations and all. The fix I made was adding `overflow-x: hidden` to the VisualizerFeatures.style.js and CollaboratorFeatures.style.js

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e551544f3420c0ee45322c2a5f74709a7095cdbe at: https://63f66ea9bcffab0639c8180e--layer5.netlify.app

**Comment by leecalcote** [comment]
Merge conflict

**Review by Shivam-AfA — APPROVED** [review]
LGTM 🚀

**Comment by Sheikh-JamirAlam** [comment]
@leecalcote Is there a problem?

**Comment by l5io** [comment]
🚀 Preview for commit bc2bf5f1eef2765843432f2d9b8dc01872e9f8c3 at: https://63f7689d7166ad0bf9e9f10d--layer5.netlify.app

**Comment by leecalcote** [comment]
> @leecalcote Is there a problem?

Was there not a merge conflict?

**Comment by Sheikh-JamirAlam** [comment]
> > @leecalcote Is there a problem?
> 
> Was there not a merge conflict?

I think its solved.

**Comment by leecalcote** [comment]
@Sheikh-JamirAlam yes, right here - https://github.com/layer5io/layer5/pull/3805/commits/bc2bf5f1eef2765843432f2d9b8dc01872e9f8c3

**Pull request merged**
