### PR TITLE
Resource addition of dc22 blogs

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**

This PR fixes #
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by debo19** [comment]
@Chadha93 will you also add technology as docker and product meshery

**Comment by l5io** [comment]
🚀 Preview for commit ffad6548e05bdf87b493b48f7687d4aa0f45be1b at: https://62822155de38ae00830972d2--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 61bba559ecb0787a74f2eb6f3e63c02f3755a885 at: https://62823c686e53b713ddc82dd9--layer5ng.netlify.app

**Review by debo19 — APPROVED** [review]
Thank you @Chadha93 🎉

**Pull request merged**
