### PR TITLE
Added links to Blog Page Authors

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
There is an issue with Ant/ Anton Weiss in some areas, mixed name is used. So, if you could make all of them to Anton.

**Comment by kishore007k** [comment]
@Nikhil-Ladha Yeah sure.

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good 👍🏼

**Comment by Nikhil-Ladha** [comment]
Yeahh! Finally first PR 🙂

**Comment by PluckyPrecious** [comment]
Yippee 🥳 
Welldone @kishore007k 💪🏽

**Comment by kishore007k** [comment]
Thank You! 😅 @PluckyPrecious

**Comment by leecalcote** [comment]
haha! Niiiice!

**Pull request merged**
