### PR TITLE
Fixed Responsiveness of buttons in Pricing section for 320px

### LINKED ISSUE #4267: The responsiveness of some button is not working properly
### Description

The responsiveness of some button is not working properly [here](https://layer5.io/pricing)

### Screenshots

![Screenshot from 2023-05-22 23-14-22]

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Gautam-04**
**Description**
There were responsiveness issues in buttons for 320px screens.
Screenshot (52)
Screenshot (53)

This PR fixes #4267

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 90aac0122fba1a7e26cb765d20ed3d81b86d051a at: https://64cbc73a40a3890d60b32222--layer5.netlify.app

**Review by samyakshah3008 — APPROVED** [review]
Great work @Gautam-04 
Nice PR description too.

**Review by Mohith234 — APPROVED** [review]
LGTM @Gautam-04

**Comment by l5io** [comment]
🚀 Preview for commit c3371caf426bcbe1987f6c1f952eb04451cc5a23 at: https://64ce4c8f4077e0434d8fe44f--layer5.netlify.app

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
@Gautam-04, updating the left margin for the screen width of ~320px, will work fine. Why were the formatting changes done here, please revert them.

**Comment by Gautam-04** [comment]
@thisiskaransgit I am just adding 4 lines in the code even after that it is showing 141 lines changed. I think only the format is getting edited according to the system.

**Comment by leecalcote** [comment]
> @thisiskaransgit I am just adding 4 lines in the code even after that it is showing 141 lines changed. I think only the format is getting edited according to the system.

@Gautam-04 all of those changes just make it harder for maintainers to review - makes the process take longer. We're in need of more maintainers. Until we groom some, it'd be helpful if you were to eliminate non-essential changes.

**Comment by l5io** [comment]
🚀 Preview for commit 284e5180d49446cecf0b419831b686abe1f51c04 at: https://64d48f7074f2453c7dfe43eb--layer5.netlify.app

**Comment by Gautam-04** [comment]
Creating other pr to solve this issue

**Comment by abhijeetgauravm** [comment]
@Gautam-04 r u on it?

**Comment by Gautam-04** [comment]
Yeah I am on it

**Comment by abhijeetgauravm** [comment]
Okay @Gautam-04 🚀

**Pull request closed without merging**
