### PR TITLE
Added the member profile of Sunku Ranganath

### LINKED ISSUE #2130: [Community] Member Profile: Sunku Ranganath
**Current Behavior**

@sunkuranganath  has been a SMP Maintainer and community member.

**Desired Situation**
Let's recognize @sunkuranganath  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: sunkuranganath
- Twitter: sunkuranganath
- LinkedIn: sunkuranganath
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Added Member profile for Sunku Ranganath

This PR fixes #2130 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6d561fe7f47335421545f42c6e797b2a3163bebb at: https://612a99ac1630d030348a58da--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ef746705db87c30e55eb8bb5da3be462723c323d at: https://612a9cd5f76d1c2533c42b0f--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM!

**Review by Tanuj22 — COMMENTED** [review]
Can you add `maintainer: yes`

**Comment by sayantan1413** [comment]
Yes @Tanuj22 added it!

**Comment by l5io** [comment]
🚀 Preview for commit 0d36b2a41e965fafc13c22f85819b5b96dc01db3 at: https://612b65431630d088578a5b46--layer5ng.netlify.app

**Review by sunkuranganath — APPROVED** [review]

**Comment by sunkuranganath** [comment]
Thank you @sayantan1413  for doing this.

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
