### PR TITLE
Added a callout to the community discussion forum

### PR DESCRIPTION
**Pull request by iambami**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Hey, @iambami I guess it's been a long time since you have updated your fork. Please fetch the new code and then create a PR.

**Comment by leecalcote** [comment]
@iambami thank you for spreading the good word about the community forum. 👍

**Comment by iambami** [comment]
@Nikhil-Ladha, Yeah it seems so, I have pulled the new repo two days ago but I have an issue cloning it. I have reached out to @Anita-ihuman but it isn't resolved yet.

**Comment by leecalcote** [comment]
I was going to resync this branch with `master`, but when I did, there are 2,000+ changes. @iambami will you give this another shot? You can save off your change, and perhaps, the easiest thing to do is delete your local clone/fork and re-clone/re-fork the repo.

**Comment by iambami** [comment]
Yes @leecalcote  I'm on it

**Comment by leecalcote** [comment]
Thank you, thank you, @iambami 👍

**Pull request closed without merging**
