### PR TITLE
Learning path link fixed

### LINKED ISSUE #4695: Issue with Learning Path Link After Requesting Free Ebook
### Description
When submitting the required details to receive the free ebook on the page [The Enterprise Path to Service Mesh Architectures](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures), a confirmation message for the free learning path is displayed. However, upon clicking the provided link, a 404 error occurs.

### Steps to Reproduce:

1. Go to [The Enterprise Path to Service Mesh Architectures](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures) page.
2. Enter the required details and submit to request the free ebook.
3. Observe the confirmation message mentioning the free learning path.
4. Click on the provided link for the learning path.

### Expected Result:
Clicking the link should lead to the free learning path related to service meshes.

### Actual Result:
Clicking the link results in a 404 error page.

### Additional Information:
The learning path link that is not working: https://layer5.io/learn/learning-path

This issue prevents users from accessing the intended learning path after requesting the free ebook. It would be greatly appreciated if this link could be fixed to provide a seamless learning experience.

### Screenshots
1. Before submitting the form:
image
2.  After Submission:
image
3. learning path page:
image

### Environment:
- Host OS: Windows 11
- Browser: Brave

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**

This PR fixes #4695 

**Notes for Reviewers**
fixes two pages : 
1) https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures
2) https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 47150cecdf093a1a1be05471d9ea256c8cdc92bc at: https://64d2608086ba9722d11c7539--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM ! @iArchitSharma

**Review by thisiskaransgit — APPROVED** [review]
@iArchitSharma Thanks for the quick fix 👍🏼

**Comment by leecalcote** [comment]
Thank you, gents. 👏

**Pull request merged**
