### PR TITLE
Added slider to the Proud Maintainers Signed-off-by: Rakshit Sharma <…

### LINKED ISSUE #4464: Add slider to the project list
### Current Behavior

 Projects list are out of the page in general as well as in small screen.
### Desired Behavior

Make this a carousal. 
### Screenshots / Mockups

Screenshot 2023-06-29 192927

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by RakshitKumar04**
…kumarrakshit0402@gmail.com>

**Description**

This PR fixes #4464

**Notes for Reviewers**

Changed the Proud Maintainer slider 
250270619-b63a7cce-3f5c-441e-a83f-3c3e38c74543

To a moving slider
Screenshot from 2023-07-09 15-13-26

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8c888a058026110c3314be767a5a8f529c7a856b at: https://64aa85cb2211461407251147--layer5.netlify.app

**Comment by leecalcote** [comment]
@sudhanshutech adding to agenda?

**Comment by Ghat0tkach** [comment]
@RakshitKumar04  good work !!
Just a few improvements , the carousal isnt responive , you can take inspiration from the home page carousal

image
image

**Comment by samyakshah3008** [comment]
@RakshitKumar04 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by sudhanshutech** [comment]
@RakshitKumar04 lets discuss on website call

**Comment by Nikhil-Ladha** [comment]
Are we finally giving up on explaining that this _is by design_ and making use of a slider, huh?

**Comment by l5io** [comment]
🚀 Preview for commit 23834e85bc71fc3d920f7a44eb005d371994b853 at: https://64b516a61165af00b7d19a2f--layer5.netlify.app

**Comment by leecalcote** [comment]
> Are we finally giving up on explaining that this _is by design_ and making use of a slider, huh?

😀 I figure this way, we might actually save ourselves from the trouble.

**Review by leecalcote — COMMENTED** [review]
@RakshitKumar04, thank you. Do you mind working to make sure that the white lettering for the SMP logo is used in dark mode?

**Comment by leecalcote** [comment]
> @RakshitKumar04 good work !! Just a few improvements , the carousal isnt responsive , you can take inspiration from the home page carousal

Excellent suggestion.

**Comment by RakshitKumar04** [comment]
Hey, @leecalcote the white lettering is now being used in the dark mode, also the slider has been made responsive and works perfectly when switched from dark to light mode as discussed in the website weekly call.

NOw the slider looks like this-
Screenshot from 2023-07-18 02-01-41

Please give it a look.

**Comment by l5io** [comment]
🚀 Preview for commit 31db87ef4f2351473a20926944d16d924626da64 at: https://64b5a6d647333e5a58a5b133--layer5.netlify.app

**Comment by leecalcote** [comment]
Yikes. Nasty.

**Comment by l5io** [comment]
🚀 Preview for commit bb0617c97ce6292244b97c43b8f2897bb5a8dee7 at: https://64bd69c633a8cd4042944fe4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bb0617c97ce6292244b97c43b8f2897bb5a8dee7 at: https://64bd6a593be6e347a84cc09f--layer5.netlify.app

**Comment by Chadha93** [comment]
@RakshitKumar04 Suggestion: Make it an auto infinite carousel with a smooth transition.

**Comment by RakshitKumar04** [comment]
> @RakshitKumar04 Suggestion: Make it an auto infinite carousel with a smooth transition.

@Chadha93  Should I also increase the distance between the blocks?
Please refer to this link: https://64b5a6d647333e5a58a5b133--layer5.netlify.app/

**Comment by Ghat0tkach** [comment]
Hii @RakshitKumar04 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Make sure to attend tommorow's website call for review

**Pull request closed without merging**
