### PR TITLE
added two new screenshots to curiefense integration

### LINKED ISSUE #4884: [Screenshots] Curiefense under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/curiefense) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Curiefense](https://layer5.io/cloud-native-management/meshery/integrations/curiefense) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by thakuraman24**
**Description**

This PR fixes #4884

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e4d08eb21efb54bdf282fcc46ff73ae9e9d32c5f at: https://652960322e23ff06288da114--layer5.netlify.app

**Review by singh1203 — CHANGES_REQUESTED** [review]
@thakuraman24 Does your screenshotrepresent the **Curiefense** Integration.?
Also, we need at least four screenshots with the specific integration.
Take this as reference [https://github.com/layer5io/layer5/pull/4990](https://github.com/layer5io/layer5/pull/4990#issuecomment-1760035148)
Thank you for your contribution.

**Comment by thakuraman24** [comment]
@singh1203 I am having two problems while contributing to this issue 

-->The first one is that I am totally new to this cloud-native field and don't know how to design these Meshmaps of different integrations, so can you provide me with some references that I can use to create a CURIEFENSE SPECIFIC Meshmap? 

-->The second one is that the LIGHTHOSECI test for the above PR failed do you have any idea what could be the reason for that?

**Comment by singh1203** [comment]
> @singh1203 I am having two problems while contributing to this issue 
> 
> -->The first one is that I am totally new to this cloud-native field and don't know how to design these Meshmaps of different integrations, so can you provide me with some references that I can use to create a CURIEFENSE SPECIFIC Meshmap? 
> 
> -->The second one is that the LIGHTHOSECI test for the above PR failed do you have any idea what could be the reason for that?

Thank you for pointing it out, feel free to open the thread in slack or discussion forum on Layer5 discuss forum where me along with other member's will help you out.

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
@thakuraman24 thankyou for working on it, make sure these acceptance test follows, and mark them as completed, also regarding design you don't need to create your own, you can use published design and clone them and take screenshot of them (You can do that in meshmap)

- [ ] Ensure your screenshot represents the use of a few specific integrations.
- [ ] The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- [ ] Add both Dark Mode and Light Mode screenshots.
- [ ] The screenshot should not be a snippet, take the full screenshot of your browser.
- [ ] Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

**Comment by saurabh100ni** [comment]
Thanks for raising PR, Let's discuss this in the Website call today at 5:30 PM IST.
Please add this as your agenda in [Docs](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

**Pull request closed without merging**
