### PR TITLE
[button] Added 'book demo' btn in navigation bar

### LINKED ISSUE #4956: Need to add **book demo** to Layer5.io
### Description
There are a number of people that book demos so we do need it exposed in [layer5.io](http://layer5.io/), like on the /meshmap page as an example.

### Expected Behavior
We need to add **book demo** to [layer5.io](http://layer5.io/)

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by HarshDeep61034**
**Description**
Added the book demo btn to navigation bar on https://layer5.io

This PR fixes #4956 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 854f981a9541d971d81873efd5b1e2ae9f1b868b at: https://65144bab734c0809cf53a43c--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by HarshDeep61034** [comment]
@abhijeetgauravm plz look into this been so long.

**Comment by abhijeetgauravm** [comment]
hey @HarshDeep61034  I think the PR wasnt discussed in the last website meeting. Let's discuss it on the tomorrow's websites call .
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by l5io** [comment]
🚀 Preview for commit 99cd25f5dd71688a82f712146f297f34d52717b3 at: https://65b3b6dbd0b5be121d1c6c58--layer5.netlify.app

**Pull request closed without merging**
