### PR TITLE
feat: multi mesh

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by chandrashritii** [comment]
**Suggestions** :
- Replace “jungle green” lines
- Add NGINX logo
- Make it non uniform

**Comment by chandrashritii** [comment]
**Suggestions** :

- Go with american date formats (MM-DD-YYYY)
- Expand the margins for all the box images to fit the box width.
- [Books Page] Box Shadow isn’t being applied to the outermost element; isn’t visible. 
- Remove unnecessary padding
- Table on the Landscape page - Add suitable padding
- Increase font size for ‘Service Mesh Timeline’ header

**Comment by Tanuj22** [comment]
Link to check - https://deploy-preview-1291--layer5ng.netlify.app/serviceMesh

**Comment by Nikhil-Ladha** [comment]
I don't think we want to show the sho the animation in case of mobile view, rather just show the complete look as an image. Thoughts?

**Comment by leecalcote** [comment]
@Nikhil-Ladha it's a good question. It would be nice to be able to hang onto the animation in the mobile view. Right now, though, it's a bit small, making it hard to see in mobile.

In its current form, it passes muster for MVP (for go-live), but could do with some improvement later.

**Comment by leecalcote** [comment]
One item to look after is an overlap of the page title with the navbar:

Screen Shot 2020-12-24 at 12 34 36 AM

**Comment by Tanuj22** [comment]
> One item to look after is an overlap of the page title with the navbar:
> 
> Screen Shot 2020-12-24 at 12 34 36 AM

This will be fixed when included in the meshery page. Is @Jashpatel1 working on that?

**Review by leecalcote — APPROVED** [review]
Progress!

**Pull request merged**
