### PR TITLE
fixed newslettersignup overlap

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Fixed the newsletter overlap
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 11d0293042358c1745da4953d15ad80cef0631c8 at: https://60e67a7e70882c6c86c2f375--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Well. You made it look easy.

18F73AC9-EFB7-4E19-B533-0F3EEF857C37

**Review by leecalcote — APPROVED** [review]

**Comment by warunicorn19** [comment]
😅

**Review by Tanuj22 — APPROVED** [review]
Thank you @warunicorn19

**Pull request merged**
