### PR TITLE
Fixed Integration Style For Dark Mode

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**

- Fixed Integration Styling for Dark Mode. 

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eff43d666d79b1d266116a27fe02634b6fda4760 at: https://632b5fb0b7b86f17030dff52--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Some of the logos have too low contrast with the dark mode background.

Screen Shot 2022-09-21 at 5 44 49 PM

**Review by debo19 — COMMENTED** [review]
@Harshit-Dandriyal we have the option of filling svg’s with a different color in both modes right? We can do that for some icons like apple, github, kuma.
 
The background color for pending integrations should be changed as well. They appear to be brighter than the actual integrations in my opinion. Views @sahilsuman933 @Harshit-Dandriyal?

**Comment by sahilsuman933** [comment]
@debo19, we should change the inactive integration design for dark mode. Do you have any suggestions like what we can do about it? 

Also changing the brand icon color doesn't seems right choice to me. We have to look for something else for the contrast issue.

**Comment by Harshit-Dandriyal** [comment]
> @Harshit-Dandriyal we have the option of filling svgs with a different colour in both modes right? We can do that for some icons like apple, GitHub, and Kuma.
>  
> The background colour for pending integrations should be changed as well. They appear to be brighter than the actual integrations in my opinion. Views @sahilsuman933 @Harshit-Dandriyal?

Yes, It has been done in many places.. can also be done here

**Comment by Harshit-Dandriyal** [comment]
> @debo19, we should change the inactive integration design for dark mode. Do you have any suggestions like what we can do about it? 
> 
> Also changing the brand icon colour doesn't seem the right choice to me. We have to look for something else for the contrast issue. 

Yes, Correct but I think we should, some logos such as making the apple logo white which is completely black. Changing colours to make it suitable for our site will surely benefit us, So change some. I think it will be one line code, Rest we will discuss on the website call. 👍

**Comment by l5io** [comment]
🚀 Preview for commit c31a3b6de270b2cc551b880464c2fdc863e4793f at: https://63317093b1a93367463b3459--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bc294901577dbb47cfd78b95bc178c8d18fe068b at: https://633174cf9d1e98008e6442db--layer5.netlify.app

**Comment by leecalcote** [comment]
Progress. Many logos left to address, yet.

**Comment by sahilsuman933** [comment]
It will be updated after today's meeting. @leecalcote

**Comment by leecalcote** [comment]
Ok, ideally, we'll have two copies of the svg - one with "_white.svg" in the filename.

**Comment by l5io** [comment]
🚀 Preview for commit 08a17e341a455d469a32e90761bb532b8b99c14e at: https://633198559c375c069ecb1758--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Progress. More logo updates needed. 👍

**Pull request merged**
