### PR TITLE
[Landscape] Fixed the irregular rows

### PR DESCRIPTION
**Pull request by EmperorYP7**
**Description**

There were some irregularities in the rows due to some weird reason.

This PR fixes #1586 (not really. just for context)

**Notes for Reviewers**

Did I make it in time?

Screenshot 2021-02-21 at 1 57 40 AM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Makes sense. These changes look good.

**Comment by Nikhil-Ladha** [comment]
The base branch should have been master.

**Comment by Nikhil-Ladha** [comment]
> The base branch should have been master.

Also, instead of writing it twice under `tr` , can you check if writing it once under the `td` tage works or not?
And, also use `rem` instead of `px`.

**Comment by EmperorYP7** [comment]
> The base branch should have been master.

Alright. So, shall I create another PR for `master`?

> Also, instead of writing it twice under tr , can you check if writing it once under the td tage works or not?
And, also use rem instead of px.

Sure!

**Comment by Nikhil-Ladha** [comment]
Yeah, with the above changes (if it works).

**Pull request merged**
