### PR TITLE
Updated subscribe form

### LINKED ISSUE #3038: Subscribe form not dark mode friendly
#### Description
Screenshot 2022-08-05 at 9 38 52 PM

#### Expected Behavior
Make the subscribe card dark mode compatible on [layer5.io/subscribe](https://layer5.io/subscribe)

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Shubhcs01**
**Description**
Added primary and secondary colors as recommended to make subscribe form dark mode friendly.

This PR fixes #3038 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✔ ] Yes, I signed my commits.

### CODE REVIEW

**Review by debo19 — CHANGES_REQUESTED** [review]
Can we have the card changed to the darker color used in any other [cards](https://layer5.io/projects) or [form](https://layer5.io/docker-extension-meshery).
Also, will you take a look at this https://github.com/layer5io/layer5/issues/3038#issuecomment-1207490485 ?

**Comment by Shubhcs01** [comment]
> Can we have the card changed to the darker color used in any other [cards](https://layer5.io/projects) or [form](https://layer5.io/docker-extension-meshery). Also, will you take a look at this [#3038 (comment)](https://github.com/layer5io/layer5/issues/3038#issuecomment-1207490485) ?

I have two designs for subscribe card:-

@debo19 @leecalcote any suggestions which design to apply? 
The first one looks nice to me 🙃

First One:

Screenshot 2022-09-01 205059

Second one:

Screenshot 2022-09-01 204825

**Comment by Shubhcs01** [comment]
@debo19  can you also guide me to where this  [#3038 (comment)](https://github.com/layer5io/layer5/issues/3038#issuecomment-1207490485) bug exactly occurs?

**Comment by leecalcote** [comment]
@Shubhcs01, the first one has my vote as well.

**Comment by debo19** [comment]
> @debo19  can you also guide me to where this  [#3038 (comment)](https://github.com/layer5io/layer5/issues/3038#issuecomment-1207490485) bug exactly occurs?

Oh I think it's fixed now, my bad. My vote is for the first design as well.

**Comment by Shubhcs01** [comment]
> > @debo19  can you also guide me to where this  [#3038 (comment)](https://github.com/layer5io/layer5/issues/3038#issuecomment-1207490485) bug exactly occurs?
> 
> Oh I think it's fixed now, my bad. My vote is for the first design as well.

It's okay 🙂

**Comment by l5io** [comment]
🚀 Preview for commit f49607e31b85cce2e39e066187952d9e88e89731 at: https://63111070c71dc54eacbb2991--layer5.netlify.app

**Comment by Shubhcs01** [comment]
Done 👍, Changed the background and also added some spacing between text fields and button.

**Comment by l5io** [comment]
🚀 Preview for commit 9cc0b8e0a31e55677c86c752a045a3a29b79b9d4 at: https://6311177a9c77ef00764de7ed--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 54165d53d56a79b020e5571dcf6b4af0cb53902e at: https://63111f24c2ddc2033a2d2125--layer5.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thank you @Shubhcs01

**Pull request merged**
