### PR TITLE
Problems with Buttons in sistent 

### LINKED ISSUE #5695: Problems with Buttons in sistent
### Description
Buttons in Sistent (specifically in sistent/components/modal) are not properly used.
URL: https://layer5.io/projects/sistent

1. The next button is not shown at the end of Components/Text Input/Code.
2. In Components/Modal there is no **Previous Button**.
3. The **Next button** and **Previous button** not working properly, as per decided in today's meeting **the buttons should only work for switching Tabs**. Currently they also work for switching within a single Tab (for example identity/color/overview to identity/color/guidance). **The switching within single Tab should NOT happen**
4. Buttons does not have preview (they don't show that where the button would lead). 

### Expected Behavior

1. In the end of Components/Text Input/Code, it should have **Next button** .
2. In Components/Modal/Overview there should be **Previous Button**.
3.  They should switch only between Tabs, for example: from identity/color to identity/spacing to identity/typography to components/button.
4. Buttons should have preview (like here https://docs.layer5.io/cloud/). User should know that where the Button would lead.

### Screenshots
Screenshot from 2024-07-22 20-40-10

Screenshot from 2024-07-19 12-29-26
Screenshot from 2024-07-19 12-28-50
Screenshot from 2024-07-19 12-28-08

### Environment:
- Host OS:
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by mannika763**
**Description**

This PR fixes #5695

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5ce6086af990313e5ed4f78d4aaacf7a5026e96a at: https://669c1405710cf52bef257bf2--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
Thanks, @mannika763!

Ideally, this navigation is dynamically driven... @sudhanshutech, @vishalvivekm

**Comment by Muhammed-Moinuddin** [comment]
@mannika763 requirements are updated now. Kindly check it.

**Comment by Muhammed-Moinuddin** [comment]
@mannika763 Are you going to work on the issue with updates within this PR? so I assigned that task (issue) to you.
Otherwise I will close this PR and will assign it to someone else. Kindly let me know.

**Comment by mannika763** [comment]
@Muhammed-Moinuddin 
Thank you for asking. 
I am working on it. will give you an update shortly

**Comment by mannika763** [comment]
Hey @Muhammed-Moinuddin 
I have updated the code but I am not sure about the styling of the buttons. Please let me know if there are any necessary changes.

**Comment by l5io** [comment]
🚀 Preview for commit 4e2dc76658f5eff9b9bf9b62a2ac8d3103260a7d at: https://66a1fcd665ce06c820dcbb91--layer5.netlify.app

**Comment by Muhammed-Moinuddin** [comment]
> Hey @Muhammed-Moinuddin I have updated the code but I am not sure about the styling of the buttons. Please let me know if there are any necessary changes.

Kindly try to follow css of those buttons for font-size, font-weight, button padding. 
Add a bit space between both texts (like inbetween Next and Text-Input -> ). I think opacity of 0.8 will make **Next and Previous texts** more suitable.
Please use icons as well (like we have done on those docs).

**Comment by mannika763** [comment]
Hey @Muhammed-Moinuddin 
I have made some CSS changes. Please let me know what works for you and what doesn't. Additionally, here's how the buttons will look with an opacity of 0.8.
image

**Comment by l5io** [comment]
🚀 Preview for commit 48881ab7e5eadb4eba793454a84f2cc8bb79d2eb at: https://66a3b3aedc39401c7ed57d18--layer5.netlify.app

**Comment by leecalcote** [comment]
@Muhammed-Moinuddin, I wonder if you have additional feedback.

**Comment by Muhammed-Moinuddin** [comment]
> Hey @Muhammed-Moinuddin I have made some CSS changes. Please let me know what works for you and what doesn't. Additionally, here's how the buttons will look with an opacity of 0.8. image

Screenshot from 2024-07-27 03-26-41
Look the above buttons lool like...

**Comment by mannika763** [comment]
Could you please share the link to the documentation for padding and font size? I'm having a hard time finding it.

**Comment by Muhammed-Moinuddin** [comment]
> Could you please share the link to the documentation for padding and font size? I'm having a hard time finding it.

This can help you: https://layer5.io/projects/sistent/components/button
You can simply follow font-size and padding from those docs button. 
We can discuss your issue via Website meeting.
And I can also help via slack huddle.

**Comment by mannika763** [comment]
okay @Muhammed-Moinuddin 
Just to clarify, was the website meeting on Monday? Also, could you please explain what a Slack huddle is?

**Comment by Ashparshp** [comment]
@mannika763.. Yes, you're right about the meeting. The Slack huddle is a feature for video call or voice meeting within Slack for quick discussions...

**Comment by mannika763** [comment]
Hi @Muhammed-Moinuddin 
I've added padding, font size, and font weight. Could you please let me know if there's anything else that needs adjustment? I'll go through it step by step for clarity.

**Comment by l5io** [comment]
🚀 Preview for commit 7fc22a30a6628ec3afb959b3251ad3c364126b5d at: https://66aa5948d596281322069d7d--layer5.netlify.app

**Comment by Ashparshp** [comment]
@mannika763, Failing!!

**Comment by sudhanshutech** [comment]
closing pr since its abandoned

**Pull request closed without merging**
