### PR TITLE
create animated peekin on hover of internship card

### LINKED ISSUE #1809: [Careers] Create animated peek-in on hover of internship card
**Current Behavior**
The internship cards on [this page](https://layer5.io/careers/internships) elevate off the page when they are hovered over.

https://user-images.githubusercontent.com/7570704/115794699-118ef180-a394-11eb-92c0-dae092fd1faf.mov

**Desired Behavior**
Using CSS, it would be nice to add an effect of a Layer5 card peeking in on hover; transitioning in from the right-hand side.

**Mockups**
Untitled-1

**Resources**
- [layer5-cards.svg.zip](https://github.com/layer5io/layer5/files/6361707/layer5-cards.svg.zip)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Thea10**
Signed-off-by: Cynthia <olucynakin@gmail.com>

**Description**

This PR fixes #1809 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 93bd7f40bc7b86c27935f8bc352b3cf31a1440ce at: https://6085b1245f5e74d3502b6a02--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 93bd7f40bc7b86c27935f8bc352b3cf31a1440ce at: https://6085b1c2cf0f870f257ad80b--layer5ng.netlify.app

**Comment by Tanuj22** [comment]
@Thea10 instead of directly on hover the peak card should transition in from the right side

**Comment by Thea10** [comment]
@Tanuj22 yikes, alright will correct that now. Thank you

**Comment by Thea10** [comment]
@Tanuj22 what do you think about this 


https://user-images.githubusercontent.com/25402504/116100283-acddda80-a6a4-11eb-9055-2c6333ad69ea.mp4

**Comment by leecalcote** [comment]
@Thea10 the video doesn't seem to be available.

**Comment by Thea10** [comment]
@leecalcote  how about this?
https://user-images.githubusercontent.com/25402504/116104234-2fb46480-a6a8-11eb-8288-a5c158e3834e.mp4

**Comment by Thea10** [comment]
https://user-images.githubusercontent.com/25402504/116105308-18c24200-a6a9-11eb-9a32-20cec5c1f0d9.mp4

@leecalcote  how about this?

**Comment by leecalcote** [comment]
Thanks. I can see the video now. I'll let @Tanuj22 guide the way, while leaving a couple comments:

- you're really close.
- ideally, the text in the job card becomes left-aligned onhover as the 5 cards should slide in (peek in) from the right and then go back to center when focus of the job card is lost.
- the job card should retain its same animation of elevating off the page.
- users shouldn't see the rightmost edge of the cards in that the cards don't peek in further than that edge. You may want to chop the image/svg so that the card edge is the end of the image. Ask for assistance from @adithyaakrishna, if that would be helpful.

**Comment by Tanuj22** [comment]
@Thea10 looks nice. I agree with all the points Lee pointed out.

**Comment by Thea10** [comment]
alright, I'll work on those. The card still retains the shadow(elevation) when hovered on though, I think the movement makes it less noticeable, I'll probably have to increase the spread radius or darken the color to make it more so.

**Comment by Thea10** [comment]
@leecalcote  @Tanuj22 

https://user-images.githubusercontent.com/25402504/116440064-00d4f480-a848-11eb-94a5-5868b64bc13c.mp4

**Comment by Thea10** [comment]
> @leecalcote @Tanuj22
> 
>  Careers._.Layer5.-.The.Service.Mesh.Company_Trim.mp4 
> ### **hold on on this please**


https://user-images.githubusercontent.com/25402504/116448573-2dd9d500-a851-11eb-88b3-d88a476704fe.mp4

how it looks now @leecalcote  @Tanuj22

**Comment by Tanuj22** [comment]
@Thea10 looks great! Please push the changes

**Comment by l5io** [comment]
🚀 Preview for commit a56077f2fd2a6031b3a97fa3e8eba5a46d765dd3 at: https://6089a4bee1aedf0ff8285816--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Thank you @Thea10

**Pull request merged**
