### PR TITLE
Add a member profile for Prateek Tripathy 

### LINKED ISSUE #853: Recognizing Prateek Tripathy as a contributor
**Current Behavior**
@tripathyprateek a new community contributor.

**Desired Behavior**
A profile for @tripathyprateek should be created and visible on `/community/members`.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

This PR fixes #853 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
💥 @tripathyprateek !

**Comment by leecalcote** [comment]
Ah, geez. I was hopeful that we might shake loose of this guy. :/

**Comment by jesuslerma** [comment]
@tripathyprateek  you can find this your card: https://deploy-preview-879--layer5io.netlify.app/community/members

**Comment by tripathyprateek** [comment]
Really sorry I was not online. This card looks good to me. Really appreciated @chandrashritii

**Review by tripathyprateek — APPROVED** [review]

**Review by jesuslerma — APPROVED** [review]
LGTM!

**Comment by tripathyprateek** [comment]
> Ah, geez. I was hopeful that we might shake loose of this guy. :/

Ah really sorry Lee. I was afk for sometime.

**Comment by chandrashritii** [comment]
Congratulations! @tripathyprateek 

Merging this 👍

**Pull request merged**
