### PR TITLE
SMPS and background floating icons

### LINKED ISSUE #622: [NG] Add service mesh logos
**Description**

Replace the floaters on the `layer5-ng` site landing page with service mesh logos.  

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### LINKED ISSUE #624: [NG] Update SMP logo
**Description**

Update the SMP logo in the `projects` modules. The logo can be found in the [SMP brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smp-brand-kit.zip).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR updates #622 
This PR fixes #624 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I suspect these might be too distracting. We should try reducing opacity and see how that works.

**Comment by Nikhil-Ladha** [comment]
To be honest it's looking a bit weird. Indeed, I was also gonna suggest to use the projects icon that we have, but few more tweaks are needed to make it look better.

**Comment by Jashpatel1** [comment]
@leecalcote This can be merged as of now.

**Comment by Nikhil-Ladha** [comment]
I am changing the description to 'updates' rather than 'fixes'  for the service mesh logos and merging it.

**Pull request merged**
