### PR TITLE
Add CustomTooltip component to the sistent components page

### LINKED ISSUE #5890: [sistent] Add `CustomTooltip` component to the sistent components page
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [CustomTooltip](https://github.com/layer5io/sistent/blob/a930045dd84d8ea45d9026ef1da98d107d66a49d/src/custom/CustomTooltip/customTooltip.tsx).
image

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The CustomTooltip comopnent currently needs this representation.

### Desired Behavior

Proper documentation for `CustomTooltip` component similar to `Button` component on  https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation about the various component props and their expected values
- Code examples for the various variants that a component might have (if any).

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Vidit-Kushwaha**
**Description**

Add CustomTooltip component to the sistent components page

- Added explanation of the function CustomTooltip component and it's usage.
- Code examples.
- Stylistic guidelines to be followed.

This PR fixes #5890 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
image

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ca6e47a2e73316855bb9347bbdb21534c5072311 at: https://6728980406bc4571c4f1e14d--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Vidit-Kushwaha Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). I have added this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by l5io** [comment]
🚀 Preview for commit db8ddacefc17aced1ea1408705b38a9e5f063151 at: https://673191407fd1e3a32746b922--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 44e6effb37991b565f05f424db42d5edceb193fa at: https://673337ef3a86680946bbe083--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Vidit-Kushwaha merge conflict

**Comment by Vidit-Kushwaha** [comment]
@sudhanshutech Resolved

**Comment by l5io** [comment]
🚀 Preview for commit 119854b157ae6dda0c1ec137ae65378e6ff21af8 at: https://6736cd1860d06fe4d2350e33--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Vidit-Kushwaha please update to new structure that you made that is we do not require dir inside pages.

**Comment by l5io** [comment]
🚀 Preview for commit 3d6ce997917eb3257e6d394ba0e1a17f33299389 at: https://6742fce5a50f03719738990c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3bcaf464dd4737321c22f35ef0a4b9833ec91ef7 at: https://67430654e47b0b6f06fcc5cb--layer5.netlify.app

**Pull request merged**
