### PR TITLE
Added the catalog assets.

### PR DESCRIPTION
**Pull request by xiaor2**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 349bd06264e77abd59f7332d4a79fd8baeb19efa at: https://64b5784bcd662a302de3ed30--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
Can you please add the catalog logo as on layer5 home page?

**Comment by xiaor2** [comment]
@goldfishdolphin Sure, but I thought the logo was already here, where do you want to put it?
image

**Comment by goldfishdolphin** [comment]
Can you please add it to the assets ?

**Comment by xiaor2** [comment]
Sure, does this look good to you?
image

**Comment by vishalvivekm** [comment]
@xiaor2 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
Hii @xiaor2 , great work on the PR , 
however the download logo assets point to download all the brand kit 
rather than specifically downloading the sole logo assets

**Comment by leecalcote** [comment]
Thanks for this feedback, @goldfishdolphin and @Ghat0tkach

**Comment by xiaor2** [comment]
Thanks for the feedbacks! I am moving to another apartment these days. And I will work on this soon.

**Review by Rexford74 — APPROVED** [review]

**Comment by xiaor2** [comment]
Hi, I have fixed the link.

**Comment by l5io** [comment]
🚀 Preview for commit 52bee340f739be0f8b9fe518abfcf87f1f8e6e31 at: https://64d058ec8bc4d0290f6513ca--layer5.netlify.app

**Review by goldfishdolphin — APPROVED** [review]
Looking good 👍🏽

**Comment by Ghat0tkach** [comment]
@xiaor2 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

We do have our weekly website meetings at 7:00 AM CT .

**Comment by xiaor2** [comment]
Sure. See you in the meeting!

**Comment by Chadha93** [comment]
@xiaor2 Merge conflicts....

**Comment by Chadha93** [comment]
@ritiksaxena124 All good here? I think @xiaor2 has some feedback to incorporate from last website's meeting....

**Comment by xiaor2** [comment]
Hi, I have incorporated the feedback. Let me know if there is any issue.

**Comment by l5io** [comment]
🚀 Preview for commit d41568aacfa89f451da0bd97f9164f63989e7f66 at: https://64dcfca5580f87094f5e92a6--layer5.netlify.app

**Comment by xiaor2** [comment]
Hi, I met an issue when I ran `make site` after I pulled from the `origin/master`. Does anyone know why this happen?
image

**Comment by l5io** [comment]
🚀 Preview for commit 2ae7cde8f9037ff457a235f4f8f2e626eb0fc8a4 at: https://64dd10b3a04ce10de00ec860--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
Deleting the cache folder may help.

**Comment by xiaor2** [comment]
Thanks! That works. And I made some changes based on the feedback I received from the last meeting. Let me know if anyone has more suggestions.

**Comment by goldfishdolphin** [comment]
> Thanks! That works. And I made some changes based on the feedback I received from the last meeting. Let me know if anyone has more suggestions.

Looking good 👍🏽

**Review by goldfishdolphin — APPROVED** [review]
Great work!

**Comment by ritiksaxena124** [comment]
Looks good @xiaor2, one last change will you increase the size of the icon in the box and do you know why the catalog icons doesn't zoom in like other icons on the page on click?

**Review by ritiksaxena124 — APPROVED** [review]

**Pull request merged**
