### PR TITLE
Project Layout

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR fixes #
The sample project page can be found at siteurl/projects/sample

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Tanuj22 — APPROVED** [review]
LGTM. You will send another PR for showing the projects in the gird-view?

**Comment by Jashpatel1** [comment]
> LGTM. You will send another PR for showing the projects in the gird-view?

Yes

**Comment by leecalcote** [comment]
The project grid looks good. Is there a link to a sample single project view?

**Comment by Tanuj22** [comment]
@leecalcote https://deploy-preview-733--layer5ng.netlify.app/projects/sample. Though it is just a dummy currently

**Review by leecalcote — APPROVED** [review]
Oh, got it. Ok. 👍

**Pull request merged**
