### PR TITLE
Replaced Lee's photo with an image of Five.

### PR DESCRIPTION
**Pull request by nwanduka**
**Description**
What are your thoughts on this image? It's the closest to a community photo of Five that I could find.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c334c1829c19a249684d9a83614a56406cc90689 at: https://658df7fc1f7c2b3b6df0dd0d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a6aed7fbb4aa15493ca4a9143f0815fcf4ceaf2a at: https://658dfd948522cb395c7014d6--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
The quality of the image is not that great @nwanduka,  It's pixelated

**Comment by nwanduka** [comment]
> The quality of the image is not that great @nwanduka, It's pixelated

Yeah, I see what you mean. I'll make it better.

**Comment by l5io** [comment]
🚀 Preview for commit 7ea14796650022c1de62864baec05d7ff8f53e6d at: https://658f26427632d6ecfdeb6f16--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3cb3d4aa0ce3d483b835265e4ded880a4f31f9d9 at: https://658f2a7b313055ee38a63374--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 024324b7689801ac2f1ca0cbbc0d26b88badb9a7 at: https://658f2efc929beaf1df85f694--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
Should we be using SVGs here? // @ritiksaxena124

**Comment by ritiksaxena124** [comment]
> Should we be using SVGs here? // @ritiksaxena124

 Five is a vector and doesn't contain any text so we can use the SVGs.

**Comment by l5io** [comment]
🚀 Preview for commit ebcb5142d717bc78aa8c5bb47a19363ab9147212 at: https://65931365fef25bf6d4f66459--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1492bda5731857bb1a57eec4509b7018f19c5ca0 at: https://659328f252257403714b2fc9--layer5.netlify.app

**Pull request closed without merging**
