### PR TITLE
fix lighthouse `heading-order` test for About page

### PR DESCRIPTION
**Pull request by ayushthe1**
**Description**

This PR fixes the failing `heading-order` test for the about page as seen [here](https://github.com/layer5io/layer5/actions/runs/4226881716/jobs/7340791299#step:6:230).

**Notes for Reviewers**
The changes need to be checked on Safari browser before merging the pr. I'll do that once preview_url is generated.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7b8ca98c508a990d4f1a38927ddda9323e3ea226 at: https://63f3e8ed4618cc3dc6544f53--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5f7fb3f30ed4f4b2639a0bb7bba84b0963957241 at: https://63fca4f4ac0606091872d9c8--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Tested on Safari as well.
Looks good.

**Comment by Nikhil-Ladha** [comment]
A minor change needed here though, i.e, center align the below image.
Screenshot 2023-03-03 at 5 18 35 PM

**Comment by Chadha93** [comment]
@ayushthe1 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 3dd25dd40a5dbbb3e55206163c1425b5edc01a7e at: https://640d9a4fe07b0051ff9bcdf6--layer5.netlify.app

**Comment by ayushthe1** [comment]
Fixed the issue @Nikhil-Ladha

**Pull request merged**
