### PR TITLE
 [Screenshots] Citrix Service Mesh under 'How it Works See It in Action' section

### LINKED ISSUE #4880: [Screenshots] Citrix Service Mesh under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/citrix-service-mesh) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Citrix Service Mesh](https://layer5.io/cloud-native-management/meshery/integrations/citrix-service-mesh) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by coder12git**
**Description**

This PR fixes #4880

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7dd8e37bf7bc4d745f1a5aac0bf86a05468433fe at: https://6519d14e83a64002596757a1--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Let's discuss this Item in today's website call,
Please add it as your agenda if you would:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by coder12git** [comment]
> Let's discuss this Item in today's website call, Please add it as your agenda if you would: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

@abhijeetgauravm but the issue was resolved, i don't think now I have any issue

**Comment by l5io** [comment]
🚀 Preview for commit c8f40af3c8b97dba36e9c50c186a54a14f6fb59a at: https://654badcef3d384683304dd95--layer5.netlify.app

**Comment by sandramsc** [comment]
@abhijeetgauravm  Taking a look at the **Name** section of the **Designe**r tab it appears as though the Light and Dark mode images are not of the same design, to my understanding these need to be the same design just that the lighting changes?

**Comment by saurabh100ni** [comment]
Merge conflict @coder12git

**Pull request closed without merging**
