### PR TITLE
mobile dropdown changes

### LINKED ISSUE #1308: [NG] Site - Mega Menu
**Current Behavior**

The Mega Menu has poor visibility in mobile view.

**Desired Situation**

Add highlights to make it more obvious (Maybe have a shadow or subtle color transitions on either side)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**
Change the hamburger menu icon to an "X" or other to distinguish between open and closed.
Add shadow on the bottom, left and right sides of the menu

This PR fixes #1308 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
These are nice improvements. I forgot to request that the navbar heading be bolded in the mobile view (e.g. **Projects**)

**Comment by Nikhil-Ladha** [comment]
If you could add a small animation effect to the 'X' icon, I think it will even enhance the effect.

**Comment by vineethvanga18** [comment]
@leecalcote  @Nikhil-Ladha is this fine?

**Comment by Nikhil-Ladha** [comment]
Only the cross should animate and not the bars. Or, they both can might be in a different animation😅

**Review by leecalcote — APPROVED** [review]
Thank you, @vineethvanga18

**Comment by leecalcote** [comment]
Thank you, @Nikhil-Ladha

**Pull request merged**
