### PR TITLE
DarkMode: Fixed the flickering of dark mode

### LINKED ISSUE #3060: Flickering of dark mode
#### Steps 
 - switch to the dark mode
 - refresh the page
 - Notice the light mode shows for some seconds before switching to dark mode.

#### Expected Behavior
The flicker shouldn't happen. The dark mode should be loaded upon page load.

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes #3060 

**Notes for Reviewers**
This is a replacement PR for [PR 3972](https://github.com/layer5io/layer5/pull/3972) due to complications with rebasing the branch to resolve DCO issue. It reverts back to the branch state before rebasing with the original DCO issue.

Please refer to [PR 3972](https://github.com/layer5io/layer5/pull/3972) for full description.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Here is the cloned PR (before rebasing) as I mentioned, it is up to date with all issues resolved and the single commit with the DCO issue.

image

This has been a good learning experience, thanks for patiently working with me through this whole process.

Also, please let me know if I should close the other PR.

Thanks,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit da89d4a14a1c9ea14b322996d0bc0c7d0beb5611 at: https://641f32b68d28a967dbdb5931--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit da89d4a14a1c9ea14b322996d0bc0c7d0beb5611 at: https://641f34ed7a2d3169dcfe0692--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Looks good, you can close out the other PR 👍🏼

**Review by Nikhil-Ladha — APPROVED** [review]
LGTM

**Comment by Nikhil-Ladha** [comment]
Theres still a small flash of the text (Date, Author name) in the cards, for ex check the blog page. I guess we just missed out the CSS update there, or some typo.

**Comment by Chadha93** [comment]
@randychilau  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by randychilau** [comment]
Hi Nikhil,

Thanks for finding this. 

> Theres still a small flash of the text (Date, Author name) in the cards, for ex check the blog page. I guess we just missed out the CSS update there, or some typo.

blog_text_flash

I checked the style-component for the Card component, and while it had a transition variable assigned for that text, that variable was not in the themeStyles.js page (it may have gotten lost in the shuffle). I resolved the issue.

blog_text_flash_fix

However, I will do a check to make sure all variables used in the code are present in the themeStyles.js page and then commit any changes.

Thanks,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 3044d18220479ded06c089ae753da9e21b4764a8 at: https://641f633decd1040e9effe996--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for adding this as a topic in tomorrow's Websites meeting, @randychilau 👍 With any luck, MeshMate @Nikhil-Ladha will be in attendance, too.

**Comment by l5io** [comment]
🚀 Preview for commit a929fd394b9656305f6c59745b29fcb609617cc3 at: https://642271b04411ce06861f9e62--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4d443f4ad92e89d7fff0455647dd2c22f875d720 at: https://64231def0dfc5d1b14bcd386--layer5.netlify.app

**Comment by randychilau** [comment]
Hi Nikhil,

Thanks for your message. 

There are methods for adjusting svg files for dark mode ([example]( https://www.ctrl.blog/entry/svg-embed-dark-mode.html)). I will give some of them a try.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
If we have to do it manually for each svg file then that doesn't seem to be a scalable option. And, anyway we would be missing out the images used in `StaticImage` component. So, if that's the case I think we can skip that.

Though, if you find a better approach, I am open to hear that 🙂

**Comment by randychilau** [comment]
Hi Nikhil,

I used a method to resolve the flash, not sure if it is optimal, but might be worth it for the logo svg in the navigation component since it is so prominent for the user.

logo_noflash2

steps taken:
1. created a copy of the svg logo file that changes one of the fill attributes to  "currentColor", which will inherit the nearest "color" setting (layer5/src/assets/images/app/layer5_nav.svg)
2. imported the svg as a React Component "Logo" (via the SVGR package that was already installed)
3. created a styled-component "LogoColorMode" that set the "color" attribute using a transition variable for the original changing colors in light and dark mode (props.theme.whiteToGreen3C494F).
note: in a flex container, a width must be set for the svg element in the css, otherwise it will disappear (got stuck on that for a while).

Thanks,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 3adb953335b399f2642813de77792b376b04acfa at: https://6423805a48f2d31eb8d5b92f--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
> Hi Nikhil,
> 
> I used a method to resolve the flash, not sure if it is optimal, but might be worth it for the logo svg in the navigation component since it is so prominent for the user.
> 
> logo_noflash2 [ logo_noflash2 ](https://user-images.githubusercontent.com/90356410/228389129-58565629-86be-4657-9532-6e2fd002a4f4.gif) [ ](https://user-images.githubusercontent.com/90356410/228389129-58565629-86be-4657-9532-6e2fd002a4f4.gif)
> 
> steps taken:
> 
> 1. created a copy of the svg logo file that changes one of the fill attributes to  "currentColor", which will inherit the nearest "color" setting (layer5/src/assets/images/app/layer5_nav.svg)
> 2. imported the svg as a React Component "Logo" (via the SVGR package that was already installed)
> 3. created a styled-component "LogoColorMode" that set the "color" attribute using a transition variable for the original changing colors in light and dark mode (props.theme.whiteToGreen3C494F).
>    note: in a flex container, a width must be set for the svg element in the css, otherwise it will disappear (got stuck on that for a while).
> 
> Thanks, Randy

Seems like a viable approach, also similar to what we already using for some svgs. Let's go ahead and do this for the SVGs at least.

**Comment by randychilau** [comment]
Hi Nikhil,

> Seems like a viable approach, also similar to what we already using for some svgs. Let's go ahead and do this for the SVGs at least.

Some of the other SVGs on the site using theme conditionals were not as straightforward as the logo svg, so this took longer than expected to implement as I could not find a way to reliably batch the changes and decided to handle each case individually. 

In order to prevent flicker of SVG icons and use styled-components to update the color of parts of the svg in a consistent manner, I ended up doing the following:

1. instead of using `` to include the SVG, convert the svg into a React Component ([via SVGR plugin](https://react-svgr.com/docs/webpack/) already installed), which will inline the SVG into the document.
2. create a copy of the svg file to be used for colorMode changes and add <style> section with class name (e.g. .colorMode1) and add the class to parts of the svg that will change colors with the colorMode change. (note: added configuration setting to [gatsby-plugin-svgr,](https://www.gatsbyjs.com/plugins/gatsby-plugin-svgr/) to allow inline style tags)
3. add to the appropriate styled-component a svg element section with the class name and the fill color using the transition variables in themeStyles.js (note: since SVGR [uses SVGO to prefix](https://react-svgr.com/docs/options/) to classes in SVG files, we grab the generated class for a specific svg that renders (e.g. "integration-image-colorMode_svg__colorMode1") this allows standardization of the class used in the SVG (e.g. colorMode1, colorMode2) and prevent collision with other SVGs)

SVGs not handled:

- As I am new to SVGs and still learning CSS, there were some advance SVG graphics that I left as is (e.g meshmap-bottom-image-dark.svg) since it involved numerous color transitions
- theme conditionals that involved frontmatter objects (e.g. Card component) and other icons retrieved from gql (e.g. IntegrationsGrid.js)

Please review and let me know of any SVGs that are not behaving correctly.

----
Also, not sure why builds are now failing for this , it might have something to do with fullCalendar

image

appreciate any assistance on how to resolve.

----

Thanks,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 14fa2797f14ab742e50eaf9260fda3bec2a88943 at: https://64307d24ae043220c56df283--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Seems fine to me. This will help avoid adding 2 different files (dark/light) versions for each SVGs.

Though, regarding the images fetched using graphql the issue is that earlier we were using an `useEffect` hook that would re-render the component if the `theme` value changes and in turn render the correct image. But, now as that's not the case it is only checking up the initial value that it gets on the very first load which is still the default mode (light for now) and uses only that value. Try using a `useEffect` hook in the `Card` component code and see if that helps or not, I think it should.

As for the more complex SVGs, that could be taken up in a different PR but with an issue opened to list all the exluded SVGs.

**Comment by l5io** [comment]
🚀 Preview for commit 3606070c68bce70ce344a505492fb8a067f5c2f8 at: https://6435c6722d1c6746f307c2dc--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for working with me through this PR, I appreciate you taking the time and effort to review the changes and provide feedback.

> But, now as that's not the case it is only checking up the initial value that it gets on the very first load which is still the default mode (light for now) and uses only that value. 

I believe you were talking about this issue:

example: https://64307d24ae043220c56df283--layer5.netlify.app/blog
darkmode_conditional_images

Where if you refresh the page in dark mode, and you have an image conditional based on color mode, the dark mode image version does not appear.

> Try using a useEffect hook in the Card component code and see if that helps or not

Thanks for the suggestion, I ran into a weird situation where the component started with the default "light" mode, then it correctly re-rendered with the dark mode variables (with and without useEffect), but for some reason the GatsbyImage component would not re-render with the updated dark mode props (and this happened only on refresh, if you change the modes after refresh it would render correctly). 

I tested each step leading up to the GatsbyImage component and everything was re-rendering correctly in response to the dark mode change. I tried using useEffect and other methods to have the GatsbyImage re-render, but was not able to trigger it from refreshing the page. I suspect when the component "rehydrates" the GatsbyImage component specifically has an issue re-rendering with updated props. I would like to hear your thoughts on the issue to understand whether this is a "bug" or I am missing a concept of how Gatsby works.

In the end, not sure if this is a good practice or not, I used the variable `publicURL` as a key for the GatsbyImage component to force the re-render (which is what is returned by the Image component). I also updated the Card component to only update the Image component if there exists a different publicURL for a dark mode version. 

If we want to avoid showing the images changing, then I think we have to do the same thing we did for the dark mode toggle, where we show an empty space until it is resolved.

darkmode_conditional_image_fix

A few notes on these recent batch of commits:

1. resolved merge conflicts (as you mentioned, until THEME.md and CONTRIBUTING.md reflect the changes in this PR, there will be merge conflicts as new pages and content are added to the site)
2. moved the footer to the layout component to be consistent with having "Navigation" in the layout component.
3. moved the layout component from all the pages to the "pageWrapElement", which reduces imports/renders and from [Gatsby](https://www.gatsbyjs.com/docs/how-to/routing/layout-components/) will:

>Gatsby does not, by default, automatically wrap pages in a layout component. The “top level” component is the page itself. As a result, when the “top level” component changes between pages, React will re-render all children. This means that shared components like navigations will unmount and remount. This will break CSS transitions or React state within those shared components.
> If you need to set a wrapper component around page components that won’t get unmounted on page changes, use the wrapPageElement browser API and the SSR equivalent.

4. updated browser API and SSR equivalent as mentioned above
5. noticed that the dark mode transitions on some pages and SVGs were uneven, such as one part of the page changing faster than the other, example:

missing_transition

and so I started adding css transitions (since they are not inherited) to sync with the globalstyle background css transition (transition: 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);), here is the above example with changes:
added_transition_2

This can be done for SVGs and any other section that involves a color transition.

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 2009691a5d3d8b60736e74b126b352f341250c4e at: https://6435da1f3915c1024396bb4f--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Interesting.
How did you try to use the `useEffect` hook? Did you pass a dependency to it, i.e, `theme` in our case?

> I tested each step leading up to the GatsbyImage component and everything was re-rendering correctly in response to the dark mode change. I tried using useEffect and other methods to have the GatsbyImage re-render, but was not able to trigger it from refreshing the page. I suspect when the component "rehydrates" the GatsbyImage component specifically has an issue re-rendering with updated props. I would like to hear your thoughts on the issue to understand whether this is a "bug" or I am missing a concept of how Gatsby works.

Even I am not sure, it shouldn't be the case. Because, if you see the current code it does re-render on a prop change. Though, in the current scenario that was happening because we were using the `theme` prop as a state and updating the state would cause a re-render as per react's semantics. And, now we are just using the return value of the hook, that doesn't trigger a re-render it's the `ThemeProvider` at play here that is causing the `theme` value to change and render new colors on theme toggle.

> In the end, not sure if this is a good practice or not, I used the variable publicURL as a key for the GatsbyImage component to force the re-render (which is what is returned by the Image component). I also updated the Card component to only update the Image component if there exists a different publicURL for a dark mode version.

We shouldn't be using random/changing key values for components it will cause a complete unmount/mount of the component. In this case, we could probably use the `frontmatter.title` value for the key and that should serve the purpose. 
On the other hand, have you pushed `key` change? I can't seem to find it.

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for your message. Apologies for the length of my reply.

As you stated 

>  And, now we are just using the return value of the hook, that doesn't trigger a re-render it's the ThemeProvider at play here that is causing the theme value to change and render new colors on theme toggle.

When the `theme` value provided to the `ThemeProvider` is changed, we can use the `isDark` value from the `useStyledDarkMode` [custom hook to trigger re-renders](https://react.dev/learn/reusing-logic-with-custom-hooks) for conditional situations (like we did with the theme value previously) for the Card component with the `thumbnail` and `darkthumbnail` files. Since the `isDark` value changing causes a re-render, I don't believe it is necessary for a useEffect here.

To show you the re-render propagating through the components, here is an example where the color mode for each component will be displayed. The blog page returns the `Card` component and we add the following code to it:

refresh_rerender1

1. add a conditional text showing what color mode is in the `Card` component
2. pass down the `isDark `value to the `Image` component
3. also create a color mode conditional `alt `value that will be passed to the `Image` component and then passed to the `GatsbyImage` component later

The `Card` component returns the `Image` component which then returns the `GatsbyImage` component to display the image, and we add the following code to the `Image` component:

refresh_rerender2

1. add a conditional text showing what color mode is in the `Image` component from the `isDark` prop value.
2. the alt prop value in the `GatsbyImage` component will be the conditional alt value that was passed down from the Card component.

Here is what happens when we reload a page in dark mode:

refresh_rerender_animated

1. the initial default value (light mode) is displayed for both the Card and Image components.
2. then the isDark value changes triggering a re-render and the conditionals to update to show dark mode statements.
3. notice the image does not update (this is controlled by the `GatsbyImage` component)

Here is a screenshot of the final render for a closer look. The dark mode conditionals work correctly in the `Card` and `Image` components. If you look at the dev console, the image being displayed shows the `alt` value "Light Mode Version", even though the `alt` value that was passed down from the `Card` component to the `GatsbyImage` component was "Dark Mode Version". 

refresh_rerender3

This is why I believe that the GatsbyImage component is not re-rendering correctly even when a prop value to the component itself is changed. 

I am not sure why this is happening, but we are not using the latest versions of Gatsby or gatsby-plugin-image, so maybe it is fixed in later versions. To have this work in the site as it is, we want to force the `GatsbyImage` component to update and display the correct image, which can be done by updating its `key` value.

The reason I chose the `publicURL` value for the key is that it is a value that is already being passed down, and it is different for the two different files we want to display (triggering the re-render). It doesn't have to be `publicURL` used, we can create another conditional value for the key based on the `isDark` boolean value.

Any key value used that isn't different for the two files will not force a re-render. I don't believe the `frontmatter.title` value is different for the two files.

Here is the result using `frontmatter.title` as the key value.

in `Card `component:
image

in `Image` component:
image

frontmatter_key

----

Here is the result using`publicURL` as the key value.

publicURL_key

----

Thanks,
Randy

**Comment by Nikhil-Ladha** [comment]
Thanks for the detailed reply, it indeed might be something wrong with the image plugin.
W can try updating to the recent version in a different PR and see if that helps, or else you can take the lead to open up a new issue under the gatsby repo and report the same.

Anyway, with this everything looks good to me and we should be good to merge the PR. Just some last conflicts around your way.

However, before we do so do you mind listing the items needed to be covered in the next PR? Some I can list right away are:
1. Update the README's
2. Fix complex SVGs for flash
3. Switch to default "Dark" mode by default.
4. Try updating gatsby image plugin to latest version and test it out for rendering issues

**Comment by Nikhil-Ladha** [comment]
@Chadha93 do you mind taking out this latest preview for a spin and see if you could find any issues?
https://6435da1f3915c1024396bb4f--layer5.netlify.app/

**Comment by l5io** [comment]
🚀 Preview for commit 470bafe5df332b85b5a0b317ea508b56cbb4bb89 at: https://6437164d73cfe430b5a7b0ef--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for your reply and help in getting everything to this point.

Regarding the items you listed for the next PR:

> - Update the README's
> - Fix complex SVGs for flash
> - Switch to "Dark" mode by default.
> - Try updating gatsby image plugin to latest version and test it out for rendering issues

If there is an option to have multiple PRs, I think the README's should be a standalone PR and be given priority to minimize the amount of new content contributions that will be outdated by the changes in this PR.

In addition to the items you listed, I would suggest:

- To reduce the theme transition variables, decide on the number of shades of grey (e.g. 6) to use on the site (currently using approx. 50), and look for other ways to consolidate key/values in the theme modes (e.g. text, bodyRevert same as whiteToBlack)
- Cleanup, consolidate, and archive unneeded svg files

Re: gatsby-plugin-image, when there is time, I will try creating a simple example using the latest versions of Gatsby and the plugins to see if it is reproducible.

-----

On a sidenote: I noticed various errors/warnings in the consoles during development that I believe can be resolved without impacting the site. For example: 

image

Does a new issue/PR need to be created for each warning/error, or could they be consolidated into one batch of fixes? Would it be okay for me to create this issue?

Thanks,
Randy

**Comment by Nikhil-Ladha** [comment]
I second the idea if creating individual PRs for each of the items listed above. I just wanted to list out the remaining items so that we don't forget later on.
You can go ahead and create individual issues and let me know, I will assign them to you.

**Review by Nikhil-Ladha — APPROVED** [review]
Great work here, @randychilau 👏🏅

**Comment by Chadha93** [comment]
> @Chadha93 do you mind taking out this latest preview for a spin and see if you could find any issues? [6435da1f3915c1024396bb4f--layer5.netlify.app](https://6435da1f3915c1024396bb4f--layer5.netlify.app/)

Sure.

**Review by Chadha93 — APPROVED** [review]
LGTM, let's do it :rocket:

**Comment by Chadha93** [comment]
@randychilau A merge conflict...

**Comment by l5io** [comment]
🚀 Preview for commit f2e701aff32575c58f0d7b1b4d6bcf20d1e202e9 at: https://643d916a7a3e832a4cc5f1d2--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Let's go then, do we have the issues up and created @randychilau ?

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for your message and guiding this to completion.

I will create the README's issue as that is the highest priority since it affects all new contributions.

Thanks again,
Randy

**Comment by Nikhil-Ladha** [comment]
Done

**Pull request merged**
