### PR TITLE
Add sistent-backdrop-component

### LINKED ISSUE #5904: [Sistent] Add `Backdrop` component to the sistent components page
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [Backdrop](https://github.com/layer5io/sistent/blob/5529c342c6ad2b00b8e8d08deafc02fe72fe5513/src/base/Backdrop/Backdrop.tsx).

(The dark background behind the modal)
image

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The Backdrop component currently needs this representation.

### Desired Behavior

Proper documentation for Backdrop component similar to Button component on https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation of the the function that the component serves in context of it's usage.
- Code examples.
- Stylistic guidelines to be followed while using the component in code (if any).

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 🎨 See [Sistent Repository](https://github.com/layer5io/sistent).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by mdkaifansari04**
**Description**

This PR fixes #5904

**Notes for Reviewers**
Added Sistent Backdrop Component with detailed documentation and easy example

image
image
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 897beb9eb55548e96f61635c9b79c5ed86b8c501 at: https://67326c05f65ba3b3c74abe5b--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@mdkaifansari04 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST

adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by sudhanshutech** [comment]
merge conflicts... and change the structure of page as per new changes made around adding sistent components

**Comment by l5io** [comment]
🚀 Preview for commit bc056cfc5e4a6d760703408808787a6834703a8a at: https://67472f667fd74511781d351d--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Review by Vidit-Kushwaha — COMMENTED** [review]
It looks good to me

**Pull request merged**
