### PR TITLE
fix: media Resources not in center issue

### LINKED ISSUE #5787: Media Resources not in center for small device
### Description
Link: [Company News page](https://layer5.io/company/news)
The heading "Media Resources" is centered on large screens, but it's not centered on mobile screens, which looks odd.

### Expected Behavior
It should be a center for the small screen as well.

### Screenshots
image

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Description**

This PR fixes #5787 

Fix this issue by creating a parent component, making it a flex container, and centering it horizontally. Previously, we used margin for centering, which was causing the issue.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit dd3b72f6f57c5dd69185ba6cc2d0ecf7bccb4890 at: https://66b4b242de61d5f2ae71cc86--layer5.netlify.app

**Comment by Ashparshp** [comment]
@amitamrutiya Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by Ashparshp — COMMENTED** [review]
LGTM! But have you noticed that there's a single `<h2>` tag? Do we really need to wrap it in a `div` with a `className`, or could we go directly? Just a suggestion, not an issue.

**Comment by amitamrutiya** [comment]
Yeah, we can do it this way as well. Let me make changes.

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
