### PR TITLE
Gatsby v5 migration

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Description**

This PR updates gatsby version. Currently it will use legacy peer flag to install packages which can be removed when we upgrade the gatsby plugin mdx after this pr merge.

### 1. Homepage ✅
- [x] layer5.io

### 2. Solutions✅
- [x] Developer-defined Infrastructure
- [x] Cloud Native Deployments by Diagram
- [x] Kubernetes Multi-cluster Operation
- [x] Collaborate with the team.
- [x] GitOps with CloudNative Insights
- [x] Pricing

### 3. Products✅
- [x] Meshery
- [x] Kanvas
- [x] Catalog
- [x] Docker extension
- [x] playground

### 4. Integrations✅
- [x] Each Integrations page 

### 5. Community✅
- [x] Open source projects
- [x] Handbook
- [x] Members
- [x] Newcomers
- [x] Meshmates
- [x] Calendar
- [x] Events
- [x] Recognition program

### 6. Resources✅
- [x] Blog
- [x] Docs
- [x] Learn
- [x] Books
- [x] Workshops
- [x] Learning paths
- [x] Interactive labs
- [x] News
- [x] Announcements

### 7. Brand✅

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e31c993a9910448eae9970eae5ddcc0409d2554a at: https://66fd6dd993a39129aca2c124--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@sudhanshutech 

https://github.com/user-attachments/assets/91a61fa1-18aa-4d08-bc98-486b6d935dc1

**Comment by sudhanshutech** [comment]
@vishalvivekm is everything other looks good?

**Comment by l5io** [comment]
🚀 Preview for commit 7cdd9f83ac7318951c8662889bbd3dc131d3caea at: https://66fe1444cdb31ff4972c0d55--layer5.netlify.app

**Comment by sudhanshutech** [comment]
> @sudhanshutech
> 
>  Mastering.Service.Meshes.For.Developers.-.Google.Chrome.2024-10-02.21-41-32.mp4

@vishalvivekm fixed. Did you able to check each page?

**Comment by l5io** [comment]
🚀 Preview for commit b3d900d0907ed4f79ad71a35e50795ad7e061d1f at: https://66fea20093a391a48da2c0cb--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 862de6096b5e5f452e7a45665eac57b13a050c49 at: https://66feb5871c356fc76663ae85--layer5.netlify.app

**Comment by Aviral0702** [comment]
image
This issue is still there.

**Comment by Aviral0702** [comment]
image
Blogs are not rendered in correct formatting.(3 in a row)

**Comment by Aviral0702** [comment]
Current Behavior on Learn page:
image

Desired Behavior:
image

**Comment by Aviral0702** [comment]
Current behavior on learn/service-mesh-workshops:
image

Desired Behavior:
image

**Comment by l5io** [comment]
🚀 Preview for commit 0181d8a719ad547609b168ef72362ce7acfae9e4 at: https://66fef0b63f7bb213ce079164--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2b24e3866bb4682219c4c5641df5e774bb309e83 at: https://66ff0cac90696c3299a36a74--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8697b7a0363773389ac9958d2d8b5a758b927607 at: https://66ff6d6df506649de91b87a3--layer5.netlify.app

**Comment by Aviral0702** [comment]
1. Homepage
- [ ]  layer5.io

2. Solutions
  - [ ] Developer-defined Infrastructure
  - [ ]  Cloud Native Deployments by Diagram
  - [ ]  Kubernetes Multi-cluster Operation
  - [ ]  Collaborate with the team.
  - [ ]  GitOps with CloudNative Insights

3. Products

  - [ ] Meshery
  - [ ]  Kanvas
  - [ ]  Catalog
  - [ ]  Docker extension
  - [ ]  playground

4. Integrations
 
  - [ ] Each Integrations page

5. Community

  - [ ] Open source projects
  - [ ]  Handbook
  - [ ]  Members
  - [ ]  Newcomers
  - [ ]  Meshmates
  - [ ]  Calendar
  - [ ]  Recognition program

2. Solutions

  - [ ]  Blog
  - [ ]  Docs
  - [ ]  Learn
  - [ ]  Books
  - [ ]  Workshops
  - [ ]  Learning paths
  - [ ]  Interactive labs

**Comment by l5io** [comment]
🚀 Preview for commit 975173a2075bd55ae102a25fbe66415f3988141e at: https://67012b0669b103f0418eab05--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5eb24f4a4da04dbb3e06730880b3315eb375ebad at: https://67018a9717b3a258637139d6--layer5.netlify.app

**Comment by Aviral0702** [comment]
https://67018a9717b3a258637139d6--layer5.netlify.app/company/news
Wrapper issues!!

**Comment by l5io** [comment]
🚀 Preview for commit 2494923b3fbf31533801487ccc47f9949af20f60 at: https://6701901352c2bb5e1c5d3ea7--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8bccfb3cd817df245b7f8c29c7c6db883356d02f at: https://6701b8a5e04bca81a3857dc6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1c3e71d274679cf93aa2dbba3c761e3c72e5acea at: https://670230752e1e5ff4c740956f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 125e59aa01a4bd3db976e1eb6cfbb90b15480f47 at: https://6702386319eadaf65a5f1d4a--layer5.netlify.app

**Comment by sudhanshutech** [comment]
Its good to go now. We can create other separate issues if we find later

**Review by Aviral0702 — APPROVED** [review]

**Comment by Touriist** [comment]
on https://layer5.io/cloud-native-management/kanvas/design

Buttons `Experience context-aware design` and `All Integrations` dont work

##
feature carousel: 



Before: 
Screenshot from 2024-10-06 16-50-08

After: on https://layer5.io/cloud-native-management/kanvas/design
Screenshot from 2024-10-06 16-49-46

**Comment by vishalvivekm** [comment]
@sudhanshutech 

Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Pull request merged**
