### PR TITLE
components/SMI-Table: Add tooltip in Service Mesh Interface Compliance table

### LINKED ISSUE #2140: [UI] Add tooltip in Service Mesh Interface Compliance table
**Description**
Only logos of the service meshes are provided in the Service Mesh Interface Compliance table, names aren't. I think is good to have a tooltip that displays the name of the mesh. 

**Expected Behavior**
When the user hovers on the service mesh logo, it should display the name of the mesh.

**Screenshots**
Screenshot 2021-08-30 at 8 43 18 PM

**Environment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: Chrome

---

[Optional] **To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://layer5.io/service-mesh-landscape'

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by 5hraddha**
**Description**

This PR fixes #2140

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 163ce34c1e972e1b7c237f7d09d1ff52ac7efbff at: https://612d1efaad36b31750338595--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@5hraddha could you please link the issue to this PR like `This PR fixes #2140 `

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Could you please make the Tooltip appear on the left, right now it ends up covering the icon below it.

https://user-images.githubusercontent.com/53532328/131385591-c4f24e15-28fb-4089-b3aa-89a91d4af08e.mov

**Comment by 5hraddha** [comment]
@warunicorn19 Yeah, sure! I would do that. I saw the already implemented tool tips in the table and kept the direction accordingly. But, would make the changes right away. Thank you !!

**Comment by 5hraddha** [comment]
@warunicorn19 Could you please confirm if this is okay? If so, I will go ahead with changes. Thank you!
tooltip-preview

**Comment by warunicorn19** [comment]
Yes, looks good @5hraddha.

**Comment by l5io** [comment]
🚀 Preview for commit ec07f4d182a570325011c3e658b51737ac1ba5d2 at: https://612d26ebd9efcc15e17c6452--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉! Thanks @5hraddha

**Review by Tanuj22 — APPROVED** [review]
Thank you @5hraddha

**Comment by 5hraddha** [comment]
You are welcome @warunicorn19 and @Tanuj22!!

**Pull request merged**
