### PR TITLE
[/projects/nighthawk] aligned images with text on nighthawk page

### PR DESCRIPTION
**Pull request by Oghene-kevwe**
Signed-off-by: Idise Praise <Idisepraise@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@Chadha93 @leecalcote Please approve the workflow 👀

**Comment by l5io** [comment]
🚀 Preview for commit fd3f16fb1d58cae86df4bdfd1700238e09206483 at: https://63aaa41e441cc54c360cc16a--layer5.netlify.app

**Comment by leecalcote** [comment]
Preview ready

**Review by Chadha93 — COMMENTED** [review]
@Oghene-kevwe the change isn't required. It looks odd now. 
image

**Comment by GaganpreetKaurKalsi** [comment]
> https://63aaa41e441cc54c360cc16a--layer5.netlify.app

Agree

**Comment by Oghene-kevwe** [comment]
I have seen the problem, I'll fix it and create a new PR @GaganpreetKaurKalsi  @Chadha93

**Comment by Oghene-kevwe** [comment]
@UtkarshMishra12 @GaganpreetKaurKalsi @Chadha93   I have corrected the bug, please review

**Comment by leecalcote** [comment]
Cool. Re-running the deploy preview workflow...

**Comment by l5io** [comment]
🚀 Preview for commit 4312d16f8b332d618db3e49570b6b2132178d3f9 at: https://63ac89a8684f1f1b699c41bb--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
Good now, LGTM, thank you @Oghene-kevwe :1st_place_medal:

**Pull request merged**
