### PR TITLE
Updated Bart Kalanski's member profile

### PR DESCRIPTION
**Pull request by bartkalanski**
Signed-off-by: Bart Kalanski <bkalanski@gmail.com>

**Description**

This PR updates @bartkalanski community member profile, as requested by @leecalcote by e-mail on December the 7th. 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@bartkalanski Can you revert the changes in package.json and package-lock.json

**Comment by bartkalanski** [comment]
> @bartkalanski Can you revert the changes in package.json and package-lock.json

Yes, I will do now, I'm having trouble figuring out what's gone wrong!

**Comment by Jashpatel1** [comment]
> > @bartkalanski Can you revert the changes in package.json and package-lock.json
> 
> Yes, I will do now, I'm having trouble figuring out what's gone wrong!

Make a fresh pull.

**Comment by bartkalanski** [comment]
> > > @bartkalanski Can you revert the changes in package.json and package-lock.json
> > 
> > 
> > Yes, I will do now, I'm having trouble figuring out what's gone wrong!
> 
> Make a fresh pull.

I'll do that, thank you

**Pull request closed without merging**
