### PR TITLE
Remove {""} from blog 2021

### LINKED ISSUE #4521: [UI]: unwanted {" "} in blog content
### Description

There is unwanted {" "} at couple of parts in the blog post of https://layer5.io/blog/community/meet-the-fall-interns-of-2021

### Expected Behavior

Let's remove them.

### Screenshots

image

image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by k0T0z**
**Description**

This PR fixes #4521 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c94283e13a9dba448cceaf2daba299039315be80 at: https://64ac2c1489f01800b82d0272--layer5.netlify.app

**Comment by k0T0z** [comment]
@leecalcote if u have time for it, please review it. Thanks in advance.

**Comment by samyakshah3008** [comment]
Thanks for showing the passion to contribute @k0T0z but unfortunately this issue is assigned to Namit Arjaria! 
So to avoid conflicting PRs, let's close this. 
Please keep an eye on another good first issues and we are more than happy to assign you!

**Comment by k0T0z** [comment]
yeah thanks @samyakshah3008

**Comment by samyakshah3008** [comment]
Noted @leecalcote ✅ 
I assigned him the task yesterday, will sync up with him to take the updates.

**Comment by samyakshah3008** [comment]
Here is the PR: https://github.com/layer5io/layer5/pull/4526 
@leecalcote

**Pull request closed without merging**
