### PR TITLE
chore: changed meshmap icon to 3-D icon of meshmap

### LINKED ISSUE #4295: [Visual Design] MeshMap hero: 3D logo
### Current Behavior
The [top-level MeshMap page](https://layer5.io/cloud-native-management/meshmap) has a large, flat logo visible in the right side of the hero.

### Desired Behavior
A large, 3D version of the same logo is displayed instead.

### Implementation
1. Generate a 3D rendering for prominent placement on this page.
2. Consider how to ensure that this design is responsive.

### Acceptance Tests
1. Design must relative small in footprint so as to not affect page speed.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Description**

This PR fixes #4295

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8f68561f5cc9da27b270c4ec4ee5b390a48260a3 at: https://64b61ed842d1e22274391c46--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
LGTM @Yana-Gupta  , Good work!

**Review by Ghat0tkach — APPROVED** [review]

**Comment by vishalvivekm** [comment]
👏 @Yana-Gupta 
 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would:)

**Comment by Yana-Gupta** [comment]
> clap @Yana-Gupta Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would:)

Okay, I will add.

**Comment by Ghat0tkach** [comment]
@Yana-Gupta  may I know why did you close this?

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta may I know why did you close this?

@Ghat0tkach I thought to raise another pr for the issue.

**Comment by Ghat0tkach** [comment]
@Yana-Gupta  Oh Okaye  , Well You can do the changes in this PR itself 😅

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta Oh Okaye , Well You can do the changes in this PR itself sweat_smile

Yea, I know but I will raise another for it.

**Pull request closed without merging**
