### PR TITLE
Adding initial structural code for learn layer5

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
This PR updates the gatsby-node.js file to generate a path on the basis of file structure and adds some dummy files to test them.
Used a sample course name, to settle in SEO index for the time being 😎 
Just baby steps towards a bigger goal....

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Few paths for testing:
- /learn/course1/react/en/getting-started
- /learn/course1
- /learn/course2/react/en/introduction

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Yayyyy 🚀🎉

**Comment by l5io** [comment]
🚀 Preview for commit 75fac2257fcd39ff4bd51df3d458171e4d2db5f4 at: https://608ae603021b4a247c76df52--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Now the PR can be merged. I have added the structure of an actual possible learning path `Mastering service meshes for developers`, it will help in SEO for the time being 😄

**Comment by Nikhil-Ladha** [comment]
Paths to test:
- /mastering-service-meshes-for-developers/securing-the-service-mesh/mutual-TLS/istio-lab
- mastering-service-meshes-for-developers/
- mastering-service-meshes-for-developers/securing-the-service-mesh
- mastering-service-meshes-for-developers/securing-the-service-mesh/mutual-TLS
- mastering-service-meshes-for-developers/securing-the-service-mesh/filtering-traffic

**Comment by l5io** [comment]
🚀 Preview for commit a647ffb0f2b23447d39981537dc90e38678b4e08 at: https://608aff9622a3764e713e3ccf--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Yay! :tada:

**Comment by leecalcote** [comment]
The paths work. :

**Pull request merged**
