### PR TITLE
Removed Empty Tag

### LINKED ISSUE #5786: Empty tag found in getting started learn page
### Description
Link: [Learn Getting Started Page](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started)
An empty tag found in step 3 doesn't represent anything.

### Expected Behavior
It should be removed.

### Screenshots
image

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by HrushiYadav**
**Description**

This PR fixes #5786 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cd62bc0cef05dbd4dddbec7bb6e819a97f3ef06e at: https://66bae17ffc8b4ea8a2baff87--layer5.netlify.app

**Comment by Ashparshp** [comment]
Thank you, @HrushiYadav. Please note that we proceed in chronological order with issue assignments. I appreciate your PR, but please ensure you get assigned next time. Are you on our Slack channel? If  not then join please.

**Review by Ashparshp — APPROVED** [review]
LGTM! Thank you @HrushiYadav..

**Comment by Ashparshp** [comment]
@HrushiYadav, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Pull request merged**
