### PR TITLE
[MDX] Migration to gatsby-plugin-mdx v4 (requires migration to MDX v2)

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR is a migration to gatsby-plugin-mdx v4 (which requires [migration to MDX v2](https://github.com/gatsbyjs/gatsby/pull/35650))

**Motivation**: To resolve an issue of imports used in MDX files being added to the app bundle for every page

Unnecessary files in the app bundle adds to the [page weight](https://www.debugbear.com/blog/page-weight-website-speed#:~:text=What%20is%20page%20weight%20or,to%20load%20for%20the%20visitor.)  and can potentially cause slower performance and longer loading times, especially on mobile.

- additional reports:
  >Imports in MDX pages go to the main bundle [#23345](https://github.com/gatsbyjs/gatsby/issues/23345)
  >MDX app bundle bloating and global scope problems [#25069](https://github.com/gatsbyjs/gatsby/discussions/25069)

Gatsby resolves this issue in [gatsby-plugin-mdx v4](https://www.gatsbyjs.com/docs/reference/release-notes/v4.21/#gatsby-plugin-mdx-v4):
>Per-file tree shaking and chunking (No more app.js bundle bloat or global scope problems)
  
---

**Layer5 example**

**before:** 
this file [src/collections/programs/sca-contributhon/index.mdx](https://github.com/layer5io/layer5/blob/master/src/collections/programs/sca-contributhon/index.mdx#:~:text=index.-,mdx,-sca%2Ddark.svg) imports the image `sca.svg`
`import {ReactComponent as ScaLogo} from "./sca.svg";`

when you view the [treemap](https://sia.codes/posts/lighthouse-treemap/#:~:text=Lighthouse%20Treemap%20is%20a%20new,unused%20(execution)%20for%20page%20load) from a recent [lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1687275460264-20216.report.html) for the `/about` page:

image

1. The `sca.svg` is included even though it is not displayed on the `/about` page.
2. The size of the`collection`, much of which shoul not be included in the bundle, is over 300K
image
3. This is a significant percentage (27%) of the page weight 1.28Mb, also notice the amount of `Unused Bytes` which is approx 350kb

**after:**
image

1. The `collection` is significantly reduced and less than 25K 
image
2. The total page weight is also reduced by 15% to 1.088Mb, and `Unused Bytes` is approx. 200kb which is over 40% less.

---

**Notes for Reviewers**

IMPORTANT:
This PR is stable for creating `production` builds, ~~but for `development` builds, it is only stable when including a limited number of mdx files (using [`ignore` option](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#ignore) in `gatsby-source-filesystem`, otherwise there is a [significant memory issue](https://github.com/gatsbyjs/gatsby/issues/36899) in Gatsby v4.~~ **Update**: Development build is stable, but requires more memory to run.

This memory issue in `development` may be resolved in [Gatsby v5 with an upgraded webpack](https://github.com/gatsbyjs/gatsby/issues/36899#issuecomment-1385544620). However as long as we are using Gatsby v4, it is not possible to get support/feedback from Gatsby Dev team on this issue.

While there are benefits to migrating to MDX v2, the time and conditions required for `production` and `development` builds in Gatsby v4 may be too costly to justify migration.

Please note there are multiple aspects of this PR that can be made into separate PRs which do not require upgrading to `gatsby-plugin-mdx v4` or `mdx v2` and merged with the current site, for example:
- mdx file changes for [MDXv2 compatibility](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#updating-mdx-content), this shouldn't change how the file will display in the current site using mdx v1.
- adding eslint settings for MDX to ensure future mdx files will be compatible with MDXv2
- use of Shortcodes to dry/clean up code.
- using the `ignore` option in `gatsby-source-filesystem` to make local dev and production builds faster, as [suggested here](https://paulie.dev/posts/2021/07/gatsby-slow-local-build-times/).
 
(please let me know if the above is a desired action)

If the decision is to archive/close this PR until the site migrates to Gatsby 5 (and React 18) and wants to move to MDXv2, then I suggest adding a comment to the gatsby-config.js file in the "gatsby-plugin-mdx" section about this PR for reference and possible future merging.

---

A OOM memory issue during production builds was resolved using this [github comment/workaround](https://github.com/gatsbyjs/gatsby/issues/36899#issuecomment-1422616312) in the gatsby-ssr.js file.

A memory issue in the development build was worked around ~~by using github comments on [limiting the number of mdx files](https://github.com/gatsbyjs/gatsby/issues/36899#issuecomment-1382369333) included ~~(and possibly [using `gatsby-plugin-no-sourcemaps`](https://github.com/gatsbyjs/gatsby/issues/36899#issuecomment-1403047762). **Update:** reducing the file size of pages built from mdx files helped work around memory issue.

These memory issues may be resolved by migrating to Gatsby v5 because it uses an upgraded version of webpack.

---

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 42bd0bc38856254bb0de92b9459b54baab181eff at: https://64adecf5f993f5589112016c--layer5.netlify.app

**Review by Nikhil-Ladha — COMMENTED** [review]
If the CI works with the plugin changes, then for dev env I would recommned we use the `--max-node-limit` flag instead of bypassing some files, becuase it will unecessaryliy make things difficult for people to build and test their changes locally.

**Comment by l5io** [comment]
🚀 Preview for commit 7e090e2083ac8ae552f4a68c7bda1c55c900e523 at: https://64b378aeb828af7bea8848b0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit eeeb674a4ad39991a5ce934c3532075e4f1e9312 at: https://64b39ac1bebe490aee0a8a28--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks again for taking the time to review this updated PR. It has been extremely challenging to isolate the issues with this migration.

It seems the [rewritten](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#migrating-from-v3-to-v4) gatsby-plugin-mdx v4 is bringing pages created from mdx files into RAM memory when creating a development build(?).

note: This might be resolved in [v5 of the plugin](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/CHANGELOG.md), but the site would have to migrate to Gatsby v5 (and React 18) first [sidenote: is this on the timeline? I would be happy to help with this].

With that assumption about the plugin, the goal was to reduce the file size of pages created from mdx files:
- resizing/optimizing/compressing unusually large files used in one or multiple mdx files 
- removing any large libraries (e.g. simple-react-lightbox) from templates/section components used for mdx files
- adding loadables to below-fold components in templates/section components used for mdx files

Also to address memory issues, I cleared any setTimeouts and eventListeners that could cause a memory leak.

With those changes, I believe it allowed the development build to be functional for general systems.

If you (or anyone else reading this) have the time, please try doing a dev and production build of this branch, and share feedback on if the dev experience has degraded from this migration. My concern is that merging this PR may cause a negative impact to the dev experience.

I understand this PR has begun to sprawl with the addition of the mdx file optimization changes, so feel free to let me know if any part should be a separate PR. I appreciate any feedback and thanks again for the assistance.

Additional Notes: 
- The [`workshop.js`](https://github.com/layer5io/layer5/pull/4528/files) page had changes merged from a recent PR 4528 that removed code that was added in a previous PR 4226 [to clear console warnings](https://github.com/layer5io/layer5/pull/4226/files#diff-ae3a16cc600295e17f1e3a7546c0fddb704a5c17670a97857df960d7c0deb92b). I restored that code in combination with the PR's other changes. Feel free to let me know if the code should not have been restored.
- `layer5-projects.svg` was modified and added to `src/sections/Company/About/index.js` as a SVG, but the size of the file (2.7MB) seemed to be causing build issues, so I replaced it with a high quality webp version that was a smaller file size.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
Hi @randychilau , I understand the concern with the plugin upgrade and apreciate the hardwork that you have been putting in, my question is that earlier you mentioned that by using the `NODE_OPTIONS=--max_old_space_size=4096` flag the dev build was working, so why not stick to that? Since, in the current changes the user would never be able to build a lot of pages if they don't adjust the config manually to include the page in the build process.

Regarding the "Additional Notes", the icons were changed because of CSS issues, if you have to revert them make sure that the icons look good after the revert. It may have been that the inital issue could have been due to cache. So, if everything works fine after the revert, I am fine with it.

**Comment by Nikhil-Ladha** [comment]
Also, I just tested out the branch locally and everything seems to be working fine for me the site build was complete without any issue. What kind of "negative-impact" where you expecting?

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for the feedback. Apologies for some confusion regarding some of your previous contents that I didn't address.

>by using the NODE_OPTIONS=--max_old_space_size=4096 flag the dev build was working

The use of the `NODE_OPTIONS` command was needed in order to get the `production` build working (which has been resolved by the gatsby-ssr.js workaround). The `development` build had no issues completing the build (even though it took much longer with no restrictions). A memory/disk space issue occurred in  the `development` build when attempting to navigate the `localhost:8000` pages. This is why I initially restricted the number of MDX pages included in the development build (restriction was removed in this PR as explained below).

---

>never be able to build a lot of pages if they don't adjust the config manually to include the page in the build process

I [defaulted the `env` setting](https://github.com/layer5io/layer5/pull/4532/commits/578d7e9f9d3f78a8acef2c928d323f896ff2f9fd) for restricting the mdx pages to `false`, so this PR will not require the user to configure anything for full site development. I believe a functional, stable dev build without the restriction was made possible by reducing the mdx page sizes. The setting can still be valuable for those advanced users who understand its usage for faster build time, but happy to remove if felt necessary.

---

> ([from previous PR](https://github.com/layer5io/layer5/pull/4426#discussion_r1243193346) re: eslintrc.js) However, we should enable some things in the lint

Since there has been no linting for MDX files in the past, when I include the settings you mentioned in the `override`, the checklint resulted in many errors:
image

sample errors:
image

I am still confused on how eslint plugins interact with each other, but using the original override settings seems to allow for MDX/JSX linting and compatibility without requiring to open and edit a significant number of mdx files.

---

>make sure that the icons look good after the revert.

Yes, the icons in the [preview](https://64b39ac1bebe490aee0a8a28--layer5.netlify.app/learn) look correct.
image
 
---

>What kind of "negative-impact" where you expecting?

For those with minimum system requirements, my concern was that this PR and migration would cause cold builds to take much longer. For my own system, a cold `development` build with gatsby-plugin-mdx v4/mdx2  took approx. 10 minutes while a cold  `development` build with gatsby-plugin-mdx v3/mdx1 took around 3-4 minutes. This was something I hope would be resolved in a migration to Gatsby v5, React 18, and gatsby-plugin-mdx v5, but I have no evidence of this.

---

Ideally, migration to upgrades should not increase build times and memory/disk space usage. It is possible that the  Layer5 site code in combination with the gatsby-plugin-mdx v4/mdx v2 creates one of the edge cases similar to others ([in this thread](https://github.com/gatsbyjs/gatsby/issues/36899)). This PR does workaround the issues and allow for migration to gatsby-plugin-mdx v4/mdx v2, but I can see why merging would be delayed or never done if the costs in time or dev experience are too much.

Look forward to hearing your thoughts and thanks for taking the time to work on this PR.

Cheers,
Randy

**Comment by leecalcote** [comment]
Whoa, a Lighthouse treemap. 😎

**Comment by l5io** [comment]
🚀 Preview for commit 68ba3a7938ca730961ff169991bc209622e3f474 at: https://64b5e77e0c5e9807769f1c52--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9d94848147d38cf7550d3ff88594470f41e3be9c at: https://64b624a8ba1b8b290e528220--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

The `src/templates/program-multiple.js` page issue caused by the [removal of `mdxrenderer`](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx#updating-page-templates) in gatsby-plugin-mdx v4/MDX v2 has been resolved. 

I don't think there are any further issues with this migration from a usability and page display standpoint.

@leecalcote [provided a report in slack](https://layer5io.slack.com/archives/C015QJKUMPU/p1689627512412749?thread_ts=1689625626.960589&cid=C015QJKUMPU) on the dev experience with this branch. From a timing perspective, cold `development` builds have been affected the most with the time taking around 10min, where warm `development` builds and warm/cold `production` builds take about the same amount of time as before.

I think the `Building development bundle` time during development builds can be reduced by finding ways to optimize files, libraries used in pages built with mdx files (e.g. size dimensions for many images are unnecessarily large).

If there is a decision to merge this PR, I can update the CONTRIBUTING.md doc to manage expectations on the timing of various builds. We can also ask contributors to report any memory issues/crashes.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
Hi @randychilau , I think we are good to go ahead and merge this PR. The time of cold dev build maybe high but that's a one time thing, so we can live with that and hoping to get it fixed in Gatsby v5 (you can take it forward if interested, we don't have any takers for now). Anyway, you have implemented a workaround for worst case scenarios using the `GATSBY_DEV_AMENDED` env variable, so all good here.

Please go ahead and update the CONTRIBUTING guide as needed.
Good work here 🏅

**Comment by l5io** [comment]
🚀 Preview for commit 697d013e6ecc1a12526a004d3831ffed6707960f at: https://64b77eab68eede4ef5ccdc34--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for the kind words. Sounds good, I updated the CONTRIBUTING.md doc with info on the build times in "How to Contributes" section and added guidelines about image filesize & dimensions, feel free to review/edit.

I recently found that any component used for shortcodes in mdx files were added to the general `app bundle` for all pages. So even though the page weight decreased with the bloating issue resolved, it was countered by the components (and related libraries) added via the shortcodes. This seems to be resolved by using loadable to have the shortcode components lazy load in `root-wrapper.js`.

For example, the following data is for the home page:

with PR:
image

current live site:
image

notes:
- I removed the gatsby-plugin-no-sourcemaps to be able to see the treemap in Lighthouse, however then the `production` build started crashing again, so I reinstalled the plugin.
- As more pages and images get added to the site, we'll get closer to the trigger for memory crashes. An optimization audit and clean up of unused files, libraries should be scheduled soon.

---

Regarding the upgrade migration to Gatsby v5, I am interested in helping with this if that is the desired direction. I noticed you were responsible for upgrading the site to Gatsby v4. Do you have any advice for going through this process?

Lastly, thanks for taking the time overseeing and reading through this verbose PR.

Cheers,
Randy

**Review by Nikhil-Ladha — APPROVED** [review]
Looking great, let's merge this and let things settle in.

**Comment by Nikhil-Ladha** [comment]
> Hi @Nikhil-Ladha,
> 
> Thanks for the kind words. Sounds good, I updated the CONTRIBUTING.md doc with info on the build times in "How to Contributes" section and added guidelines about image filesize & dimensions, feel free to review/edit.
> 
> I recently found that any component used for shortcodes in mdx files were added to the general `app bundle` for all pages. So even though the page weight decreased with the bloating issue resolved, it was countered by the components (and related libraries) added via the shortcodes. This seems to be resolved by using loadable to have the shortcode components lazy load in `root-wrapper.js`.

Yeah, I am aware of this. Though, just to confirm did you cross-check if we were importing a component in an incorrect way that is leading to this, or that's just how Gatsby is? I think it's the latter, but WDYT?

> 
> For example, the following data is for the home page:
> 
> with PR: image
> 
> current live site: image
> 
> notes:
> 
> * I removed the gatsby-plugin-no-sourcemaps to be able to see the treemap in Lighthouse, however then the `production` build started crashing again, so I reinstalled the plugin.
> * As more pages and images get added to the site, we'll get closer to the trigger for memory crashes. An optimization audit and clean up of unused files, libraries should be scheduled soon.

I can feel the same too, we might need some optimization throughout the code base in how we are using GraphQL as well.

> Regarding the upgrade migration to Gatsby v5, I am interested in helping with this if that is the desired direction. I noticed you were responsible for upgrading the site to Gatsby v4. Do you have any advice for going through this process?
> 

Well, thanks to Gatsby documentation it makes the process much smoother. Just follow the migration guide, there might be some hiccups due to some extra plugins that we use, but we should be able to get around it some way or the other. Let me know, if something doesn't pan out, we can connect and discuss futher on that.

> Lastly, thanks for taking the time overseeing and reading through this verbose PR.
> 
> Cheers, Randy

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

As you can see, things did not go as planned, and turned into one of my biggest worries as an aspiring developer. Thankfully it was reverted relatively quickly.

What I neglected to consider was that anything involving page creation needs another layer of testing with the `CI` variable set to `true`, since we are customizing the handling of urls for GitHub Pages.

Another misstep was that I should have taken a look at the build logs and tested the netlify site preview, instead of simply trusting the checks passing and my experience with the local production builds. Then I would have:

- seen the `.html.html` in the build logs:
image

- noticed the [redirect loop](https://64b77eab68eede4ef5ccdc34--layer5.netlify.app/programs/gsoc/) in the netlify site preview.

I think what is happening with the gatsby-plugin-mdx v4 when `CI==="true"` is that it is triggering our customized [onCreatePage](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onCreatePage) function which is meant to handle non-mdx sourced pages. This was not the case in v3, and in the doc it says:

>There is a mechanism in Gatsby to prevent calling onCreatePage for pages created by the same gatsby-node.js to avoid infinite loops/callback

The mdx source pages are being created by the same gatsby-node.js so it should not trigger onCreatePage, but perhaps the plugin is doing something different now (it only does this when using `${postTemplate}?__contentFilePath=${node.internal.contentFilePath}` value in the component property, it behaves as previously when only the template is used). 

To handle this trigger in onCreatePage, a conditional check is done to see if the path ends in `.html`, and then it simply returns. This seems to have resolved the issue, but cannot be absolutely sure until it is in a live GitHub Pages production environment. The PR is pending since I had some other missteps with git.

Is there a GitHub Page testing environment that can be used for PRs that involve page creation as a double check before going to live production?

Anyway, hopefully that fix will resolve it and things can move forward.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
A big miss from my end too, should have cross checked the preview :/
Anyway, it seems like the internal working of the plugin has changed as you pointed out and seems to be interferring with how we are handling the trailing slashes.
Thank you for being on top of it.

**Comment by Nikhil-Ladha** [comment]
Regarding the testing env, we created a testing [repo](https://github.com/layer5labs/layer5) long back, probably you can use that.
It uses Github pages to serve the site so we should be able to test it out correctly there itself.

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

The testing repo looks very interesting, a few questions:

- are the settings already configured to publish from a branch? 
- should the master be made current with the live site? or unnecessary?
- what are the steps for uploading/merging a PR to it for site preview viewing?

>Structure of pull request previews:
>
>https:layer5labs.github.io/layer5/<pr#>

I think this would be very useful for changes to gatsby-node.js involving page creation/redirects/urls.

Thanks,
Randy

**Comment by Nikhil-Ladha** [comment]
The site is already configured to build from Github pages, so once I merge your PR in the repo you should be able to see the same on the hosted site.
We don't have a preview mechanism as such in the repo.

**Comment by leecalcote** [comment]
Ah, geez. I was to help, but time got away from me. Did we end up getting @randychilau's PR/commits reopened?  Is that what this PR is?

**Comment by leecalcote** [comment]
Maybe it's evident or has already been discussed, but outside of local builds, deployment previews are build each time that a PR is opened and each time that a new commit is pushed to an open PR.

**Comment by leecalcote** [comment]
Oh! Gotcha. Great suggestion, particularly, since @Nikhil-Ladha is quite adept at X-Robots-Tag: noindex. 😄

**Comment by randychilau** [comment]
@leecalcote No problem, I appreciated the quick response and offer to help. Thanks to a blog post on git reverting reverts, I was able to get another PR set up (#4585) for review.

Regarding previews, I thought for PRs that specifically interact with the trailing slash customizations for GitHub pages, an option to test a preview served by GitHub Pages may be useful (since the current site previews in GitHub Actions are served by Netlify).

---

@Nikhil-Ladha When you can, please merge the PR to the testing repo to see it in action.

I can also update the CONTRIBUTING.md "Developer Notes" section with some language about this repo being available for additional testing of certain PRs and asking a maintainer for additional assistance/more information.

Thanks!

**Comment by Nikhil-Ladha** [comment]
> @leecalcote No problem, I appreciated the quick response and offer to help. Thanks to a blog post on git reverting reverts, I was able to get another PR set up (#4585) for review.
> 
> Regarding previews, I thought for PRs that specifically interact with the trailing slash customizations for GitHub pages, an option to test a preview served by GitHub Pages may be useful (since the current site previews in GitHub Actions are served by Netlify).
> 
> @Nikhil-Ladha When you can, please merge the PR to the testing repo to see it in action.
> 

Sure, some more changes are required in the repo before the testing because of the repo confiuration like adding a `prefix` to the gatsby-confg. I am a bit occupied as of now, so do you mind testing it out yourself? If so, signal me here and I would grant you merge permissions to the repo and you can test it out by mergeing the changes directly and testing out. No PR previews are available there, sorry 😓 

> I can also update the CONTRIBUTING.md "Developer Notes" section with some language about this repo being available for additional testing of certain PRs and asking a maintainer for additional assistance/more information.
 
I would let it be a _secret_, and only grant access to special scenarios :)

> Thanks!

**Comment by randychilau** [comment]
@Nikhil-Ladha Sure, please grant me merge permissions and I can try testing it out myself (at least if I start a 🔥 on this site, it won't required emergency assistance  🚒  🧯). Thanks for taking the time!

**Comment by Nikhil-Ladha** [comment]
Cool, sent you the invite.
For your ref: https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/ this is what I am talking about.
Check the deployment link under `Settings` tab of the repo, if in case it is not showing here's the link: https://layer5labs.github.io/layer5/

**Pull request merged**
