### PR TITLE
Recognizing Rodolfo Martínez as a Contributor and Community Member

### PR DESCRIPTION
**Pull request by OlushesiToheeb**
Signed-off-by: olushesitoheeb <olaolushesi98@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — APPROVED** [review]
Looks good to me. @leecalcote can you confirm the details?

**Comment by leecalcote** [comment]
+ @ramrodo

**Review by leecalcote — APPROVED** [review]
Looks real good. 👍

**Comment by ramrodo** [comment]
@leecalcote looks good 👍🏼

**Review by leecalcote — APPROVED** [review]
Thank you, @OlushesiToheeb. 😄 Nice!

**Comment by leecalcote** [comment]
There it is, @OlushesiToheeb! 🥇 🎈

**Comment by OlushesiToheeb** [comment]
Thanks guys am glad, Looking forward to more contribution

**Pull request merged**
