### PR TITLE
Added Contributor Journey Map to About page

### LINKED ISSUE #2196: [Handbook] Add Contributor Journey Map to About page
**Desired Behavior**
Under the **Newcomer's Path** section on this page (https://layer5.io/community/handbook/about), add the contributor journey map as shown on https://layer5.io/community/newcomers.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by YashKamboj**
**Description**
Added the contributor journey map as shown on https://layer5.io/community/newcomers , under the Newcomer's Path section on this page (https://layer5.io/community/handbook/about)
This PR fixes #2196 

**Notes for Reviewers**

Screenshot (91)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@YashKamboj look like you forgot to sign-off your commit, try following this to sign-off now:https://github.com/layer5io/layer5/pull/2223/checks?check_run_id=3724627701, or if you don't have a signoff configured, try going through this: https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by YashKamboj** [comment]
> @YashKamboj look like you forgot to sign-off your commit, try following this to sign-off now:https://github.com/layer5io/layer5/pull/2223/checks?check_run_id=3724627701, or if you don't have a signoff configured, try going through this: https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

Yeah done, thank you for reminding me .

**Comment by l5io** [comment]
🚀 Preview for commit 72ce786995b98b7d5dc56406d9c0561509ccec64 at: https://615222204c6d86a681aec09c--layer5ng.netlify.app

**Review by warunicorn19 — COMMENTED** [review]
@YashKamboj these changes look great😄! Thanks for this. But, there is a slight content change on this page, which is being tracked in #2200, so let's hold off on merging for now. We'll merge after the other PR goes through.

**Comment by YashKamboj** [comment]
> @YashKamboj these changes look great😄! Thanks for this. But, there is a slight content change on this page, which is being tracked in #2200, so let's hold off on merging for now. We'll merge after the other PR goes through.

Ok no worry.

**Comment by warunicorn19** [comment]
Hey @YashKamboj, that other PR has been merged, could you just resolve the merge conflict, then we can merge this.

**Comment by warunicorn19** [comment]
You'd basically have to go here https://github.com/layer5io/layer5/pull/2223/conflicts and merge the master here.

**Comment by YashKamboj** [comment]
> You'd basically have to go here https://github.com/layer5io/layer5/pull/2223/conflicts and merge the master here.

How do i do that , the thing is i am not good at git , so can you please help.

**Comment by warunicorn19** [comment]
@YashKamboj no problem, I've resolved it.

**Comment by l5io** [comment]
🚀 Preview for commit a3d6500006f8aa5685076bd7c3302e19c113e658 at: https://61536ed383ee982fa1ce3118--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
@warunicorn19 thank you very much.

**Comment by YashKamboj** [comment]
Hey, @warunicorn19 , i really want to contribute but couldn't find issues ,would you share some repos , it would be really helpful .

**Comment by warunicorn19** [comment]
@YashKamboj you could take a look at this issue https://github.com/layer5io/layer5/issues/2153, I don't think the people assigned are working on it.

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, good work on this @YashKamboj

**Comment by YashKamboj** [comment]
> LGTM🎉, good work on this @YashKamboj 

Thnx

**Pull request merged**
