### PR TITLE
Fixed font colour of statement box in dark mode

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**

Screenshot from 2023-02-03 05-40-51

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Harshit-Dandriyal** [comment]
Screenshot from 2023-02-03 05-55-30
Screenshot from 2023-02-03 05-55-46

**Review by leecalcote — APPROVED** [review]
We didn't have a matching color in the theme for #fafafa, huh?

**Comment by l5io** [comment]
🚀 Preview for commit beec19f0e3dd15a3139fdddd7f45281b8fb593d0 at: https://63dc5fa41fe9396b1e02d12f--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
Adding correct and exact inversion opacity.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
