### PR TITLE
Integration Count on meshmap design page updated. 

### PR DESCRIPTION
**Pull request by saaagarsingh**
**Description**
Meshmap integration count was outdated. It is now updated and can be updated dynamically as the value changes.
This PR fixes #
fixes: #4666 
**Notes for Reviewers**
Before:
IntegrationCountBefore

After:
IntegrationCountAfter

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 42987517593cc1a1eaf5c8a46c3651640cd5a92b at: https://64c93219e29b4c3ee77f96a2--layer5.netlify.app

**Review by samyakshah3008 — COMMENTED** [review]
Pretty good work @saaagarsingh ✅

**Review by samyakshah3008 — APPROVED** [review]

**Comment by Ghat0tkach** [comment]
hey @saaagarsingh 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by thisiskaransgit — APPROVED** [review]
@saaagarsingh Looks good to merge, thank you for your contribution :tada:

**Comment by leecalcote** [comment]
Sweet!

**Pull request merged**
