### PR TITLE
Updated sections on homepage

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
This PR
1. Replaced SVGs with PNG embedded with complete SVGs
2. SVG colors are now adaptable with theme
3. Added highlighted text in the section heading

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ea7a40fda3f5d3d71c891fbba9fdd26d7f0bee1e at: https://657c4f92c6eaed0fdc44910d--layer5.netlify.app

**Comment by leecalcote** [comment]
The new images are so very worth your time spent. This is a dramatic improvement, @ritiksaxena124.

I'm afraid that the new word highlight looks too similar to our close at-hand button, however.

**Comment by leecalcote** [comment]
@ritiksaxena124 will you also revert the size allocated to the images vs text? The text is disproportionately provided a smaller space such that it becomes a little too columnar.

**Comment by leecalcote** [comment]
Is Harry Turner a long-haired dude or a mis-labeled gender?

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 will you also revert the size allocated to the images vs text? The text is disproportionately provided a smaller space such that it becomes a little too columnar.

Sure, I will update the sizes 👍

**Comment by ritiksaxena124** [comment]
> Is Harry Turner a long-haired dude or a mis-labeled gender?

I used it randomly 😅

**Review by leecalcote — CHANGES_REQUESTED** [review]
@ritiksaxena124 the two avatars are still PNGs.

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 the two avatars are still PNGs.

Ohh I got it what you mean by Harry turner comment 😅. 

Other than avatars nothing is png I guess. I will check and update

**Comment by l5io** [comment]
🚀 Preview for commit 081a9cad20d1df96a701174ce8d7169f4dc475bb at: https://657c58ae02230b135c6086d2--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 10b160c00f535ace93b1dbdef38d2a47299ac13e at: https://657caac3b0fbca26d47b5ea9--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cd973c726a346100eec2d4be5d729705ad06eea9 at: https://657caf73e9642c29ff9d765a--layer5.netlify.app

**Pull request merged**
