### PR TITLE
feat: set up redirect plugin

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <tanujagarwal22@gmail.com>

**Description**

Add and Configure redirect plugin 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
An example redirect - https://deploy-preview-897--layer5ng.netlify.app/blog/2019-07-09-getting-started-with-Meshery-WSL2-k3d/

**Review by Jashpatel1 — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Can you explain a bit about this plugin? @Tanuj22 
I didn't quite get it, how the redirect is working.

**Comment by Tanuj22** [comment]
@Nikhil-Ladha it is mentioned here https://www.gatsbyjs.com/plugins/gatsby-redirect-from/. Basically, it states that it creates server-side redirects without affecting the SEO.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha it is mentioned here https://www.gatsbyjs.com/plugins/gatsby-redirect-from/. Basically, it states that it creates server-side redirects without affecting the SEO.

Ohh, got it. That was nasty url change. Didn't caught my eye😆

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
