### PR TITLE
Height fix

### LINKED ISSUE #4542: [Bug]Non-uniform height when hovered
### Description

in the [handbook](https://layer5.io/community/handbook) page , whenever we hover the elements the following disturbance occurs

https://github.com/layer5io/layer5/assets/59855919/3921c9e7-89d1-457e-a810-bfbd543052ca

### Expected Behavior

I have done the following changes to resolve the bug

## Fix 1 : With scale property  

https://github.com/layer5io/layer5/assets/59855919/fe3efe0b-664a-4afb-9652-726be5a5f0db

##  Fix 2 : Without scale property 

https://github.com/layer5io/layer5/assets/59855919/3b2f1c4f-4b60-44e8-a6bd-04fcdb94be84

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #4542 

**Notes for Reviewers**
This PR fixes the current disruptive increased height on hover in handbook overview page
Following are the changes made ;

- [x] Replaced height increase with scale property on hovering
- [x] Positioned the ''read-more'' button according to the current change

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d04bc6cc91e998868eb7f360460f614fd17b6cf5 at: https://64b271fa8ca8dd741832a8f4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3d4cf4f9536420f92fcde5687ac84399c3887634 at: https://64b275869a72cb7608efde57--layer5.netlify.app

**Review by DarrenDsouza7273 — APPROVED** [review]
LGTM @Ghat0tkach

**Comment by vishalvivekm** [comment]
@Ghat0tkach 
Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Pull request merged**
