### PR TITLE
Rearranged order of text and images in mobile view of About section

### LINKED ISSUE #4640: [About] Rearrange order of text and images in mobile view
### Description 

On the About page ( layer5.io/about), text and images are not interleaved. Instead, long walls of text followed by multiple adjacent images are shown.

### Expected Behavior
interleave text and images one after the other. 

### Screenshots

https://github.com/layer5io/layer5/assets/7570704/b723255c-16fd-46a8-ae2a-e6f618c34bc0

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**
Rearranged order of text and images in mobile view of About section

This PR fixes #4640 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 86d38a6d195104096083de4da497aa3d5b05f76f at: https://64d765c8763dcc7321250b5c--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
hey @ShravaniAK Please do sign off your commits as DCO check is failing!

**Comment by ShravaniAK** [comment]
Yes @abhijeetgauravm , i forgot to sign off the second commit

**Comment by l5io** [comment]
🚀 Preview for commit 908627f7dee12672b5cfd2a93f064444ea627ca1 at: https://64d84ba895284a5a95743a4a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 02048fe2c4d6177961b9038b12a82a8aa4194a2a at: https://64d85a1d2fce3c5e681942bd--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @ShravaniAK 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by leecalcote** [comment]
@ShravaniAK please double-check in mobile view. There should be text - image - text - image alternating, so no two images / styled sections should be adjacent to one another and no two text sections should be adjacent to one another.

**Comment by ShravaniAK** [comment]
Ok @leecalcote , got it , I'll push the changes within few hours

**Comment by l5io** [comment]
🚀 Preview for commit c25867f47061f1266445f9c13e188e12451f77bb at: https://64db0c24415966254018f3fe--layer5.netlify.app

**Comment by ShravaniAK** [comment]
@leecalcote please let me know if there are more changes to be done .

**Review by Chadha93 — APPROVED** [review]
Good work here @ShravaniAK

**Pull request merged**
