### PR TITLE
AWS page hero image size and transition update

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**

image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3957119fc10cd3f4f8355e7e0325d8aa6768ce25 at: https://6585bd31e78d19e92ac17ff0--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
@iArchitSharma, Instead of using the current layout for the hero section. I wonder if we should use the layout that we have on the whiteboard or the commenting page because the graphic is more visible in that layout and the current layout has many CSS issues for different window sizes.

image

**Comment by iArchitSharma** [comment]
@ritiksaxena124 Yes, the layout on https://layer5.io/whiteboard is really good, and a plus point is its responsiveness. I think we should go with it.

**Comment by l5io** [comment]
🚀 Preview for commit 41d37a7e3be04bc96244a3f06a61bc0262eeca58 at: https://658701c91eb607a0fac8b2f6--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@ritiksaxena124 implemented new hero section

**Comment by l5io** [comment]
🚀 Preview for commit 260ba86064d53fcdd0e93f97198c310ed133edac at: https://65871d5158d63aad8920ba9b--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @iArchitSharma  Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by ritiksaxena124** [comment]
It looks good 👍, please add the same style to the GCP page as well @iArchitSharma

**Comment by iArchitSharma** [comment]
@ritiksaxena124 done!

**Comment by l5io** [comment]
🚀 Preview for commit fae0f379a37b7f11e8dc2f3854dbc387a0b03498 at: https://658a67f838826a5fc1269cc9--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Will you make sure @iArchitSharma that the hero image starts its animation when it touches the navbar?

**Comment by iArchitSharma** [comment]
@ritiksaxena124 Done!

**Comment by l5io** [comment]
🚀 Preview for commit 4d18b2505156ba0a9938c02e130c356972b75853 at: https://658b22533098facf35d5c0f1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 52bf2376c41339b02635982cba2fd7779fd88126 at: https://658c8f0d6b80c831589a7d62--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8c5bbc8ac46c2fca2f626f372d3d9f1f8d63b312 at: https://658d5d4bb5ce80a651ee53a9--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0a76a5442694b68fc6e3a3ae89b34af6ae286e8d at: https://658d7baec10e81009ba47835--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bd25be90e1d514fb65e344c8213d5262db306fdb at: https://658d8618583e3c092d06cf1d--layer5.netlify.app

**Comment by leecalcote** [comment]
Please be aware of the odd and delayed affect on reverse (on scroll back to the top).


https://github.com/layer5io/layer5/assets/7570704/be0f5c0f-6611-4775-bc6c-19180e1bf6b7

**Pull request merged**
