### PR TITLE
Update animations direction: from top to bottom to bottom to top

### LINKED ISSUE #5344: [UI] Add animations to a section
### Current Behavior
When the site loads we show all the content at once and there are not many animations for different components/sections of the site pages.

### Desired Behavior
Add animations to the section shown below screenshot [present on the homepage of layer5.io]. 
See the [site1](https://www.rejouice.com/) or [site2](https://brainboard.co/) for inspiration on what animation we can use.

image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ashparshp**
**Description**
Update animations direction: from top to bottom to bottom to top

This PR fixes #5344

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@iArchitSharma Please have a look and help me..

**Comment by l5io** [comment]
🚀 Preview for commit 018b8dfede40a7f082571833b28c3357a4aa6bd6 at: https://65ca0f5ecd4bfbe08a307077--layer5.netlify.app

**Comment by Ashparshp** [comment]
@saurabh100ni I'm unable to get what's wrong.. Please help me and also tell where am i making the mistake?

**Comment by l5io** [comment]
🚀 Preview for commit 4fca5f9f1b97619bb893118a452a52dc55579f4f at: https://65ca1992722bc9e3456e67db--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@Ashparshp Always remember to to sign off your commit `git commit -s` otherwise the DCO check will fail

**Comment by Ashparshp** [comment]
I followed the procedures but still.. May I have made a mistake.. Now, what to do?

**Comment by iArchitSharma** [comment]
@Ashparshp, no problem. I've fixed the check. You can now focus on the issue you are working on

**Comment by Ashparshp** [comment]
Screenshot_2024-02-13-19-42-44-086_com android chrome~2

@iArchitSharma, Can I click on update the branch since it's showing as out of date with the base branch? Also, to get it ready for review.

**Comment by iArchitSharma** [comment]
@Ashparshp yes you can, but always do `git pull` locally once you update branch

**Comment by Ashparshp** [comment]
I'll keep in mind!

**Comment by l5io** [comment]
🚀 Preview for commit 3a5e6dd3f26eebf5d2890109fe576a29f0a743a5 at: https://65ce28918e1349213941a144--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Hi @Ashparshp  ,
Thanks for your PR! I encourage you to share this in the Website Meeting on Monday at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by l5io** [comment]
🚀 Preview for commit 555d2a1fdee58d94a2a6db0002b246d85611065c at: https://65d4593c472a4097640aeff9--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@Ashparshp are you still working on it?

**Comment by Ashparshp** [comment]
@iArchitSharma Apologies for the delay in response. Yes, I'm still actively working on it. I'll create a new PR for the inview animations shortly.

**Comment by iArchitSharma** [comment]
@Ashparshp No updates??

**Comment by Ashparshp** [comment]
@iArchitSharma Sorry for being inactive; exams, projects, and assignments have been keeping me busy. I'll be available by 12 once my exams are over tomorrow.

**Comment by iArchitSharma** [comment]
@Ashparshp are you still working on it?

**Pull request closed without merging**
