### PR TITLE
feat: decrease font sizes for smaller screen 

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Are most of these sizes taking effect only on mobile or do these style updates affect desktop as well?

**Review by leecalcote — DISMISSED** [review]

**Comment by Tanuj22** [comment]
> Are most of these sizes taking effect only on mobile or do these style updates affect desktop as well?

The sizes for desktop were done in #1326 by @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Could you fix the unwanted padding in the banner for mobile view and the width of Layer5 icon on the nav bar as well, in this PR?

**Comment by Nikhil-Ladha** [comment]
Also, remove the font-size defined for the home page headings.

**Comment by Nikhil-Ladha** [comment]
Screenshot from 2021-01-02 12-37-07
The text should be `with` -> `as`.

**Comment by Tanuj22** [comment]
> Could you fix the unwanted padding in the banner for mobile view and the width of Layer5 icon on the nav bar as well, in this PR?
> 
> P.S: I just noticed the icon is fixed in this PR, but the padding is left.

I didn't make any changes to the homepage as it will be changed according to a new design (including the banner)

**Comment by Tanuj22** [comment]
> Screenshot from 2021-01-02 12-37-07
> The text should be `with` -> `as`.

Done!

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
