### PR TITLE
Added DevOps Infographic | CU-3t4x2vr

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
New Resource: Infographic

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-3t4x2vr DevOps Adoption Infographic](https://app.clickup.com/t/3t4x2vr)

**Comment by leecalcote** [comment]
The image size seems to be larger than the pdf. We might need to reduce the image size / quality.

**Comment by l5io** [comment]
🚀 Preview for commit 2e3a4aedd1a94413cb19b7ca0960bc2023c08206 at: https://630412870408dc1e45193fbd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7f3dfec09be9622b810d8bafc3898898b3e04112 at: https://6304bcd343c1b76ccb8d828c--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Nice

**Pull request merged**
