### PR TITLE
Fixed Service Mesh Interface Compliance table horizontal scroll

### LINKED ISSUE #3826: Unable to horizontal scroll 'Service Mesh Interface Compliance' table in mobile device
### Description

While using a mobile device the Service Mesh Interface Compliance table isn't scrolling and we cannot see the columns to the right.
on the page [https://layer5.io/service-mesh-landscape](https://layer5.io/service-mesh-landscape)

### Expected Behavior

The table should scroll towards the right to view the rest of the columns.

### Screenshots

https://user-images.githubusercontent.com/88512639/221382563-9c90bd83-5acf-49e1-aa47-86945bea4c44.mp4

### Environment:
- Host OS: Android
- Browser: Chrome

I am working on this issue

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by divz-codess**
**Description**
This commit fixes horizontal scroll issue of Service Mesh Interface Compliance table due to which it was not able to be scrolled. 

This PR fixes #3826 

**Notes for Reviewers**
Img

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@divz-codess thanks. You'll want to take some time to get your get commit sign off, set up permanently configured. There are instructions for doing so in the contributing guide.

**Comment by leecalcote** [comment]
Here are the commands you can run to sign off on your commits in this PR: https://github.com/layer5io/layer5/pull/3902/checks?check_run_id=11776073964

**Comment by l5io** [comment]
🚀 Preview for commit 5a9eb1ffa07657ea69002ffc7fcc8ab8c91afb03 at: https://6404f69840c48f51a73aded4--layer5.netlify.app

**Comment by divz-codess** [comment]
> @divz-codess thanks. You'll want to take some time to get your get commit sign off, set up permanently configured. There are instructions for doing so in the contributing guide.

Sure will do. @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit 0bc5a2cd358fca9f8231d4b78573aa84659b8b6c at: https://640799b2946822191737fad8--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f43001c1e1c286806f277614f0a80ad4070f260b at: https://64082f34ac196d6d796243ff--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c5ac2b10efd89dae8456184ab1ac748ac371975f at: https://6408dc350e2b22033621951b--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Still stuck on the DCO issue?

**Comment by divz-codess** [comment]
> Still stuck on the DCO issue?

Yeah, idk why it's failing still even though I have signed my commits. Although the issue is fixed you may please review it. @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Doesn't seem signed to me. Please follow the steps mentioned [here](https://github.com/layer5io/layer5/pull/3902/checks?check_run_id=11860424734) to resolve it

**Comment by divz-codess** [comment]
> Doesn't seem signed to me. Please follow the steps mentioned [here](https://github.com/layer5io/layer5/pull/3902/checks?check_run_id=11860424734) to resolve it

Done @Nikhil-Ladha

**Comment by divz-codess** [comment]
> Seems like the PR has a lot of unrelated changes now, probably an incorrect rebase?

Yeah maybe, so what can I do now to fix it? please suggest

**Comment by Nikhil-Ladha** [comment]
> > Seems like the PR has a lot of unrelated changes now, probably an incorrect rebase?
> 
> Yeah maybe, so what can I do now to fix it? please suggest

Reset your head to the last correct commit and then force push.

**Comment by Chadha93** [comment]
@divz-codess  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Chadha93** [comment]
Merge conflicts. @divz-codess Has stepped away due to school. Let's close this and Reassign the issue.

**Pull request closed without merging**
