### PR TITLE
Designed Kubernetes image dark mode compatible

### LINKED ISSUE #4712: 'Kubernetes Service' between service interface and pod isn't visible
### Description

'Kubernetes Service' between service interface and pod isn't visible in dark as well as light mode.

### Expected Behavior

It should be visible.
### Screenshots

image

image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Description**

This PR fixes #4712 

**Notes for Reviewers**
Before :
image

After :
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4e092709b7556bf1e8874132fa41af509d07306c at: https://64d5ae75bea8f5206a01c96e--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Looks Great to Merge @VivekBaldha0712, Thank you for Contributing to Layer5 🎉🎈

**Comment by Khemendra-Bhardwaj** [comment]
Hey, how did you get tick on " Yes, I signed my commits."
I'm unable to do so

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
Altering svg colors is not required, this will affect other sections where it is being used 

image
_/meshmap/collaborate section_

We are using another version of the same element [here](https://layer5.io/cloud-native-management/meshmap/collaborate)

**Comment by l5io** [comment]
🚀 Preview for commit 6180a3b5764f78fb744e3683d69f7827bafa4019 at: https://64d6fdce555a76498559c0ea--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @VivekBaldha0712 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by leecalcote — APPROVED** [review]
Nice! Good work, @VivekBaldha0712

**Pull request merged**
