### PR TITLE
Removed unwanted scrollbars

### LINKED ISSUE #862: remove scroll-bars
**Current Behavior**
remove these unwanted scroll bars in [workshop page](https://layer5.io/workshops)

sc
sc2

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by knowyours**
Signed-off-by: knowyours <knowyours.cbe@gmail.com>

**Description**

This PR fixes #862 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Pratyush-Saxena** [comment]
@knowyours I guess your forked repository is not up to date with the base repository....because the issue you are facing is recently resolved #792...so fork again the repository and then make changes

**Comment by knowyours** [comment]
> @knowyours I guess your forked repository is not up to date with the base repository....because the issue you are facing is recently resolved #792...so fork again the repository and then make changes

Yeah sure. Just noticed that. I'll fix it

**Comment by knowyours** [comment]
@Pratyush-Saxena Now it works as expected. Thanks for the hint.

**Review by Pratyush-Saxena — CHANGES_REQUESTED** [review]
@knowyours pls have look  to below image ...
sss
i guess these  images get affected by the changes you made ...

**Comment by knowyours** [comment]
@Pratyush-Saxena They seem to be alright from my end.
image

**Review by Pratyush-Saxena — APPROVED** [review]
All right @knowyours ..LGTM :)

**Comment by knowyours** [comment]
> All right @knowyours ..LGTM :)

Nice. Thank you :)

**Comment by leecalcote** [comment]
Teamwork! Very cool, @knowyours and @Pratyush-Saxena.

**Review by leecalcote — APPROVED** [review]
Looking good. 👍

**Comment by knowyours** [comment]
> Looking good. 👍

Thank you @leecalcote :)

**Pull request merged**
