### PR TITLE
added screenshots for aws target group

### LINKED ISSUE #4853: [Screenshots] AWS Target Group Binding under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/aws-target-group-binding) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [AWS Target Group Binding](https://layer5.io/cloud-native-management/meshery/integrations/aws-target-group-binding) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by saikiranpatil**
**Description**

This PR fixes #4853 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by saikiranpatil** [comment]
@saurabh100ni are these screenshots correct?

**Comment by l5io** [comment]
🚀 Preview for commit e31f7c8ed151d7813ea16e09132202c068961f09 at: https://653a2f0f6572196aa32c96cc--layer5.netlify.app

**Review by sandramsc — COMMENTED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit 6362bd8e35ccb0634aa3a6f2928a4010cd999433 at: https://653adac438560623c1688901--layer5.netlify.app

**Comment by saikiranpatil** [comment]
@sandramsc I have fixed DCO check, please check it once

**Comment by leecalcote** [comment]
Awesome. Thank you, @sandramsc and thank you, @saikiranpatil

**Pull request merged**
