### PR TITLE
blog list view thumbnail correction

### LINKED ISSUE #3551: [Blog] List view doesn't use dark mode thumbnail.
**Current Behavior**

On the blogs page, when the list view is selected, it does not use the dark thumbnail when switched to dark theme.

image

**Desired Situation**

Dark and light thumbnails should be used for dark and light themes respectively.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam-AfA <shivamsood634@gmail.com>

**Description**

This PR fixes #3551 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 808165295cd7714788485b3d6f5e7bf68bd1c247 at: https://63a5d14e46200d1c88f4fef1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7bd82cb5d63a48a26a2ed1c8cc37f0129e932121 at: https://63a6b955754f3f4968fd9def--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fd329523c16df444eae3226f78b3f09a02c70e54 at: https://63a9d0d7ef27712fef9a086d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fd6b55d2303623df3843d80e70da79eb15ab82fb at: https://63a9d4cc1e1ae54259e3168a--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@Chadha93 I added the resource blog. Kindly review.

**Comment by Chadha93** [comment]
> @Chadha93 I added the resource blog. Kindly review.

@Shivam-AfA It's still in blog. I'll push the fix then in this PR. 
image

**Comment by l5io** [comment]
🚀 Preview for commit ff927c51c72f4720f711a1019c5cbf1228b4bcf2 at: https://63ab3c77c43aa349711a4cb5--layer5.netlify.app

**Comment by Chadha93** [comment]
@Shivam-AfA looks like you have made some issues while solving merge conflicts. Please revert those commits which are mixed, or simply open up a new one if you want. 
image

**Comment by Chadha93** [comment]
Thank you for moving it to the resources.

**Comment by Shivam-AfA** [comment]
@Chadha93 I really don't know how this happened. 😅 I am quite confused about reverting these commits. So I'll open a new PR.

**Pull request closed without merging**
