### PR TITLE
Changed heading gradient when hovered : Issue 4099

### LINKED ISSUE #4099: Change heading gradient when hovered
### Current Behavior
The MeshMap page https://layer5.io/cloud-native-management/meshmap/ contains three feature sections: Design, Visualize and Collaborate. Each section has a heading which redirects the user to the respective page. 

image

### Desired Situation
The color/ gradient of the heading should change when the user hovers over it. The "Learn More" text color should also change to white on hover.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hirentimbadiya**
**Description**

This PR fixes #4099 

**Notes for Reviewers**

https://user-images.githubusercontent.com/86219935/233137350-0e4fcdf7-dca5-433b-a65e-0f05b274b955.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Shivam-AfA — COMMENTED** [review]
@hirentimbadiya It'll be nice to add a smooth animation to it. Like `ease-in` or `ease-in-out` ?

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya It'll be nice to add a smooth animation to it. Like `ease-in` or `ease-in-out` ?

Right , I will do that no worries

**Review by Shivam-AfA — COMMENTED** [review]
@hirentimbadiya I see that you added the scaling effect on hover, however, I suggest that we add the animation only to the color change, and do not modify the scaling.

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya I see that you added the scaling effect on hover, however, I suggest that we add the animation only to the color change, and do not modify the scaling.

I have removed scaling , can you review please ?

**Comment by Shivam-AfA** [comment]
@hirentimbadiya Thanks for this! Let's see the deploy preview.

**Comment by l5io** [comment]
🚀 Preview for commit 822bc982e12d4b4c127678d71c01adbd13f12370 at: https://64473babdcc1705f226f467a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 95905663951940219d49f8fffc3bbe636786e7d8 at: https://644911f63678c36af2416d91--layer5.netlify.app

**Comment by hirentimbadiya** [comment]
@Shivam-AfA please review preview site.

**Review by Chadha93 — COMMENTED** [review]
@ritiksaxena124 How do you feel about the hover color?

**Comment by ritiksaxena124** [comment]
Thank you for your contribution @hirentimbadiya, The color looks good as it makes the heading in focus, just as @Shivam-AfA said to add some animation on the color change, it would be great if you make that changes.

**Comment by hirentimbadiya** [comment]
> Thank you for your contribution @hirentimbadiya, The color looks good as it makes the heading in focus, just as @Shivam-AfA said to add some animation on the color change, it would be great if you make that changes.

@ritiksaxena124 I've already added cubic bezier with the transition property what else I can add for animation ? can you suggest some ?

**Comment by ritiksaxena124** [comment]
> > Thank you for your contribution @hirentimbadiya, The color looks good as it makes the heading in focus, just as @Shivam-AfA said to add some animation on the color change, it would be great if you make that changes.
> 
> @ritiksaxena124 I've already added cubic bezier with the transition property what else I can add for animation ? can you suggest some ?

As you can see currently on hover the background changes instantly, can you add something so that it should change smoothly i.e, it should take some time for the effect to complete like 0.25  seconds

**Comment by hirentimbadiya** [comment]
I got it.

**Comment by l5io** [comment]
🚀 Preview for commit 470b9453b12bc2053f083da9cfaa7eae5d915f13 at: https://6455c22a0554c844ed43eb0d--layer5.netlify.app

**Comment by hirentimbadiya** [comment]
@ritiksaxena124 is this good now ?

https://user-images.githubusercontent.com/86219935/236598031-ff445a89-8ba4-47d0-95bf-de09ab4473e4.mp4

**Comment by l5io** [comment]
🚀 Preview for commit 40b09cb9e7f78c778a59224d221f1ad96d81170a at: https://6455d2080eaef4479d3284e3--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
It looks good, Nice @hirentimbadiya 👍🚀

**Review by Shivam-AfA — APPROVED** [review]
Thanks for this @hirentimbadiya

**Pull request merged**
