### PR TITLE
bugfix [MeshMap] Jolting form submission behavior

### LINKED ISSUE #3183: [MeshMap] Jolting form submission behavior
#### Description
When I say visitors submit the form for MeshMap, their browser is navigated to the top of the window and their focus is taken away from the form, which is often not even in view.

#### Expected Behavior
Not have your location updated, but to be shown the submission response in-place.

#### Screenshots
The confirmation dialog presented to visitors, who submit the form:
Screen Shot 2022-09-20 at 5 27 03 PM

#### Environment:
- Host OS: Mac
- Browser: Safari

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by siddheshJungade**
Signed-off-by: siddhesh jungade <connect@siddheshjungade.me>

**Description**
[l5.webm](https://user-images.githubusercontent.com/32316726/191543402-31216b90-2964-43f6-94fb-b49159a21abe.webm)

This PR fixes #3183

**Notes for Reviewers**
change window.scrollTo function 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by legendarykamal — APPROVED** [review]
LGTM , the demo video looks smooth thanks @siddheshJungade :100:

**Comment by siddheshJungade** [comment]
Thanks @legendarykamal this is my first time will try to improve and  also provide more details in next PR✌️

**Comment by l5io** [comment]
🚀 Preview for commit 04e95b7a237e6f7c6181515ea4cef6bfdfc075d9 at: https://63314e38746bfd35f5083d8b--layer5.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @siddheshJungade

**Comment by siddheshJungade** [comment]
Thanks for accepting my PR, this first will contribute more.

**Pull request merged**
