### PR TITLE
Adjusts padding to navigation text

### LINKED ISSUE #5081: intra page navigation text is being cutoff in contribution page
### Description
The navigation text on right side is not visible completely in [contribution page](https://layer5.io/community/handbook/contribution)

### Expected Behavior

The sections on right side are completely visible with good amount of space in between text and edge.

### Screenshots
image

### Environment:
- Host OS: Windows 11
- Browser: chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Harsha-10**
**Description**

This PR fixes #5081

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b028b048f92664bd64284f58f7083ddeae85f835 at: https://653f665b7cf240350fd61f56--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@Harsha-10 i don't see any difference in preview b/w your commit and this [page](https://layer5.io/community/handbook/contribution) live?
image

**Comment by Harsha-10** [comment]
This issue is for 14 inch screens, check the attached screenshot.

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
@Harsha-10 it would be better if you make it responsive for all screen sizes

**Comment by l5io** [comment]
🚀 Preview for commit a30a136f81384712e316ab6c6177643698d98346 at: https://6548bee4a334a90c08c3c613--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

**Comment by l5io** [comment]
🚀 Preview for commit cbe21c62654acb2ea6e632d0afc96dada9fe963f at: https://654a181f8a9c6b0e3d05a8b8--layer5.netlify.app

**Comment by Mohith234** [comment]
IMG-20231111-WA0003

This is a screenshot from a 14 inch laptop. @Harsha-10 Could you confirm if you're zoomed in? I couldn't replicate the issue even on the 14-inch laptop. 

// @sudhanshutech

**Comment by Harsha-10** [comment]
Yeah I'm sure.i can see the problem in my laptop, i think mac's screen width is 13.3 inch or something?

**Comment by Harsha-10** [comment]
This is the screenshot in my 14 inch  laptop at 100% zoom

image

**Comment by iArchitSharma** [comment]
@Harsha-10 as i see you are using chrome , have you tried opening this page on different browser?

**Comment by Harsha-10** [comment]
Yeah, it's same in edge too @iArchitSharma

**Comment by iArchitSharma** [comment]
@Harsha-10 http://whatismyscreenresolution.net/ can you please share a screenshot of your screen size from this link

**Comment by Harsha-10** [comment]
@iArchitSharma 

image

**Comment by iArchitSharma** [comment]
I think the issue is caused by the list in right site, because its going out in all screen sizes above width 750 and below 1341px
image

**Comment by iArchitSharma** [comment]
@Harsha-10 looks like you PR fixes it for some screen sizes but not all, can you fix it for all the screen sizes?

**Comment by Harsha-10** [comment]
It doesn't have any problem for remaining sizes... Can you please specify if anything?

**Comment by iArchitSharma** [comment]
@Harsha-10 750 to 1341 width has this problem
image

**Comment by Harsha-10** [comment]
Now i got the problem @iArchitSharma  , Thanks for mentioning this . but i'm getting that problem starting from 951px....

image

This is for 751px...

image

**Comment by iArchitSharma** [comment]
@Harsha-10 you can see a black space in right side this is also part of this problem at 751px

**Comment by Harsha-10** [comment]
Okay got it

**Comment by Harsha-10** [comment]
@iArchitSharma I have give display block where width issues present, looking good now?

image

**Comment by iArchitSharma** [comment]
the issue still exists, notice one thing that the page becomes horizontally scrollable in smaller screen sizes, make sure you scroll to right when testing for other screen sizes
image

**Comment by Harsha-10** [comment]
@iArchitSharma I haven't committed my changes yet, now there's no horizontal scrolling.... Will commit my changes to PR

**Comment by l5io** [comment]
🚀 Preview for commit 92035d8669043998e41898e6f8a4847759a31c2c at: https://65608059e5daf20656e977cf--layer5.netlify.app

**Comment by Harsha-10** [comment]
check now @iArchitSharma

**Comment by iArchitSharma** [comment]
@Harsha-10 this should remain in right side of page not in the bottom
image

**Comment by Harsha-10** [comment]
@iArchitSharma Really sorry, i haven't checked that.... Can I remove it at that size instead?

**Comment by Harsha-10** [comment]
image

it would look like this.... from 751px to 1279px intra page navigation will not be shown...even i tried to keep it, but i'm unable to remove the extra space and scrolling...i found a way but it was too complicated for it so i think this is better option to remove navigation at above size...

**Comment by iArchitSharma** [comment]
@Harsha-10 Can you please push the changes you have made so I can take a look?

**Comment by l5io** [comment]
🚀 Preview for commit 2a577a99e8864a510a593fe3a08ad3024c800372 at: https://6560c72558dbf33bc0d57d35--layer5.netlify.app

**Comment by Harsha-10** [comment]
i have pushed my changes @iArchitSharma

**Comment by iArchitSharma** [comment]
@Harsha-10 LGTM, lets discuss this on Website Meet on Monday

**Comment by leecalcote** [comment]
Yay! 👏

**Pull request merged**
