### PR TITLE
member profile added - Rex

### LINKED ISSUE #4724: [Community] Member Profile: Rex
**Current Behavior**

@Rexford74 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Rexford74 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Rexford74 
- Twitter: [rexford__](https://twitter.com/rexford__)
- LinkedIn: [rex-joshua-designer](https://www.linkedin.com/in/rex-joshua-designer/)
- Meshery Cloud: [f0a2dc22-e7c6-4143-a984-1f6c22f8e696](https://meshery.layer5.io/user/f0a2dc22-e7c6-4143-a984-1f6c22f8e696)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by shivankurchavan**
**Description**

This PR fixes #4724

**Notes for Reviewers**
1. Added Rex's member profile
2. removed png file from Ananya's member folder ( issue : #4725 )

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by shivankurchavan** [comment]
@Chadha93  @Rexford74 @vishalvivekm please review and suggest if any changes are needed. Thank you.

**Comment by l5io** [comment]
🚀 Preview for commit 65a68e87f781b6eb2be8831968394f519f936e44 at: https://64df4df526bf8b0c9279f96d--layer5.netlify.app

**Comment by vishalvivekm** [comment]
> @Chadha93 @Rexford74 @vishalvivekm please review and suggest if any changes are needed. Thank you.

thanks @shivankurchavan 
### Yay :balloon: @Rexford74 :tada:

**Review by VivekBaldha0712 — COMMENTED** [review]
LGTM

**Comment by Ghat0tkach** [comment]
hey @shivankurchavan 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by Rexford74 — APPROVED** [review]
I think this is nice and good to go, Shivankur. Well done and thank you very much for helping out with this!

**Pull request merged**
