### PR TITLE
fix: add width and height

### PR DESCRIPTION
**Pull request by Udit-takkar**
**Description**

This PR fixes https://github.com/layer5io/layer5/issues/4077

https://user-images.githubusercontent.com/53316345/230798447-df4f4c46-e6bf-4706-b4d0-24a9d1293e6e.mov

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 796a327ad81b43644bba947a46697c05d57a18fb at: https://643338f806fb267fdd28dfca--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
LGTM!!

**Review by Shivam-AfA — APPROVED** [review]
Thanks @Udit-takkar

**Comment by Chadha93** [comment]
@Udit-takkar Will you also take this? the position of the carousel navigation (dots) in the mobile menu? A separate issue/PR will also work.

**Comment by l5io** [comment]
🚀 Preview for commit 8337c0e14e91ed269c59ff628a8a7ff5e85b4a81 at: https://6433f385d305910882608241--layer5.netlify.app

**Pull request merged**
