### PR TITLE
Learn: Introduction to service mesh using linkerd

### PR DESCRIPTION
**Pull request by Blakelist7**
Signed-off-by: Kanwal Singh <kanwal.88singh@gmail.com>

**Description**
This PR adds the 7th chapter to Introduction to service mesh using linkerd

This PR fixes #
Part fixing of #1986 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bfd296602110a06b80a3e2e6832f234efb105d55 at: https://60f31fcdd2629362f9ea77e5--layer5ng.netlify.app

**Comment by Blakelist7** [comment]
@Nikhil-Ladha

**Comment by The-Loony-Coder** [comment]
hey @Blakelist7, I'am having difficulty in adding the chapters, like where can  I view the changes in my localhost, the added content. What I am trying to say is where are these added chapters/folder in website are located or how can I view them (the added mdx files) in my localhost.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Blakelist7** [comment]
Hey, @The-Loony-Coder first you need to set up `Layer5 site` locally use can refer to [CONTRIBUTING](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) guide for this.
Then, you need to visit `localhost:8000` in your browser and can add `path` to the page you want to view/check.

**Pull request merged**
