### PR TITLE
Update Hacktoberfest date to 2022

### PR DESCRIPTION
**Pull request by NPDebs**
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>

**Description**
This PR fixes issue #3175. 
The date on the Hacktoberfest page has been updated to 2022.

Hacktoberfest2022

**Notes for Reviewers**
Here is the path to the page => https://layer5.io/programs/hacktoberfest

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eb25f8b4de69e169833c32ad980cd997568dfaca at: https://632de8409b681d3728e0b53a--layer5.netlify.app

**Review by Chadha93 — COMMENTED** [review]
@NPDebs. Thanks for this. I've quickly made a new graphic for the Hacktoberfest you could toss in. https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1494%3A2023.

Let me know in the #websites channel if you face any issues while accessing Figma.

**Comment by Chadha93** [comment]
@NPDebs. Thanks for this. I've quickly made a new graphic for the Hacktoberfest you could toss in. [figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1494%3A2023](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1494%3A2023).

Let me know in the #websites channel if you face any issues while accessing Figma.

**Comment by NPDebs** [comment]
It's nothing, @Chadha93 🙏🏼 🚀

Eeshaan and I agreed that he would add the graphics, while I change the date. I'll quickly check with him  and do it myself if he's unavailable.

Thank you! 🙌🏼

**Comment by NPDebs** [comment]
Hi @Chadha93 
Eeshaan wants to update the new graphic in a separate PR. Can you please go ahead and merge this if it checks all the boxes? Thanks. 👍🏻

**Comment by eeshaanSA** [comment]
https://github.com/layer5io/layer5/pull/3198/commits/129c9e5467f540d89463c362133163e9b39ffdb6

**Comment by Chadha93** [comment]
> Hi @Chadha93 Eeshaan wants to update the new graphic in a separate PR. Can you please go ahead and merge this if it checks all the boxes? Thanks. 👍🏻

Sure, Thanks for the update here @NPDebs

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by NPDebs** [comment]
You're welcome. 🙂

**Pull request merged**
