### PR TITLE
Video embedding

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b14627c005407e7ae2994f1a0e7e8034458fb779 at: https://66bdf07246a3731700f7c374--layer5.netlify.app

**Review by Ashparshp — COMMENTED** [review]
In mobile view, the layout needs improvement.

**Comment by l5io** [comment]
🚀 Preview for commit b6ce6bdd480ffa292393c34c38cb2b2de03b716d at: https://66bdfe411499f728b103da7b--layer5.netlify.app

**Review by vishalvivekm — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
