### PR TITLE
[Programs] Added description of  5 Lfx internships 

### LINKED ISSUE #3086: [Programs] Add descriptions for 7 LFX 2022 Fall internships
#### Current Behavior
This page https://layer5.io/programs/lfx doesn't have the description of the 7 upcoming internships.

#### Desired Behavior
Add the Meshery, SMP, and CNCF TAG Network internship descriptions --> https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2022/03-Sept-Nov/README.md (5)

_Note: Two internships for MeshMap will be added under https://github.com/layer5io/layer5/issues/3087_

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**

This PR fixes #3086

Screenshot from 2022-08-31 11-33-59

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fa194dc9ddd239a9679314e89dbb8284c30cb43a at: https://630efe21a3288c54499df70d--layer5.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
You shouldn't be updating the existing page, rather create a new page for the year 2022.
Ref: https://github.com/layer5io/layer5/tree/master/src/collections/programs/gsoc-2022

There is another PR that updates information for the year 2022. So, please check with him and coordinate accordingly.

**Comment by legendarykamal** [comment]
Thanks @Nikhil-Ladha for the feedback I will do the necessary things :👍

**Comment by legendarykamal** [comment]
All 5 layer5 internships added 
image

**Comment by Nikhil-Ladha** [comment]
The "Additional Information" header is not aligned correctly.
And, remove the "Project Administrators" section.

**Comment by legendarykamal** [comment]
Both the changes are done @Nikhil-Ladha :+1:

**Comment by l5io** [comment]
🚀 Preview for commit 6421ca68a2e435633c396c242a8dcf354982666e at: https://6318ddcafe85540c07d0f43e--layer5.netlify.app

**Pull request merged**
