### PR TITLE
Fixed Rapid Toggle Between Nav Elevated and Flat State Issue

### LINKED ISSUE #1795: Nav toggles back and forth between elevated and flat state
**Description**

The navbar, after you scroll up to a certain point then stop scrolling, toggles quickly between elevated (with box shadow) and flat states causing to look as if its shaking 

**Expected Behavior**

It should remain in one place. I think this is an edge-case because this behavior occurs at the instant where the box-shadow is supposed to be applied to the nav.

**Screenshots**

https://user-images.githubusercontent.com/37044906/115149163-70690980-a028-11eb-8a96-b8a3908c2780.mp4

**Enviroment:**
- Host OS: Windows
- Meshery Version: 
- Kubernetes Version: 
- Browser: Chrome 89

---

[Optional] **To Reproduce**
1. Open up the layer5.io site
2. Resize the browser until the nav is replaced with a clickable burger (at  a width of about 900px)
3. Scroll down just untill the point where the nav is given a light green shadow, then stop scrolling at that point
4. The nav toggles between the elevated state (with box shadow) and flat state

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by karinape**
Signed-off-by: Karina Rebecca Peters <karinape@umich.edu>

**Description**

This PR fixes #1795

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Very good. 🙂

**Comment by l5io** [comment]
🚀 Preview for commit 998483208e2ea3943885c3f4c8e67b1fca250c9c at: https://6082113d7413d81653865617--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@OlaoluwaM looking good?

**Comment by OlaoluwaM** [comment]
Interesting problem. The padding (y-axis) was the issue, just confirmed it. It looks great!

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @karinape 🙂

**Pull request merged**
