### PR TITLE
Added theme to integrations page

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added themesetter code to the integrations page and also updated the eslint config to add space around infix operations like `a=b` -> (after adding the rule) `a = b` 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@debo19 @warunicorn19 @leecalcote thoughts? 🤔

**Comment by l5io** [comment]
🚀 Preview for commit db60b2c35b00d8c671eb20727ea6b49c85fb8d02 at: https://62ea85ec448433083413889d--layer5.netlify.app

**Comment by leecalcote** [comment]
Is the integration honeycomb flashing for a moment, then disappearing for you, too? https://62ea85ec448433083413889d--layer5.netlify.app/service-mesh-management/meshery/integrations

**Comment by warunicorn19** [comment]
+1 to the `a = b`

**Comment by sahilsuman933** [comment]
@leecalcote Honeycomb is disappearing cause a new theme configuration wasn't added to the Integration page.

**Comment by warunicorn19** [comment]
Snitch 😂

**Comment by sahilsuman933** [comment]
LGTM @Nikhil-Ladha, and thanks for updating the theme configuration on the Integration page.

**Review by sahilsuman933 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit fc44f4ed17479c2cc3391c8cf039030399046c53 at: https://62eaa63704c95e0088ff87d4--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Back to normal 😌 
Merging...

**Comment by leecalcote** [comment]
Whoa, this boilerplate theme support has to be added to _every page?_ Can this be added to a universal "import" instead?

**Comment by Nikhil-Ladha** [comment]
> Whoa, this boilerplate theme support code has to be added to _every page?_ Can this be added to a universal "import" instead?

Nope, as it includes other bits and pieces needed on each page.
Though, any new page added would be a copy (of code) of some other page, So, missing it out in the future is a very ver low possibility.

**Comment by leecalcote** [comment]
Gotcha. Hopefully, this is written as efficiently as possible to reduce cognitive overhead for all contributors involved.

**Pull request merged**
