### PR TITLE
Animation Fix and Logo-list

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
Removal of logolist and use of logo list component 
Animation Fix [minor]

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Looks good to me, Can the logos moved a bit downwards in mobile view on landing.
image

**Comment by leecalcote** [comment]
Pretty slick. Much smoother now.

**Review by leecalcote — APPROVED** [review]

**Comment by vinayaksh42** [comment]
> Looks good to me, Can the logos moved a bit downwards in mobile view on landing.
> image

For the mobile view, I am planning to make the whole animation stay static and in full size on top of the paragraphs because it is not really possible and won't exactly look good to animate it considering the width of a mobile device

**Review by Jashpatel1 — APPROVED** [review]
Nice work. Thanks @vinayaksh42 . The mobile view change can be addressed in a different PR. As we, follow iterative development, we are ready to go with this PR.

**Pull request merged**
