### PR TITLE
updated footer

### LINKED ISSUE #1124: [NG] updates to footer
**Desired Behavior**
The following changes are needed on the footer of layer5-ng site - 
- Remove `Gsoc 2020`, `Gsod 2020` and `CommunityBridge`. Use `Programs` with URL `/programs` in place on it 
- Remove the entire `Languages` section . 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by codetheorem**
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Description**
Added single Programs link instead of separate programs. removed language sections from the footer.

This PR fixes #1124 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
This is leading to empty space in the footer. Any thought on what can be placed in the empty space @Nikhil-Ladha @Jashpatel1 @vinayaksh42

**Comment by vinayaksh42** [comment]
I think we should get rid of the border that is used on the icons in the contact section as they are merging or give them a proper spacing
chrome_XyO2zAc3r8

**Comment by leecalcote** [comment]
+1 for spacing between buttons

**Comment by codetheorem** [comment]
I have changed the footer layout. It is better than the previous one. We cannot change the border of the icons as it is through the svg not css.

**Review by leecalcote — APPROVED** [review]
Thanks, @codetheorem. 👍

**Pull request merged**
