### PR TITLE
Add badge

### LINKED ISSUE #2480: Add Badges to certain member profiles
**Current Behavior**
A variety of badges exist so that community members and their efforts may be affiliated with a particular project or with a community initiative.

**Desired Situation**
Add the respective badges to the following member profiles to recognize their effort in our projects.

- [Abhishek Kumar](https://layer5.io/community/members/abhishek-kumar): Meshery
- [Aditya Chatterjee](https://layer5.io/community/members/aditya-chatterjee): Meshery
- [Manav Kapoor](https://layer5.io/community/members/manav-kapoor): Meshery
- [Gaurav Chadha](https://layer5.io/community/members/gaurav-chadha): Meshery, Landscape

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by valanm22**
Signed-off-by: Valan Baptist Mathuranayagam valanm22@gmail.com

**Description**

This PR fixes #2480

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
You missed the signoff again 😅

**Comment by warunicorn19** [comment]
See how the DCO is failing.

**Comment by l5io** [comment]
🚀 Preview for commit 6fb885aa537d619aafcc2b84108badd13cde248c at: https://61e329be6a840ea0c47e7791--layer5ng.netlify.app

**Comment by valanm22** [comment]
Is it good now?

**Review by warunicorn19 — APPROVED** [review]
Yup, LGTM. Thank you @valanm22

**Pull request merged**
