### PR TITLE
No space between the button from 768px to 991px on meshery page, issue -  #3333

### LINKED ISSUE #3333: No space between the button from 768px to 991px on page: /cloud-native-management/meshery
#### Description

No space between the button from 768px to 991px on page: /cloud-native-management/meshery
Issue

#### Expected Behavior

After

#### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AbhishekTiwari23**
Signed-off-by: Abhishek Tiwari <97469132+AbhishekTiwari23@users.noreply.github.com>

**Description**
Changed the max-width at the media query, which can solve this issue.

This PR fixes #3333 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by AbhishekTiwari23** [comment]
@legendarykamal, sir, I just changed the max-width. If it is not a good choice, please let me know. I am waiting for your advice.
Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit a413d72694b6b70c57ebff00f75532b74167c1da at: https://63545215ebafdd6023992d8c--layer5.netlify.app

**Review by legendarykamal — APPROVED** [review]
The changes look fine to me though there's an ambiguity over if video should come first or the heading at different sizes. But considering the earlier flow this looks acceptable ✔️ .

image

**Comment by Nikhil-Ladha** [comment]
Please write a more sensible PR title 🙏

**Comment by AbhishekTiwari23** [comment]
> Please write a more sensible PR title 🙏

I apologize for that. It might be the default title. Actually, it happened in 2 out of 3 pr that I make simultaneously.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Instead, make the side-view of the video and text consistent for screen-wdith:768px just add a margin around the buttons, and then the column-reverse, i.e, make the change current to 768px

**Comment by leecalcote** [comment]
@AbhishekTiwari23 does this last feedback make sense?

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23, does this last feedback make sense?

Oh, thanks, sir, to remind me, I forgot about it because of the festivals; I will make the necessary changes as soon as possible.

**Comment by Nikhil-Ladha** [comment]
Any update here @AbhishekTiwari23 ?

**Comment by AbhishekTiwari23** [comment]
> Any update here, @AbhishekTiwari23?

I apologize for that, but currently, there is no update because, after Diwali, I was busy with Chhat Puja(u might know it). And because of that also have a big bunch of backlog, so if it is urgent, you can assign it to someone else, or I will try it after 1-2 days. 
Thanks.

**Comment by leecalcote** [comment]
@AbhishekTiwari23 thanks much for the update about your availability. This really helps with planning and expectation setting. 👍

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
