### PR TITLE
This PR fixes #5825

### LINKED ISSUE #5825: [Community] Member Profile: Ijeoma Eti
**Current Behavior**

@Aijeyomah has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aijeyomah as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Aijeyomah
- Twitter: https://twitter.com/EtiIjeoma
- LinkedIn: https://www.linkedin.com/in/ijeoma-eti
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sparshagl**
**Description**

This PR fixes #5825

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@Aijeyomah

**Comment by l5io** [comment]
🚀 Preview for commit 0a11b6190db90e5f90b5350482143286c4fe5754 at: https://66c218d19cb5a3e11e653c52--layer5.netlify.app

**Review by Aijeyomah — COMMENTED** [review]
Looks good to me

**Review by Ashparshp — APPROVED** [review]
Thank you @sparshagl

**Comment by sparshagl** [comment]
@Ashparshp thanks for the opportunity to contribute! Looking forward to many more :)

**Comment by l5io** [comment]
🚀 Preview for commit 0a11b6190db90e5f90b5350482143286c4fe5754 at: https://66c247d95b098bd681ea1e79--layer5.netlify.app

**Comment by Ashparshp** [comment]
@sparshagl Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the meeting minutes.

**Pull request merged**
