### PR TITLE
Chore[Discuss]: Responsive Footer for smaller screens

### LINKED ISSUE #1894: [Discuss] Footer not mobile-friendly
**Description**
The https://discuss.layer5.io site's footer is not responsive.

**Expected Behavior**
Footer should adjust in size to accommodate mobile visitors. See layer5.io for an example.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Responsive for smaller screens (mobile and tablets)

This PR fixes #1894 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1226ef25d45c8a576120fa8edc4993a79a03f279 at: https://61df46499c4b9d4cb0e77a4f--layer5ng.netlify.app

**Review by leecalcote — COMMENTED** [review]
This looks promising, @Abhijay007!

**Comment by leecalcote** [comment]
Feedback - 

https://user-images.githubusercontent.com/7570704/149258671-25a31c8c-3b44-4be4-84b4-22d8590b7163.mov

The banner also is affected:

Screen Shot 2022-01-12 at 9 05 26 PM

**Comment by leecalcote** [comment]
@Abhijay007, just in case the current css in `master` is any different than what is actually running on the site now, here is a copy of the current css:

```
/* Font Styles */
@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftBlack.otf') format('opentype');
    font-weight: normal;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftBold.otf') format('opentype');
    font-weight: bold;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftBlackItalic.otf') format('opentype');
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftBoldItalic.otf') format('opentype');
    font-weight: bold;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftExtraBold.otf') format('opentype');
    font-weight: 800;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftExtraBoldItalic.otf') format('opentype');
    font-weight: 800;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftHeavy.otf') format('opentype');
    font-weight: 900;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftHeavyItalic.otf') format('opentype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftLight.otf') format('opentype');
    font-weight: 300;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftLightItalic.otf') format('opentype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftMedium.otf') format('opentype');
    font-weight: 500;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftMediumItalic.otf') format('opentype');
    font-weight: 500;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftRegular.otf') format('opentype');
    font-weight: 400;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftRegularItalic.otf') format('opentype');
    font-weight: 400;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftSemiBold.otf') format('opentype');
    font-weight: 600;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftSemiBoldItalic.otf') format('opentype');
    font-weight: 600;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftThin.otf') format('opentype');
    font-weight: 100;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftThinItalic.otf') format('opentype');
    font-weight: 100;
    font-style: italic;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftUltraLight.otf') format('opentype');
    font-weight: 200;
}

@font-face {
    font-family: "Qanelas Soft";
    src: url('https://layer5.io/fonts/qanelas-soft/QanelasSoftUltraLightItalic.otf') format('opentype');
    font-weight: 200;
    font-style: italic;
}



// @font-face {
//   font-family: 'Qanelas Soft';
//   src: url('Qanelas-Soft.eot'); /* IE9 Compat Modes */
//   src: url('Qanelas-Soft?#iefix') format('embedded-opentype'), /* IE6-IE8 */
//       url('Qanelas-Soft.woff2') format('woff2'), /* Super Modern Browsers */
//       url('Qanelas-Soft.svg#svgFontName') format('svg'); /* Legacy iOS */
// }


body {
    font-family: "Open Sans", sans-serif;
    --heading-font-family: "Qanelas Soft", sans-serif; 
}

/* Header Styles */

.d-header {
    height: 6rem;
    background-color: rgb(243, 255, 253);
}

.custom-header-links .headerLink {
    a {
        --font-up-1: 15px;
        margin: 0 10px;
        color: var(--header-primary);
    }
    a:hover {
        color: var(--layer5_green);
    }
} 

@media only screen and (max-width: 1150px) {
  .headerLink {
    display: none;
  }
}

@media only screen and (max-width: 480px) {
  .headerLink {
    display: none;
  }
  .header-buttons{
    display: none;
  }
  .d-header #site-logo {
   width: auto;
   height: 2em;
  }
}

/* Hero Styles */

.search-widget {
    display: none;
}

.custom-search-banner {
    margin: -1em 0 2em 0;
    background-color: var(--layer5_green);
    .custom-search-banner-wrap{
        max-height: 250px;
        padding-top: 4em;
        h1{
            color: white;
            font-size: 50px;
        }
        p{
            color: white;
            font-size: 28px;
            margin: 1rem 0 3rem 0;
        }
    }
}


/* Category Section Styles */

.list-controls .combo-box .combo-box-header {
    border: none;
    font-size: 1.25em;
    text-transform: capitalize;
}

.select-kit.combo-box .select-kit-header {
    border: none;
    font-size: 1.25em;
}

.categories-and-latest div.column.categories {
    flex: 1 1 55%;
}
.categories-and-latest div.column {
    flex: 0 1 40%;
}

.category-list{
    border-collapse: separate;
    border-spacing: 0 1em;
    thead{
        display: none;
    }
    tr {
        display: flex;
        box-sizing: border-box;
        padding: 1em;
        margin-bottom: 2.5em;
        border: none;
        background: #fbfbfd;
    }
    tbody {
        .category {
            border: none;
            .category-logo.aspect-image {
                --max-height: 75px;
                max-width: 90px;
                height: auto;
            }
        }
    }
} 

/* Latest Section styles */

.latest-topic-list-item {
    border-bottom: none;
    margin-bottom: 20px;
}

.table-heading {
    border-bottom: none;
}

.latest-topic-list-item.visited a.title:not(.badge-notification) {
    color: black;
}

.latest-topic-list .table-heading {
    margin-left: 10px;
    color: black;
    font-size: 20px;
}

.twiiter-sidebar {
    margin-top: 20px;
}

.container {
    max-width: 1110px;
    margin: auto;
}
```

**Comment by YashKamboj** [comment]
@Abhijay007 adjusting margin, padding and width would solve the issues

**Comment by warunicorn19** [comment]
@leecalcote we might try and deploy the footer we have on staging right now, it's gonna be quite difficult for this to be exactly the same as the one layer5.io because the discourse template we are using is not mobile responsive.

**Comment by Abhijay007** [comment]
@leecalcote @YashKamboj @warunicorn19 

I tested these changes locally as the server is not live, it is working fine for me, I think some CSS classes are overwriting these changes.


https://user-images.githubusercontent.com/64387054/149295794-ee5fe067-6729-435e-b5cc-0b2833f3d507.mp4


Note: please ignore underlined links, input, and button CSS these components are fetching styling from a different CSS file, maybe from any globe CSS theme or something.

**Comment by leecalcote** [comment]
@Abhijay007 will you add this to the Websites' call agenda for tomorrow? Let's examine the current server for conflict.

**Comment by l5io** [comment]
🚀 Preview for commit 4904e209e6d26a6df1fe395dad03a0dad1c10cbe at: https://61e6ed812224af9699fdad8d--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Could you please reduce the font weight just a little, similar to the one we have on layer5.io

Screenshot 2022-01-18 at 12 21 41 PM

**Comment by Abhijay007** [comment]
> Could you please reduce the font weight just a little, similar to the one we have on layer5.io
> 
> Screenshot 2022-01-18 at 12 21 41 PM

ok sure !!

**Comment by l5io** [comment]
🚀 Preview for commit 01f9129be9e84bd1c5c48cb5d0dba6495b35051a at: https://61e70a24acb7ff0a39b77c95--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@Abhijay007 could you please add this to your code. Then we can merge. 

```
.footer-sections {
    a {
        font-weight: 400;
        
    }
}
```
There's a slight issue between 1024px - 879px. We can probably ignore that for now.

**Comment by Abhijay007** [comment]
> @Abhijay007 could you please add this to your code. Then we can merge.
> 
> ```
> .footer-sections {
>     a {
>         font-weight: 400;
>         
>     }
> }
> ```
> 
> There's a slight issue between 1024px - 879px. We can probably ignore that for now.

ya, sure !!

**Review by warunicorn19 — APPROVED** [review]
Awesome! Great stuff @Abhijay007. Way to prove me wrong 😁

**Comment by Abhijay007** [comment]
finally, we have responsive footer 🚀 yaaay

**Pull request merged**
