### PR TITLE
New component for catalog on MeshMap page

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**

https://user-images.githubusercontent.com/85789734/170522123-ed07a958-7d24-4f06-a8dc-b7296ccaa7c9.mov

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6021969b13f58013a7a77631c3b2c8352c881b71 at: https://628fa17fa8691a192baf7eb8--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
This looks pretty cool. But, just to think as a user doesn't the on hover behavior on the card here give the conception that it's clickable even though it's not?? 🤔

**Comment by leecalcote** [comment]
@YashKamboj we're ready for those service catalog filters now.

Each card type can link to the predefined filter for that category (or to that specific card) on meshery.io/catalog.

**Comment by leecalcote** [comment]
Oh, wait. These are SVGs. But, they are blurred based on the animation, it seems. I don't that the current level of blur is acceptable.

**Comment by l5io** [comment]
🚀 Preview for commit c2150b8dce3c042daaf96e5c9587409b5fa8cbec at: https://62909c1a044481078867af88--layer5ng.netlify.app

**Comment by debo19** [comment]
@leecalcote fixed the blur issue

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
