### PR TITLE
[Fix] Correct link to Community Member Profile issue template

### LINKED ISSUE #2892: [Docs] Link in Creating a Member Profile does not work.
**Description**
The link provided in <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updatingcreating-a-community-member-profile">CONTRIBUTING.md</a> named as `Community member profile issue template` redirects to page with a status code of 500.

**Expected Behavior**
It should redirect to the desired page

**Screenshots**
error

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Santosh1176**
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

**Description**
Correct link to Community Member Profile issue template file.

This PR fixes #2892

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. This is an improvement. Will you also include a link to the issue template?

**Comment by Santosh1176** [comment]
> Thanks. This is an improvement. Will you also include a link to the issue template?

Could you please clarify, which issue template needs to be added?

**Comment by Santosh1176** [comment]
@leecalcote is this the link you want to be on the page: [Community Member Profile issue template](https://github.com/layer5io/layer5/blob/master/.github/ISSUE_TEMPLATE/community_member_profile.md)

**Review by leecalcote — APPROVED** [review]
Feedback applied.

**Comment by leecalcote** [comment]
Thanks, @Santosh1176

**Pull request merged**
