### PR TITLE
Changed integrations to color

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam Sood <shivamsood634@gmail.com>

**Description**

This PR presents a preview regarding experimentation with changing integration icons to color in dark theme.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shivam-AfA** [comment]
@leecalcote 

Here are some background color suggestions for the icon containers.

**background: #333333**
image

**background: #666666**
image

**background: linear-gradient(to right, #666666, #444444)**
image

**Comment by l5io** [comment]
🚀 Preview for commit ecba3fa9528778ef348746ee25d3d421565e33bb at: https://63e23fb418a2ff5a35301115--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@leecalcote I have added the Emissary icons and also changed updated the Linux and Istio icons in the spreadsheet.

**Review by leecalcote — APPROVED** [review]
Looking good. 👍

**Comment by leecalcote** [comment]
The istio svg can be pulled from meshery.io with transparent background. The linux penguin can have an issue opened for it.

**Comment by l5io** [comment]
🚀 Preview for commit 5b9f6d1d709e87ba576f189aec280098921d5b7c at: https://63e75079c36db77e74c14970--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
Um.. I already changed both logos to transparent background in the spreadsheet.

**Comment by leecalcote** [comment]
Oh! Ok. I hope that works (it should).

**Pull request merged**
