### PR TITLE
Flux screenshots

### LINKED ISSUE #5337: [Screenshots] Flux under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/flux) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Flux](https://layer5.io/cloud-native-management/meshery/integrations/flux) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #5337 
please review my PR
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0627321a9ded5121c5fd88e37a67fde9b1902291 at: https://65c4ea2d3838cf13c3dd1afb--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c72402ed4d184d2e2879f73c998fc811dea2446b at: https://65c4ef86df124317d2c20a60--layer5.netlify.app

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
@narasimha-1511 thankyou for helping here, please make your browser does not contain any bookmarks, please see this acceptance test from issue

- [ ] Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

**Comment by narasimha-1511** [comment]
@Yashsharma1911 Doing the Requested Changes Right Now

**Comment by l5io** [comment]
🚀 Preview for commit 6156c1e1561592b3e026dbfdc0d54922101e3ea6 at: https://65cb381b88f393ad72f82dd9--layer5.netlify.app

**Comment by saurabh100ni** [comment]
The Order Narsimha, Desired order is:

1. Designer - 🌑
2. Designer - 🌕
3. Visualizer - 🌑
4. Designer - 🌕

**Comment by narasimha-1511** [comment]
You mean 
first two designers , then two visuvalizer ?
@saurabh100ni

**Comment by saurabh100ni** [comment]
Yes that's correct

**Comment by l5io** [comment]
🚀 Preview for commit f6ec84f900ed76aa773d0840d1ac25b88c7f0194 at: https://65cc466d73b8126737824bce--layer5.netlify.app

**Comment by saurabh100ni** [comment]
@narasimha-1511, The order on the preview is still in the wrong order, it needs to be fixed.

Cross-check the order on [this page](https://65cc466d73b8126737824bce--layer5.netlify.app/cloud-native-management/meshery/integrations/flux) and the order I have mentioned [here](https://github.com/layer5io/layer5/pull/5381#issuecomment-1943062349).

you can take [this page](https://layer5.io/cloud-native-management/meshery/integrations/actions-runner-controller-arc) as a reference.

**Comment by narasimha-1511** [comment]
@saurabh100ni i have did it locally its showing diffrently not like this one as you have said but this one is showing differently

**Comment by saurabh100ni** [comment]
I see the code LGTM. @vishalvivekm, Is there anything we can do here? If not then Let's get this merger.

Thanks for your efforts @narasimha-1511, I see you doing some good work here. Would you please apply all the feedback you got so far? i.e. : **The order** and the screenshots **in incognito mode**.

**Review by saurabh100ni — APPROVED** [review]

**Comment by narasimha-1511** [comment]
image

here you can see first two designers and then two visualizers ..

**Pull request merged**
