### PR TITLE
Animation fixed for integrations + removed unused css for button Learn More 

### PR DESCRIPTION
**Pull request by legendarykamal**
**Description**

This PR fixes #
Titles of all the integrations were not coming at center on hovering so made them in place .

https://user-images.githubusercontent.com/95926324/200140710-48c22306-35ab-4e51-9bb9-f686eb485b76.mp4

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. Can we:

1. Leave the Learn More button in case we bring it back.
2. Avoid use of specific padding/margin given that some names are one, two, three lines long? Can we find a `center` instead?

**Comment by legendarykamal** [comment]
cool , yes we can . I will update this ✔️ .

**Comment by l5io** [comment]
🚀 Preview for commit 6fcb4b5d4d9592100b3416a919255faa14a7c0fd at: https://6366d0c36084a03cb129ffd2--layer5.netlify.app

**Comment by legendarykamal** [comment]
@leecalcote no using the `justify-content` or `align-self: center` results in some undesired changes , 

This `margin` applied css works best be it 1 line or 3 line title . If you would consider :)

**Comment by l5io** [comment]
🚀 Preview for commit fd2773814d664c5d0949e5da45625eef6190dfda at: https://6367d19752cfab60309f2d5a--layer5.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Technically, this change is not at all needed. I mean don't see any issue with the positioning of the text currently. It looks center-aligned without any changes to the margin or any other CSS per see.
However, we can remove the `font-size: 0.675rem` for the title to avoid that abrupt change in font-size on hover.

**Pull request closed without merging**
