### PR TITLE
chore: Fixed FAQ title small size on mobiles

### LINKED ISSUE #4946: Frequently Asked Questions font is very small in mobile view
### Current Behavior

The Frequently Asked Questions in Pricing Section of Layer5 Website has very small font size for the questions in mobile view
image

### Desired Situation

it must be little more than the present size of the font so that it should be more readable.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**Description**
Fixed small font size on FAQ title

This PR fixes #4946 

**After**

Layer4946

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2667f2239181429fb5737fb13fec3924b573459c at: https://650eeeb40c4ca433322d6d21--layer5.netlify.app

**Comment by dhamkirti21** [comment]
image
the arrow is merging on the text

**Comment by pateldivyesh1323** [comment]
Are you talking about this? It looks perfectly fine.
Layer-Arrowmerging

**Comment by Mohith234** [comment]
Appreciate your enthusiasm @pateldivyesh1323 , Please do not create any PRs unless the issue is marked as valid and assigned to you. Read the contributing guidelines beforehand.

**Comment by pateldivyesh1323** [comment]
@Mohith234 Sorry, I will take care.

**Comment by Chadha93** [comment]
> Appreciate your enthusiasm @pateldivyesh1323 , Please do not create any PRs unless the issue is marked as valid and assigned to you. Read the contributing guidelines beforehand.

:100:, Well said @Mohith234 , thank you for opening PR, since the issue is not required, I'm closing the PR. Please check the contribution insturctions.

**Pull request closed without merging**
