### PR TITLE
Fixed the responsiveness in the maintainers and contributors section

### LINKED ISSUE #1483: [Home] Proud Maintainers: spacing is off in grid; escaped logos
**Description**
In the Proud Maintainers section of the Home page, the issues shown in the screenshot are present.

**Screenshots**
Screen Shot 2021-02-04 at 9 44 50 PM

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR fixes #1483 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
How is it working now? @Tanuj22, is the issue with Netlify fixed?

**Review by Jashpatel1 — APPROVED** [review]
Looks good to me

**Comment by Tanuj22** [comment]
> How is it working now? @Tanuj22, is the issue with Netlify fixed?

It works when PR is from a branch from the Layer5 repo 😬

**Comment by Nikhil-Ladha** [comment]
I just created the branch and pushed it, so how come it was already there?

**Comment by Tanuj22** [comment]
> I just created the branch and pushed it, so how come it was already there?

Any branch from the main repo works. But from a fork it fails.

**Comment by Nikhil-Ladha** [comment]
But the branch is not there in the main repo 🤔.
How are you creating a new branch?
I use `git checkout -b <branch-name> upstream/layer5-ng` . And, this is done from a repo which is a fork of the layer5 repo.
What steps do you or others follow?

**Comment by Tanuj22** [comment]
Are you sure? 😅This PR is showing that the branch is `home_prod`. If it was created in the forked repo it would have been `Nikhil-Ladha:home_prod`

**Comment by Nikhil-Ladha** [comment]
I think the issue, is arising because I have write permissions to the repo?

**Pull request merged**
