### PR TITLE
[Handbook] Added sign-off instructions to contributions page

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1b6c037cbb34836beede2a6425527033b0e97fdc at: https://6158ad3448af42f29d402f2d--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@debo19 good work but just a couple of things, 
Let's lose the line `Now, go to town hacking away and make whatever changes you want to.` in line no.52 (hacking has a negative tone to it)
And also if you could re-phrase line 25 in a better way or just remove it, doesn't make a lot of sense.

**Comment by l5io** [comment]
🚀 Preview for commit 58a07bffd1ccab478d76e02f6810b05a5a4a4c48 at: https://6158b38e0314159bc0e80c09--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@debo19 just one small nitpick 😅, could you please make this into a code block instead of it being in one line.
Screenshot 2021-10-03 at 7 35 50 PM
(The alias part)

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thanks @debo19

**Pull request merged**
