### PR TITLE
Equal top and bottom padding added to subsection cards of Navigation bar

### LINKED ISSUE #3632: [UI] Card inside dropdown menu doesn't have even spacing
#### Description
Card inside the dropdown menu doesn't have even spacing on hover in desktop resolution

#### Page Link:
[Link](https://layer5.io/)

#### Expected Behavior
It should have even spacing from top and bottom

#### Screenshots
Group 6

#### Environment:
- Host OS: Mac
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by AgniveshChaubey**
Signed-off-by: Agnivesh Chaubey <agniveshvapi@gmail.com>

**Description**
Cards inside the dropdown menu of Navigation bar does not have equal spacing on hover in desktop resolution.

This PR fixes #3632

**Notes for Reviewers**
The top-bottom spacing in the cards of navigation bar was not even. Equal top-bottom padding is added in this PR.

Before:
Screenshot (79)

After:
Screenshot (80)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey, nice work @AgniveshChaubey I have a suggestion rather using `px` unit you can use `em` relative unit to give padding and clear you all checks to merge

**Comment by AgniveshChaubey** [comment]
Hey @Yashsharma1911, thanks for your suggestion. I have changed the unit to `em`. I am getting some of checks failing, can you please explain a bit more about why they are failing?

**Comment by Yashsharma1911** [comment]
Hey, @AgniveshChaubey there is extra padding of 5px in the bottom look at it and try to remove it. This may be because somewhere it has defined 5px which is unnecessary

213219374-541d2b13-674b-44d1-9dca-733a8da97507

**Comment by AgniveshChaubey** [comment]
> Hey, @AgniveshChaubey there is extra padding of 5px in the bottom look at it and try to remove it. This may be because somewhere it has defined 5px which is unnecessary
> 
> 213219374-541d2b13-674b-44d1-9dca-733a8da97507

okey let me check!

**Comment by AgniveshChaubey** [comment]
Hey @Yashsharma1911, I have removed the extra 5px padding and committed the changes as well! But why am I getting this error while pushing the changes? 
image

**Comment by AgniveshChaubey** [comment]
Hey @Yashsharma1911 I have removed the 5px extra padding, consider checking it out. I forgot to signoff the commit. Is there any way I can signoff on the PR itself?

**Comment by Yashsharma1911** [comment]
Hey @UtkarshMishra12 please review this PR

**Comment by AgniveshChaubey** [comment]
> Hey @UtkarshMishra12 please review this PR



> Amazing @AgniveshChaubey you have done great work do one more thing clear your DCO check

is there any way I can do it on the PR itself, or do I have to commit again?

**Comment by AgniveshChaubey** [comment]
> Amazing @AgniveshChaubey you have done great work do one more thing clear your DCO check

Hey @UtkarshMishra12, I was facing some problem signing off the commit, so I have created a new pull request with all the required changes, requesting you to review it. PR link- https://github.com/layer5io/layer5/pull/3649

**Pull request closed without merging**
