### PR TITLE
service-mesh-performance home page aligned centered

### PR DESCRIPTION
**Pull request by pratikdongre**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 724c14f72b68a86191012e84596996ca638947bf at: https://63fdd77ba5f53010894134a1--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @pratikdongre  🚀🥇

**Comment by l5io** [comment]
🚀 Preview for commit 2f1b87719a230adfe5858cd453ca182f55fa75a8 at: https://63ff65e06657d51a58457168--layer5.netlify.app

**Comment by pratikdongre** [comment]
hey @UtkarshMishra12 

it shows to me some checks were not successful 
lighthouseci/lighthouseci(pull_request) failing

am i missing something ?

**Comment by Nikhil-Ladha** [comment]
> hey @UtkarshMishra12
> 
> it shows to me some checks were not successful lighthouseci/lighthouseci(pull_request) failing
> 
> am i missing something ?

Good of you to notice that @pratikdongre .
For now, you can ignore the test as we are still in the process of fixing out the issues reported by lighthouse.

**Comment by Nikhil-Ladha** [comment]
I would be closing out this PR as I don't think this PR fixes an _actual_ issue. The current alignment is by design and no improvement is needed there.

**Pull request closed without merging**
