### PR TITLE
Added sections in FAQs

### LINKED ISSUE #1708: [FAQs] Breakdown FAQs into sections
**Current Behavior**
The FAQs component is capable of displaying only specific topics (a topic passed in as a property). The FAQ component is used on different pages with different topics listed. However, this page has ALL of the FAQs included - https://layer5.io/company/faq.

Screen Shot 2021-03-17 at 11 41 16 AM

**Desired Behavior**
Ideally, https://layer5.io/company/faq breaks the questions into different sections by category. See mockup.

Topics should not be statically configured on this page, the number of sections shown is dynamically determined from datafile / GraphQL queries.

 **Screenshots / Mockups**
Screen Shot 2021-03-17 at 11 41 16 AM

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

This PR fixes #1708 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e4dfe055806643a14753184b3e12c502f2412aa7 at: https://60757079d84e10a074605dd2--layer5ng.netlify.app

**Review by Tanuj22 — COMMENTED** [review]
The FAQs are not getting filtered for the category here https://60757079d84e10a074605dd2--layer5ng.netlify.app/careers/programs

**Comment by Nikhil-Ladha** [comment]
> The FAQs are not getting filtered for the category here https://60757079d84e10a074605dd2--layer5ng.netlify.app/careers/programs

Ahh, I looked for any such reference but couldn't find. Will update the code to fix this.

**Comment by l5io** [comment]
🚀 Preview for commit e725bb11840dafa042d201079c6ce48436c06f63 at: https://607582cc1fa930bb9321970d--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
