### PR TITLE
Layer5-community_meetup update

### LINKED ISSUE #2690: [About] Swap "Community First" image on About page
**Current Behavior**
The About page (https://layer5.io/company/about) has an image next to "Community First" section with this image:

**Desired Behavior**
Swap the existing image next to "Community First" section with this image: https://pbs.twimg.com/media/FO4vSXcWQAUc1Uj?format=jpg

Reference tweet: https://twitter.com/oluwabamikemi/status/1508194928442159112

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Michellebuchiokonicha**
**Description**

This PR fixes #2690

**Notes for Reviewers**

The line-break error have been corrected as advised and the name of the image, alt and source changed as well

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Looks like the commits are not signed.
You could follow the instructions mentioned [here](https://github.com/layer5io/layer5/pull/2708/checks?check_run_id=6004279557) to fix that.

**Comment by Nikhil-Ladha** [comment]
Also, please update the already open PR #2707, instead of creating a new one.
Or, close out the old PR.

**Comment by Nikhil-Ladha** [comment]
Other commits have been included in the PR, please look into it.

**Comment by leecalcote** [comment]
@Michellebuchiokonicha you'll need to resync your fork and branch. Instructions can be found in the contributing guide and/or contributing.md.

**Comment by leecalcote** [comment]
@Michellebuchiokonicha you'll need to resync your fork and branch. Instructions can be found in the contributing guide and/or contributing.md.

**Comment by Chadha93** [comment]
@Michellebuchiokonicha would you please address the conflicts and commits?

**Comment by Michellebuchiokonicha** [comment]
> 

I have been trying to fix it to no avail. it keeps bringing back the line-break error. more like a reversal of my previous commit. Perhaps I will close this pr, fork again and start afresh.

**Pull request closed without merging**
