### PR TITLE
added maintainer status

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #

**Notes for Reviewers**
Added frontmatter Maintainer Status for the following people:
1. Aabid Sofi
2. Aadhitya Amarendiran
3. Mario Arriaga
4. Vivek Vishal
5. Yash Sharma

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Thank you @hargunkaur286

**Comment by vishalvivekm** [comment]
will you please also update value of position frontmatter for these individuals from `position: Contributor` to `position: Maintainer`

**Comment by l5io** [comment]
🚀 Preview for commit c5f5bde1b1d3f1f9d9932fb3e931d4cea500e909 at: https://670ba1fb96a5a44d613487dd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a55c41ae60666f2d79c566bedae21c2b77da4905 at: https://670ba89a768ef84f0e210210--layer5.netlify.app

**Pull request merged**
