### PR TITLE
fixed heading responsiveness issue

### LINKED ISSUE #5684: Layer5 Community Member Text is Not Responsive
### Description
The text "Layer5 Community Member" on the [community members page](https://layer5.io/community/members) is not responsive. It does not scale properly across different screen sizes, causing layout issues on smaller devices.

#### **Steps to Reproduce**
1. Go to [Layer5 Community Members Page](https://layer5.io/community/members).
2. Resize the browser window to a smaller size or view the page on a mobile device.
3. Observe that the text "Layer5 Community Member" does not adjust to fit the screen properly.

### Expected Behavior
The text "Layer5 Community Member" should be responsive and adjust its size and position appropriately across all screen sizes to ensure a consistent user experience.

### Screenshots
Members

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by akaBisht**
Description

This PR fixes #5684 

Notes for Reviewers

In this PR, I changed the text alignment of the heading to the left, fixing the responsiveness issue across various screen sizes.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6bdd994dbd234f78c5a7f19f0f8985806f6eeb09 at: https://669d0e2452b089798bc882c1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 359d9ca06b89c69a44818942f3ae13852368c530 at: https://669dca269dd1e02655104ab2--layer5.netlify.app

**Comment by hargunkaur286** [comment]
@akaBisht Thank you for your contribution. Let's discuss it today in website's weekly meeting. Adding this to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by l5io** [comment]
🚀 Preview for commit 11045b122e84546a769766d740fb23fdac7b87ed at: https://66a000ac662a1218d3865db1--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
