### PR TITLE
changed <img> to gatsby-plugin-image to improve performance

### LINKED ISSUE #5842: [Performance] Use gatsby-plugin-image component instead of <img> tag
### Description

Few images due to large size and taking time to render creating bad  performance to site . Use gatsby-plugin-image instead  because  lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive

### Expected Behavior
Replace in following page with gatsby-plugin-image instead  tag

In the following page:
- ### [Case study](https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap)
image

- ### [Layer5 site](https://layer5.io/)
image
image

- ### and search in code base with `alt="meshery-logo"`
 And replace those with gatsby image plugin.

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by yaten2302**
**Description**

Fixes #5842 

This PR fixes #5824 

This PR changes all the images of this section in [this link](https://layer5.io/), and replaces `` tag with `<StaticImage />` <br>
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 807b63dedeb4aabedd1e242722a04a8d9f94375b at: https://6708100b21b1093b3d602bac--layer5.netlify.app

**Comment by Touriist** [comment]
@yaten2302 Thank you for this. LGTM
Can you refer to the correct issue for this PR, if there's one ?

**Comment by Touriist** [comment]
@yaten2302 the Meshery logo being cut off
Screen Shot 2024-10-13 at 01 50 24

**Comment by l5io** [comment]
🚀 Preview for commit 3818cd36d1905ccfaabaaf6d685d5a7c38503726 at: https://670ad9d66e5649874caf9bb8--layer5.netlify.app

**Comment by yaten2302** [comment]
@Touriist , this PR fixes #5842 issue

**Comment by Touriist** [comment]
> @Touriist , this PR fixes #5842 issue
> 
> Also, I copied the meshery logo from the file path which was earlier being used to render the image. Could you please guide that is this the wrong image which I'm using?

@yaten2302 the css previously applied to the `` element might not be properly applied to the `<StaticImage>` component. We'll have to ensure existing styles target the image inside StaticImage correctly

**Comment by l5io** [comment]
🚀 Preview for commit 84213cb215356c3ff7e6df4d209b0c5b4adbf262 at: https://670cb5b6768ef85b3e210065--layer5.netlify.app

**Comment by yaten2302** [comment]
@touriist , I was checking about the styles applied to the `` tag. But, ig, I haven't removed the tags in my commit, I'm checking if there's any other error here :/

Also, I recently pulled some changes from the main repo, actually, this error is being shown to me, are you also getting this, or should I re clone this repo? <br>
image
<br>
image

**Comment by vishalvivekm** [comment]
@yaten2302 
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by yaten2302** [comment]
@vishalvivekm , ig this issue is already added in the meeting minutes 👍 
We'll surely discuss about it today 👍

**Comment by yaten2302** [comment]
@vishalvivekm @Touriist , there's some issue with this PR, I'm closing this, will create a new PR soon👍

**Pull request closed without merging**
