### PR TITLE
Few general updates

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
I think decreasing the width in brand page in making it much longer(4 colors in row > 3 colors in row). The figma design shows it less wider with respect to bigger dimension.
Views @leecalcote @Tanuj22

**Comment by Nikhil-Ladha** [comment]
> I think decreasing the width in brand page is making it much longer(4 colors in row > 3 colors in row). The figma design shows it less wider with respect to bigger dimension.
> Views @leecalcote @Tanuj22

I didn't get it. Are you suggesting to increase the width?

**Comment by Nikhil-Ladha** [comment]
I think it's in some ways good that the page is long. It depicts how good our brand guide is and hoe much detailed analysis of logos and colors we have for different projects, programs.

**Comment by Jashpatel1** [comment]
> > I think decreasing the width in brand page is making it much longer(4 colors in row > 3 colors in row). The figma design shows it less wider with respect to bigger dimension.
> > Views @leecalcote @Tanuj22
> 
> I didn't get it. Are you suggesting to increase the width?

Yes😅

**Review by Tanuj22 — APPROVED** [review]
For my part, I don't think the width should be increased more as the place will look too out of place compared to other pages then. 

We should later add a component like the one they have on the side here https://www.hashicorp.com/brand for easy navigation and more clear separation of sections

**Comment by Nikhil-Ladha** [comment]
> For my part, I don't think the width should be increased more as the place will look too out of place compared to other pages then.
> 
> We should later add a component like the one they have on the side here https://www.hashicorp.com/brand for easy navigation and more clear separation of sections

Yeah, that would look much better.

**Comment by Nikhil-Ladha** [comment]
Merging it, so that we can move ahead for the time being.

**Pull request merged**
