### PR TITLE
Add Neil to community member 

### LINKED ISSUE #1359: [Community] Member Profile: Neil Alvares
**Current Behaviour**

@Neil-140301 has been a consistent contributor and community member.

**Desired Situation**
Let's recognizing @Neil-140301 as a contributor and community member by creating a profile on https://layer5ng.netlify.app/community/members.

- GitHub: Neil-140301 
- Twitter: 
- LinkedIn: neil-alvares-2986561a0
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/layer5-ng">`layer5-ng` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

### PR DESCRIPTION
**Pull request by Anita-ihuman**
**Description**
Added  a community profile for Neil
This PR fixes #1359

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@Anita-ihuman Actually, this update was intended on the layer5-ng website. I think I mentioned it in the issue. Can you take care of it?

**Comment by leecalcote** [comment]
Contrib instructions for layer5-ng site - https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md.

**Comment by leecalcote** [comment]
@Anita-ihuman given #1364, would you like to close this PR?

**Comment by Jashpatel1** [comment]
@Anita-ihuman I think this should be closed and #1364 reopened.

**Pull request closed without merging**
