### PR TITLE
Updated the eslint config to have better parsing

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description**

This PR updates the eslint config to add more rules, such that spurious updates are avoided.
Also, the existing parser was EOL, so updated that to a newer version.

P.S: The huge changeset is because of the config updates.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 384b666d7f5e083929787e6394f3997cbd9a719d at: https://62bc34745fa1cc21b097038e--layer5.netlify.app

**Comment by leecalcote** [comment]
Cool. Thank you. Will this run as a pre-commit hook, then?

**Comment by Nikhil-Ladha** [comment]
> Cool. Thank you. Will this run as a pre-commit hook, then?

Yes.

**Comment by Nikhil-Ladha** [comment]
Merging the PR...

**Comment by Abhishek-kumar09** [comment]
@Nikhil-Ladha I think the space before `:`(colon) is way too old. The code linting practices in vscode or any other editor suggests to have no space before colon while writing objects

**Comment by Nikhil-Ladha** [comment]
I wondered for about 10 minutes or so, regarding the same thing. But, then somehow convinced myself that this would be better 😐.
 In that case, let's revert it back to only have space after colon.

**Comment by Abhishek-kumar09** [comment]
haha, Thank You @Nikhil-Ladha , Btw I know why you are convinced because the same style behaviour is used in meshery-ui. But it's gone in the new refactoring branch

**Comment by Nikhil-Ladha** [comment]
> haha, Thank You @Nikhil-Ladha , Btw I know why you are convinced because the same style behaviour is used in meshery-ui. But it's gone in the new refactoring branch

You read my mind!
That sounds good 🙂. Thanks for keeping a tab around this sweet, old, nasty repo 😉

**Pull request merged**
