### PR TITLE
spelling mistake fix 

### PR DESCRIPTION
**Pull request by kushvahasumit**
**Description**

 In the [LFX program page 2023 ](https://layer5.io/programs/lfx) , in the "multi-user cloud native playground" section , spelling is fix from "Descripto" to "Description" .

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bef287693f4e1958258dbe390b274c2099e5c33e at: https://63e7e3ebfb18ad64d05c4da6--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks great. Thank you, @kushvahasumit 👍

**Comment by kushvahasumit** [comment]
happy to learning new things in this community🎊.

**Comment by eeshaanSA** [comment]
Congratulations for your first merge, @kushvahasumit 🚀

**Comment by kushvahasumit** [comment]
thanks @eeshaanSA hope i will learn more.

**Pull request merged**
