### PR TITLE
Solved the overflow of content of community callout from smp page

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description**Solved the overflow of content of community callout from smp page /projects/service-mesh-performance

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 70fe2ef06f1637b1c50c6fc60abe6ae518895600 at: https://61b76cad2b90c723508e48e0--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c90b9ca5e53fb7c261318cf5092831700d7d1495 at: https://61b7760d8f9d11336cb1133a--layer5ng.netlify.app

**Comment by Mr-DG-Wick** [comment]
LGTM! 😄

**Review by Mr-DG-Wick — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks for this. Looking at the issue again. I'm not able to reproduce the affect that we saw on today's websites call. Are you, @yash?

**Comment by YashKamboj** [comment]
@leecalcote Yeah, when we open the page from the button on the home page but if we open the page after copying the link the callout becomes too big . This is not because of the image size as we discussed , this is because the css is overlaping.

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you sir.

**Pull request merged**
