### PR TITLE
Add patterns badge 

### LINKED ISSUE #2479: Add Patterns Badge to the Members page filter
**Current Behavior**
The filter on https://layer5.io/community/members does not contain the Patterns badge.

Members _ Layer5 - The Service Mesh Company - Google Chrome 15-01-2022 03_40_09 (2)

**Desired Situation**

Add the Service Mesh Patterns Badge as an option under the Badges category.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by verma-kunal**
**Description**

This PR fixes #2479 
Adds the Service Mesh Patterns badge to the Members page filter

img

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — APPROVED** [review]
LGTM :1st_place_medal:
good work @verma-kunal

**Comment by l5io** [comment]
🚀 Preview for commit ad9e7d3f9b629c03a033644b25cf22d24f50f4d8 at: https://61eab26e55fd2cef6b4804fd--layer5ng.netlify.app

**Comment by Chadha93** [comment]
Yes, @warunicorn19 is right, you can make a new pr @verma-kunal

**Comment by verma-kunal** [comment]
Sure! Will do that 🙂

**Comment by Chadha93** [comment]
> @warunicorn19 @Chadha93 Sure! Will do that slightly_smiling_face A direct PR would work, right? Or will have to open a new issue as well

Direct PR will work @verma-kunal

**Comment by verma-kunal** [comment]
> Direct PR will work @verma-kunal

Made it here: https://github.com/layer5io/layer5/pull/2538

**Pull request merged**
