### PR TITLE
feat: add features and hero component

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Slick improvement.

**Comment by Tanuj22** [comment]
Link to check - https://deploy-preview-1014--layer5ng.netlify.app/animated-terminal

**Comment by Tanuj22** [comment]
@leecalcote can you check this out?

**Comment by leecalcote** [comment]
I looked at this on my mobile earlier today. There may be some considerations need. Looking at desktop view now...

**Comment by leecalcote** [comment]
Screen Shot 2020-10-28 at 11 54 51 PM

We may need to provide an easier to navigate control in mobile view. 

This page is really something neat.

**Pull request merged**
