### PR TITLE
update meta description and title

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR
-  modifies meta title to avoid duplicate meta titles:
1. https://layer5.io/community/handbook/contributor-journey
2. https://layer5.io/community/handbook/community-roles
Currently both these pages have same title : `Contributor Journey`
- modifies meta description to avoid duplicate meta description:
1. https://layer5.io/community/handbook/faq
2. https://layer5.io/company/faq
Currently both these pages have same meta description : `Frequently Asked Questions`

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7926acc5908806033144654b10e9d8223db44c2a at: https://64f0aa8f3a2bd2581a5f52aa--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7d2d7acf5c2cfecddf98c32f3382a446beb1a022 at: https://64fa1080501b7232319c8cb4--layer5.netlify.app

**Comment by vishalvivekm** [comment]
This is good to merge.

**Comment by l5io** [comment]
🚀 Preview for commit 71c4b16cda8f250cb935e8456433c7a9405cb591 at: https://64fa3956615ca956265ef905--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
