### PR TITLE
[Blog] added layer5 learning resources blog

### LINKED ISSUE #2323: [Blog] Publish the Learning path blogpost
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:**  Introducing Layer5 Learning Paths
**Draft:**  https://docs.google.com/document/d/1qqGluGEePjcBl2R79M_6h6wfu81xYaFcMgeSPLNDKt4/edit?usp=sharing
**Author:** Anita Ihuman

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by hirentimbadiya**
**Description**

This PR fixes #2323 

**Notes for Reviewers**
This Blog still requires an image of learning path architecture, @ritiksaxena124 can you creat one for it.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a6c5200cf5adfdeb08fd7ab8b2ceca8d9237400a at: https://64d7c029708b801e40d1c365--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hii @hirentimbadiya
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by hirentimbadiya** [comment]
@Chadha93, i have replaced older images with new ones for learning path architecture, thanks to @ritiksaxena124.

**Comment by l5io** [comment]
🚀 Preview for commit dae069aedb3b8e1b6801460556a07aefa170a6d2 at: https://64e64ed2f0199b08a4daa233--layer5.netlify.app

**Comment by Chadha93** [comment]
@hirentimbadiya As discussed on the website's call, the blog content is not ready to be published. It needs an update. cc @Anita-ihuman

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya As discussed on the website's call, the blog content is not ready to be published. It needs an update. cc @Anita-ihuman

Sorry @Chadha93, I was busy with some of my university work these days can you suggest me what needs to be changed?

**Pull request closed without merging**
