### PR TITLE
Fixed Responsiveness issue at 320px

### LINKED ISSUE #4267: The responsiveness of some button is not working properly
### Description

The responsiveness of some button is not working properly [here](https://layer5.io/pricing)

### Screenshots

![Screenshot from 2023-05-22 23-14-22]

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Gautam-04**
**Description**
Fixed Responsiveness issue at 320px in the pricing Section
This PR fixes #4267

**Notes for Reviewers**
Screenshot (53)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3f129e1797637ce93a76e5a776815905fc4bcd00 at: https://64e0bc0d00639e4e22a747d2--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
Looks good @Gautam-04 !

**Review by thisiskaransgit — COMMENTED** [review]
Thanks @Gautam-04, this works. Have you tried updating the table margin under [prcing.style.js](https://github.com/layer5io/layer5/blob/master/src/sections/Pricing/pricing.style.js)? 
```css
  @media (max-width: 992px) {
    margin: 1.5rem 0rem;
  }
```

**Comment by Ghat0tkach** [comment]
hii @Gautam-04 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Pull request closed without merging**
