### PR TITLE
[Screenshots] Citrix Service Mesh under 'How it Works See It in Action' sectio

### LINKED ISSUE #4880: [Screenshots] Citrix Service Mesh under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/citrix-service-mesh) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Citrix Service Mesh](https://layer5.io/cloud-native-management/meshery/integrations/citrix-service-mesh) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by coder12git**
**Description**

This PR fixes #4880

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Mohith234** [comment]
@coder12git Please fix the errors that are causing `Site Preview` and `Lighthouse` checks

**Comment by coder12git** [comment]
> @coder12git Please fix the errors that are causing `Site Preview` and `Lighthouse` checks

Sure

**Comment by coder12git** [comment]
@Mohith234 I tried to fix this error, and found that in images folder for all images that are added in the site has a ```.webp``` file too along with ```.png```. So I want to ask that whether is this causing those errors?

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by l5io** [comment]
🚀 Preview for commit 7dd8e37bf7bc4d745f1a5aac0bf86a05468433fe at: https://6519c566c575e3025da46cd1--layer5.netlify.app

**Comment by coder12git** [comment]
> @coder12git Please fix the errors that are causing `Site Preview` and `Lighthouse` checks

Done @Mohith234

**Comment by coder12git** [comment]
> Let's discuss this in tomorrow's website meeting, Please add it in the Doc, If you would ^^: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edi

**Comment by coder12git** [comment]
Sorry, I closed this PR by mistake, as the operation can't be revert, so I am opening new one.

**Pull request closed without merging**
