### PR TITLE
Change meta image and title for Community Member Form

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**
I've added a meta image and changed the title for community member form

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 65907fee3afa2e8cdfe0a9048cf0e7403a779ea2 at: https://619f4add38e1538c8c72816f--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
Thanks for the effort @theBeginner86, but i dont think this a required change. @leecalcote thoughts?

**Comment by theBeginner86** [comment]
Actually this was with respect to this message on slack: https://layer5io.slack.com/archives/C011VPREG2Z/p1637771880103600?thread_ts=1637770268.102700&cid=C011VPREG2Z

**Comment by warunicorn19** [comment]
Oh okay, gotcha! But i think @leecalcote is referring to this image. 
Layer5-mentor-program

**Comment by theBeginner86** [comment]
> Oh okay, gotcha! But i think @leecalcote is referring to this image.
> Layer5-mentor-program

Ohh!! I'll change it 👍

**Comment by warunicorn19** [comment]
Couldn't find the one without the white background, you'll be able to see it in the readme of this repo. And he said to use it in the `meta` and not add it to the page. You'd have to make changes here https://github.com/layer5io/layer5/blob/master/src/pages/newcomers.js and basically change the image in the title( the one that is going to present in the tab)

**Comment by leecalcote** [comment]
Thank you, @warunicorn19. That’s right.

**Comment by theBeginner86** [comment]
Thanks, @warunicorn19 for your help 
Can you please have a look again?

**Comment by l5io** [comment]
🚀 Preview for commit d66cc2135111a5da8f99a72c89fa70a01bc94e76 at: https://619fc6292458c7009904f4f2--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
@theBeginner86  ( just a suggestion ) it looked better with the image, looked more interactive.

**Comment by leecalcote** [comment]
@theBeginner86, while you're in here, do you mind changing the tooltip message for required files to "please fill-in this field"? image

**Comment by theBeginner86** [comment]
> @theBeginner86, while you're in here, do you mind changing the tooltip message for required files to "please fill-in this field"? image

Done!!
Please check PR: https://github.com/layer5io/layer5/pull/2384

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @theBeginner86

**Pull request merged**
