### PR TITLE
made banner svg responsive

### LINKED ISSUE #4186: Banner image not responsive on mobile devices
### Description
Banner image not responsive on mobile devices

### Expected Behavior
Banner image should be responsive on mobile devices

### Screenshots
448237c7-b5d4-43f4-afbc-012f70478500

### Environment:
- Host OS: Android
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4186

[Screencast from 05-05-23 10:10:41 PM IST.webm](https://user-images.githubusercontent.com/92908347/236517039-98a8f2a4-5b04-4d89-a563-15c4dd0acaf4.webm)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e2ad692f5d2c9bf66988b9500490783dbf5fe866 at: https://6455362a06844b10a68a0729--layer5.netlify.app

**Comment by leecalcote** [comment]
Mr. @randychilau, I wonder if you might offer a review here...

**Review by randychilau — APPROVED** [review]
Nice job @AkashS20 working with the media queries!

The video showing the banner image responding to the browser size looks good.

Also, doing a side by side comparison to the current site (on the left) to your changes (on the right) at the different phone sizes shows the improvement:

iPhone SE
image

iPhone 12Pro
image

LGTM!

**Comment by leecalcote** [comment]
Thank you, gents!

**Pull request merged**
