### PR TITLE
Custom embedding video

### LINKED ISSUE #2968: [Site] Custom Embedded Video Player
**Current Behavior**
Currently for adding/embedding video to the site we are just using <iframe> due to which its customization availability limits us. 

**Desired Behavior**
Use [gatsby-remark-embed-video](https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video) plugin for sourcing a video. It will allow us to write custom components for videos such as controllers and thumbnail customization etc.

---
**Resources*
Do follow this resource and read the documentation before implementation:

- https://www.gatsbyjs.com/docs/how-to/images-and-media/working-with-video/
- https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video

**Acceptence**

- The component should be reusable across the project.
- Should allow adding custom thumbnails as png/jpeg/svg.
- Let enable/disable controls over videos.

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by legendarykamal**
**Description**

Currently for adding/embedding video to the site we are just using <iframe> due to which its customization availability limits us.

The idea behind is to use [gatsby-remark-embed-video](https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video) plugin for sourcing a video. It will allow us to write custom components for videos such as controllers and thumbnail customization etc.

This PR fixes #2968 

**Notes for Reviewers**
I am pushing step by step to see the integration with the main site.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 406e313cd5344bef4e8dc4576ace7e781baa982a at: https://63386053a7b24e13291960ce--layer5.netlify.app

**Comment by debo19** [comment]
@legendarykamal will you discuss this on the websites call today?

**Comment by Nikhil-Ladha** [comment]
Any updates on this @legendarykamal ?
Where are you stuck at?

**Comment by legendarykamal** [comment]
hey @Nikhil-Ladha due to lack of proper resources and docs, I am finding myself stuck here .
image

image

image

image

**Comment by warunicorn19** [comment]
@Nikhil-Ladha I don't think you uploaded the screenshot here 😅.

**Comment by Nikhil-Ladha** [comment]
Yeah for some reason it is stuck at uploading 😑.
Though, hint for Kamal: We use "MDX" (though that should be evident from the file format 🌚)

**Comment by Nikhil-Ladha** [comment]
Screenshot from 2022-10-31 19-16-52

Here you go

**Comment by eeshaanSA** [comment]
@legendarykamal are you still working on this?

**Comment by eeshaanSA** [comment]
@legendarykamal 👀

**Comment by legendarykamal** [comment]
no ser. You can take on it , If you wish @eeshaanSA

**Comment by leecalcote** [comment]
Thanks for this initial effort. Given that it has been abandoned, let's close this PR.

**Pull request closed without merging**
