### PR TITLE
Home/banner 3

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 853c09f58f7510a33c159996f3a712f44fa47eec at: https://6053236b435a7de8aad1e963--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Screen Shot 2021-03-18 at 9 27 00 AM

**Comment by vineethvanga18** [comment]
@leecalcote Yes this is weird. Dont know why. Please pull in these changes.
banner

**Comment by Tanuj22** [comment]
@vineethvanga18 I am getting this issue on my mobile but not on my laptop

**Comment by vineethvanga18** [comment]
> @vineethvanga18 I am getting this issue on my mobile but not on my laptop

For the deploy preview?

**Comment by Tanuj22** [comment]
Yeah

**Comment by vineethvanga18** [comment]
Iam facing the same issue with both mobile and laptop

**Comment by vineethvanga18** [comment]
It appears to me that there is a problem with css. The same css for the default banner is getting applied for all the banners

**Comment by l5io** [comment]
🚀 Preview for commit 6e23f11c5a47f6534fcf87d27628014264d71175 at: https://6054b0b59f5987398b027d56--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 660ac2b5ce9da9ceec9afdd21883846631eaa79b at: https://6054cfa4d83fa600c1bb9276--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4d443b97e0403a777233107df32d6f3facbd32ef at: https://6054d3bebae527007d9b51a7--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
One thing though, which I wanted to confirm shouldn't the banner change on a page reload?
It changes on moving to a sub-link and coming back to the home page, but not on reload.

**Comment by l5io** [comment]
🚀 Preview for commit b62d256dcd2c52f92366adbdeae6dc71a83bb312 at: https://6054dc23ce692516264606e9--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 05b6451c7ea1a55ab7357ec30da7a4f6f995fcab at: https://6054e349fc8a061c7c44c308--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3caab6f9db2ed645ebad69dc6f5ad3d6adee4036 at: https://6054ec97369ba22c9ee3f261--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 34b07744f98460134f09e3ddf01fe9aa8cc111ec at: https://6054f219d83fa62c27bb95cc--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f458fa6ceaeb3090327f67d9a8225b6792f1de7a at: https://60558a57b16f084463aa6d5b--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
LGTM. Just one problem. The text is not visible for smaller screens 

Screenshot from 2021-03-20 15-26-04

**Comment by vineethvanga18** [comment]
@Tanuj22 yes. Do you have any suggestion?

**Comment by l5io** [comment]
﻿Slide the cards down and to the right a bit  Left-align the text, “ The Layer5 community represents the largest collection of service mesh projects and their maintainers in the world.”

**Comment by l5io** [comment]
🚀 Preview for commit b6194ed8609547ae490363836ac1c58cde55ef10 at: https://60578d36d60627fe4b38a14d--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@vineethvanga18 this is close. If you move the two cards off to the right a bit more and the page contracts in width, we'll avoid any overlap.
Screen Shot 2021-03-21 at 2 07 27 PM

**Comment by l5io** [comment]
🚀 Preview for commit ec963fba0c1a55a31766513aef9ff6c233567f4b at: https://6057ba2496e97a92163cc245--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Yay, @vineethvanga18! 💯 You nailed it. 😄

**Pull request merged**
