### PR TITLE
fix GitHub logo for dark mode

### LINKED ISSUE #3785: [UI] The GitHub logo should be replaced with light-version when site in dark-mode
### Current Behavior
when in dark mode the GitHub logo is in black on https://layer5.io/cloud-native-management/meshery/operating-service-meshes

logo-error

### Desired Behavior
The GitHub logo should be replaced with the light version of it when the site is in dark-mode 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### LINKED ISSUE #3789: [UI] The SCA logo should be replaced with light-version when site in dark-mode on Programs page
### Description
The SCA logo is not so visible in dark mode

### Expected Behavior
The color of the SCA logo should be visible in darkmode on the Programs page. And able to toggle between light mode and dark mode.
Find the various SVG files to the logo here
- https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T

### Screenshots
Screenshot 2023-02-20 at 9 49 32 AM

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by nerdynikhil**
**Description**

This PR fixes #3785 

**Notes for Reviewers**

Before
Screen Shot 2023-02-20 at 6 13 40 PM

After
Screen Shot 2023-02-20 at 6 11 50 PM

I used only the existing assets. However, the light logo seems to be a bit larger. Need advice on this.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5940c0660cc511776a0c98a07c12aebd6b511337 at: https://63f3746aeeaea55a548d23b4--layer5.netlify.app

**Review by UtkarshMishra12 — CHANGES_REQUESTED** [review]
@nerdynikhil  You are right, the logo should be the same in both modes. Please change it as per the needs.

**Comment by nerdynikhil** [comment]
> @nerdynikhil You are right, the logo should be the same in both modes. Please change it as per the needs.

Should I resize it myself and upload it to assets so that it can be used? @UtkarshMishra12

**Comment by UtkarshMishra12** [comment]
> > @nerdynikhil You are right, the logo should be the same in both modes. Please change it as per the needs.
> 
> Should I resize it myself and upload it to assets so that it can be used? @UtkarshMishra12

@nerdynikhil  Yes, you can. Or you can look into the assets for the image, maybe you'll be able to find one.

**Comment by nerdynikhil** [comment]
Yes, I tried `src/assets/images/socialIcons/github_white_trim.svg` but this has a white outline that looks absurd. I will upload a new resized asset.

**Comment by Chadha93** [comment]
@nerdynikhil  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
Hey @nerdynikhil, resizing the assets would work. Also the MeshMap icon is a bit larger than the others because of it's different aspect ratio.  Let's have it consistent as well, `height: 48px, width: 48px`.

Also let's try to keep the PR free from indentation changes. It just makes reviewers life a little easy 😀

**Comment by AbhiiVops** [comment]
Hello @GaganpreetKaurKalsi ,

I hope this message finds you well. I am writing to express my interest in contributing to the project and fixing issue #3791, which is related to **fixing the GitHub logo for dark mode.**

I have experience working with CSS and web design, and I believe I can help address this issue. I have also read through the project's contribution guidelines and code of conduct, and I'm committed to following the established best practices and protocols.

Would it be possible to assign this issue to me? I would be happy to collaborate with other team members and ensure that the logo is properly updated for dark mode users.

Thank you for your consideration, and I look forward to contributing to the project.

Best regards,
**Abhishek Bhattacharjee**

**Comment by nerdynikhil** [comment]
Hey reviewers, I started a thread a Slack on this. Kindly take a look at it and advice. https://layer5io.slack.com/archives/C015QJKUMPU/p1677522842958589

**Comment by nerdynikhil** [comment]
I’m guessing the page http://localhost:8000/cloud-native-management/meshery/operating-service-meshes itself has some CSS issue which is causing SVGs to appear larger in dark mode. For instance look the `meshery-operator-dark.aabaafd9.svg` image closely while switching to dark mode.
Likewise, the existing Github logo (svg) in assets would suffice, but we probably need some minor CSS change. Need advice on this.

ezgif-1-3e992acad2 (1)

**Comment by nerdynikhil** [comment]
@Udit-takkar is working on this.

**Pull request closed without merging**
