### PR TITLE
[Home Page] Slider dots not visible in Brands carousel in dark mode #…

### LINKED ISSUE #4336: [Home Page] Slider dots not visible in Brands carousel in dark mode
### Description
There is a slider on the home page of https://layer5.io/ that features the partner brands. The slider dots are visible in light mode but not in dark mode. The color "#CCC" can be used for inactive dots in dark mode.

image

image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Manish254252**
…4336

**Description**

This PR fixes #4336 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9a1eca3e95c9aa4832555997cebb2b11ff30794e at: https://649054cbbb4a6666cc46b1e9--layer5.netlify.app

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@Manish254252 , I don't see slider dots are visible please change the color "#ccc" as @Shivam-AfA mentioned in issue.

**Comment by Savio629** [comment]
@Manish254252 Please incorporate the above changes!

**Comment by hirentimbadiya** [comment]
any updates @Manish254252 ??

**Pull request closed without merging**
