### PR TITLE
Add Adapter Pattern to Configuration Patterns 

### PR DESCRIPTION
**Pull request by nomstradamus**
**Description**
We can use a WASM filter to do protocol conversion from let's say JMS to Kafka or Apache Pulsar. This capability relieves us from the burden of maintaining sdk in different languages. Also with meshery support the application of filters for protocol conversion can be a self service task. Any upgrade to filter would not require the clients/ customer upgrading their code.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.
 Signed-off-by: Gagandeep Singh < nomstradamus@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
// @nicholasjackson

**Comment by l5io** [comment]
🚀 Preview for commit afe278d4909d5f61721fe5e6b95ddc429bc3cafb at: https://608b0b5b9b627d59e49deab3--layer5ng.netlify.app

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks, @nomstradamus 
Just a small piece of feedback, Would you mind signing off the PR, so that we can proceed with this PR. Signing instructions are given in the contributing guide.

**Comment by nomstradamus** [comment]
I have done it . Please let me know if anything else needs to be ddone.

**Review by leecalcote — APPROVED** [review]
Looking good, @nomstradamus!

I'm pleased that you joined today's call and hopeful that you might find a foothold in an area of one the projects. It's fantastic to have you engaged. 👍 Here's a link to one of the projects we spoke of - https://github.com/layer5io/image-hub. The #wasm channel in the community Slack is active currently with chatter on the next phase of this project.

**Pull request merged**
