### PR TITLE
fixed npm build in service-mesh-landscape page

### LINKED ISSUE #4090: Errors in service-mesh-landscape page when using npm build
### Description

`npm start` or `make site` build is failing on page https://layer5.io/service-mesh-landscape, this error is not occurring when building with `gatsby`

### Video

[Video](https://user-images.githubusercontent.com/92908347/231837267-dc0af1b4-d7a9-4820-970d-9cc6d26412c2.webm)

### Expected Behavior

The build should not break.

### Environment:
- Host OS: Linux
- Browser: Edge

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4090 
The service-mesh-landscape page is now behaving as expected

[Video](https://user-images.githubusercontent.com/92908347/232122695-77d066d8-8626-4254-8f27-320bd133358a.webm)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 78d9abef5b93067ac9a3eb8e7b92f51034891dd1 at: https://64399aa406036e1d06172115--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Do you have any reference to support this change?

**Comment by AkashS20** [comment]
@Nikhil-Ladha I followed [this](https://stackoverflow.com/questions/53558916/babel-7-referenceerror-regeneratorruntime-is-not-defined?noredirect=1&lq=1) answer on stackoverflow

Screenshot from 2023-04-15 00-19-54

I found that the build still works even if I don't add `import "core-js/stable"`

**Comment by Nikhil-Ladha** [comment]
Yeah, because the issue is being caused by the usage of `regenrator-runtime` in the `react-table` package. So, importing `core-js` is not mandatory here.

**Review by Nikhil-Ladha — APPROVED** [review]

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
