### PR TITLE
Added alt tag and aria role in play button

### LINKED ISSUE #4266: [Accessibility] Play button for cloud native program video on home page is an image without an alt tag
### Description
The video play button is an image without an alt. This will cause accessibility issues and will not allow tools like screen readers to understand what the image tag is and if it is a button to play a video.

I would like to work on this issue

### Expected Behavior
The image should have an alt attribute as well as aria-role set as button to improve the accessibility for the play button.

### Screenshots
Following is the play button we are talking about:
image

Following is what lighthouse has to say about the issue:
play button

### Environment:
- Host OS: Windows
- Browser: Brave

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #4266 
i have solved this issue now the alt attribute is added and aria role is added .
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f22ca2647aae499d68fbaa81be0b669224700722 at: https://647474071619086290f2ece7--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@surajvast1 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by surajvast1** [comment]
Yaa sure ! I have asked for the document access on my I'd

**Comment by surajvast1** [comment]
Yaa i have filled it I mistook it with other id . Thanks i have filled the doc file

**Comment by Shivam-AfA** [comment]
Thanks @surajvast1 for this.

**Comment by l5io** [comment]
🚀 Preview for commit 1a633fe91db6c6b0e943351201b7f88c99a94f6d at: https://6486ffec561c6a1e6da5e920--layer5.netlify.app

**Pull request merged**
