### PR TITLE
Update posthog-color.svg to actual logo of PostHog

### PR DESCRIPTION
**Pull request by crazyshrut**
Updated to actual logo of PostHog. 
Earlier it was, Postgres logo at the place of PostHog

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e57c558cc4e65a5ed88d58ada59be691d843d018 at: https://66bca3f5450da3937f65c418--layer5.netlify.app

**Comment by crazyshrut** [comment]
Hey @Ashparshp , kindly merge the PR that I have raised.

**Comment by Ashparshp** [comment]
@narasimha-1511, why did you close this?

**Comment by crazyshrut** [comment]
narasimha closed this.

**Pull request closed without merging**
