### PR TITLE
Add member profile: Naimot Oyewale

### LINKED ISSUE #1910: [Community] Member Profile:  Naimot Oyewale
**Current Behavior**

 @Naimaoye has been a consistent contributor and community member.

**Desired Situation**
Let's recognize  @Naimaoye as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Naimaoye
- Twitter: @Naimatoyewale
- LinkedIn: Naimot Oyewale
- Link to profile picture: https://drive.google.com/file/d/16iN2eERaTCSSAqtgcfVcTSCN4ljI4y63/view
- About: A software engineer with experience building robust
web applications. In the last two years, I have focused on API development, USSD application development, cloud computing, API documentation, End to End test
with various technologies.
- Location: Lagos, Nigeria

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Blakelist7**
Signed-off-by: Blakelist7 <kanwal.88singh@gmail.com>

**Description**
Added new member profile: Naimot Oyewale
This PR fixes #1910 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — COMMENTED** [review]
The **image_path** should be named as firstname-lastname.jpg/png/jpeg and so is the image name so that the pattern remains same for every member.

**Review by sayantan1413 — COMMENTED** [review]
I saw that there are some changes made in **package-lock.json** file which I think is not required.

**Review by sayantan1413 — COMMENTED** [review]
Actually I told you not to commit any changes in the package-lock.json. Only the changes to be made are in **index.mdx** and the **image file**. In the **files changed** tab you must see that there are 2 files changed. But in your pr you can see that there are 3 files changed which include the package-lock.json which is not requred.

**Comment by Blakelist7** [comment]
So, now should I close this PR and create a new one?

**Comment by sayantan1413** [comment]
Yes I think it would be better.

**Pull request closed without merging**
