### PR TITLE
Fix overflow by making row to flex-wrap

### LINKED ISSUE #6038: Text Overflow on all internship pages and are not responsive
### Description
- `Apply By` and `Layers` text are merging.
- On Zoom `Stipend` text goes out of the box.
issue at : https://layer5.io/careers/digital-marketing-internship

### Screenshots
1)
Screenshot (258)
2)
Screenshot (259)

### Expected Behavior
Need to work on Css for above issues.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vrushabhgawas14**
**Description**
Added a class `job-details-row` to ROW of COL with class `job-details`.
Made Row to flex wrap so it will not overflow.

This PR fixes #6038

**Notes for Reviewers**
flexwrap

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d06507f683bd0b7eb84019b9773daff1e6c066c6 at: https://67279d2f388ea8504a5762fa--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@vrushabhgawas14 
Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by vishalvivekm** [comment]
> @vrushabhgawas14 Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

added. // @vrushabhgawas14 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0

**Comment by narasimha-1511** [comment]
@Ashparshp

**Review by leecalcote — APPROVED** [review]
Excellent. Thank you, @vrushabhgawas14 👍

**Pull request merged**
