### PR TITLE
FIX #4690 Change route path from /projects to /products

### LINKED ISSUE #4690: Change route path from /projects to /products
## Description
Recently we switched from projects to products, and the routes (URL path) were not updated.

## Expected Behavior
Please update all the /projects to /products in the site, and ensure sure by testing and visiting all the products/projects.

## Important

 Please make sure your PR doesn't break  all of the existing links to the projects pages. You need to ensure that redirects are in place for site-external references and updates are made for all site-internal references. 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Aryan8912**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5a41a64bbe3b10ce3bad00ec8a7936a7f1a59536 at: https://64d12b36cfa0d7009559b28d--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks! Unfortunately, this consideration isn't this simple.

**Comment by Shreya111111** [comment]
@leecalcote we have to make changes here right as stated in ur issue can u assign this to me 
pro

**Comment by Chadha93** [comment]
@Aryan8912, @Shreya111111 has an open PR on this, with a followup comment.

**Comment by Chadha93** [comment]
> @Aryan8912, @Shreya111111 has an open PR on this, with a followup comment.

@Aryan8912 I'm closing this PR, as this will be archived.

**Pull request closed without merging**
