### PR TITLE
added meshery quotes

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Shivam-AfA this is a nice-looking style. The animation is fine as well except that it animates at in opportune moments.

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA this is a nice-looking style. The animation is fine as well except that it animates at in opportune moments.

@leecalcote Is the timing not good? What should be changed?

**Comment by leecalcote** [comment]
@Shivam-AfA When I reach the bottom of the page, the animation invokes again, even though the quote is about halfway off the screen at that point,

**Review by Udit-takkar — COMMENTED** [review]
Your code looks good but the component that you are using ishttps://github.com/layer5io/layer5/blob/master/src/components/Inline-quotes/index.js#L84 uses setquoteInView inside component body directly. is this a recommended practise ?

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA When I reach the bottom of the page, the animation invokes again, even though the quote is about halfway off the screen at that point,

For this I can eliminate the delay, so that the animation takes place quickly as soon as the quote appears in the viewport.

**Comment by Shivam-AfA** [comment]
> Your code looks good but the component that you are using ishttps://github.com/layer5io/layer5/blob/master/src/components/Inline-quotes/index.js#L84 uses setquoteInView inside component body directly. is this a recommended practise ?

Thanks for pointing this out @Udit-takkar. The code can be modified to use the setquoteInView function when the component mounts. I suppose the useEffect hook would help implement this functionality.

**Comment by vishalvivekm** [comment]
> > Your code looks good but the component that you are using ishttps://github.com/layer5io/layer5/blob/master/src/components/Inline-quotes/index.js#L84 uses setquoteInView inside component body directly. is this a recommended practise ?
> 
> Thanks for pointing this out @Udit-takkar. The code can be modified to use the setquoteInView function when the component mounts. I suppose the useEffect hook would help implement this functionality.

@Shivam-AfA Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 9ad8c39c646cffcf4d422992633255a17fc1459c at: https://6433fb14f3fded0816d152eb--layer5.netlify.app

**Pull request merged**
