### PR TITLE
fix: reduce bundle size by removing nuka-carousel

### PR DESCRIPTION
**Pull request by Udit-takkar**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 681eb0c4d86993e1f2a1bf9990692d92d034e510 at: https://644ccf182155016c5e6b81ca--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 36444cefd1ae94e0fcc4fe978157b5d101c2d7f5 at: https://6458ee9e0554c8331143f13f--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Merge conflicts @Udit-takkar ...

**Comment by ayushthe1** [comment]
@thisiskaransgit  Let's discuss this on websites call. Add this as an agenda item in meeting minutes if you would :).
I'll add this item for you if it's ok.

**Comment by Udit-takkar** [comment]
@ayushthe1 i already discussed this before in the meeting. fixing conflicts now

**Comment by l5io** [comment]
🚀 Preview for commit 2a120d41a530d1f2509996fea8820e6e76d5f2cc at: https://646b2d1475ecde005759255b--layer5.netlify.app

**Pull request merged**
