### PR TITLE
Hovering Built-In Integrations Card Buttons text black

### LINKED ISSUE #4568: Hovering Built-In Integrations Card Buttons text black
### Description

Build In Integration Page bottom, second card color change to black on hovering. 

Idle:
Screenshot (22)
Screenshot (19)

### Expected Behavior

It must look like the first card. 

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by shivankurchavan**
**Description**
someone had overwritten the button css, so it is fixed.

This PR fixes #4568 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4e6080859f10c2291b216d9f8748f97d4c2eb34d at: https://64c4e83c23a9c35909205af6--layer5.netlify.app

**Comment by Savio629** [comment]
If we don't need previous css then we can remove it,wdyt @vaibhav-xt

**Review by DarrenDsouza7273 — APPROVED** [review]
Good work @shivankurchavan, I suppose the un-used css can be eliminated.

**Comment by vaibhav-xt** [comment]
> If we don't need previous css then we can remove it,wdyt @vaibhav-xt

@leecalcote What do you think?

**Comment by leecalcote** [comment]
This s works in both light and dark mode?

**Comment by vaibhav-xt** [comment]
> This works in both light and dark mode?

Yes, this is compatible with all docs. 

@leecalcote I think you missed the message posted in the issue. 
`
@leecalcote & @vishalvivekm what is your opinion?
My opinion is to close this issue by making a pull request via @shivankurchavan. Will raise another issue for this issue as button enhancement. I found thorough out the websites on hovering yellow buttons text color turns to white and not following Figma design. Check out Figma design which also said to make it rounded for the mobile section.
`

**Comment by Ghat0tkach** [comment]
@shivankurchavan 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by thisiskaransgit — APPROVED** [review]
@shivankurchavan Looks good to merge, thank you for your contribution :tada:

**Comment by shivankurchavan** [comment]
Thank you @thisiskaransgit and @DarrenDsouza7273 for the review. When can I expect the merger of this issue?

**Review by abhijeetgauravm — APPROVED** [review]
LGTM @shivankurchavan !

**Comment by leecalcote** [comment]
Thank you, @shivankurchavan, @thisiskaransgit, @vaibhav-xt, @Savio629 👍

**Pull request merged**
