### PR TITLE
Fixed the dark mode colors of table on Service mesh patterns page and removed the bg-color of the book cover image

### LINKED ISSUE #4271: [UI] Dark Mode Color Issue in Table at Service Mesh Patterns page
### Description
The table at Service Mesh Patterns [page](https://layer5.io/learn/service-mesh-books/service-mesh-patterns) seems to have Dark Mode Color issues.

image

image

### Expected Behavior

The Color of the Header of table does not turn white.

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by niranjan-kurhade**
**Description**
In this PR I have fixed the colors of the table in dark mode on this [page](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)

Also removed the background-color from the book cover image.
This PR fixes #4271 

Previous Behavior- 
image

Updated Behavior-
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eb51a417a2b9189ddd0253c979c813c04bc47d2f at: https://646e0dc494b0470f8913cf8f--layer5.netlify.app

**Review by Nikhil-Ladha — COMMENTED** [review]
While you are there, can you please remove the redundant `background-color` property from the book cover image on the top-right?

**Comment by niranjan-kurhade** [comment]
> While you are there, can you please remove the redundant `background-color` property from the book cover image on the top-right?

Sure, I'll do it!

**Comment by niranjan-kurhade** [comment]
> > While you are there, can you please remove the redundant `background-color` property from the book cover image on the top-right?
> 
> Sure, I'll do it!

@Nikhil-Ladha Removed the background-color of the book cover image.

**Comment by Nikhil-Ladha** [comment]
The DCO check is failing, please follow the steps mentioned [here](https://github.com/layer5io/layer5/pull/4279/checks?check_run_id=13752797106) to fix it.

**Comment by l5io** [comment]
🚀 Preview for commit e97b3fb9cb586dd887e0f78e439ce22c982142fd at: https://646f3d5a2716b6062f29e2b5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ab7cc50c997c2da80b19497130ed0699ebd212cb at: https://646f4456ee30e80bc2530711--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
