### PR TITLE
fix: separate eslint check

### PR DESCRIPTION
**Pull request by dottharun**
Signed-off-by: Tharun T <tharun242424@gmail.com>

[Do not merge]

**Description**

This PR fixes #
- separates eslint CI check
- update about linting in CONTRIBUTING.md
- fix eslint err introduced in #5681 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
Please rename the file with specific like eslint-check

**Comment by dottharun** [comment]
> Please rename the file with specific like eslint-check

I was planning to add prettier checks in this file too in the future. Similar to sistent [here](https://github.com/layer5io/sistent/blob/master/.github/workflows/checks.yml)

**Comment by l5io** [comment]
🚀 Preview for commit 56d44a043e56732fb2b0533312ca60cae3efe144 at: https://669fd2636823e46230928170--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@dottharun can you quickly fix that 1 error so we can merge this and other pr can have build to pass

**Comment by sudhanshutech** [comment]
> @dottharun can you quickly fix that 1 error so we can merge this and other pr can have build to pass

oh you already did right?

**Comment by l5io** [comment]
🚀 Preview for commit c6f8e927267d05bb155b82f81e1150466fea1b50 at: https://669fd7c439ab4e637e5c9134--layer5.netlify.app

**Pull request merged**
