### PR TITLE
[UI] change the bullet colors in handbook w/signoff

### LINKED ISSUE #2136: [UI] change the bullet colors in handbook
**Description**
The bullets used in the handbook are in kepel green as of now.

**Expected Behavior**
All the bullets should be changed to the charcoal. (please use from theme)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by shreyaansjain**
Signed-off-by: shreyaansjain <shreyaansjain60@gmail.com>

**Description**
Change the bullet colors in handbook

This PR fixes #2136 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @shreyaansjain. Heads-up: there's a merge conflict on the package.json.

**Comment by leecalcote** [comment]
Also, there shouldn't be a need for changes to the package.json file. Will you consider removing change to this file from this PR?

**Comment by shreyaansjain** [comment]
So i need to remove the package-lock.json file from pull request that is commit and add only that file from which i changed the color ?

**Comment by l5io** [comment]
🚀 Preview for commit 9d865b82ad9750162479ec8eedd3c7ae63828a79 at: https://612e4a002f7934313529562c--layer5ng.netlify.app

**Review by debo19 — CHANGES_REQUESTED** [review]
Looks good @shreyaansjain. Can you change the bullet color on [this](https://612e4a002f7934313529562c--layer5ng.netlify.app/community/handbook/learn-layer5) page to charcoal too?

**Comment by shreyaansjain** [comment]
Aren't they already in charcoal colour?

**Comment by warunicorn19** [comment]
@shreyaansjain They are in dark jungle green if I'm not wrong

**Review by warunicorn19 — APPROVED** [review]
LGTM code-wise🎉, thanks @shreyaansjain

**Comment by shreyaansjain** [comment]
Sorry i was wrong i made the changes now

**Comment by shreyaansjain** [comment]
What is lgtm code wise ?

**Comment by l5io** [comment]
🚀 Preview for commit ace397560415d896d0e76363cb2ce93d983c3c77 at: https://612f392dd090279e961ab8ca--layer5ng.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM 👍

**Pull request merged**
