### PR TITLE
Fixed the typo error in the Makefile file 

### LINKED ISSUE #3624: Typo Error in Makefile
#### Description
There is a typo error in Makefile file. While trying to use `make clean` , it popups a message of no command found. It is because the makefile contains a semicolon and a backslash. 

#### Screenshots

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Savio629**
Signed-off-by: Savio629 <diassavio629@gmail.com>

**Description**

This PR fixes #3624 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cb78770adb089a22a3dd1568fccb2c85edaad526 at: https://63c304cc6b470a3ffd739b70--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
@leecalcote Is this a valid issue?? // @Chadha93

**Review by Shivam-AfA — COMMENTED** [review]
Well this issue seems valid @leecalcote @UtkarshMishra12 @Chadha93 since it does give an error when `make clean` command is executed.

**Comment by Savio629** [comment]
#### OS : Windows
#### While using make clean command, the following error would occur : 


#### Successful execution after removing the semicolon, backlash :

**Comment by leecalcote** [comment]
Confirm this change works on Linux and macOS, please.

**Comment by Nikhil-Ladha** [comment]
The better way to go here would be `gatsby clean && make site`. This would work across all the OS without any issues.

**Comment by Savio629** [comment]
@Nikhil-Ladha 
So rather than : 
```
gatsby clean
make site
```
Change it to :
`gatsby clean && make site`

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha So rather than :
> 
> ```
> gatsby clean
> make site
> ```
> 
> Change it to : `gatsby clean && make site`

Yes 👍🏼

**Comment by Savio629** [comment]
Done @Nikhil-Ladha 👍

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
