### PR TITLE
Extra column space in mobile view

### PR DESCRIPTION
**Pull request by vermabraj**
**Description**
I have fixed this problem, there was problem in mobile/tablet view or in between 900px-1000px that i have fixed, please look at this PR
This PR fixes #
Extra column space in mobile view #4716
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2f4096ba79064b2d7aaf0e46265f1d98939bba63 at: https://64d3c454d41d05009d88099b--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
@vermabraj Please mention this PR fixes which issue!

**Comment by leecalcote** [comment]
Thank you, @vermabraj

**Comment by vermabraj** [comment]
@leecalcote now its done or needs to do anything for this PR or issue

**Comment by l5io** [comment]
🚀 Preview for commit a41480340a22cf69a29025640c52f1e036283839 at: https://64d46ed4e507b22c775dccf0--layer5.netlify.app

**Comment by Chadha93** [comment]
@abhijeetgauravm No update?

**Comment by vermabraj** [comment]
@leecalcote can anyone help me with DCO failed issue ?

**Comment by leecalcote** [comment]
@vermabraj follow the instructions and the details link of the field check.

**Comment by l5io** [comment]
🚀 Preview for commit d61c24b13ccafb39a88fdf527a59cd2877eca6ed at: https://64ee2c594fe00e0673622406--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 17c9337151d179d490aa2795bc6fd1da93282633 at: https://64f0d3302e5ef21687f18847--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@vermabraj 
Still missing DCO @vermabraj and conflicts.
Please address these issues.

**Comment by Chadha93** [comment]
> @vermabraj Please mention this PR fixes which #issue ? and also sign off your commit as DCO check is failing!

@vermabraj This is still unaddressed, please consider opening the issue first. I'm closing this issue seeing no response and and activity.

**Pull request closed without merging**
