### PR TITLE
Reviews Added (on the Pricing & MeshMap Page)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Reviews Added (on the Pricing & MeshMap Page)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Don't use PNG for photos. Use JPG.

**Comment by leecalcote** [comment]
Build is failing...

**Comment by UtkarshMishra12** [comment]
@leecalcote  I've changed the image format from png to jpg but still, the build is failing. 🤔

**Comment by leecalcote** [comment]
Thanks. The image format is separate from the failing build.

**Comment by leecalcote** [comment]
Rebuilding

**Comment by l5io** [comment]
🚀 Preview for commit 6616f6a86dae17407ca0cc1da013b62f5b4b3d2b at: https://63d3d8f0832603279e534e56--layer5.netlify.app

**Pull request merged**
