### PR TITLE
Create Introducing Layer5 Learning Paths

### LINKED ISSUE #2323: [Blog] Publish the Learning path blogpost
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:**  Introducing Layer5 Learning Paths
**Draft:**  https://docs.google.com/document/d/1qqGluGEePjcBl2R79M_6h6wfu81xYaFcMgeSPLNDKt4/edit?usp=sharing
**Author:** Anita Ihuman

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by akshayamadhuri**
**Description**
A new blog post fitting the following description is requested to be written

Desired Title: Introducing Layer5 Learning Paths
Draft: https://docs.google.com/document/d/1T5KycIgR6TtyTAv6bKuT-fiGQi7j9e4VYb0yzE2d4D8/edit?usp=sharing
Author: Anita Ihuman

This PR fixes #2323

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 95e289e9eac8fcca644bd1ff5e137ee4cb3b964e at: https://649444db5525f627f10506e6--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@akshayamadhuri Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by akshayamadhuri** [comment]
**@vishalvivekm** Sure, do  i need to change something

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@akshayamadhuri , please create a directory starting with date and then title like in screenshort and then create index.mdx and other files like this. 
blog

**Comment by leecalcote** [comment]
@akshayamadhuri thanks for this. 👍 

You can use the "workshops.svg" image found at the bottom of this page - https://layer5.io/learn/service-mesh-workshops- for the blog post hero.

**Comment by akshayamadhuri** [comment]
@leecalcote  the link shows the page doesn't exist  
Screenshot (1574)

**Pull request closed without merging**
