### PR TITLE
Added other press kits

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
Added press kits for: 
- Meshery Docker Extension
- CNCF adopts Meshery
- CNCF adopts SMP

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 941774eb4cacabfeb7e370d5d7e6fbe7f907c834 at: https://62a4c7346ba27a411d37f25b--layer5.netlify.app

**Comment by debo19** [comment]
@leecalcote These are all the kits we need for now right or am I missing anything?

**Comment by leecalcote** [comment]
@debo19 did we have one for MeshMark? I can’t remember. These four would be the only ones.

**Comment by debo19** [comment]
@leecalcote Yes, MeshMark was already published.

**Pull request merged**
