### PR TITLE
Added Dynamic Data fetch for SMI Table

### PR DESCRIPTION
**Pull request by dhruv0000**
**Description**

This PR populates SMI table with [public endpoint](https://meshery.layer5.io/smi/results/public)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Screen Shot 2021-03-23 at 4 33 41 PM

**Comment by dhruv0000** [comment]
Looking into it.

**Comment by leecalcote** [comment]
```
Warning: Failed prop type: There should be an equal number of 'Tab' and 'TabPanel' in `Tabs`. Received 0 'Tab' and 1 'TabPanel'.
```

```
Warning: Each child in a list should have a unique "key" prop.
```

**Comment by l5io** [comment]
🚀 Preview for commit 45620085d30890b8ff4e4f2554ece30fa8d082ff at: https://605a600d3ad9b7007cc48329--layer5ng.netlify.app

**Comment by leecalcote** [comment]
New deploy preview building...

**Comment by l5io** [comment]
🚀 Preview for commit 75864df7b435cdcaa48b3b88276572bf4095c775 at: https://605ac93f1a18227db6a3d065--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Screen Shot 2021-03-24 at 12 51 34 AM

**Pull request merged**
