### PR TITLE
Meshery Page for layer5-ng

### LINKED ISSUE #893: [NG] Migrate Meshery Page to layer5-ng
**Current Behavior**
The current meshery page is as shown [here](https://layer5.io/meshery).

**Desired Situation**
Migrate the meshery page and make use of sections that are provided in the template.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR fixes #893 
Currently, I have just migrated the data and made use of a few components. 
You can find the page at [https://deploy-preview-920--layer5ng.netlify.app/meshery](https://deploy-preview-920--layer5ng.netlify.app/meshery)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Exciting!

**Comment by Jashpatel1** [comment]
@leecalcote @Nikhil-Ladha @chandrashritii @shivaylamba @Tanuj22 @NupurThakur27 Looking forward to get some valuable feedback from you guys.

**Comment by shivaylamba** [comment]
Overall the new version looks really good @Jashpatel1 
Just a few suggestions : 
1. The gap here between Step 2 and solution can be reduced. 
image

2. In Run Meshery section we can add icons for mac, brew, windows. 

3. This Image under Configuration Best Practices and Service Mesh Patterns isn't very clear. 

image

4. The text size for the sub heading could be improved. 
image

Apart from that it looks good. We could also probably add a few more animations. But as the first version it looks quite good.

**Comment by NupurThakur27** [comment]
1. In my opinion these arrows may shift to the nextline as currently they are overlapping the text.
Screenshot from 2020-10-05 20-59-09
2. The opacity of the background of topbar can be decreased, as on overlapping with text it looks a little mishap. 
Screenshot from 2020-10-05 20-56-50

**Comment by Nikhil-Ladha** [comment]
Meshery heading can be moved a little bit down, like add some white space on top of it, between the heading and nav.
Also, I think making `Meshery` in the tag line `Mesher is the service mesh management plane`, bold/italic might look nice!

**Comment by Jashpatel1** [comment]
> Meshery heading can be moved a little bit down, like add some white space on top of it, between the heading and nav.
> Also, I think making `Meshery` in the tag line `Mesher is the service mesh management plane`, bold/italic might look nice!

Something different is coming.😁

**Comment by Nikhil-Ladha** [comment]
> > Meshery heading can be moved a little bit down, like add some white space on top of it, between the heading and nav.
> > Also, I think making `Meshery` in the tag line `Mesher is the service mesh management plane`, bold/italic might look nice!
> 
> Something different is coming.

Ohh.....nice :fire:

**Comment by leecalcote** [comment]
@Jashpatel1 The new structure is a positive change of direction. Some good bones here.

**Comment by leecalcote** [comment]
@Jashpatel1 will you have a look at this conflict? - https://github.com/layer5io/layer5/pull/920/conflicts

**Review by leecalcote — APPROVED** [review]
Good work, @Jashpatel1!

**Pull request merged**
