### PR TITLE
Added description prop to Blog and Resource templates

### LINKED ISSUE #4805: Duplicate meta descriptions
### Current Behavior

Currently, these 4 pages have duplicate meta descriptions (og:description)
- https://layer5.io/blog/docker/extending-the-docker-compose-experience-to-service-mesh
- https://layer5.io/blog/docker/extending-docker-with-meshery-spire-and-istio
- https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap
- https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership

Note:  Ctrl+U – Open the pages' source code and search for og:description to see the meta description

### Desired Situation

Each of these pages should have different content for og:description property in meta tag.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #4805 

**Notes for Reviewers**
- Added description prop to the graphql query and passed it as a prop to SEO component in the blogs and resources template
- This solved the duplicate SEO property of the first 3 pages mentioned in the issue description
- The last page doesn't have any description by default, so the default description is shown. Let me know if I should add one.
- Thanks to @randychilau for helping me out <3

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a98da0e37b5df852812b769a4afdc1a5c35c83e9 at: https://64f965b44a56463c4b4d70b4--layer5.netlify.app

**Review by vishalvivekm — COMMENTED** [review]
Thanks @Mohith234 @randychilau 🎉 
Yeah since the three pages now have their own descriptions. All these 4 pages now have different description.

For the news though, I wonder if we would want to have specific meta description for each of the news page instead of the default : ```News and press about Layer5, the cloud native management company.
    Layer5 the company behind industry-leading, open source software.```

**Review by vishalvivekm — APPROVED** [review]

**Comment by Mohith234** [comment]
@vishalvivekm Having different descriptions for the news articles sounds good to me too. 
Let me know and then I will create a separate issue and work on it if needed.

**Review by randychilau — APPROVED** [review]
Hi @Mohith234,

Nice job on this PR and good notes for the reviewers.

LGTM!

Cheers,
Randy
-

**Comment by randychilau** [comment]
Hi @Mohith234,

Expanding on @vishalvivekm comment regarding news articles, a follow-up PR could be checking all the other templates to see if there is an appropriate field that could be used as the `description` prop for the SEO component, and make the necessary changes.

note: You can review the available `frontmatter` fields for a template by finding its respective folder in `collections` and opening a few `.mdx` files to see which frontmatter field would be appropriate.

For example:

- for `src/templates/career-single.js`, by opening the `src/collections/careers/digital-marketing-internship/index.mdx` file, we can see that the `abstract` field seems to be a good candidate for the `description` prop.

Cheers,
Randy

**Comment by vishalvivekm** [comment]
> Hi @Mohith234,
> 
> Expanding on @vishalvivekm comment regarding news articles, a follow-up PR could be checking all the other templates to see if there is an appropriate field that could be used as the `description` prop for the SEO component, and make the necessary changes.
> 
> note: You can review the available `frontmatter` fields for a template by finding its respective folder in `collections` and opening a few `.mdx` files to see which frontmatter field would be appropriate.
> 
> For example:
> 
> * for `src/templates/career-single.js`, by opening the `src/collections/careers/digital-marketing-internship/index.mdx` file, we can see that the `abstract` field seems to be a good candidate for the `description` prop.
> 
> Cheers, Randy

This is incredibly helpful, @randychilau.
Thank you most kindly, Sir! :)

**Comment by l5io** [comment]
🚀 Preview for commit 4ead670783576fb05bbb4b5605f0ecd75f61a34b at: https://64fae52173876a59c167e4b8--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Excellent, @Mohith234 👏

**Pull request merged**
