### PR TITLE
The image address was wrong.

### PR DESCRIPTION
**Pull request by Modern-artist**
**Description**
The image address was wrong which caused a blank page in dark mode.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Good! This takes care of the breaking page issue. Hopefully, the swapping of the two filenames takes care of the dark/light mode issue.

**Comment by l5io** [comment]
🚀 Preview for commit f41fec92777022ad9c72c49fd950d95cd9f04efc at: https://64f98e5d3e093952b07e9521--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 81159e10eedec052482386b18c7507a1fa43d0e2 at: https://64f99738db1acd5495457bdc--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for getting a proper, colored version for light mode in here, @Modern-artist 👍

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
