### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by Jat1nSood**
**Description**

This is a test PR

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4fa4583c1f77c34f44f7f7d582556a88c6259329 at: https://657d7ac666e83a19462b5eca--layer5.netlify.app

**Comment by Jat1nSood** [comment]
@leecalcote

**Comment by Savio629** [comment]
The delay is quite visible, though the artifacts load properly right now.
It doesn't have any performance issue, just checked with light house

**Comment by Jat1nSood** [comment]
> The delay is quite visible, though the artifacts load properly right now. It doesn't have any performance issue, just checked with light house

I am not sure if you talking about the delay for other components or delay for those artifacts??

**Comment by abhijeetgauravm** [comment]
Hey @Jat1nSood  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @Jat1nSood can you edit your PR title for the issue it's solving if you could?

**Pull request closed without merging**
