### PR TITLE
Sangram Rath Member Profile

### LINKED ISSUE #5463: [Community] Member Profile: Sangram Rath
**Current Behavior**

@sangramrath has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @sangramrath as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sangramrath
- Twitter: [mr_sangramrath](https://twitter.com/mr_sangramrath)
- LinkedIn: [in/sangramrath](https://www.linkedin.com/in/sangramrath/)
- Layer5 Cloud: [7dde79fb-2778-4a66-9ce5-6772bafe8df8](https://meshery.layer5.io/user/7dde79fb-2778-4a66-9ce5-6772bafe8df8)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Satakshijain**
**Description**

This PR fixes #5463 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8f938b691101df8b2f1d5700226c3290cc82d702 at: https://660c6453d5d159228dac978b--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@sangramrath requesting your review, please.

**Review by leecalcote — APPROVED** [review]
Whoo-hoo! 👏

**Comment by sangramrath** [comment]
@vishalvivekm looks all right. Thanks.

**Comment by iArchitSharma** [comment]
You don't have to @sangramrath 
Thanks @Satakshijain

**Pull request merged**
