### PR TITLE
 Fixed : Much spaces between contribution and General contribution flow #4636 

### LINKED ISSUE #4636: Much spaces between  contribution and General contribution flow
### Current Behavior

There is much spaces between  contribution and General contribution flow [here](https://layer5.io/community/handbook/contribution)
Similarly , in Projects [here](https://layer5.io/community/handbook/projects) , Mentorship Programs [here](https://layer5.io/community/handbook/mentorship-programs) , Writing Program [here](https://layer5.io/community/handbook/writing-program) , UX Contributors [here](https://layer5.io/community/handbook/designer) , Code of Conduct [here](https://layer5.io/community/handbook/code-of-conduct) 
### Desired Behavior

The spaces should reduced between contribution and General contribution flow [here](https://layer5.io/community/handbook/contribution) .
### Screenshots / Mockups

image
image
image
image

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by kituuu**
**Description**

This PR fixes #4636

**Notes for Reviewers**
Just change 2-3 lines of css. Please check the changes on your local system once.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d24dc6cdfddbb1b25244d03a89fc935b5387f4bf at: https://64dff5e51f25ef08eb298a92--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3bfb8a5ec9d01082e3641e0ade89f534538cfbb8 at: https://64dffac01f25ef0b97298a87--layer5.netlify.app

**Review by gopivaibhav — COMMENTED** [review]
Hey @kituuu 
You may have forgotten to change the email before you sign off your commits.
Note - You can follow either of these to re-sign your commits. [Link1](https://gist.github.com/whatisor/3b6f9d30eee5789f04cd90039163cb84) [Link2](https://stackoverflow.com/a/15667644)

**Comment by kituuu** [comment]
@gopivaibhav, it wasn't working. I made a new PR, can you check it once?

**Pull request closed without merging**
