### PR TITLE
add community member profile:rex #4724

### LINKED ISSUE #4724: [Community] Member Profile: Rex
**Current Behavior**

@Rexford74 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Rexford74 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Rexford74 
- Twitter: [rexford__](https://twitter.com/rexford__)
- LinkedIn: [rex-joshua-designer](https://www.linkedin.com/in/rex-joshua-designer/)
- Meshery Cloud: [f0a2dc22-e7c6-4143-a984-1f6c22f8e696](https://meshery.layer5.io/user/f0a2dc22-e7c6-4143-a984-1f6c22f8e696)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Golu7667**
**Description**

This PR fixes #4724

**Notes for Reviewers**
Added Rex Profile to the Community Member Profile

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 930dee66fef860331739313c43cfd8e9a604dd72 at: https://64dccf8fe4d9060e61bf36ff--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
hey @Golu7667 , @Rexford74 will provide his bio and also ask once for getting assign before making PR.

**Comment by l5io** [comment]
🚀 Preview for commit b753a78394ff702d176639fa7682450ffdae3aca at: https://64dcdaf59f7e4614d8c3b8ac--layer5.netlify.app

**Review by Rexford74 — CHANGES_REQUESTED** [review]
This is looking nice, and the preview looks good as well. However, I dropped some additions for Shivankur on slack. I think there are a few more changes to implement.

**Comment by Chadha93** [comment]
> This is looking nice, and the preview looks good as well. However, I dropped some additions for Shivankur on slack. I think there are a few more changes to implement.

Ouch looks like @Golu7667 didn't updated.

**Comment by Chadha93** [comment]
@Rexford74 Will you drop the update required here, I'll make sure to get it incorporated. Or you can directly make suggestions as code in this PR, I'll add it.

**Review by VivekBaldha0712 — COMMENTED** [review]
LGTM

**Comment by Rexford74** [comment]
Sorry for the tardiness @Chadha93. The addition is on the bio:

'I am a digital product designer passionate about the interaction between humans and technology. I am also a curious, adaptable, and effective person, capable of analyzing and understanding new concepts quickly and applying them when needed. I use my skills to improve user flows in order to help them achieve their objectives and, as much as possible, align them with business goals to ensure an optimized experience and productivity.
When I'm not designing and proposing solutions, I enjoy listening to music, watching football and movies, or playing video games.'

**Comment by abhijeetgauravm** [comment]
Hey @Golu7667 Thanks for the PR but the issue has been closed now and the bio has been updated already. And always try to ask for assignment before making direct PR as assignee was already working on that issue. And bunch of open issues are there you are most welcome to contribute.

**Review by Rexford74 — APPROVED** [review]
This updated version is nice. I think this is good to go! Well done @Golu7667!

**Review by abhijeetgauravm — COMMENTED** [review]
hey @Golu7667 In location u mentioned bio , in location there should be location and in bio there should be bio.

**Comment by Chadha93** [comment]
@Golu7667 @Rexford74, already has profile - https://layer5.io/community/members/rex-joshua-ibegbu

**Pull request closed without merging**
