### PR TITLE
[Books] - Updated SMP Book Cover

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #
The SMP Book Cover at https://layer5.io/learn/service-mesh-books has been updated

**Notes for Reviewers**
- Removed the old thumbnails and updated the new cover image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 493e70ac8c4d5ccf4481c99677714dd5d7be3f53 at: https://608941ef12727beeddc0d81a--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 493e70ac8c4d5ccf4481c99677714dd5d7be3f53 at: https://608942486a51590ca0ddc088--layer5ng.netlify.app

**Comment by adithyaakrishna** [comment]
Thanks for the preview bot :)

**Comment by leecalcote** [comment]
Double thanks, it seems. @Nikhil-Ladha, I wonder if we might adjust the triggers for this workflow.

**Comment by adithyaakrishna** [comment]
@leecalcote They are getting triggered on edits also, Ig we can fix them by removing the edited option here, 
image

**Comment by Nikhil-Ladha** [comment]
Yes, removing that `edited` option in the workflow will fix this.
@adithyaakrishna you can fix that in this PR itself.

**Comment by Nikhil-Ladha** [comment]
Or open you can open a separate PR to keep things sanitized 😉

**Comment by adithyaakrishna** [comment]
> Or open you can open a separate PR to keep things sanitized 😉

Okay Sure, I'll open another PR for that👨‍🔧

**Review by Nikhil-Ladha — COMMENTED** [review]
I don't think the line just below the header on this book's description page, highlighting the names `Lee Calcote and Nic Jackson` makes any sense here?
Can be removed @leecalcote ?

**Comment by leecalcote** [comment]
@Nikhil-Ladha without denoting that these are the authors, you're right.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha without denoting that these are the authors, you're right. I think we can remove.

Ack. @adithyaakrishna please remove that line from the book description.

**Comment by adithyaakrishna** [comment]
> Ack. @adithyaakrishna please remove that line from the book description.

Done @Nikhil-Ladha

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 7e12afd4403a532730e63bcf2a83c0dcd15aaebf at: https://6089bd35e1aedf3d6a2853e4--layer5ng.netlify.app

**Pull request merged**
