### PR TITLE
Added member profile: Elizabeth Lola

### LINKED ISSUE #1909: [Community] Member Profile: Elizabeth Meshioye
**Current Behavior**

@Lezette has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Lezette as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Lezette
- Twitter: ilizette7
- LinkedIn: elizabeth-lola
- Link to profile picture: https://drive.google.com/drive/folders/1qUCMYDaQQkuJ-Btbxf1Yw2Wh22SlWiPL
- Short Bio: I am a frontend developer and Open Source enthusiast currently using react and nuxt to build web-accessible and user-friendly websites. I also enjoy writing technical articles. I spend my weekends reading other people's codes or daydreaming.
- Location: Lagos, Nigeria

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by jeantiston**
Signed-off-by: jeantiston <jean.tiston.work@gmail.com>

**Description**

Added member profile for Elizabeth Lola

This PR fixes #1909

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @jeantiston. 🙂

**Comment by l5io** [comment]
🚀 Preview for commit 3bd91e2c15a48c20179c04e60fb088f70dd4e58b at: https://60be5f83eda0020fb1a60658--layer5ng.netlify.app

**Review by Lezette — APPROVED** [review]

**Comment by Lezette** [comment]
This is great! Thank you  @jeantiston  and @leecalcote  I really appreciate this

**Review by Anita-ihuman — APPROVED** [review]
Good work @jeantiston

**Comment by leecalcote** [comment]
Thank you, @jeantiston 👍

**Pull request merged**
