### PR TITLE
[NG] Added lolyparty as a contributor

### LINKED ISSUE #1247: [NG] Community: Recognizing Lolyparty as a Contributor and Community Member
**Current Behavior**
 @lolyparty has been a consistent contributor and community member.

**Desired Situation**
A profile for @lolyparty should be created and visible on /community/members on next generation layer5.io site.

Github: https://github.com/lolyparty
Twitter: lolyparty
LinkedIn: olayiwola-ololade-064933168
Profile picture: https://i.postimg.cc/vZkSsNq5/IMG-20180929-155636.jpg

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by MaximeCoignus**
Signed-off-by: MaximeCoignus <maxime.coignus@gmail.com>

**Description**

This PR fixes #1247 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Looking good so far. Let's go ahead and add new details for:

- location
- bio
- badges

**Review by lolyparty — COMMENTED** [review]
Looks Good. Nice work @MaximeCoignus

**Comment by Tanuj22** [comment]
> Looking good so far. Let's go ahead and add new details for:
> 
> * location
> * bio
> * badges

@lolyparty Can you provide these?

**Comment by lolyparty** [comment]
> > Looking good so far. Let's go ahead and add new details for:
> > 
> > * location
> > * bio
> > * badges
> 
> @lolyparty Can you provide these?

Oh yeah.
Location - Nigeria 
Bio - Frontend Developer(react)
badges - *I don't know what this means

**Comment by leecalcote** [comment]
For the time being, let's go ahead and leave `badges` blank.

**Comment by MaximeCoignus** [comment]
@leecalcote, done!

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Great work. Thanks @MaximeCoignus

**Pull request merged**
