### PR TITLE
fix: broken image links

### LINKED ISSUE #1798: [Getting Started] Broken images on Meshery's Getting Started page
**Description**
On https://layer5.io/service-mesh-management/meshery/getting-started, there are a number of broken images which are in need of being fixed.

**Screenshots**
Screen Shot 2021-04-19 at 2 02 35 PM

Screen Shot 2021-04-19 at 2 04 45 PM

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <agarwal.5@iitj.ac.in>

**Description**

This PR fixes #1798 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Tedious. Thanks for doing this. Do you know what brought about the need for this change?

**Comment by Tanuj22** [comment]
Gatsby V3 dropped support for `require` statement  :sweat:

**Comment by Nikhil-Ladha** [comment]
I was actually, wondering if Gatsbyv3 brought improvement or reduced the number of features 😂

**Comment by Nikhil-Ladha** [comment]
With, this I am not sure if we there is still `require` being used in other places for rendering images 🤔.
@Tanuj22 have you checked that ad well or it needs ro be checked?

**Comment by Tanuj22** [comment]
> With, this I am not sure if we there is still `require` being used in other places for rendering images .
> @Tanuj22 have you checked that ad well or it needs ro be checked?

I checked. It's not being used anywhere else

**Pull request merged**
