### PR TITLE
https://github.com/layer5io/layer5/issues/4987 hacktoberfest-accepted

### LINKED ISSUE #4987: Duplicate 'Subscribe to Newsletter' on Blog Page
### Description

There is an issue on the page: https://layer5.io/blog. When scrolling down to the bottom of the page, the problem described in the screenshot below is observed.

#### Steps to reproduce 
- Navigate to https://layer5.io/blog
- Scroll down to the bottom of the page
- The issue is depicted in the following screenshot:

### Screenshots
Screenshot 2023-10-01 020746

### Expected Behavior

There should either be a gap between the "Subscribe to Newsletter" section above and the footer, or the "Subscribe to Newsletter" section should be removed since there is already one at the bottom in the footer.

### Environment:
- Host OS: Windows
- Browser: Chrome, Brave,Edge

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by prakashAditya639**
**Description**

This PR fixes #4987

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a66a4370b7b1dd04001383e5f6de0a731c4228cf at: https://651adfcb26c40702b5fe4725--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a66a4370b7b1dd04001383e5f6de0a731c4228cf at: https://651b74efad4c4f0c9c714d8a--layer5.netlify.app

**Comment by prakashAditya639** [comment]
Please Merge it as soon as possible........................

**Comment by prakashAditya639** [comment]
Everything is working fine...............

**Comment by prakashAditya639** [comment]
Is there anything I can do to fix the deploy issue, Is that from my end???

**Comment by Mohith234** [comment]
@prakashAditya639 Appreciate your enthusiasm, I would prefer you to read through the contribution guidelines and then start working on issues. The PR is not assigned to you. So please refrain from creating PRs that are not assigned to you.

**Comment by prakashAditya639** [comment]
@Mohith234 Sorry for doing that I actually don't know about that I have joined github few days ago and not that much experience in github, Thank You for giving the advise it will be very helpful for me in the future...
Sir I am very eager to resolve the issue if the PR I made is correct then can you please assign the issue to me under hacktoberfest...?
Thank You sir

**Comment by abhijeetgauravm** [comment]
Hey @prakashAditya639, appreciate your enthusiasm to contribute but actually the team is still discussing what might be possible solution to this issue. We don't want to abruptly remove the subscribe button. We are still planning on alternatives to this. Please keep looking out for other open issues we have plenty of them. Yeah most of them will be assigned under the label: "Hacktoberfest".

**Comment by prakashAditya639** [comment]
@abhijeetgauravm Is the issue fixed???

**Comment by abhijeetgauravm** [comment]
> We don't want to abruptly remove the subscribe button.

hey @prakashAditya639  We don't want to abruptly remove the subscribe button. Please keep looking out for other open issues we have plenty of them.

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm Is the issue fixed???

hey @prakashAditya639 We really appreciate your enthusiasm to contribute. But We don't want to abruptly remove the subscribe button. But that won't stop you from contributing 🦾. We do have a bunch of open issues , you are most welcome to contribute.

**Pull request closed without merging**
