### PR TITLE
[Resources] Updated quote text visibility

### LINKED ISSUE #4237: [Resources] Text visibility affected by image
### Description

I found this issue here: https://layer5.io/resources.
The text is getting mixed with the quotes image which affects its visibility. 

### Expected Behavior

There can be 2 ways to fix this:
1. Changing the color of the affected text, and/or
2. Changing the position of the quotes image

### Screenshots

Dark Mode:
image

Light Mode:
image

### Environment:
- Host OS: Windows
- Browser: Google Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by aku1310**
**Description**
Update text position to relative for better text visibility

This PR fixes #4237 

**Notes for Reviewers**
Before:
image

After:
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6246af6892c6d864ce0fa2424eaca912190abd52 at: https://64670b57e70ca143f9d35f72--layer5.netlify.app

**Comment by Saksham294** [comment]
@aku1310 LGTM

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@aku1310 , looks good but can you make something similar to [layer5 ](https://layer5.io/) 's home page then it would be nice.

**Comment by aku1310** [comment]
> @aku1310 , looks good but can you make something similar to [layer5 ](https://layer5.io/) 's home page then it would be nice.

Okay sure, I will update this by tomorrow.

**Comment by ayushthe1** [comment]
@aku1310  Let's discuss this on websites call. Add this as an agenda item in meeting minutes if you would :).
I'll add this item for you if it's ok.

**Comment by aku1310** [comment]
> @aku1310 Let's discuss this on websites call. Add this as an agenda item in meeting minutes if you would :). I'll add this item for you if it's ok.

Sure, please do. Thank you!

**Comment by l5io** [comment]
🚀 Preview for commit f2081cbb56a1035a98d1da24f6b8ab0959d06503 at: https://646a5558a4054b2b54b3cd8f--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
Looking good 👍

**Review by goldfishdolphin — APPROVED** [review]
LGTM 🚀

**Pull request merged**
