### PR TITLE
feat: meshery v0.4.0 blog post

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
@shivaylamba I have kept the blog as simple as possible with a brief overview of what changes have we made so far including bug fixes, features & enhancement.

**Comment by shivaylamba** [comment]
@kushthedude It looks good. But being a blog, I think we have the liberty to be more creative and say add images for some of the important changes that were made. While the entire summarized version detailing about each new iteration looks good, but then What's new? looks more like a standard change log. So I think we can screenshots of the new features in place where they matters.

**Comment by kushthedude** [comment]
I have followed the release blogs of kubernetes, chromium . They were simple and intuitive without much design or images, what here is missing is known issues and breaking changes which I will be adding in further iteration once we release the v0.4.0 . Also coming to the images part, we can't add images for each functionality since most of then are changes in meshery working and architecture. Adding the image for UI is only feasible for performance page where we can actually see the changes but then again this will remove the consistency in blog.
About the design, if you have any design planned for the following blog post then we can look over it. 
Release announcements should be simpler with changes, known issue and breaking changes and must read sections.

**Comment by leecalcote** [comment]
I consider there is a spectrum and that we’re missing and gravely need content on the more rich end of the spectrum.

**Spectrum:**
- Changelogs: ad nauseum list every change made from prior release. [essentially where we are [with ReleaseDrafter today](https://github.com/layer5io/meshery/releases/tag/untagged-efa4c846952938c6734a)].
- Release Notes: a curated, bulleted list of highlights, summarized and categorized in human-readable with some engineering-speak and some issue references. [where I hope that we can get with ReleaseDrafter]
- Release Announcement: A human-written summary, the bubbles the most significant items to the top, highlights any caveats (e.g. incompatibility on upgrade), points people to other sources of information (e.g. upgrade guide, feature blogs, full list of all bug fixed). Should include a graphic or two and links to new docs covering things in-depth. Each significant feature should have a hyperlink to something explaining it [essentially what Kush has written]
- Feature-functionality Blog / Net new sections in User Docs / Upgrade Guide: In-depth review of new functionality or significantly augmented behavior, explaining what the functionality is, why is was added, and how to use it. [we desperately need these]

If we don’t have all these things, then, let’s merge some "Feature Blog" items in with Release Announcement. If we can get a couple feature / functionality articles written, then let’s keep the Announcement separate and link to those articles / new docs.

**Comment by chandrashritii** [comment]
@kushthedude @leecalcote @shivaylamba I made a few small edits to make the release notes more verbose. Please review.

**Comment by leecalcote** [comment]
Added the release documentation notes above into this document - https://docs.google.com/document/d/1JuegfkG-u1MU_xp_jtLyzCpZ_LzW5-Axb4fA-e6Hb_Y/edit#

**Comment by leecalcote** [comment]
I wasn't able to make it through the full announcement, but did update the first half of it.

**Review by leecalcote — APPROVED** [review]
Ready to publish. Go be social!

**Pull request merged**
