### PR TITLE
[community] initial upload of new contributor profile

### LINKED ISSUE #1902: [Community] Member Profile: Gaurav Chadha
**Current Behavior**

@Chadha93 has been a consistent contributor and community member. It's time to recognize his contributions by adding a member profile on the [Layer5 Community Members](https://layer5.io/community/members) page.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Chadha93 
- Twitter:
- LinkedIn: gaurav-chadha93
- Link to profile picture: https://drive.google.com/file/d/13LK3vMFmbc5Yj9yco9z24Yve-wQ9FNBr/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by josephmidura**
Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR fixes #1902 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by josephmidura** [comment]
Here's a [preview](https://user-images.githubusercontent.com/11523557/121108308-24884480-c7cf-11eb-9350-da9953d578dd.mov).

**Comment by l5io** [comment]
🚀 Preview for commit 2bfd857d4493c03a86d4ef8bc2aa42424b137c31 at: https://60bec9843c34fe88e3a3a236--layer5ng.netlify.app

**Review by Chadha93 — CHANGES_REQUESTED** [review]
Could please update the profile image, Sorry the previous image was not having any background so it was looking all grey (I have added a background)
https://drive.google.com/file/d/1r3nbkvl-pyiHHUoLp9VvCESIAjm1oGbi/view

**Comment by josephmidura** [comment]
Sure, we can update your picture.

**Comment by leecalcote** [comment]
> Sure, we can update your picture.

🙂 @josephmidura 🥇

**Comment by josephmidura** [comment]
@Chadha93 It looks like you linked to the same picture as before. Could you please verify?

**Comment by Chadha93** [comment]
> @Chadha93 It looks like you linked to the same picture as before. Could you please verify?

@josephmidura Yes I have checked, the new one is having a white background while the old one was not having any background.

**Comment by josephmidura** [comment]
@Chadha93 Let us know what you think:

https://user-images.githubusercontent.com/11523557/121571529-c46cea80-c9e8-11eb-8a53-52a9f730e066.mov

**Comment by Chadha93** [comment]
> @Chadha93 Let us know what you think:
> 
>  Screen.Recording.2021-06-10.at.12.37.05.PM.mov

Thanks @josephmidura It's perfect now 😊

**Review by Chadha93 — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Nice!

**Comment by josephmidura** [comment]
> 
> Thanks @josephmidura It's perfect now 😊

You're welcome. That's what I like to hear :tada:

**Comment by adithyaakrishna** [comment]
Yayyyy @Chadha93  🎉🎈

**Pull request merged**
