### PR TITLE
[Learn] added `Bookmark Notification` for users

### PR DESCRIPTION
**Pull request by NikhilSharma03**
**Description**

- added `Bookmark Notification` for users to notify them that we bookmark their progress.

https://user-images.githubusercontent.com/58226527/152629929-4d7c8851-702b-49f5-9d29-9168a177f811.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6e26b696545824aef090c8585d99fd8ba9749875 at: https://61fe0ca0fffbdb9216980b1f--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@NikhilSharma03 let's discuss your PR's on the websites' call.

**Comment by NikhilSharma03** [comment]
@warunicorn19 :+1:

**Comment by NikhilSharma03** [comment]
@Nikhil-Ladha

- Removed the bookmark icon from `TOC` 
- Updated text
- The notification is placed in the bottom left, should I update it to the top right? :thinking:

**Comment by l5io** [comment]
🚀 Preview for commit 3b52d29886ad149d4677e31c05e3ebfa1d659aea at: https://6201336da32e45430450eef3--layer5ng.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
