### PR TITLE
demo for service mesh [how-it-works]

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
A demo for the placement of service mesh logos
demo page Link="/serviceMesh"

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This branch builds successfully for me locally.

**Comment by leecalcote** [comment]
@vinayaksh42 does this build for you?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 does this build for you?

Yes this branch is successfully building in my local environment but the svgs are not visible.

**Comment by leecalcote** [comment]
Good deal. If you clean up the conflict, let's merge.

**Comment by vinayaksh42** [comment]
I have made a new pr #1162

**Review by leecalcote — APPROVED** [review]

**Pull request closed without merging**
