### PR TITLE
new course folder(advance concepts of service mesh) and 1st chapter is added

### LINKED ISSUE #1987: [Learn] Add a new course "Advance concepts of Service Mesh"
**Current State:**
We have only 1 course `introduction to service mesh` under the learning path `mastering service mesh`, the `advance concepts of service mesh` course is not yet added.

**Desired State:**
A new course `Advance concepts of service mesh` needs to be added under the learning path `mastering service mesh` [here](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio), it should use the content from this [repo](https://github.com/layer5io/advanced-istio-service-mesh-workshop) and have a structure similar to this [course](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

### PR DESCRIPTION
**Pull request by The-Loony-Coder**
Signed-off-by: Mritunjay <msengar121@gmail.com>

**added new course [here**](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio),advance-concept-of-service-mesh and a single chapter in istio

This PR fixes #1987

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by The-Loony-Coder** [comment]
hey @Nikhil-Ladha , have a look for the course folder and chapter,if it is okay I will send the next chapters pr.
folder
chapter-1

**Comment by l5io** [comment]
🚀 Preview for commit 57c37d3e7397d4795d4b5ef464343ee8e7669e77 at: https://60fbe5c91e03a2d04cf3d4cf--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Let's change the course name to `Advanced Concepts of Service Meshes - Hands On`

**Comment by The-Loony-Coder** [comment]
sure

**Comment by leecalcote** [comment]
Very cool, @The-Loony-Coder

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by The-Loony-Coder** [comment]
hey @Nikhil-Ladha ,I was having issues with git, I wanted to know that , should I make PR for every new chapter or I should make commit in this only?

**Comment by Nikhil-Ladha** [comment]
> hey @Nikhil-Ladha ,I was having issues with git, I wanted to know that , should I make PR for every new chapter or I should make commit in this only?

A new PR for each chapter.

**Comment by l5io** [comment]
🚀 Preview for commit 40a8a7deca8d37554c67bfe8a9bf0a14ea5db5c5 at: https://60fe6fac6a6955e0cc573c84--layer5ng.netlify.app

**Pull request merged**
