### PR TITLE
Changed h3 tags to h2 for logos and colors in brand page

### PR DESCRIPTION
**Pull request by H-A-R-S-H-K**
This PR fixes ##5788

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8dcd899d14774c658710cd103c70664d204c7f36 at: https://66baeb8a2f3b1aa649e3ffc2--layer5.netlify.app

**Comment by Ashparshp** [comment]
Thank you, @H-A-R-S-H-K. Please note that we proceed in chronological order with issue assignment, and we haven't finalized what has to be done with the issue yet. Wouldn't it be better to ask for assignment as others might be working on the same issue? Also, please read the contributing guide and add a sign-off DCO fix. I appreciate your PR, but ensure you get assigned next time. Are you on our Slack channel?

**Comment by H-A-R-S-H-K** [comment]
Hey @sudhanshutech @Ashparshp please review my PR

**Comment by H-A-R-S-H-K** [comment]
Sorry for putting a PR without assignment. No I am not yet on Slack.

**Comment by Ashparshp** [comment]
@H-A-R-S-H-K https://layer5.io/community/newcomers

**Comment by l5io** [comment]
🚀 Preview for commit 72dc800d81d86200bd93ea50164c789aa2a45931 at: https://66bb1405d98256d9c357f5a8--layer5.netlify.app

**Review by Ashparshp — APPROVED** [review]
Thank you, @H-A-R-S-H-K.

**Comment by Ashparshp** [comment]
@H-A-R-S-H-K, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by H-A-R-S-H-K** [comment]
@sudhanshutech Please review my PR.

**Pull request merged**
