### PR TITLE
fix tooltip for smi table

### LINKED ISSUE #3279: Tooltip hidden for the last row in table
#### Description
Due to the size of the tooltip, the tooltip doesn't find space to render at top or left so it renders below the text and therefore gets hidden.

image

#### Expected Behavior
The tooltips should be visible for all cells of the last row.

#### Possible solution
We can determine a max-width value for all the tooltips so that they don't exceed a particular length. Also at some places the text is too long. Having such a long tooltip doesn't look very good.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
**Description**
Issues :- 
- Tooltip not visible for Partially Compatible checks
- Each cell has more than 1 tooltip displaying for it. Not noticeable because positioning is bottom for all tooltips. So all tooltips overlap each other and couldn't see the multiple stacked tooltips with naked eye. Can be visible if we change the color and position for FULL, HALF and NONE tooltips. Below is an image displaying the same.
image

**This happens because all tooltips have the same id `id="capablity"`**

<br>

**This PR fixes #3279** 

**Notes for Reviewers**
- Now each row has a single tooltip. Previously there were 4 different tooltips, 1 with different id and other 3 with same id. 
- In future we can use rc-tooltip instead of react-tooltip. rc-tooltip is much easier to implement and works in a much simpler manner.
- The tooltips work perfectly fine now for all kinds of cells in the table 
image

- Tooltips are visible for last row cells as well.
image
 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9a9d5625cd5849e0a62412eb5ddeccc73ba31229 at: https://6342ebd5d6cd7b3185f49018--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1a27091f23309740fbe4a1c5ea22ee7af16525ab at: https://6342f75882fe0e392fe6d98d--layer5.netlify.app

**Comment by debo19** [comment]
@GaganpreetKaurKalsi let's discuss this update on the websites call today?

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi let's discuss this update on the websites call today?

Sure!

**Review by Nikhil-Ladha — COMMENTED** [review]
The `overflow` has to be updated to `hidden` as well at the top of the stylesheet of the SMI Table, else there is an unwanted scrollbar for tooltips on the fifth column.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by GaganpreetKaurKalsi** [comment]
**Current -** 
image

**Proposed -**
image

Does it look any better now, the shadow I mean?
If it looks good then I'll push changes for this minor one as well.

**Comment by Nikhil-Ladha** [comment]
Though, I don't see a noticeable difference in the shadow 🤔 
Both seem similar to me.

**Comment by GaganpreetKaurKalsi** [comment]
> Though, I don't see a noticeable difference in the shadow 🤔 Both seem similar to me.

Yeah, that's true.
@leecalcote asked if we could make the north and the south even.

Your views @leecalcote!!

**Comment by leecalcote** [comment]
I believe this is what happens on hover of a table row: `box-shadow: rgb(255 255 255) 0px 2px 15px -10px;`. If so, we might be off by 2px.

**Comment by leecalcote** [comment]
In the Current screenshot above, I can _juuussst_ see the 2px difference. In the Proposed screenshot, I don't see a difference.

**Comment by Nikhil-Ladha** [comment]
Gotcha!
Verryyyy minute detail.
@GaganpreetKaurKalsi please send out a new PR with this change

**Comment by leecalcote** [comment]
Totally - a super eensy-weensy, teeny-tiny, I-can't-believe-how-amazing-your-pixel-sniffer-is-lee, essentially inconsequential, who-even-cares, itty-bitty, small little, why-do-you-have-to-be-such-a-picky-@%#$-lee detail.

**Pull request merged**
