### PR TITLE
Modified meshmap page

### PR DESCRIPTION
**Pull request by debo19**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 79bad0d433de34581c3090dd35e3d12c326660be at: https://623ce008b34c4b46cc41a977--layer5ng.netlify.app

**Review by NikhilSharma03 — APPROVED** [review]
LGTM :+1: Excellent Work :zap: + UIWizard.

**Comment by warunicorn19** [comment]
@debo19 the form is getting completely skewed in mobile view. image

**Comment by leecalcote** [comment]
This section also needs some responsiveness:
Screen Shot 2022-03-25 at 3 14 28 PM

**Comment by l5io** [comment]
🚀 Preview for commit d9bf2105bc1ad9f7333d7cc2900451308f53f596 at: https://623f1440b90e530683a25e6d--layer5ng.netlify.app

**Review by Chadha93 — COMMENTED** [review]
Suggestion: We should use the latest UI images to display(Designer & Visualizer) for Beta.

**Comment by leecalcote** [comment]
Good call, @Chadha93. Also, we should work to ensure that each screenshot follows the same format, which in this case is to have a drop shadow behind the screenshot.

**Pull request merged**
