### PR TITLE
Improve colors for Table in darkMode

### LINKED ISSUE #3322: Improve dark-mode colors for table
**Current Behavior**
The current dark-mode color combination looks too dark with white borders visible and white color for the selected tab. 

image
image

**Desired Behavior**
Would like to improve the color combination for table in dark mode.
- The white border around tabs look weird.
- The active tab can be of a lighter form of dark color instead of white. Too contrasting.
- The active tab and the table heading row should have same color as in light mode.
image

<br>

In the below image, the active tab has the same color as that of heading row. This should be the desired behavior.

image

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
Signed-off-by: Gaganpreet Kaur Kalsi <gagansinghkalsi4126@gmail.com>

**Description**
Improve the UI for Table in Dark Mode

**Current UI**

image
image

**Proposed UI**

image
image
image

**This PR fixes #3322** 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4ad4c735bf4e153d2812ca09713843b42beb4714 at: https://634bc906e1f2e458223dcaf1--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Seems like you have taken it as a mission to beat the shit out of the dumb person who designed this landscape page, huh? 😭

**Comment by GaganpreetKaurKalsi** [comment]
> Seems like you have taken it as a mission to beat the shit out of the dumb person who designed this landscape page, huh? 😭

Give me BUGS....BUGS.....UI BUGS🐛😂.  Will try to shift my focus to some other page now 😂

**Comment by Nikhil-Ladha** [comment]
Haha, well if you still find bugs on the landscape page feel free to knock them out! 💯

**Pull request merged**
