### PR TITLE
Management of Kubernetes Article

### PR DESCRIPTION
**Pull request by deepeshaburse**
**Description**

Resource article on Management of Kubernetes.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 19b2f95be90210310e4dbd848e57a155b6a73617 at: https://638ed9461c52d86bc2600b55--layer5.netlify.app

**Comment by leecalcote** [comment]
@TolulopeMO up for review...

**Comment by leecalcote** [comment]
@deepeshaburse the quality of images used is quite poor - https://638ed9461c52d86bc2600b55--layer5.netlify.app/resources/kubernetes/management-of-kubernetes

**Comment by l5io** [comment]
🚀 Preview for commit 991ad610f9ad1fd643bc771fcd4510efbd22a24e at: https://639351d9f042bc6392653bed--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e8ad41b35a97997f798a2e0137431d0a5dbaf8fa at: https://63944ddc5893fc7480a4706b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f22d3b51d67a0711aa13163a35101c11b4014fa2 at: https://6395d4181fbc8c0d77d67441--layer5.netlify.app

**Comment by deepeshaburse** [comment]
@leecalcote I have changed the images. The PR is ready to be merged if no other changes are needed.

**Comment by leecalcote** [comment]
It's looking good. You might consider tossing "developers using Kubernetes were able to deploy new code changes at least 27% faster than developers without any container orchestration solution." into a `<Blockquote>`, which would add a little (more) flair to the article.

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 6530089504fc62e9c4bb77378bc2fce3e979bb39 at: https://63a1efb11cff160d4bdd6a41--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0d1413a7b8d9cbf5552932395aade0fcd3c52485 at: https://63a1f9c27e59780094c9a88d--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
