### PR TITLE
Created Mobile Swiper for MeshMap design section

### LINKED ISSUE #3866: Create card component with CSS animation
### Desired Situation

A component with an animation is needed **(referencing to the image below)** where on clicking over a card, it pops out of the stack and gets placed beside the stack as shown in the image. The placed card shows some content. But the cards do not show any content when they are stacked.

image

The color and border-radius that can be used for the card:
`background: linear-gradient(266.65deg, #00B39F 40.19%, #477E96 74.31%, #3C494F 92.89%);`
`border-radius: 20px;`

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #3866 

i Have created a card swiper for tablet and mobile view .

Screenshot 2023-03-17 at 12 47 58 AM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a4eb104e56b7577a0159984437d114eedce28b2e at: https://641370e859d15300be13643b--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks, @ShravaniAK. Initial feedback:

Screenshot 2023-03-16 at 3 51 41 PM

**Comment by ShravaniAK** [comment]
@leecalcote thanks for the feedback , ill start working on this.

**Comment by ShravaniAK** [comment]
Should i remove the drag hand ?

**Comment by l5io** [comment]
🚀 Preview for commit 07406f324ca45a2577629b60940a793b8a2bba4d at: https://641563f265f550100b2041aa--layer5.netlify.app

**Comment by ShravaniAK** [comment]
I am making a pr again , i just saw there is some css faults

**Comment by l5io** [comment]
🚀 Preview for commit face12128637e71af90518cad6315b9cb7200c5e at: https://64156c5b0831641f791d43a7--layer5.netlify.app

**Comment by leecalcote** [comment]
@ShravaniAK it looks like you have a solid agenda item for today's meeting. 👏

**Comment by l5io** [comment]
🚀 Preview for commit c18a2c5961c08a95c57d4fc673b1442c4c0b8ae9 at: https://6417e84bdf97a65d1f2dfc81--layer5.netlify.app

**Comment by Chadha93** [comment]
@ShravaniAK  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 393d74aa304dddf90c17b4f7f467298670a2b13f at: https://6419822d09fd067db300b315--layer5.netlify.app

**Comment by ShravaniAK** [comment]
@leecalcote @Shivam-AfA please review.

**Review by Shivam-AfA — COMMENTED** [review]
@ShravaniAK The cards looks better now. Although I think we are aiming to show the dark gradient only when the card is in the background, not when it comes to the front to show the content. 

And did you happen to change the font size by mistake? 

image

**Comment by Shivam-AfA** [comment]
@ShravaniAK I think it was a bug in the deploy preview since it's working fine now. 
Please provide some top and bottom padding here, since the text is either too close to the borders or it is being cut off. (in the range of 470px - 767px)

image

image

Also take care
> Although I think we are aiming to show the dark gradient only when the card is in the background, not when it comes to the front to show the content.

Please do this as soon as you can so that we can merge this as this is an important section on the page.

**Comment by leecalcote** [comment]
@Shivam-AfA another review needed.

**Comment by Shivam-AfA** [comment]
@ShravaniAK This looks good now. @leecalcote What images should we use for the cards?

**Comment by ShravaniAK** [comment]
@leecalcote can you please review

**Comment by Shivam-AfA** [comment]
@ShravaniAK we need top and bottom padding on the card:

image

Also please center-align the text above. with the title **Multi-user real-time collaboration**.

We can merge this PR, and we'll be publishing this with the suitable content (text and images).

**Comment by Chadha93** [comment]
@ShravaniAK @Shivam-AfA  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Chadha93** [comment]
Build is failing ....

**Comment by Shivam-AfA** [comment]
@Chadha93. I noticed that the build is failing, that's why I didn't merge this. I think it's due to an extra empty line I guess.

**Comment by l5io** [comment]
🚀 Preview for commit dc1583ecee3b8051d4aba18ccd0382ed366f2d32 at: https://6421e0191df3e911dfc3b753--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
I am reverting this PR, as it causes issues in other pages that uses the same className as the one used in the `.css` file here.
We shouldn't be using `.css` files in gatsby, by default it imports the CSS into all the pages which could lead to unknown issues on different pages if they have similar classNames.

Secondly, I don't see any neew packages been added then why are there changes in the `package-lock.json` file? And, why are the commited? Please refrain from commiting unreelated changes like unwanted extra line additions and spacings, those just bloat the PR and messes up the file history.

Eihter of @ShravaniAK or @Shivam-AfA can submit a new PR in which the `.css` file is converted to a `styled-component` and then the styles are used.

**Comment by Nikhil-Ladha** [comment]
Huh, Github doesn't allow to revert this PR now :/

**Comment by Shivam-AfA** [comment]
Okay, I'll replace the css file with a styled component file. @Nikhil-Ladha. Thanks for pointing this out.

**Comment by Nikhil-Ladha** [comment]
This is an urgent item, so if you could send the fix now it would be helpful.
Otherwise, let me know

**Comment by Shivam-AfA** [comment]
Yes, doing it now.

**Pull request merged**
