### PR TITLE
Included links to projects websites 

### PR DESCRIPTION
**Pull request by Anita-ihuman**
**Description**
I included the links to the project sites on the web based form.
This PR fixes # An enhancement

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c413830946d46385f31b8d7d0ca1445a73e4274c at: https://60e2f7b60d8a13cefb69b009--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Do these changes need to be added to this branch/PR, so as to not create a merge conflict? - https://github.com/layer5io/layer5/pull/1812

**Comment by Anita-ihuman** [comment]
> Do these changes need to be added to this branch/PR, so as to not create a merge conflict? - #1812
Yes, that's right.

**Comment by l5io** [comment]
🚀 Preview for commit 054a35163a7230bd7e770882d1d2114807807d2c at: https://60e47b4260fb0b75b6791a87--layer5ng.netlify.app

**Comment by vinayaksh42** [comment]
I think merging this might create conflicts for this pr https://github.com/layer5io/layer5/pull/1812 , We should get that pr merged asap.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@Anita-ihuman could you please resolve the conflicts?

**Comment by l5io** [comment]
🚀 Preview for commit 6e3aa0ffafcdab84df99b0bb3819ed05531552cd at: https://60e6f0eba9a51bfc9569b692--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 80d0879114f6885c04e6f9f535f5888829783b5d at: https://60e9b4a335cf881f53fafbb1--layer5ng.netlify.app

**Pull request merged**
