### PR TITLE
CHANGED THE FONT COLOR

### LINKED ISSUE #696: [NG] Change the font color to a darker shade
**Current Behavior**
Currently, the single blog page in layer5-ng site has default grey text for paragraphs. It seems to be less readable.

**Desired Behavior**
Change the colour of text to black aur a darker grey such that its easily readable. The CSS file where the changes are to be applied is [here.](https://github.com/layer5io/layer5/blob/layer5-ng/src/posts/blogs/Blog.style.js)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by was-coder**
The font color for the paragraphs are changed to dark gray

Signed-off-by: was-coder <wasleadwears4u2c@gmail.com>

**Description**

This PR fixes #696 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by was-coder** [comment]
@Jashpatel1 can you please review

**Comment by was-coder** [comment]
@leecalcote can you please review this too

**Comment by leecalcote** [comment]
@was-coder, it's confusing, but I think you're looking to make this change in the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng) (not the `master`) branch.

**Comment by was-coder** [comment]
@leecalcote i will check it out now

**Comment by Jashpatel1** [comment]
Hey, @was-coder you have to make the changes in the file I stated in layer5-ng branch. Also the change you made is in the sub-heading. What you have to do is just make a new attribute color: black for the entire CSS(at the very first line of BlogWrapper). If you still have any issues you can hop into slack.

**Comment by Jashpatel1** [comment]
Closing this as another PR is open by the contributor for the same changes.

**Comment by was-coder** [comment]
Ok, I will work on that

**Pull request closed without merging**
