### PR TITLE
Fix layer5 logo

### LINKED ISSUE #2633: Layer5 logo is not responsive
**Current Behavior**

- Layer5 logo is not responsive on every screen size.

**Desired Behavior**

- Reduce the left margin 
- Like the mentioned picture 

---
**Screenshots / Mockups**

image

image

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Krishnapro**
**Description**

This PR fixes #2633 

**Notes for Reviewers**
- layer5 logo is now fully responsive in every screen size. This is my first contribution in **Layer5** please review and merge this.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
@Krishnapro It's still not response in 990 X 1080p

**Comment by Krishnapro** [comment]
Ok  I will checkout again.

**Comment by Krishnapro** [comment]
**On my laptop it's working** what is the problem please help me. @Akshit42-hue 

Screenshot from 2022-03-16 15-49-30

**Comment by Akshit42-hue** [comment]
It's not responsive in my system
Screenshot from 2022-03-16 17-54-40
Try to change min-width

**Comment by l5io** [comment]
🚀 Preview for commit b5fe499e00934ccbbcf552f96e899f08201c339c at: https://6231e7656b95dc0350e76b47--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
@Krishnapro Still not working

**Comment by Krishnapro** [comment]
I think whatever I have changed in code it is not properly pushed or does not save changes. please tell me, anyone, why it is happening. @YashKamboj @Akshit42-hue

**Comment by Krishnapro** [comment]
I think it is working now please check.

**Comment by Krishnapro** [comment]
I have close this pull request and open a fresh pull request please review #2658

**Pull request closed without merging**
