### PR TITLE
[Learn] Using UEM Partner Image Instead of UT Partner Image In Light Mode

### PR DESCRIPTION
**Pull request by akatcha**
Signed-off-by: akatcha <akatcha@flash.net>

**Description**

This PR fixes https://github.com/layer5io/layer5/issues/3743

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 
# Testing
Manual

## Before
image

## After
image

### CODE REVIEW

**Comment by leecalcote** [comment]
@Yashsharma1911 would you like to review?

**Comment by l5io** [comment]
🚀 Preview for commit 90a5dc55371c4430bd7780827ba4d9d24c8f5145 at: https://63e9216e10adff2752180ccd--layer5.netlify.app

**Review by Yashsharma1911 — APPROVED** [review]
Thanks, @akatcha It's working let's get this merged

**Comment by akatcha** [comment]
Sounds great @Yashsharma1911. I'm not able to merge...looks like only someone with write access is allowed to merge :pray:

**Review by eeshaanSA — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit b538bf320ebb5871128588ecb2c729010a117a7f at: https://63ea77c2923ce20cdd7d1ab1--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @akatcha 👍

**Comment by UtkarshMishra12** [comment]
@leecalcote But I don't see any such problem on the website.
image

**Comment by Yashsharma1911** [comment]
Hey @UtkarshMishra12 switch to light mode it works fine in dark mode but not in light mode

**Pull request merged**
