### PR TITLE
fix issue 4148: search state is cleared in grid to list view

### LINKED ISSUE #4148: Clearing of search bar upon changing search result view from list to grid.
### Description
When performing a search on the blog, the search results are displayed in a grid view by default. However, when the user changes the view to list, the search bar is cleared, and any text that was previously entered in the search bar disappears. It would be more intuitive and user-friendly to maintain the searched text even if the user switches between the list and grid view.

Link : https://layer5.io/blog

### Expected Behavior
The searched text should not disappear if you change the view.

### Screenshots
https://user-images.githubusercontent.com/91362589/234633337-f7af795b-5ca5-4b5f-bfec-4e34b67407e5.mp4

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by probiruk**
**Description**

This PR fixes #4148

**Notes for Reviewers**

I have fixed search state is cleared issue when navigating form grid to list view and vice versa.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Hi @probiruk 
Let's discuss this on websites call. Add this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would :)

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Same issue as mentioned [here](https://github.com/layer5io/layer5/pull/4163#pullrequestreview-1425447138)

**Comment by leecalcote** [comment]
@probiruk, will you be continuing your effort here or has this PR been abandoned?

**Comment by thisiskaransgit** [comment]
- Closing as completed by #4373 Thank you for working on this so far.

**Pull request closed without merging**
