### PR TITLE
Added operator-light and changed it according to theme

### PR DESCRIPTION
**Pull request by Harshit-Dandriyal**
Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>

**Description**

Screenshot from 2022-08-16 04-39-22

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you for this example. 🫡

**Comment by l5io** [comment]
🚀 Preview for commit 366d87a9378f5567acaa8439777ede8b307a219e at: https://62fad5be2013e70eb77b5cdd--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for this. I'm also wondering about the approach to graphics listed in data arrays like this one -- 
Screen Shot 2022-08-16 at 8 49 22 AM

**Review by leecalcote — APPROVED** [review]
Swapped images.

**Pull request merged**
