### PR TITLE
fix : Invisibility of Text in Meet the Meshmate Blog #4482

### LINKED ISSUE #4482: Invisibility of Text in Meet the Meshmate Blog
### Description

Currently in the [blog](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma) meet the meshmate : @Yashsharma1911 by @vishalvivekm 

The name of our friendly meshmate isnt available in dark mode.

### Expected Behavior

His name should be visible

# Possible Fix
- removing the color attribute from interviewee section of [MeetTheMeshMate.style.js](https://github.com/layer5io/layer5/blob/18114f5603813f9ef5ce6c5226028f8715badc61/src/collections/blog/2023/2023-05-24-meet-the-meshmate-yash-sharma/MeetTheMeshMate.style.js?plain=1#L18)
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ykumar1415**
**Description**

This PR fixes #4482

**Notes for Reviewers**
Below is the proof : 
Screenshot from 2023-07-06 13-01-57

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ykumar1415** [comment]
@Ghat0tkach can you please review this pr.

**Comment by Ghat0tkach** [comment]
@Ykumar1415 LGTM , good work 🚀

**Comment by Ykumar1415** [comment]
> @Ykumar1415 LGTM , good work rocket

Thanks @Ghat0tkach looking to contribute in more issue.

**Review by Ghat0tkach — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 567e9c9c552cdca433b1d221869c702948a57b6a at: https://64a6727ccdbb3d4b82cd0e89--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
Thanks you gents.

**Pull request merged**
