### PR TITLE
Playground top promotional banner added

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
This PR adds the top promotional banner of the playground. The Try it Now button takes the user to _play.meshery.io_
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit aa8076025ff7d01b2981d1d8b4c1fe3eee129966 at: https://6576ce11ce777551c5db5757--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e95e44b4ada8c5a039e96b8e20e8d98e0e91dbd5 at: https://65786a6ccf0a016ad27cffd7--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a7332bb1acba98ae5773284b033ce9ad31056bb at: https://65789d95fd59a000a96a1b91--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d614d2c7dab92e326c7ace00de315efa84d9d6f1 at: https://657b04c29ba4a51c152701fa--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@ritiksaxena124 the image gets clear as we zoom, not normally clear

https://github.com/layer5io/layer5/assets/90546692/bd48c6bf-3546-4b9e-bd9f-636728a2be87

**Comment by sudhanshutech** [comment]
just a suggestion , can we have a cross button at right most if user want to close the banner

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 the image gets clear as we zoom, not normally clear
> 
>  Recording.2023-12-18.110215.mp4

This is because of the skinny stroke of the stick figure. 

when a user scrolls down, the banner disappears, so maybe we can keep it as it is or close button at right corner is also a good suggestion

**Pull request merged**
