### PR TITLE
Layer5 brand guide added

### LINKED ISSUE #4110: Publish Layer5 Brand Guide
### Current Behavior
Layer5 has a [Brand Guide](https://docs.google.com/presentation/d/1Ofy15e2bAIz4IYC8X70omnlpX9vI0QZpkRijYbxGAd4/edit#slide=id.g232ed436c58_0_144), which needs cleaned up and published.

_Note: submit a community member form, if you can't access the brand guide --> https://layer5.io/newcomer_

### Desired Behavior
1. Clean up the brand guide; give it final polish.
1. Find a section to include a description of the brand guide on https://layer5.io/company/brand or create a new section and publish.

### Implementation
1. Export as PDF.
1. Include PDF in the overall brand kit.zip
1. Publish on /brand page as an individual section.

### Acceptance Tests
1. Brand guide is complete, polished, and publicly available on layer5.io/company/brand

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
This PR adds the brand guide to the layer5.io/brand page

This PR fixes #4110 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6c065ff7d7e904e29d66a242a67acbe9baa61714 at: https://6473175416190814d5f2eabd--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 58e5682680b626aafbfdff5c20bc6fd1fa14719b at: https://647639817572aa00db9d8b12--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@ritiksaxena124 IS the brand guide ready to be published?

**Comment by ritiksaxena124** [comment]
Let's merge this PR so that user's can download it

**Pull request merged**
