### PR TITLE
[Community] Member Profile : added Muhammed Moinuddin

### LINKED ISSUE #5739: [Community] Member Profile: Muhammed Moinuddin
**Current Behavior**

@Muhammed-Moinuddin  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Muhammed-Moinuddin  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  @Muhammed-Moinuddin
- Twitter: https://x.com/moin_TheCoder?t=ie3DABxFX5ep5c57esC4SQ&s=09
- LinkedIn:   https://www.linkedin.com/in/muhammad-moinuddin-software-developer/
- Layer5 Cloud:  https://meshery.layer5.io/user/dce018e4-dde0-4937-931f-b62de3fd5d42
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sanjanaynvsdl**
### Description 
This  [PR](#5739 ) adds Muhammed Moinuddin to the Layer5 community members page.

Changes made:
- Created a new profile file for Muhammed Moinuddin
- Added available information: GitHub, LinkedIn, and Layer5 Cloud profile
- Left placeholders for missing information (Twitter, profile picture)

This recognizes Muhammed's consistent contributions to the Layer5 community.

Closes #5739 
### Screenshots
image

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2cf227a08aacdf91e34728f8d2c3697eb03b0e5d at: https://66a67d71975f4c5dbe977aa8--layer5.netlify.app

**Comment by vishalvivekm** [comment]
### Yay! :balloon: @Muhammed-Moinuddin :sunglasses: :rocket:

**Comment by Muhammed-Moinuddin** [comment]
Kindly use image from here: https://drive.google.com/file/d/1KRMyllE1BvZ6zdJ48OOuS72VrXdhrvWu/view?usp=sharing
Kindly remove hyphen/dash from name.
Change bio to: 
Software Engineer - Computer Science - UoK. 
Passionate about web apps, cloud native and open source, eager to learn and innovate.
Let's connect and grow together.

**Comment by l5io** [comment]
🚀 Preview for commit 0b41f470e829999f7203efe920e6292e0b6cb1f7 at: https://66a72a289788dcea91196483--layer5.netlify.app

**Comment by sanjanaynvsdl** [comment]
@Muhammed-Moinuddin made changes according to your requirements thankyou :)

**Pull request merged**
