### PR TITLE
change seo

### LINKED ISSUE #1667: [News] HashiCorp partnership page has broken link to image
**Description**
This page has a broken image - https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership

Screen Shot 2021-03-04 at 9 28 00 PM

**Expected Behavior**
Image should be displayed on page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <agarwal.5@iitj.ac.in>

**Description**

This PR also fixes #1667

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2e1c94675b0ec2779d27841676477c6122c79e24 at: https://604604a793462c5a6867fddc--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e09a6d9d55b847643a66b01409f92c73baa7a102 at: https://6046213258e88200ad90c0c8--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9d567ac022dd3dd6b83d867141b78b690a14d26d at: https://6046266d199f620bea4bbe7c--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b733a8c956a596919cccc1632382ed2847634d5c at: https://6047e2666c629c00aec15bf6--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a01c6fde49b035b1571af9701427f9a6631de523 at: https://6047f474e3b0aa0a72bcd075--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a01c6fde49b035b1571af9701427f9a6631de523 at: https://6047f447bbe1200a18d32e01--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Wow. Ok, then. :)

**Review by leecalcote — APPROVED** [review]
Let’s do it.

**Pull request merged**
