### PR TITLE
Corrected performance hyperlinks for README file, #1818. 

### LINKED ISSUE #1818: Bad link for Service Mesh Performance in README
**Current Situation**
Hyperlink in README file for Service Mesh Performance - "https://layer5.io/performance" doesn't link to an actual page. (404)

**Desired Situation**
Redirect link to https://layer5.io/projects/service-mesh-performance

### PR DESCRIPTION
**Pull request by Dr-Calvin**
**Description**

This PR fixes #1818

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Very good!

**Comment by l5io** [comment]
🚀 Preview for commit 48e74ce43ce465f6680f0ffc0c8d676bee2232be at: https://6084ca335f5e7457dd2b6b69--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 48e74ce43ce465f6680f0ffc0c8d676bee2232be at: https://6084ca57ded25a7f1677093c--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 48e74ce43ce465f6680f0ffc0c8d676bee2232be at: https://6084ca5c36adba6eb2de1b38--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 48e74ce43ce465f6680f0ffc0c8d676bee2232be at: https://6084cb29a7386364693419c6--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 48e74ce43ce465f6680f0ffc0c8d676bee2232be at: https://6084cb4b4d59487fe75ac790--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Thank you @Dr-Calvin

**Pull request merged**
