### PR TITLE
Added Member Profile of Yash Sharma

### LINKED ISSUE #4820: [Community] Member Profile: Yash Sharma
**Current Behavior**

@yash37158 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @yash37158 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @yash37158
- Twitter:[YashSha49433608](https://twitter.com/YashSha49433608)
- LinkedIn: [yash-sharma-7b688a19b](https://www.linkedin.com/in/yash-sharma-7b688a19b/)
- Meshery Cloud: 
- Link to profile picture:[link](https://drive.google.com/drive/folders/1Z6O09sf6TM_ye2hbl-pkduufzLv-lkex?usp=sharing)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**Description**

- Added member profile of Yash Sharma as Yash.
- Fixed a typo in Yash Sharma member profile changed to Kerala.

This PR fixes #4820 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e367d4ee18e715040cc3c5aa7426618acdacdd93 at: https://6504a30c5ed2ae13e128cca0--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM ! Thanks for the contribution @akhilender-bongirwar

**Review by Mohith234 — APPROVED** [review]
Nicely done @akhilender-bongirwar, LGTM 🚀

@yash37158 You might like to review it.

**Comment by yash37158** [comment]
LGTM 🚀🎉

**Comment by abhijeetgauravm** [comment]
> LGTM 🚀🎉, Great work @akhilender-bongirwar

@Chadha93 @leecalcote Good to merge!

**Pull request merged**
