### PR TITLE
mega menu abstract

### PR DESCRIPTION
**Pull request by shivaylamba**
Signed-off-by: Shivay Lamba <shivaylamba@gmail.com>

**Description**
Revamping of existing nav bar menu items to behave like a Mega Menu 
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Hey @shivaylamba don't you think showing the name of the option again in the dropdown is redundant?. The user knows he has clicked the 'Home' button, so instead of showing that again in the dropdown wouldn't it be better to highlight the nav option which is currently referred to.

**Comment by shivaylamba** [comment]
> Hey @shivaylamba don't you think showing the name of the option again in the dropdown is redundant?. The user knows he has clicked the 'Home' button, so instead of showing that again in the dropdown wouldn't it be better to highlight the nav option which is currently referred to.

I agree with you @Nikhil-Ladha But I was simply trying to implement the design inspiration from Strapi.io site. 
It can be removed.

**Comment by Nikhil-Ladha** [comment]
> > Hey @shivaylamba don't you think showing the name of the option again in the dropdown is redundant?. The user knows he has clicked the 'Home' button, so instead of showing that again in the dropdown wouldn't it be better to highlight the nav option which is currently referred to.
> 
> I agree with you @Nikhil-Ladha But I was simply trying to implement the design inspiration from Strapi.io site.
> It can be removed. I will highlight the nav-bar item. Thanks for your comment.

Ohh ok, No issues. Nice update 👍

**Comment by leecalcote** [comment]
Thank you, @shivaylamba!! 

Wow. The whole thing is covered by just these two files, huh? This is a re-styling of an existing component, right? Or are we pulling in and open source component from somewhere else?

**Comment by shivaylamba** [comment]
@leecalcote I restructured the existing component

**Pull request merged**
