### PR TITLE
pop out card carousel draft

### LINKED ISSUE #3866: Create card component with CSS animation
### Desired Situation

A component with an animation is needed **(referencing to the image below)** where on clicking over a card, it pops out of the stack and gets placed beside the stack as shown in the image. The placed card shows some content. But the cards do not show any content when they are stacked.

image

The color and border-radius that can be used for the card:
`background: linear-gradient(266.65deg, #00B39F 40.19%, #477E96 74.31%, #3C494F 92.89%);`
`border-radius: 20px;`

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by avikt18**
**Description**

This PR fixes #3866 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by avikt18** [comment]
@Shivam-AfA @leecalcote 
Things left to be done:
1. Animate card to the center of the  screen dynamically 
2. Expand the card dynamically to fit its text content.
3. Responsiveness to different screens

**Comment by l5io** [comment]
🚀 Preview for commit 56f2d6fa7962f37ffac756263258e94eb9687bd5 at: https://640f0ad6fbc9f75f15b35e54--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@avikt18 This looks nice. The way cards react to hover is pretty neat. You can use the text in the features section below the card carousel.

**Comment by avikt18** [comment]
Suggestions received:

- Keep one of the cards active (popped out) initially to make the carousel more intuitive. 
- Roll over the cards (move unseen cards on top) as they get opened/popped by user, so that just tapping on one place do the job.

**Comment by l5io** [comment]
🚀 Preview for commit ca566f8f94f66e0a84abda268034452aca5c0694 at: https://641067067eb0860adb65d14f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 34af4b1125c1263f71ab0824be204a90183b42b1 at: https://64106db2b6333b06e3c78edc--layer5.netlify.app

**Comment by avikt18** [comment]
Roll over effect 1.0  (Clicking on any card show the next card but doesn't change the order of them in the deck)
https://641067067eb0860adb65d14f--layer5.netlify.app/cloud-native-management/meshmap/design

Roll over effect 2.0  (Clicking on any card show the next card and also places the current active card at last in deck)
https://64106db2b6333b06e3c78edc--layer5.netlify.app/cloud-native-management/meshmap/design

@leecalcote @Shivam-AfA thoughts on the two variations?

**Comment by Shivam-AfA** [comment]
@avikt18 I think the 2.0 effect looks better. Your thoughts @leecalcote? Although I think it would be better if we use the card with only the green gradient in the center. (Currently the one containing both blue and green gradient is being used).

**Comment by avikt18** [comment]
@leecalcote @Shivam-AfA how about we auto play the carousel?

**Comment by l5io** [comment]
🚀 Preview for commit 9cf9c3670a62e9904baa136832111bf116f36fc6 at: https://64146365a0506315b9dd06a6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ada75d914e003eea196d0446a25db924e6583d56 at: https://64146d8e5e38511d1b473990--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@avikt18 please fix these overflow issues.
image

And also I can still see the card with blue gradient being used in the center. It should be changed to green.
image

And about the autoplay,  it's a good idea, although, it sometimes becomes irritable to the user when the user is trying to read something and it just moves away. So we can save that for later. Currently please make these changes and also correct the remaining responsiveness issues.

**Comment by Chadha93** [comment]
@avikt18  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit fdd833996bfeba9e3d5c2e883b38136a2d2a0939 at: https://64183e9c97a24a3470ec150c--layer5.netlify.app

**Comment by leecalcote** [comment]
@Shivam-AfA there are few unreviewed commits here. Is this PR acceptable or needs more work?

**Review by Shivam-AfA — COMMENTED** [review]
Thanks for fixing the issues @avikt18. There's a little tiny issue left here:

image

And speaking for the responsiveness, we can remove the description text beside the cards, and that'll allow to increase the width of the active card. Please make this change as soon as you can so that we merge this PR. This carousel is quite awaited.

**Comment by avikt18** [comment]
@Shivam-AfA We can make the heading above the cards only below 768px when the whole page becomes centre aligned. Above that, I guess it would look off.

**Comment by Shivam-AfA** [comment]
Above 767px, we can separately center align the heading.

**Comment by Shivam-AfA** [comment]
This is being done to provide a full width to the card, so that a supporting image could also be added inside it.

**Comment by avikt18** [comment]
> This is being done to provide a full width to the card, so that a supporting image could also be added inside it.

Ohh, got it

**Comment by l5io** [comment]
🚀 Preview for commit 0aedaf5415ce5dba89384d0f881342eb1a6d41b7 at: https://641ad6deca810605a5dabc95--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@avikt18 Did you work on the feedback?

**Comment by Shivam-AfA** [comment]
@avikt18 Yes sure, add a sample image.

**Comment by Shivam-AfA** [comment]
@leecalcote Does this look good to merge?

**Comment by l5io** [comment]
🚀 Preview for commit 1cbb2c032befdeefb2d2445cea01e07b011ba74e at: https://641daee3b0ea48354b62ef15--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@avikt18 This looks really good. We'll merge this, but need some changes before publishing this: 

- The center card should cover the full width. No whitespace should remain.
image

- We'll need to update the text content and images befoe publishing.

**Comment by Chadha93** [comment]
@avikt18  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 36592ab457d208abe5ab6d34d348f9ba1760474d at: https://64220049e95ed307f3b6941a--layer5.netlify.app

**Pull request merged**
