### PR TITLE
Update Contributor to Community

### PR DESCRIPTION
**Pull request by Ruth-ikegah**
Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>

**Description**

This PR fixes #1248

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ruth-ikegah** [comment]
> Great work @Ruth-ikegah !!

Thanks @kushthedude It feels good contributing.

**Comment by kushthedude** [comment]
Congrats @Ruth-ikegah, for your first PR in the community!!! 🥳 🥳

**Comment by Ruth-ikegah** [comment]
Thanks @kushthedude It is actually the second,lol

**Comment by kushthedude** [comment]
Oops my bad 😅 !

**Comment by Ruth-ikegah** [comment]
> Oops my bad 😅 !

It's fine. Hoping to contribute more!

**Pull request merged**
