### PR TITLE
fix: toc component links are active when they shouldn’t be in mobile

### PR DESCRIPTION
**Pull request by StephNathai**
Signed-off-by: Stephanie Nathai-Cueter <stephanie.nathaicueter@aexp.com>

**Description**
Defect fix for active table of content component links for mobile
This PR fixes [#2138](https://github.com/layer5io/layer5/issues/2138)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yay! Thank you, @StephNathai

**Comment by l5io** [comment]
🚀 Preview for commit b55debabb3a293a8c130852d1568f96eee4aeaee at: https://612e757f2689240ff5d722b6--layer5ng.netlify.app

**Review by NikhilSharma03 — APPROVED** [review]
LGTM. Thank you @StephNathai  :rocket:

**Review by Ruth-ikegah — APPROVED** [review]
well done @StephNathai! looking good to me!

**Review by warunicorn19 — APPROVED** [review]
Good work @StephNathai , LGTM😄.

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
