### PR TITLE
[Community] Added Freedisch as new Community Member

### LINKED ISSUE #4435: [Community] Member Profile: Freedisch
**Current Behavior**

@freedisch has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @freedisch as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @freedisch
- Twitter: 
- LinkedIn: [thibaut-freedisch-batale-905843208](https://www.linkedin.com/in/thibaut-freedisch-batale-905843208/)
- Meshery Cloud: [a551897f-da39-4d4d-812e-6b299e82c457](https://meshery.layer5.io/user/a551897f-da39-4d4d-812e-6b299e82c457)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Chetan-Managavi**
**Description**

This PR fixes #4435.
Freedisch

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2466def8f3aa58b5901a444a532dec288426da6b at: https://64997ca2078a800654927812--layer5.netlify.app

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@Chetan-Managavi , kindly revise the modifications you made to the BookComponent.js and index.js files, please.

**Comment by Chetan-Managavi** [comment]
@hirentimbadiya I am not able to commit without doing those changes. It shows error due to checklint  script run before commit is done.

**Comment by l5io** [comment]
🚀 Preview for commit 2fb09b1a4752a34d9e31b43322249aa22b19d9b6 at: https://649c2af4aaae600d8d3d392a--layer5.netlify.app

**Pull request closed without merging**
