### PR TITLE
added card for adventures of five and friends in handbook section

### LINKED ISSUE #4616: [Handbook] Add card for Adventures of Five and Friends
### Current Behavior
On the community handbook [page](https://layer5.io/community/handbook), there is no card for Adventures of Five and Friends.

### Desired Behavior
Add a card for Adventures of Five and Friends on the handbook, link it to https://layer5.io/community/adventures-of-five-and-friends

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Shashank2104125**
**Description**
This PR add card for adventures of five and friends in handbook section

This PR fixes #4616 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f306c23521e9a242ae3be824498901946e59c9e7 at: https://64c8319051a5ca1bfce6b444--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
hey @Shashank2104125 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by yeskaydee** [comment]
@Ghat0tkach so you cloned the repo, and hosted it on netlify??

Second question:- where can i find the source code to make changes? , i am really sorry if my questions are too basic, i am learning to contribute to open source

**Comment by Shashank2104125** [comment]
> @Ghat0tkach so you cloned the repo, and hosted it on netlify??
> 
> Second question:- where can i find the source code to make changes? , i am really sorry if my questions are too basic, i am learning to contribute to open source

@yeskaydee No problem it's common for newcomers but try to ask your doubt on the discussion forum https://discuss.layer5.io/

**Comment by yeskaydee** [comment]
@Shashank2104125 got it , thank you very much, will post q in community

**Review by Chadha93 — APPROVED** [review]
Good work @Shashank2104125

**Pull request merged**
