### PR TITLE
made image responsive

### LINKED ISSUE #4387: Blog Landscape Cards images are not responsive
### Description
In [blog/category/landscape](https://layer5.io/blog/category/landscape), the first two categories of images are going out of the boxes on mobile view and there should be some minimum gap between the search bar and category boxes.  

### Expected Behavior

It should be inside of the boxes.

### Screenshots
Screenshot (59)

#### on mobile:
screenshot_20230616-212002 (2)

### Environment:
- Host OS: Windows
- Browser: All 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by harshit-senpai**
**Description**

This PR fixes #4387

**Notes for Reviewers**
made the image responsive and added a breathing space search box and card

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 07aba99711906a66652a84aeba58b59d2b46415b at: https://64a8763d3571ea0d026532fe--layer5.netlify.app

**Comment by samyakshah3008** [comment]
@harshit-senpai  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit 30af4d9fe97fb34480470dc3370ef7712163d929 at: https://64aaa13401213a1fe77869b5--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
@vaibhav-xt the preview looks good now? Mind giving it a check on your end?

**Comment by vaibhav-xt** [comment]
@Nikhil-Ladha In my opinion it's looking good 😊 to merge 🚀.

**Review by vaibhav-xt — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit ad6cc6b141380c01f3f387beb821e0f5ba9a7ad4 at: https://64b2e19b9a72cb3200efe1a5--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by harshit-senpai** [comment]
Hey since the changes have been approved. Can the branch be merged now

**Comment by vaibhav-xt** [comment]
Thank you @harshit-senpai  & @Nikhil-Ladha for making this a successful pull request.

**Pull request merged**
