### PR TITLE
add meshmap section in readme

### LINKED ISSUE #4242: [Readme] Add MeshMap project entry
### Current Behavior
This repository's readme.md has a list of Layer5' projects. Currently, this list is missing an entry for MeshMap (https://layer5.io/meshmap).

### Desired Behavior
Readme.md has an entry for MeshMap.

### Implementation
1. Use MeshMap logos from src/assets/images/meshmap
2. Use SVGs not PNGs.
3. Support both light and dark modes image versions.
4. Follow aa similar format as to the existing project entries.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Meyazhagan**
**Description**

This PR fixes #4242 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ayushthe1** [comment]
@Meyazhagan   Let's discuss this on websites call. Add this as an agenda item in meeting minutes if you would :).
I'll add this item for you if it's ok.

**Comment by leecalcote** [comment]
Don't forget to sign off on your commits.

**Comment by Meyazhagan** [comment]
> Will you ensure that light and dark mode is considered for here?

@leecalcote yes, I used this icon, which is same in the website. works well in both mode 

image

**Comment by goldfishdolphin** [comment]
@Meyazhagan, thank your for your contribution. Can you please ensure that the styling of the MeshMap is sync with other projects? 
Screenshot 2023-05-22 at 12 24 30 pm

**Comment by l5io** [comment]
🚀 Preview for commit f2e16ef5bc92ee2ded565aef7ab30ec7d436b372 at: https://646b59afbf05c42d0d1a9589--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
