### PR TITLE
[Resource] New article - Istio at a Glance

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
1) Added a new article to `/resources`.
2) Added a Resource Template.
3) Removed few unnecessary styles from Resources stylesheet.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@debo19 good stuff. Let's qualify this resource as Istio v1.5. The architecture of Istio changed from v1.6 forward.

**Comment by l5io** [comment]
🚀 Preview for commit 3a4f02093c03091008c1694f233890a518aa4f7c at: https://61fd9e8a8869350cdb80906e--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 62fb590bebc7e0490286717c55c7cd345016645c at: https://61fe93fcb19bda4412bd7d3d--layer5ng.netlify.app

**Comment by debo19** [comment]
@leecalcote changed the title. Good to merge? I'll add a couple more articles soon.

**Review by warunicorn19 — APPROVED** [review]
Looks good

**Comment by leecalcote** [comment]
@debo19 yes, ma'am. It would be nice to use diagrams that don't have my "@lcalcote" twitter handle on them. You can grab new screenshot from any of the presentations here: calcotestudios.com

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 478cfaf9ac58043bca86d731be358b93f124f45a at: https://62000b3dfffbdb205a9822fb--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@debo19 could you please make the image a little bigger, it's getting really tiny in smaller views.

**Comment by l5io** [comment]
🚀 Preview for commit 55ce3add739f18036494d581e5d03a03415de340 at: https://6200fe4b5f2b550a21dacfd0--layer5ng.netlify.app

**Pull request merged**
