### PR TITLE
added 1 more question in FAQ section

### LINKED ISSUE #3862: add 1 more question in FAQ section .
### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #3862 

Screenshot 2023-03-02 at 9 49 00 PM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8c719824f65d64d4e61177905282519a0a3b0a9b at: https://6400d13003fd850666e99f80--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks, @ShravaniAK. Will you please rephrase the question?

**Comment by ShravaniAK** [comment]
yes will de that @leecalcote

**Comment by ShravaniAK** [comment]
Are development meetings set up to discuss the New development code changes made and for PR discussion?

is this fine or should it modify it more?

**Comment by leecalcote** [comment]
> Are development meetings set up to discuss the New development code changes made and for PR discussion?
> 
> is this fine or should it modify it more?

I must have misunderstood what you were asking. You were simply asking if we hold project meetings. Yes, we do and it's well documented already. There's no need for an FAQ on this.

I thought that you were asking a question past this one, though. I thought that you were asking, "In addition to the routinely scheduled project development meetings, do project contributors ever meet separately to deep-dive on special topics?"

We had just ended the weekly Meshery Development Meeting when you asked in Slack, which is part of why I thought that you were asking something further. If you'd like to update this PR with the question that I phrased above, then yes, this is a question and answer that can be published.

**Comment by ShravaniAK** [comment]
ok i will update the question , will that work ?

**Comment by leecalcote** [comment]
I’ll repeat:

> If you'd like to update this PR with the question that I phrased above, then yes, this is a question and answer that can be published.

**Comment by ShravaniAK** [comment]
yes i meat that i will update the current question with the question that you phrased

**Comment by l5io** [comment]
🚀 Preview for commit 7e7a700315cf17d5cb01d058f0fc4a489701ec35 at: https://6401d66974931f10efd82702--layer5.netlify.app

**Comment by leecalcote** [comment]
Yes, I know. That’s what I said.

**Comment by ShravaniAK** [comment]
will you please check if its ok now , please let me know if there are more changes to be made

**Comment by l5io** [comment]
🚀 Preview for commit b89daacd89bff0d9eabe9ed88fa758a575865681 at: https://6401f52a66ba0a142c16a5fb--layer5.netlify.app

**Pull request closed without merging**
