### PR TITLE
fixed the height and width of the logos

### LINKED ISSUE #5308: Fix stretching of some brand logos
### Description

Visit the page:
https://layer5.io/cloud-native-management/meshery/integrations

Notice some brand logos are stretched this needs fixing
Screenshot 2024-01-20 at 8 47 31 PM

### Environment:
- Host OS: iOS/Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Abraham599**
**Description**

This PR fixes #5308

**Notes for Reviewers**
Fixed the height and width of the logos which was earlier stretched out

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by VamshiReddy02 — APPROVED** [review]
LGTM!
Screenshot 2024-02-05 at 11 35 19 PM

**Comment by leecalcote** [comment]
> LGTM! Screenshot 2024-02-05 at 11 35 19 PM

This screenshot does NOT LGTM.

**Comment by narasimha-1511** [comment]
Can i also try to fix the error?

**Comment by saurabh100ni** [comment]
are you still working on this @Abraham599? If not, let's get this assigned to @narasimha-1511.

**Comment by narasimha-1511** [comment]
hey @leecalcote can i work on this issue as there is no response form @Abraham599 .

**Comment by leecalcote** [comment]
@narasimha-1511, sounds real good. Thanks for stepping up. 👍

**Comment by leecalcote** [comment]
@iArchitSharma, I believe that the solution offered his PR only reinforces the skewing on the aspect ratio, is that right?

**Comment by iArchitSharma** [comment]
This issue has already been fixed!

**Pull request closed without merging**
