### PR TITLE
fix: fix typo

### LINKED ISSUE #5128: [Handbook] Word repetition
### Description

Currently the word "other" is repeated twice (after each other) in a sentence. 

Path: Handbook > [General FAQ's](https://layer5.io/community/handbook/faq) > last answer --> "...the community calendar, while other other times they are simply self-organized by interested contributors."
### Expected Behavior

Removing the duplicate word _other,_ would fix the grammar/typo i.e "...the community calendar, while other times they are simply self-organized by interested contributors."

### Screenshots

img
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by phukon**
-remove redundant 'other' in the route /community/handbook/faq

fixes #5128 

**Description**
The word "other" is redundant in a sentence within the Handbook's General FAQ section.

**Notes for Reviewers**
Context:
This PR addresses a minor typo/grammar issue in the General FAQ's section. The redundant word "other" has been removed to improve sentence clarity and readability.

Scope:
The change is isolated to a single sentence in two files and doesn't affect any other content. It's a straightforward fix.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6224d12383bf9eda8bb0dad82abb42ca203d2e6b at: https://65554187106979047e812c9d--layer5.netlify.app

**Comment by sandramsc** [comment]
@phukon Hi thanks for your enthusiasm to contribute. Issues are assigned on a "first come first serve basis" by commenting on them and the issue this PR attempts to resolve is already assigned to someone else. I suggest reading the [New Comers Guide](https://layer5.io/community/newcomers), particularly the section under "Finding an Issue to Work On" first before creating a PR in future,  in order to prevent your work and efforts from going to waste.

**Comment by phukon** [comment]
Thank you for the heads-up! I apologize for the oversight.

**Comment by abhijeetgauravm** [comment]
@phukon Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Pull request closed without merging**
