### PR TITLE
Integrations boxes now have a sufficient margin(Left & Right)

### LINKED ISSUE #3461: Integrations boxes do not have a sufficient margin(Left & Right), due to which it is touching the extreme left and right of the device screen
#### Description

Integrations boxes do not have a sufficient margin(Left & Right), due to which it is touching the extreme left and right of the screen

#### Page Link:

[Link](https://layer5.io/)

#### Expected Behavior

There should be a proper left and right margin.

#### Screenshots

https://user-images.githubusercontent.com/67385503/202512803-0344093f-3344-452f-88df-7542ad5bf7ba.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Integrations boxes now have a sufficient margin(Left & Right)

This PR fixes #3461 
**Before**

https://user-images.githubusercontent.com/67385503/202538088-e207dfaa-f948-456b-9bf6-93af252f7fb7.mp4

**Now**

https://user-images.githubusercontent.com/67385503/202538118-a4d2fa24-2aee-4260-a028-b1f037ec6496.mp4

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 13de20becb5b664a5e1ad4a8491e1b7052c7bfbb at: https://63768ca5c159520be818ea7a--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
Cool :+1:

**Comment by Chadha93** [comment]
@UtkarshMishra12 Thanks for adding the video demo fix PR description. I really appreciate it. :ok_hand:

**Comment by UtkarshMishra12** [comment]
My pleasure @Chadha93  😊

**Pull request merged**
