### PR TITLE
[Blog] The legendary Maintainer Vivek Vishal

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Description**

This PR highlights the works of @vishalvivekm

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 89820945b2c07fdc2b3298a09f757705321c1f77 at: https://67125f3fd0608b2a039fb468--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@vishalvivekm good to go?

**Comment by leecalcote** [comment]
@vishalvivekm will need to fill in a few blanks.

**Comment by leecalcote** [comment]
PR abandoned. @vishalvivekm never responded.

**Pull request closed without merging**
