### PR TITLE
Add White Calico Icon

### PR DESCRIPTION
**Pull request by NPDebs**
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>

**Description**

This PR fixes issue #3346.
I created a white version of the Calico logo to be used in the dark mode.

layer5-calico-pr

**Notes for Reviewers**
I'm open to feedback and suggestions, please. Thank you!

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NPDebs** [comment]
@sahilsuman933, @legendarykamal, @eeshaanSA, @richardnikolas.........have a look, please. 👀

**Comment by l5io** [comment]
🚀 Preview for commit 9426c6f980e4d372f984cd6074233136102b6154 at: https://634f7bf8315383478ff9510d--layer5.netlify.app

**Comment by eeshaanSA** [comment]
Good work, @NPDebs 🚀

**Comment by sahilsuman933** [comment]
@NPDebs It looks excellent, but we only need the logo icon, not the text. So, could you please update that?

**Comment by NPDebs** [comment]
> @NPDebs It looks excellent, but we only need the logo icon, not the text. So, could you please update that?

@sahilsuman933 Thanks! 🙌🏼
I think you might be viewing on Github mobile. Hehe.
I did upload the svg icon. 😃

Screenshot_20221019-074040_Chrome

**Comment by sahilsuman933** [comment]
What I meant was we need calico icon logo not the one with text.  @NPDebs

**Comment by NPDebs** [comment]
> What I meant was we need calico icon logo not the one with text. @NPDebs

Ahhh. Of course that's what you mean. 😶

I'll update this one to exclude the text now. 👍🏻

**Comment by NPDebs** [comment]
@sahilsuman933 Done. 🤲🏻

**Comment by NPDebs** [comment]
Oh, I just noticed the poor guy is missing a whisker. 🤦🏽‍♀️ Not if I can help it! 🏃🏽‍♀️ 🏃🏽‍♀️

**Comment by NPDebs** [comment]
Done done @sahilsuman933 . 👍🏻

**Comment by l5io** [comment]
🚀 Preview for commit 0adea815a51afb225832375be60f86a1848a6fdf at: https://634fb23b77f3d666e4012a15--layer5.netlify.app

**Comment by sahilsuman933** [comment]
LGTM! 🚀

**Review by sahilsuman933 — APPROVED** [review]

**Pull request merged**
