### PR TITLE
Add Sistent-box component

### LINKED ISSUE #5906: [Sistent] Add `Box` component to the sistent components page
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [Box](https://github.com/layer5io/sistent/blob/5529c342c6ad2b00b8e8d08deafc02fe72fe5513/src/base/Box/Box.tsx).

(https://playground.meshery.io/management/environments)
image

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The Box component currently needs this representation.

### Desired Behavior

Proper documentation for Box component similar to Button component on https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation of the the function that the component serves in context of it's usage.
- Code examples.
- Stylistic guidelines to be followed while using the component in code (if any).

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 🎨 See [Sistent Repository](https://github.com/layer5io/sistent).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by mdkaifansari04**
**Description**
Added sistent box component with detailed documentation and easy examples
This PR fixes #5906

**Notes for Reviewers**
image
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bca574ac083c0209ad27f2996bf43b20e544cadc at: https://67269b8315ea81048abdf188--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@mdkaifansari04  Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit 2792c419920ee58886586e8170e88ba81f41f725 at: https://672a88e12362cc512152ddc8--layer5.netlify.app

**Comment by Vidit-Kushwaha** [comment]
Hello, @mdkaifansari04 , can you remove the excess indentation from the array of code in the code example so that it looks more uniform?

**Comment by mdkaifansari04** [comment]
@Vidit-Kushwaha can you please check if the changes needs made look perfect

**Comment by l5io** [comment]
🚀 Preview for commit 2a93ef126d1bb9420cf4adcd209d222517c0d1cb at: https://672bcd526848a14313dd48df--layer5.netlify.app

**Review by ianrwhitney — COMMENTED** [review]
LGTM

**Comment by Vidit-Kushwaha** [comment]
@mdkaifansari04 It looks great.

**Comment by l5io** [comment]
🚀 Preview for commit 19b368ef87ef9293370272ff5a8743de0c672c19 at: https://673214f27db18127fcd6e380--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 100b21e135fa91d873cb243bf82a5b8bc1e207a7 at: https://673258db5c8bad924148faac--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
