### PR TITLE
Profile of Suhani Agarwal has been added

### LINKED ISSUE #2155: [Community] Member Profile: Suhani Agarwal
**Current Behavior**

@suhaniii  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @suhaniii  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @suhaniii 
- Twitter: 
- LinkedIn: suhani-agarwal (https://www.linkedin.com/in/suhani-agarwal/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by vishal-codes**
**Description**
Profile of Suhani Agarwal has been added on the members page of the website
This PR fixes #2155

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Not going to make a difference but just a nitpick😄, if you could please name the jpeg file as Suhani Agrawal, instead of Shivani Agrawal, might cause confusion in the future

**Comment by vishal-codes** [comment]
> Not going to make a difference but just a nitpicksmile, if you could please name the jpeg file as Suhani Agrawal, instead of Shivani Agrawal, might cause confusion in the future

Ohh sorry !! I'll make the changes right now

**Comment by warunicorn19** [comment]
Also, it seems like you also committed Abhishek Kumar's profile in this PR, if you could please also revert that.

**Comment by vishal-codes** [comment]
> Also, it seems like you also committed Abhishek Kumar's profile in this PR, if you could please also revert that.

How did that got commited I have no idea 
😵 I used a different branch for adding his profile

**Comment by warunicorn19** [comment]
It might be because you didn't switch to the master branch before you created this branch😅.

**Comment by vishal-codes** [comment]
> It might be because you didn't switch to the master branch before you created this branchsweat_smile.

How can I undo those commit?

**Comment by warunicorn19** [comment]
🤔 ummm, you could try to either revert these files, or rebase or create a new PR.

**Comment by warunicorn19** [comment]
Creating a new PR would probably be the easier solution, I think

**Comment by vishal-codes** [comment]
> Creating a new PR would probably be the easier solution, I think

I'll do this

**Pull request closed without merging**
