### PR TITLE
Add white version for Knative logo

### LINKED ISSUE #3364: Create a white Knative Logo for Dark Theme
**Current Behavior**

You need to create a white logo for Knative for the dark theme, which will be used across the website.

You can find the colored logo in location `layer5/src/collections/integrations/knative/icon/color/knative-icon-color.svg`.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by beakman**
**Description**
White version for Knative logo.
This PR fixes #3364

### CODE REVIEW

**Comment by sahilsuman933** [comment]
@beakman Thank you for contributing to Layer5. But, there are a few things that you have to change like we want only a black and white logo so that it will fit the dark mode. 

You can check out this PR for your reference:
https://github.com/layer5io/layer5/pull/3360
https://github.com/layer5io/layer5/pull/3343

Also, please do the DCO and always ask for permission before working on any issue by asking the author to assign that issue to you. You can check out this guide for DCO
https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits

**Comment by beakman** [comment]
Sorry @sahilsuman933! I will ask for permission next time for sure. I've uploaded a black and white version of the logo at: src/collections/integrations/knative/icon/color/knative-icon-bw.svg

**Comment by sahilsuman933** [comment]
Great. Now, could please do DCO @beakman?

**Comment by beakman** [comment]
Sure @sahilsuman933 !

**Review by sahilsuman933 — APPROVED** [review]

**Pull request merged**
