### PR TITLE
Reduced response message height

### LINKED ISSUE #3081: [Contact Form] Reduce response message height after form submission
#### Description
Screenshot 2022-08-12 at 8 18 56 PM

#### Expected Behavior
The message should not take up this unwanted space. 

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by janvi01**
Signed-off-by: janvi01 <janvibajo1@gmail.com>

**Description**

This PR fixes #3081 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8008f88b17334823407377b978f803a1ddbfe9f0 at: https://632d494fbb11713fd9bf299b--layer5.netlify.app

**Comment by janvi01** [comment]
Attaching ref screenshot

Screenshot 2022-09-23 at 10 56 15 AM

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Unfortunately, this doesn't help.
Because we lose the smooth transition of form opening.

CSS Animations could be something you can look upon to fix this issue and keep the smooth animation, replacing the transition property.

**Comment by janvi01** [comment]
Oops, I didn't notice that. 
I see we cannot apply the transition effect to the `max-content` height.
An Alternate solution to this could be
Let the height of the form remain at its initial value and change it to maybe `20rem` when the form is submitted using JavaScript.
What do you say? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Hmm...yeah, we can do that as well.
Though, animations didn't work out either?

**Comment by janvi01** [comment]
It's working!

**Comment by Nikhil-Ladha** [comment]
> It's working!

Which one?

**Comment by janvi01** [comment]
> Oops, I didn't notice that. I see we cannot apply the transition effect to the `max-content` height. An Alternate solution to this could be Let the height of the form remain at its initial value and change it to maybe `20rem` when the form is submitted using JavaScript. What do you say? @Nikhil-Ladha

The solution I mentioned here.

**Comment by Nikhil-Ladha** [comment]
Cool, do push your changes once you are done with "test@gmail.com" :)

**Comment by janvi01** [comment]
I wonder if that's the ideal approach as I have used JS here. @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
It's fine, we are using JS to toggle the classList in the first place too.
Though, please fix the DCO.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by janvi01** [comment]
Thanks, @Nikhil-Ladha :) I will make sure next time.

**Pull request merged**
