### PR TITLE
[Blog] Validating mesheryctl functionalities

### LINKED ISSUE #2476: [Blog] Validating Meshery CLI Functionality
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

#### Core points to convey in the post:
1. the need for user acceptance testing.
1. how to checkout a PR’s branch 
1. how to build `mesheryctl` (incorporate instructions for different OSes)
1.  how to test with your compiled binary
1. reference to https://docs.meshery.io/project/contributing/contributing-guide and how these principles and practices should be kept in mind while assessing functionality and UX.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>

**Description**

This PR fixes #2476

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@debo19 could you please take a look why the build is failing.

**Comment by leecalcote** [comment]
@piyushsingariya still considering tying this one off or should we close it?

**Comment by leecalcote** [comment]
Updating with master...

**Comment by l5io** [comment]
🚀 Preview for commit 83a89244609e11f936ac0c24fffb48ef9a61934a at: https://62875b2e7489432b518ff584--layer5ng.netlify.app

**Comment by piyushsingariya** [comment]
Blog link- https://62875b2e7489432b518ff584--layer5ng.netlify.app/blog/meshery/validating-meshery-cli-functionality

**Comment by Nikhil-Ladha** [comment]
@leecalcote ready to take this in?

**Comment by leecalcote** [comment]
Thanks for asking - yes, good to go 👍

**Pull request merged**
