### PR TITLE
[Design Page] Deck of cards background gradient update

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
This PR updates the background of the deck of cards on the `https://layer5.io/cloud-native-management/meshmap/design` page.

**Current view:**
image

**After PR merge view:**
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 09b6aa10e93099992eef92863d8694a70bb5175a at: https://659d996ca1714846d5194199--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 022dd383bddc807db32361d83b42a149e568159f at: https://659e771ae0eeffcc2ca2ef79--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit df4fbaeda4bc6f3fe1ad106fd8f1c0e358ee0342 at: https://65a1148f4bef13b0b53c13e7--layer5.netlify.app

**Comment by leecalcote** [comment]
Why was the box shadow removed? We were only looking for a card color change.

**Pull request merged**
