### PR TITLE
Fix: Updated Newcomers page mascot image

### LINKED ISSUE #4929: [Community] Newcomers: Update mascot image
### Current Behavior
The [Newcomers page](https://layer5.io/community/newcomers) has an old version of Five, our stick figure mascot.

Screenshot 2023-09-17 at 8 41 39 PM

### Desired Situation
Replace the old version with one of the available new versions of Five. Select from those available under https://layer5.io/brand

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**Description**

- Replaced the outdated version of Five, our stick figure mascot, on the Newcomers page.
- The new mascot image has been selected from the available updated versions provided under https://layer5.io/brand.

This PR fixes #4929 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
@Rajdip019 Up for review 👀

**Comment by Rajdip019** [comment]
@akhilender-bongirwar if `contributor-chest-colorMode.svg` is not getting used anywhere then we can remove that. Everything else looks fine.

**Comment by akhilender-bongirwar** [comment]
Yeah `contributor-chest-colorMode.svg` , `contributor-chest-white.svg` and `contributor-chest.svg` are not getting used anywhere.
Should I remove all of them?

//@Rajdip019

**Comment by Rajdip019** [comment]
> Yeah `contributor-chest-colorMode.svg` , `contributor-chest-white.svg` and `contributor-chest.svg` are not getting used anywhere. Should I remove all of them?
> 
> //@Rajdip019

Yes, it's better to remove them. As the svgs are updated with new ones.

**Comment by l5io** [comment]
🚀 Preview for commit 98394d909abc59eb04f34f4115b4b1b31c70020b at: https://650c9690ec18021f525a859c--layer5.netlify.app

**Comment by akhilender-bongirwar** [comment]
Hey @Rajdip019, removed all the old svg files. Could you please review this PR : )

**Review by Mohith234 — COMMENTED** [review]
The logo looks good in light mode, what about the dark mode? Do we have any other mascot logo for the dark mode to look better? @akhilender-bongirwar 

image

**Comment by akhilender-bongirwar** [comment]
I see no problem with the looks of the logo even in the dark mode; it looks great IMO. //@Mohith234 
Please any other opinions on the change of the logo for the dark mode would be appreciated greatly. // @Rajdip019

**Comment by Rajdip019** [comment]
The logo in dark mode looks good to me as well.

**Comment by akhilender-bongirwar** [comment]
Thank you for the immediate feedback @Rajdip019 : )

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
