### PR TITLE
[Blog] New post

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

This PR will add @Nikhil-Ladha's experience post to the Layer5 blog.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — DISMISSED** [review]
I thought some more changes may be needed there....but it seems like without you the blog would have been impossible. Thank you @chandrashritii :tada:

**Comment by Nikhil-Ladha** [comment]
And, also nevertheless the feature image....It's just **MIND BLOWING**!!
@leecalcote I guess @chandrashritii can be our visual designer :laughing:

**Comment by leecalcote** [comment]
> And, also nevertheless the feature image....It's just **MIND BLOWING**!!
> @leecalcote I guess @chandrashritii can be our visual designer 😆

If I had bigger muscles, I would use them here. 💪

**Comment by leecalcote** [comment]
No image update here, right?

**Comment by chandrashritii** [comment]
@leecalcote Shared alternative options with you on slack.

**Review by leecalcote — APPROVED** [review]
Awesome

**Comment by Nikhil-Ladha** [comment]
Finally, I have my image on that card too! Yippee 😁🎉

**Comment by Nikhil-Ladha** [comment]
Thank you for the improvement here @chandrashritii 🙂

**Comment by leecalcote** [comment]
It’s pretty cool. We’ll have to get busy on social media about this on Monday.

**Pull request merged**
