### PR TITLE
Added Dark Mode logo for eBPF

### LINKED ISSUE #5056: A specific dark-mode version of ebpf logo on catalog page
### Description

- Currently, in the dark mode the "ebpf logo" is not visible accurately on the [catalog page](https://layer5.io/catalog)
### Expected Behavior

- A dark-mode friendly ebpf logo should be updated with the current one

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Shreyas0410**
**Description**

This PR fixes #5056 

**Notes for Reviewers**

Screenshot 2023-10-18 191708

I have followed the design guidelines of eBPF logo and added dark mode for it (https://ebpf.foundation/brand-guidelines/) 

Screenshot 2023-10-18 190720

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 270e47c0eb106de9898d9ee36a3db2e815845104 at: https://652fe8b36a619200927ed1a3--layer5.netlify.app

**Comment by oerzn** [comment]
Looks good!

**Comment by Shreyas0410** [comment]
@Mohith234 can you have a look?

**Review by leecalcote — APPROVED** [review]
Some clean work here. Good stuff, @Shreyas0410 👏

**Comment by leecalcote** [comment]
Thank you for reviewing, @oerzn. This helps!

**Pull request merged**
