### PR TITLE
fixed coming soon image in layer5/pricing

### LINKED ISSUE #4335: coming soon image not rendering on layer5/pricing
### Expected Behavior

Fix the coming soon image
### Screenshots

Screenshot from 2023-06-05 08-53-41

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4335 
image

**Notes for Reviewers**
The reason behind this is that in the import statement for the coming_soon image, the file extension was modified from .png to .webp. However, the image was imported from a web link instead of being located within the project directory. There are two potential solutions. The first option is to include the image in the project directory and the other is reverting the file extension in the import statement back to .png. 
In this PR I opted the second option.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7eaf0c169a88475d735b76121489b09bdc6b775c at: https://647f1e1b3c600317b69f2761--layer5.netlify.app

**Comment by Savio629** [comment]
Hey @AkashS20 we had a discussion to convert all the png/jpg to webp for better performance.

**Comment by l5io** [comment]
🚀 Preview for commit d8696b4f55018ba7b929ad858907f950d764616f at: https://6481f5f42c10850f1324d7a2--layer5.netlify.app

**Comment by AkashS20** [comment]
@Savio629 I have added the image to the project directory now

**Review by leecalcote — APPROVED** [review]
Great feedback, @Savio629

**Comment by leecalcote** [comment]
Thanks, @AkashS20!

**Pull request merged**
