### PR TITLE
fixes [Community] Member Profile: Matthieu EVRIN #5566

### LINKED ISSUE #5566: [Community] Member Profile: Matthieu EVRIN
**Current Behavior**
@lekaf974 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @lekaf974 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @lekaf974
- Twitter:@mevrin
- LinkedIn: 
- Layer5 Cloud: e4a0ec88-35c6-4976-9715-f3d0f8ff029e
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by preyanshu**
**Description**

This PR fixes #5566 + eslint version issue (no eslint.config.js found + use of .eslintignore deprecated)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8bbedfb221cf7ddb2a4235e0eab6945e062aa78d at: https://6665b15a28a7e0d20e46b5b2--layer5.netlify.app

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
Please revert changes in `package-lock.json` and `package.json` @preyanshu

**Comment by l5io** [comment]
🚀 Preview for commit 70d27c5a4c3e5c2c3fe807ec52d6c5caf249ed53 at: https://6666a73fd8028b88967a1eea--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thank you @preyanshu :rocket:

**Comment by vishalvivekm** [comment]
yay! :balloon: :tada:  @lekaf974

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
