### PR TITLE
resize overall megamenu and blog thumbnail

### LINKED ISSUE #1233: [NG] reduce the size of megamenu
**Current Behavior**

The current megamenu is slightly large
Screenshot from 2020-12-08 07-54-27

**Desired Situation**

Reduce the overall size of this menu

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### LINKED ISSUE #1234: [NG] image sizing in megamenu
**Current Behavior**

Currently image sizes in megamenu are not the same
Screenshot from 2020-12-08 08-21-40

**Desired Situation**

Use card component around these images and resize them 

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

This PR fixes #1233 and also fixes #1234 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by shivaylamba — COMMENTED** [review]
Looks Great @vineethvanga18 
Just a small fix required for Projects Mega Menu Card Thumnail : It shows the events, earlier it showed Meshery and Image Hub as featured items.
image

**Comment by vineethvanga18** [comment]
@shivaylamba that's because Iam receiving null images from graphql for projects, so I just used events query for projects too

**Comment by shivaylamba** [comment]
> @shivaylamba that's because Iam receiving null images from graphql for projects, so I just used events query for projects too

Is there a way to rectify the null error by changing the querying in the GraphQL to fetch the images?

**Comment by vineethvanga18** [comment]
@shivaylamba yeah did it committing changes now

**Comment by vineethvanga18** [comment]
@leecalcote ^^

**Comment by leecalcote** [comment]
A item to debug - https://youtu.be/wKs6-RilTPI

Outside of this item to debug, there are just a minor tweaks to convey to you over a screenshare.

Words can't describe how pumped I am about this work, @vineethvanga18. 😄

**Comment by leecalcote** [comment]
@vineethvanga18 did you rework the Mega Menu or is this PR still valid?

**Comment by vineethvanga18** [comment]
@leecalcote I didn't start rework as Iam currently working on remote component for user preferences.  I only made one change(no animation for text and separator line) in this PR. This can be merged for the time being. I will start the rework today.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Sounds good. Thanks, @vineethvanga18

**Comment by vineethvanga18** [comment]
@leecalcote I was about to push the changes for no animation 😅

**Comment by leecalcote** [comment]
Oh! Oops

**Pull request merged**
