### PR TITLE
[Subscribe] Enhance page with long-form subscription

### LINKED ISSUE #1603: [Mailing List] Create long-form version of subscribe component
**Current Behavior**
The current "[subscribe](https://github.com/layer5io/layer5/tree/master/src/sections/subscribe)" component has a single field for email. 

Screen Shot 2021-02-24 at 5 29 43 AM

**Desired Behavior**
The current, short-form serves as a simple Call to Action for the visitor and should remain as-is.

Ideally, a long-form version of this component that includes two additional fields (first name and last name) can be made available at https://layer5.io/subscribe so that the visitor's first and last name may also, optionally be captured.

---
**Contributor Resources**
The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #1603

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
If we push directly to layer5 repo, the build happens directly on the PR and the actual site reflects the changes 😄

**Comment by leecalcote** [comment]
@Nikhil-Ladha good call out here. To clarify, do you mean that if changes are pushed directly to `master` without a PR associated, that those changes will not be published? Hopefully, that's not the case with the trigger set to `push` - https://github.com/layer5io/layer5/blob/8b146d1b1928896ec15831eec6e61a397244ffe3/.github/workflows/gatsby.yml#L2

**Comment by Nikhil-Ladha** [comment]
No no...what I meant was if we create a PR from the layer repo directly, then the `build` action deploys the changes on the live site, even though the PR is not merged.
I don't think that is something we want, as there might be discrepancies in the PR which we might not want to be on live site before a review.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha good call out here. To clarify, do you mean that if changes are pushed directly to `master` without a PR associated, that those changes will not be published? Hopefully, that's not the case with the trigger set to `push` -
> 
> https://github.com/layer5io/layer5/blob/8b146d1b1928896ec15831eec6e61a397244ffe3/.github/workflows/gatsby.yml#L2

I am not sure, but if we change it to `on: commit` that I might fix things?

**Comment by Nikhil-Ladha** [comment]
Or change it to:
```on:
  push:
    branches:
      - master
```

**Comment by leecalcote** [comment]
Trying out 
```    
branches:
      - master
```

**Comment by leecalcote** [comment]
oh, no. I was referencing an old commit above. Here is the latest commit on `master` - https://github.com/layer5io/layer5/blob/master/.github/workflows/gatsby.yml

The history of the workflow seems to be indicating that builds are happening on push - https://github.com/layer5io/layer5/actions/workflows/gatsby.yml

**Pull request merged**
