### PR TITLE
Change multiple Active navlinks

### LINKED ISSUE #4570: Navbar hovering effect highlights two elements simultaneously
### Description
Currently on hovering or clicking over projects in navbar highlights both Solutions and Projects together(Particularly with green color).

### Expected Behavior
It should highlight only a single element at once.

### Screenshots
Problem:
navbarIssue1

Expected behaviour:

navbarIssue2

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Modern-artist**
**Description**
Now Navbar doesn't highlights two elements simultaneously(Solutions/Products).

This PR fixes #4570

Screenshot 2023-07-22 at 8 15 39 PM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Modern-artist Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would:)

**Comment by l5io** [comment]
🚀 Preview for commit 7ef8df8baaa954d2987f0dd8d12a8a26ed0e9399 at: https://64be5e27c8740d008bf9bbaa--layer5.netlify.app

**Review by Chadha93 — COMMENTED** [review]
@Modern-artist good, but we have one more Solution - "GitOps with Cloud
Native Insights". If we point them to MeshMap, high chance people will miss out on that page. 

More solutions:
1. Add a section to GitOps with MeshMap on the existing Meshmap page.
2. Create a solutions page.

**Review by leecalcote — APPROVED** [review]
Thank you, sir.

**Comment by leecalcote** [comment]
> @Modern-artist good, but we have one more Solution - "GitOps with Cloud Native Insights". If we point them to MeshMap, high chance people will miss out on that page.
> 
> More solutions:
> 
> 1. Add a section to GitOps with MeshMap on the existing Meshmap page.
> 2. Create a solutions page.

Both of these are great suggestions. Let's do them.

**Pull request merged**
