### PR TITLE
Rename and remove service mesh reference

### PR DESCRIPTION
**Pull request by iArchitSharma**
`<hostname>/cloud-native-management/meshery/operating-cloud-native-infra`

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
Remove the service mesh logo from the graphic / animation and use the logos of projects that are graduated. You will get the graduated projects list from  [cncf.io/projects](https://www.cncf.io/projects)
image

**Comment by l5io** [comment]
🚀 Preview for commit e68ec1db7a29f729bb8c478acbef2a9a0e55bc87 at: https://66226abbbfa707065419075c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9a5e970e227d8dd4fd2596fe513b0ed251b0797a at: https://6622799a0787aa1896d77cdd--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
@iArchitSharma, This page can go under products and Meshery is a product so the URL can be `<hostname>/products/cloud-native-management/meshery/managing-cloud-native-infrastructure`

**Comment by vishalvivekm** [comment]
@iArchitSharma 

Let's discuss this on websites call today. I've added this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#).
Meeting details: https://meet.layer5.io

**Comment by ritiksaxena124** [comment]
@iArchitSharma remove the conflicts so that we can merge your PR

**Pull request merged**
