### PR TITLE
[NG] General Updates on Layer5-NG

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR fixes the page headers and many more.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
I think this will have dome conflicts with my open PR😆

**Comment by Jashpatel1** [comment]
> I think this will have some conflicts with my open PR😆
> 
> What I would suggest is let the changes in my PR be merged and you can update yours accordingly, is tjat fine?
> Also, please use `rem` unit instead of `px` at all places. I have updated the same in mine, you can update the same in yours as well.

Sure, captain😂

**Comment by Jashpatel1** [comment]
Closing as issue already resolved.

**Comment by Nikhil-Ladha** [comment]
> Closing as issue already resolved.

Oopss.... don't know, if we shall be happy or upset😂

**Pull request closed without merging**
