### PR TITLE
Add color scheme and change image width w/signoff

### LINKED ISSUE #681: Update Brand page to use CSS color blocks, not images for color schemes
**Current Behavior**
Akin to what @manishkrjha accomplished in https://github.com/layer5io/layer5/pull/666 for the SMP project, convert all color scheme images (for each project) to colored blocks with color codes inside.

**Implementation**
1. Create color-filled, box-shaped divs with each color code number inside of them for each of the project color schemes.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by manishkrjha**
Signed-off-by: Manish Jha <codernibba@gmail.com>

**Description**
Replaced the colour scheme images with colour blocks and added few divs, changed image widths to make this page more responsive.

This PR fixes #681 and #688

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@manishkrjha, thank you! It would be nice if we could reclaim some of this whitespace - 

Screen Shot 2020-08-31 at 5 54 50 PM

**Comment by Nikhil-Ladha** [comment]
The mobile view looks good. But as Lee pointed out in desktop view the whitespace needs to be retducex a bit . You can try display as inline-block or flex to fullfill that.

Also, what is the purpose of this block/image here?
// @leecalcote , @manishkrjha 
Screenshot_20200901-105835__01
We are already showing this color block above, it can be removed I guess.

**Comment by manishkrjha** [comment]
@Nikhil-Ladha 
The block was present in the original file, I'll remove this if you guys approve

**Comment by leecalcote** [comment]
@manishkrjha thanks for asking. I'll leave this decision to @Nikhil-Ladha

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Okay then, let's do few changes here:
1. Generalize the way logos and colors are shown in all the sections l. In some sections the colors are there under web in some under use online. So, to make it proper do one thing, in each section under the `Colors` heading in the Web subheading heading show the color blocks and below it, instead of writing for use online make it `Logos to use online` and rest is same.
2. Remove the block which I pointed out as it is already displayed in the block above.
3. Reduce the white space pointed out by Lee

**Comment by manishkrjha** [comment]
You want it completely filled or shall I give some space??

Screenshot (254)

**Comment by Nikhil-Ladha** [comment]
You can give some space or what tou can do for this specific section as it has a grayscale too, is that make them display side by side on the same line. That will solve the issue.

**Comment by Nikhil-Ladha** [comment]
Looks better, just a few tweaks more:
1. For the Layer5 section, you have moved the grayscale to the same line of colors, good! But, the odd white space is still there, so add a subheading within web like 'Color', 'Grayscale', and separate these into two divs, then add some spacing between both the divs. And, later on in the mobile view move it below the color subheading.
2. All the color blocks should be of the same height.
3. In the SMP section, add the RGB color along with the # notation to maintain consistency with other blocks.

**Comment by Nikhil-Ladha** [comment]
Also, the color of the 3rd block in the Meshery section is wrong. The RGB is correct, but the block is not of that color. Please rectify that.

**Comment by manishkrjha** [comment]
I was trying to implement ***media*** rule but couldn't do it properly. Although I've added flex and some margin and this is how the colour looks now:

web:

Screenshot (259)

Mobile:

Screenshot (257)

Is this okay??

**Comment by Nikhil-Ladha** [comment]
Yeah, better :+1:

**Review by Nikhil-Ladha — APPROVED** [review]
Good work @manishkrjha . Now it's better :+1:

**Review by leecalcote — APPROVED** [review]
These color-coded boxes are a nice improvement. Thank you for this, @manishkrjha. 😄

**Pull request merged**
