### PR TITLE
added the reviews on the products page

### LINKED ISSUE #5612: Add the Testimonials in Product page
### Current Behavior
Currently we don't have any Testimonial on our product page - https://layer5.io/products
### Desired Behavior
Add the Testimonials in Product page, just like we have them here in bottom - https://layer5.io/cloud-native-management/generate-aws-architecture-diagram
image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by MUFFANUJ**
**Description**

This PR fixes #5612 

**Notes for Reviewers**
As per the instructions the same testimonial section is added now in products page and is working perfectly fine

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4976f26e4f121560f56d8b04c2ecb6b878f843cb at: https://6684f75c683e17a3d899365d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c708c9395aae16bbbc13f604a52d45d533bc66ee at: https://6684fca49cd465a840766c80--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 66de410f955c6d3923d39b78ab3c55f52af593b7 at: https://668505536c2962b332326921--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a6f270d0699dde0e051bd7e97ae4c522ec590b9c at: https://66853f18756ef1f951219f1e--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@leecalcote make sense to have reviews page in products page too? If yes then we can go ahead since it looks good to me

**Comment by MUFFANUJ** [comment]
> @MUFFANUJ please wait for issue to get assigned

Yeah got it

**Comment by vishalvivekm** [comment]
@MUFFANUJ 
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by Ashparshp** [comment]
@leecalcote Are we gonna have these?

**Comment by Ashparshp** [comment]
@leecalcote, sir what to do?

**Review by vishalvivekm — APPROVED** [review]

**Pull request merged**
