### PR TITLE
Added the widget for adventures of friends and five

### LINKED ISSUE #4618: [Site] Add a card/widget for Adventures of Five and Friends
### Current Behavior
Currently, the [blog](https://layer5.io/blog) page has only one card/widget which is discuss forum. 

### Desired Behavior
Add a card/widget adjacent to the discuss CTA for Adventures of Five and Friends which points to this [page](https://layer5.io/community/adventures-of-five-and-friends)

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by khushalsonawat**
**Description**

This PR fixes #4618 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e828c2252cc2e6ebfadb46ac1cc51ffb4b14a287 at: https://64df049fae276d0ec15c0bcf--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
hey @khushalsonawat u can edit the description that This PR fixes #issue_no.

**Review by abhijeetgauravm — COMMENTED** [review]
image
 Subscribe to newsletter part is touching footer , bottom margin would be good here.

**Comment by khushalsonawat** [comment]
> hey @khushalsonawat u can edit the description, This PR fixes #issue_no.

Hello @abhijeetgauravm ,
I have updated the description. Sorry for the inconvenience as I am new to the community

**Comment by Ghat0tkach** [comment]
hey @khushalsonawat 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Chadha93** [comment]
@khushalsonawat, @Rexford74, gave some great feedback on the last Website's meeting. You may want to incorporate.

**Comment by leecalcote** [comment]
@khushalsonawat did you incorporate the feedback given or was that not necessary?

**Comment by Mohith234** [comment]
Completed #4930

**Pull request closed without merging**
