### PR TITLE
Add sistent modal component

### LINKED ISSUE #5519: [Sistent] Implement Modal component page
### Current Behavior
There is no page for Modal in [Sistent](https://layer5.io/projects/sistent/components)

### Desired Behavior
Implement the modal page using this [Figma mockup](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=5209%3A13685&mode=design&t=qP2uRkuetMXltHDo-1)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Description**

This PR fixes #5519 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c9bd32f3924a6250c55938f01b6cee6b4030dc7a at: https://668ba40161200ef289114fe1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3ea33e0ee2f3953ecb9ee11195f609a9d56d7c73 at: https://668bcb973bde7d0acfeafc53--layer5.netlify.app

**Review by hargunkaur286 — COMMENTED** [review]
Screenshot 2024-07-10 at 1 16 06 PM
opening the modal component redirects to a blank page. Also, the "Modal" component the we import from the sistent package, by default has an overlay property cannot be overwritten and thus, we cannot display the modal inline, as it was given in the figma file:

Screenshot 2024-07-10 at 1 20 29 PM

I was trying to make the modal to be pixel perfect which is why i made a custom component for the "overview", "guidance" and the "code" pages, for the sake of displaying them on the screen. The modal imported from the sistent package has extra padding in the header and footer, and no space between the buttons, and making changes in it wouldn't make any sense. 
Screenshot 2024-07-10 at 1 28 23 PM

This is why I got confused, but if this is the approach that we'll be working with, then it looks good to me. Let me know if I can help in any part.

**Comment by l5io** [comment]
🚀 Preview for commit ae28f0aecb1a8dc7dcb4ebefa05275f73e932f67 at: https://668fcdb215bf4d0e4f8f7d20--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8a5dc4ed505f42c6bb85bf5f8408507e8711136c at: https://6691a68c2fc3db59838a057a--layer5.netlify.app

**Pull request merged**
