### PR TITLE
Added play icon on home page

### LINKED ISSUE #4012: low contrast of play button
### Screenshots / Mockups

Screenshot (100)

Screenshot (99)

@leecalcote  if this is an issue can i work on this?

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4012 

[video](https://user-images.githubusercontent.com/92908347/230499503-93b9296b-02c2-4646-afa5-fd902ae4654b.webm)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
hey, hey. This is pretty slick, @AkashS20 😄 

you might have to make this same update on play.meshery.io...

**Comment by AkashS20** [comment]
Happy to contribute :smile: . I am trying to setup `meshery.io` but  facing some isuues

**Comment by AkashS20** [comment]
@thisiskaransgit I have made the required changes

**Comment by l5io** [comment]
🚀 Preview for commit 5f1fb016897691f7d7e18955ad3e0c89ae6407b7 at: https://6453be41c3c82333e3e5f510--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
Good one @AkashS20 LGTM

**Pull request merged**
