### PR TITLE
Added CNCF logo to Home page carousel

### LINKED ISSUE #4017: Add CNCF logo to Home page carousel
### Desired Behavior
In the "ENGAGING AND COLLABORATING WITH" section, add the CNCF logo (SVG is already present as an asset in the site) to the carousel.

Screenshot 2023-03-28 at 10 29 06 AM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ayushgupta4002**
**Description**

This PR fixes #4017 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [.] Yes, I signed my commits.
 
Added CNCF logo to Home page carousel, solved issue #4017 

regards
image

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
can anyone help me with the checks?

**Comment by leecalcote** [comment]
@ayushgupta4002 you can ignore the lighthouse-ci check for now. // @ayushthe1 

@ayushgupta4002 will you try using the [horizontal version](https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/black/cncf-black.svg) instead?

**Review by leecalcote — APPROVED** [review]
Looks great. Nice work, @ayushgupta4002 👍

**Comment by Chadha93** [comment]
@ayushgupta4002 Will you again make a PR without making any update to dependencies? I'm reopening and assigning the issue to you.

**Pull request merged**
