### PR TITLE
[UI] Added shadow in header menu card to support dark mode

### LINKED ISSUE #3738: [UI] Header menu item container does not have background shadow on hover in Dark mode
### Description
On hover there should be a little white shadow in dark mode as there is grey shadow in light mode

https://user-images.githubusercontent.com/71271069/218280487-43fc2c3b-8ba8-45f3-b0a1-17955fdcd327.mov

### Expected Behavior
There should be white shadow on hover

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Description**

Added box shadow in header menu card to support dark mode
This PR fixes #3738 

https://user-images.githubusercontent.com/71271069/218298971-b340afd7-36cd-456c-ace9-cb7778c330fa.mov

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e093ffeec5d232920205878e67b08f3906d830d0 at: https://63e89c16c36db7513dc14897--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
While you are there, can you please the alignment of the blog title, "see more" link on the card of the nav menu to `center`

**Comment by Yashsharma1911** [comment]
sure I will do that

**Comment by Yashsharma1911** [comment]
Hey @Nikhil-Ladha I have made the changes have a look and let me know if the changes are correct
ee

**Comment by l5io** [comment]
🚀 Preview for commit 6cd8b571dd04fc3ac778e51e46a5a562377e79a0 at: https://63e8f087abe015059d6b6276--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
The request is to have it center aligned vertically, not horizontally

**Comment by Yashsharma1911** [comment]
is this correct changes @Nikhil-Ladha 
fdsa

**Comment by leecalcote** [comment]
@Yashsharma1911 while you're in there, will you please also have the colored version of the MeshMap logo show (not the white version) in dark mode?

**Comment by Yashsharma1911** [comment]
Sure @leecalcote I will fix that too

**Comment by l5io** [comment]
🚀 Preview for commit dc1a2c9d948909a4b495f3e64fe9f3e0c4146770 at: https://63e941c6a25c0f3b772a7370--layer5.netlify.app

**Comment by leecalcote** [comment]
@Yashsharma1911 while you're in there....



.... just kidding! 😉

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by Yashsharma1911** [comment]
🙂 😂 

> @Yashsharma1911 while you're in there....
> 
> .... just kidding! 😉

🙂😂

**Pull request merged**
