### PR TITLE
change routes to /products

### LINKED ISSUE #4690: Change route path from /projects to /products
## Description
Recently we switched from projects to products, and the routes (URL path) were not updated.

## Expected Behavior
Please update all the /projects to /products in the site, and ensure sure by testing and visiting all the products/projects.

## Important

 Please make sure your PR doesn't break  all of the existing links to the projects pages. You need to ensure that redirects are in place for site-external references and updates are made for all site-internal references. 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Shreya111111**
**Description**

This PR fixes #4690 

**Notes for Reviewers**
change the routes from projects to products.
If there are any further corrections kindly tell accordingly

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shreya111111** [comment]
@Ghat0tkach plz review the pr and if there are any corrections needed then tell accordingly

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@Shreya111111 The internal links will also require an update https://64db97c3cb9ad6764bbf8f94--layer5.netlify.app/projects. For each project path.

**Comment by Shreya111111** [comment]
@Chadha93 changing internal links is resulting into breakage

**Comment by vishalvivekm** [comment]
@Shreya111111 Let's discuss it on the websites call on Monday. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Shreya111111** [comment]
@vishalvivekm yes sure but it says require access in meeting minutes https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Ghat0tkach** [comment]
> @vishalvivekm yes sure but it says require access in meeting minutes https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima
> 

No worries, I've added your agenda . ☺️

**Comment by Chadha93** [comment]
> @Chadha93 changing internal links is resulting into breakage

@Shreya111111 Since a new products page is developed and we will be archiving this, this update isn't required. Until then feel free to take on new issues.

**Comment by Shreya111111** [comment]
@Chadha93 Even I was thinking about the same

**Comment by Chadha93** [comment]
> @Chadha93 Even I was thinking about the same

@Shreya111111 I'm closing this PR.

**Pull request closed without merging**
