### PR TITLE
Updated README in layer5-ng branch to match README in master branch

### PR DESCRIPTION
**Pull request by dmoini**
**Description**

Updated [README in layer5-ng](https://github.com/layer5io/layer5/blob/layer5-ng/README.md) branch to match [README in master branch](https://github.com/layer5io/layer5/blob/master/README.md). This PR addresses issue #525.

**Notes for Reviewers**

N/A

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @dmoini! This is great. It looks like files from the `master` branch have accidentally been included in this pull request. This PR should only contain changes to the readme.md file. You'll want to confirm that in your local fork, you first `git checkout layer5-ng`, then update the readme, push your changes to https://github.com/dmoini/layer5:layer5-ng and create the PR from `dmoini/layer5:layer5-ng` to `layer5io/layer5:layer5-ng`

**Comment by dmoini** [comment]
@leecalcote Are you referring to all the files added from `assets/images`? If so, some of the images in the README required images that are not found in the `layer5-ng` branch. I could delete all the unnecessary files in `assets/images` and push those changes if that sounds good?

**Comment by leecalcote** [comment]
@dmoini, yes, that sounds great. ~7 or 8 images 👍

**Comment by dmoini** [comment]
@leecalcote Just removed the unnecessary images. The only images left are the ones required by the README.

**Comment by leecalcote** [comment]
@dmoini thank you for taking this on. You’re most welcome to join the Layer5 community - http://slack.layer5.io. There is a large effort to overhaul this site that may be of interest to you (or another project). 👍

**Pull request merged**
