### PR TITLE
Remove comments section from blogs and more feature to blogs

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**
Add thumbnail, author, and tags to blogs
Remove comments section from blogs

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
Following changes are needed - 

- Images dimensions need to be changed for thumbnails
- I had to add inline style for in the [blog](https://deploy-preview-534--layer5ng.netlify.app/2020/2020-07-16-growing-as-an-open-source-contributor-with-layer5/). Need to think of better way to do this.

**Comment by Nikhil-Ladha** [comment]
> Next steps would be -
> 
> * Images dimensions need to be changed for thumbnails
> * I had to add inline style for one of the image in the [blog](https://deploy-preview-534--layer5ng.netlify.app/2020/2020-07-16-growing-as-an-open-source-contributor-with-layer5/). Need to think of better way to do this.

Hi @Tanuj22 , we can use the image plugin for Gatsby, it will take care of the size and responsiveness of the image. If we are not using it.

**Comment by Nikhil-Ladha** [comment]
> > Next steps would be -
> > 
> > * Images dimensions need to be changed for thumbnails
> > * I had to add inline style for one of the image in the [blog](https://deploy-preview-534--layer5ng.netlify.app/2020/2020-07-16-growing-as-an-open-source-contributor-with-layer5/). Need to think of better way to do this.
> 
> Hi @Tanuj22 , we can use the image plugin for Gatsby, it will take care of the size and responsiveness of the image. If we are not using it.

gatsby-image, gatsby-plugin-sharp, gatsby-transformer-sharp

**Comment by Tanuj22** [comment]
@Nikhil-Ladha I am doing that. But if I let the image plugin take control of the size completely this happens 
Screenshot from 2020-07-28 13-04-10. 

So what I am doing in the PR is keeping the max-width =500 and max-height=300, which gave better results.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I am doing that. But if I let the image plugin take control of the size completely this happens
> Screenshot from 2020-07-28 13-04-10.
> 
> So what I am doing in the PR is keeping the max-width =500 and max-height=300, which gave better results.

Ohh, I saw the code now. And , IMO the way in which you have set the values are completely fine and fits with the functionality of the plugin as far as I remember. That styling is not an issue.

But, one thing you may want to change is that in the blogs page on top-left side, below the blog name a `in` field is there. That can either be changed to `Tags` or as we have the `Tags` field present at the bottom that can be removed. What do you think?

**Comment by Nikhil-Ladha** [comment]
Also, in the preview of blog, the one in the image you shared the date and author should be below the blog name, don't you think that would be correct?

**Comment by Tanuj22** [comment]
> But, one thing you may want to change is that in the blogs page on top-left side, below the blog name a `in` field is there. That can either be changed to `Tags` or as we have the `Tags` field present at the bottom that can be removed. What do you think?

WIll remove the `In` field
 

> Also, in the preview of blog, the one in the image you shared the date and author should be below the blog name, don't you think that would be correct?

Yeah, that would be better

**Comment by Tanuj22** [comment]
@Nikhil-Ladha I have changed `In` to `Tags` for now as there were some checks in place in `PageHeader` which I thought we may need later. I will remove it if it is not needed later on.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I have changed `In` to `Tags` for now as there were some checks in place in `PageHeader` which I thought we may need later. I will remove it if it is not needed later on.

Cool👍🏼

**Comment by leecalcote** [comment]
I missed it... was the single page post template deleted entirely or replaced with a new one?

**Comment by Tanuj22** [comment]
> I missed it... was the single page post template deleted entirely or replaced with a new one?

It was moved to a `templates` folder and was rendered during build time by `gatsby-node.js`

**Comment by Tanuj22** [comment]
@Nikhil-Ladha @leecalcote Can you merge this PR so I can move forward with migrating rest of the blogs :sweat_smile:

**Pull request merged**
