### PR TITLE
navOverflow problem resolved

### LINKED ISSUE #4789: Overflow of Navbar
### Description
Overflowing of navbar.

### Expected Behavior
It should not overflow.

### Screenshots
Screenshot 2023-08-25 at 10 34 24 PM

### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Modern-artist**
**Description**
I have solved nave overflow problem solved.

This PR fixes #4789

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 876d0f704fb4cf0038753c4fea107627f2324def at: https://64e9bd9fedd7a71a9cf59846--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
Looks good!

**Review by Shivam-AfA — COMMENTED** [review]
LGTM 🚀

**Review by brijeshbhikadiya — COMMENTED** [review]
LGTM

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
