### PR TITLE
[Footer] - Added the hovering effect in privacy and terms

### LINKED ISSUE #1891: Links do not have a hovering effect
**Description**

The privacy and terms links beside the copyright section are not having the hovering effect.

**Expected Behavior**

The privacy and terms links should have a hovering effect.

**Screenshots**

Screenshot 2021-05-30 at 11 30 50 PM

**Enviroment:**
- Host OS: Any
- Meshery Version: Any
- Kubernetes Version: Any
- Browser: Any

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sayantan1413**
**Description**

Added the hovering effect in the privacy and terms.

This PR fixes #1891 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @sayantan1413. Will you use the appropriate theme variable to reference color here? 

e.g.

```
color: ${props => props.theme.secondaryColor};
```

**Comment by sayantan1413** [comment]
Sure @leecalcote am doing it.

**Comment by sayantan1413** [comment]
@leecalcote I changed it can you verify once

**Comment by leecalcote** [comment]
Is that the right color?

**Comment by sayantan1413** [comment]
Yes its giving the same effect as the other links.

**Review by leecalcote — APPROVED** [review]
Thanks, @sayantan1413

**Comment by sayantan1413** [comment]
Welcome. I got my first pull request merged . :)

**Comment by leecalcote** [comment]
Haha! 👏 Awesome 🎈

**Pull request merged**
