### PR TITLE
[Community] Member Profile: Updated Yash Pandey's profile photo

### LINKED ISSUE #1738: [Community] Member Profile: Yash Pandey's profile photo is wrapped in an unnecessary layer
**Screenshot**
Screen Shot 2021-04-01 at 10 53 25 PM

**Current Behavior**
@austinogiza, I believe @EmperorYP7's profile photo was exported from Figma as a member card inadvertently and used in his member profile. 

**Desired Situation**
[@EmperorYP7's member profile](https://layer5.io/community/members/yash-pandey) should simply have his photo, not a double-layering of outer edging. Yash's photo - https://drive.google.com/file/d/1jo43k3xaB0jZCmaBTGcczRkaZOZ6D_CG/view?usp=sharing

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by siddhantdixit**
Signed-off-by: SIDDHANT DIXIT siddhant.dixit23@gmail.com

**Description**

This PR fixes #1738

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f46619b0b78228e5bca9e9d83195ead04cff6119 at: https://60676c0ea2dd931a85b06d14--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
Fantastic. Thank you, @siddhantdixit

**Comment by siddhantdixit** [comment]
@leecalcote  You’re welcome!

**Comment by leecalcote** [comment]
@siddhantdixit if your not already a member of the Layer5 open source community, I welcome you to join - http://slack.layer5.io. Friendly folks inside.

**Pull request merged**
