### PR TITLE
Contact-Card-Fixed-Mobile-View

### LINKED ISSUE #4768: Fix the inconsistent Card Size in Contacts Page
### Description
[https://layer5.io/company/contact](https://layer5.io/company/contact)
Card sizes are inconsistent for mobile screens
### Expected Behavior
Card styles need to be updated to be consistent for all mobile screens

Ideally, we need to update the current variables and not introduce new ones

### Screenshots

</img>

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by jiyanpatil07**
**Description**
This PR fixes  #4768

**Notes for Reviewers**
Here is the screenshot for the reference.
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 267d8cf5f727823d7b61d05f9f558a14908cf1ca at: https://64ebae778de23f19eb29b339--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
In mobile view its looking good now! but in ipad view and in some other dimensions there is slight inconsistency.
image

image

image

image

image

**Comment by jiyanpatil07** [comment]
Okay @abhijeetgauravm.
Will look into it.
Thank You.

**Comment by l5io** [comment]
🚀 Preview for commit 2dbe71d1bf0b5c6f0e8f9f8e9f3f8216133c35a4 at: https://64ed03abb215b40e5fa0e301--layer5.netlify.app

**Comment by jiyanpatil07** [comment]
Any Update?

**Comment by VaibhavMalik4187** [comment]
@jiyanpatil07 Please squash the commits to a single commit. Also, modify the commit message and description to follow: https://cbea.ms/git-commit/

**Comment by jiyanpatil07** [comment]
@VaibhavMalik4187 Sure.
Will squash the commits ASAP.

**Comment by abhijeetgauravm** [comment]
// @jiyanpatil07

**Pull request closed without merging**
