### PR TITLE
🔴 [fixes] text crash in mobile view

### PR DESCRIPTION
**Pull request by anjali1102**
#1177 please review

### CODE REVIEW

**Comment by leecalcote** [comment]
@anjali1102 thanks for contributing here. Please don’t use multiple exclamation marks when asking for a review. Please don’t ask for a review from a specific person if that person isn’t focus on this area of our projects. Please remove the tagging of @blake so that he doesn’t get unnecessary and irrelevant email. Please sign-off on your commits.

**Comment by Nikhil-Ladha** [comment]
Also, where do you see this crash. Better to create one issue before submitting a PR and changing the font-size of the complete `html` tag suddenly. 
Please have a look at the Contributing guidelines before opening a PR.
Closing this one now 🙂

**Comment by leecalcote** [comment]
@Nikhil-Ladha here is the issue this PR is addressing - #1177. The PR Template may have been removed, making it harder to read.

@anjali1102 let me reiterate that we're very pleased that you have jumped in to assist. Thank you very much for doing so. Seeing the issue in #1177, it is something that needs to be fixed. Please don't let this first set of interactions discourage you. You're on the right path here. 

@Nikhil-Ladha seeing #1177, how would you like to @anjali1102 to proceed? Different approach to solving the issue in a new PR or similar approach to solving the issue and a reopening of this PR or other?

Thanks again, @anjali1102 👍

**Comment by Nikhil-Ladha** [comment]
Okay, missed the issue number I guess. My bad. 
So, coming to the issue. Never ever change the font size for the `html` tag itself, until and unless its something which effects the overall site. For, this issue @anjali1102 what you can do is, check if there is some class already assigned for the table in that page and edit the value ONLY for that table, if there is no such class add one and update the value accordingly.

Reopening the PR with hope that you would be updating the changes.

**Comment by leecalcote** [comment]
Hi @anjali1102, would you like to incorporate this feedback into the PR?

**Comment by anjali1102** [comment]
> Hi @anjali1102, would you like to incorporate this feedback into the PR?

Yes @leecalcote

**Comment by leecalcote** [comment]
@anjali1102 ok, sounds real good. Jump into the community Slack if we can offer any assistance.

**Comment by Nikhil-Ladha** [comment]
Hey, @anjali1102 any updates here?

**Comment by anjali1102** [comment]
> Hey, @anjali1102 any updates here?

@Nikhil-Ladha sorry for late response, I will make PR by today 👍

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha sorry for late response, I will make PR by today

Any updates or trouble @anjali1102 ?

**Comment by leecalcote** [comment]
Thanks for your efforts here, @anjali1102. Feel free to reopen this PR should you like to work on it in the future.

**Pull request closed without merging**
