### PR TITLE
Solutions pages restructure

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**

This PR is a part of #5359 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 63e68bde006fcecc3b2d781aa824d0585994b58b at: https://65be57a065175a9fcbd50b94--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@iArchitSharma 
Let's discuss this on website call at 6:30 PM IST / 7 AM Central time Today. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by leecalcote — CHANGES_REQUESTED** [review]
redirects? Avoid 404s...

**Comment by iArchitSharma** [comment]
@leecalcote done!

**Comment by l5io** [comment]
🚀 Preview for commit 2864b7bbb277c14319fc9b9048e3f06d6a7bdb3a at: https://65c225e143d60679e768bbb5--layer5.netlify.app

**Pull request merged**
