### PR TITLE
update: Twitter's logo has been changed to X #4631

### PR DESCRIPTION
**Pull request by parmishh**
updated to latest logo X #4631 

Here is the video demo:

https://github.com/layer5io/layer5/assets/91942072/9567287a-4bb7-44a1-9f74-721218e66a1c

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b174c702129e637195a73da346dd1001a3895b29 at: https://64c9516bba4c931fa7511936--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
@parmishh 
https://discuss.layer5.io/t/ways-in-which-to-participate-in-the-layer5-community/3290?u=ghat0tkach


The Twitter logo is same in mobile widths.

**Comment by parmishh** [comment]
@Ghat0tkach the logo also remains the same in desktop view if you are viewing the deployed preview because as you can see somehow the preview only generated for commit b174c70 in which I have made only css changes and not logo the preview didn't included commit eba860d.

Can you guide me what to do next.


> 🚀 Preview for commit [b174c70](https://github.com/layer5io/layer5/commit/b174c702129e637195a73da346dd1001a3895b29) at: https://64c9516bba4c931fa7511936--layer5.netlify.app

**Comment by parmishh** [comment]
because of which the deployed preview doesn't shows the logo. But in my local machine its visible on all screen widths:

https://github.com/layer5io/layer5/assets/91942072/d0e53313-0f52-44e2-ac9e-2fe704bb5a4e

**Comment by parmishh** [comment]
@leecalcote could you help with this

**Comment by Ghat0tkach** [comment]
@parmishh  , I believe you have manually added svg code using HTML inspect tool?
You have changed twitter icon of discuss.layer5.io , Well it was needed there as well.
However as I believe you should check the following files to fix the footer on Actual Website

https://github.com/layer5io/layer5/blob/fb0a68a9d6edd97bb7c02fbc76cff4851b0ec42a/src/assets/images/socialIcons/twitter-dark.svg
https://github.com/layer5io/layer5/blob/fb0a68a9d6edd97bb7c02fbc76cff4851b0ec42a/src/components/SocialLinks/index.js

**Comment by Ghat0tkach** [comment]
@parmishh 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Pull request closed without merging**
