### PR TITLE
Added Functionality  that will be triggered on issue/valid label

### LINKED ISSUE #4933: [CI] Label Commenter for new GH issue label: "issue/valid"
### Current Behavior
A new GitHub issue label `issue/valid` has been created for purposes of enhancing issue triage and conveying expectations regarding the procedure of issue assignment.

### Desired Situation
Issues labeled with `issue/valid` will ideally have automated comment added in which the  issue is identified as being verified valid and desirable that action be taken in accordance with the description offered in the issue.

Consideration should be given as to whether a similar comment should be made on issues labeled with `help wanted`. 

### Implementation
Enhance the existing [label-trigger.yaml workflow](https://github.com/layer5io/layer5/blob/be89af60eda10e59683abfcb6a936a46354ea5d8/.github/workflows/label-triggered.yml#L35-L40) to include support for `issue/valid` and potentially `help wanted`.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by dhamkirti21**
**Description**

This PR fixes #4933

**Notes for Reviewers**

Its my one of the first contribution to open-source please review it and give me a feedback.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0b48e16152d60ede64abbe7158fe9fd34e2706c2 at: https://650e56a9e4fd42674ae58796--layer5.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@dhamkirti21, just a friendly reminder: before you create a pull request, make sure the issue is assigned to you.

**Comment by dhamkirti21** [comment]
@hirentimbadiya okk thanks I will take care of that.

**Comment by saurabh100ni** [comment]
let's discuss this item on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Pull request closed without merging**
