### PR TITLE
aligned Project page

### LINKED ISSUE #4554: [UI] Alignment of Image and Heading.
### Description
Alignment of Image and Heading is pretty random and some of the width are not as expected.

### Expected Behavior
Alignment of Image and Heading  should be at centre with proper gap and width.

### Screenshots
Screenshot 2023-07-16 at 7 43 26 AM

### Environment:
- Host OS: macOS
- Browser: FireFox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Modern-artist**
**Description**
 Alignment of Image and Heading is pretty random and some of the width are not as expected.
This PR fixes #4554 

Screenshot 2023-07-21 at 6 49 45 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 22d56d87746953990be859bb9f78b7f8c3e924aa at: https://64ba894a03c27504444276a9--layer5.netlify.app

**Review by HarshDobariya79 — COMMENTED** [review]
Thank you for this PR. I've noticed some issues, 1) Service mesh performance icon is a bit inconsistent with other icons. 2) Meshery docker extension icon margin is not as expected. Please have a look.

image

**Comment by Modern-artist** [comment]
I have solve these issue and i had raise PR, I think which was merged.
Screenshot 2023-07-23 at 8 46 39 AM

**Comment by vishalvivekm** [comment]
@Modern-artist  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would:)

**Comment by l5io** [comment]
🚀 Preview for commit 0acee8a6e690aa51af9819068aaf4c18c9be5348 at: https://64be5f46bf2fd104c98dcaf2--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
