### PR TITLE
Added open-icon animation

### LINKED ISSUE #1739: Mobile menu icon animation
**Description**
Mobile menu icon has no closing animation

ezgif com-gif-maker

**Expected Behavior**
On closing the mobile menu, the icon should have some sort of animation

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by tileitner**
Signed-off-by: tileitner <timoleitner@gmx.at>

**Description**

This PR fixes #1739

**Notes for Reviewers**
Also added opacity to close-icon animation for a better look

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9de960548963a2a916c952aec7605cbae7d912cf at: https://60674218400774b495112f21--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9de960548963a2a916c952aec7605cbae7d912cf at: https://60674a9bcf6cd6b94c8eaee6--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Haha! Nice. 😀

**Review by leecalcote — APPROVED** [review]
Looks great. 👍

**Comment by leecalcote** [comment]
@tileitner if your not already a member of the Layer5 open source community, I welcome you to join - http://slack.layer5.io. Friendly folks inside.

**Comment by leecalcote** [comment]
We’re about to start designs on a new sub-site: learn.layer5.io that may well interest you.

**Pull request merged**
