### PR TITLE
set config for css conflict warning

### PR DESCRIPTION
**Pull request by ShivamCoder23**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c18625e0e4b7e2bbd13341a6eee11071d10045e7 at: https://67714114c3164cda40a04d3a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9b9d2c91c23d6008d94681d78eb0a3f70dc26e77 at: https://6771b4e24e307464b3e33fe3--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Vidit-Kushwaha tested again ?

**Review by Vidit-Kushwaha — APPROVED** [review]
@ShivamCoder23 Thank you so much for your help in resolving the CSS conflict issue. We really appreciate the time you took to assist. 🙌.

**Pull request merged**
