### PR TITLE
add nic-jackson profile to community

### LINKED ISSUE #1608: [Community] Member Profile: Nic Jackson
**Current Behaviour**

@nicholasjackson has been a consistent community member and supporter of Layer5 projects.

**Desired Situation**
Let's recognize @nicholasjackson as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: nicholasjackson
- Twitter: sheriffjackson
- LinkedIn: jacksonnic
- Link to profile picture: https://pbs.twimg.com/profile_images/839112434501713921/RsZIXY0l_400x400.jpg

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

### PR DESCRIPTION
**Pull request by Grumpyyash**
Signed-off-by: Yash Vardhan <yashvardhan513@gmail.com>

Added the profile of Nic Jackson to the community section

This PR fixes #1608 

nic-jackson

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@Grumpyyash  Can you change the target branch to master?

**Comment by Grumpyyash** [comment]
Are we directly working on the master branch now? Didn't know it, I will do it

**Comment by Tanuj22** [comment]
@Grumpyyash Can you make a PR from master brach as this is leading to conflict

**Comment by Grumpyyash** [comment]
Yes, I will

**Pull request closed without merging**
