### PR TITLE
updated Pratyay Banerjee profile

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**
Updated my profile info.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@Nikhil-Ladha :rocket:

**Comment by Nikhil-Ladha** [comment]
Just the 'State, Country' is fine for the location. Please update that.

**Comment by Neilblaze** [comment]
Lemme make the quick change.

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good now! 👍🏼

**Pull request merged**
