### PR TITLE
fix wrapping around color brand

### PR DESCRIPTION
**Pull request by ShivamCoder23**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8215086730db89180b1954d774e60ea0d68d07b4 at: https://675671e0d7d3f892b08bdd8b--layer5.netlify.app

**Review by ShivamCoder23 — COMMENTED** [review]
I am aware this kind of now repetitive style but i will fix this with more reusable.

**Comment by l5io** [comment]
🚀 Preview for commit 47b8d38198fe260d747a5dbcbd9a72b1ba5b7081 at: https://6756853ee75d2ec2e87b0911--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0787dd5253a0764b217c51c2869aeca3e34a8d69 at: https://675689ee613d00ad901a2ae2--layer5.netlify.app

**Pull request merged**
