### PR TITLE
[NG] Blockquote component

### LINKED ISSUE #1402: [NG] Custom React Component: Blockquote
**Current Behavior**
In blogs and other pages, the Layer5 site needs to the ability to show a stylized quote from a person. 

**Desired Behavior**
A new custom React component needs to show the person's quote, name, and title. Name and title can be optional properties.

**Implementation**
Turn this into a custom component called "Blockquote" - https://codepen.io/jupago/pen/GPxqLX

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #1402

**Notes for Reviewers**
This includes one style for how the blockquote might look. Multiple built-in styles would be useful as an add-on to this initial version.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by bartkalanski — APPROVED** [review]
Looks good @leecalcote ! Is there any way to preview the changes live ? Or is this only possible once the changes have been approved ?

**Comment by Nikhil-Ladha** [comment]
> Looks good @leecalcote ! Is there any way to preview the changes live ? Or is this only possible once the changes have been approved ?

Good ask @bartkalanski ....there is a netlify preview triggered for each PR but it was turned off recently due to few limitations, but from today onwards for each new PR you will get one preview build as well.

**Comment by bartkalanski** [comment]
@Nikhil-Ladha Ahh that clears things up, thank you! I wondered whether the netlify preview wasn't yet available for the new generation site.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by leecalcote** [comment]
and they were _just_ turned back on, too - https://github.com/layer5io/layer5/pull/1404#issuecomment-765899775

**Pull request merged**
