### PR TITLE
AWS Diagram page created

### PR DESCRIPTION
**Pull request by iArchitSharma**
ScreenShot

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
@iArchitSharma what is the URL to get to this page?

**Comment by iArchitSharma** [comment]
@ritiksaxena124 the build is still in progress

**Comment by l5io** [comment]
🚀 Preview for commit ec50b4f4bdb767eae11dfbffead78b63f4a6cc2f at: https://65786793f9d08e68c4ad8db4--layer5.netlify.app

**Comment by Lucif3r-in** [comment]
Hey @iArchitSharma few tweaks.
image
Screenshot 2023-12-12 194601
You can center-align the section titles and maybe left align the excerpt below that.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @iArchitSharma. Will you please reduce the amount of unused imports and CSS? The copy / pasta becomes both not tasty and unwieldy over time.

**Comment by l5io** [comment]
🚀 Preview for commit 2e11f4c69d4a2e8261b5f1b91632d06034354f8b at: https://657a2efa8e191d16ec550242--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@leecalcote Done

**Comment by l5io** [comment]
🚀 Preview for commit 6c2a0ecbfbea3293a9ff71f5440cfe2970cf68e2 at: https://657aa56aa8f4d864bd0a8e43--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
@iArchitSharma 
1. we can remove this section 
image

2. Reduce the line height of the title
image

**Comment by iArchitSharma** [comment]
@leecalcote @ritiksaxena124 Fixed the styling as requested and also added pushed GCP page

**Comment by iArchitSharma** [comment]
Should I add the AWS and GCP pages under Solutions

**Comment by l5io** [comment]
🚀 Preview for commit 8373a71823db86c1ffab75393f721e74b482ea14 at: https://657c207ba4a9c45aad2bfe0f--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@leecalcote sure ill add subtle parallax effect once we have the hero image
@ritiksaxena124 do we have hero image for the two pages?

**Comment by ritiksaxena124** [comment]
> @leecalcote sure ill add subtle parallax effect once we have the hero image @ritiksaxena124 do we have hero image for the two pages?

not yet @iArchitSharma

**Comment by l5io** [comment]
🚀 Preview for commit ae77c61881222ac0301d00999a5cf2d511eccca2 at: https://65845ce8727b00c71e888c2c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ecccde29a02dbee83756c7b56da35b9ee7a6c0d3 at: https://65848a3fb2a7d7303c4e8b69--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 822ee6c3dd1336a9793b9b3c560d4671960ed4b8 at: https://6584b6dab2a7d74f204e8b29--layer5.netlify.app

**Review by ritiksaxena124 — APPROVED** [review]
There are changes required @iArchitSharma, for now, I am merging this PR so that we have this page live.
Some fixes that are needed are :-
1. Animation on hero image
2. Mobile view fixes 
3. Increase hero image size etc...

**Pull request merged**
