### PR TITLE
d-cryptic/sidebar

### PR DESCRIPTION
**Pull request by d-cryptic**
I was solving issue #2077 
First removed the `margin-inline-end`
And then renamed Header to "Table of Content"

### CODE REVIEW

**Comment by sayantan1413** [comment]
Hey @d-cryptic good work 💪. But could you please solve the DCO from here https://github.com/layer5io/layer5/pull/2083/checks?check_run_id=3319769960.

**Review by sayantan1413 — CHANGES_REQUESTED** [review]
hey @d-cryptic I guess we do not need this `package-lock.json` file. So can you please revert this particular file.

**Comment by d-cryptic** [comment]
Hey @sayantan1413 can you guide me how to solve this DCO error, I tried but still it is unresolved.

**Comment by sayantan1413** [comment]
Hey @d-cryptic lets connect on slack.

**Comment by d-cryptic** [comment]
ok

**Comment by warunicorn19** [comment]
@d-cryptic I saw that you made another PR for the same issue, should we close this PR?

**Comment by d-cryptic** [comment]
Yes please close this PR

**Pull request closed without merging**
