### PR TITLE
fix: Slider unresponsiveness for smaller width 

### LINKED ISSUE #5670: Related resources container are not responsive content are overflowing
### Description

In ``What is Kubernetes`` page (Dont know about other one) containers in ``related resources`` are not responsive content are overflowing from their original state 
here is the video

https://github.com/layer5io/layer5/assets/116784047/09858442-a4e0-45ed-bad3-802f85bafa08

 

### Expected Behavior

Content shouldnt overflow from their original state . 
Also their is extra width for smaller width as you can see in the starting of the video that should also be fixes

### Environment:
- Host OS: Linux mint(UBUNTU)
- Browser:MOZILLA

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by upsaurav12**
**Description**

This PR fixes #5670

**Notes for Reviewers**

In this PR i have changed some properties like ``no of slides`` in each breakpoints by using ``use state`` because it was taking long time to render correct styling .  so by using this method we can see the changes at the same time we are changing the width 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8a30198e18e2db3ae1c15a92a6af6031be425866 at: https://669c214459d015307760b2c3--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks, @upsaurav12! 🎈

**Comment by Muhammed-Moinuddin** [comment]
@upsaurav12 Kindly elaborate the issue in detail and properly. Your point is not clear in the commit or in PR. There are couple of issues that I can see in your commit attached video. What is the issue that you are targeting?

In Live Preview:  Slider is unresponsive, we got horizontal scrolling/extra left-side space issue, Meshmap CTA is unresponsive.

We have meeting on Monday regarding Website discussion, I'll suggest you to join that as well. https://layer5.io/community/calendar

**Comment by upsaurav12** [comment]
can you tell me at which media query the slider is unresponsive like when i see in ``preview`` i could not see the unresponsive at mobile view . also what is `Mesh-map CTA `` container
the problem in issue that i opened was :- the slider was unresponsive(i have attached the video) so when i saw this in ``local setup to contribute`` i noticed that the number of slides at specific breakpoint so i modified the number of slider at ``708px`` , ``991px``, ``1400px``

**Comment by Ashparshp** [comment]
@upsaurav12 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin can you tell me at which media query the slider is unresponsive like when i see in `preview` i could not see the unresponsive at mobile view . also what is `Mesh-map CTA `container the problem in issue that i opened was :- the slider was unresponsive(i have attached the video) so when i saw this in`local setup to contribute`` i noticed that the number of slides at specific breakpoint so i modified the number of slider at ``708px`` , ``991px``, ``1400px``

Issue description that you've attached with PR created confusion. Yup, I got your point. 
Let's discuss this further via meeting.

**Comment by upsaurav12** [comment]
Hi @Muhammed-Moinuddin any update?

**Comment by l5io** [comment]
🚀 Preview for commit 2862fa72046e70bd1306397d43127be4693e2530 at: https://66a66d1e9788dc4edb19639d--layer5.netlify.app

**Comment by Muhammed-Moinuddin** [comment]
On my end, via live preview. The changes of slides is still taking time. I've to load everytime to check the responsiveness effect.
What is the main issue? Responsiveness of Sliders? or there rendering time? 

I'm unable to understand your changes properly. The issue that you have attached with this PR talks about some **related resource container not responsive**, you have not talked about any slider?

**Comment by upsaurav12** [comment]
oh i see whats the confusion the problem was that(from my end) that if you to the website and see the slider and change the width size it will.be unresponsive(elements are going outside) but if you see.this in local host then it will take some time to change from the unresponsive to responsive so i have change that

**Comment by upsaurav12** [comment]
Hi @Muhammed-Moinuddin, are still facing the same problem?? from my end everything seems to be fine

**Comment by l5io** [comment]
🚀 Preview for commit 4a1600c1583ed772b2d6d1e16c20af3ca4ba1e95 at: https://66acc9e49e097e39dded7e2a--layer5.netlify.app

**Comment by Muhammed-Moinuddin** [comment]
> Hi @Muhammed-Moinuddin, are still facing the same problem?? from my end everything seems to be fine

@upsaurav12 Your PR is just a logic enhancement and this issue is not considered valid as well please check: https://github.com/layer5io/layer5/pull/5724#issuecomment-2254626924

There might be some other aspects causing it, but your PR is not about those.
Thanks for the efforts.

**Comment by upsaurav12** [comment]
@upsaurav12 ok np. 
Should i close the issue??

**Comment by upsaurav12** [comment]
Do i need to close the issue?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Do i need to close the issue? Btw Thank you for your efforts ❤️

Yup you can close them.

**Pull request closed without merging**
