### PR TITLE
Fixing the full text for "sign into" call to action not visible in light mode

### LINKED ISSUE #4919: [UX] Learn - full text for "sign into" call to action not visible in light mode
### Current Behavior

- Link to website: https://layer5.io/learn/service-mesh-labs
- [Light mode] Currently when each learning path is opened by clicking on "Open Scenario", it reveals the text "Meshery Playground" as text in green color, which does not give much context to the user as to what options/steps they have to navigate the platform further. This only becomes clear if a user hovers over the already opened path revealing the full action option which states "Sign in to the Meshery Playground (free account) to continue your lab."

#### Screenshots
lmode

### Desired Behavior

Users should be able to see the option to navigate the platform further (before and after hovering over the path), this enhances user experience as not every user might have the notion to "hover" over an item to reveal the most important call to action/option which is signing up for a free Meshery Playground account to **continue their lab**.

### Screenshots

dmode

### Implementation

- [Light mode] Consider changing the text color for "Sign in to the Meshery Playground (free account) to continue your lab." to one that is different from its background, so its visible, before hover.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VamshiReddy02**
**Description**

This PR fixes #4919

**Notes for Reviewers**
I fixed the full text for the "sign into" call to action not visible in light mode. Please let me know if there are any changes to be made.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e52bf9720f48d2e036b3816db328ce8946e54a6f at: https://65058bcba20b4e08bf8ee747--layer5.netlify.app

**Review by Mohith234 — APPROVED** [review]
LGTM, Thanks for your contribution @VamshiReddy02 🚀

**Comment by VamshiReddy02** [comment]
Hey @Chadha93, and @abhijeetgauravm, can you review this PR,  and let me know of any changes?

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@VamshiReddy02, fix the hover issue for this one as well that you just fixed in issue #4941

**Comment by l5io** [comment]
🚀 Preview for commit 9fe9221edcd83de66541faea917f97d5d90b852b at: https://650ddd6de678fa1e57a8b77c--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
> @VamshiReddy02, fix the hover issue for this one as well that you just fixed in issue #4941, because hovering in light mode gives black color, it should be changed to white.

hey @hirentimbadiya but in layer5 site hovering in light mode to the links gives black color , and hovering in dark mode to the links gives white color.

**Review by Chadha93 — APPROVED** [review]
Thank you gents

**Pull request merged**
