### PR TITLE
[NG] Logo updates for Testimonies

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@kushthedude I included _site in .gitignore. Is that causing Netlify deployment failure?

**Comment by kushthedude** [comment]
> @kushthedude I included _site in .gitignore. Is that causing Netlify deployment failure?

No since your target branch for master initially so layer5-ng netlify never kicked off hence the failures

**Comment by Jashpatel1** [comment]
> > @kushthedude I included _site in .gitignore. Is that causing Netlify deployment failure?
> 
> No since your target branch for master initially so layer5-ng netlify never kicked off hence the failures

@kushthedude As you have changed the target from master to layer5-ng and it has changes, shouldn't there be a layer5-ng deploy by netlify. P.S. -  I dont have much knowledge about these actions.

**Comment by kushthedude** [comment]
> > > @kushthedude I included _site in .gitignore. Is that causing Netlify deployment failure?
> > 
> > 
> > No since your target branch for master initially so layer5-ng netlify never kicked off hence the failures
> 
> @kushthedude As you have changed the target from master to layer5-ng and it has changes, shouldn't there be a layer5-ng deploy by netlify. P.S. - I dont have much knowledge about these actions.

The webhook only trigger on the creation of PR against the specific branch, here the target was changed from master to layer5-ng so the deploy didn't trigger.

**Pull request merged**
