### PR TITLE
Added Summer Intern Blog

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eb5a71cc8acc6ea5c7773ce2afddf0d21ea35dab at: https://60ba6b39d8fdef7ec29ab364--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ad56d7b258bca9a7ac07c09649bbe3731efac548 at: https://60ba806651588413d61022be--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b433fade430fc268bcee983a296edb7ae792f6ef at: https://60babce5c5967871ba7fcd63--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9c31bd8545ddbb6f2f92f8a3b38dc6d3245572ec at: https://60bdf6162e76d4034ae2a4ed--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7e15881a96d418039f2a08bbc81fa84ee1a1ff6f at: https://60bdfad82e76d4fdbee2a8af--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@piyushsingariya's name has an accidental misspelling in the main post image.

**Pull request merged**
