### PR TITLE
Added spec Versioning and Mesh Images

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
Screenshot from 2021-01-02 18-45-09
 One of the icon is getting cropped I guess.

**Comment by leecalcote** [comment]
> Screenshot from 2021-01-02 18-45-09
> One of the icon is getting cropped I guess.

Good catch, @Jashpatel1. This half icon is actually intentional. Maybe we need a different color icon. This means that the service mesh is only half passing it’s tests.

**Comment by dhruv0000** [comment]
smi-marker-half
Fiddling around with other possibilities 🤔

**Comment by leecalcote** [comment]
Great job, @dhruv0000. The table is something to be proud of.... onto dynamic data!

**Pull request merged**
