### PR TITLE
Fixed broken image issue in meshery.html

### PR DESCRIPTION
**Pull request by bartkalanski**
Signed-off-by: Bart 61667381+bartkalanski@users.noreply.github.com

**Description**

This PR fixes broken image issue in meshery.html

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @bartkalanski. 👍

**Review by leecalcote — APPROVED** [review]
Looks great. Thank you. @bartkalanski 😄

**Comment by leecalcote** [comment]
Whoo-hoo, @bartkalanski 🎈

**Comment by bartkalanski** [comment]
> Looks great. Thank you. @bartkalanski 😄

Happy to be involved, if you have any more similar issues feel free to give me a shout!

**Comment by leecalcote** [comment]
Oh, very good! Two items that you might consider:

1. Jump into the Layer5 community - http://slack.layer5.io. It's a welcoming place.
1. This issue may be of interest - https://github.com/layer5io/meshery/issues/1604

**Pull request merged**
