### PR TITLE
Added deepak gutpa's profile and community badge to debopriya profile

### LINKED ISSUE #2400: [Community] Member Profile: Deepak Gupta
**Current Behavior**

@Mr-DG-Wick  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Mr-DG-Wick as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Mr-DG-Wick 
- Twitter: Mr_dg_wick
- LinkedIn: https://www.linkedin.com/in/mrdgwick/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
Signed-off-by: Prakhar Agarwal <prakhar@everything.net.in>

**Description**

This PR fixes #2400, #2397

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 74f4fd945b48dc7c2cd9055231557f81d7603c9f at: https://61af14bbf3867f7e203f953f--layer5ng.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @Prakhar-Agarwal-byte

**Review by Mr-DG-Wick — APPROVED** [review]
LGTM! 🥳 Thank you @Prakhar-Agarwal-byte 😄

**Review by leecalcote — APPROVED** [review]
Excellent!

**Comment by leecalcote** [comment]
Whoo-hoo!

**Pull request merged**
