### PR TITLE
[Blog] What are Kubernetes Validating Admission Controllers?

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR adds a timely description of a new Kubernetes 1.26 feature.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ed7f0b5f1ed3dc7dd67d815b4c221eecc784324d at: https://63a48bc91ff61f5362960eb9--layer5.netlify.app

**Review by deepeshaburse — APPROVED** [review]

**Review by Shivam-AfA — APPROVED** [review]
I think this PR can be merged after updating the branch. @leecalcote

**Comment by leecalcote** [comment]
Thank you. Updating...

**Comment by l5io** [comment]
🚀 Preview for commit 9adf84478f11c304fb6038331dd127db58d1508d at: https://63c1bdfdb3ab2c12df0764ee--layer5.netlify.app

**Comment by deepeshaburse** [comment]
@leecalcote do we need to add anything to this blog or can we merge this PR?

**Pull request closed without merging**
