### PR TITLE
[Screenshots] CRI-O under 'How it Works See It in Action' section

### LINKED ISSUE #4881: [Screenshots] CRI-O under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/cri-o) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [CRI-O](https://layer5.io/cloud-native-management/meshery/integrations/cri-o) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by coder12git**
**Description**

This PR fixes #4881

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 28404f222231dec9920c50410555683c9998c2c5 at: https://6519caa911d6340301a79a75--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Let's discuss this Item in today's website call,
Please add it as your agenda if you would:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by coder12git** [comment]
> Let's discuss this Item in today's website call, Please add it as your agenda if you would: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

@abhijeetgauravm but the issue was resolved, I don't think now I have any issue

**Review by sandramsc — CHANGES_REQUESTED** [review]
Hi @coder12git , thank you for your contribution, the visualizer screenshot is missing icons on the canvas, please upload a new one. See the comment/screenshot on this [PR](https://github.com/layer5io/layer5/pull/4914#issuecomment-1734386234) for more visual context and entire [PR](https://github.com/layer5io/layer5/pull/4914) for overall context.

**Comment by coder12git** [comment]
> Hi @coder12git , thank you for your contribution, the visualizer screenshot is missing icons on the canvas, please upload a new one. See the comment/screenshot on this [PR](https://github.com/layer5io/layer5/pull/4914#issuecomment-1734386234) for more context.

@sandramsc it's done!

**Comment by l5io** [comment]
🚀 Preview for commit cec976cdb1569611f1712400096832e75aa15e50 at: https://65282c1edbaa8e4e86cd27dc--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@coder12git merge conflict

**Comment by l5io** [comment]
🚀 Preview for commit 63eb5ed330860ef9464d14f3f349fd0cb10ab8a0 at: https://65b3c4645a91911d1574d002--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dff2720b35a68140343273435e126942cac9e4cf at: https://65b3c7bbfdec1d19ddcf0599--layer5.netlify.app

**Pull request merged**
