### PR TITLE
[CONTRIBUTING] Remove duplicate smp link

### LINKED ISSUE #1815: [CONTRIBUTING] Missing GetNighthawk badge
**Description**
Contributors receive badges on their member profiles when they engage in specific projects. The list of batches can be seen in the [contributing.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) . This list is missing an entry for GetNighthawk and has a duplicate entry for SMP

**Expected Behavior**
- no duplications
- the getnighthawk badge

GetNighthawk logo can be found on https://layer5.io/brand

**Screenshots**

image

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by josephmidura**
Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR fixes #1815

**Notes for Reviewers**
I removed the duplicate smp link and added the GetNighthawk link. I noticed multiple capitalizations of "Nighthawk" in the repo

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Excellent. 😄 

Thank you, @josephmidura 👍

**Comment by leecalcote** [comment]
Hi @josephmidura, there’s lots more where this comes from. There’s a warm and welcoming community of open Sourcer here - https://layer5.io/community. You’re most welcome to join. It’d be nice to have another Austinite join. 🙂

**Comment by josephmidura** [comment]
Thanks for the invite. I actually joined the slack channel this afternoon. I'm looking forward to learning how I can get involved.

**Comment by Ruth-ikegah** [comment]
Nice @josephmidura You are welcome, you know we have a Newcomers call on Thursdays at 8 am CT. Also, feel free to slack me @Ruth Ikegah.

**Pull request merged**
