### PR TITLE
deployement previews in ci

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <agarwal.5@iitj.ac.in>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by Tanuj22** [comment]
@leecalcote I think there is something wrong with `NETLIFY_AUTH_TOKEN` set up

**Comment by Nikhil-Ladha** [comment]
Shall we close this one, considering the PR #1468 ?

**Comment by Tanuj22** [comment]
> Shall we close this one, considering the PR #1468 ?

Yes. Still there is a issue though. Check this https://layer5io.slack.com/archives/C011VPREG2Z/p1612352663028300?thread_ts=1612325427.023100&cid=C011VPREG2Z

**Comment by Nikhil-Ladha** [comment]
Hmm....interesting 🤔

**Comment by Tanuj22** [comment]
Closing with #1468

**Pull request closed without merging**
