### PR TITLE
New component for MeshMap modes

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**
( Github is not letting me upload the screen recording :/ )
Screenshot 2022-05-13 at 4 58 57 PM

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1565c118c6a458ddb2f7250748f98976fe7b0db3 at: https://627e45351b2c5d603e0ec3c7--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Looks good.
Two things though:
1. The animation time can be reduced a bit.
2. In mobile view, the `dots` for the carausel are coming above the images. That should be below them.

Once, the above is done. We are good to merge.

**Comment by Nikhil-Ladha** [comment]
> **Description** ( Github is not letting me upload the screen recording :/ 

Good that we have deploy previews :p

**Comment by leecalcote** [comment]
Piling on the feedback: the gradient coloring seems to be missing in the mobile view.

**Comment by debo19** [comment]
@Nikhil-Ladha the `dots` in the carousal are above the images on the `/meshery` page as well. That should be changed too, right?

Screenshot 2022-05-15 at 7 11 51 PM

**Comment by debo19** [comment]
> Piling on the feedback: the gradient coloring seems to be missing in the mobile view.

@leecalcote the component was becoming too thin in mobile view and the hover effect will not work there. That's why I changed it to a normal carousal.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha the `dots` in the carousal are above the images on the `/meshery` page as well. That should be changed too, right?
> 
> Screenshot 2022-05-15 at 7 11 51 PM

Ohh, never noticed it.
Yes, those should be changed too.

**Comment by l5io** [comment]
🚀 Preview for commit 45d7012968c87bda1b4e3d9ed921c80cced163b7 at: https://62814a8921663a6b6cadb248--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Getting better. Now, if there's some way to either give the user an indicator or arrow to control the carousel other than the circles (which are easily overlooked and a little difficult to navigate) we can add something. It might be that the background of the section should be off-colored so as to further indicate that this section is special and swipe-able.

**Comment by leecalcote** [comment]
This new meshmap-modes component is really slick. 🥇

**Comment by leecalcote** [comment]
This is too cool not to merge. Man, this is slick!

**Pull request merged**
