### PR TITLE
Override the useSortBy Method To Fix Sorting Issue [Issue - 2644]

### LINKED ISSUE #2644: [Books] Data is not filtered correctly in the table on the service-mesh-patterns book page.
**Description**

The table in the [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns) is not sorting the data correctly.

**Expected Behavior**

It should not consider the section headers while sorting the data, rather sort the data as per the requested sorting technique under individual sections.

**Screenshots**

[Reference screen recording](https://youtu.be/G3Ks4ddQy1o)

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: sahilsuman933 <sahilsuman933@gmail.com>

**Description**
I added custom sorting method which sorts all the sub-sections length wise. 

Before:

https://user-images.githubusercontent.com/34382211/174189342-0db4ae1a-bcdf-49f8-aa7b-83e9d8887040.mp4

After:

https://user-images.githubusercontent.com/34382211/174189332-fbb410f5-1801-495d-9306-a58c9745a6fb.mp4

This PR fixes #2644

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 15b1610537d693310a634a9c38dda4f1c9d75b83 at: https://62abb2effde57246f7fd9e53--layer5.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
It shouldn't be sorted based on length. The requirement is to have it sorted alphabetically. Check the `useSortyBy` function in `react-table` that might help.

**Comment by sahilsuman933** [comment]
@Nikhil-Ladha I read about the useSortBy function in react-table and the only solution that I was able to come up was to override the predefined function. 

There was one more solution but it would  have required to build that table from ground up. That's why I prefered custom sort method. it was clean and simple.

**Comment by l5io** [comment]
🚀 Preview for commit 8ef6ab820ca809421a4a59d3ceba09d9fa3b3952 at: https://62ac18d69b668e0c3e76dfe6--layer5.netlify.app

**Comment by YashKamboj** [comment]
@sahilsuman933 Please add a appropriate title for the pr

**Comment by sahilsuman933** [comment]
> @sahilsuman933 Please add a appropriate title for the pr

Done.

**Comment by l5io** [comment]
🚀 Preview for commit 8dbbfb20326b63436f42a6ed07cce85ecb49844b at: https://62acf4dd81919333b1b30140--layer5.netlify.app

**Comment by sahilsuman933** [comment]
@Nikhil-Ladha and @YashKamboj Could you please review this PR?

**Comment by leecalcote** [comment]
Heads-up: @Nikhil-Ladha is taking a couple vacations and will be in and out over the next few weeks.

**Comment by sahilsuman933** [comment]
> Heads-up: @Nikhil-Ladha is taking a couple vacations and will be in and out over the next few weeks.

Okay. Meanwhile I will fix some other issues. Any issue suggestion lee which is moderate level and which is related to JS?

**Comment by leecalcote** [comment]
@sahilsuman933 good of you to ask. Yes, I can describe one to you on this Monday’s Websites meeting, which is today (meeting details at https://meet.layer5.io)

**Comment by sahilsuman933** [comment]
> @sahilsuman933 good of you to ask. Yes, I can describe one to you on this Monday’s Websites meeting, which is today (meeting details at https://meet.layer5.io)

Okay. Thanks

**Pull request merged**
