### PR TITLE
Updated Twitter Logo with X logo

### LINKED ISSUE #4631: Twitter's logo has been changed to X
### Current Behavior
Twitter's logo has been changed to X .I was thinking if we need to update the logo on the layer5 website.
What are the views on this/Any comments?
@leecalcote 
I made some changes it will look somewhat as in the video.
It can be assigned to me if it needs to be changed.

### Screenshots / Mockups

https://github.com/layer5io/layer5/assets/91942072/fc24b4eb-2018-43b7-9f78-b30fe88340f1

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Navansh**
**Description**

This PR fixes #4631 

**Notes for Reviewers**
Updated the Twiiter Logo, to the new X logo 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by abhijeetgauravm — COMMENTED** [review]
hey @Navansh signing-off your commits, will pass the DCO check.

**Comment by l5io** [comment]
🚀 Preview for commit e11977dae988a5a8561fbb862102492c2102ac0c at: https://64df2f372476a3009579ccee--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e11977dae988a5a8561fbb862102492c2102ac0c at: https://64df301d116a9b0098395a2f--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
> 🚀 Preview for commit [e11977d](https://github.com/layer5io/layer5/commit/e11977dae988a5a8561fbb862102492c2102ac0c) at: https://64df301d116a9b0098395a2f--layer5.netlify.app

Looks good @Navansh

**Review by Mohith234 — APPROVED** [review]
LGTM @Navansh 🚀

- Do sign off your commits that will pass the DCO check

**Comment by Navansh** [comment]
> LGTM @Navansh 🚀
> 
> * Do sign off your commits that will pass the DCO check

How do signoff this ?

**Comment by abhijeetgauravm** [comment]
> > LGTM @Navansh 🚀
> > 
> > * Do sign off your commits that will pass the DCO check
> 
> How to signoff this ?

hey @Navansh After doing changes in your forked repo , run these commands in terminal

git config --global user.name "Your Name"
git config --global user.email "your.email@example.com"

git add .

git commit -s -m "your msg"
   // this will sign-off your commit
git push

**Comment by Navansh** [comment]
> > > LGTM @Navansh 🚀
> > > 
> > > * Do sign off your commits that will pass the DCO check
> > 
> > 
> > How to signoff this ?
> 
> hey @Navansh After doing changes in your forked repo , run these commands in terminal
> 
> git config --global user.name "Your Name" git config --global user.email "[your.email@example.com](mailto:your.email@example.com)" git add . git commit -s -m "your msg" // this will sign-off your commit git push

So, do I need to push again and create a new PR ?

**Comment by Mohith234** [comment]
@Navansh Just informing that please do not create any additional PR's. You can push the commits to the same branch and it will reflect here directly

**Comment by Navansh** [comment]
> @Navansh Just informing that please do not create any additional PR's. You can push the commits to the same branch and it will reflect here directly
> 
> Now as you've created another you can close this one. Please refrain from creating extra PRs from next time

Sure, I will keep that in mind from next time

**Pull request closed without merging**
