### PR TITLE
replace-above-with-below-in-DCO-check-above

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

- It should be "To amend the commits in this PR with your signoff using the instructions provided in the `DCO check below`."
not `DCO check above`
Screenshot 2023-07-07 030513

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2cb01c99a59f5c8a9cbbdcd2f341ca71e0bc0c0a at: https://64a7395872e3300809ad13f4--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by leecalcote** [comment]
Not quite. Think more about this and you'll realize either above or below is possible.

If we're going to bother with us, I suggest changing the verbiage to remove that either of those prepositions. And then, propagating this change across the other repos.

**Comment by Nikhil-Ladha** [comment]
> Not quite. Think more about this and you'll realize either above or below is possible.
> 
> If we're going to bother with us, I suggest changing the verbiage to remove that either of those prepositions. And then, propagating this change across the other repos.

In case, of an issue it can be `above` but for a PR it has to be `below`.
Anyway, removing the verbiage makes more sense as we are anyway providing a link to set the DCO just below the statement.
@vishalvivekm please make the suggested update (across all the repos, if you would or open issues for the same)

**Comment by vishalvivekm** [comment]
> > Not quite. Think more about this and you'll realize either above or below is possible.
> > If we're going to bother with us, I suggest changing the verbiage to remove that either of those prepositions. And then, propagating this change across the other repos.
> 
> In case, of an issue it can be `above` but for a PR it has to be `below`. Anyway, removing the verbiage makes more sense as we are anyway providing a link to set the DCO just below the statement. @vishalvivekm please make the suggested update (across all the repos, if you would or open issues for the same)

Thanks @Nikhil-Ladha @leecalcote , I'll remove the prepositions ( above/below) in all the repos.

**Pull request merged**
