### PR TITLE
Added Hussaina Begum in the community list

### LINKED ISSUE #1054: Recognizing Hussaina Begum as a Contributor and Community Member
**Current Behavior**
@hexxdump has been a consistent contributor and community member.

**Desired Behavior**
A profile for @hexxdump should be created and visible on `/community/members` on both the **current** and **next-gen** layer5.io sites.

- Github: https://github.com/hexxdump
- Twitter: https://twitter.com/hexxdump
- Profile picture: need a picture from @hexxdump 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by naman360**
Signed-off-by: naman360 <naman.geek@gmail.com>

This PR fixes #1054

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by tripathyprateek — APPROVED** [review]

**Comment by leecalcote** [comment]
My apologies, @naman360. I accidentally referenced the wrong profile picture in the initial description of this issue. @hexxdump is a lovely lady, not the handsome man that I accidentally referenced. @hexxdump might provide her preferred profile picture instead.

**Comment by naman360** [comment]
Okay cool @leecalcote

**Review by hexxdump — COMMENTED** [review]
@naman360 , you could use my profile picture from - https://drive.google.com/file/d/1yiKX6UgkFQcInsEbyytzpM-bWtOhsAmA/view?usp=sharing

**Review by Jashpatel1 — APPROVED** [review]
Nice work. Thanks @naman360

**Comment by leecalcote** [comment]
Yay! A community profile for @hexxdump. 🎈

**Pull request merged**
