### PR TITLE
[NG] Meta images in SEO component

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR adds SEO images #1395 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@leecalcote Checkout the imagehub page. Its just import the image and pass as a prop. Will you provide me images or add them?

**Comment by leecalcote** [comment]
This makes sense. I know that it's a bit of work, but you're able to:

1) set all pages to have the default image if none other area specified - this should be done in one central place and imported to all pages, ideally.
2) pull page specific images from the existing pages on the current site

**Comment by leecalcote** [comment]
I will happily do this work. My plate spills over, though.

**Comment by Jashpatel1** [comment]
> I will happily do this work. My plate spills over, though.

I will do it. Will ask if I don't find an image.

**Comment by leecalcote** [comment]
Thank you, Jash

**Comment by Tanuj22** [comment]
Some pages in the templates folder like blog-category-list blog-tag-list are left do not have a description. Also, we are not keeping a description for the other individual pages?

**Comment by Jashpatel1** [comment]
> Some pages in the templates folder like blog-category-list blog-tag-list are left do not have a description. Also, we are not keeping a description for the other individual pages?

Description can be done. For images, SEO component would have to be incorporated inside all individual pages.

**Comment by Tanuj22** [comment]
> > Some pages in the templates folder like blog-category-list blog-tag-list are left do not have a description. Also, we are not keeping a description for the other individual pages?
> 
> Description can be done. For images, SEO component would have to be incorporated inside all individual pages as done in books.

Why can't we use the public URL from graphql query kind of like this https://github.com/layer5io/layer5/blob/776622f27c3267e962d22f3bd07c6724128b0df7/src/components/image.js#L9

**Comment by Jashpatel1** [comment]
> > > Some pages in the templates folder like blog-category-list blog-tag-list are left do not have a description. Also, we are not keeping a description for the other individual pages?
> > 
> > Description can be done. For images, SEO component would have to be incorporated inside all individual pages as done in books.
> 
> Why can't we use the public URL from graphql query kind of like this https://github.com/layer5io/layer5/blob/776622f27c3267e962d22f3bd07c6724128b0df7/src/components/image.js#L9 

I tried it. It couldn't resolve the static image at that URL.

**Comment by Tanuj22** [comment]
Can you set the description for blog-category-list blog-tag-list. They will same as blog

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
