### PR TITLE
[Community] Member Profile: Deepesha Burse

### LINKED ISSUE #3144: [Community] Member Profile: Deepesha Burse
**Current Behavior**

@deepeshaburse  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @deepeshaburse  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @deepeshaburse 
- Twitter: [3007Burse](https://twitter.com/3007Burse)
- LinkedIn: [deepeshab](https://www.linkedin.com/in/deepeshab/)
- Link to profile picture: https://drive.google.com/file/d/1aCPVhjT-5vX5Jv8wnKOjtDC42YI13eTD/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Jonathan-Foo**
Signed-off-by: Jonathan Foo jonathan.foozh@gmail.com

**Description**
Completed member profile for Deepesha Burse.
image

This PR fixes #3144 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 89a8cfbfac8169140c4b0e59591de8dcca450720 at: https://6316ec6ac76bbe139d57f94c--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Chadha93** [comment]
// @deepeshaburse

**Comment by deepeshaburse** [comment]
Looks great to me! Thanks @Jonathan-Foo 😄

**Pull request merged**
