### PR TITLE
Added Aneesh Nema as a Contributor & Community Member

### LINKED ISSUE #1592: [Community] Member Profile: Aneesh Neema
**Current Behaviour**

@aneeshnema has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @aneeshnema as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  aneeshnema 
- Twitter:  aneeshnema
- LinkedIn:  aneesh-nema
- Link to profile picture: https://avatars3.githubusercontent.com/u/31976598?s=460&u=d6bdd33fec1343f12c7dd5637a55c916ff78a844&v=4

@aneeshnema Could you please check and confirm this?

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

### PR DESCRIPTION
**Pull request by chinmaym07**
**Description**

This PR fixes #1592 

Here you go @aneeshnema  .Congrats & Keep Contributing !! 🎆 🔥 

Screenshot_2021-02-23 Aneesh Nema

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — COMMENTED** [review]
Please update the location as well

**Comment by Nikhil-Ladha** [comment]
@aneeshnema if you could share your location (City, Country/State) the same can be updated as well.

**Comment by chinmaym07** [comment]
> Please update the location as well

Yes Sure @Nikhil-Ladha . Can your please provide the location to be added ?

**Comment by aneeshnema** [comment]
Delhi, India

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
