### PR TITLE
added meshery operator web page

### LINKED ISSUE #2021: Create webpage for meshery operator
**Description**
As of now there is no webpage for meshery operator .
So when https://layer5.io/service-mesh-management/meshery/meshery-operator is opened , there is a 404 error.
**Expected Behavior**
A  meshery operator webpage needs to be designed and created.

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

Created a meshery operator page

This PR fixes #2021 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cc2fcdfce42cd71c00477878709af62f970d1939 at: https://61137321ee78ba99ddaf8fdc--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
https://61137321ee78ba99ddaf8fdc--layer5ng.netlify.app/service-mesh-management/meshery/mesheryoperator

**Review by Jashpatel1 — COMMENTED** [review]
@debo19 Looks good. Just a few tweaks. For mobile view, remove the extra margins.
Capture1

**Comment by l5io** [comment]
🚀 Preview for commit 2d0b98363a7d9222eb58aade81ae80deda29edfc at: https://61141a6158c1ad00aa8b17f5--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b6d4a54372c79825d0b845ce0ce7258618c0f9e2 at: https://61145000e1e4972b80a2e788--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 79d5cd80bd88baca7acfbb4cf0dd1d2ae74e4012 at: https://611452c172ba0d2f9596ce03--layer5ng.netlify.app

**Review by Jashpatel1 — DISMISSED** [review]
Looks good. @leecalcote Please verify the content

**Comment by Jashpatel1** [comment]
image
Please fix this.

**Comment by Jashpatel1** [comment]
> image
> Please fix this padding/margin.

**Comment by l5io** [comment]
🚀 Preview for commit f094e9eb4112d7c4e15c76b2113daf691d73d591 at: https://6114b7b0db32ed684b849b71--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Thanks for these updates, @debo19. Ready for review round 2, @Jashpatel1

**Comment by Jashpatel1** [comment]
@debo19 You have reverted the name change and thus the URL change. Is it intentional?

**Comment by debo19** [comment]
@Jashpatel1 I think it is some issue with my device, I couldnt load the page with that name, I'm changing it back now, I hope it works

**Comment by l5io** [comment]
🚀 Preview for commit 00c8a034a2fce4824e5aec63e987d92e14a9cc7d at: https://61153bd873d674e68e514352--layer5ng.netlify.app

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks @debo19

**Pull request merged**
