### PR TITLE
added call to action => join the community on the meetings page 

### LINKED ISSUE #2979: [Community] Calendar page: Add Newcomers Welcome section
**Current Behavior**
A call to action (to join the community) is missing after the table of meeting information on this page - https://layer5.io/community/calendar#meetings.

**Desired Behavior**
Ideally, Newcomers Welcome section from the /community page is also added to the /community/calendar page after the table full of meeting details.

**Screenshots / Mockups**
Screen Shot 2022-07-27 at 3 34 35 PM

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**
Added the  call to action (to join the community) after the table of meeting information on meetings page.
This PR fixes #2979

**Notes for Reviewers**

Screenshot from 2022-07-31 13-59-30

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Yes, I signed my commits.

### CODE REVIEW

**Review by kayceeDev — APPROVED** [review]
This is good to go 💯 Weldone!!

**Comment by legendarykamal** [comment]
Thankyou @kayceeDev

**Review by Lezette — APPROVED** [review]
Looks good to me! nice one @legendarykamal

**Review by subhradwip01 — APPROVED** [review]

**Comment by subhradwip01** [comment]
Looks good to me

**Comment by legendarykamal** [comment]
@leecalcote everyone is happy, now lets get this merged :)

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @legendarykamal, however, I'm looking for the Newcomers Welcome section to be added, not the Join the Community CTA.

**Comment by leecalcote** [comment]
I see how the description under Current Behavior leads you to this implementation. Please see the description under **Desired Behavior** and the mockup.

**Comment by kayceeDev** [comment]
Wow!, I take an L for this. Next time I will surely look on what the issue is before looking at the implementation and code quality. @legendarykamal please not of @leecalcote feedback and update the PR. Thanks a lot @leecalcote

**Comment by legendarykamal** [comment]
ohhh @leecalcote got it , will make changes .

Yes @kayceeDev noted :) I guess lee was checking everyone's reviewing skills .

**Comment by legendarykamal** [comment]
Updated ss 
image

**Comment by subhradwip01** [comment]
@leecalcote always on good edge of review.. it is my mistake i didn't read the description of issue properly 😓

**Comment by leecalcote** [comment]
@legendarykamal no sweat. I've been there, too.

**Comment by l5io** [comment]
🚀 Preview for commit e5e00125b2e8db433ef811a9008a92eade2a1854 at: https://62e986464c8fb30062ba2fe8--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Thanks!

**Pull request merged**
