### PR TITLE
[Layer5 Programs] - Updated LFX Mentorship

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR Updated LFX Mentorship Page at https://layer5.io/programs/lfx

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 96be5df07eedd3818ee1692e339ced683605d861 at: https://609ef559642f7900d6ee495d--layer5ng.netlify.app

**Comment by leecalcote** [comment]
I should have clarified that we'll leave the GSoD program as-is (copy and paste, not cut and paste)

**Comment by adithyaakrishna** [comment]
The GSOD Page is still there, the file I deleted didn't contain any data, everything was commented in that. So I thought we could remove it 😶

**Comment by leecalcote** [comment]
Oh! I see. Ok, sounds good.

**Pull request merged**
