### PR TITLE
[Community] Member Profile: Senali

### LINKED ISSUE #4205: [Community] Member Profile: Senali
**Current Behavior**

@senali-d  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @senali-d  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @senali-d 
- Twitter: [senali_d](https://twitter.com/senali_d)
- LinkedIn: [senali-d](https://www.linkedin.com/in/senali-d/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by kotkaravishkar**
**Description**

This PR fixes #4205

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c6ad52ea3007613210d37995ffb10aa51be0c5bf at: https://645d68c9e32895112cda847b--layer5.netlify.app

**Comment by leecalcote** [comment]
Yay, @senali-d! 🎈

**Review by senali-d — CHANGES_REQUESTED** [review]
Thank you @kotkaravishkar.

Please make sure to sign-off your commits by adding -s flag, i.e, `git commit -s -m "commit message"`

Please refer the [contribution guide](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits) for further information.

**Comment by l5io** [comment]
🚀 Preview for commit 43e1feed081f9ac5b0e3661510a2bc4fd9a2ae73 at: https://645ea75df630b33e38c387b8--layer5.netlify.app

**Comment by senali-d** [comment]
@kotkaravishkar Still DCO fails. Please refer [DCO](https://github.com/layer5io/layer5/pull/4217/checks) for resolve it.

**Comment by Chadha93** [comment]
Let's not hold this one. Taking care of DCO.

**Review by Chadha93 — APPROVED** [review]
LGTM, thank you @kotkaravishkar

**Pull request merged**
