### PR TITLE
added mohammed zaki to the members

### LINKED ISSUE #5041: [Community] Member Profile: Zaki
**Current Behavior**

@zakisk has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @zakisk as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @zakisk
- Twitter: [@dev_zaki](https://twitter.com/dev_zaki)
- LinkedIn: 
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by shishiro26**
**Description**

This PR fixes #5041 

**Notes for Reviewers**

added mohammed zaki to the members 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a31be3b7739c5f7bd7af3b4e7f37f377fe7b89ed at: https://652aceeedafbc11b00c12223--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Review by zakisk — APPROVED** [review]

**Comment by abhijeetgauravm** [comment]
> LGTM!

// @ritiksaxena124 @sudhanshutech

**Comment by ritiksaxena124** [comment]
Thank you @shishiro26 👏

**Review by ritiksaxena124 — APPROVED** [review]

**Pull request merged**
