### PR TITLE
fix typo error in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vivekBoii**
**Description**

targetted -> targeted

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 942f8ed19bff9224e027d4b1e1506943097fde6c at: https://653e8ca22f3724140f657d67--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
Thanks for the contribution @vivekBoii . 

P.S. - It's a good practice to open an issue before making the PR.

**Comment by vivekBoii** [comment]
@abhijeetgauravm  I am new to open source sir thanks for guiding

**Review by Mohith234 — APPROVED** [review]
Thanks for the quick fix @vivekBoii. Keep Contributing 🚀

**Comment by vivekBoii** [comment]
Ready for merge

**Pull request merged**
