### PR TITLE
[Footer] Footer style fix

### LINKED ISSUE #3719: [Footer] Overlapping content: newsletter subscription
### Description
We're in need of a tweak of the media query as it pertains to the footer.

### Expected Behavior
No overlap of elements.

### Screenshots
Screenshot 2023-02-08 at 5 02 09 PM

### Environment:
- Host OS:  macOS
- Browser:  Safari

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
Signed-off-by: Sheikh-JamirAlam <alamjamir15@gmail.com>

**Description**

This PR fixes #3719 

**Notes for Reviewers**
Now the newsletter subscription doesn't overlap with other elements.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Sheikh-JamirAlam** [comment]
@leecalcote Going through the footer.style.js file, I noticed this line-
https://github.com/layer5io/layer5/blob/e9dd7372b489edf13e3ce2698db83d95f9177ec5/src/sections/General/Footer/footer.style.js#L148
It didn't have the '@' in media thats why it didn't change anything in the css. Therefore, I took the liberty to remove that and add my changes. Let me know if you want to add it back.

**Comment by eeshaanSA** [comment]
Click on the build/Preview site link and check why the build preview is failing, @Sheikh-JamirAlam

**Comment by eeshaanSA** [comment]
did you commit any changes made in package-lock.json or package.json?

**Comment by Sheikh-JamirAlam** [comment]
@eeshaanSA @leecalcote Submitted a new pr #3723

**Comment by leecalcote** [comment]
Thanks, @Sheikh-JamirAlam!

Syncing with master.

**Comment by l5io** [comment]
🚀 Preview for commit c20786925832165fbdc3037ab8465b9498b1d55f at: https://63e54c9e23b42c060f879004--layer5.netlify.app

**Pull request closed without merging**
