### PR TITLE
issue fix pointer disappears on search icon Fixes #3891

### LINKED ISSUE #3891: The pointer disappears when I try to click on search icon
### Description
The pointer disappears when I try to click on search icon   at    https://layer5.io/blog

### Expected Behavior
Pointer must not disappear

### Screenshots

https://user-images.githubusercontent.com/91942072/222900726-bac9d20e-a8c4-4e2f-932e-51091a9d95b4.mp4

@leecalcote I don't know if it is actually a problem or it has to be like that
Please confirm. If it was made like that intentionally then I will close this issue
If its a issue then please assign me😊

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by parmishh**
Fixes #3891 
https://github.com/layer5io/layer5/issues/3891

**Description**

This PR fixes #3891 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 08549b2b11a0c830c04866d482fa2c8d32b5c8dd at: https://640428f89f540d51310ef55e--layer5.netlify.app

**Comment by parmishh** [comment]
@leecalcote I have solved the issue of disappearing pointer which you assigned me and it looks good now
I have made a PR for the same  could you review the changes.
It looks like this now

https://user-images.githubusercontent.com/91942072/222943143-e2c31281-51c5-4e39-9de4-d8e5c8d1ce2e.mp4

**Comment by swagataroy30** [comment]
May be we can make `cursor: pointer` specific to the search icon as i checked your fix it's made cursor pointer to the entire button
which makes the cursor to be pointer when hovered over the button not being specific to the icon

**Comment by parmishh** [comment]
@swagataroy30 the cursor disappears when on the button not only when on the icon.
Here we need to understand that why button is created functionality is linked to button not just the icon.
Icon is just part of the button. So What I have done is correct.

**Comment by leecalcote** [comment]
@parmishh I encourage you to add this to the agenda of this Monday's Websites meeting.

**Comment by parmishh** [comment]
@Chadha93 @leecalcote  how to add this to agenda item for the meeting?

**Comment by leecalcote** [comment]
> @Chadha93 @leecalcote how to add this to agenda item for the meeting?

@parmishh follow the steps in the [Newcomers Journey Map](https://layer5.io/community/newcomers) and you'll find yourself with the ability to suggest agenda items.

**Pull request closed without merging**
