### PR TITLE
fix nav bar highlight colors

### LINKED ISSUE #3593: Inconsistency in navbar item highlight across themes
#### Description

image

image

#### Expected Behavior
Only the active tab should be highlighted in a different color, all others should be same.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by moazzam07**
Signed-off-by: unknown <kmohdmoazzam70@gmail.com>

**Description**

This PR fixes #3593 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by moazzam07** [comment]
hey @Shivam-AfA i have made a pull request please do check

**Comment by l5io** [comment]
🚀 Preview for commit c39d21ad2e5389bab395af90a20f44e438230da2 at: https://63bc67bd42e27d077deae694--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
It seems correct to me! @leecalcote @GaganpreetKaurKalsi

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Seems good to me, great work done here @moazzam07 🚀 👍

**Comment by moazzam07** [comment]
Thanx @Shivam-AfA @GaganpreetKaurKalsi

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good.

**Pull request merged**
