### PR TITLE
fix #4917 Added Community Handbook link in the footer

### LINKED ISSUE #4917: [Programs] Representation of Writing Program
### Current Behavior
The site footer does not include a direct "[Handbook](https://layer5.io/community/handbook)" link under community. 

### Desired Behavior
It’d be good to have the Writing Program added to the Internship Program page and to then consolidate the footer links, making room for a Community Handbook link in the footer. 

Screenshot 2023-09-15 at 11 58 49 AM

### Screenshots / Mockups
__mockup for needed__

### Implementation
1. Consolidate "Internship and Writing Programs" into one line. If this combined text is too long, then shorten to simply "Internship Programs"
2. Add new section for Writing Program in the [Internships page](https://layer5.io/careers/programs)

### Acceptance Tests
1. layer5.io/community/handook is a new "Handbook" link in the footer under the Community section.
2. Writing program is represented on the Internships page.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by aman44444**
**Description**

This PR fixes #4917

**Notes for Reviewers**
I tried to add Writing Program section in the Internship Page but link path didn't work.
Screenshot (3)
Screenshot (4)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8022c5201708e44b3a889f92983ce8658cb58b37 at: https://6511623f79d05806b06fc216--layer5.netlify.app

**Review by Mohith234 — CHANGES_REQUESTED** [review]
- Do Implement the writing program section on the Internship Programs page
- DCO check is failing, Fix it

// @aman44444

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by l5io** [comment]
🚀 Preview for commit 3531055b0a24e061e73f5ef920eca9310de9197b at: https://651a59b04119b6557110820a--layer5.netlify.app

**Comment by vishalvivekm** [comment]
> * Do Implement the writing program section on the Internship Programs page
> 
>     * DCO check is failing, Fix it
> 
> 
> // @aman44444

@aman44444 The desired behavior and implementation is explained in detail here in the [Issue Description ](https://github.com/layer5io/layer5/issues/4917#issue-1898795130).
We need to make sure those are addressed.

**Pull request closed without merging**
