### PR TITLE
feat: add news section

### LINKED ISSUE #514: [NG] Add the news items section with a news post
**Current Behavior**
Currently, The layer5-ng site does not have a news section, So generate a news section which can cater to all the news posts. Also, add a sample news post for preview.

**Desired Behavior**
The news posts can be found [here](https://layer5.io/news).

---
[Optional] **Alternatives**
A possible solution can be replicating the blog section and using the same template as the blogs for the news items.

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #514

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
This looks pretty nice, @Tanuj22.

It's probably time for us to be rid of the blue header / section title color.

There is a merge conflict you might want to have a look at.

**Comment by leecalcote** [comment]
Never mind about the merge conflict. You knocked it out already. 👍

**Comment by Tanuj22** [comment]
@leecalcote You mean the pink colors right?

**Comment by leecalcote** [comment]
Screen Shot 2020-09-04 at 10 52 30 PM

And these, too. We should be able to find another color in the layer5.io/brand to put to use here.

**Review by leecalcote — APPROVED** [review]
Merging. The text color can be addressed separately.

**Pull request merged**
