### PR TITLE
[Books] Add a couple o' service mesh patterns site callouts; fixes [Projects] Service Mesh Pattern website links

### LINKED ISSUE #3447: [Projects] Service Mesh Patterns: add link to book website
**Current Behavior**
A new site has been stood up here - https://service-mesh-patterns.github.io/service-mesh-patterns/

**Desired Situation**
A link or two to this site should be found on the layer5.io page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR fixes #3447

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@tinniaru3005 review at-will.

**Comment by l5io** [comment]
🚀 Preview for commit 3fcb99dafebe29bc4c5f5a818eca850b86f2e896 at: https://638999218c00a53af73cbf0e--layer5.netlify.app

**Comment by leecalcote** [comment]
@tinniaru3005 any feedback?

**Comment by tinniaru3005** [comment]
> @tinniaru3005 any feedback?

Hey @leecalcote will look into it and the other PRs by today (within 12 hours).

**Comment by tinniaru3005** [comment]
Looks perfect @leecalcote

**Comment by leecalcote** [comment]
Thanks!

**Pull request merged**
