### PR TITLE
Added Member Profile Of Hiren Timbadiya

### LINKED ISSUE #4723: [Community] Member Profile: Hiren
**Current Behavior**

@hirentimbadiya has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @hirentimbadiya as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @hirentimbadiya
- Twitter: [heyhiru](https://twitter.com/heyhiru)
- LinkedIn: [hirentimbadiya74](https://www.linkedin.com/in/hirentimbadiya74/)
- Meshery Cloud: [01da757f-4fee-448e-9ba1-1bb655b2b05a](https://meshery.layer5.io/user/01da757f-4fee-448e-9ba1-1bb655b2b05a)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Description**

This PR fixes #4723

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1325669c82a4b17e7a9cbdcd3a2df5f66ed4fb71 at: https://64d742bebc78e762bcd0fb17--layer5.netlify.app

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@VivekBaldha0712 , please replace my bio with this one : 
I am Hiren Timbadiya, I consider myself an inquisitive developer, constantly seeking to expand my knowledge in various technologies and delve into the boundless possibilities they offer. I am  interested in DevOps technologies like kubernates, docker, service meshes, ci/cd, cloud and also enthusiastic about opensource. I am a highly motivated individual who is continuously learning and during my spare time, I love playing cricket and preparing a meal for myself.

and profile picture with this : 
image

**Comment by l5io** [comment]
🚀 Preview for commit 2a5fbe04873a456bdb1a712f7affc564f50685b8 at: https://64d77a7bf606f97eb4fbc334--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3805d50d0bd3dcd0360c7555b5a92cc19a314301 at: https://64d7942efaf3190c2f5eed55--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Thanks @VivekBaldha0712 , Looks Good to Me 👍🏻

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Comment by Ghat0tkach** [comment]
Hii @VivekBaldha0712 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by VivekBaldha0712** [comment]
@Chadha93 Kindly review this PR.

**Pull request merged**
