### PR TITLE
[Community] Jared Byers

### LINKED ISSUE #2713: [Community] Member Profile: Jared Byers
**Current Behavior**

@jbyers19 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @jbyers19
- Twitter: N/A
- LinkedIn:  jaredbyers25  
- Link to profile picture: 

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Akshit42-hue**
**Description**

This PR fixes #2713 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
please do have a look @asubedy @warunicorn19

**Review by Abhijay007 — COMMENTED** [review]
@Akshit42-hue you have some indentation issues in your added Yaml file 

here is error log : 

```

  YAMLException:end of the stream or a document separator is expected at line 3  , column 9:
      position: Contributor
              ^/home/runner/work/layer5/layer5/src/collections/members/jared-bye  rs/index.mdx: end of the stream or a document separator is expected at line 3,   column 9:
      position: Contributor
              ^
 ```

**Comment by Akshit42-hue** [comment]
@Abhijay007 still the prevent build is failing

**Comment by l5io** [comment]
🚀 Preview for commit 5f3fbaa098c04aaaa0b4d6b0112077c5f70f7e91 at: https://6259ae87cafef90ad2f06fa2--layer5ng.netlify.app

**Review by jbyers19 — APPROVED** [review]
It feels a bit weird reviewing a PR about myself. 😆

**Review by Chadha93 — APPROVED** [review]
LGTM, you look great in pic @jbyers19

**Pull request merged**
