### PR TITLE
[NG] Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**
Updates to instructions for contributing on Layer5NG

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] No, I didn't. GitHub web doesn't allow me to do so.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
It would require some changes ig.....I think let's keep this PR open and on hold for the time being as we are almost there to go live with the site...once done I will push the updates to this PR....does that sound good?

**Comment by leecalcote** [comment]
@Nikhil-Ladha, in general, that makes sense. This update is against the `layer5-ng` branch, though, where we already have a separate CONTRIBUTING.md that is specific to layer5-ng.  This PR is an update to that.

**Comment by Nikhil-Ladha** [comment]
Okay...then in that aspect there might needs to be few updates in the landscape section of this guides as the files are no more in `yml` format but in `js` format 😅....also I think we should add the view only or view/comment link of the site design spec as the new members not already part of the community will not be able to access the guides then.

**Comment by leecalcote** [comment]
Thanks for this, @Nikhil-Ladha. I changed from .yml to .js and added a note about the data source for the SMI table.

I'm ok with requiring that would-be contributors first join the community in order to gain access to resources like this Google Doc. Having the link here is helpful for those already part of the community and the lack of access hopefully serves as an incentive for would-be members to join.

**Review by Nikhil-Ladha — APPROVED** [review]
Cool 😎

**Pull request merged**
