### PR TITLE
logo according to theme

### LINKED ISSUE #3789: [UI] The SCA logo should be replaced with light-version when site in dark-mode on Programs page
### Description
The SCA logo is not so visible in dark mode

### Expected Behavior
The color of the SCA logo should be visible in darkmode on the Programs page. And able to toggle between light mode and dark mode.
Find the various SVG files to the logo here
- https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T

### Screenshots
Screenshot 2023-02-20 at 9 49 32 AM

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### LINKED ISSUE #4228: theme based logo on programs page
### Description
1)On the https://layer5.io/careers/programs page in dark mode the linux foundation logo is 
image 

while on https://layer5.io/programs/lfx in dark mode, the logo is 
image

2)Same is the issue with MLH logo. On https://layer5.io/careers/programs in dark mode the MLH logo is 
image
while on https://layer5.io/programs/mlh in dark mode, the logo is 
image

### Expected Behavior
Theme based color change in logo on the https://layer5.io/careers/programs page should be followed on https://layer5.io/programs/mlh and https://layer5.io/programs/lfx pages too

### Screenshots
imageimage
I would like to work on this issue.

### Environment:
- Host OS:
- Browser:

### PR DESCRIPTION
**Pull request by HetviSoni**
**Description**

This PR fixes #4228 and fixes #3789

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4b570850c250ca195f3e0f5373c9af0687d9d0d6 at: https://647104cfd1859f09abced9f6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 56c3823f13927911b7942f45a47375fdd1da05f8 at: https://6471a6da7840e246d7fe2134--layer5.netlify.app

**Comment by randychilau** [comment]
Hi @HetviSoni,

Just wanted to say nice job! 

You understood how to correctly target a specific SVG class in the appropriate styled-component. 

You also used styled-component theming `props` to allow the color to change depending on the theme and transition in sync with the rest of the page.

The text in the MLH logo is changing correctly in the preview:

[mlh.webm](https://github.com/layer5io/layer5/assets/90356410/3863a53c-c706-4766-af43-381e7bbd0812)

For the reviewers, here is the current live site:

[mlh_live.webm](https://github.com/layer5io/layer5/assets/90356410/17740f85-a8eb-4344-b9e4-f0f17bf662a4)

Cheers,
Randy

**Comment by vishalvivekm** [comment]
> Hi @HetviSoni,
> 
> I'm not a reviewer, but just wanted to say nice job!
> 
> You understood how to correctly target a specific SVG class in the appropriate styled-component.
> 
> You also used styled-component theming `props` to allow the color to change depending on the theme and transition in sync with the rest of the page.
> 
> The text in the MLH logo is changing correctly in the preview:
> mlh.webm
> 
> For the reviewers, here is the current live site:
> mlh_live.webm
> 
> Again, nice work!
> 
> Cheers, Randy

@randychilau 
I've added you to reviewers. Please review and Say LGTM if you would :))

**Review by randychilau — APPROVED** [review]
Using my [earlier post](https://github.com/layer5io/layer5/pull/4293#issuecomment-1565249470) as part of my review.

The code submitted looks good: 

- svg imported correctly
- correct styles applied to svg
- correct use of theme props and targeted css to change color based on theme.

and the issue is [resolved on the preview](https://6471a6da7840e246d7fe2134--layer5.netlify.app/programs/mlh) as seen in the videos in the earlier post.

LGTM!

**Comment by l5io** [comment]
🚀 Preview for commit 27297e853f5784c48154c5cbb825c01872563dbd at: https://6473bbb837f6b0761280ebf6--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@HetviSoni Thanks for fixing this issue! I see that the LFX logo is still different, I suggest that it should also be consistent. 
And thanks @randychilau for helping out the contributors. 🚀

**Comment by HetviSoni** [comment]
> @HetviSoni Thanks for fixing this issue! I see that the LFX logo is still different, I suggest that it should also be consistent. And thanks @randychilau for helping out the contributors. 🚀

I actually did not make any changes to the lfx logo according to the suggestion (https://github.com/layer5io/layer5/issues/4228#issuecomment-1547744250) (If I understood it correctly😅)

**Comment by Shivam-AfA** [comment]
@HetviSoni I suppose we should change the LFX logo as well. What say @thisiskaransgit?

**Comment by Shivam-AfA** [comment]
@HetviSoni anything on this?

**Comment by HetviSoni** [comment]
Hey @Shivam-AfA really sorry for the delay but I am trying to set up the project. Its getting stuck at image processing jobs🥲

**Comment by l5io** [comment]
🚀 Preview for commit dc5776233470319854bccfb93e71117988bc6f86 at: https://64870bf0e9100a26feef9290--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
Oh okay. @HetviSoni try setting up the environment in WSL2.

**Comment by HetviSoni** [comment]
> Oh okay. @HetviSoni try setting up the environment in WSL2.

Hey finally I am done setting up the project and solving the issue😮‍💨.
I have changed the logos according to theme on the following pages
https://layer5.io/programs/lfx
https://layer5.io/programs/mlh
and as mentioned earlier, there is a similar stale issue for the sca logo so I have also solved it on page
https://layer5.io/programs/sca-contributhon .
Please assign me the issue https://github.com/layer5io/layer5/issues/3789 so that I can push my changes

**Comment by l5io** [comment]
🚀 Preview for commit 15a469009bfd7f06658eb0b8912e82e8468449c4 at: https://648992547e4ef1072980adcc--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@HetviSoni Thanks, please include the fix for #3789 as well.

**Comment by l5io** [comment]
🚀 Preview for commit 8e529381dd33c981bb11e9e9155e62409edd5fdf at: https://6489d11b7b0332007b87bcb6--layer5.netlify.app

**Comment by HetviSoni** [comment]
I have made the changes. Please review it @Shivam-Afa @randychilau

**Comment by Shivam-AfA** [comment]
Thanks @HetviSoni

**Pull request merged**
