### PR TITLE
adding-updated-designs-to-how-it-works-section

### LINKED ISSUE #4826: [Screenshots]  Azure Active Directory (AAD) under "How it Works See It in Action” section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/akri) has only two old screenshots of the designer and visualizer in the  "How it Works See It in Action” section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for **[Azure Active Directory (AAD)](https://layer5.io/cloud-native-management/meshery/integrations/azure-active-directory-aad)**  integration.

### Acceptance Points

- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser. 
- Use Incognito mode on chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by PRANJALRANA11**
**Description**
i have updated the how it works section with updated images both in light and dark mode
This PR fixes #4826 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a709b323218df9aa060dfcab430eb58dc6334648 at: https://64f9bd844150e70a9d0b5ed2--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a709b323218df9aa060dfcab430eb58dc6334648 at: https://64f9bfb9a39a4411137bc3a3--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
hey @PRANJALRANA11 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by PRANJALRANA11** [comment]
hey @Ghat0tkach  i am not able to understand what are you asking and docs stuff could you please explain

**Comment by Ghat0tkach** [comment]
@PRANJALRANA11 , we have our weekly website meeting minutes where we review your PR and takes your feedback.
Join slack channel to get timings of the meeting.

**Comment by PRANJALRANA11** [comment]
ok

**Review by abhijeetgauravm — CHANGES_REQUESTED** [review]
hey @PRANJALRANA11 in preview still not able to see new images from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap)). See this for reference  https://github.com/layer5io/layer5/pull/4914

**Comment by PRANJALRANA11** [comment]
but i had added it already is there  a problem in screenshot

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm image

Ohh you r suppose to add the screenshots to the [Azure Active Directory (AAD)](https://layer5.io/cloud-native-management/meshery/integrations/azure-active-directory-aad) according to the issue u raised PR but it seems like u added to the [Akri](https://layer5.io/cloud-native-management/meshery/integrations/akri) integration.

**Comment by abhijeetgauravm** [comment]
But @PRANJALRANA11 No sweat u comment on this issue for assignment https://github.com/layer5io/layer5/issues/4830 . And mention this issue u r fixing in your PR.

**Comment by PRANJALRANA11** [comment]
@abhijeetgauravm oh ok I got it sorry for inconvenience

**Pull request closed without merging**
