### PR TITLE
updated recognition

### LINKED ISSUE #4573: [Site] Move badge to separate list
### Description
These badges are not in sets of list.
At - https://layer5.io/community/handbook/recognition

### Expected Behavior
Separate them. Move them into two lists. 
The two sets of badges need to be separated into two lists. Also, fix the typo in GitOPs, and make P a small case.

Set 1 name - Activity badges:
1. Design Pioneer
2. Application Pioneer
3. Sharing is caring
4. First design
5. Shipped
6. Need for speed
7. Hip Hacker
8. Streamer
9. GitOps with friends

Set 2 name - Projects:

1. Image Hub
2. MeshMap
3. Service Mesh Performance
4. Community
5. Meshery
6. Meshery Operator
7. Patterns
8. Landscape
9. Writer’s Program
10. Nighthawk
11. UI/UX
12. Meshery Catalog
13. Docker Extension
14. Meshery Docs

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
**Description**
Signed-off-by: abhijeetgauravm [abhijeetdav24aug@gmail.com](mailto:abhijeetdav24aug@gmail.com)
This PR fixes #4573 

**Notes for Reviewers**

**[Signed commits] (https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e946b72e937cfeef51e49c642edf178dd9da5290 at: https://64bae8fe693f0b0f46241f1d--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
I think this issue has been resolved na @Chadha93 Sir ?

**Comment by HarshDobariya79** [comment]
Can you please sign off your commits @abhijeetgauravm?

**Comment by abhijeetgauravm** [comment]
Yes I m doing!

**Pull request closed without merging**
