### PR TITLE
Add White Kind Logo

### PR DESCRIPTION
**Pull request by NPDebs**
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>

**Description**
This PR fixes issue #3283.
I created a white version of the Kind logo to be used in the dark mode.

kind-white

**Notes for Reviewers**

This is an alternative. Personally, I think it is more suitable for dark mode.
I'd really appreciate some feedback and suggestions. Thank you!
 
kind-logo-white2

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NPDebs** [comment]
@eeshaanSA @legendarykamal @sahilsuman933 @Nikhil-Ladha @leecalcote 
(In no particular order) Can I get a review from you? Thanks!

**Comment by legendarykamal** [comment]
Nice nice ⭐  ,
2 nd one looks better to my eyes, just a lighter shade of black I would recommend @NPDebs , 

Considering that as I hover on it will come to Life with colour.

**Comment by eeshaanSA** [comment]
That logo is a beauty!! Awesome work @NPDebs

**Comment by NPDebs** [comment]
> Nice nice ⭐  ,
> 2 nd one looks better to my eyes, just a lighter shade of black I would recommend @NPDebs , 
> 
> Considering that as I hover on it will come to Life with colour.

Thanks!

Your input has been noted! If the majority agrees, I'll upload the second logo, with a lighter shade of black. 🙌🏼🙌🏼

**Comment by NPDebs** [comment]
> That logo is a beauty!! Awesome work @NPDebs 

Thanks, Eeshaan! 🤭😊🚀

You didn't say which one though. 😅

**Comment by l5io** [comment]
🚀 Preview for commit c980bbd653efbfeed5da73827d3fa93a1ada1e46 at: https://63446bca13daba48a21df280--layer5.netlify.app

**Comment by leecalcote** [comment]
Thank you for offering feedback, @eeshaanSA 👏

**Comment by leecalcote** [comment]
Ha! You do need to be specific, though, @eeshaanSA 🙂

**Comment by NPDebs** [comment]
Hi Mr @leecalcote. Are you concerned voting early might influence the consensus? 👀 😃

**Comment by Nikhil-Ladha** [comment]
It is not about which logo looks better and which one does not. We shouldn't be creating our own versions of logo TBH. I don't know why are we doing so, using CSS to filter out the color isn't helping?

And, if not then how we should be updating the colors is like maintaining the color pattern of the existing logo. Where it's dark/deep color use black(or a shade of black), and where it's black use white, where it's white use black.

Considering all that, use the second logo but with the below changes like the cork should be black with white spots, the container colors should be what you have in the first image, the left part (which looks more like an engine) should have the 2 strokes and antenna in white color. This should do the trick, share a mock after making the changes then we can decide

**Comment by eeshaanSA** [comment]
@leecalcote I was talking about the second one. @Nikhil-Ladha has a valid point. After making the changes suggested by him, i think the second logo willl go perfectly.

**Comment by NPDebs** [comment]
@Nikhil-Ladha Thannks for the review.

As per your question on why we're creating these logos...maybe that's a valuable topic for the next meeting? 🤔 We can discuss an alternative to optimising logos in dark mode.

I'll make the said changes and share a screenshot right away. 👍🏻

**Comment by NPDebs** [comment]
> It is not about which logo looks better and which one does not. We shouldn't be creating our own versions of logo TBH. I don't know why are we doing so, using CSS to filter out the color isn't helping?
> 
> And, if not then how we should be updating the colors is like maintaining the color pattern of the existing logo. Where it's dark/deep color use black(or a shade of black), and where it's black use white, where it's white use black.
> 
> Considering all that, use the second logo but with the below changes like the cork should be black with white spots, the container colors should be what you have in the first image, the left part (which looks more like an engine) should have the 2 strokes and antenna in white color. This should do the trick, share a mock after making the changes then we can decide

@Nikhil-Ladha Did I miss anything, please?

kind-mock

**Comment by eeshaanSA** [comment]
looks good, @NPDebs

**Comment by Nikhil-Ladha** [comment]
Looks good @NPDebs 👍🏼

**Comment by NPDebs** [comment]
> Looks good @NPDebs 👍🏼 

Thanks! 👍🏻
I'll update the PR now.

**Comment by NPDebs** [comment]
Done @Nikhil-Ladha. 👍

**Review by sahilsuman933 — APPROVED** [review]

**Pull request merged**
