### PR TITLE
Added scroll to top functionality on pagination

### LINKED ISSUE #4108: Pagination should redirect to top
In the blog/resources page i think after click on any page it should scroll to the top of the section so that user can see new resources according to the page right now user have to manually go to top to see new resources after changing the page.

### Screenshots / Mockups

https://user-images.githubusercontent.com/68184118/233058496-b8b979e3-8b6c-4900-aef4-0c1b5062b7f1.mp4

### PR DESCRIPTION
**Pull request by 777Prabhjot**
**Description**

This PR fixes #4108 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a5b64b399d653bcf54852ac6b53965c1badb039d at: https://64423d7d01a060235d476c66--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
LGTM 👏🏻

**Review by Shivam-AfA — COMMENTED** [review]
Great @777Prabhjot ! This was a priority issue which was overlooked. Thanks for the fix. Can you please add the same functionality to the Blogs page as well? https://layer5.io/blog

**Comment by 777Prabhjot** [comment]
@Shivam-AfA done

**Comment by l5io** [comment]
🚀 Preview for commit 049b7eaa61c68c03e278cde8ddafdb550e4a2411 at: https://64436aad954f5a504317a9e0--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Great @777Prabhjot , Thanks for your contribution.

**Review by Shivam-AfA — APPROVED** [review]
Thanks @777Prabhjot

**Comment by Shivam-AfA** [comment]
@777Prabhjot Just a reminder, we stepped over the DCO check this time, but please ensure that you sign off your commits in your upcoming contributions.

**Pull request merged**
