### PR TITLE
Docker screenshots

### LINKED ISSUE #5323: [Screenshots] Docker under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/docker) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Docker](https://layer5.io/cloud-native-management/meshery/integrations/docker) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #5323 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by surajvast1** [comment]
@vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit c5acd39072af32d7fc051f69f8606b1673f7d016 at: https://65ca80bdf12198379cc3e822--layer5.netlify.app

**Comment by narasimha-1511** [comment]
Hey @surajvast1 you have uploaded only the Design part of the Screen shots you should also upload the visualize part ..

**Review by narasimha-1511 — CHANGES_REQUESTED** [review]
need two more screen shots of the visualize part

and also need to update the index.mdx file of the particular integration

**Comment by surajvast1** [comment]
Sure @narasimha-1511

**Comment by surajvast1** [comment]
@saurabh100ni LGTM

**Comment by l5io** [comment]
🚀 Preview for commit dd6a3ebc5c3ed717c119aa99b2e410cf40d9359f at: https://65cbbefeb451fc14e5885938--layer5.netlify.app

**Review by narasimha-1511 — CHANGES_REQUESTED** [review]
all these four are the design ones and where are the visualize?

**Comment by saurabh100ni** [comment]
@surajvast1, for designer it looks two separate designs to me and in some of them are overlapping, can we fix that?

**Comment by surajvast1** [comment]
ofc @saurabh100ni

**Comment by surajvast1** [comment]
Updated image @saurabh100ni

**Comment by saurabh100ni** [comment]
@surajvast1, Don't we sign our commits in PR description by signing the check box 👀?

**Comment by l5io** [comment]
🚀 Preview for commit 82a71f97a41d435f6816070c4ed83036f7886eb6 at: https://65cc5d64db914c72ac4627be--layer5.netlify.app

**Comment by saurabh100ni** [comment]
I see some good work done here, Thanks @surajvast1.

@narasimha-1511 @surajvast1, I guess you guys can make an Impact working collaboratively and taking on Screenshots issues, What do you think of teaming up? You can also encourage new contributors towards this and help in the review, nourishing your leadership skills.

remember we have 230+ integrations, and we aren't halfway there.

**Review by saurabh100ni — APPROVED** [review]

**Comment by surajvast1** [comment]
@saurabh100ni It will be a pleasure contributing in a team and mentoring newcomers. Thanks for this

**Comment by l5io** [comment]
🚀 Preview for commit b32e31bcafd747f9238d0211f267382e495528a2 at: https://65ce57a96f188321fdd84500--layer5.netlify.app

**Comment by saurabh100ni** [comment]
@vishalvivekm, PR LGTM, would please merge it?

**Comment by surajvast1** [comment]
@vishalvivekm Please merge this

**Review by vishalvivekm — APPROVED** [review]
Thanks a bunch @surajvast1 :rocket:

**Pull request merged**
