### PR TITLE
Commented out GSoC 2019 link, and standardized line endings to LF

### LINKED ISSUE #1397: "https://layer5.io/programs/past/gsoc/2019" link gives a 404
Found on [the Layer5 GSoC page](https://layer5.io/programs/gsoc)

### PR DESCRIPTION
**Pull request by pranav-bhatt**
fixes #1397

**Description**

This PR "fixes" #1397 by commenting out the link in question. I have also converted all line endings to LF (Unix), since it caused me issues, and may cause others the same.

**Notes for Reviewers**
I've tested it locally, and seems to run fine even after the line ending conversion. (Will leave the PR as draft for now)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@pranav-bhatt The "This PR fixes #issue_no" should be without quotes on "fixes" so that GitHub can automatically link this PR and the issue. This will automatically close the Issue if you merge the PR. Not a problem, but a suggestion to make things easier.

**Comment by pranav-bhatt** [comment]
> 
> 
> @pranav-bhatt The "This PR fixes #issue_no" should be without quotes on "fixes" so that GitHub can automatically link this PR and the issue. This will automatically close the Issue if you merge the PR. Not a problem, but a suggestion to make things easier.
> 
> A line on the top-
> 
> fixes #1397
> 
> would work.

Thanks for the tip!

**Review by navendu-pottekkat — COMMENTED** [review]
There seems to be a lot of changes that may not be intentional. I think you were trying to add newlines to each file. Is there any way to make the changes to a minimum so that they are easy to review.

This may not be a big deal for this issue but may be helpful for easily maintaining things.

**Comment by navendu-pottekkat** [comment]
> Thanks for the tip!

Congrats on your first PR here!

**Comment by pranav-bhatt** [comment]
> 
> 
> There seems to be a lot of changes that may not be intentional. I think you were trying to add newlines to each file. Is there any way to make the changes to a minimum so that they are easy to review.
> 
> This may not be a big deal for this issue but may be helpful for easily maintaining things.

So the only change to the content is in "collections/_programs/gsoc_2020.html".

The rest are line ending changes, which I thought would reduce errors (I faced a couple of issues while trying to test locally) and maybe even confusion (https://layer5io.slack.com/archives/CFGG6U10E/p1611562206025900) for future contributors.

If you still feel these aren't needed, I'll just roll back and make the one change. Or should I open another issue for this? (this would be more work :P)

**Comment by pranav-bhatt** [comment]
> 
> 
> > Thanks for the tip!
> 
> Congrats on your first PR here!

Thanks 😄

**Comment by navendu-pottekkat** [comment]
@pranav-bhatt That is a nice fix and would be helpful. Since you have mentioned the change in the PR, I think it would be enough.

**Review by Jashpatel1 — APPROVED** [review]
Nice work here. Thanks @pranav-bhatt

**Pull request merged**
