### PR TITLE
[Update] Layer5 projects Image updated on about page

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
This PR updates the Layer5 projects image on the [About page](https://layer5.io/company/about)

Before

After

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ddea0bffdd3fdace8018c92e23af56291b0cf224 at: https://64a8602614a7be18194416dc--layer5.netlify.app

**Comment by leecalcote** [comment]
@ritiksaxena124 the after is missing graphics...

**Comment by ritiksaxena124** [comment]
> @Nikhil-Ladha @randychilau how do we prevent Gatsby from optimizing images? Image quality suffers here more than is necessary. // @Shivam-AfA @Udit-takkar

Maybe we can use image tag instead of using StaticImage tag provided by Gatsby

**Comment by randychilau** [comment]
Hi All,

Is the image a svg? If so, I don't believe Gatsby provides an ability to optimize it via `StaticImage` or `GatsbyImage` offered by the [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/).

>Can Gatsby Image be used with SVGs/GIFs?
Unfortunately Gatsby Image cannot be used to display SVG or GIF images.

>Why will SVGS not work with Gatsby Image?
SVGs are vector files and can scale infinitely without loss of quality. There is no need to make multiple versions of the file for different sizes.
([source](https://robertmarshall.dev/blog/an-introduction-to-gatsby-plugin-image/))

@ritiksaxena124 suggestion is one of Gatsby's [recommended ways](https://www.gatsbyjs.com/docs/how-to/images-and-media/importing-media-content/#images-svg-and-pdfs) to add a SVG to a page.

If there are still image quality issues, then we can investigate more with comparisons of what it should look like vs. what is being displayed on the site?

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit 1b7c2f5fac6a124d51726ace119ceb56905aa227 at: https://64a961ba6ffd1001a4ee1f67--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Thank you @randychilau it looks good now 🙌

**Comment by samyakshah3008** [comment]
@ritiksaxena124  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by Nikhil-Ladha — APPROVED** [review]
The image looks good to me now

**Pull request merged**
