### PR TITLE
Changed faqs behavior to not allow multiple expansion closes#4481

### LINKED ISSUE #4481: FAQ Section need to be enhanced in https://layer5.io/careers/programs
### Current Behavior

In the faq accordion, all 4 drop down qna panels can be open at the same time. But this leads to a bad user experience

### Desired Behavior

Only one panel should be open at a time.

### Screenshots / Mockups

image

### Acceptance Tests

Please assign me this issue
---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ranjanmangla1**
**Description**

This PR fixes #4481 

**Notes for Reviewers**
I have changed the faq accordions to be only one open at one time. Earlier you could open many at one time, they would not close, so it become messy at pages like https://layer5.io/company/faq.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 65b88aae4d002851958935ce6b25d1b992f5743c at: https://64aab298c6d6e629fddcbcde--layer5.netlify.app

**Review by saaagarsingh — COMMENTED** [review]
I've checked the codebase and preview the solution looks fine and good to go. Maintainers should verify once before merging it to the main codebase.

**Comment by samyakshah3008** [comment]
@ranjanmangla1  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, thanks for the quick fix, while you're on this page kindly provide a quick fix here too: 

Screenshot from 2023-07-10 00-18-11

**Comment by l5io** [comment]
🚀 Preview for commit 3adcf45a50417e1366c53eb9e6eadbe5da7890c3 at: https://64ab9e63af181520247c353e--layer5.netlify.app

**Comment by ranjanmangla1** [comment]
@thisiskaransgit DONE

**Comment by ranjanmangla1** [comment]
removed "BETA" @thisiskaransgit

**Comment by l5io** [comment]
🚀 Preview for commit 1d222d6c3eb3c0c9a45e6c5711d1f26e9828ec2a at: https://64ac3de78311f900d1036186--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
