### PR TITLE
[Community] Created Member Profile: Harkirat Singh 

### LINKED ISSUE #3037: [Community] Member Profile: Harkirat Singh
**Current Behavior**

@harkiratsm has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @harkiratsm  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: harkiratsm
- Twitter: harkiratsm
- LinkedIn: harkiratsm 
- Link to profile picture: https://pbs.twimg.com/profile_images/1538715817860141056/lEdWAejx_400x400.jpg

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**

This PR fixes #3037

**Notes for Reviewers**
Screenshot from 2022-08-12 23-59-46

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
@harkiratsm let me know If you want something to be added in your bio.

**Comment by l5io** [comment]
🚀 Preview for commit d7ee2e320de0dc032b8c05c65bb7bb21358fe1bd at: https://62f6a070928db2009a8fc3a7--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
LGTM.

🎈 @harkiratsm! 🎉

**Comment by leecalcote** [comment]
Thank you for this screenshot, @legendarykamal. Most helpful.

**Comment by legendarykamal** [comment]
SS No sweat @leecalcote  thanks 🙇 

Congratulations @harkiratsm 🥇

**Comment by leecalcote** [comment]
🚀 👨‍🎤

**Pull request merged**
