### PR TITLE
Added alt tag to all images

### LINKED ISSUE #1050: [NG] Add alt texts to all images present in layer5-ng
**Current Behavior**
Currently, many image tags do not have alt texts present in the layer5-ng site.

**Desired Situation**
Add related alt texts to images.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes #1050 

**Notes for Reviewers**
Also fixed the wrong usage of the images

Capture35

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
A very hefty work, here. Thanks for taking it @kishore007k  
A few images left with adding alt tags.
[GSOC logo](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/blog/2020-06-23-google-summer-of-code-2020-service-mesh-performance-with-envoy-nighthawk/index.mdx)
[Community Bridge](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/programs/communitybridge/index.mdx)
[GSOC 19](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/programs/gsoc-2019/index.mdx)
[GSOC 20](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/programs/gsoc-2020/index.mdx)
[GSOD](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/programs/gsod-2020/index.mdx)
[MLH](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/programs/mlh-2020/index.mdx)
[Social Links](https://github.com/layer5io/layer5/blob/layer5-ng/src/components/SocialLinks/index.js)

After adding all these, you can run a lighthouse check, and under the SEO section of the report, you can find the links to images left without alt tag if present. Also please resolve the conflicts.

**Comment by kishore007k** [comment]
Hey, @Tanuj22 I'm facing some difficulty in giving the `alt` tag to one element on the landing page of the site, Can you help me with that?

Here is the Image
Capture37

**Comment by Jashpatel1** [comment]
> Hey, @Tanuj22 I'm facing some difficulty in giving the `alt` tag to one element on the landing page of the site, Can you help me with that?
> 
> Here is the Image
> Capture37
> 
> Here it says `canvas` I wonder how to add `alt` tag for that.

@kishore007k I guess you can leave it for now. Please resolve the conflicts.

**Comment by Tanuj22** [comment]
@kishore007k there are still a lot of conflicts

**Comment by kishore007k** [comment]
> @kishore007k there are still a lot of conflicts

It works fine in my machine I don't get why it is showing as conflict

**Comment by Tanuj22** [comment]
This is due to the merge of #1048. You can get your `layer5-ng` branch in sync with the upstream. Then merge `layer5-ng` into `kishore007k/added-altTag-to-all-images` branch. Then you have to resolve the conflicts.

**Review by Tanuj22 — APPROVED** [review]
Thanks for this @kishore007k :)

**Pull request merged**
