### PR TITLE
add code block component and cypress turorial in newcomers page

### LINKED ISSUE #1559: [Meshery] Change single install step to to CodeBlock component
**Desired Behavior**
Implement the code section on /service-mesh-management/meshery/getting-started with the copy-to-clipboard support using src/components/CodeBlock component.

**Screenshots / Mockups**
Screen Shot 2021-02-17 at 5 06 49 PM

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### LINKED ISSUE #1724: [Community] Newcomers tutorials - add Cypress tutorial from Rodolfo
**Current Behavior**
The [table of tutorials on the newcomers page](https://layer5.io/community/newcomers) is missing Rodolfo's tutorial on Cypress.

**Desired Behavior**
IN addition to linking to his slides and recording, a link to @ramrodo's blog post can also be included - https://layer5.io/blog/meshery/functional-testing-with-cypress-in-meshery-ui

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #1559 
Fixes #1724 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 17e0fa2fe9c7f0cccb65ab47f1dd3a8d2105aa22 at: https://6087d9fe0431bbfa80a0752b--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Is it possible to manually override the CSS for the block-component for the Meshery page only, and do few changes:
- Remove the line numbering
- Increase width a bit, or make it scrollable so that the complete command is visible.

**Comment by Nikhil-Ladha** [comment]
Also while you are there, adding a little shadow to that resources table might improve its looks and feel.
Screenshot from 2021-04-27 15-09-54

**Comment by l5io** [comment]
🚀 Preview for commit 879abb13e14dc8a25241f26d9b3d4db4ef868498 at: https://6088419e7cccdd9cbe9bcc26--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Looking pretty good.

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
