### PR TITLE
added the code section of the Text-Input (Sistent)

### LINKED ISSUE #5667: [sistent] Complete `code` section of Text-Input component
### Current Behavior

The code section is not completed under https://layer5.io/projects/sistent/components/text-input/code 

### Desired Behavior

Complete the code section of text input component , design can be found here: https://www.figma.com/design/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?node-id=2592-13759&t=mFkghFS6lrXZEMTg-0

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #5667 

**Notes for Reviewers**
I have added the basic ones , still i need to add the input with search and password functions .

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 19a2385b636595da321bd606425ab0a5da0251be at: https://66a646ac0aed3b32e786f4ea--layer5.netlify.app

**Comment by Ashparshp** [comment]
@narasimha-1511 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
@narasimha-1511, is there anything more to update, or is this good to go?

**Comment by Ashparshp** [comment]
@narasimha-1511, last ask if you're available, if we don't hear back from you then will be closing the PR and moving to next one.

**Pull request closed without merging**
