### PR TITLE
[NG] Add and move Layer5 logos

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**
Layer5 logo refresh for NG site

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I suspect that I have a file reference out of place, but am not sure. I'm receiving a number of these warnings on build:

```
warn You can't use childImageSharp together with feature-image.svg — use publicURL instead. The childImageSharp
portion of the query in this file will return null:
```

**Comment by Jashpatel1** [comment]
> I suspect that I have a file reference out of place, but am not sure. I'm receiving a number of these warnings on build:
> 
> ```
> warn You can't use childImageSharp together with feature-image.svg — use publicURL instead. The childImageSharp
> portion of the query in this file will return null:
> 
@leecalcote Its a common warning we are looking forward to resolve.

**Comment by leecalcote** [comment]
Oh, I see. Does visiting /blogs crash the local non server?

**Comment by Jashpatel1** [comment]
> Oh, I see. Does visiting /blogs crash the local non server?

Yes, we need to create redirect paths from /blogs to /blog .

**Comment by Tanuj22** [comment]
> I suspect that I have a file reference out of place, but am not sure. I'm receiving a number of these warnings on build:
> 
> ```
> warn You can't use childImageSharp together with feature-image.svg — use publicURL instead. The childImageSharp
> portion of the query in this file will return null:
> ```

This warning is due to the use of svgs with Gatsby Image. It is a workaround that was suggested in the gatsby docs. But going so introduced this warning.

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
