### PR TITLE
migrate to google-tag-manager

### PR DESCRIPTION
**Pull request by ayushthe1**
**Description**

This PR attempts to migrate the [layer5.io ](https://layer5.io/)site from using gtag.js to gtm.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 69389febde7a7c6c731a1252dd55becbe3018356 at: https://645369e8d08a2d690a2256dc--layer5.netlify.app

**Comment by ayushthe1** [comment]
@leecalcote I tried adding the adding the gtm script to `gatsby-browser.js` file but it wasn't loading properly. So ,i added it in the `_html.js` file .This method was more simple and working properly.

**Comment by vishalvivekm** [comment]
@ayushthe1 Let's discuss this on websites call. Add this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would :)

**Comment by leecalcote** [comment]
> @leecalcote I tried adding the gtm script to `gatsby-browser.js` file but it wasn't loading properly. So ,i added it in the `_html.js` file .This method was more simple and working properly.

@ayushthe1 I'm looking for a stronger justification.

**Comment by ayushthe1** [comment]
> > @leecalcote I tried adding the gtm script to `gatsby-browser.js` file but it wasn't loading properly. So ,i added it in the `_html.js` file .This method was more simple and working properly.
> 
> @ayushthe1 I'm looking for a stronger justification.

@leecalcote I will try again adding it to gatsby-browser.js file and see if it works.

**Comment by l5io** [comment]
🚀 Preview for commit 6ebec09efbf2ecaa9caef9dfaabb118d7deda835 at: https://6467d5ad0a7b5b0ac28a0593--layer5.netlify.app

**Review by Udit-takkar — COMMENTED** [review]
I didn't use the plugin to improve the web performance. unused JS has increased with this plugin

Screenshot 2023-05-20 at 9 21 40 PM

2) This is current live website

Screenshot 2023-05-20 at 9 27 12 PM

**Comment by l5io** [comment]
🚀 Preview for commit c1290b2d95f63ec38b6d5b806ecee2e010632f33 at: https://6469af513e59cb3ae34c3311--layer5.netlify.app

**Comment by ayushthe1** [comment]
@Udit-takkar Thanks for the suggestion .I have added the gtm script other way instead of using the plugin. Could you please review it. Below are the SS of lighthouse scores of original website and last deploy_url : 

Deploy_url :
image

Original website : 
image

**Comment by l5io** [comment]
🚀 Preview for commit 09ab99e9523eae2d622c9fcc686d716bd7d1faa4 at: https://646a01cee93dbc65a2267711--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9c3f6d6793ebd4849fd925cc9342b92e8e8648f2 at: https://646a2de84c260d7e5cba4aec--layer5.netlify.app

**Review by Udit-takkar — APPROVED** [review]
LGTM 
great work @ayushthe1

**Pull request merged**
