### PR TITLE
tooltip height increased

### LINKED ISSUE #3908: height of the viewer option and search bar is not same
### Desired Behavior

height of the viewer option and search bar can be made equal 

### Screenshots / Mockups

Screenshot 2023-03-06 at 3 40 35 PM

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #3908 

Screenshot 2023-03-08 at 9 35 45 AM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks. Too little margin between the elements, though.

**Comment by ShravaniAK** [comment]
yes you are right , i will increase the margin

**Comment by l5io** [comment]
🚀 Preview for commit f407d4337ab627dcb23bc7f1458521731fcb2df2 at: https://640812ce31e3c35a1244e42b--layer5.netlify.app

**Comment by sudhanshutech** [comment]
Good work @ShravaniAK,  but as you can see the icons inside these boxes are shifted too much upside so make it slight centered
image

**Comment by ShravaniAK** [comment]
@sudhanshutech please review it once now

**Comment by l5io** [comment]
🚀 Preview for commit cdbb84d37515dc20f89d8c296fdeaae7bcca57a5 at: https://6409d6157aa9ae007330ab61--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]
Looks good now

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Let's make the list/grid view consistent.
We are not showing thee sidebar after a certain resolution is Grid view and also have a `max-width` property defined for the search bar. Please check the stylesheet of grid view and update the list view CSS  accordingly

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha sorry but i was having a doubt , the issue for which i have raised a pr is solved right? now you are talking about some another improvment that needs to be done ? how will the sidebar affect the height of the tooltip ?

It's not about _just_ solving the issue.
Its about solving it the _right_ way :)

Coming to the sidebar, if you check the grid/list view for different resolutions you will notice that we are not showing thr sidebar after a certain resolution (I don't remember the value check it once), which allows us to have more space for the blog cards and ultimately for the search bar. Just take a look at the grid view CSS for search bar, view toggle and the sidebar and replicate that for list view.

**Comment by vishalvivekm** [comment]
@ShravaniAK let's hear from you about the further updates on this PR. did you incorporate maintainer @Nikhil-Ladha 's suggested changes?

**Comment by leecalcote** [comment]
PR abandoned.

**Comment by thisiskaransgit** [comment]
- Completed via #4289, thus closing this PR.

**Pull request closed without merging**
