### PR TITLE
[UI] Event DevConf '22 Image not properly aligned

### LINKED ISSUE #2622: [UI] Event DevConf '22 Image not properly aligned
**Description**
Event DevConf '22 Image is not properly aligned. 

image
image

---
**Expected Behavior**
Either this below new image could be replaced with the old image or resolution can be set using some CSS rule.
image

---
**Screenshots**

**Environment:**
- Host OS:  WSL
- Browser:  Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sidd-oo**
Signed-off-by: sidd-oo <sahoosiddharth3@gmail.com>

**Description**
Event DevConf '22 Image is now properly aligned inside the event card on the community dropdown and it is also changing the image for the DevConf'22 blog page.

This PR fixes #2622

**Notes for Reviewers**
As the old image was more like a banner, It was making it difficult to fit inside the Event Card and it was not a good idea to put CSS rules to fix the alignment of the image inside the card. So I completely replaced it with a new image.
**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sidd-oo** [comment]
@Abhijay007 Kindly review this PR and do share valuable feedback. Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit 7e8a91ff2a0af657fa8d2fc0ffab7cd60d87992a at: https://621df355facc34202e902095--layer5ng.netlify.app

**Review by Abhijay007 — APPROVED** [review]
@sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2626

**Comment by sidd-oo** [comment]
> @sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2622

I had a small discussion with @Chadha93 on slack yesterday. He told me, rather than changing the image if possible get image size(height and width) dynamically for the component so that the image gets fit to the card component accordingly, 

But turns out to be the [image](https://layer5.io/static/791af573338098749fee2d2850e97328/94e74/devconfcz-2022.webp) is actually quite long in width and small in height (It is more like a long rectangular banner). So in my opinion replacing the old image with a more square-looking image is a much better idea. 

Do share what you think about my approach? @Abhijay007 Thank you.

**Comment by Abhijay007** [comment]
> > @sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2622
> 
> I had a small discussion with @Chadha93 on slack yesterday. He told me, rather than changing the image if possible get image size(height and width) dynamically for the component so that the image gets fit to the card component accordingly,
> 
> But turns out to be the [image](https://layer5.io/static/791af573338098749fee2d2850e97328/94e74/devconfcz-2022.webp) is actually quite long in width and small in height (It is more like a long rectangular banner). So in my opinion replacing the old image with a more square-looking image is a much better idea.
> 
> Do share what you think about my approach? @Abhijay007 Thank you.

it is great @sidd-oo that you managed to fit in that image accordingly, and I also think that making images size dynamic so it will fix in the box is not quite possible here as we don't know which images are used by contributors, as most of the images have different aspect-ratio, to avoid this what I think that we can specify that "use images for events of this size (width and height) only " at the time of opening an issue which is related to events or blogs and doing that manually is not possible as not all the future contributors are not aware of my this comment :P 

so what we can do to resolve this is to specify that in the issue template itself, can you please look into templates if the specific temples for events exist or not? if yes you can edit that. 

PS: I am not sure about it, you might need approval from other contributors as well :)

**Comment by Abhijay007** [comment]
> > > @sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2622
> > 
> > 
> > I had a small discussion with @Chadha93 on slack yesterday. He told me, rather than changing the image if possible get image size(height and width) dynamically for the component so that the image gets fit to the card component accordingly,
> > But turns out to be the [image](https://layer5.io/static/791af573338098749fee2d2850e97328/94e74/devconfcz-2022.webp) is actually quite long in width and small in height (It is more like a long rectangular banner). So in my opinion replacing the old image with a more square-looking image is a much better idea.
> > Do share what you think about my approach? @Abhijay007 Thank you.
> 
> it is great @sidd-oo that you managed to fit in that image accordingly, and I also think that making images size dynamic so it will fix in the box is not quite possible here as we don't know which images are used by contributors, as most of the images have different aspect-ratio, to avoid this what I think that we can specify that "use images for events of this size (width and height) only " at the time of opening an issue which is related to events or blogs and doing that manually is not possible as not all the future contributors are not aware of my this comment :P
> 
> so what we can do to resolve this is to specify that in the issue template itself, can you please look into templates if the specific temples for events exist or not? if yes you can edit that.
> 
> PS: I am not sure about it, you might need approval from other contributors as well :)

edit : yes we have specific templates :)

**Review by Chadha93 — CHANGES_REQUESTED** [review]
@sidd-oo could you please change the image which also shows the year and dates for this? If not let's go with this only.

**Comment by sidd-oo** [comment]
> @sidd-oo could you please change the image which also shows the year and dates for this? If not let's go with this only.

Unfortunately, I don't have any image with dates on it. @Chadha93 Can we go with this image?

**Review by Abhijay007 — COMMENTED** [review]
@sidd-oo can you try to edit image and dates to it, it will be great if we are able to do that, you can ping me on slack if you need any assistance with that :)

**Comment by sidd-oo** [comment]
> @sidd-oo can you try to edit image and dates to it, it will be great if we are able to do that, you can ping me on slack if you need any assistance with that :)

Thanks, @Abhijay007
I changed the devconf'22 image which is having dates as well. It is looking something like this. 
image

**Comment by sidd-oo** [comment]
Kindly review these latest changes @Abhijay007 @Nikhil-Ladha

**Review by Abhijay007 — APPROVED** [review]
LGTM !! for the card view

**Comment by Abhijay007** [comment]
> > > @sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2622
> > 
> > 
> > I had a small discussion with @Chadha93 on slack yesterday. He told me, rather than changing the image if possible get image size(height and width) dynamically for the component so that the image gets fit to the card component accordingly,
> > But turns out to be the [image](https://layer5.io/static/791af573338098749fee2d2850e97328/94e74/devconfcz-2022.webp) is actually quite long in width and small in height (It is more like a long rectangular banner). So in my opinion replacing the old image with a more square-looking image is a much better idea.
> > Do share what you think about my approach? @Abhijay007 Thank you.
> 
> it is great @sidd-oo that you managed to fit in that image accordingly, and I also think that making images size dynamic so it will fix in the box is not quite possible here as we don't know which images are used by contributors, as most of the images have different aspect-ratio, to avoid this what I think that we can specify that "use images for events of this size (width and height) only " at the time of opening an issue which is related to events or blogs and doing that manually is not possible as not all the future contributors are not aware of my this comment :P
> 
> so what we can do to resolve this is to specify that in the issue template itself, can you please look into templates if the specific temples for events exist or not? if yes you can edit that.
> 
> PS: I am not sure about it, you might need approval from other contributors as well :)

look into this as well, and after the approval from other contributors try to implement this well by opening a new issue and PR :)

**Comment by l5io** [comment]
🚀 Preview for commit 262bd76b39cf546166e6a996f56684a07f975850 at: https://6224997ed049c2a428106a13--layer5ng.netlify.app

**Comment by sidd-oo** [comment]
> > > > @sidd-oo it LGTM for this card, but it will be great if we are able achieve what @Chadha93 suggested in issue #2622
> > > 
> > > 
> > > I had a small discussion with @Chadha93 on slack yesterday. He told me, rather than changing the image if possible get image size(height and width) dynamically for the component so that the image gets fit to the card component accordingly,
> > > But turns out to be the [image](https://layer5.io/static/791af573338098749fee2d2850e97328/94e74/devconfcz-2022.webp) is actually quite long in width and small in height (It is more like a long rectangular banner). So in my opinion replacing the old image with a more square-looking image is a much better idea.
> > > Do share what you think about my approach? @Abhijay007 Thank you.
> > 
> > 
> > it is great @sidd-oo that you managed to fit in that image accordingly, and I also think that making images size dynamic so it will fix in the box is not quite possible here as we don't know which images are used by contributors, as most of the images have different aspect-ratio, to avoid this what I think that we can specify that "use images for events of this size (width and height) only " at the time of opening an issue which is related to events or blogs and doing that manually is not possible as not all the future contributors are not aware of my this comment :P
> > so what we can do to resolve this is to specify that in the issue template itself, can you please look into templates if the specific temples for events exist or not? if yes you can edit that.
> > PS: I am not sure about it, you might need approval from other contributors as well :)
> 
> look into this as well, and after the approval from other contributors try to implement this by opening a new issue and PR :)

Sure

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
@sidd-oo the image is fine for card view but it got distorted for the blog, try to fix this 

image

**Comment by Abhijay007** [comment]
@sidd-oo the images are misaligned for every blog, it will be great if fix that and make it center aligned. it is a new issue, which is also reflected on the main deployed site as well

**Comment by sidd-oo** [comment]
> @sidd-oo the image is fine for card view but it got misaligned for the blog, try to fix this as well
> 
> image

Thanks, @Abhijay007 I created an issue (#2640) for addressing the above problem, It is something that is not happening with my code, so better we merge this PR (if they are fine).

**Review by Nikhil-Ladha — APPROVED** [review]
Let's move ahead with this. The alignment can be taken care of in a different issue, as both are not related.

**Comment by Nikhil-Ladha** [comment]
@Chadha93 , can you please re-review the changes and open the path to merge (you have 24hrs to do that :p).

**Review by Chadha93 — APPROVED** [review]
@sidd-oo Looks good, sorry for the delay in review, I was on leave till the weekend. Let's merge.

**Comment by sidd-oo** [comment]
> @sidd-oo Looks good, sorry for the delay in review, I was on leave till the weekend. Let's merge.

Thank you for merging. @Chadha93

**Pull request merged**
