### PR TITLE
Issue #1970 Fix

### LINKED ISSUE #1970: [README] Need to rectify `Slack badge` link
**Description**

Slack badge link got changed, i.e, `GitHub Link` itself.

**Expected Behavior**

Need rectification & update as:
```
https://slack.layer5.io
```

**Enviroment:**
- Host OS: Any
- Meshery Version: Any 
- Kubernetes Version: Any
- Browser: Any
--------
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Jayita10**
Signed-off-by: Jayita Pramanik <jayitapramanik2018@gmail.com>

**Fix Slack badge link**

This PR fixes #1970

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
hey, youll have to signoff your PR for the DCO check to pass.
Refer to this https://github.com/layer5io/layer5/pull/1972/checks?check_run_id=2995357486

**Comment by Jayita10** [comment]
Hi @warunicorn19 , I have made this changes with github editor. So For DCO check to pass do I need to clone the repo locally or there are any other way I miss?

**Comment by warunicorn19** [comment]
I dont think you were supposed to do it directly on the github editor.
@sayantan1413 all these changes to need to be done locally right?

**Comment by sayantan1413** [comment]
Yes @Jayita10 the changes are needed to be done locally and always sign off your commits to pass the DCO.

**Comment by leecalcote** [comment]
GitHub is a pain in the rump in this regard. There is a longstanding enhancement request for GH's web UI to support sign-offs. Given the nature of this update, I'll go ahead and manually override the sign off requirement. 👍 

Thanks for your help, @Jayita10. 😄

**Pull request merged**
