### PR TITLE
feat:fixed book_links

### LINKED ISSUE #4364: Wrong links for the Books
### Description

Currently two of the books under learn path of [service mesh bookS](https://layer5.io/learn/service-mesh-books) leads to the wrong urls.
The books are  [Enterprise path to Service mesh architecture edition 1](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures) and
[Enterprise path to service mesh architecture edition 2](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition)

They both are currently leading to the below link.
[this](https://www.nginx.com/blog/how-to-choose-a-service-mesh/?utm_source=calcote)
### Expected Behavior

Upon searching on the O Reilly Website I found that current links should be 
[edition-1](https://www.oreilly.com/library/view/the-enterprise-path/9781492041795/)
[edition-2](https://www.oreilly.com/library/view/the-enterprise-path/9781492089353/)
### Screenshots

| Original page  | Expected Page |
| ------------- | ------------- |
|image|image|
| image|image|  
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #4364 

**Notes for Reviewers**
As we were supposed to add a form to fix the incorrect links , The  UI did became a little disruptive after submission. However due to the guidance of @Savio629 , I did the following changes and the result are -:
image

Since we had disruptive UI issues only for the books in which forms have to be implemented , I added a new ```book-1``` class 
to them . With this class . we can add forms to new book in future without any disruptive UI changes.
Here is the full implementation:

https://github.com/layer5io/layer5/assets/59855919/d2589b22-d7de-4ff5-8c1e-3894baabfe88

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
I know the form height needs to be fixed , but will proceed further only after this design approval and community's valuable feedback

**Comment by l5io** [comment]
🚀 Preview for commit a0aa48b30f80a0c183b8e22d591603d438cf897a at: https://6495d5606e75365d009ba425--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 61df86d1c640b9d5234260dbed7ee507dbb118e3 at: https://6496ac595380a23e36cb96ca--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 70cf952afab80a6c32593cb56b6f288e84c4a220 at: https://6496b3a30342ec40e26dc476--layer5.netlify.app

**Comment by Savio629** [comment]
The changes looks good for mobile devices but I'm not sure if looks good for desktop
### For desktop the form submission looks good as well


### You can easily increase width for larger devices only by adding media query, but I feel it doesn't still look good


Is it possible to align the form components side by side for desktop like 

Get the Book | -
--- | ---
First Name |Last Name 
Email Address | Occupation / Title
Organization / Company / School  | What role best identifies you?

**Comment by Ghat0tkach** [comment]
> The changes looks good for mobile devices but I'm not sure if looks good for desktop
> ### For desktop the form submission looks good as well
> 
> 
> ### You can easily increase width for larger devices only by adding media query, but I feel it doesn't still look good
> 
> 
> Is it possible to align the form components side by side for desktop like 
> 
> Get the Book | -
> --- | ---
> First Name |Last Name 
> Email Address | Occupation / Title
> Organization / Company / School  | What role best identifies you? 

Thanks for your feedback @Savio629 , I beleive that is possible only if we create another form component specific for these book as we are using the already common-form component .

**Comment by Savio629** [comment]
// @Shivam-AfA @vishalvivekm @thisiskaransgit

**Comment by Savio629** [comment]
Let's get feedback in today's website meeting and make sure to complete it by today if possible...
@Ghat0tkach

**Comment by Ghat0tkach** [comment]
> Let's get feedback in today's website meeting and make sure to complete it by today if possible...
> @Ghat0tkach 

Yes will try my best to complete it by today after the valuable feedbacks.

**Comment by Savio629** [comment]
@Ghat0tkach @Deepak-Choudhary0 
So how are we wrapping this issue ?
I assumed you got some feedbacks from the meeting.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach @Deepak-Choudhary0 
> So how are we wrapping this issue ?
> I assumed you got some feedbacks from the meeting.

I think we need to have some form while we start on the parallax design as @avantikajain289 suggested. 

Can we merge it for the meantime? 
@leecalcote

**Comment by leecalcote** [comment]
Thanks, gents.

**Pull request merged**
