### PR TITLE
Fix #4586: Used white needle version of smp-dark.webp logo

### LINKED ISSUE #4586: Use white needle version of logo in dark-mode
### Description

The SMP logo on  [Homepage](https://layer5.io) has black needle.
Screenshot 2023-07-20 at 7 17 03 AM (1)

### Expected Behavior

Let's use the light version of the logo with the white needle for dark mode : <a href="https://github.com/layer5io/layer5/tree/master/src/assets/images/service-mesh-performance/icon/smp-light.svg"> smp-light.svg</a>

**Note**: Both versions of the logo must be present to support both light and dark modes on the site.

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ducksblock**
**Description**

This PR fixes #4586

**Notes for Reviewers**
- I edited the image to change it to a white needle to be used for the dark version of the logo.

**Signed commits**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d38a4e84beacda915b3277c3773344e05dda5999 at: https://64b97ff370c75d1c01388ba0--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
Logos are not to be edited.

**Comment by leecalcote** [comment]
Use the light version of the logo with the white needle. Both versions of the logo must be present to support both light and dark modes on the site.

@vishalvivekm it seems that the requirement is misunderstood. Please review the issue description for clarity. If it is crystal clear as-is, then please reassign the issue. If not, please clarify in the description of the issue.

**Comment by ducksblock** [comment]
> Use the light version of the logo with the white needle. Both versions of the logo must be present to support both light and dark modes on the site.
> 
> @vishalvivekm it seems that the requirement is misunderstood. Please review the issue description for clarity. If it is crystal clear as-is, then please reassign the issue. If not, please clarify in the description of the issue.

Oh I apologize! I'm new to this, should I close this pull request and create a new one for new changes?

**Comment by HetviSoni** [comment]
@ducksblock Please understand this issue has been assigned to someone else. SO do not create a pr for an issue if it is not assigned to you. 
There are many 'help wanted' issues. If you want to work on any of them then first ask the maintainers to assign you the issue. Work on an issue only after assignment. Also if you are new then go through [contributing guidelines](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) once.

**Comment by ducksblock** [comment]
@HetviSoni I apologize. Thanks, for the info.

**Comment by vishalvivekm** [comment]
> Use the light version of the logo with the white needle. Both versions of the logo must be present to support both light and dark modes on the site.
> 
> @vishalvivekm it seems that the requirement is misunderstood. Please review the issue description for clarity. If it is crystal clear as-is, then please reassign the issue. If not, please clarify in the description of the issue.

:heavy_check_mark:

**Pull request closed without merging**
