### PR TITLE
Created the member profile: Sayantan Bose

### LINKED ISSUE #1976: [Community] Member Profile: Sayantan Bose
**Current Behavior**

@sayantan1413  has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @sayantan1413  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sayantan1413 
- Twitter: sayanta33163352
- LinkedIn: sayantan-bose-14134a1a6
- Link to profile picture: https://drive.google.com/file/d/1HUr29lAPIapMH6V2Fpy0cyIA3c6nQpfu/view?usp=sharing
- About: A pre-final year student from Narula Institute of Technology, who is digging his way into the vast world of programming. I had joined Layer5 on May 2021 to put my hands into open-source and it has opened a wide world in front of me that had all the right things to upskill my knowledge and had helped me to be the best version of myself !!
- Location: West Bengal, India

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by debjani1413**
Signed-off-by: debjani1413 <deydebjani916@gmail.com>

**Description**
Created the member profile: Sayantan Bose

This PR fixes #1976 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 112554d408178bfd86a5ed85d7fae665928aa10d at: https://60e5e84f88c051c2b30e5476--layer5ng.netlify.app

**Comment by sayantan1413** [comment]
Hey @debjani1413 thanks for creating 😃 . I realized that I have some problem with my twitter handle. So would you mind to remove my twitter handle?

**Comment by debjani1413** [comment]
@sayantan1413 yes sure, definitely!

**Comment by l5io** [comment]
🚀 Preview for commit c8dcec3861213aff37d658ec432318db0357d393 at: https://60e5efc3a27ac1ca20f8d935--layer5ng.netlify.app

**Comment by debjani1413** [comment]
@sayantan1413 could you please check and review!

**Review by sayantan1413 — APPROVED** [review]
Hey @debjani1413 it looks great now.

**Review by Anita-ihuman — APPROVED** [review]
Great work @debjani1413, this looks nice

**Review by Tanuj22 — APPROVED** [review]
Thank you @debjani1413! Congrats @sayantan1413 🥳

**Pull request merged**
