### PR TITLE
metadata description fix

### LINKED ISSUE #5237: Duplicate meta descriptions on member profiles [SEO]
### Description
In all the member profiles **layer5.io** we have same meta description  **(not a good thing for SEO)**
You can access all member profiles here: https://layer5.io/community/members

image

### Expected Behavior
Add a unique description for all the member profile pages

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AjaxAueleke**
**Description**

This PR fixes #5237 

**Notes for Reviewers**
In the original implementation, the SEO component was configured to include only the title and image for each member. This setup limited the SEO effectiveness as it didn't provide unique descriptions for individual members.

With the proposed changes, the SEO component is now enhanced to include a unique description for each member, derived from their bio. This addition not only enriches the metadata for search engine optimization but also provides a more detailed context about each member on web pages.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 93412a6aacdf2b47ab209f466ff4b9225e96244d at: https://6590252d73b2166c73441c72--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@AjaxAueleke Thanks can you please add unique description to each member profile page

**Comment by AjaxAueleke** [comment]
@iArchitSharma The description is basically the bio of each member so I guess they'll be unique for each member. Sorry but if I am missing something do let me know.

Screenshot 2023-12-31 at 1 51 25 AM

Screenshot 2023-12-31 at 1 51 35 AM

**Comment by iArchitSharma** [comment]
Oh, great! I didn't notice that earlier

**Review by iArchitSharma — APPROVED** [review]
LGTM!

**Review by leecalcote — APPROVED** [review]
Thanks!

**Comment by leecalcote** [comment]
Thank you, @AjaxAueleke and @iArchitSharma 👍

**Pull request merged**
