### PR TITLE
fixed color from green to caribbean grean

### LINKED ISSUE #5250: The green color used for the headings on the [Collaborate](https://layer5.io/cloud-native-management/meshmap/collaborate) page needs to be changed to Caribbean green.
### Description
The green color used for the headings on the [Collaborate](https://layer5.io/cloud-native-management/meshmap/collaborate) page needs to be changed to Caribbean green. Specifically, the headings "Collaborate with your Team" and "Work from Anywhere" should use the lighter of the two greens.
### Expected Behavior
The headings "Collaborate with your Team" and "Work from Anywhere" on the Collaborate page should have their green color changed to Caribbean green.
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Somnath-sanu**
### This PR fixes #5250 

**Notes for Reviewers**
**Before**

Screenshot 2024-01-04 164158

**After**

Screenshot 2024-01-04 221951

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b85b79211d72f784a71636be3bc4ce24e993528d at: https://6596e75cf4cd5214397eb4e1--layer5.netlify.app

**Comment by Ashparshp** [comment]
Hi @Somnath-sanu,

I wanted to acknowledge the recent discussion in the meeting regarding the plan adjustment, particularly the proposed change to Caribbean Green.

I appreciate your efforts and the initiative taken. It's worth noting that there's already an existing pull request https://github.com/layer5io/layer5/pull/5253 addressing a similar change. While the current proposal may not be necessary due to the existing PR, your contribution and engagement in the process are commendable.

Moving forward, it might be beneficial for all contributors to ensure they are assigned to an issue before initiating work. This ensures better coordination and avoids duplication of efforts.

Thank you for your great work!

**Comment by Ashparshp** [comment]
a decision made during our recent meeting regarding the proposed plan adjustments. It was decided that the color change originally suggested as Caribbean Green will be modified to white.

**Comment by vishalvivekm** [comment]
> Hi @Somnath-sanu,
> 
> I wanted to acknowledge the recent discussion in the meeting regarding the plan adjustment, particularly the proposed change to Caribbean Green.
> 
> I appreciate your efforts and the initiative taken. It's worth noting that there's already an existing pull request #5253 addressing a similar change. While the current proposal may not be necessary due to the existing PR, your contribution and engagement in the process are commendable.
> 
> Moving forward, it might be beneficial for all contributors to ensure they are assigned to an issue before initiating work. This ensures better coordination and avoids duplication of efforts.
> 
> Thank you for your great work!

Thanks for this @Ashparshp :clap: 

@Somnath-sanu Find all the good-first and help-wanted issues here: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by ritiksaxena124** [comment]
Thank you for the contribution @Somnath-sanu. The issue is completed and closed already.

**Pull request closed without merging**
