### PR TITLE
Added LFX spring projects

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Description**

This PR fixes #

This PR adds LFX spring projects

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 40bdb1bf19d45e94d7d31eb582789efb02ded3cf at: https://65b509cb2ddcf99bc9abc367--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
This page is dated 2024, right? Why did we have descriptions for internships already? Has 2023 been archived into another file?

**Comment by vishalvivekm** [comment]
> This page is dated 2024, right? Why did we have descriptions for internships already? Has 2023 been archived into another file?

Yes, 2023 lfx program has been archived into lfx-2023 directory.
When @abhijeetgauravm created the folder for 2024, he updated the timeline retaining the description : https://github.com/layer5io/layer5/pull/5223

**Comment by leecalcote** [comment]
Thanks for being on top of this gentlemen.

**Comment by Yashsharma1911** [comment]
Thankyou @leecalcote and @vishalvivekm, @vishalvivekm as we will these internships published on LFX can you make sure we also update this document with those internships links it would be helpful

**Comment by vishalvivekm** [comment]
> Thankyou @leecalcote and @vishalvivekm, @vishalvivekm as we will have these internships published on LFX can you make sure we also update this page with those internships links it would be helpful

sure, once they're listed, I'll see it's done @Yashsharma1911

**Pull request merged**
