### PR TITLE
fix: changed route /projects to /products

### LINKED ISSUE #4610: [Site] Update the /projects routes to /products
### Description
Recently we switched from projects to products, and the routes (URL path) were not updated. 

### Expected Behavior
Please update all the /projects to /products in the site, and ensure sure by testing and visiting all the products/projects. 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Description**

This PR fixes #4610

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 069459b62b9797fdc00a11598cee96acd28f9d71 at: https://64c60ecceececd5a1d7cdb34--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
@Yana-Gupta 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta
> 
> Let's discuss it on the websites call. Please add this as an agenda item in the meeting minutes, if you would :)
> 
> https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

Sorry I won't be able to join the meet tomorrow.

**Review by Chadha93 — APPROVED** [review]
Thanks @Yana-Gupta. Good work. :1st_place_medal:

**Review by leecalcote — COMMENTED** [review]
@Chadha93, this PR broke all of the existing links to the projects pages. You must ensure that redirects are in place for site-external references and updates are made for all site-internal references. I am reverting this PR.

**Pull request merged**
