### PR TITLE
[NG] Added sort and filter options in SM Patterns table

### LINKED ISSUE #1386: [NG] Make Service Mesh Patterns table sortable and filterable
**Current Behavior**
The [table of service mesh patterns](https://layer5ng.netlify.app/books/service-mesh-patterns) has two columns, neither of which are sortable, nor filterable.

**Desired Behavior**
1. Users can click on the column name to sort each column, toggling between ascending and descending alphabetical order.
2. Users can filter on Category type. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by EmperorYP7**
**Description**

This PR fixes #1386 

**Notes for Reviewers**
Implemented sort and filter options using the predefined features of react-table.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Ooooh, exciting!

**Comment by leecalcote** [comment]
Good progress, @EmperorYP7. Early feedback below.
Screen Shot 2021-01-24 at 11 11 10 AM

**Comment by EmperorYP7** [comment]
@leecalcote Thank you for reviewing! Apologies for the delay, took a day off. Will fix it today. 😄

**Review by Jashpatel1 — COMMENTED** [review]
@EmperorYP7 Nice work here.
The responsiveness has caught up some issues for mobile views. Can you fix that up?

**Comment by EmperorYP7** [comment]
@Jashpatel1 Thanks for pointing it out! Fixed. :+1:

**Comment by Tanuj22** [comment]
@EmperorYP7 only the table should have overflow as scroll. Currently the entire is scrolling 
Screenshot from 2021-01-27 00-33-49

**Comment by EmperorYP7** [comment]
@Jashpatel1 I hope it is alright now. (tested on Safari and Chrome, everything looked fine to me)

**Comment by leecalcote** [comment]
Here’s a snapshot from Safari on an iPhone. 
06D91309-DD17-46F4-BF3B-F18B5C7F1C80

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Nice work here. Thanks @EmperorYP7

**Pull request merged**
