### PR TITLE
 Fix link to CODE OF CONDUCT

### PR DESCRIPTION
**Pull request by ealvarez968**
Signed-off-by: Eduardo Alvarez <ealvarez0896@gmail.com>

**Description**

The link to the code of conduct in the CONTRIBUTING.md file leads to a 404 page.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — APPROVED** [review]
Nice to point this out. Thanks @ealvarez968

**Review by Nikhil-Ladha — APPROVED** [review]
Nasty one!

**Comment by leecalcote** [comment]
Thank you, @ealvarez968 👍

**Comment by ealvarez968** [comment]
Always a pleasure!

**Pull request merged**
