### PR TITLE
kong is displaced with kuma

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
fixes #281

**Comment by gunjanmimo** [comment]
@leecalcote sir, may you take a look in this pr?

**Comment by leecalcote** [comment]
@gunjanmimo that would helpful, yes, please.

**Comment by gunjanmimo** [comment]
@leecalcote sir, I have added new kuma description

**Pull request merged**
