### PR TITLE
Footer update to align with design; Font update

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Tanuj22 the qanelas font isn't (wasn't) being applied in many places. I wasn't sure how to import the app.style.js into the Footer component, and so I'm using straight .css. What do you think about this approach?

**Comment by Nikhil-Ladha** [comment]
I think the app.style.js is automatically import d for all the pages. The reason for the correct font not being shown is because the correct tags might not be used for the same.

Like if you will see, currently we are showing the headings using just the link component which doesn't have the 'Qanelas Soft' font saved for it.

**Comment by Tanuj22** [comment]
> I think the app.style.js is automatically import d for all the pages. The reason for the correct font not being shown is because the correct tags might not be used for the same.
> 
> Like if you will see, currently we are showing the headings using just the link component which doesn't have the 'Qanelas Soft' font saved for it.

Yeah. So if we want to use 'Qanelas Soft' for a text that isn't headings we will have to set the font-style for that in its respective css.

**Comment by Nikhil-Ladha** [comment]
I think if we intend to use any particular font for any section we can use the appropriate tag which has that font associated with it.
Or assign font-family to the tags that should have a particular font-family globally, so as to keep a consistency across the site.

**Review by leecalcote — COMMENTED** [review]
Merging progress... will follow-up with fixes if font is still off.

**Pull request merged**
