### PR TITLE
Added wireframe for TOC

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added a wireframe for TOC, and migrated a chapter for the istio course.

This PR updates #1940 and updates #1841 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This initial skeleton will make it easy for others to follow.

**Comment by Nikhil-Ladha** [comment]
> This initial skeleton will make it easy for others to follow.

Yes! We could then have contributors migrate only the md files while the js work continues parallelly.

**Comment by l5io** [comment]
🚀 Preview for commit dc97ccfd8540af7cae483fb076e1c092fb981f9e at: https://60d22908486f0708506610bf--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
The link to check the progress: https://60d22908486f0708506610bf--layer5ng.netlify.app/learn-ng/mastering-meshery-istio/performance-of-service-mesh/istio/getting-started

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
