### PR TITLE
Fixed copy button position

### LINKED ISSUE #3095: Copy button overlaps with the terminal code
#### Description

the copy to clipboard button is overlapping the command in the terminal
https://layer5.io/service-mesh-management/meshery/getting-started
#### Expected Behavior

Add an copy button as shown in the terminal in the meshery docs.
Screenshot from 2022-08-19 17-02-50
this is what we are trying to achieve.

#### Screenshots

Screenshot from 2022-08-19 14-20-03

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sourav-sharma7**
Signed-off-by: sourav-sharma7 <souravsharma1321@gmail.com>

**Description**
Fixed copybutton position overlapping with the codeblock text
This PR fixes #3095 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 25fcde9254a0860953ee8b279d89f07d0569d154 at: https://630b2153b736cd1f76509bb7--layer5.netlify.app

**Review by YashKamboj — CHANGES_REQUESTED** [review]
Would you please add better styling to the button. it looks ugly @sourav-sharma7

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Hey @sourav-sharma7, let's iterate a little more here. ideally, the button should be inside the code-block itself, maybe making the code-block a little bigger would help. If you have trouble figuring out what colors to use where you can reference our brand-guide-https://layer5.io/brand. Good stuff!

**Comment by sourav-sharma7** [comment]
Screenshot from 2022-08-29 21-44-19
Thanks for the feedback @YashKamboj @warunicorn19  Is this what we are looking out for?

**Comment by warunicorn19** [comment]
Yup, please push these changes.

**Comment by l5io** [comment]
🚀 Preview for commit 8d98c32f2c610698094e8d03ff8186f55203539b at: https://6318736841798319df857f00--layer5.netlify.app

**Review by legendarykamal — APPROVED** [review]
LGTM :1st_place_medal:

**Comment by leecalcote** [comment]
I'm seeing this, which will need improvement: 

Screen Shot 2022-09-21 at 5 48 16 PM

**Comment by legendarykamal** [comment]
strange @leecalcote can you confirm if you are on safari or not as I am seeing this (chrome)
image

@sourav-sharma7 this can be further improved by making the bg code block bigger and adding a little padding to the copy button so that it is highlighted a bit.

**Comment by Nikhil-Ladha** [comment]
Any updates on this @sourav-sharma7 ?

**Comment by leecalcote** [comment]
I wonder if this issue has been separately fixed. @legendarykamal, would you be so kind as to confirm, closing this PR if you find this to be the case?

**Comment by legendarykamal** [comment]
yes this has been fixed by in the earlier PR https://github.com/layer5io/layer5/pull/3341 . 

Thank you @sourav-sharma7 for taking in the time to contribute in this area . You were so close I realise just the styling remained.

Let us close this PR in the meantime as the issue has been solved successfully,

**Pull request closed without merging**
