### PR TITLE
MeshMap Collaboration page - WIP

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shivam-AfA** [comment]
I have intentionally hidden a section from the page. Trying to think of something else that could take its place.

**Comment by l5io** [comment]
🚀 Preview for commit 289149acc7d1a7716ae231890a3430864bc55092 at: https://640bb8e007646c1321cc68e3--layer5.netlify.app

**Comment by Chadha93** [comment]
@Shivam-AfA  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit dff8836d081c226a749a4c95e32c97991bffc748 at: https://640f1106740f1a69d5738883--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 79903b3586ece1d56fa8cf908ba202678ccf276d at: https://640f7e8b8002bd0393d3caaa--layer5.netlify.app

**Pull request merged**
