### PR TITLE
Added quotes

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4678e67e7eafd58207a4bd1af5b9776b6c238e24 at: https://64243dfd1bea1d1a8521a957--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@leecalcote Do the quotes on the home page look fine?

**Comment by l5io** [comment]
🚀 Preview for commit 3b5a3696bcde26e43d6899e4fbaaba0d8e8fc914 at: https://6426e21255f73d29bd20d062--layer5.netlify.app

**Comment by leecalcote** [comment]
Great job on the quotes. Let's grab a third (and fourth?) for the page. And then more for each of the other pages.

**Pull request merged**
