### PR TITLE
[News] Kubernetes Evolves into an Enterprise Platform added

### PR DESCRIPTION
**Pull request by dDab-panda**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @dDab-panda. If you would, on future PRs, enter in the issue # that is fixed by the PR, so that GitHub will automatically close the corresponding issue. ✔️

**Comment by dDab-panda** [comment]
> Thank you, @dDab-panda. If you would, on future PRs, enter in the issue # that is fixed by the PR, so that GitHub will automatically close the corresponding issue.

Thank you for the information, didn't knew that. Will take care of them next time.

**Review by leecalcote — APPROVED** [review]
Looks good. Thank you, @dDab-panda 👍

**Comment by leecalcote** [comment]
> > Thank you, @dDab-panda. If you would, on future PRs, enter in the issue # that is fixed by the PR, so that GitHub will automatically close the corresponding issue.
> 
> Thank you for the information, didn't knew that. Will take care of them next time.

No sweat. You bet. Here's more info - https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Pull request merged**
