### PR TITLE
[NG] Update in landscape for linkerd

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Updated the `multi_cluster` support for Linkerd 2.x

This PR updates #1168 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote this one too 😅

**Comment by leecalcote** [comment]
@WLun001 does this look about right?

**Comment by WLun001** [comment]
Wow the site looks so nice, @leecalcote yeah

**Review by Jashpatel1 — APPROVED** [review]
Lokks good to me. Thanks @Nikhil-Ladha

**Pull request merged**
