### PR TITLE
Aligned Social Media logos with layer 5 logo

### LINKED ISSUE #3274: Footer: Social media logos are not aligned with the layer 5 logo.
#### Current Behavior
Social media logos are not aligned with the layer 5 logo.
Screenshot 2022-10-07 123820

#### Desired Behavior
Screenshot 2022-10-07 123911

#### Acceptance Tests

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sandeepB3**
Signed-off-by: Sandeep Pillai <sandeepxpillai@gmail.com>

**Description**
Solved issue #3274 by adding margin-top: 0.4rem to align the social media logos with layer 5 logo 

This PR fixes #3274 

**Notes for Reviewers**

Before:
Screenshot 2022-10-07 at 10 30 11 PM

After:
Screenshot 2022-10-07 at 10 12 59 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit de7f1b76f7b5ace5ec04fd8afa8b56610045c06b at: https://634099a3d6cd7b0cbff49292--layer5.netlify.app

**Comment by sandeepB3** [comment]
The preview looks fine to me.

**Comment by sandeepB3** [comment]
Should I do anything else for the changes to be merged ??

**Comment by Krishna2323** [comment]
You were assigned for this?
I my opinion, there was no need to add margin-top. You just had to add 'align-item: center' to the div containing the Layer5 logo and other social media logos.

**Comment by sandeepB3** [comment]
Hey Krishna, I am new to open source contribution I didn't knew you had to be assigned to make a contribution, sorry about that. Can I be assigned this?
And yes I made the changes with 'alignItems: center' it is better now.   
Screenshot 2022-10-08 at 12 13 57 PM

**Code:**
Screenshot 2022-10-08 at 12 14 09 PM

**Comment by sandeepB3** [comment]
Changed the inline styling and added align-items to footer.style.js
Works the same.   

Screenshot 2022-10-08 at 12 30 47 PM

**Comment by sandeepB3** [comment]
I have made the required above changes

**Result:**
Screenshot 2022-10-08 at 12 39 07 PM

**Please Verify!**

**Comment by Krishna2323** [comment]
@sandeepB3, Pls verify if anyone is assigned already to the issue or not before contributing. The issue you are working on is already assigned to someone. I am also new to open source. The maintainers can only assign someone.
Try finding some new issues or work on the issues that are open.
Your code looks good to me but it can't be merged.

**Comment by sandeepB3** [comment]
Got it!! Thankyouu

**Comment by Nikhil-Ladha** [comment]
A very good pointer from @Krishna2323 .
@sandeepB3 if you are interested to work on any issue, then please comment on the issue and request for assignment and ONLY if the issue is assigned to you, submit a PR for it. It helps avoid unnecessary confusion and discrepancies among contributors. PR looks good, but I will give priority to the actual assignee to make a PR for this.

**Comment by sandeepB3** [comment]
Hey, I am really sorry about that. I have recently started open source contribution and I wasn't aware of the assignment system. It is quite fun when a PR you make is merged, that's why I made the PR. In case the assigned person isn't doing the work please do consider merging my PR. Thank you!

**Comment by sandeepB3** [comment]
Is this issue still not resolved??

**Comment by l5io** [comment]
🚀 Preview for commit 3f821bd0157abf4d368c5bb83d17699d883332db at: https://6347f3729546691beee2f37f--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
