### PR TITLE
Added victoria-nduka profile 

### LINKED ISSUE #5160: [Community] Member Profile: Victoria Nduka
**Current Behavior**

@nwanduka  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @nwanduka  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @nwanduka
- Twitter: [nwa_nduka](https://twitter.com/nwa_nduka)
- LinkedIn:  [in/victorianduka](https://www.linkedin.com/in/victorianduka/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by balagowda**
**Description**

This PR fixes #5160 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2180761437f96fad4db6fad1ddc43b6e8b503316 at: https://6566f314f7136e36cd695902--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
You might like to review it @nwanduka

**Comment by nwanduka** [comment]
Excellent work @balagowda

**Review by nwanduka — APPROVED** [review]
LGTM

**Comment by abhijeetgauravm** [comment]
> LGTM

// @Mohith234 @ritiksaxena124 @sudhanshutech

**Comment by vishalvivekm** [comment]
## Yay! 🎈 @nwanduka 😎

**Pull request merged**
