### PR TITLE
Added "Solutions" item on navigation bar

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shivam-AfA** [comment]
@leecalcote I have replaced the landscape item with the solutions item and also added sub-items. Currently the solutions button redirects to the Projects page. There was empty space beside the drop-down items, so I placed a link to the meshery playground there. 

All-in-all the changes look like this:

image

**Comment by l5io** [comment]
🚀 Preview for commit 20c01624e3b997c30b8822aeb87cd2fe1e39e76c at: https://641f0078dd17fa3e608e9431--layer5.netlify.app

**Comment by Chadha93** [comment]
@Shivam-AfA  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by l5io** [comment]
🚀 Preview for commit f86e606a55eccce2628cffd4aed9b2ba1d86f99b at: https://6423d23a6dac1358458115ec--layer5.netlify.app

**Pull request merged**
