### PR TITLE
Updated Integration Icons For Dark Theme

### LINKED ISSUE #3182: Integrations: Dark-mode friendly
#### Current Behavior
The integrations honeycomb only has one color-mode: light.

#### Desired Behavior
Make the integrations grid dark-mode friendly.

#### Screenshots / Mockups
Conflicting dark-mode for the site with light-mode for the integrations:

Screen Shot 2022-09-20 at 8 34 13 AM

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**

PR fixes #3182

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5d25990773bd0d4a81aba83da1e749c2e25510be at: https://633b4825562fe636549ce0e1--layer5.netlify.app

**Comment by Harshit-Dandriyal** [comment]
Screenshot from 2022-10-04 02-19-47
 minikube seems left @sahilsuman933 .

**Comment by sahilsuman933** [comment]
I wasn't able to find a white logo for the Minikube. So I raised an issue to make one https://github.com/layer5io/layer5/issues/3257

@Harshit-Dandriyal

**Comment by Harshit-Dandriyal** [comment]
Good work then @sahilsuman933

**Review by leecalcote — APPROVED** [review]
Thank You, @sahilsuman933

**Pull request merged**
