### PR TITLE
Added member profile for Debopriya Bhattacharjee

### LINKED ISSUE #2064: [Community] Member Profile: Debopriya Bhattacharjee
**Current Behavior**

@debo19  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @debo19  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @debo19 (https://github.com/debo19)
- Twitter: https://twitter.com/debopriyabh19
- LinkedIn: Debopriya Bhattacharjee (https://www.linkedin.com/in/debopriya-bhattacharjee-660861211)
- Link to profile picture: https://drive.google.com/file/d/1ARAfzko8yyhSmhXivnRKUx-5ZlcaYXWN/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**
Added Member profile for Debopriya Bhattacharjee

This PR fixes #2064 

**Notes for Reviewers**
Let me know if there are any other changes we can.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 90291f722bdc8b4034940c321ac643f4fb9974d7 at: https://610e575cea2a79dea79b3415--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM!, Thanks @NikhilSharma03

**Review by debo19 — APPROVED** [review]
LGTM, thanks a lot @NikhilSharma03

**Review by Tanuj22 — APPROVED** [review]
Thank you @NikhilSharma03. Congrats @debo19 :tada:

**Pull request merged**
