### PR TITLE
Award badges

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR adds badges to select members' profiles

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@vishalvivekm :rocket: . Thanks for this. Please also ensure this PR is reviewed and approved by everyone who is awarded a badge.

**Comment by vishalvivekm** [comment]
## Congratulations 🎊
@Aisuko @avantikajain289  @ritiksaxena124 @Abhishek-kumar09 @Yashsharma1911 @sudhanshutech @theBeginner86 @hershd23  @MUzairS15 @kayceeDev🎈

Please take a look at the badges on your [profiles](https://64a6d23a636ca13a39edaf12--layer5.netlify.app/community/members).
Thanks for your contributions to the Layer5 community!  5-light-small

**Review by ritiksaxena124 — APPROVED** [review]

**Review by sudhanshutech — APPROVED** [review]

**Review by Aisuko — APPROVED** [review]
approved

**Review by MUzairS15 — APPROVED** [review]

**Comment by samyakshah3008** [comment]
@vishalvivekm  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by theBeginner86 — APPROVED** [review]

**Review by Yashsharma1911 — APPROVED** [review]

**Review by Abhishek-kumar09 — APPROVED** [review]
Thanks, LGTM 🎈

**Review by Chadha93 — APPROVED** [review]

**Comment by Chadha93** [comment]
@vishalvivekm Merge conflicts...

**Comment by l5io** [comment]
🚀 Preview for commit d37fbba66d21f01cd73d2ff727dc6fc8577f08ad at: https://64b522dd85054d0e470ef74c--layer5.netlify.app

**Comment by vishalvivekm** [comment]
> @vishalvivekm Merge conflicts...

Resolved @Chadha93

**Pull request merged**
