### PR TITLE
fixed category slider in integrations page

### LINKED ISSUE #5269: Integration categories disapper on clearing search text
### Description

On the integrations page
LINK: https://layer5.io/cloud-native-management/meshery/integrations

When we enter any search text and clear it by pressing the backspace the category slider disappers leaving empty space behind with just the arrows.
This issue is in both mobile and desktop screen.

### Expected Behavior

category slider should stay at its place after clearing the search text.
### Screenshots

Screenshot 2024-01-05 at 9 58 08 PM

### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by prabhjeevnijjar**
**Description**

This PR fixes #5269 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2d68a6e55005e254d42609d80c2df6d58148a936 at: https://659837064804832d8bfabe93--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
@prabhjeevnijjar thank you.

Is there anything that we can do about this? This happens in Safari (and maybe other browsers).

Screenshot 2024-01-05 at 11 54 56 AM

**Comment by prabhjeevnijjar** [comment]
> @prabhjeevnijjar, we have another issue with respect to maintaining aspect ration of the icons. I wonder if you might have a look into this as well. Screenshot from Chrome.
> 
> Screenshot 2024-01-05 at 11 57 47 AM

Just checked, Logo is too wide hence the compression
1. We can change the logo (less wide preferably)
2. I can use some css to make height smaller
 - conditionally for this particular logo
 - across all logos
 
 let me know which one i go with.

**Comment by prabhjeevnijjar** [comment]
> @prabhjeevnijjar thank you.
> 
> Is there anything that we can do about this? This happens in Safari (and maybe other browsers).
> 
> Screenshot 2024-01-05 at 11 54 56 AM

Its safari only problem 😆
Work fine with chrome, brave

**Comment by vishalvivekm** [comment]
@prabhjeevnijjar 
Today, we've our weekly Websites meeting at 6:30 PM IST : https://meet.layer5.io/websites.
Let's get feedback on your work in today's call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
@prabhjeevnijjar, while we won't be able to change this logo, we can use content-fit or something similar to control it's display. Let me know if you get stuck and can't quite figure this one out.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
We can merge your progress, if you open up a new issue to track the other item discussed in the comments.

**Comment by prabhjeevnijjar** [comment]
Sure

**Comment by prabhjeevnijjar** [comment]
> We can merge your progress, if you open up a new issue to track the other item discussed in the comments.
@leecalcote 
Created a new Issue: https://github.com/layer5io/layer5/issues/5307

**Comment by prabhjeevnijjar** [comment]
> We can merge your progress, if you open up a new issue to track the other item discussed in the comments.

Created new issue for stretching of some logos: https://github.com/layer5io/layer5/issues/5308

**Review by vishalvivekm — APPROVED** [review]

**Comment by vishalvivekm** [comment]
Thank you @prabhjeevnijjar

**Pull request merged**
