### PR TITLE
Added margin from the top of the image on the page: layer5.io/community/newcomers

### LINKED ISSUE #3462: There should be a margin from the top of the image on the page: layer5.io/community/newcomers
#### Description

There should be a margin from the top of the image on the page: layer5.io/community/newcomers
#### Page Link:

[link](https://layer5.io/community/newcomers)

#### Screenshots

Before
image
After

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Added margin from the top of the image on the page: layer5.io/community/newcomers

This PR fixes #3462 

**Notes for Reviewers**
Before 
image

Now
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cd3949141e0aadfc70317a8e408dee8d264c1249 at: https://6378a370b5af5420c8eab881--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d1a4150f387eba5b5c5a4a6b409b99e1e8aabe3a at: https://63790a9982dd307d3ea34f8a--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
@Harshit-Dandriyal Gentle Reminder 😄

**Review by leecalcote — APPROVED** [review]
thank you, gents. 👍

**Pull request merged**
