### PR TITLE
Add community member profile

### LINKED ISSUE #3748: [Community] Member Profile: Ayush Sharma
**Current Behavior**

@ayushthe1 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ayushthe1  as a contributor and community member by creating a profile on https://layer5.io/community/members.

Profile pic : [link](https://drive.google.com/file/d/1ieF3vfft-wg6mq0zRl8WdpZ9IUxGq_pN/view?usp=share_link)
 2.  GitHub : [link](https://github.com/ayushthe1)
 3.  Twitter : [link](https://twitter.com/ayushthe5)
 4.  LinkedIn : [link](https://www.linkedin.com/in/ayushthe1/)
 5.  Short bio : "A curious learner who loves to collaborate"
 6.  Location : Bengaluru , India
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
Signed-off-by: Sheikh-JamirAlam <alamjamir15@gmail.com>

**Description**
Added community member profile.

This PR fixes #3748 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 37e2c1fd1cc6dc244b0c12baabb73d2a176cfd90 at: https://63ea360ad26b540dbd849421--layer5.netlify.app

**Comment by UtkarshMishra12** [comment]
Hey @Sheikh-JamirAlam, I appreciate your enthusiasm for contributing to the community 😄 . But please wait before you make any PR, wait for someone to get the issue assigned to you. This time I'm considering this PR but please keep this in mind for your future PRs.

**Comment by Sheikh-JamirAlam** [comment]
@UtkarshMishra12 Got it. Sorry for causing inconvenience.

**Comment by Sheikh-JamirAlam** [comment]
@ayushthe1 Done.

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @Sheikh-JamirAlam 🚀🥇

**Pull request merged**
