### PR TITLE
Add spacing above the heading

### LINKED ISSUE #5648: Add spacing above the heading
### Current Behavior

Open Source Internship Program heading with it's title needs alignment.

Screenshot from 2024-07-08 04-31-36

### Desired Behavior

Heading should have some space on top as well as on bottom (check with headings of other pages like https://layer5.io/projects)

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by r-kundan**
**Description**

This PR fixes #5648

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1919cfa7f68faef74a89e7e3e0fc7d3e249b37a4 at: https://668c20c5d681547e79ca73ef--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b038cd8715592a22aa53a3dbc330301a0f1881fc at: https://668cdaea27123c42136a5348--layer5.netlify.app

**Review by Ashparshp — APPROVED** [review]
Hi @r-kundan,

LGTM!! Thank you for making the changes. Apologies for the oversight on the issue assignments. I've noticed your consistent interest in working on various issues. Unfortunately, assignments are made in chronological order, which sometimes results in issues already being assigned. We greatly appreciate your participation and contributions to the project. 

Thanks again!

**Review by Ashparshp — CHANGES_REQUESTED** [review]
Also, please add some space above the top heading. Do not add space between "Open Source Internship Programs" and "Build Your Career at Layer5"—definitely not that much.

**Comment by vishalvivekm** [comment]
@r-kundan 
Thank you for your contribution.
Let's discuss this on Websites' call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit 6d1e38bf24d12350da6404bd1c1180f48412b726 at: https://66950145c84a200092beda48--layer5.netlify.app

**Review by Muhammed-Moinuddin — COMMENTED** [review]
@r-kundan changes in file i.e. (src/reusecore/PageHeader/pageHeader.style.js) is also impacting another page i.e. (https://layer5.io/projects).
So, we need to make changes in a way that both pages look good. Let's discuss via slack.

**Comment by leecalcote** [comment]
Keep at it, @r-kundan. Almost there...

**Pull request closed without merging**
