### PR TITLE
fix svgs for checks and crosses

### LINKED ISSUE #3321: Make check, half check, cross images consistent across all platforms
**Current Behavior**

The check icons aren't consistent across all platforms. Below are the 3 places I could find there occurrence in. 

image
image
image

**Desired Behavior**
The check, half-check and cross icons should follow the same pattern across all areas; same icon-type and colors everywhere.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
Signed-off-by: Gaganpreet Kaur Kalsi <gagansinghkalsi4126@gmail.com>

**Description**
The icons for compliance checks aren't consistent across all areas of application. This PR contains some changes to svgs to make all check icons consistent across all places.

This PR fixes #3321 

<details>
<summary><h4>Screenshots of current UI</h4></summary>
image
image
image
image
</details>
<details>
<summary><h4>Screenshots of proposed UI changes</h4></summary>
image
image
image
image
</details>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5e54d54ccc3cf5234789509934412e9efa468e5b at: https://634c0a83735def7e6d36ea08--layer5.netlify.app

**Comment by l5io** [comment]
Yay! This is nice to see.

**Comment by l5io** [comment]
@YashKamboj any feedback to offer?

**Comment by l5io** [comment]
🚀 Preview for commit b3dbd6e153767f9a52ea18e3ff93d65a9d587441 at: https://634dbbcefc207a2cec16f5b1--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
> @YashKamboj any feedback to offer?

Someone seems to be hacking around with the bot account, huh? 👀

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by GaganpreetKaurKalsi** [comment]
> > @YashKamboj any feedback to offer?
> 
> Someone seems to be hacking around with the bot account, huh? 👀

Thought the bot was artificially intelligent😅

**Comment by leecalcote** [comment]
Now, just who could be masquerading here?

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi are you adept with Adobe Illustrator?

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi are you adept with Adobe Illustrator?

Ah never worked with that. Will soon, someday.

**Pull request merged**
