### PR TITLE
Update kanvas_banner.js

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@vishalvivekm @Aviral0702 please fix the broken build.

**Review by Aviral0702 — APPROVED** [review]
LGTM!

**Comment by vishalvivekm** [comment]
> @vishalvivekm @Aviral0702 please fix the broken build.

fixed.

**Comment by l5io** [comment]
🚀 Preview for commit dd6d955bc2ce2f8940d3c27186dd9edce92e3645 at: https://66e2b7f6b7b725366fa8c385--layer5.netlify.app

**Comment by leecalcote** [comment]
> > @vishalvivekm @Aviral0702 please fix the broken build.
> 
> fixed.

Nice work, @vishalvivekm. 🎉  You certainly know your way around these intertwined systems. 👏

**Pull request merged**
