### PR TITLE
Add search to integrations

### LINKED ISSUE #3417: [Integrations] Add Search feature to integrations
#### Current Behavior
We don't allow users to search for a specific integration they are looking for. 

#### Desired Behavior
Add a search feature to the integrations grid on both the Home page as well as the All Integrations page. Use the existing Search component used in Blogs and Resources.

#### Implementation
The search should match the title/name of each integration.

#### Acceptance Tests

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kayceeDev**
**Description**

This PR fixes #3417 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cb758aa4e5a5af72cc2649abd8995d821c661c06 at: https://636ca182fe93f9532ef70986--layer5.netlify.app

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
Looks good! Great work done 👍, @kayceeDev . 
Just 2 pointers from my side - 
- As we are using debounce searching, we aren't using the search button provided. Maybe we can remove the `pointer-event` on the button as it doesn't have any click function. Just make the search-icon look like an icon not a button that can be clicked.
- When we enter an alphabet into the search-bar, the first time, the search bar and the searched integrations go outside the view area. How about keeping the search-bar in view at all times?? Is that possible?

What say @leecalcote ?

**Comment by sahilsuman933** [comment]
Could you please remove the search bar from the Integration section on the homepage? 

Also, I agree with @GaganpreetKaurKalsi about removing the pointer event from the search button. 

Other than that, it looks good to me.  @kayceeDev

**Comment by kayceeDev** [comment]
> Could you please remove the search bar from the Integration section on the homepage?
> 
> Also, I agree with @GaganpreetKaurKalsi about removing the pointer event from the search button.
> 
> Other than that, it looks good to me. @kayceeDev

I will definitely look into all the feedback and adjust the changes. Thank you @sahilsuman933 @GaganpreetKaurKalsi

**Comment by l5io** [comment]
🚀 Preview for commit 86cad85145dc527da836707b497b339a4ad70bd8 at: https://63723a5f075a5f3758d40aea--layer5.netlify.app

**Comment by leecalcote** [comment]
@kayceeDev ping when the search is moved above the category filters.

**Comment by leecalcote** [comment]
Search on the home page is desired. This should be incorporated into the [single row category filter](https://github.com/layer5io/layer5/issues/3416). See @gbotesco's designs, which can be updated to include search.

**Comment by kayceeDev** [comment]
> Search on the home page is desired. This should be incorporated into the [single row category filter](https://github.com/layer5io/layer5/issues/3416). See @gbotesco's designs, which can be updated to include search.

I think it's better to leave the search on just the integration page.  This is because we will have just a few integrations on the homepage and users are likely not to need a search. We need to somehow make them go to the integrations page to see all integrations and then they can perform a search there.

**Comment by l5io** [comment]
🚀 Preview for commit 37f27b51c08e5e359a4bbedaea06f0a6d54dd749 at: https://637495b3bde7451eb532c4d8--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Great work, @kayceeDev. 👏 

Insightful and helpful feedback, @GaganpreetKaurKalsi @sahilsuman933 🥇

**Pull request merged**
