### PR TITLE
padding of menu items

### LINKED ISSUE #4669: [Mega Menu] Fine-tune responsive fitting of menu items
### Description
Menu items are somewhat difficult to read on smaller width desktop screens.

### Expected Behavior
Screenshot 2023-07-31 at 2 40 43 PM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShivangRawat30**
**Description**

This PR fixes #4669 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a195efb1fd6052167a691e7c32daeff57444d763 at: https://64c9500266565d14a5a65415--layer5.netlify.app

**Review by DarrenDsouza7273 — APPROVED** [review]
Good Work @ShivangRawat30 LGTM

**Review by Mohith234 — APPROVED** [review]
Looks good to me @ShivangRawat30 🚀

**Comment by Ghat0tkach** [comment]
hey @ShivangRawat30 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
@ShivangRawat30, thanks much, but the enhancement is only required in the solutions' mega menu, this will affect other navigation sections too which already have an adequate amount of horizontal space.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @ShivangRawat30, thanks for this fix. Please incorporate @thisiskaransgit's feedback, if you would. Let us know when ready for re-review:

> @ShivangRawat30, thanks much, but the enhancement is only required in the solutions' mega menu, this will affect other navigation sections too which already have an adequate amount of horizontal space.

**Comment by Chadha93** [comment]
@ShivangRawat30, Still here? Let's close this PR if feedback is not incorporated by Friday.

**Comment by l5io** [comment]
🚀 Preview for commit e1b293e82959dc81d12031a5f8dbaa6b246f7482 at: https://64e647070b8d1302fb0b932f--layer5.netlify.app

**Comment by Chadha93** [comment]
> @ShivangRawat30, Still here? Let's close this PR if feedback is not incorporated by Friday.

@ShivangRawat30, Closing this PR, as the requested feedback was not incorporated.

**Pull request closed without merging**
