### PR TITLE
[Learn] Final updates to learn-ng

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Made the updates as discussed in the last Websites Call.
Only, textual updates need to be done by Lee wherever necessary.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 293fbe329df8919e2645f15b71cc41a570754a3a at: https://616ac57774687f3b7917aec5--layer5ng.netlify.app

**Comment by leecalcote** [comment]
The /learn section is looking good, although, there doesn't seem to be a link to /learn/learning-paths

**Comment by Nikhil-Ladha** [comment]
> The /learn section is looking good, although, there doesn't seem to be a link to /learn/learning-paths

It is in the navbar. We don't have links to individual page for any of the section in the /learn page itself. Or do we? 🤔

**Comment by Nikhil-Ladha** [comment]
Good to merge @leecalcote . Updated the position of `learning-paths` on the learn page and added the button to go to individual pages for each section like `Checkout all service mesh books` and `Checkout all learning paths`

**Comment by l5io** [comment]
🚀 Preview for commit 8f79c7e0919a2bc81e0c90f3e68192837d2d4497 at: https://616ff1b882844fed56421c50--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Merging the PR....If any changes need to be done, let me know.

**Pull request merged**
