### PR TITLE
[Blog] Introducing Learning Paths

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description*
Fixed the issue from the previous PR which was causing the build to fail and added the learning paths blog. 
This PR fixes #

**Notes for Reviewers**
Styling still needs to be fixed. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by adithyaakrishna — APPROVED** [review]

**Comment by leecalcote** [comment]
The Learning Paths blog needs reviewed (needs a few corrections and a little more forward-looking substance).

**Comment by adithyaakrishna** [comment]
@warunicorn19 Approved this as the only thing changed when compared to the closed PR was the file name

**Comment by warunicorn19** [comment]
Yes @leecalcote i agree, i just made the PR as an initial commit. Took me like 45mins to figure out what was bug that was causing the build to fail🥲.

**Comment by l5io** [comment]
🚀 Preview for commit a2588aceb74e8c5c36f9ca0077ee5581b76fb03e at: https://61940d5b06a47c00767f9eca--layer5ng.netlify.app

**Pull request closed without merging**
