### PR TITLE
added documentation of Link Component

### PR DESCRIPTION
**Pull request by NishantSinghhhhh**
Description

Component Name : Link component present in Sistent component folder ,

This PR addresses various enhancements and features, including:

Documentation : I have written Documentation for the Link Component Used in Sistent Repository
Link Variants: Added different styles for links, including underlined and colored versions to enhance navigation and visibility.

Security Practices: Documented best practices for using links with target="_blank", highlighting the importance of rel="noopener" and rel="noreferrer" attributes to improve security.

Notes for Reviewers

Please pay special attention to the documentation and security notes for external links. Feedback on these changes would be greatly appreciated.

preview:
Screenshot 2024-10-20 235214

[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

 Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@NishantSinghhhhh  Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by NishantSinghhhhh** [comment]
@vishalvivekm  Sir I am not able to edit the doc that you put in your previous comment ,thus I am not able to add my name in it

**Comment by NishantSinghhhhh** [comment]
@nebula-aac  https://github.com/layer5io/layer5/pull/6015 , I have created 1 more PR that passes all the test except the kanvas test , can you please review it
Screenshot 2024-10-21 124816

**Comment by vishalvivekm** [comment]
duplicate of https://github.com/layer5io/layer5/pull/6008

**Pull request closed without merging**
