### PR TITLE
Updated the text below learn heading

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description** Updated the text below learn heading on learn homepage
Before

Screenshot (17)

After

Screenshot (19)
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit cbc66f6a6cd2a825acbd30fc8d41400453236bf8 at: https://619897b554e726ad5aa68691--layer5ng.netlify.app

**Comment by vedant-kakde** [comment]
image

@YashKamboj Please check mobile view of website. I think we shouldn't add side margins in mobile site.

**Comment by YashKamboj** [comment]
@vedant-kakde
Screenshot (29)

does this look okay.

**Comment by vedant-kakde** [comment]
> @vedant-kakde Screenshot (29)
> 
> does this look okay.

Yes, now it looks great. 👍🏻

**Comment by l5io** [comment]
🚀 Preview for commit e81e7fc9f0a7e41179ccc1667196478a941cd558 at: https://6198a0d2f0ab4dc826325341--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5fedde220c11f09830d706b22ace98f9caa6bf99 at: https://6198a87f8cdcbbc253abe5be--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5675cb4cee63d858b35a20f16320f035551d0c4d at: https://6198ac8db4e38ee3bc979ce0--layer5ng.netlify.app

**Comment by vedant-kakde** [comment]
@YashKamboj  Please sign off your commits.

**Comment by YashKamboj** [comment]
@vedant-kakde dco is not working did the  force many times but not working even did the first commit with -s but still dco is failed

**Comment by l5io** [comment]
🚀 Preview for commit 7eece381712fba4508ad9939d7bac5c2d7bdde2e at: https://6198ce19be4542f00242b362--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
@vedant-kakde I tried so many times but still unable to do dco, even tried another commit with small change but still failed in dco, should i make another pr.

**Comment by vedant-kakde** [comment]
image

@YashKamboj  click here on details and follow those steps.

**Comment by YashKamboj** [comment]
@vedant-kakde did but still

**Comment by l5io** [comment]
🚀 Preview for commit 268a361830e37c29315acd3fb87c0872bff38699 at: https://6198d20d5c958408cde120b4--layer5ng.netlify.app

**Comment by vedant-kakde** [comment]
@YashKamboj try following those steps without doing any changes.

**Comment by YashKamboj** [comment]
@vedant-kakde did but  still same, tried many times

**Comment by vedant-kakde** [comment]
@warunicorn19 please look into this

**Comment by YashKamboj** [comment]
@vedant-kakde should i make another pr

**Comment by vedant-kakde** [comment]
No, please wait

**Comment by l5io** [comment]
🚀 Preview for commit 5464f03d400ec82deed865050be01f58a1afc43d at: https://6198d74b631a90f82f9db787--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d547cd9f6efafc0ba7c17db3a40d663fc072ad40 at: https://6199ed46f813cba918e03b6e--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1c3c0fb8e05fc7b3e6140edd699277dcdfbad05d at: https://619a1e40c6e9b4f78bbbd71d--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@YashKamboj it would be really helpful if you'd make a new PR. That'll fix the DCO problem and also you'd be able to do that in a single commit, right now there are too many commits for a small change.

**Pull request closed without merging**
