### PR TITLE
fixing hover effect on cards on news page

### LINKED ISSUE #4470: [UI] hover effect on cards on news page
### Description

on https://layer5.io/company/news on hover on cards, the image gets cut and does not look appropriate.

### Expected Behavior

left and right margin can be added to the image so that even if it enlarges on hover, it would not get cut.

### Screenshots

image
image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VamshiReddy02**
**Description**

This PR fixes #4470

I tried to fix the hover effect, please let me any changes.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4270d7b826f93f482ba572cab0f09d88cc7d09de at: https://64b26de6dd121d6e484e9fbe--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@VamshiReddy02 

Let's discuss it on the websites call ( On Monday at 5:30 PM IST).
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by HetviSoni** [comment]
I think the way the image inside these card change on hover is a bit weird(length increases but width remains the same).  Also, these 2 images still get cut. 

image

Screenshot 2023-07-23 191016

What is your opinion on this @thisiskaransgit @vishalvivekm @VamshiReddy02 ?

If you too think that, then 2 ways it can be corrected
1) No hover effect on the images only a hover effect on card would look good
2) First reduce the size of the image, so that the earlier hover effect ` transform: scale3d(1.1,1.1,1); ` would not cut the images

**Comment by Chadha93** [comment]
@VamshiReddy02?

**Review by Udit-takkar — COMMENTED** [review]
@VamshiReddy02 when i hover only the height increase and not width which feels a bit weird. any other workaround to fix the issue?

**Comment by VamshiReddy02** [comment]
I agree with @HetviSoni and @Udit-takkar, it looks weird when only the height increase and not the width. Can I Remove the hover effect on the images? keeping the hover on the cards as @HetviSoni suggested. It also looks good to me. Or any other suggestion?

**Comment by HetviSoni** [comment]
Yes according to me it would look good. I would also like to ask-
@Chadha93 @vishalvivekm @thisiskaransgit @Shivam-AfA  what are your suggestions on this?

**Comment by thisiskaransgit** [comment]
@VamshiReddy02, keep the post thumbnail block proportions for cards,  same as we have for[ layer5.io/blogs](https://layer5.io/blog). Let's wrap this up soon.
// @HetviSoni

**Comment by Khemendra-Bhardwaj** [comment]
Hey, is it still open so I can start working on it

**Pull request closed without merging**
