### PR TITLE
moved program listing to relative paths

### PR DESCRIPTION
**Pull request by kumarabd**

### CODE REVIEW

**Comment by leecalcote** [comment]
@kumarabd thank you. Have a look at the deployment preview. It seems that this relative path might break the links used in the buttons to these programs on the landing page. - https://5efe067d7d59a100082e9ca8--layer5io.netlify.app

**Comment by kumarabd** [comment]
@leecalcote  Let me have a review of it and will make the necessary changes right away.

**Comment by Nikhil-Ladha** [comment]
@kumarabd , the links worked on your local right?
While using the 'localhost:4000/programs/gsod/2020' as the address?

**Comment by Nikhil-Ladha** [comment]
Well, the link `/programs/gsod/2020` is working, but to completely solve it. @kumarabd you might want to update the value of `href` in the index.html file too.

**Comment by Nikhil-Ladha** [comment]
Screenshot from 2020-07-03 21-08-57 (1)
Notice the URL ^^

**Comment by kumarabd** [comment]
@Nikhil-Ladha  Ive made the necessary changes for the same. Does everything look good now? My local seems to be working perfectly.

**Comment by Nikhil-Ladha** [comment]
LGTM 👍🏼

**Pull request merged**
