### PR TITLE
Issue 1757 - Use Live Performance Text Count on Operating Service Mes…

### LINKED ISSUE #1757: [Meshery] Use Live Performance Text Count on Operating Service Meshes page
**Current Behavior**

1. Operating Service Meshes page counts up to a static number (2,000+)
https://layer5.io/service-mesh-management/meshery/operating-service-meshes
2. Gettnighthawk project page counts up to static number (2000+)
https://layer5.io/projects/getnighthawk

**Desired Situation**

Use the public endpoint (https://meshery.layer5.io/result/total) that has a real-time test result count instead.

See an example of its use here - https://layer5.io/service-mesh-management/meshery

The animated count should still occur, but count to the actual number instead of a hardcoded number.

---

**Screenshots / Mockups**
Screenshot_2021-04-05 Meshery, Multi-Mesh Manager

Screenshot_2021-04-05 GetNighthawk

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ting-c**
…hes page

**Description**

This PR fixes #1757 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 77df0e17b3de895c07a6062b0124c4b8437a0f23 at: https://606b2128263526008b43c2f8--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 77df0e17b3de895c07a6062b0124c4b8437a0f23 at: https://606b2151c491c90085e3128a--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 77df0e17b3de895c07a6062b0124c4b8437a0f23 at: https://606b2166c491c900c5e3125d--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@ting-c thank you for this contribution! 😄 

if you'd like to add a sign-off to your commit(s) here, you can do so by executing these instructions - https://github.com/layer5io/layer5/pull/1760/checks?check_run_id=2270409396

**Comment by l5io** [comment]
🚀 Preview for commit 9f5e983ac2165d4538dab4fcffcb43fd5f8512f7 at: https://606b4464de76393a2434a1f0--layer5ng.netlify.app

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks for this @ting-c 
Do you mind singing off your commits so that we are good to go?

**Comment by ting-c** [comment]
> Looks good. Thanks for this @ting-c
> Do you mind singing off your commits so that we are good to go?

**Comment by l5io** [comment]
🚀 Preview for commit 7396582d97cc037e73ce361f89837cf344509885 at: https://606c2c1a04ad831aac9e8a18--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7396582d97cc037e73ce361f89837cf344509885 at: https://606c2cba9be653121f95cb19--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Thank you @ting-c

**Pull request merged**
