### PR TITLE
[NG] Added Omkar Phansopkar as a contributor

### LINKED ISSUE #1240: [NG] Community: Recognizing Omkar Phansopkar as a Contributor and Community Member
**Current Behavior**
@OmkarPh  has been a consistent contributor and community member.

**Desired Situation**
A profile for @OmkarPh  should be created and visible on `/community/members` on next generation layer5.io site.

- Github: https://github.com/OmkarPh
- Twitter: https://twitter.com/omkarphansopkar/
- LinkedIn: https://www.linkedin.com/in/omkarphansopkar
- Profile picture: @OmkarPh can you provide a link to your profile picture?

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by MaximeCoignus**
Signed-off-by: MaximeCoignus <maxime.coignus@gmail.com>

**Description**

This PR fixes #1240

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@OmkarPh if you have a short blurb for a bio and your location to share, it would be great to have these included.

**Comment by OmkarPh** [comment]
Location: Mumbai, India

Bio:
I am a student majoring in Computer Engineering currently engaged in Mobile and web development. Eager to learn something new everyday and explore more and more technologies. 
Love problem solving and have been contributing to open source for a while.

**Review by OmkarPh — APPROVED** [review]

**Comment by Jashpatel1** [comment]
@MaximeCoignus do you mind adding the additional two details provided by Omkar?

**Comment by MaximeCoignus** [comment]
@Jashpatel1, done!

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Great work here, @MaximeCoignus

**Comment by OmkarPh** [comment]
Thanks @MaximeCoignus for this 😄🎉

**Pull request merged**
