### PR TITLE
Resources and blog search update

### LINKED ISSUE #2989: Search Component not functional on Resources page
**Description**
When you use pagination and go to any other page other than `1`, the component fails to search and shows a blank screen even though there are articles matching the keyword.

https://user-images.githubusercontent.com/85789734/181833870-6a6d5928-ef8c-47ea-8db9-a2097f12d4e2.mov

**Expected Behavior**
The component should search on every page. Ideally, it should search through the entire collection of resources to match results.

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by kayceeDev**
**Description**

This PR fixes #2989 #3031 

**Notes for Reviewers**
- Search feature bug now fixed on both blog and resources page

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 112f1d5a575c17e6ccee015bfd49db3106a181b5 at: https://62f0f7d9abfa6d5f2efc5579--layer5.netlify.app

**Comment by leecalcote** [comment]
@kayceeDev 💪

**Comment by kayceeDev** [comment]
> @kayceeDev 💪

Thanks Lee 😌

**Comment by Nikhil-Ladha** [comment]
Will wait for @debo19 's review.

**Comment by leecalcote** [comment]
Heads-up: @debo19 has been traveling these past couple days.

**Comment by Nikhil-Ladha** [comment]
> Heads-up: @debo19 has been traveling these past couple days.

Oh ok. In that case, merging the PR.

**Pull request merged**
