### PR TITLE
added cytoscape to design page

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a85a0b44e9471142d004251737c8a70dc366549b at: https://641cb6788a02ff02c01bc8e3--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a8a0af3040de2ef71eb9867b120b631647845bbb at: https://641cd1b251d9b000a7ed2a22--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
Absolutely @Chadha93. I would have been struggling with this if you hadn't guided me. 😁

**Comment by leecalcote** [comment]
@Shivam-AfA @Chadha93 is this ready?

**Comment by Chadha93** [comment]
> @Shivam-AfA @Chadha93 is this ready?

No, this requiers lots of changes. I'm creating a new PR with new Cytoscape functionality that represents context aware.

**Comment by leecalcote** [comment]
Duplicate PR

**Pull request closed without merging**
