### PR TITLE
Ibrahim Mbaziira memeber profile added

### PR DESCRIPTION
**Pull request by Deepak0320Singhal**
**Description**

This PR fixes [#5597](https://github.com/layer5io/layer5/issues/5597)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit af13dc6d8a36f8bfe9ccfd2808ebc2778d086121 at: https://667661a402ce935f239beed4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a05641bf68034294ab40b269c39b9e171a82d80e at: https://6677a85cedf85b3688ad5c8f--layer5.netlify.app

**Comment by Deepak0320Singhal** [comment]
@iArchitSharma can you please review the code.

**Review by iArchitSharma — APPROVED** [review]
LGTM thanks @Deepak0320Singhal

**Comment by vishalvivekm** [comment]
### yay :balloon: @code-sleuth :tada: 

Thank you @Deepak0320Singhal :sunglasses:

**Comment by Deepak0320Singhal** [comment]
@vishalvivekm Thank you for your appreciation 😎

**Pull request merged**
