### PR TITLE
Representation of Writing Program #4917 Added Handbook

### LINKED ISSUE #4917: [Programs] Representation of Writing Program
### Current Behavior
The site footer does not include a direct "[Handbook](https://layer5.io/community/handbook)" link under community. 

### Desired Behavior
It’d be good to have the Writing Program added to the Internship Program page and to then consolidate the footer links, making room for a Community Handbook link in the footer. 

Screenshot 2023-09-15 at 11 58 49 AM

### Screenshots / Mockups
__mockup for needed__

### Implementation
1. Consolidate "Internship and Writing Programs" into one line. If this combined text is too long, then shorten to simply "Internship Programs"
2. Add new section for Writing Program in the [Internships page](https://layer5.io/careers/programs)

### Acceptance Tests
1. layer5.io/community/handook is a new "Handbook" link in the footer under the Community section.
2. Writing program is represented on the Internships page.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Tishathakral**
**Description**

This PR fixes #4917

### CODE REVIEW

**Comment by Tishathakral** [comment]
Please review and merge the pull request @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit 14e3550a6845a3092519b74726d6bd79ccb2b030 at: https://65063f22e98862597fe7097a--layer5.netlify.app

**Comment by Mohith234** [comment]
Hey @Tishathakral, Without getting assigned please do not create any PRs. Do read the contributing guidelines beforehand.

Also, this was not the complete requirement in the issue. I guess @Modern-artist is assigned, You can work on other open issues. Do ask for getting assigned under the issue and after assigning only start working on it and making a PR thereafter.

Thank you

**Comment by abhijeetgauravm** [comment]
Hey @Tishathakral  We really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first . And we do have a bunch of open issues , you are most welcome to contribute. 

Thank you

**Comment by Tishathakral** [comment]
@Mohith234  @abhijeetgauravm 
I understand that I made a mistake in creating a PR without being assigned to the issue, and that I did not read the contributing guidelines carefully enough.

I am new to contributing to open source projects, and I am still learning the process. I am committed to following the rules and guidelines in the future, and I will be sure to ask for clarification if I am unsure about anything.

I understand that my mistake may have caused inconvenience or confusion, and I am truly sorry for that. I appreciate your understanding and patience.

**Pull request closed without merging**
