### PR TITLE
corrected product icons

### LINKED ISSUE #3554: Problems with product icons in Layer5's home page
**Current Behavior**

The product icons in the built-in integrations section on the home page of Layer5's website (https://layer5.io/) have problems. The first three icons from the top left and the second and third icons from the bottom right have this issue:
- Azure Active Directory (AAD): icon does not follow the black and white colour scheme in dark mode and stands out from the rest making it inconsistent.
- Akri: icon is incorrect in the light mode, only the bottom half of the icon is visible and the upper half has vanished.
- Azure Application Gateway: icon is incorrect in dark mode, the details of the icon blends into one and making the icon incorrect and also does not follow the dark mode colour scheme and becomes inconsistent.
- Buildpacks: icon is wrong in light mode.
- CDK for Kubernetes: icon is wrong in dark mode, it's a solid cube design with no detailing.

Screenshot from 2022-12-24 11-06-17
Screenshot from 2022-12-24 11-07-07

**Desired Situation**

Correct icon representation in both light and dark modes.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam-AfA <shivamsood634@gmail.com>

**Description**

This PR fixes #3554 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b79eb9c9782b18796de8893d69f0a3535e575c69 at: https://63a980c0d922a80309fb2ff9--layer5.netlify.app

**Comment by leecalcote** [comment]
@Shivam-AfA will you connect with @UtkarshMishra12 regarding how updates to the integrations are sourced and how to ensure that updates are not overwritten?

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA will you connect with @UtkarshMishra12 regarding how updates to the integrations are sourced and how to ensure that updates are not overwritten?

Sure @leecalcote . I'll take care of that.

**Comment by leecalcote** [comment]
Many thanks.

**Comment by l5io** [comment]
🚀 Preview for commit 85bffb2fd0de03d369e0ea5cb478fd847d29dc3b at: https://63adee24a2f90e237ee90d9e--layer5.netlify.app

**Review by leecalcote — COMMENTED** [review]
@Shivam-AfA where did you get the color version of Akri? It looks pieced together. Can you point me to the location from where the original was pulled?

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA where did you get the color version of Akri? It looks pieced together. Can you point me to the location from where the original was pulled?

I just changed the SVG content of the image for Akri. But just now, I went to the Akri repository and found a fit SVG icon for our site.

**Comment by Abiey2579** [comment]
# ATTENTION @Shivam-AfA @leecalcote 

Did you realize that there are lots of problems with same icons under
`https://layer5.io/cloud-native-management/meshery/integrations/`

Some Icons are not working correctly in both mode `Light and Dark`

## DARK MODE
Screenshot 2022-12-29 233717
Screenshot 2022-12-29 233810
Screenshot 2022-12-29 233843
Screenshot 2022-12-29 233912

## LIGHT MODE
Screenshot 2022-12-29 234001
Screenshot 2022-12-29 234049
Screenshot 2022-12-29 234122



@Shivam-AfA @leecalcote  Check it out

@Shivam-AfA If you need extra hands solving this, can't wait to volunteer

**Pull request closed without merging**
