### PR TITLE
adding dynamic footer year

### LINKED ISSUE #2648: Footer Date
**Description**
The current year setting at the footer is not dynamic I guess and that is why it it showing as 2021.

image

**Expected Behavior**

The Year should change dynamically every year without the need to change it each year.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Ardent10**
Signed-off-by: Zakariya khan <zak786khan@gmail.com>

**Description**
This PR fixes the Dynamic date of the Footer in the Layer5io webpage.

This PR fixes  #2648 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a855dd2f62d625d4f09114235ff8a10ad4226623 at: https://622c47002788c605a601c294--layer5ng.netlify.app

**Review by Abhijay007 — COMMENTED** [review]
@Ardent10 you did changes for [discuss.layer5](https://discuss.layer5.io/) footer section, revert these changes and do same for layer5 site footer

**Comment by Ardent10** [comment]
> @Ardent10 you did changes for [discuss.layer5](https://discuss.layer5.io/) footer section, revert these changes and do same for layer5 site footer

Thankyou for pointing out, Must have confused it.

**Comment by Ardent10** [comment]
It's done.

**Comment by l5io** [comment]
🚀 Preview for commit be8836dfae934ce3599c5ca1047840b7f2fb878c at: https://622cbdc92788c63fd001c426--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b0adbfec97140ae2af00cc0063a5514fce389b43 at: https://622cfb0c334b351f0dabc1ec--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @Ardent10

**Pull request merged**
