### PR TITLE
Partners-home: added support for react slider dots (partner section) : dark mode w/s…

### LINKED ISSUE #3830: Dark Mode issue on Partner section carousel
### Current Behavior

The dots below the partners section carousel aren't visible in dark mode and also gives outline on hovering that doesn't looks good

### Desired Behavior

Remove the outline from dots on hovering and fix the dark mode issue as dots are not visible

### Screenshots / Mockups

https://user-images.githubusercontent.com/77241166/221620857-87cd0a8c-3ad5-4523-b4fe-05518a376099.mp4

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by melsonic**
…ignoff

**Description**

This PR fixes #3830

**Notes for Reviewers**
### Before
* in dark mode, the Partner section dots were not visible because the color was set to dark gray/black same as in light mode
### After 
* changed the color to white for the active dot and the remaining dots to the #939393 color
------------------
* Below I am attaching a video showing the output of this PR

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
 - [x] Yes, I signed my commits.
 

[Layer5 - Partner Section PR](https://user-images.githubusercontent.com/88551650/222546168-b6d061f2-9a12-4eba-901a-68bae5a1ad0c.webm)

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6d795408b085044176a21277cf8a90fdaf53a3e8 at: https://64010d4bac19fa2f0dac2bcf--layer5.netlify.app

**Comment by melsonic** [comment]
@leecalcote can you check it once, please

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
I can still see that ugly square background eeffect on hover. Could you please fix that @melsonic ?

**Comment by melsonic** [comment]
> I can still see that ugly square background effect on hover. Could you please fix that @melsonic .

Should I remove the hover effect completely?

**Comment by Nikhil-Ladha** [comment]
> > I can still see that ugly square background effect on hover. Could you please fix that @melsonic .
> 
> Should I remove the hover effect completely?

Yes, please.

**Comment by l5io** [comment]
🚀 Preview for commit 48db4fc273c7584bbf318e36d24b7babe03ee422 at: https://6402022a032a121d3d6df20b--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
