### PR TITLE
Brand page made mobile responsive

### LINKED ISSUE #946: [NG] Improvise the responsiveness of Brand page of layer5-ng
**Current Behavior** : 

The current [Brand page](https://layer5ng.netlify.app/brand) on the [layer5-ng site](https://layer5ng.netlify.app/) is live, which comprises distinct layer5 brand div's.

**Desired Behavior** : 
-  Align the pallets (color-boxes) in meshery and SMP to center in mobile view.

 

95051883-a0476400-070b-11eb-9791-60c66ec0db2a

-   Keep the contact us part below the heading in the mobile view.
-  The section header should have a bigger font size and should be properly left-aligned similar to other sub-headings.

95051913-ab01f900-070b-11eb-9245-567098926f35

- The grayscale and the color, colors are getting mixed up as we make the view responsive and move to a mobile view or tablet view.

image

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by codetheorem**
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Description**
Made Brand page mobile responsive.

This PR fixes #946 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
All the points have not been addressed, right?

**Comment by codetheorem** [comment]
There are two points which are left. One is working fine and the other is about the contact us section I didn't get that. Can you explain that?. Grayscale one is working fine.

**Comment by Tanuj22** [comment]
- The section on the side of `Layer5 Brand Kits` that is `We’ve created some guidelines to help you use our brand and assets....` should be below the `Layer5 Brand Kits` heading in mobile view.
- Try to decrease the size of the screen you will observe that the color pallets that belong to grayscale gets mixed up with other colors in smaller screens.

**Review by Jashpatel1 — COMMENTED** [review]
I think the links are not attached to the buttons. Please look into it @codetheorem

**Comment by codetheorem** [comment]
@Jashpatel1 can you provide me the links.

**Review by Jashpatel1 — CHANGES_REQUESTED** [review]
In the desktop view, the color pallettes in meshery and SMP coincide with left border. Please add some padding or margin over there.
image
Rest all looks good.

**Review by Tanuj22 — CHANGES_REQUESTED** [review]
Apart from what @Jashpatel1 mentioned. Increase the size of `layer5 brand kit` heading and center it in mobile view.

**Comment by codetheorem** [comment]
@Jashpatel1 and @Tanuj22 please review it.

**Review by Tanuj22 — APPROVED** [review]
LGTM! Thank you for working on this @codetheorem :)

**Pull request merged**
