### PR TITLE
Fixes 5675 {Align items in Career/Software-engineer-internship page}

### LINKED ISSUE #5675: Align items in Career/Software-engineer-internship page
### Description
The Internship Details in the Career/Software-engineer-internship page happen to appear unaligned when viewed from a device with higher resolution.

#### Ideally, the intended view of the page should look something like this:
Screenshot from 2024-07-12 21-22-56

#### How it looks when viewed from a screen with higher resolution:
Screenshot from 2024-07-12 15-21-54

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by iamclintgeorge**
**Description**
The Internship Details in the Career/Software-engineer-internship page was not aligned when viewed from a device with higher resolution.

This PR fixes #5675 

**How it used to look**
Screenshot from 2024-07-13 20-22-13

**How it looks after the changes made**
Screenshot from 2024-07-13 20-22-50
Screenshot from 2024-07-13 20-22-17

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 55d7a0c1623b25b7e9055eeceb0577c0fefc4625 at: https://669299539ef7e25b2c5fbfa5--layer5.netlify.app

**Comment by iamclintgeorge** [comment]
Sure. @sudhanshutech

**Comment by iamclintgeorge** [comment]
@sudhanshutech I have made the changes as you requested by removing all the lint from the code page that concerns this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 0005d6381ab575d56239bcf04a519360f5aa4309 at: https://6693ae3ac9f4c83434474b7a--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@iamclintgeorge 
Thank you for your contribution.
Let's discuss this on Websites' call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by iamclintgeorge** [comment]
@hargunkaur286 Can you share the screenshot of your device at 1440 resolution since i am not sure why it is not visible.

**Comment by hargunkaur286** [comment]
> @hargunkaur286 Can you share the screenshot of your device at 1440 resolution since i am not sure why it is not visible.
Screenshot 2024-07-15 at 6 36 12 PM

**Comment by iamclintgeorge** [comment]
Screenshot from 2024-07-15 18-38-10


Can someone confirm this issue?

**Comment by iamclintgeorge** [comment]
@hargunkaur286 Should i close this PR since i confirmed that it is just unaligned in my browser. Sorry for the inconvenience caused by me, i should have cross checked the error.

**Comment by hargunkaur286** [comment]
> @hargunkaur286 Should i close this PR since i confirmed that it is just unaligned in my browser. Sorry for the inconvenience caused by me, i should have cross checked the error.

No issues, yes, you may close it. 🙂

**Comment by Ashparshp** [comment]
@iamclintgeorge No problem. Thanks for the confirmation!

**Pull request closed without merging**
