### PR TITLE
Initialize posthog in site

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b90d4c813a79f46578274940f23b6b2ac40a393a at: https://66ec35b52ffe93ca804aa04e--layer5.netlify.app

**Comment by sudhanshutech** [comment]
Oops build failed. Looking.

**Comment by sudhanshutech** [comment]
I am able to see recordings though in posthog dashboard

**Comment by l5io** [comment]
🚀 Preview for commit 5bf6d1bbfd1fc848644c294e5bd2cee4ad1ae672 at: https://66ec412f1e173200be987d4c--layer5.netlify.app

**Comment by leecalcote** [comment]
@sudhanshutech still "do not merge"?

**Comment by vishalvivekm** [comment]
@sudhanshutech Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
