### PR TITLE
Add Abhijay Jain as a recognized member 

### LINKED ISSUE #2517: [Community] Member Profile: Abhijay Jain
**Current Behavior**

@Abhijay007 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Abhijay007 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Abhijay007
- Twitter: CodeInVeins
- LinkedIn: /abhijay-jain-551b01193
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ShivamTyagi12345**
Signed-off-by: ShivamTyagi12345 <shivamt.ug19.ec@nitp.ac.in>

**Description**
I have added the Details to a new Member Card.
This PR fixes #2517
- https://github.com/layer5io/layer5/issues/2517
**Notes for Reviewers**
I was missing out on the details of the state he belongs to hence I  have mentioned India in his Location

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Do add issue number just adjacent to the `fixes` keyword so that the issue is linked to the PR and closes automatically on merge.

**Review by Abhijay007 — COMMENTED** [review]
@ShivamTyagi12345 I don't think that we need this file :   `src/components/.image.js.swp` , not sure.

**Comment by l5io** [comment]
🚀 Preview for commit 135fd969c53dca22b8d2d6d921b35e4a5bd23a72 at: https://61efdc6ce0bc9fecc9bf51f3--layer5ng.netlify.app

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 I don't think that we need this file : `src/components/.image.js.swp` , not sure.

i am pretty sure I added just 2 files ,not sure How this file got committed. How do I fix this?

**Comment by Abhijay007** [comment]
> > @ShivamTyagi12345 I don't think that we need this file : `src/components/.image.js.swp` , not sure.
> 
> i am pretty sure I added just 2 files ,not sure How this file got committed. How do I fix this?

@ShivamTyagi12345 it is a `.swp` type file which is a swap file created by the Vi text editor or one of its variants it might be auto generated to store info about recovery version of a file being edited in the program.  

You can simply remove it by not including it, As may not shown in the commits, you try to add this in `.gitignore` and then try to commit the changes. @warunicorn19 can you please assist here by proving more info :)

**Comment by Nikhil-Ladha** [comment]
I have seen this issue faced by you multiple times now.
Looks like you are not closing the editor properly and as a result, these `.swp` files are generated.
If you could check, there should be a `.swp` file in the system, just delete it and make a commit.

**Pull request closed without merging**
