### PR TITLE
[NG] Projects and Partners section

### LINKED ISSUE #1419: Implementation of Our Projects and Partners Logo Sections
**Current Behavior**
We currently have no implementation of our project and partner logo section. 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

Checkout the section below
logo

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vineethvanga18**
**Description**

This PR fixes #1419

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Does “draft” mean that I can’t prematurely merge this PR? 

Dang it!!

**Comment by vineethvanga18** [comment]
Only one issue. The svg on projects section comes over project cards, will need to figure out a way to get it behind them.

**Comment by Tanuj22** [comment]
> Only one issue. The svg on projects section comes over project cards, will need to figure out a way to get it behind them.

Can the `VintageBox` component be used?

**Comment by vineethvanga18** [comment]
@Tanuj22 tried that, but missing something.

**Comment by vineethvanga18** [comment]
turns out the background for cards is transparent.

**Comment by Tanuj22** [comment]
Is the hover effect on the partners logos too much? @Nikhil-Ladha @Jashpatel1 what do you think?

**Comment by Jashpatel1** [comment]
> Is the hover effect on the partners logos too much? @Nikhil-Ladha @Jashpatel1 what do you think?

Agreed. Can be reduced a bit.

**Comment by Nikhil-Ladha** [comment]
Hover effect for both the partners and projects can be made a bit subtle...also the partner logos seems a bit skewed. Isn't it?

**Comment by leecalcote** [comment]
@vineethvanga18 images fixed. Ready for you to adjust sizing of Cols to fit.

**Comment by leecalcote** [comment]
@vineethvanga18 what does this look like if we keep it to a single line?

**Comment by vineethvanga18** [comment]
It is fine for larger screens.

**Comment by leecalcote** [comment]
Oh, just seeing your comment.... Yes, you're right that it looks good. For now, we're not necessarily trying to show all the partners, not trying to make it obvious that people can click them. The logos are there to inspire confidence and appear to be a lot and a lot of recognizable logos.

**Comment by vineethvanga18** [comment]
@leecalcote I see that some of them aren't fitting on the screen. Is that intentional?

**Comment by leecalcote** [comment]
Sort of, yes. Hard to explain, I suppose other than how I characterized it above.

There is clean up here that is needed. Will you fiddle with it a bit?

**Comment by leecalcote** [comment]
https://user-images.githubusercontent.com/7570704/107088018-ef88c880-67c1-11eb-810d-4a012c52fc70.mov

Issues to address:
1. overflow is not contained on the righthand side of the site.
2. need a minimum size set such that the logos are still perceptible (legible) on small screen sizes.
3. need a maximum size set such that the logos stop growing at a reasonable max size.

**Review by leecalcote — CHANGES_REQUESTED** [review]
see video in comment above

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
