### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description**

Small fixes/cleanups for careers page and about page.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Please ignore the amending of the SocilaIcons component into this PR......it happened by mistake 😆

**Comment by Tanuj22** [comment]
@Nikhil-Ladha can you remove the 2 not used imports

**Review by leecalcote — APPROVED** [review]
Thank you.

**Comment by leecalcote** [comment]
> @Nikhil-Ladha can you remove the 2 not used imports

Ooops, I missed this.

**Pull request merged**
