### PR TITLE
Fix checklint warning

### LINKED ISSUE #4069: fix the checklint warnings
### Description

Currently there are a number of checklint warnings that appear when any changes are committed locally.

### Expected Behavior

These warnings should be fixed. All of these warnings are related to unused variables ,so this would require just removing those variables from the files

### Screenshots

image

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ashuthe1**
**Description**

This PR fixes #4069

**Notes for Reviewers**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 23a0060a71b58b44e4a8b3e9f3af06c71e918274 at: https://642f40eb5b894a1a1b8be35c--layer5.netlify.app

**Review by ayushthe1 — CHANGES_REQUESTED** [review]
Thanks for the changes @ashuthe1 .There are just some unsigned commits that need to be fixed.
Run these commands in your local repo to fix the issue:
* `git rebase HEAD~4 --signoff`
* `git push --force-with-lease origin fix-warning`

**Review by ayushthe1 — APPROVED** [review]
ready to be merged now :+1:

**Comment by l5io** [comment]
🚀 Preview for commit 905c28873eb8ace2d28fabab3e69a59380a6178b at: https://642fb87a2de71f726dc3103f--layer5.netlify.app

**Comment by leecalcote** [comment]
@Shivam-AfA will you help resolve these conflicts?

**Comment by ashuthe1** [comment]
conflicts resolved

**Comment by l5io** [comment]
🚀 Preview for commit 59610272dab5d4628c8a2da4de62e3511c94565c at: https://643107c85408495ce37a7d03--layer5.netlify.app

**Review by ayushthe1 — APPROVED** [review]
Great 👍

**Comment by l5io** [comment]
🚀 Preview for commit 09c696a5654f6225ab8de9598d07088d9ca81055 at: https://6432d46ff3fded33afd150e0--layer5.netlify.app

**Comment by leecalcote** [comment]
> conflicts resolved

Good, good.

**Review by leecalcote — APPROVED** [review]
This is very helpful. Thank you for these updates, @ashuthe1 👍 and review, @ayushthe1

**Pull request merged**
