### PR TITLE
program_permission_required #5022 (update)

### LINKED ISSUE #4981: Add hyperlink of FAQ to required table of repository-overview page
### Current Behavior
Currently there are some repos which are not accessible to everyone. This creates confusion for newcomer.
### Desired Behavior
It should explain why it is not accessible to everyone.
### Screenshots / Mockups
image
### Implementation
We can add hyperlink to that section which will lead to FAQ page where we can answer to the quiestion
---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Jat1nSood**
**Description**

This PR fixes #4981 
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fd2982e111a14aafb1f2aab2ae4bec9d4b2287a2 at: https://657c8a0592f9780eee7c805b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4b351d1b6184f1ed97155e4e1a32cda4bd06606 at: https://657c8f7acd7a7c12afdda699--layer5.netlify.app

**Comment by Jat1nSood** [comment]
Hi @ritiksaxena124 although this PR is merged but the feature is not on the site. I wonder if that happened because I reverted changes in other branch for the other PR. It should not have happened because they are two different branch

**Comment by ritiksaxena124** [comment]
> Hi @ritiksaxena124 although this PR is merged but the feature is not on the site. I wonder if that happened because I reverted changes in other branch for the other PR. It should not have happened because they are two different branch

This might happen because you created a branch and from that branch, you created another branch this way you had two branches. 

Next time when you do make sure to create separate branches from the master and for this issue would you mind creating another PR?

**Pull request merged**
