### PR TITLE
[Community] Make Meetings Table Responsive

### LINKED ISSUE #785: [Community] Layer5 Community Meetings table not mobile responsive
This table (https://layer5.io/community#meetings) is not configured to be responsive in a mobile view.

It needs to be responsive. There are existing styles in the site that can be used to make it responsive.

Screenshot_20200918-093727__01
One issue with the table in mobile view.

_Originally posted by @Nikhil-Ladha in https://github.com/layer5io/layer5/pull/764#issuecomment-694638322_

### PR DESCRIPTION
**Pull request by clementkng**
Signed-off-by: Clement Ng <clementdng@gmail.com>

**Description**

This PR fixes #785

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by akashgp09 — COMMENTED** [review]
LGTM 👍

**Comment by chandrashritii** [comment]
@clementkng can the scroll bar be hidden?

**Comment by clementkng** [comment]
@chandrashritii do you mean hidden at all screen widths?

**Review by leecalcote — APPROVED** [review]
Good work, @clementkng. 👍 

Thank you, @akashgp09 💯

**Comment by leecalcote** [comment]
Haha! Very nice, @clementkng! 🎈

**Pull request merged**
