### PR TITLE
added meshery 1000 stars blog

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
Added "The Story of Meshery's 1000 Stars" blog post.

This PR fixes #

**Notes for Reviewers**
This one was long overdue. We're 200 stars ahead already 😅 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7abf94e0b1da7169b512291d3178983da8889570 at: https://61ec1ab40c553c299c814264--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9d19fbaffab055f5076521329c24c47ed8a9aa92 at: https://61ec1e6b3a3b713d6401e8ba--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
`type: Blog` needs to be included. Also, in my opinion considering we are already 200 ahead of 1000 maybe we should release this blog at 1500 or 2000.

**Comment by l5io** [comment]
🚀 Preview for commit 8433861b6ce527d41af1d82603d8e258d852273c at: https://61ec24e80b7692356305505b--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 5183e08c3767403f481d330066834d4ad53877e2 at: https://61f1c5ff3b56fb53d5d75dfd--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 395d5377839cf52571bdf5196c2b427bcc6ed78a at: https://61f22b776c549d4ab03eda2a--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dbdfee9246963b260335f2a50b0100a3ffdc4558 at: https://61f249f64a49e264e45455d6--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@debo19 we can merge this now, right?

**Pull request merged**
