### PR TITLE
Card sistent component

### LINKED ISSUE #5908: [Sistent] Add Card component to the sistent components page
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [Card](https://github.com/layer5io/sistent/blob/5529c342c6ad2b00b8e8d08deafc02fe72fe5513/src/base/Card/Card.tsx).

(https://playground.meshery.io/user/preferences)
image

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The Card component currently needs this representation.

### Desired Behavior

Proper documentation for Card component similar to Button component on https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation of the the function that the component serves in context of it's usage.
- Usage and information of accompanying utility components:
  - CardActions
  - CardContent
  - CardHeader
  - CardMedia
- Code examples.
- Stylistic guidelines to be followed while using the component in code (if any).

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 🎨 See [Sistent Repository](https://github.com/layer5io/sistent).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Anand-Theertha**
**Description**

This PR fixes #5908. This PR adds a Card component to the Sistent components. Following are a few screenshots of how the implementation looks: 

image

image

image

**Notes for Reviewers**

1. Check description of each type of Card to ensure sufficient information is provided to the user. 
2. Ensure all important types of cards are present.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3c75342d4b7c259ae8ebbcf97adfac70b19ea4a2 at: https://673ca2742fbcdf34f871fb47--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8fafebcdd4cbf4d15bea52685857444bba4ca0c4 at: https://673debc2bd0ffbc2451e7ea3--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Anand-Theertha change the structure of page as per new changes made around adding sistent components.

**Comment by Anand-Theertha** [comment]
Alright, will do. Where can I find these new changes?

**Comment by sudhanshutech** [comment]
> Alright, will do. Where can I find these new changes?

you don't need create directories under pages that will automatically will taken taken care.

**Comment by sudhanshutech** [comment]
@Anand-Theertha wrap this quickly

**Comment by vishalvivekm** [comment]
@Anand-Theertha 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST

adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Anand-Theertha** [comment]
Will do @sudhanshutech

**Comment by sudhanshutech** [comment]
@Anand-Theertha still pending?

**Comment by sudhanshutech** [comment]
@Anand-Theertha ?

**Comment by sudhanshutech** [comment]
@Anand-Theertha i am closing this due to no activity for others to work, please reopen if you are active again

**Comment by Anand-Theertha** [comment]
Reopened a PR fixing the same issue with all of the changes requested: https://github.com/layer5io/layer5/pull/6117

@sudhanshutech

**Pull request closed without merging**
