### PR TITLE
[Resource] Search feature is added for Resource page

### LINKED ISSUE #2767: [Resource] Add Search feature  for Resource page
**Current Behavior**
Currently, we do not have any search feature on the Resource page : https://layer5.io/resources

**Desired Behavior**
Create a search feature for it

---
**Screenshots / Mockups**

**Alternatives**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by subhradwip01**
**Description**
Search feature is added in Resource page

This PR fixes #2767

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 037425b84a7a179cf90f32021c0e31de0a8486bc at: https://62814cd59c197563da0cf5a8--layer5ng.netlify.app

**Comment by leecalcote** [comment]
hey, hey, @subhradwip01 👏

**Review by leecalcote — APPROVED** [review]

**Comment by debo19** [comment]
@leecalcote this needed some more work 😅  @subhradwip01 will you make the changes that we talked about in the websites call?

**Comment by subhradwip01** [comment]
Ya sure...

**Comment by leecalcote** [comment]
_Gasp!_ @subhradwip01 please ensure that there is an issue open tracking those enhancements.

**Pull request merged**
