### PR TITLE
[website] modify svg for smi to a proper one

### LINKED ISSUE #2019: [Website] The image in sservicemesh interface page is Buggy
**Description**

I have observed the image in Service Mesh Interface(https://layer5.io/projects/service-mesh-interface-conformance) has some Servicemesh places being blank. See the image below
Screenshot 2021-07-22 at 9 03 22 PM

**Expected Behavior**

It should look something like this:
Screenshot 2021-07-22 at 9 12 58 PM

**Screenshots**

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by bariqhibat**
Signed-off-by: Bariq <bariqhibat@gmail.com>

**Description**

This PR fixes #2019

image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 102f72cb03475e7c769a7fec42a0c6faecf39181 at: https://60f9b8d1fc4ac82b95b8a648--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@bariqhibat good stuff. 👍 

Little known fact: Figma notoriously messes up exports of SVG files. The color of the Kuma and Istio logos are off.

**Comment by bariqhibat** [comment]
I see, alright I fixed the color for the both logos. Also modify the order to what I think makes sense (descending). 
image

**Comment by l5io** [comment]
🚀 Preview for commit f2128918f18d9e37c6d22e1c40430f9fb0769f1a at: https://60faa40bd5fb27b546db17ec--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Mr. ColorMan (@leecalcote), does the colors looks fine to you now? :')

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by leecalcote** [comment]
👮 The color police heartily approves this fine work.

**Comment by leecalcote** [comment]
@bariqhibat one other item to attend to, if we could: a little less red. Will you kindly toss in a couple more green checks and a couple of half checks with orange? See https://meshery.io/service-mesh-interface) for an example.

 // @dhruv0000

**Comment by bariqhibat** [comment]
> @bariqhibat one other item to attend to, if we could: a little less red. Will you kindly toss in a couple more green checks and a couple of half checks with orange? See https://meshery.io/service-mesh-interface) for an example.
> 
> // @dhruv0000

Sure, just changed it!
image

**Review by leecalcote — APPROVED** [review]
Thank you, @bariqhibat. Looking good. 👍

**Pull request merged**
