### PR TITLE
fixes #1500

### LINKED ISSUE #1500: [Home] Proudly Maintaining: background color and card scale
**Description**
Each of the participating projects should be on a card with rounded corners. Some of the cards may spill off the page.

@vineethvanga18 will you revise this section to look more like the mockup?

**Screenshots**
Screen Shot 2021-02-07 at 9 19 02 PM

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18. This is much, much better. Two remaining items:

1. the cards are touching each other between the two rows.
2. the cards are evenly aligned vertically. Instead, the hope is that they will be staggered and offset from one another.
Screen Shot 2021-02-08 at 8 48 27 AM

**Comment by Nikhil-Ladha** [comment]
One thing though, if we are using a white background for the cards then what's the use of the cards 😅 ?

**Comment by leecalcote** [comment]
@Nikhil-Ladha good point. It's very light, isn't it?

**Comment by leecalcote** [comment]
@vineethvanga18 the labels weren't staying within the boundaries of the cards, so I removed the labels. Now, a couple of the logos look awkward because there aren't centered. I couldn't get them to be centered without having them escape the boundary of the card. Will you take a crack at this and we're good to merge afterward.

@Nikhil-Ladha I darkened the card background a little.

**Review by leecalcote — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
@leecalcote I guess you haven't committed the darkened version of the cards 🤔

**Pull request merged**
