### PR TITLE
adding screen shots

### PR DESCRIPTION
**Pull request by TyagiRajat**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 15348eb72b51f33431632527321932924c5c93d6 at: https://66be3fb69b90ff1385d8d3f0--layer5.netlify.app

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
please rename the dir from `_images/bridage` to `_images/brigade` @TyagiRajat 
Refer to : https://github.com/layer5io/layer5/pull/5129#issue-1995493031

**Comment by Ashparshp** [comment]
@TyagiRajat, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
@TyagiRajatk, are you on slack?

**Comment by sudhanshutech** [comment]
@TyagiRajat please reply to above feedbacks.

**Pull request closed without merging**
