### PR TITLE
Added SPIFFE/SPIRE data to the landscape

### LINKED ISSUE #2364: [Landscape] Ensure that SPIFFE and SPIRE are displayed on the Service Mesh Landscape
**Current State:**
SPIFFE and SPIRE's use by service meshes is cataloged in the [service mesh landscape](https://layer5.io/landscape)'s data model, but doesn't seem to be exposed on the landscape's "Functional" table.

**Desired State:**
A column dedicated to SPIFFE/SPIRE should be visible. See the landscape [data here](https://github.com/layer5io/layer5/tree/master/src/sections/Landscape).

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Ciggzy1312**
Signed-off-by: Deepayan <deepayanmukherjee1312@gmail.com>

**Description**
Ensures that SPIFFE/SPIRE mesh compatibility data is displayed on the Service Mesh Landscape

This PR fixes #2364

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e7a6310ee7399577af74fbe3a29331b2bf6b0528 at: https://61a3c42162b3369becf9802e--layer5ng.netlify.app

**Comment by leecalcote** [comment]
We're talking about this PR on the weekly Websites meeting now. You're encouraged to join @Ciggzy1312 --> https://meet.layer5.io

This PR is looking good!

**Comment by Ciggzy1312** [comment]
> We're talking about this PR on the weekly Websites meeting now. You're encouraged to join @Ciggzy1312 --> https://meet.layer5.io
> 
> This PR is looking good!

Had my college classes today. Will make sure to hop in from next week if that sounds okay

**Comment by leecalcote** [comment]
Sounds great. It's be nice to have you. :)

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Good detective skills, @Ciggzy1312. Good of you to find this missing data and get it into the right place.

**Comment by Ciggzy1312** [comment]
Thanks @leecalcote . Means a lot

**Pull request merged**
