### PR TITLE
Playground popup on home page (bottom right corner)

### LINKED ISSUE #4276: Add Meshery Playground popup on Layer5's home page.
A popup is required on the home page of the website (https://layer5.io/) that should redirect users to the Meshery Playground (https://play.meshery.io/). 

Some assests/ graphics that can be used for the poup are available here: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=10869-15222

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Shivam-AfA**
**Description**

This PR fixes #4276 

This is an alternative implementation for #4291 
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c208a3f2f0ceb710dbc2b7f9210d39d1a184ebe2 at: https://6473b75ece747378a23ac79f--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
on mobile view the button "Explore Meshery Playground" is taking up too much space, maybe we can change the text to "Explore".

**Comment by Shivam-AfA** [comment]
> on mobile view the button "Explore Meshery Playground" is taking up too much space, maybe we can change the text to "Explore".

Yes, this seems appropriate.

**Comment by leecalcote** [comment]
Mobile view needs fixed.

**Pull request merged**
