### PR TITLE
[Blog] Collapsible tag and category list

### LINKED ISSUE #2577: [Blog] Collapsible tag and category list
**Current Behavior**
The tags and categories list on blog page has become too long. On selecting a specific category, there's a lot of unnecessary blank space on the page. 

https://user-images.githubusercontent.com/85789734/152233646-e8f9280b-8ce5-46a0-a777-f5284d826312.mov

**Desired Situation**
Make the tag list and category list collapsible. They should be collapsed while viewing blogs of any particular category or tag but open on the main blog page.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by subhradwip01**
**Description**

This PR fixes #2577

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by subhradwip01** [comment]
Output:

https://user-images.githubusercontent.com/88609894/156172711-556201aa-0330-4d28-b7d4-0c2f622dc39b.mp4

**Comment by l5io** [comment]
🚀 Preview for commit 9d0ffe7afbfd395235c2300575e74910552cfc72 at: https://621e19c08464b4151b04e016--layer5ng.netlify.app

**Review by Abhijay007 — APPROVED** [review]
@subhradwip01,, LGTM !! it is working fine for mobile/tablets as well :)

**Comment by leecalcote** [comment]
Weird. The preview deployment doesn't seem to have either of the two chevrons for expanding/collapsing the categories and tags sections....

**Comment by subhradwip01** [comment]
> Weird. The preview deployment doesn't seem to have either of the two chevrons for expanding/collapsing the categories and tags sections....

I haven't shown/provided them unless users visits a particular tag or link...should I also  make that feature on main blog page also?

**Comment by Nikhil-Ladha** [comment]
> > Weird. The preview deployment doesn't seem to have either of the two chevrons for expanding/collapsing the categories and tags sections....
> 
> I haven't shown/provided them unless user visits a particular tag or category...should I make that feature on main blog page also?

Yes please. By default it should be open, in case of `/blog` page but there should be an option to collapse them as in the `category`,  tags` page.

Also, while you are there can you move the `Subscribe to newsletter` callout to the end of the column. It looks weird in between the two collapsible menu

**Comment by subhradwip01** [comment]
> 

Ok, Understood...Will the newsletter always be at last (after the tags and category) or in the main /blog page it should be in the middle of the tags and category?

**Comment by subhradwip01** [comment]
> > > Weird. The preview deployment doesn't seem to have either of the two chevrons for expanding/collapsing the categories and tags sections....
> > 
> > 
> > I haven't shown/provided them unless user visits a particular tag or category...should I make that feature on main blog page also?
> 
> Yes please. By default it should be open, in case of `/blog` page but there should be an option to collapse them as in the `category`, tags` page.
> 
> Also, while you are there can you move the `Subscribe to newsletter` callout to the end of the column. It looks weird in between the two collapsible menu

Ok, Understood...Will the newsletter always be at last (after the tags and category) or in the main /blog page it should be in the middle of the tags and category?

**Comment by Nikhil-Ladha** [comment]
> Ok, Understood...Will the newsletter always be at last (after the tags and category) or in the main /blog page it should be in the middle of the tags and category?

Always at the end.

**Comment by subhradwip01** [comment]
> > Ok, Understood...Will the newsletter always be at last (after the tags and category) or in the main /blog page it should be in the middle of the tags and category?
> 
> Always at the end.

Ok

**Comment by l5io** [comment]
🚀 Preview for commit 0839941ef192815dc1fc02566bc59d47c6aec466 at: https://62219f212c2c8c397f1ced2c--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@subhradwip01 could you please demo on the websites' call?

**Comment by subhradwip01** [comment]
> @subhradwip01 could you please demo on the websites' call?

ya sure

**Comment by Nikhil-Ladha** [comment]
Once the issue in the mobile view is fixed (as discussed on the Website's call), do signal @subhradwip01 .
The highlight of the active `category/tag` could be done in a separate PR by a newcomer, please open an issue for it.

**Comment by subhradwip01** [comment]
> Once the issue in the mobile view is fixed (as discussed on the Website's call), do signal @subhradwip01 . The highlight of the active `category/tag` could be done in a separate PR by a newcomer, please open an issue for it.

Ya Sure

**Comment by subhradwip01** [comment]
@Nikhil-Ladha I fixed that mobile view..could you check the latest update?

**Comment by l5io** [comment]
🚀 Preview for commit dd32be7984be5136199f0b41a6779be9a436c74d at: https://62270853e1ca7b65902e6836--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
@Nikhil-Ladha should I open the issue for highlighting active tag/category now? or I should open the issue after resolving that blog collapsible category/tags?

**Comment by Nikhil-Ladha** [comment]
Looks fine. Just one last update would be to move the "discuss" callout to the end in case of the mobile view.
Somthing with `display: flex; flex-direction: column-reverse` should do.

**Comment by subhradwip01** [comment]
> Looks fine. Just one last update would be to move the "discuss" callout to the end in case of the mobile view. Somthing with `display: flex; flex-direction: column-reverse` should do.

Sure

**Comment by l5io** [comment]
🚀 Preview for commit ae9e374bb2308fa09f40c450c795123b750e0e2e at: https://6229fe499d0ecf2d3cbd967b--layer5ng.netlify.app

**Review by debo19 — COMMENTED** [review]
Screenshot 2022-03-14 at 2 16 40 AM
Looking good @subhradwip01. One last thing 😅 can you get the Newsletter centre aligned or atleast have the text aligned with "Categories" and "Tags".

**Comment by subhradwip01** [comment]
> Screenshot 2022-03-14 at 2 16 40 AM
> 
> Looking good @subhradwip01. One last thing 😅 can you get the Newsletter centre aligned or atleast have the text aligned with "Categories" and "Tags".

Ya sure

**Comment by subhradwip01** [comment]
Latest update:
Screenshot from 2022-03-14 17-22-58

**Comment by l5io** [comment]
🚀 Preview for commit ef0f595d77b8a1d7012cb856e4fd1b1e11dba1f8 at: https://622f2eec98d33b0e890a8018--layer5ng.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @subhradwip01

**Pull request merged**
