### PR TITLE
Fixed visibility issue

### LINKED ISSUE #4308: Text visibility on Docker Swarm Tutorial Page in Dark Mode
### Description
Text visibility on Docker Swarm Tutorial Page in Dark Mode
Link : https://layer5.io/resources/docker/configuring-highly-available-docker-swarm

### Expected Behavior
Text should be visible on Docker Swarm Tutorial Page in Dark Mode

### Screenshots
Dark mode
darkdocker
Light mode
lightdocker

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vinyashegde**
**Description**

Fixed Text visibility on Docker Swarm Tutorial Page in Dark Mode

This PR fixes #4308 

**Notes for Reviewers**
@Savio629 @leecalcote @Chadha93 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 124dcd48af6fa7b82b1d6f1c5862e8585ab28c8c at: https://647512c1e9d70357f18e3f07--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
LGTM

**Review by goldfishdolphin — APPROVED** [review]
Good job 👍🏽

**Comment by Shivam-AfA** [comment]
Thanks @vinyashegde for this.

**Pull request merged**
