### PR TITLE
Style updates on landscape

### PR DESCRIPTION
**Pull request by aayushdutt**
@leecalcote Let's merge this into feature/spectrum so that @shivaylamba is also on the same page. You might want to take a look a the data yaml file

### CODE REVIEW

**Comment by aayushdutt** [comment]
@leecalcote Oops, was in the middle of merging with upstream master 😅, should have mentioned that.
I'll open a new PR.
I've finished off the landscape spectrum part. Let me know if something needs to be changed

**Comment by leecalcote** [comment]
Ha! No sweat. :)

**Comment by leecalcote** [comment]
@aayushdutt one item to double-check on is the use of Ruby version 2.7.0 in the Gemfile.lock. Master is currently on this version (and Jekyll 4.0).

**Comment by leecalcote** [comment]
@aayushdutt a small item you might address:

Screen Shot 2020-06-09 at 5 06 27 PM

**Pull request merged**
