### PR TITLE
Refactor the graphql queries to JS code for community members

### LINKED ISSUE #2034: Refactor the graphql queries to JS code for community members
**Description**
The GraphQL queries being used in the files under the [Members-Grid](https://github.com/layer5io/layer5/tree/master/src/sections/Community/Members-grid) code is mostly the same (except a few), they differ only in some fields like `badges`, `maintainers`, `meshmates` which makes the query of data every time, for each type of data redundant.

**Expected Behavior**
Update the code to use a more JS approach to filter out the data based on the type needed from the complete set of data.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by riteshsp2000**
**Description**

This PR fixes #2034 

- To solve this issue, I have created a Higher Order Component for all the different categories that will fetch all members data and pass it as a prop
- In each category Member Page, I filter through this data to display as per the category.

**Notes for Reviewers**
- A suggestion was made to implement the feature to showcase users from multiple categories after selecting them (basically allow multiple selections in the drop-down, and depending upon the selected ones, showcase the members)
- The current Component hierarchy is not appropriate, the dropdown being shown is being rendered with the member category components and not the parent. There is also the issue of props drilling which can be fixed very easily with context API.
(Both these changes have been implemented)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@riteshsp2000 Heads up: steps to fix DCO https://github.com/layer5io/layer5/pull/2165/checks?check_run_id=3545574537

**Comment by Tanuj22** [comment]
PR on hold based on the conversation on slack

**Comment by l5io** [comment]
🚀 Preview for commit b1c8d96b93fafb4b5ec158ad15cbc8f30da894cc at: https://6138c96e048bf9d57bdbc764--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Thank you for this PR, @riteshsp2000

**Comment by riteshsp2000** [comment]
Hey @Tanuj22 @leecalcote I have implemented the feature. If you could check and suggest any changes if necessary.

Also, I am not really sure why DCO is failing. I made sure that I signed the commits while committing.

**Comment by l5io** [comment]
🚀 Preview for commit 128fb140d5f36aa40a6e31b12e31f19eb25f300d at: https://613a55d24cc9664fa1ae8f45--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Good work @riteshsp2000, just a few nitpicks,
Could you please position ta filter on the right side, like it is right now, looks better that way.
Also, when hovering over the cross on each category in the filter, there's a rectangular red hover, could you please remove that, maybe on hover the 'x' fills up or anything else.. the red doesn't look good.
Screenshot 2021-09-10 at 12 17 17 AM

**Comment by Tanuj22** [comment]
Apart from what @warunicorn19 mentioned. A bit of padding on the right side of the logo would be nice and the margin between the label and logo can be reduced. 
image

Also, there is a union between the selected options. I thought intersection would be the way to go but not sure now 😬 . @warunicorn19 @Nikhil-Ladha @debo19 what do you think?

**Comment by debo19** [comment]
> Apart from what @warunicorn19 mentioned. A bit of padding on the right side of the logo would be nice and the margin between the label and logo can be reduced.
> image
> 
> Also, there is a union between the selected options. I thought intersection would be the way to go but not sure now 😬 . @warunicorn19 @Nikhil-Ladha @debo19 what do you think?

Even I think intersection will be a better option otherwise selecting even 2 badges at a time is resulting in a long list of members and its not really clear who wears what badge from there.

**Comment by riteshsp2000** [comment]
> Also, there is a union between the selected options. I thought intersection would be the way to go but not sure now 😬 . @warunicorn19 @Nikhil-Ladha @debo19 what do you think? 
> 
> 

Intersection is also easy actually.... a few minor changes might do the job...

**Comment by warunicorn19** [comment]
Yes, +1 , the whole point of the filter is to cut down the list, so intersection would make more sense.

**Comment by Tanuj22** [comment]
@riteshsp2000 go ahead with intersection then

**Review by debo19 — COMMENTED** [review]
meshmates
I think the filter is not reading `meshmates` and `maintainers` at the moment.

**Comment by warunicorn19** [comment]
@Tanuj22 are you getting the filter on left or right? I see @debo19 is getting it on the right side, while I get it on the left🤔.

**Comment by Tanuj22** [comment]
I am getting it on the right. Are you using safari @warunicorn19 ?

**Comment by warunicorn19** [comment]
Nope on chrome itself🤔, on safari as well I'm getting it on the left.

**Comment by Nikhil-Ladha** [comment]
> I am getting it on the right. Are you using safari @warunicorn19 ?

I am also getting it on the left 😓 ... brave browser

**Comment by warunicorn19** [comment]
This is weird😄🤔

**Comment by Tanuj22** [comment]
@riteshsp2000 where are you seeing it? 😆

**Comment by riteshsp2000** [comment]
> @riteshsp2000 where are you seeing it? 😆 

Im seeing it on the right 🤣
Ill check for multiple browsers. But atleast for me, on chrome and firefox it is on the right

**Comment by warunicorn19** [comment]
Cool 😂, We'll see what happens after the changes.

**Comment by riteshsp2000** [comment]
Hey @warunicorn19 @Tanuj22 @debo19 ... I have made all the suggested changes.

**Comment by l5io** [comment]
🚀 Preview for commit 2a4f392644d1da73c1cea1bc26817e7d62788480 at: https://613b1d7206465a96df418425--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@riteshsp2000 one minor nitpick, so when we view a profile and then go back it takes us back to the `active` page, is it possible to make it redirect to the immediate previous page?

https://user-images.githubusercontent.com/53532328/132830128-f25437d7-11c1-49f8-8efa-125bed9fbc58.mov

**Comment by warunicorn19** [comment]
Getting it on the right side now, yay😄

**Comment by riteshsp2000** [comment]
> @riteshsp2000 one minor nitpick, so when we view a profile and then go back it takes us back to the `active` page, is it possible to make it redirect to the immediate previous page?
> 

Okay so regarding this, the member grid is just one page and only a single component is changing and the profile page is a different one, making this happen might require quite a few changes in the routing i guess.

**Comment by warunicorn19** [comment]
🤔makes sense, we could just let it be then. 
Also, if you could follow [this](https://github.com/layer5io/layer5/pull/2165/checks?check_run_id=3565293999) to signoff

**Comment by riteshsp2000** [comment]
> 🤔makes sense, we could just let it be then.
> Also, if you could follow [this](https://github.com/layer5io/layer5/pull/2165/checks?check_run_id=3565293999) to signoff

I'm not really sure why the commits are not signing while I'm committing them.
`git commit -s -m ""`
This is what I'm doing. Is there something else that I need to setup?

**Comment by warunicorn19** [comment]
You'll have to add it to your alias, https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by Tanuj22** [comment]
@riteshsp2000 the all members filter doesn't seem to be working 
image

**Comment by Tanuj22** [comment]
> > thinkingmakes sense, we could just let it be then.
> > Also, if you could follow [this](https://github.com/layer5io/layer5/pull/2165/checks?check_run_id=3565293999) to signoff
> 
> I'm not really sure why the commits are not signing while I'm committing them.
> `git commit -s -m ""`
> This is what I'm doing. Is there something else that I need to setup?

Let me manually flag the dco to pass for now

**Comment by l5io** [comment]
🚀 Preview for commit 82fb76d53292e95dc72fe5e96b29357c74429f4a at: https://613b263b6a6eea9c621c2a87--layer5ng.netlify.app

**Comment by riteshsp2000** [comment]
@Tanuj22 I have resolved the issue.

**Comment by l5io** [comment]
🚀 Preview for commit 2c1474b65dfd25e1fc06035fc185d0bbe4df213e at: https://613b2d9d36dc13b2699b1513--layer5ng.netlify.app

**Comment by Tanuj22** [comment]
@riteshsp2000 if you select any other option with all members it not filtering 
image

**Comment by riteshsp2000** [comment]
@Tanuj22 I guess with this all sorts of errors are fixed 😄

**Comment by l5io** [comment]
🚀 Preview for commit f45336d7d6d36059c68bad8f43ec6e574f070aee at: https://613b5df28c815bdf9e1bdba2--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Thank you @riteshsp2000 for seeing this too the end!

**Pull request merged**
