### PR TITLE
Logos have same text color (white) in darkmode 

### LINKED ISSUE #3220: All logos should have same text color(white) in darkmode
#### Description
On the Projects page, some logos have different text colors in dark mode that is not looking in UI perspective also in the open service mesh logo there is a whitish shade in the "e" alphabet

#### Expected Behavior
All the text in the logos should be of the same color.

#### Screenshots

image
image

#### Environment:
- Host OS:  Windows
- Browser: Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ronitblenz**
Signed-off-by: Ronit Banerjee <ronitbanerjee03@gmail.com>

**Description**

This PR fixes #3220 

**Notes for Reviewers**
Screenshot 2022-10-01 at 7 30 43 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sahilsuman933 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 858f6a185e066980463a85fe6abc3da30a98f488 at: https://6339a32be46692647a834cfe--layer5.netlify.app

**Comment by ronitblenz** [comment]
Can we get it merged?

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
The logos should change based on the theme, i.e, for the dark theme, we should be using the white version while for the light theme the colored logo.
Also, I don't see the logos which Lee provided for Envoy, OPA, and Helm being included in the PR.

Also, for "Traefik Mesh" update the text/imported image name to "Helm" as well.

**Comment by Nikhil-Ladha** [comment]
Reference: [Service Mesh Timeline](https://github.com/layer5io/layer5/blob/master/src/sections/Landscape/ServiceMeshTimeline.js#L46)

**Comment by debo19** [comment]
@ronitblenz any updates?

**Comment by leecalcote** [comment]
Hi @ronitblenz, not hearing back from you by end of day Friday, we'll assume that you have abandoned your effort here and close it out.

**Pull request closed without merging**
