### PR TITLE
Fixed Broken URL

### LINKED ISSUE #2381: Defect: Bad links in Layer5.io/events/kubecon-china-2021
**Description**
The links to "Solving the Service Mesh Adopter’s Dilemma" and "CNCF TAG Network and Service Mesh Working Group" in layer5.io/events/kubecon-china-2021 are broken. 

**Expected Behavior**
The right link to "Solving the Service Mesh Adopter’s Dilemma" can be found [here](https://static.sched.com/hosted_files/kccncosschn21/88/TAG%20Network%20at%20KubeCon%20China%202021.pdf)

The right link to  "CNCF TAG Network and Service Mesh Working Group" can be found [here](https://kccncosschn21.sched.com/?iframe=yes&w=100%25&sidebar=yes&bg=no#)

**Screenshots**
This is the image of the Error message.

broken link

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**
Fixed the broken URL.

This PR fixes #2381

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sahilsuman933** [comment]
@iambami can you please check this PR and approve it.

**Comment by iambami** [comment]
@warunicorn19 please review this, please.

**Comment by sahilsuman933** [comment]
@warunicorn19 Bhaiya could you please review this pull request too?

**Review by leecalcote — APPROVED** [review]
Looking real good, @sahilsuman933 👍 

Thank you.

**Pull request merged**
