### PR TITLE
[Blog] What's new in Kubernetes 1.26

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR adds a blog post on the upcoming K8s release.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f443bd1af75bd0d3fc24f6e0e1720885ddf62dd4 at: https://638d6b1410a4d325a1b3a6ff--layer5.netlify.app

**Comment by leecalcote** [comment]
@Nikhil-Ladha I wonder why the `<code>` formatting is with double line spacing.

**Comment by Nikhil-Ladha** [comment]
Here's the PR which caused this issue 😞 https://github.com/layer5io/layer5/pull/3341
Will send a quick fix.

**Comment by Nikhil-Ladha** [comment]
Fixed it here: https://github.com/layer5io/layer5/pull/3501
If you rebase, you will get the latest changes.

**Comment by leecalcote** [comment]
Oh, I see now. Yes, thank you - this branch is now synced with master.

**Comment by l5io** [comment]
🚀 Preview for commit 4af1969d900a06cf1928143eec85709e7addc247 at: https://638e0227eae33625b6f11a50--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3515d77179a28ea54e96a60cbefa443b1bcee7d2 at: https://638e629164c0211adc29c4f2--layer5.netlify.app

**Pull request merged**
