### PR TITLE
Font Family from “Open Sans” to “Qanelas Soft”

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 150bcb5db0a85da6b8c2b03deefbea3b2db38349 at: https://63d78db0c5ef960050052e7c--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 12da20b68576d662e33d73924af9e74e6f917f2d at: https://63d7e30282cec53428425102--layer5.netlify.app

**Review by Yh010 — APPROVED** [review]

**Comment by UtkarshMishra12** [comment]
@leecalcote Are we good to go with this change? 🤔

**Comment by leecalcote** [comment]
I'd love to hear feedback from others...

**Comment by leecalcote** [comment]
Given @Nikhil-Ladha's blessing, let's proceed. 👍

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Added "Open Sans" as the secondary fallback with "sans-serif" as the final font in the family list.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
