### PR TITLE
created member profile

### LINKED ISSUE #2025: [Community] Member Profile: Joeseph Midura
**Current Behavior**

@josephmidura  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @josephmidura  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @josephmidura 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**

This PR fixes #2025 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Wow thanks  ⚡️@debo19 , Just waiting for the site to build

**Comment by l5io** [comment]
🚀 Preview for commit ffe082abebb3ab5bcd20bcf0280870764d173b32 at: https://61081b8bf5c202f37e0c5545--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM!🎉, Thanks a ton @debo19

**Review by Anita-ihuman — APPROVED** [review]
looks good 👍

**Review by josephmidura — APPROVED** [review]
This looks good. Thank you @debo19

**Comment by leecalcote** [comment]
@josephmidura! 🎈 🥳 

Speaking of Mr. Pivot Tables, here's an item for you to consider - https://discuss.layer5.io/t/mesheryctl-aliases/155/3

**Comment by josephmidura** [comment]
I'll have a look at it 👀

**Pull request merged**
