### PR TITLE
Added Dark Mode

### LINKED ISSUE #972: [NG] Add dark theme to Layer5-NG.
**Current Behavior**

There is only a light theme present currently.

**Desired Behavior**

Add a dark theme to the layer5-ng website.

---
 **Alternatives**

Use this https://www.gatsbyjs.com/plugins/gatsby-plugin-dark-mode/.

 **Additional context**

You can add a dark theme in the theme folder in src.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by geraldmaboshe**
Signed-off-by: Gerald <maboshegerald1@gmail.com>

**Description**
Added dark mode
This PR fixes #972 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b762b6193da5adf1005da225c596883bb84b8886 at: https://606732d83f60d0b37b329bd0--layer5ng.netlify.app

**Comment by adithyaakrishna** [comment]
Hey @geraldmaboshe 
What's the exact color code you used for the dark background? 👀

**Comment by geraldmaboshe** [comment]
> Hey @geraldmaboshe
> What's the exact color code you used for the dark background? 👀

#24271B

**Comment by Nikhil-Ladha** [comment]
There seems to be some issue with the initial usage of the switch, then it works fine. Can you please fix that?
Also, the switcher and the images in the `switch button` is not centered, please update that as well.

**Comment by l5io** [comment]
🚀 Preview for commit 1e6ab7f4893b9f8e923262534aefae2c1efc75c8 at: https://606a617a407c81f394ea1c87--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@geraldmaboshe I think this is a neat idea and I really appreciate this effort. Given the scope of the change, I have a strong suspicion that it will take you presenting this at one of the meetings (either Monday's Websites meeting or Friday's community meeting - https://meet.layer5.io) in order to for it to get the exposure and feedback necessary to gain consensus on it's merge. 

What a great idea for our developer-centered site.

**Comment by geraldmaboshe** [comment]
> @geraldmaboshe I think this is a neat idea and I really appreciate this effort. Given the scope of the change, I have a strong suspicion that it will take you presenting this at one of the meetings (either Monday's Websites meeting or Friday's community meeting - https://meet.layer5.io) in order to for it to get the exposure and feedback necessary to gain consensus on it's merge.
> 
> What a great idea for our developer-centered site.

Thank you, Lee. I'm happy to have this discussed this Friday.

**Comment by vinayaksh42** [comment]
The color feels a bit too greenish to me https://www.colorhexa.com/24271b . Generally, I have seen websites use more of a dark blue color for dark mode (Github for example). We should discuss this point in the meeting as well.

**Comment by Nikhil-Ladha** [comment]
> The color feels a bit too greenish to me https://www.colorhexa.com/24271b . Generally, I have seen websites use more of a dark blue color for dark mode (Github for example). We should discuss this point in the meeting as well.

Dare you speak about, looking too much GREEN infront of @leecalcote 😂

**Comment by l5io** [comment]
🚀 Preview for commit 43f880676de59046c64e95ebf119be5ca9ae2804 at: https://6073d5f4ca631cf61f9b10af--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ed92b9b20a7cb85136c908d3c79a9e6cb14d6ec6 at: https://607a08bed14a1f00b0ba278b--layer5ng.netlify.app

**Comment by geraldmaboshe** [comment]
logos

We may need the light versions of these logos designed by the design team. Thoughts, @Nikhil-Ladha  @leecalcote

**Comment by adithyaakrishna** [comment]
@geraldmaboshe How about if we add `filter: invert(1);` rule to the styling, this will invert the images to white instead of black.

**Proposed Screenshot:**
image

// @Nikhil-Ladha

**Comment by Anita-ihuman** [comment]
@geraldmaboshe whats the progress of this issue?

**Comment by warunicorn19** [comment]
I think we need to put some thought into this, and discuss this design. Closing this PR for now, we could reopen it after we have discussed this through. Thanks @geraldmaboshe for the effort.

**Comment by geraldmaboshe** [comment]
Hey @warunicorn19, so sorry I have been MIA. 

Happy to jump on that design conversation.

Thanks

**Pull request closed without merging**
