### PR TITLE
Added ekoh franklin profile to community/member

### PR DESCRIPTION
**Pull request by gogoiakash2311**
**Description**

Signed-off-by: Akash gogoi gogoiakash09@gmail.com

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sahilsuman933** [comment]
@DeveloperAspire could you please verify your details.

Also, @gogoiakash2311 please do the DCO.

**Comment by gogoiakash2311** [comment]
@sahilsuman933 How can I do the DCO and Do I need to make another PR after I have done the DCO?

**Comment by l5io** [comment]
🚀 Preview for commit 95c37ce7ea1dec4e1e1ffce371a5f045f85ccfa4 at: https://637491be7ab60413845d7395--layer5.netlify.app

**Comment by gogoiakash2311** [comment]
@franklinekoh please verify the details

**Comment by franklinekoh** [comment]
Looks great

**Review by warunicorn19 — APPROVED** [review]

**Comment by gogoiakash2311** [comment]
Thanks, @warunicorn19 for merging my PR!

**Pull request merged**
