### PR TITLE
created the FAQs page in community handbok-siddhantkhariwal w/signoff

### LINKED ISSUE #2225: [Handbook] Create a page for FAQ in the community handbook
**Current Behavior**
The current handbook doesn't have an FAQ section, the questions are [here](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o), some of which are not answered yet.

**Desired Situation**
Create a separate page for FAQ and add the questions from the above document here (https://layer5.io/community/handbook)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by siddhantkhariwal**
Signed-off-by: siddhantkhariwal <siddhant.209301640@muj.manipal.edu>

**Description**

Created FAQs page in community handbook

This PR fixes #2225 

**Notes for Reviewers**
Let me know for any feedback or if I missed any changes. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 28202f8cdbda9b5c113a8cda3b81aa13c3b78878 at: https://616256183311c3469d34028c--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
> LGTM. Not sure if we can change the Q/A font-family thinking. @warunicorn19 What do you think?

We can use `h4` for Questions and `p` for answers.

**Comment by l5io** [comment]
🚀 Preview for commit e78ffa736bd9ade4e9c873b6950c78c0d7037be8 at: https://616e5d87bcf041fac784c57b--layer5ng.netlify.app

**Comment by siddhantkhariwal** [comment]
> @siddhantkhariwal you'll have to pull the changes using `git pull` on the branch you're working on. Then just add FAQ in the TOC in the current format. Try doing that, let me know if you need any help.

@debo19 Thank you for helping me out, I have made a commit ..please look if this Is correct.

**Comment by l5io** [comment]
🚀 Preview for commit 0a1a5f6e0f77f17906ea24988cbc7ae813477729 at: https://617c6eb46961c58aeb72c011--layer5ng.netlify.app

**Review by debo19 — CHANGES_REQUESTED** [review]
Yes, the merge conflict is resolved now. Can we just reduce this space slightly, move the text up to the mark here. It should be good to go after this. 
space

**Comment by l5io** [comment]
🚀 Preview for commit 673ff185c7ab25b483d558a1e84cdfad45262ae9 at: https://617d069ce0b1ae7040b2d133--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
Moving forward with merge. Will add corrections in a holistic review.

**Pull request merged**
