### PR TITLE
Updated Cert Manager Screenshots, under How It Works section

### LINKED ISSUE #4864: [Screenshots] Cert Manager under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/cert-manager) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Cert Manager](https://layer5.io/cloud-native-management/meshery/integrations/cert-manager) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Aarya01Patil**
**Description**

This PR fixes #4864 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c4e7a69ebd6062ce90bae40ef65020f44821c638 at: https://66b22b501e5763214aff7c97--layer5.netlify.app

**Comment by Ashparshp** [comment]
@Aarya01Patil Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by sudhanshutech** [comment]
please keep the image by creating that component specific directory not directly under images. See other example @Aarya01Patil

**Comment by Aarya01Patil** [comment]
Hey @sudhanshutech created the component directory and pushed the new changes , please review and let me know if any further changes are needed

**Comment by l5io** [comment]
🚀 Preview for commit 797a77595c02e73e7e740e015228f30c26adca65 at: https://66c03f729a4e0d2a3faa67b1--layer5.netlify.app

**Comment by Aarya01Patil** [comment]
Hey @vishalvivekm can you please review this PR and let me know if any changes are needed ?

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
will you use webp images @Aarya01Patil ?

**Pull request closed without merging**
