### PR TITLE
Used Full cover photo for SMA Book

### LINKED ISSUE #1658: [Books] Use full cover image for The Enterprise Path to Service Mesh Architectures book
**Description**
This page, https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures, should have an image of the full book cover. The full book cover image is available here - https://raw.githubusercontent.com/layer5io/layer5/master/src/collections/service-mesh-books/the-enterprise-path-to-service-mesh-architectures/The-Enterprise-Path-to-Service-Mesh-Architectures.png

**Screenshots**
Screen Shot 2021-03-02 at 5 04 06 PM

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #1658 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — APPROVED** [review]
Okay, now I remember....ig somewhere I am responsible for this issue 😶, when I updated the filenames earlier...

**Comment by Nikhil-Ladha** [comment]
Thanks @chinmaym07 for the quick fix.

**Comment by l5io** [comment]
🚀 Preview for commit 303403ed6dc2b3d90136ed0baf6b5f20fe2ccb7d at: https://6040935e4a3de893e4f82a89--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@chinmaym07 do you mind fixing the O Reilly book image in the carousel as well, in this PR. I think it would be having a similar issue.

**Comment by chinmaym07** [comment]
> @chinmaym07 do you mind fixing the O Reilly book image in the carousel as well, in this PR. I think it would be having a similar issue.

I was actually thinking to do the same.
I will do the change 👍🏻

**Comment by chinmaym07** [comment]
Hey @Nikhil-Ladha  . I think that O Reilly logo is available only in that size.

**Comment by chinmaym07** [comment]
I have tried increasing the height of the image 
Screenshot_2021-03-04 Service Mesh Books

**Comment by Nikhil-Ladha** [comment]
Ohh, right....I think that would upset @leecalcote considering the disobey of aspect ratio. But, we might want a new image for it.

**Comment by Nikhil-Ladha** [comment]
Let's merge this....and update that later on.

**Comment by leecalcote** [comment]
Ouch. We mustn't _ever_ skew the aspect ratio on images. Especially not on logos, but also... just _never_ do this in the first place.

**Pull request merged**
