### PR TITLE
Blog background black color is removed

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by ashiscs** [comment]
fixes #280

**Comment by gunjanmimo** [comment]
@leecalcote sir, so we need the dark background instead of green ?

**Comment by leecalcote** [comment]
@gunjanmimo essentially, you'll work to ensure that the menu item (e.g. "Workshops") that matches the current page that the user is navigated to (e.g. "/workshops") has a background color.

Currently, when a user navigates to /blog, the "Blog" menu item receives a background color as the **active** hyperlink (menu item). 

See this section of the CSS that controls this behavior - https://github.com/layer5io/layer5/blob/master/_sass/top-nav.scss#L133-L136.

**Comment by leecalcote** [comment]
@gunjanmimo would you like to give this another try?

**Comment by leecalcote** [comment]
At this point, I believe these changes are immaterial.

**Pull request closed without merging**
