### PR TITLE
Created an intra-page for the content of the handbook

### LINKED ISSUE #2256: [handbook] Create an intra-page for the content of the handbook
**Description**
Currently, it is difficult to know the subheading that exists within each section of the handbook.

**Expected Behavior**
We need an intra-page nav for the handbook for that we can easily navigate to each subheading on a section. 
A typical example would be the navigation by the right on [this site.](https://docs.meshery.io/concepts/architecture)

**Screenshots**
Screenshot 2021-10-12 at 01 34 54

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by YashKamboj**
**Description**
Created an intra-page for the content of the handbook
This PR fixes #2256 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b48814d1b17e34e818b7d266068c6e7b1922ea94 at: https://617cf47118edaa274ef0dbf1--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
Hey @warunicorn19 i tried everything , but unable to solve the problem , can you help me a little .

**Comment by l5io** [comment]
🚀 Preview for commit 59bce270f84624607b7d93f2e3a5cff10c756a0a at: https://617f824bf3d23ba09f23a632--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
Hey i am unable to do dco or push any changes ,
Screenshot (3)
Can someone help

**Comment by YashKamboj** [comment]
Hey @warunicorn19 can i make other pr this branch is causing problem , unable to dco

**Comment by warunicorn19** [comment]
Yeah sure @YashKamboj whatever is convenient for you.

**Pull request closed without merging**
