### PR TITLE
 added tooltip on hover effect on the badges of individual member profile page 

### PR DESCRIPTION
**Pull request by DarrenDsouza7273**
**Description**
Added the tooltip on hover effect on badges of individual member profile page.

This PR fixes #4380

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 455048dd7479215d94685d3554d6a5f46adde820 at: https://648a1538cab2c516d11b1f87--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 916b3aaef9a2b7cac134bfc5ae9c487c1b3df467 at: https://648ab5dd199bd04d8240074c--layer5.netlify.app

**Comment by DarrenDsouza7273** [comment]
@Chadha93 can u please review

**Comment by vishalvivekm** [comment]
@DarrenDsouza7273 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Comment by leecalcote** [comment]
Please note that the tooltip gets cutoff. Screenshot from Safari:

**Comment by DarrenDsouza7273** [comment]
> @DarrenDsouza7273 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

sure sure i will

**Comment by DarrenDsouza7273** [comment]
@leecalcote the screenshot you uploaded isnt visible

**Comment by leecalcote** [comment]
Confirmed: the same bug is present in Chrome, too.

**Comment by DarrenDsouza7273** [comment]
@leecalcote will try resolving this issue asap

**Comment by l5io** [comment]
🚀 Preview for commit e4976822ea6524547ab946bbbe1cdaedc4c00ab4 at: https://648fe8f403357624e368d731--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ad27ab39f79e342becaa70e519220ae196d70096 at: https://64967c3693d70726e41f1f2f--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@DarrenDsouza7273 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by DarrenDsouza7273** [comment]
surely will @vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit f5141305cd02f98c67555a0c75bfe543816016db at: https://649906a41428007331eb4533--layer5.netlify.app

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm theres alot of alterations here and there so is it fine if i close this pr and create a new one?

**Comment by vishalvivekm** [comment]
> @vishalvivekm theres alot of alterations here and there so is it fine if i close this pr and create a new one?

Absolutely @DarrenDsouza7273

**Pull request closed without merging**
