### PR TITLE
[MeshMap] Include catalog

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR needs help The catalog doesn't have to be put into the feature slider.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 01a1a3673f1912add7a72ddb3996be6bb2b834e9 at: https://62846c710d95d91f083e84c7--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
@warunicorn19  Ohk understood....I was thinking that catelog should be removed from meshmap-mode...That's why i raised a pr for that...
Now i need to close that

**Comment by warunicorn19** [comment]
Im still on this.

**Comment by warunicorn19** [comment]
@leecalcote merging this incase the action is cached.

**Comment by leecalcote** [comment]
Thanks much

**Comment by warunicorn19** [comment]
I don't understand what's going wrong, everything is perfect locally but the build is still failing.

**Comment by subhradwip01** [comment]
@warunicorn19 is now in focus mode

**Pull request merged**
