### PR TITLE
feat: add testimonial on products page.

### PR DESCRIPTION
**Pull request by 35C4n0r**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
Build preview failed @35C4n0r

**Comment by l5io** [comment]
🚀 Preview for commit 0dd7350d2abbd0c7373e698555f07f9cb5a7085b at: https://6568aab357d79f1be9eae4f4--layer5.netlify.app

**Comment by leecalcote** [comment]
@ritiksaxena124 @35C4n0r I'm hopeful for a split section: book demo on left with single quote on right.

**Comment by leecalcote** [comment]
A bit more of the single quote style as seen on https://layer5.io/cloud-native-management/meshmap

**Comment by l5io** [comment]
🚀 Preview for commit db19a2253e9e7eaf8c196fe1bf5bacd4644809e6 at: https://6568bcf188210308b93eeb0d--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @35C4n0r Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
@35C4n0r how'd we make out on a different social proof layout?

**Comment by abhijeetgauravm** [comment]
Hey @35C4n0r Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by iArchitSharma** [comment]
@35C4n0r are you still there?
can you please fix the merge conflicts

**Comment by sudhanshutech** [comment]
Lets close this @iArchitSharma  and open for other contributors, what say?

**Comment by iArchitSharma** [comment]
created an issue - https://github.com/layer5io/layer5/issues/5612

**Pull request closed without merging**
