### PR TITLE
SEO enhancement of various pages in Collections

### LINKED ISSUE #5064: SEO Enhancements in Collections
### Description of Issue

Various page collections are in need of SEO enhancements as described in @randychilau's message below:

> If you wanted expand your previous work even further in another PR, here are some possible tasks:
> 
> As you mentioned in your notes regarding the `news` pages, there was a field `subtitle` not being used.
>    - to improve SEO for these pages, update the `news` mdx files with a proper `frontmatter` field and content to be shown in the `head` section. Options may include adding content for the `subtitle` field or adding a `description` field and using the first two sentences of the post as content.
>   - find the instructions for creating MDX files in each collection (e.g. `news`) and review/update them to make sure it indicates which fields should be required before publishing and why.
> 
> Other mdx page collections that could benefit from better SEO:
>   - there are MDX files in folders `src/collections/members` and `content-learn` that are using templates that could also be improved. (note: if the content for a potential field may seem too long (e.g. `bio`), you can use javascript techniques to only include a portion of that content in the field).
> 
> Cheers,
> Randy
> 

_Originally posted by @randychilau in https://github.com/layer5io/layer5/issues/4898#issuecomment-1719879317_

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #5064 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2c7c56768eb38bb20aee11a5c7db412efc7d7091 at: https://653a2f0c9f844e7af8f707c9--layer5.netlify.app

**Comment by saurabh100ni** [comment]
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

**Comment by leecalcote** [comment]
@Mohith234, I wonder why this isn't building. Hmm. I'm resyncing this branch with `master` now...

**Comment by leecalcote** [comment]
The changes that you've put in here are very helpful. This is good.

**Comment by leecalcote** [comment]
Found the issue. Duplication key eliminated.

**Comment by l5io** [comment]
🚀 Preview for commit 468ad7454883a56f9938482fdf0d3a6099eff6dc at: https://6567d053d5c1e23403c2ce44--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
