### PR TITLE
community member profile sucessfully added.

### LINKED ISSUE #4786: [Community] Member Profile: Aritra Majumder
**Current Behavior**

@Aritra8438  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aritra8438 s a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Aritra8438 
- Twitter: 
- LinkedIn: [aritra-majumder-juee23](https://www.linkedin.com/in/aritra-majumder-juee23 )
- Meshery Cloud:[1b462fee-7808-4a79-a504-9c4e986f32b9](https://meshery.layer5.io/user/1b462fee-7808-4a79-a504-9c4e986f32b9) 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by brijeshbhikadiya**
**Description**

This PR fixes #4786

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c1fa953f72dc60a25ee06ed6dab2a9e62376fb0b at: https://64f41e498db61166700607e1--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM

**Comment by Ghat0tkach** [comment]
hey @brijeshbhikadiya 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by Aritra8438 — APPROVED** [review]

**Comment by abhijeetgauravm** [comment]
@Chadha93 @leecalcote We can merge this now!

**Comment by leecalcote** [comment]
yay! 🎈

**Pull request merged**
