### PR TITLE
Add Popper component to the sistent components page #5955

### LINKED ISSUE #5955: [Sistent] Add Popper component to the sistent components page
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [Popper](https://github.com/layer5io/sistent/blob/5529c342c6ad2b00b8e8d08deafc02fe72fe5513/src/base/Popper/Popper.tsx).

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The Popper component, currently needs this representation.

### Desired Behavior

Proper documentation for Popper component, similar to Button component on https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation of the the function that the component serves in context of it's usage.
- Code examples.
- Stylistic guidelines to be followed while using the component in code (if any).

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 🎨 See [Sistent Repository](https://github.com/layer5io/sistent).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Vidit-Kushwaha**
**Description**
Add Popper component to the sistent components page

- Added explanation of the function popper component and it's usage.
- Code examples.
- Stylistic guidelines to be followed.

This PR fixes #5955 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

Screenshot: 
Screenshot_19-10-2024_231157_fuzzy-space-fishstick-x6v6q4pvp9vh6gwg-9000 app github dev

Screenshot_19-10-2024_231955_fuzzy-space-fishstick-x6v6q4pvp9vh6gwg-9000 app github dev

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 53e9d14a80fd16450890a34678ad72b94fdd2eb3 at: https://6713f5bc840ac7f4e4a76be9--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Vidit-Kushwaha 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by vishalvivekm** [comment]
> @Vidit-Kushwaha Thank you for your contribution! Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).
> 
> Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

adding

**Comment by l5io** [comment]
🚀 Preview for commit 88313e58de8f12449bc24849927e00ce3baeab3a at: https://6716640cc892345253f86186--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b471863509c88d36695fc89fb2805d38a0d6c099 at: https://6717e0a6a04c4e34f7ab8e85--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 00de1c05514ade9b2ff91a5af99a48a0e915abdc at: https://6717f1e03fdedc867693b842--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
