### PR TITLE
[Nighthawk] UI cards not responsive on nighthawk page fix

### LINKED ISSUE #2766: [UI] Cards not fully responsive in Distributed Performance Management section
**Description**

On the [nighthawk page](https://layer5.io/projects/nighthawk), the cards are not fully responsive.

**Expected Behavior**

The cards should be responsive and their heights should be the same. Also, a little bit of spacing between the text sections in individual cards would make the cards look even better. It will make the cards look more consistent with the overall design of the website. 

**Screenshots**

Cards1
cards2
cards3

**Environment:**
- Host OS: Windows 11
- Browser: Google Chrome

**I would love to work on this issue.**

---
[Optional] **Additional Context**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by indraantoor**
**Description**

This PR fixes #2766 

**Notes for Reviewers**
The cards are fully responsive now and more consistent with the overall design of the website. They adapt the 2 cards on first row and 3rd on the second row in the center format. I gave space in between the individual card elements and wrote the code for the cards into a "_CardsContainer_" using styled components, so that it can be maintained conveniently. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2e1bfc1f705794642aad039a9d9a180fa15904ab at: https://62853c54f0ce4d1d1fd14047--layer5ng.netlify.app

**Review by NikhilSharma03 — APPROVED** [review]
LGTM

**Comment by subhradwip01** [comment]
LGTM

**Review by Akshit42-hue — COMMENTED** [review]
Great work @indraantoor, but in the mobile view the cards are still not responsive

**Comment by Nikhil-Ladha** [comment]
> Great work @indraantoor, but in the mobile view the cards are still not responsive

I don't see at which ratio the cards are still not responsive. Could you help me out with that @Akshit42-hue ?

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Akshit42-hue** [comment]
In the mobile view all the cards are not uniform 
Here is the screenshot 
Uploading Screenshot fr
![Screenshot from 2022-05-22 17-44-32
om 2022-05-22 17-44-50.png…]()
// @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Ok, so when you meant uniform you meant height?
How can that possibly be? Each card has different amount of content so it is obvious to have different heights. I don't see any issue with that.

**Pull request merged**
