### PR TITLE
correct Order of Section Titles on Recognition Page

### LINKED ISSUE #5111: Incorrect Order of Section Titles on Recognition Page
### Description
Incorrect Order of Section Titles on Recognition Page
image

### Expected Behavior
The table of contents of section titles should be swapped

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by jayesnc2512**
### Before
282225094-9ca36b4d-2bd0-4293-819f-19d2936a9e48
### After Update
Screenshot 2023-11-11 214447

**Description**
This pull request addresses an issue where the section titles on the Recognition Page were displayed in an incorrect order. The table of contents has been adjusted to ensure the proper sequence of section titles.  The issue has been successfully resolved, and the corrected section title order improves the overall user experience on the Recognition Page.

**Resolved Issue:**
The section titles on the Recognition Page were initially presented in a swapped order, leading to confusion for users. This pull request corrects the table of contents, ensuring that section titles are now displayed in the expected and logical sequenc

This PR fixes #5111

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Hey @jayesnc2512  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by leecalcote — APPROVED** [review]
Thanks, @jayesnc2512

**Comment by leecalcote** [comment]
It'd be good to have you on the meeting that @abhijeetgauravm has invited you to. We'll be discussing the need for this to be dynamic.

**Comment by jayesnc2512** [comment]
Thank you inviting me.
I'll surely be there for the meeting.

**Pull request merged**
