### PR TITLE
fixed video iframe on GSOC page 

### LINKED ISSUE #1076: Wrong alignment of Layer5 intro video.
**Description**
The intro video is left aligned which hides some part of the video.

**Expected Behavior**
It should be centered so that the whole video is properly visible.

**Screenshots**

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/programs/gsoc
2. Scroll down to the video

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

The YouTube video is out of the page when viewed on a mobile device as shown below:

Screenshot from 2020-11-06 11-33-45

This is fixed by setting the iframe size to percentages instead of pixel values. And the fixed version is shown below:

Screenshot from 2020-11-06 11-25-23

And on the web:

Screenshot from 2020-11-06 11-25-12

This PR fixes #1076 

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@navendu-pottekkat Thanks for this change. A bit of alignment is also required to work upon on the same page. Can you do that too?

**Comment by navendu-pottekkat** [comment]
> @navendu-pottekkat Thanks for this change. A bit of margins and word wrapping is also required to work upon on the same page. Can you do that too?

Do you mean this?

Screenshot from 2020-11-06 11-50-34

The rest looks fine to me.

**Comment by Jashpatel1** [comment]
> > @navendu-pottekkat Thanks for this change. A bit of margins and word wrapping is also required to work upon on the same page. Can you do that too?
> 
> Do you mean this?
> 
> Screenshot from 2020-11-06 11-50-34
> 
> The rest looks fine to me.

Yes.

**Comment by navendu-pottekkat** [comment]
> > > @navendu-pottekkat Thanks for this change. A bit of margins and word wrapping is also required to work upon on the same page. Can you do that too?
> > 
> > 
> > Do you mean this?
> > The rest looks fine to me.
> 
> Yes.

I will try it.  Should I make it a new PR?

**Comment by Jashpatel1** [comment]
> > > > @navendu-pottekkat Thanks for this change. A bit of margins and word wrapping is also required to work upon on the same page. Can you do that too?
> > > 
> > > 
> > > Do you mean this?
> > > The rest looks fine to me.
> > 
> > 
> > Yes.
> 
> I will try it. Should I make it a new PR?

You can do whatever suits you. Its fine with any of the above.

**Comment by navendu-pottekkat** [comment]
@Jashpatel1 Fixed.

Before:

Screenshot from 2020-11-06 12-23-33

After:

Screenshot from 2020-11-06 12-25-12

Should I create an issue so that we can track it or is this enough?

**Comment by Jashpatel1** [comment]
> @Jashpatel1 Fixed.
>
> 
> Should I create an issue so that we can track it or is this enough?

Great work. Can you do the same for text present above the video?
image

**Comment by navendu-pottekkat** [comment]
> Great work. Can you do the same for text present above the video?
> image

I think the current one looks better. Like Project idea -- sub category --> SMI Conformance Testing -- sub category --> Description etc. The indentation looks good right?

**Comment by Jashpatel1** [comment]
> > Great work. Can you do the same for text present above the video?
> 
> I think the current one looks better. Like Project idea -- sub category --> SMI Conformance Testing -- sub category --> Description etc. The indentation looks good right?
> 

Yaa the indentation is good  But I think some initial margin is also present. Can you please check? If not, we can go on with this PR.

**Comment by navendu-pottekkat** [comment]
> Yaa the indentation is good But I think some initial margin is also present. Can you please check? If not, we can go on with this PR.

Yes you are right. I will even it out like the one before. I will add a new commit

**Comment by navendu-pottekkat** [comment]
Screenshot from 2020-11-06 12-51-53

**Comment by navendu-pottekkat** [comment]
@Jashpatel1 I think we can merge now

**Review by Jashpatel1 — APPROVED** [review]
@navendu-pottekkat Thanks for taking care of the changes requested. Congratulations on your first contribution to Layer5.

**Comment by navendu-pottekkat** [comment]
@Jashpatel1 Thanks! Always feels great when you merge the first PR

**Pull request merged**
