### PR TITLE
Update multiple files with unnecessary code.

### LINKED ISSUE #4521: [UI]: unwanted {" "} in blog content
### Description

There is unwanted {" "} at couple of parts in the blog post of https://layer5.io/blog/community/meet-the-fall-interns-of-2021

### Expected Behavior

Let's remove them.

### Screenshots

image

image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by depleur**
**Description**

This PR fixes #4521 

**Notes for Reviewers**

Fixed multiple instances of the `{" "}` string in code.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8382eed975c4eaadca855c5dd2e7c12d9521f78f at: https://64acfda428607248eb46b9e2--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
@randychilau are you addressing this in your open PR, if so I would have to politely ask @depleur to close out this PR in your favour to avoid unwanted hustle

**Comment by randychilau** [comment]
> @randychilau are you addressing this in your open PR

Hi @Nikhil-Ladha,

Thanks for the message.

I did not address the instances of `{" "}` in mdx files in my PR, and do not believe there is any overlap/conflict with this PR. 

Cheers,
Randy

**Comment by depleur** [comment]
Hey, I accidentally added a commit to this PR which actually should be in a PR of its own as it resolves another issue. Is there anything I can do?

**Comment by Nikhil-Ladha** [comment]
> Hey, I accidentally added a commit to this PR which actually should be in a PR of its own as it resolves another issue. Is there anything I can do?

Undo the changes and commit them

**Comment by depleur** [comment]
Hey, can someone help me with conflict resolution on the index.js file?

**Comment by vishalvivekm** [comment]
@depleur 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by samyakshah3008** [comment]
Hi @depleur you are left to sign off the DCO check as well. 
Please do

**Comment by Chadha93** [comment]
@depleur heads-up: merge conflicts...

**Comment by thisiskaransgit** [comment]
Hey @depleur, let's wrap this up soon, also please update the PR title 🙄

**Comment by leecalcote** [comment]
Thanks for this, @depleur. 

P.S. Smaller PRs = Quicker review. :)

**Comment by Chadha93** [comment]
@depleur... Reminder, let's close this pr if not updated by Friday.

**Comment by abhijeetgauravm** [comment]
Closing this as the issue is fixed by #4715 .

**Pull request closed without merging**
