### PR TITLE
Update text color on 404 page

### LINKED ISSUE #3961: [Dark Mode] Update text color on 404 page
### Description
A small update is needed to make the 404 page dark mode friendly.

### Expected Behavior
"Page does not exist" should be in a light font color.

### Screenshots
Screenshot 2023-03-15 at 5 07 00 PM

### Environment:
- Host OS: macOS
- Browser: Safari

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by weilirs**
**Description**

This PR fixes #3961 

**Notes for Reviewers**
Lighten the text color of the error message "page does not exist." on 404 page.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by hirentimbadiya — COMMENTED** [review]
as in issue @leecalcote said @weilirs removed dark grayish color and eventually it gets white color , so looks good to me @leecalcote and @Chadha93 can approve this PR.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks for reviewing, @hirentimbadiya.

@weilirs, please ensure that consideration is given to support both light and dark mode. There are other examples that are helpful to reference in other areas of the site in terms of how to do this.

**Comment by weilirs** [comment]
I think now it supports both light and dark mode @leecalcote

**Comment by l5io** [comment]
🚀 Preview for commit 7e6b7702d6686dca73558b1fdac692dcfcb63024 at: https://64151a3ba5113f6d5fbaead1--layer5.netlify.app

**Review by himanshu1221 — APPROVED** [review]
It works well for both dark as well as light themes 
LGTM :+1:

**Pull request merged**
