### PR TITLE
Fix: Service mesh labs menu options

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@leecalcote check this now.

**Comment by leecalcote** [comment]
Argh. Lost electricity. Trying now...

**Comment by leecalcote** [comment]
Haha! Bingo! This works. 😄 Who's da man?

**Review by leecalcote — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
> Haha! Bingo! This works. 😄 Who's da man?

Awesome 😎

**Pull request merged**
