### PR TITLE
Migrated Landscape Page

### LINKED ISSUE #714: [NG] Migrate the site data for the Landscape page (Resources section)
**Description**
Currently, the following pages on the Resources section on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error:

- [ ]  [Service Mesh Comparison](https://layer5ng.netlify.app/landscape)
- [ ] [Service Mesh Tools](https://layer5ng.netlify.app/landscape#tools)

[Service Mesh Books](https://layer5ng.netlify.app/learn/books) - Issue #780 
[Service Mesh Workshops](https://layer5ng.netlify.app/learn/workshops) - Issue #781 

**Expected Behavior**

The data can be sourced from the following pages on the [layer5.io site](https://layer5.io/):

- [Service Mesh Comparison](https://layer5.io/landscape)
- [Service Mesh Tools](https://layer5.io/landscape#tools)
- [Service Mesh Books](https://layer5.io/books)
- [Service Mesh Workshops](https://layer5.io/workshops)

**Note**

**Individual PR's may be opened by different contributors for the four pages separately. Kindly add `This PR references #"Issue-number"` to your PR when you attempt to do so.**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by geraldmaboshe**
Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>

**Description**
Migrated Landscape Page

This PR fixes #714 

**Notes for Reviewers**
N/A

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Progress. 👍 
Screen Shot 2020-10-15 at 11 59 02 AM

**Comment by Nikhil-Ladha** [comment]
Just a question, we won't be changing the design?

**Review by leecalcote — APPROVED** [review]
Good looking draft. Considering that the site isn't live, we can merge in-progress work, so as to move forward iteratively.

It'd be good to have a look at some of the prior art here in terms of comparative spectrums to identify ways in which we can convert much of the tabular data into visualizations.

**Comment by geraldmaboshe** [comment]
> Good looking draft. Considering that the site isn't live, we can merge in-progress work, so as to move forward iteratively.
> 
> It'd be good to have a look at some of the prior art here in terms of comparative spectrums to identify ways in which we can convert much of the tabular data into visualizations.

Sounds good.

**Pull request merged**
