### PR TITLE
modifications: corrected the gsoc link under partner page

### LINKED ISSUE #2590: [Bug] Broken link of GSOC on the partners page
**Description**

Broken link of GSOC on the partners page.  https://layer5.io/partners
**Expected Behavior**

Redirect it to https://layer5.io/programs/gsoc
**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Simba-97**
Signed-off-by: Hritik Kumar Singh <singhhritik978@gmail.com>

Modified and corrected the gsoc-link under the Partners page, now proper redirection to the correct url.

This PR fixes #2590 

@YashKamboj here are the requested changes in the task, Please review and let me know if any changes are required.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Simba-97** [comment]
@YashKamboj I have made the necessary changes. Please review and request code changes if any.

**Comment by l5io** [comment]
🚀 Preview for commit 5d0fd07229f1db934771340d42b56ac077e074cf at: https://6201776742ef9747db2ca454--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉 Thank you @Simba-97

**Comment by Simba-97** [comment]
You're welcome @warunicorn19 . It was great contributing to your project :)

**Pull request merged**
