### PR TITLE
Revert "Fixed Image Rendering Issue and Updated Makefile"

### PR DESCRIPTION
**Pull request by leecalcote**
Reverts layer5io/layer5#1796

### CODE REVIEW

**Comment by Tanuj22** [comment]
@leecalcote This will break it in other places also. Let fix the issue now

**Comment by leecalcote** [comment]
Ok. I'm not sure what issue was being addressed by https://github.com/layer5io/layer5/pull/1796

**Comment by l5io** [comment]
🚀 Preview for commit fd22b3305f1d770d3e401a301f409aece2859f0f at: https://607dde7b9a224e1aac9927b0--layer5ng.netlify.app

**Comment by Tanuj22** [comment]
Fixed in #1800

**Pull request closed without merging**
