### PR TITLE
[Community] Member Profile: Vivek Vishal

### LINKED ISSUE #3969: [Community] Member Profile: Vivek Vishal
**Current Behavior**

@vishalvivekm has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @vishalvivekm
- Twitter: https://twitter.com/vishalvivekm
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sidharthviz**
**Description**

This PR fixes #3969 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 88ee7600bb8defbb123e29c5ccf1bab361d3c10c at: https://641802e522b59b7221081202--layer5.netlify.app

**Comment by sidharthviz** [comment]
Hi @vishalvivekm Please review the profile details. 
Thank you

**Comment by vishalvivekm** [comment]
> Hi @vishalvivekm Please review the profile details. Thank you

Hi @sidharthviz 
I'd like to have a bio for me, that I'll be dropping in here after my college, if that's okay for you ?
Thanks

**Comment by sidharthviz** [comment]
> > Hi @vishalvivekm Please review the profile details. Thank you
> 
> Hi @sidharthviz I'd like to have a bio for me, that I'll be dropping in here after my college, if that's okay for you ? Thanks

Sure @vishalvivekm 👍🏼

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@sidharthviz please use only username only in twitter and linkedin instead of writing whole link and also bio when @vishalvivekm provides.

**Comment by sidharthviz** [comment]
> 

Sure @hirentimbadiya  Thank you

**Comment by Chadha93** [comment]
// @vishalvivekm

**Comment by vishalvivekm** [comment]
> // @vishalvivekm

Yes
@sidharthviz :

Vivek Vishal is a passionate CS undergrad from India who loves to explore new technologies and contribute to Open-Source projects. With proficiency in various programming languages, including Java, C++, C, Bash, and JavaScript, he possesses a profound understanding of SQL, Git, and Command-line tools. Vivek has a strong inclination towards Maths and a keen interest in Machine Learning, constantly expanding his knowledge and skillset. As an active member of the Layer5 community, he eagerly participates in community events and discussions, both to learn and to assist others in getting started with Layer5 projects or other Open-Source endeavors. Don't hesitate to connect with him on his socials below:

**Pull request closed without merging**
