### PR TITLE
Member Profile of archit sharma added

### LINKED ISSUE #5024: [Community] Member Profile: Archit Sharma
**Current Behavior**

@iArchitSharma has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @iArchitSharma as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @iArchitSharma
- Twitter: [IArchitSharma](https://twitter.com/IArchitSharma)
- LinkedIn: https://www.linkedin.com/in/iarchitsharma/
- Meshery Cloud: 
- Link to profile picture: [Image](https://media.licdn.com/dms/image/D4D03AQEOedBLI8sjbw/profile-displayphoto-shrink_800_800/0/1692993231433?e=1702512000&v=beta&t=IG-5G7Kyzz3_Oec9Sib8Taphvh1vUGcIQ9a9ov83v5E)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Description**

This PR fixes #5024 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
image

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e183618a343a87e1bd9ca537ef43305f1a0be6b7 at: https://65280f5cb12eff3154dbbf5d--layer5.netlify.app

**Comment by EraKin575** [comment]
please put a screenshot and a change to a valid PR name.Really helps with the review

**Review by abhijeetgauravm — COMMENTED** [review]
Hey @VivekBaldha0712 some commit unrelated to the issue is also getting reflected in the PR. Rest looks good!

**Review by iArchitSharma — COMMENTED** [review]
why is there a change made to the svg?

**Comment by VivekBaldha0712** [comment]
Reverted unwanted changes.

**Comment by l5io** [comment]
🚀 Preview for commit 0a6c7a29bb194f3c2f80913eb4c24af687913da8 at: https://6528abb930e4aa5558ba75b4--layer5.netlify.app

**Review by iArchitSharma — APPROVED** [review]
LGTM

**Review by abhijeetgauravm — APPROVED** [review]
Thanks for the contribution @VivekBaldha0712 . LGTM!

**Comment by abhijeetgauravm** [comment]
> LGTM

// @ritiksaxena124 @sudhanshutech

**Comment by ritiksaxena124** [comment]
LGTM 🚀

**Pull request merged**
