### PR TITLE
Added Modal Component

### LINKED ISSUE #5519: [Sistent] Implement Modal component page
### Current Behavior
There is no page for Modal in [Sistent](https://layer5.io/projects/sistent/components)

### Desired Behavior
Implement the modal page using this [Figma mockup](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=5209%3A13685&mode=design&t=qP2uRkuetMXltHDo-1)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #5519

**Notes for Reviewers**
@sudhanshutech Can you please review this?

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 52a82f0f1f1c9d208ee6c8d0c7624388af340957 at: https://66824385f102c1d8bac4e00f--layer5.netlify.app

**Comment by Deepak0320Singhal** [comment]
@hargunkaur286 Thank you for your contribution.
Let's discuss this on Websites's call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by sudhanshutech** [comment]
what is the progress @hargunkaur286 ?

**Comment by sudhanshutech** [comment]
@hargunkaur286 what issue you are having when using sistent only modal components. I wonder we should not make here a custom one

**Comment by iArchitSharma** [comment]
@hargunkaur286 ?

**Pull request closed without merging**
