### PR TITLE
[Fix] Responsiveness of first hero banner

### LINKED ISSUE #2868: [Hero] Responsiveness of first hero banner
**Description**
Text is overlapped the two "5" cards, but should not be.

**Expected Behavior**
Text should be responsive - as large as possible without overlapping the graphics.

**Screenshots**
Screen Shot 2022-06-06 at 6 21 57 PM

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by VaibhavArora19**
Signed-off-by: Vaibhav Arora <aroravaibhav817@gmail.com>

**Description**

This PR fixes #2868

**Current Behaviour**
Layer5

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Building preview..

**Comment by l5io** [comment]
🚀 Preview for commit d89d378ffd537b24d31e18b3f704db6bcbbaa347 at: https://62a1e0fe293a1a70555d3eee--layer5.netlify.app

**Comment by leecalcote** [comment]
Screen Shot 2022-06-09 at 8 42 06 AM
Will you kindly address the overlapping in this other banner version, too?

**Comment by leecalcote** [comment]
@VaibhavArora19 I'm hopeful that you can find a way to get the "of developer-defined infrastructure" to stay on a single line by adjusting margins (not using `white-space: nowrap;`)

**Comment by VaibhavArora19** [comment]
I think that will make the text too small considering for every screen size!

**Comment by leecalcote** [comment]
> I think that will make the text too small considering for every screen size!

Humor me.

**Comment by VaibhavArora19** [comment]
sc

Will that work?

**Comment by l5io** [comment]
🚀 Preview for commit aac169d06f3b70b0fcd90e309f8964ed357dfdaf at: https://62a237a8e2278b1cc43d774b--layer5.netlify.app

**Comment by leecalcote** [comment]
Yes, that'll work. As of the last deployment preview, the same issues are still present with both the first and second banner.

**Comment by VaibhavArora19** [comment]
@leecalcote can you check now?

**Comment by l5io** [comment]
🚀 Preview for commit 28692f38bd8409dbcf5daa96caf9783edb4ce0c2 at: https://62a36464d4616f5f9f77c5ce--layer5.netlify.app

**Pull request merged**
