### PR TITLE
Make SVG responsive on page: /cloud-native-management/meshmap/collaborate

### LINKED ISSUE #4191: SVG disappears on smaller screens
### Description
When the screen size is reduced, the SVG image disappears and becomes 0x0 in size. This issue occurs because the SVG element is not properly responsive to smaller screen sizes. 
Link : https://layer5.io/cloud-native-management/meshmap/collaborate

### Expected Behavior
The svg should be visible for smaller devices 
### Screenshots

https://user-images.githubusercontent.com/91362589/236462940-32e5bc22-233a-47a0-9bc2-ec89f4e498a0.mp4

### Environment:
- Host OS: Windows/Android
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by aku1310**
**Description**

This PR fixes #4191 

**Notes for Reviewers**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1650b363d09b7c3ff61c7c21771687c51f069906 at: https://645699938f69eb4e25488483--layer5.netlify.app

**Comment by Savio629** [comment]
@aku1310 Was there any reason you made the width of svg to 80% rather than 100%?

**Comment by aku1310** [comment]
> @aku1310 Was there any reason you made the width of svg to 80% rather than 100%?

Apologies, 100% width is functioning perfectly. I realized that it not working properly yesterday was due to my mistake with the local development, and not with the functionality of 100% width, which have since been resolved. Thank you for bringing it to my attention, fixing it now.

**Comment by l5io** [comment]
🚀 Preview for commit 7043710a2b8076eba6041899634df6dd51de3eca at: https://6457e3eec2f36f07af0359c0--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@aku1310 Let's discuss this on websites call. Add this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would :)

**Comment by Savio629** [comment]
No worries @aku1310
LGTM 👍

**Review by Savio629 — APPROVED** [review]

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Pull request merged**
