### PR TITLE
fixed spelling error in readme

### PR DESCRIPTION
**Pull request by wesley-moody**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by PluckyPrecious** [comment]
Hello @wesley-moody thank you for your contribution 🥳, the PR need a little touch and we are good to go.

1. Run this command to sign [DCO](https://github.com/layer5io/layer5/pull/717/checks?check_run_id=1072578375) : `git commit --amend --signoff`
next run `git push --force-with-lease origin readme-spelling`
2. Edit description section This PR fixes #issuenumber 
3. Add a small letter `x` in the signed commits box 

Do visit the Layer 5 [slack community](Slack.layer5.io), we will be glad to have you.😊

**Review by Jashpatel1 — APPROVED** [review]

**Comment by PluckyPrecious** [comment]
@leecalcote @Jashpatel1 this issue has been and fixed by another contributor.

**Comment by Jashpatel1** [comment]
Closing this as a matter of duplicancy. The issue is already been resolved. @wesley-moody you can look out for some other open issues.

**Review by leecalcote — APPROVED** [review]
@wesley-moody thank you for this. Looks good. 👍

**Comment by wesley-moody** [comment]
@leecalcote, thank you. I'll be sure to give a heads up in the future, thanks for accepting the contribution!

**Comment by leecalcote** [comment]
@wesley-moody awesome. 😄

**Pull request merged**
