### PR TITLE
[community] Member profile : Chinu Anand

### LINKED ISSUE #3845: [Community] Member Profile:@chinu-anand
**Current Behavior**
 
<@chinu-anand > has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@chinu-anand> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @chinu-anand 
- Twitter - https://twitter.com/chinustwt
- Linkedin - https://www.linkedin.com/in/chinu-anand/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by roopeshsn**
**Description**

Created a community page for @chinu-anand 

This PR fixes #3845 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3cae65752420dcffa02c58d128093db32eced322 at: https://640165e9a8023c67b3c96731--layer5.netlify.app

**Comment by roopeshsn** [comment]
Here you go @chinu-anand https://640165e9a8023c67b3c96731--layer5.netlify.app/community/members/chinu-anand

**Comment by ayushthe1** [comment]
Congrats @chinu-anand 🥳

**Review by Nikhil-Ladha — APPROVED** [review]
Hooray 🎉

**Pull request merged**
