### PR TITLE
chore: updates to members page

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

- Members Gird Page
- SIngle Members Page
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@leecalcote doubt regarding these two points - 
- Change font for name to light gray. - Won't this make the name unreadable for inactive members card? 
- Change from light green to dark green - This was already from before. Did you mean the dark green to light green?

**Comment by vinayaksh42** [comment]
Upon hovering over the meshmates logo inside the single-member page the logo becomes invisible 
chrome_xiLSk0BRo7
chrome_vFjCb4Qud3

**Comment by leecalcote** [comment]
> @leecalcote doubt regarding these two points -
> 
> * Change font for name to light gray. - Won't this make the name unreadable for inactive members card?
> * Change from light green to dark green - This was already from before. Did you mean the dark green to light green?

@Tanuj22 

1. You're right. We can either leave the name color as-is or consider the name color on an inactive card separately.
1. This shorthand note is too concisely written. It was intended to state that we can move to having a dark green background for active members that changes to light green on hover of the card.

- the MeshMate badge hanging off the lower, right hand corner of the profile picture looks awesome. Perhaps, this badge can be added on the MeshMate profiles on /community/meshmates, too.
- 
Screen Shot 2020-11-22 at 8 42 21 PM

**Comment by Nikhil-Ladha** [comment]
I think we decided on to remove the skill section and just keep the icons of the projects with links to there github repo, to which the user has contributed. Isn't so?
/cc @leecalcote @Tanuj22 ?

**Comment by Nikhil-Ladha** [comment]
Also, another thing is shall we keep the circular white ring/border around the icons or remove it?
If you ask me, I would suggest to remove it.

**Comment by Tanuj22** [comment]
> I think we decided on to remove the skill section and just keep the icons of the projects with links to there github repo, to which the user has contributed. Isn't so?
> /cc @leecalcote @Tanuj22 ?

Yes. I will do it separately. @leecalcote which projects should I consider?

**Comment by Tanuj22** [comment]
> Also, another thing is shall we keep the circular white ring/border around the icons or remove it?
> If you ask me, I would suggest to remove it.

I agree. Removing it...

**Comment by Nikhil-Ladha** [comment]
> Yes. I will do it separately. @leecalcote which projects should I consider?

I think any project under Layer5 ONLY.

**Comment by Nikhil-Ladha** [comment]
Wondering, if we can have any Github API for this, so that it becomes dynamic and we won't have to change it periodically.

**Comment by leecalcote** [comment]
Ideally, all links are internal to the layer5.io site. For example, Meshery logo linked to layer5.io/meshery

**Comment by leecalcote** [comment]
The white outline onhover of the buttons is a desired effect. It would be nice to keep this.

**Comment by leecalcote** [comment]
Yes, only icons for Layer5 projects.

**Comment by Tanuj22** [comment]
@leecalcote @Nikhil-Ladha please check these

**Comment by Nikhil-Ladha** [comment]
Screenshot from 2020-11-24 12-52-07
The colors for the cards in the image for Active/Inactive is what @leecalcote was trying to say earlier. That is, for the Active card we should be having the card with our main color (#3c494f), and for the Inactive card the gray color is fine. On hovering, the cards make the active card color to the lighter version i.e, (#00d3a9) and the Inactive card a bit more light gray to something like the image which is (#c7c7c7).
Also, I have added a `filter: grayscale(1)` property for the Inactive cards, to give it a bit more feeling.

**Comment by Nikhil-Ladha** [comment]
And, while you are there it will be good to add a legend for colors in the filter dropdown too.

**Comment by Tanuj22** [comment]
> And, while you are there it will be good to add a legend for colors in the filter dropdown too.

This is being done in #1075

**Comment by Jashpatel1** [comment]
I guess we will have to reduce the image size in individual member pages because many images come from profile images on Github, Twitter or Linkedin, etc, and look like extra zoomed(less clarity) on individual pages.

**Comment by Nikhil-Ladha** [comment]
The cards still do not have the dark green color(#3c494f), @Tanuj22

**Comment by Nikhil-Ladha** [comment]
> I guess we will have to reduce the image size in individual member pages because many images come from profile images on Github, Twitter or Linkedin, etc, and look like extra zoomed(less clarity) on individual pages.

Like, dynamically fetched?

**Comment by Jashpatel1** [comment]
> > I guess we will have to reduce the image size in individual member pages because many images come from profile images on Github, Twitter or Linkedin, etc, and look like extra zoomed(less clarity) on individual pages.
> 
> Like, dynamically fetched?

No, but the local copy comes from this sites I guess.

**Comment by Tanuj22** [comment]
> The cards still do not have the dark green color(#3c494f), @Tanuj22

@Nikhil-Ladha this is the gray color of layer5 :thinking:

**Comment by Nikhil-Ladha** [comment]
> > The cards still do not have the dark green color(#3c494f), @Tanuj22
> 
> @Nikhil-Ladha this is the gray color of layer5 🤔

Yeah, it's actually green only. But yeah, this color itself.

**Comment by Tanuj22** [comment]
> > > The cards still do not have the dark green color(#3c494f), @Tanuj22
> > 
> > 
> > @Nikhil-Ladha this is the gray color of layer5 thinking
> 
> Yeah, it's actually green only. But yeah, this color itself.

I hope I used the correct colors this time :see_no_evil:

**Comment by Nikhil-Ladha** [comment]
Well, you did 😆

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
