### PR TITLE
Logo has been changed

### LINKED ISSUE #5015: Change the color of Meshery logo to keppel green
### Description

Color of the Meshery logo is white. It should be Keppel Green.

### Screenshots

image

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Description**

This PR fixes #5015 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e3f15b9d9020ac04d4fa66ff134e041d76282602 at: https://6526115579509c77faacbb98--layer5.netlify.app

**Comment by Mohith234** [comment]
@VivekBaldha0712 The changes look good but do you think we can increase the size a bit? The previous logo looks bigger than the current one.

What are your thoughts on it?

**Review by Mohith234 — APPROVED** [review]
Never mind, It looks good although.

**Comment by VivekBaldha0712** [comment]
@Mohith234 , Yes the previous logo is bigger but this one also looks good. It will not impact a lot

**Comment by sudhanshutech** [comment]
@VivekBaldha0712 it's a good practice when making pr to write a descriptive message that should tell where this change has been made, so we can review and merge pr's soon

**Comment by sudhanshutech** [comment]
So where is this changes on which page?

**Review by Gautam-04 — COMMENTED** [review]
The PR looks good, but could you also mention where these changes were made? Alternatively, you could try adding screenshots of the changes.

**Pull request merged**
