### PR TITLE
now service mesh pattern project name is under box

### LINKED ISSUE #2676: [UI] Service Mesh pattern project name out of card
**Current Behavior**

- **service mesh pattern** project name is out of the card on screen size 780 x 1080.

Screenshot from 2022-03-22 01-37-32 (copy)

**Desired Behavior**

-  project name should be in under the card.

---
 

 **Environment:**
- Host: Ubuntu 20.04.02 LTS
- Browser: Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Krishnapro**
Signed-off-by: Krishnapro <krishnachaurasia@gmail.com>

**Description**
-service mesh pattern project name is now under the card please merge it.

This PR fixes #2676 

Screenshot from 2022-04-08 00-11-48
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by subhradwip01** [comment]
Could you please increase the padding/margin between text and image..so that it will look similar to other cards...and also make sure it is vertically and horizontally centered

**Comment by Krishnapro** [comment]
@subhradwip01  I have to increase all card sizes to increase padding/margin between image and text.

**Comment by l5io** [comment]
🚀 Preview for commit 3e75a58fd164d523af79d6704d7a0ae6d7247530 at: https://6250dad212d65336ae9d98ef--layer5ng.netlify.app

**Comment by Krishnapro** [comment]
@l5io It's working fine. please tell me what is the problem.

**Comment by leecalcote** [comment]
@l5io isn't reporting a problem, but providing part of the solution - a preview of your changes.

**Comment by Nikhil-Ladha** [comment]
Update the CSS of the last card to be similar to the other cards with one parent div, having the display property as `flex`, and then just update the `flex` value based on screen resolution using media queries.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Incorporate the above change.

**Review by Krishnapro — COMMENTED** [review]
it's working

**Comment by Nikhil-Ladha** [comment]
I don't see the suggested CSS, yet.
Avoid using fixed height. It is not at all required.

**Comment by l5io** [comment]
🚀 Preview for commit db68ce6047d740cf068d72f67477abdc444eb8c6 at: https://6255ca96a2284f04649d962e--layer5ng.netlify.app

**Review by Krishnapro — COMMENTED** [review]
please check it is responsive on all screens.

**Comment by Krishnapro** [comment]
@Nikhil-Ladha  please check and let me know if it's working or not.

**Comment by Nikhil-Ladha** [comment]
Why are you making the code uglier by using repetitive `margin-top`?
Use `flex` property, and none of this would be required.

**Comment by l5io** [comment]
🚀 Preview for commit 7823be833aefdd7ffe83d9e35bab8bbdfca756eb at: https://626163bc2f7fad71c0e1fc69--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
Screenshot_20220428-163649_Chrome
In mobile view the size of the card is not responsive...

**Comment by subhradwip01** [comment]
Also try to refactor the code if possible ..there are aome repetitive code

**Review by Krishnapro — COMMENTED** [review]
I think it's good, please check

**Comment by Akshit42-hue** [comment]
Hey @Krishnapro, Good work till now but it is not responsive (check in 1047 X 1080  not in the center)

**Comment by Akshit42-hue** [comment]
Hey @Krishnapro, In the mobile view in the last card aligned card title properly  (position is not same as all the above card)
WhatsApp Image 2022-05-07 at 9 55 35 AM

**Comment by subhradwip01** [comment]
Screenshot from 2022-05-07 12-00-14
Reduce the height of `.seven` card
and Remove top padding(no need to use padding), use `place-content:center` for the class `project__card-container-seven` when `min-width:741px` will make your problem solve

**Comment by subhradwip01** [comment]
And the mobile view issue actually happening because of the used <Row/> and <Col/> components in it...If you want you can remove them and make the 7th card's logic as same as the others..

**Comment by Krishnapro** [comment]
ok I will fix that

**Comment by leecalcote** [comment]
@Krishnapro let's wrap this up.

@subhradwip01, will you drive this to conclusion by Friday with or without @Krishnapro (if he's not able to do so)?

**Comment by subhradwip01** [comment]
Sure

**Review by Krishnapro — COMMENTED** [review]
@subhradwip01  please check out I think It will be good now.

**Comment by subhradwip01** [comment]
Could you share an output?

**Comment by Krishnapro** [comment]
@subhradwip01  are you talking about Screenshots of changes?

**Comment by subhradwip01** [comment]
@Krishnapro yes

**Comment by subhradwip01** [comment]
@Krishnapro yes

**Comment by subhradwip01** [comment]
@Krishnapro could please upload it asap? So we can bind up this issue

**Comment by Nikhil-Ladha** [comment]
> @Krishnapro could please upload it asap? So we can bind up this issue

Triggered the preview, that should help

**Comment by Krishnapro** [comment]
@subhradwip01 ok just 5 min

**Comment by Krishnapro** [comment]
@subhradwip01 
Screenshot from 2022-05-19 17-57-07

**Comment by Krishnapro** [comment]
@subhradwip01 


Screenshot from 2022-05-19 17-58-23

**Comment by Krishnapro** [comment]
is it ok?

**Comment by subhradwip01** [comment]
LGTM

**Review by Akshit42-hue — APPROVED** [review]
LGTM! Great work @Krishnapro

**Comment by leecalcote** [comment]
Thank you, MeshMate!

**Comment by subhradwip01** [comment]
@Krishnapro will you try to do it asap(by today) ? ... @leecalcote I actually  i don't have the privilege to push my commit in the other's pr... so i can't update the changes... i hope @Krishnapro can do it asap

**Comment by Krishnapro** [comment]
@subhradwip01 what changes I have to made pls explain.

**Comment by subhradwip01** [comment]
> @subhradwip01 what changes I have to made pls explain.

As per @Nikhil-Ladha 's suggestion. Default view is pc view...

**Comment by Krishnapro** [comment]
@subhradwip01 ok I am doing.

**Comment by Krishnapro** [comment]
@subhradwip01 @Nikhil-Ladha  
Screenshot from 2022-05-20 22-55-04

**Review by Krishnapro — COMMENTED** [review]
@subhradwip01 plz check and let me know what happens.

**Comment by l5io** [comment]
🚀 Preview for commit 26292527a805792e442cc14e291c8118ecfb5b50 at: https://6287d9b41c5760155b3da17a--layer5ng.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
