### PR TITLE
meshery operator updated as required 

### LINKED ISSUE #3085: Replace outlined Meshery Operators logos with filled logo
#### Current Behavior
The outlined version of the Meshery Operator logo is deprecated and needs to be replaced with the filled version of the logo. The filled version of the logo is available for in light and dark theme depending upon the need of the page/place it is being displayed.

#### Desired Behavior
Replace out outlined Meshery Operators logos with the filled Meshery Operator logo, using light or dark as appropriate.  Use .SVG format where possible.

#### Screenshots / Mockups
Do not use - Deprecated - Outlined
meshery-operator-8ea331b554c6de098f49b7792c6a5080

Use -
meshery-operator

meshery-operator-white

Find copies of the Meshery Operator logo in the `meshery-operator-brand-kit.zip` on layer5.io/brand

#### Implementation
Update the following locations and anywhere else the logo is found:

1. https://layer5.io/brand
1. https://layer5.io/community/handbook/repository-overview
1. https://docs.meshery.io/concepts/architecture/operator
1.
1.
1.

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**
The outlined version of the Meshery Operator logo is deprecated and needed to be replaced with the filled version of the logo.

This PR fixes #3085

**Notes for Reviewers**
This is under progress. 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
updated svg on repository-overview page

**Comment by l5io** [comment]
🚀 Preview for commit 8cd0590b69c17937fad009178c152f02dd5aeb95 at: https://62ff38a12cb296567987f3b8--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
The older image needs to e replaced as well `meshery-operator.svg` (with the dark one) and remove the `meshery-operator-skinny.svg` image.

**Comment by legendarykamal** [comment]
yes @Nikhil-Ladha work  under progress

**Comment by legendarykamal** [comment]
Hero section updated succesfully with the latest operator svg
image

**Comment by l5io** [comment]
🚀 Preview for commit a25812982a85196cc5d88d311b31f7c01a544f2e at: https://6301c38373d24555581fa7ec--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
