### PR TITLE
Add docs.layer5.io to repo overview

### LINKED ISSUE #5102: Add docs.layer5.io to the Repo Overview
### Current Behavior

- The current [repo overview](https://layer5.io/community/handbook/repository-overview) doesn't contain docs.layer5.io site

### Desired Situation

- Need to add that into repo overview
---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #5102 

**Notes for Reviewers**
- Added [docs.layer5.io](https://layer5.io/community/handbook/repository-overview) to Repository overview

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2961621316111452ad1050e29255acae1b4f5148 at: https://6540cd3ba4f0952eb193b596--layer5.netlify.app

**Comment by sandramsc** [comment]
@Mohith234 Please remember to indicate which issue this PR closes in the **Description** section of your PR.

**Comment by Mohith234** [comment]
@sandramsc Thanks for reminding me, I have updated the PR description with the related issue.

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
