### PR TITLE
Move code section of identity to table format

### LINKED ISSUE #5668: [Sistent] Move `code` section of identity to table format
### Current Behavior

The identity section under https://layer5.io/projects/sistent/identity/color like color, typography and spacing these sections code part is currently a image so user can't copy the color code.

### Desired Behavior

Move these images to table format instead of images, same structure just use table to display the colors and rest code section of identity.
Design can be found here: [Figma](https://www.figma.com/design/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?node-id=1379-19519&t=mFkghFS6lrXZEMTg-0)

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by mannika763**
**Description**

This PR fixes #5668

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by mannika763** [comment]
This PR doesn't contain the final changes. I have made changes in the Primitive Category for now. I would like to confirm if this is the right approach, or I would appreciate your guidance on what the approach should be.

Thank you!

**Comment by l5io** [comment]
🚀 Preview for commit ad433625cfb3f4d793ba69c525ee98bd4a772a09 at: https://6697f2ccfebba8f53f006db4--layer5.netlify.app

**Comment by hargunkaur286** [comment]
Looks good to me! Also, if you would take care of responsiveness and change in the colors of the table in the dark mode

**Comment by mannika763** [comment]
okay, i'll consider all these points also.

**Comment by leecalcote** [comment]
Thank you, @mannika763 !

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
This is nice @mannika763 . Though there is table in sistent @mannika763 named as `responsibledatatable`which you can use here so you don't have make so many changes and you will also find the readme how to use it: https://github.com/layer5io/sistent/tree/master/src/custom#responsive-data-table-component
You find the examples of it in [meshery playground](https://playground.meshery.io/) which can be found in meshery repo

**Pull request closed without merging**
