### PR TITLE
Updated the Text

### PR DESCRIPTION
**Pull request by lavakush07**
Signed-off-by: Lavakush biyani <70131581+lavakush07@users.noreply.github.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 95042919a06d571b590bd23e2ea63ab2de0c964b at: https://633ab365c51f173eb319df3c--layer5.netlify.app

**Comment by sahilsuman933** [comment]
LGTM! 🚀

**Review by Chadha93 — APPROVED** [review]
Thank you @lavakush07

**Comment by Chadha93** [comment]
@lavakush07 Please add a description and a meaningful title in the PR.

**Comment by legendarykamal** [comment]
> @lavakush07 Please add a description and a meaningful title in the PR.

@lavakush07

**Pull request merged**
