### PR TITLE
Traefik mesh lab added

### LINKED ISSUE #2167: [Learn] Add Traefik Mesh lab
**Current Behavior**
The newly created Traefik Mesh lab hasn't been added to https://layer5.io/learn

**Desired Situation**
Let's put up the Traefik Mesh lab [here]( https://layer5.io/learn).

https://github.com/layer5io/layer5/blob/master/src/sections/Learn/Service-Mesh-Labs/courseData.js

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Manish-210**
Signed-off-by: Manish Prajapati <210manishprajapati@gmail.com>

**Description**

This PR fixes #2167

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3af70f5fcdb4938da398d543043a6af3c5cc43f4 at: https://61419fa8749edf52c4c77f38--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks @Manish-210

**Review by Tanuj22 — APPROVED** [review]
Thank you @Manish-210

**Comment by Manish-210** [comment]
Thanks to the wonderful community of Layer5 :smile:

**Pull request merged**
