### PR TITLE
Added the member card for Savio Dias under the community section

### LINKED ISSUE #4275: [Community] Member Profile: Savio Dias
**Current Behavior**

@savio629 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Savio629  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Savio629 
- Twitter: [Savio_dias629](https://twitter.com/Savio_dias629)
- LinkedIn: [savio-dias-984b45198](https://www.linkedin.com/in/savio-dias-984b45198/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by DarrenDsouza7273**
**Description**
Added the member card for Savio Dias under the community section as an active member
This PR fixes #4275 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by DarrenDsouza7273** [comment]
@Savio629 please review had some issues as i was solving it using gitpod

**Comment by l5io** [comment]
🚀 Preview for commit 1defeae7b30221fe800251021e2dadd7286610c3 at: https://6470e7f3c907c80067da2858--layer5.netlify.app

**Review by Savio629 — APPROVED** [review]
LGTM 👍

**Review by Savio629 — COMMENTED** [review]
Regarding the gitpod, I was facing the same issue while using git add .
@vishalvivekm is it fine if he adds `gitpod.yml` to `.gitignore` file in this pr or do we have to create a new pr for it?

**Comment by DarrenDsouza7273** [comment]
Please review @Chadha93 @vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit 302cb925e17dace6ed095abb78aa0eddd42a0d43 at: https://6471bdf2cc503551676b205a--layer5.netlify.app

**Comment by vishalvivekm** [comment]
> Regarding the gitpod, I was facing the same issue while using git add . @vishalvivekm is it fine if he adds `gitpod.yml` to `.gitignore` file in this pr or do we have to create a new pr for it?

My suggestion would be to ` git add <file/directory-name> ` instead of ` git add .`

Moreover let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.7hys5m5156u1) if you would :)
// @DarrenDsouza7273 @Savio629

**Review by vishalvivekm — APPROVED** [review]
LGTM
Thanks @DarrenDsouza7273 :rocket:

**Review by Chadha93 — APPROVED** [review]

**Comment by Chadha93** [comment]
Yay @Savio629 :balloon:

**Comment by DarrenDsouza7273** [comment]
No worries @vishalvivekm

**Comment by DarrenDsouza7273** [comment]
> > Regarding the gitpod, I was facing the same issue while using git add . @vishalvivekm is it fine if he adds `gitpod.yml` to `.gitignore` file in this pr or do we have to create a new pr for it?
> 
> My suggestion would be to `git add <file/directory-name>` instead of ` git add .`
> 
> Moreover let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.7hys5m5156u1) if you would :) // @DarrenDsouza7273 @Savio629

on it

**Comment by Savio629** [comment]
@Chadha93 @vishalvivekm Feels so good to be a part of such a great community💚

**Pull request merged**
