### PR TITLE
added more topics under resources

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**
Added two new articles under the Resources section :
1) 7 Key Considerations for Microservices-Based Application Delivery
2) Choosing the Perfect Proxy

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f3ffcc52b4d22defd56ae99c489f059492b6685f at: https://619d6e3ed512c61950396d5a--layer5ng.netlify.app

**Comment by leecalcote** [comment]
One that that we'll want to be sure to do is use SVG where possible. Any Google Drawing or individual Google Slide can be downloaded as an SVG.

**Comment by leecalcote** [comment]
I updated ~1/2 of the diagrams to SVG. Specific to this article(s), please prepend "citrix" in each filename. In general for all assets, use all lowercase and hyphenate (`-`) in lieu of whitespace between words (better SEO).

**Comment by l5io** [comment]
🚀 Preview for commit 75ca2cf3f884ae345808e5e14db3b44f9cefa2d6 at: https://619dd0cc29264ea4f192d4fc--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 33925a4c7b244c692ae30365ab6651731805a64b at: https://619fd6dd0b1968234c0d1403--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@debo19 are we good to go with this?

**Review by leecalcote — APPROVED** [review]
Thank you for tossing in these SVGs. 👍

**Pull request merged**
