### PR TITLE
Config: Updated sharp-plugin config and robots.txt for deploy previews

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description**

This PR updates the default value of `placeholder` in gatsby-sharp to show `blurred` images while the image loads, instead of a dominant color.
Also, it updates the `gatsby-robots-txt` plugin to create a `robots.txt` file based on the type of deployment.

**Note for reviewers**
Husky@7 is a breaking change and they have updated the config file setup. Hence, I have updated the same in the repo so that others do not face issues while committing.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bd6ea01d6bb552de671d1ec1fbd15695e2ba6f76 at: https://61fea69a11bc0259f799299f--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@leecalcote let's see if this config updates the deploy previews or not (we will have to merge the PR to confirm that)
If not, we can revert to the old hack.

**Comment by l5io** [comment]
🚀 Preview for commit eacf986180e177915a2ec3b0564ae1b7d56245b4 at: https://61feab046242576585b4e52e--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM!

**Pull request merged**
