### PR TITLE
updates on careers and programs page in layer5-ng

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR makes a few updates on careers and programs page

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
There would be an update in the `programs` section on the careers page, later on?
Like, changing the heading to something like `Looking out for external programs?` (just a suggestion :laughing) and then a small paragraph (which I suspect @leecalcote has to provide) about the programs and then a button having the text as `Check them out` or something which goes appropriately with it.

**Comment by Jashpatel1** [comment]
> There would be an update in the `programs` section on the careers page, later on?
> Like, changing the heading to something like `Looking out for external programs?` (just a suggestion  ) and then a small paragraph (which I suspect @leecalcote has to provide) about the programs and then a button having the text as `Check them out` or something which goes appropriately with it.

Yes exactly.

**Comment by Nikhil-Ladha** [comment]
I have some suggestions for the individual careers page, you can either fix it this PR itself or create a new one.
Screenshot from 2020-11-24 12-39-14
- I think it would be better to left-align the `Back to Open Positions` on this page.
- Better to move the job code and work location to the top. Zip-code can be removed(not sure though).

**Comment by Jashpatel1** [comment]
> I have some suggestions for the individual careers page, you can either fix it this PR itself or create a new one.
> Screenshot from 2020-11-24 12-39-14
> 
> * I think it would be better to left-align the `Back to Open Positions` on this page.
> * Better to move the job code and work location to the top. Zip-code can be removed(not sure though).

Lets do it in another PR.

**Comment by Nikhil-Ladha** [comment]
No worries 😉

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
