### PR TITLE
Git img text alignment

### PR DESCRIPTION
**Pull request by Modern-artist**
**Description**
Alignment of Image and Heading is pretty random and some of the width are not as expected.
This PR fixes [#4554](https://github.com/layer5io/layer5/issues/4554)

**Notes for Reviewers**

Screenshot 2023-07-18 at 9 46 25 AM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3f362e78ccc026459822ae00213b3bfc80221334 at: https://64b69657d6a4df0079c73068--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1c822f8f4c2d185e4ea3915b57ef3565cdb2e3d8 at: https://64b6b9ca67ff4c07d7ea415e--layer5.netlify.app

**Comment by Modern-artist** [comment]
@Chadha93 Check it out.

**Review by hirentimbadiya — COMMENTED** [review]
why navbar is different than layer5 's homepage

navbar

**Comment by l5io** [comment]
🚀 Preview for commit 12a77bfa076341ad3f19c729ed4a310d3cb301ea at: https://64b7a81baf2fd36af29d23a3--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 03c5ed2e72e7d396664783f001604d6cad3d6fca at: https://64b7dab2dbe8440c0d7fda59--layer5.netlify.app

**Comment by Modern-artist** [comment]
@hirentimbadiya look it at now there was some change in website I have changed it now.

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@Modern-artist, everything else appears fine except for the modifications made in the package-lock.json file for dependencies. Please undo the changes made to the package-lock.json file.

**Comment by Modern-artist** [comment]
I haven't changed any thing in json but still how can i revert it?

**Comment by l5io** [comment]
🚀 Preview for commit 1f325ce804b1916d5b51a59c80491b4694a5523f at: https://64ba528a4e9d606c12e0095f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 1f325ce804b1916d5b51a59c80491b4694a5523f at: https://64ba52c4c60d8e647fdc5b08--layer5.netlify.app

**Pull request closed without merging**
