### PR TITLE
Added News on the News Section Issue:#2732

### PR DESCRIPTION
**Pull request by Sam-Radnus**
**Description**

This PR fixes adds new news folder

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Sam-Radnus. Will you take. moment to update the title of this PR to be descriptive of its purpose? Will you also list the issue # that this PR fixes?

**Comment by Sam-Radnus** [comment]
#2732

**Comment by leecalcote** [comment]
@Sam-Radnus I tried to help out by removing the unwanted changes. I wasn't successful. I recommend you close this PR and open a new one.

**Comment by debo19** [comment]
@Sam-Radnus you just need to add the news under "/collections/news" which will include the index.js file and the thumbnail image according to the template. No other files should be added to the PR.

**Pull request closed without merging**
