### PR TITLE
Updated imags in containd section

### LINKED ISSUE #4875: [Screenshots] Containerd under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/containerd) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Containerd](https://layer5.io/cloud-native-management/meshery/integrations/containerd) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #4875

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1f8964a649cbbdfea3de3e44bdcfd045607ffcc7 at: https://65a96d0b337ae106f8a0cb87--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit daa73b25534b40665c0f7850afed454898027104 at: https://65abf61e32bdb7b52c486298--layer5.netlify.app

**Comment by saurabh100ni** [comment]
LGTM. @surajvast1 please sign your commit in your PR Description.

@sandramsc up for review 👀?

**Comment by surajvast1** [comment]
Please merge this !!

**Comment by saurabh100ni** [comment]
Shubham I see `Elastic Search in the screenshot being used and not `Containerd` as the issue is referencing to `Containerd`. will you please check and confirm?

**Comment by surajvast1** [comment]
As discussed in the meeting, we currently don't have the designs related to containerd available. In the meantime, I've taken screenshots from other sources that I believe are better,

**Comment by saurabh100ni** [comment]
Hm, Fair enough. Yes, I remember.

**Review by saurabh100ni — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 3dc13ea56071280cac546addbcb57e862171b71c at: https://65b897bfe0090ea44c9ece6d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4e2d3e76b15555b5b81a61e045c6f0856f5aed4 at: https://65bbd91f6b4a560aa94de741--layer5.netlify.app

**Comment by surajvast1** [comment]
@vishalvivekm Can you review whether it matches the workflow as discussed in the meet

**Comment by l5io** [comment]
🚀 Preview for commit 423848cdc2d983d6ca1386d9d3d43023b2ad01c5 at: https://65bcdd445638ab7ee222ce5e--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@saurabh100ni will you please mention https://github.com/layer5io/layer5/pull/5129#issue-1995493031 in each open and future Screenshots related issue's description or comment?

**Comment by saurabh100ni** [comment]
Sure, Thanks for the heads-up @vishalvivekm.

**Comment by l5io** [comment]
🚀 Preview for commit 91a6f90f31f4db27c5ce0f9e49f28dd8e1dac3ba at: https://65c644814809de0acd59b07e--layer5.netlify.app

**Pull request closed without merging**
