### PR TITLE
GSoC21 project ideas page added

### LINKED ISSUE #1670: GSoC21- public idea page list
Google Summer of Code 2021 page missing from Open Source Internship Programs. 
An idea page list containing possible project ideas for the upcoming GSoC edition should be published.

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>

**Description**
 An idea page list containing possible project ideas for the upcoming GSoC edition should be published.

This PR fixes #1670 
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9e9a07f87c0cf4dd728aac16c3c5f154421cff84 at: https://60431ba6f32a8d94e6684ad2--layer5ng.netlify.app

**Comment by piyushsingariya** [comment]
Hey @Tanuj22 can you review this?

**Comment by l5io** [comment]
🚀 Preview for commit f2ab1e345bd85efa537025f4af56554c040c842d at: https://604f006d53c69878d8efea1d--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @piyushsingariya. This looks good.

Do consider a follow-up PR to remove the year from each of the programs.

**Pull request merged**
