### PR TITLE
Updated SMI Table

### LINKED ISSUE #1031: [Landscape] Build a New Version of SMI table on Service Mesh Landscape
**Current State:**
The current [Service Mesh Interface Compatibility](https://layer5.io/landscape#smi) table has some missing items
**Desired State:**
Build a new version using the following JSON:

```
{
    "results": [
        {
            "id": "0dd368be-745f-4433-a356-f717aac40457",
            "date": "2020-10-14T20:14:48+05:30",
            "mesh_name": "Open Service Mesh",
            "mesh_version": "v0.3.0",
            "cases_passed": "0",
            "passing_percentage": "0",
            "status": "completed",
            "more_details": [
                {
                    "smi_specification": "traffic-access",
                    "time": "2m5.607711181s",
                    "assertions": "10",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-beloved-alpaca/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }, {
                    "smi_specification": "traffic-split",
                    "time": "4m10.378728809s",
                    "assertions": "8",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-dominant-tuna/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }, {
                    "smi_specification": "traffic-spec",
                    "time": "6m16.323837714s",
                    "assertions": "10",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-honest-mallard/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }
            ]
        }
    ]
}
```

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

### PR DESCRIPTION
**Pull request by geraldmaboshe**
Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>

**Description**
Updated smi table
This PR fixes #1031

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@geraldmaboshe details are good, but can be hide those in a tooltip? Can we move to more of a green, red, N/A style list? Let's incorporate use of the service mesh logos into the design, too.

@dhruv0000 will collaborate on a mockup in here - https://docs.google.com/spreadsheets/d/1yTGPgqbG_QrVd3ENEdCmqwQwFJMNAXCgcil6crcxvhM/edit#gid=1674563539

Will you take inspiration from this compatibility matrix? - https://www.vmware.com/resources/compatibility/sim/interop_matrix.php#interop&2=&551=&648=

Screen Shot 2020-10-29 at 5 45 17 PM

**Comment by dhruv0000** [comment]
Yes. @geraldmaboshe and I talked yesterday, and decided on some few changes, that are currently being worked on.
1) make the tables collapsible
2) shorten the ID and url
3) Format the date properly

**Comment by dhruv0000** [comment]
Peek 2020-11-02 01-57

Hey @geraldmaboshe the table is coming great. Just some suggestions:
1) The alignment of the sub-table is a bit off.
2) I don't think we need the name of service meshes in the sub-table. Instead having them as the icon's tooltip in the main-table would look more cleaner.
3) The last commit you made seems to mess around with other files. Try not to use other beautifiers or linters.

Also replacing the Full/Half/None with icons would be more engaging. The project already uses [Material-icons](https://material.io/resources/icons/?style=baseline), so we can have a pick from there. Mabey @leecalcote can help us here. I was thinking of using green and blue `check_circle` for full and half and `not_interested` for none. Another possibility can be `brightness_1` `brightness_2` and `panorama_fish_eye`.

**Comment by leecalcote** [comment]
Nice. This last revision is really coming along.

**Comment by geraldmaboshe** [comment]
Thanks for the feedback team. I will work on these as soon as I get some time.

**Comment by leecalcote** [comment]
Thank you, @geraldmaboshe. We will be meeting with a broad set of stakeholders (each participating service mesh project) on this subject within ~a week.

**Pull request closed without merging**
