### PR TITLE
Added Domain and Timezone to the Meshmate Cards

### LINKED ISSUE #894: Update MeshMate cards
**Current Behavior**

The individual MeshMate cards currently don't reflect details about the MeshMate on this [page](https://layer5.io/community/meshmates).

**Desired Behavior**

Each MeshMate card should include the following details about the MeshMate, in the below-mentioned order. This should preferably be placed under their name and above their Social ID's:
- Domain(s)
- Timezone

The details for each MeshMate can found in this [document](https://docs.google.com/document/d/1omot8vRinfQlNKMt5KRBlGiHJRMC6xEdRd0o0jIifrM/edit?usp=sharing).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by geraldmaboshe**
Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>

**Description**
Added mehsmate domain and timezone to the meshmate cards
This PR fixes #894 

**Notes for Reviewers**
N/A

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — DISMISSED** [review]
Looking good! @geraldmaboshe

**Comment by Jashpatel1** [comment]
> Looking good! @geraldmaboshe

Is the change only for grid-view?

**Comment by Nikhil-Ladha** [comment]
> > Looking good! @geraldmaboshe
> 
> Is the change only for grid-view?

This is the current site @Jashpatel1 . Which grid view are referring to here?

**Comment by Jashpatel1** [comment]
> > > Looking good! @geraldmaboshe
> > 
> > 
> > Is the change only for grid-view?
> 
> This is the current site @Jashpatel1 . Which grid view are referring to here?

I am referring as the card shows those details only on grid-page currently, not on individual pages.

**Comment by Nikhil-Ladha** [comment]
> > Looking good! @geraldmaboshe
> 
> Is the change only for grid-view? I think the issue was to make those details available in individual pages. @Nikhil-Ladha correct me if I am wrong.

No no, this was only the page where we wanted to have these.

**Review by Jashpatel1 — DISMISSED** [review]
Looks good to me.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @geraldmaboshe! Please see - https://github.com/layer5io/layer5/issues/894#issuecomment-703339363

**Comment by chandrashritii** [comment]
Hey @geraldmaboshe 
As explained in the original issue, the details should be added on the individual pages. Taking an example here, the details are currently visible on the card itself -
Screenshot_2020-10-05 Meshmates

The details should instead be added on individual pages -
Screenshot_2020-10-05 Kush Trivedi

**Review by Jashpatel1 — DISMISSED** [review]

**Review by Nikhil-Ladha — APPROVED** [review]
LGTM!

**Review by chandrashritii — DISMISSED** [review]
Good work @geraldmaboshe

**Review by leecalcote — CHANGES_REQUESTED** [review]
Hi @geraldmaboshe, Thanks for seeing this through.

Will you consider a revision on the formatting of this information? Perhaps, bump the font size down a couple notches, remove italics, create an unordered list of areas domains of expertise, create two, borderless columns:

| Time Zone | - Domain 1 |
|                    | - Domain 2 |

**Comment by geraldmaboshe** [comment]
> Hi @geraldmaboshe, Thanks for seeing this through.
> 
> Will you consider a revision on the formatting of this information? Perhaps, bump the font size down a couple notches, remove italics, create an unordered list of areas domains of expertise, create two, borderless columns:
> 
> | Time Zone | - Domain 1 |
> | | - Domain 2 |

Great feedback. I will work on it in a bit.

**Review by leecalcote — APPROVED** [review]
Way to be, @geraldmaboshe! Looking good. 😄

**Comment by geraldmaboshe** [comment]
> Way to be, @geraldmaboshe! Looking good. 😄

Thanks @leecalcote! 😄

**Pull request merged**
