### PR TITLE
feat: add commnity members page

### LINKED ISSUE #740: [NG]: Add the community members page
**Current Behavior**

The NG site lacks a community members page which lists all the community members we have at Layer5.

**Desired Behavior**

A community member page needs to be added to the NG site, feel free to reach out to @Nikhil-Ladha for design inspiration.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #740

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@Nikhil-Ladha thoughts on this? The link is https://deploy-preview-778--layer5ng.netlify.app/community/members

P.S this is just the initial design :stuck_out_tongue:

**Comment by leecalcote** [comment]
Looking pretty good. I wonder if there are improvements on this current design that we might make here. You may want to have another look at the onhover effect on the GitHub and twitter buttons. The effect is subtle currently given that they remain the same dark green color.

Is that a new picture for you, @Tanuj22?

**Comment by Tanuj22** [comment]
@leecalcote Not an image of me. Just a stock image :laughing:

**Comment by leecalcote** [comment]
> @leecalcote Not an image of me. Just a stock image 😆

I didn't want to say anything, but, man, lay off the rice. 😉

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha thoughts on this? The link is https://deploy-preview-778--layer5ng.netlify.app/community/members
> 
> P.S this is just the initial design

Well, I am eagerly waiting for the completion of it. The design of the card is gooood!
Lee, pointed out few things, which I agree upon too. So, hoping to see this complete and ready for demo in the next Websites Call :muscle:

**Comment by JubayerJoy** [comment]
The design is really good and responsive. 🚀
While hovering cards, the color changes to a darker shade very quickly. Maybe changing the color a bit slower will look nicer.
@Tanuj22 what's your thought on this?

**Comment by Tanuj22** [comment]
> The design is really good and responsive. 
> While hovering cards, the color changes to a darker shade very quickly. Maybe changing the color a bit slower will look nicer.
> @Tanuj22 what's your thought on this?

Yeah. This may look nice. Will give it a shot :+1:

**Comment by leecalcote** [comment]
[MeshMate brand kit](https://github.com/layer5io/layer5/raw/master/assets/resources/brand/meshmate-brand-kit.zip) is now available. We'll want to explore how to add the MeshMate icon as a badge to MeshMate profiles.

**Comment by Tanuj22** [comment]
Made a couple of changes and populated the data. 
- Any thoughts where to add the meshmate badge?
- Do we need separate pages for active/inactive members (like in #739)
- How should the individual pages of the different members look like? Should it be something similar to the current page or like the one for [docker captains](https://www.docker.com/captains/lee-calcote) (though we don't have a description for members)?

@leecalcote @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
The update looks really good @Tanuj22 .
- I think the MeshMate bade can be added here as well as in the page on which we will be redirected to on clicking any of the cards, which is the profile of the member.
- If we add the MeshMate badge here too, then it should redirect to the MeshMate page which lists all the MeshMate s and the MeshMate program description.
- For active/inactive members we can do something similar to we have for the blogs page, just the difference here would be that the content will be filtered.
- And, for the individual members page, since we don't have a content for them right now we can do something similar to what we have in the current site or we can ask for a small description about the members and it here.

**Comment by Tanuj22** [comment]
Added meshmate badge with the other links for now (having some issues with the colour change of meshmate svg, will fix later)

**Comment by leecalcote** [comment]
Whoa! This is looks fantastic. I have included a few more variants of the MeshMate logo in the shared drive here - https://drive.google.com/drive/folders/1SwKkCysWq-lA-lgCwQgglIqxOY5ZDRD0, which will have the white version that you're looking for, @Tanuj22

**Comment by Nikhil-Ladha** [comment]
Agree with @leecalcote on adding the white version of the MeshMate logo. 
Also, I think the MeshMate logo is not visible in the individual member page, can you take a look into once @Tanuj22 .
Just asking, will a scaling effect animation look good here. On clicking or hovering the member cards ?
Like we have for the programs card under careers page.
And, we want to get rid of this purple and blue at the earliest I suppose 😤

**Comment by Nikhil-Ladha** [comment]
Last thing, @Tanuj22 the individua memberl page is still left to be work upon or is it done from your end?

**Comment by Tanuj22** [comment]
> Last thing, @Tanuj22 the individua memberl page is still left to be work upon or is it done from your end?
> 
> If not I would like to make few suggestions,
> The image in the individual member page can be bigger, and there we can use a backdrop of the layer5's `5` logo for the images, or to do something fancier we can add different backdrop images for MeshMates, Maintainers if that looks good (as per the discussion on our last call). The social icons and the text mentioning the role can be moved outside the card.

Yeah I was thinking to come back to the single members page later and work on making the careers page dynamic and fix a graphql related issue

**Comment by Nikhil-Ladha** [comment]
Okay, then do consider the above mentioned points when you work on that page.

**Comment by Nikhil-Ladha** [comment]
How will it be if instead of having a legend-filter option we have a drop-down filter option which will include options like `MeshMates` and `Maitainers` and stuff?
/cc @leecalcote

**Comment by Nikhil-Ladha** [comment]
Though, it can be addressed in a seperate PR.

**Comment by Tanuj22** [comment]
@Nikhil-Ladha I will address this in a separate PR. Can we merge this as it is looking to block progress for #761 ?

**Review by Nikhil-Ladha — APPROVED** [review]
Good work here @Tanuj22 💯🎉

**Pull request merged**
