### PR TITLE
Added light/dark mode images for the rescpective section

### LINKED ISSUE #5327: [Screenshots] Etcd Cluster Operator under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/etcd-cluster-operator) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Etcd Cluster Operator](https://layer5.io/cloud-native-management/meshery/integrations/etcd-cluster-operator) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Chay2203**
**Description**

This PR fixes #5327

**Notes for Reviewers**
This is my first PR, kindly review it. :D

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0fe5b08a7634057b87ccb06b612042d3536db28d at: https://65e1c6f58759c2cb0415c688--layer5.netlify.app

**Comment by Chay2203** [comment]
Hey @leecalcote, I have made the necessary changes that we have discussed in the GMeet, please have a look now :)

**Comment by l5io** [comment]
🚀 Preview for commit 80713e7631c8e6143300ea2915d7859033b1b5a6 at: https://65e947adac098aa599f21afa--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@Chay2203 are you still there?

**Comment by sudhanshutech** [comment]
Closing this so that other contributor can take this

**Pull request closed without merging**
