### PR TITLE
Updated feature image on landscape post

### LINKED ISSUE #541: [Blog] Update feature image on landscape post
**Description**
This [blog post](https://layer5.io/blog/layer5-landscape-spectrums-revisited) is currently using a feature image that is generic. Source code for this blog post is [here](https://github.com/layer5io/layer5/blob/master/collections/_blogs/2019-12-04-layer5-landscape-spectrums-revisited.md).

Screen Shot 2020-07-30 at 1 25 58 AM

**Expected Behavior**
Each blog post should be provided with a unique feature image. 
Use the landscape project logo as the feature image (below):

landscape

### PR DESCRIPTION
**Pull request by Ruth-ikegah**
Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>

**Description**

This PR fixes #541

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@Ruth-ikegah , I think there is a typo in the src of the image, it should be `assets` instead of `assests`.

**Comment by Ruth-ikegah** [comment]
> @Ruth-ikegah , I think there is a typo in the src of the image, it should be `assets` instead of `assests`.

okay thanks, let me change it

**Comment by Ruth-ikegah** [comment]
> Now it's fine, Good work @Ruth-ikegah 👍🏼

thanks @Nikhil-Ladha for your help. Yaay finally!

**Comment by Nikhil-Ladha** [comment]
You are welcome 🙂.

**Pull request merged**
