### PR TITLE
Fix newsletter position in Footer

### LINKED ISSUE #4750: Fix Inconsistent newsletter Position
### Current Behavior
The newsletter component is overlapping for screen widths of ~723px
</img>

### Desired Behavior
No overlapping of elements
### Implementation
Update the width specific styles to be consistent  
### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by dibyendu02**
**Description**

This PR fixes #4750 

**Notes for Reviewers**

I fixed the newsletter position for the screen width 724 and added some spacing as discussed in the meeting, I faced a error while committing that says string type can only be double quoted so I needed to change a file just a little bit.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks for this, @dibyendu02. FYI, I'm still seeing this:

Screenshot 2023-08-29 at 5 25 05 PM

**Comment by dibyendu02** [comment]
Could you please mention your screen width? I've checked from 724 to 730, it's working fine while I have tested this preview link in different devices.

**Comment by vishalvivekm** [comment]
@dibyendu02 
Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by dibyendu02** [comment]
Okay, in last website meeting I showed them the solution and was got approved.

**Comment by sudhanshutech** [comment]
Solving the current issue created a another, and considering the assignee is no more active,let close this and reopen issue for others

**Pull request closed without merging**
