### PR TITLE
Updated maintainer list

### LINKED ISSUE #4999: [Handbook] Repository Overview: Update Maintainer list
### Current Behavior
Gaurav Chadha is no longer a maintainer.

### Desired Situation
One this page, https://layer5.io/community/handbook/repository-overview, remove "Gaurav Chadha" from the lists.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Description**

This PR fixes #4999 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9d7e1cb15d9b8755a2138f4a237325bfb52fed29 at: https://651cf5d54b000d07bb8685cd--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Review by hirentimbadiya — APPROVED** [review]
Looks Good To Merge!!

**Comment by VivekBaldha0712** [comment]
@leecalcote  Please review PR

**Review by leecalcote — APPROVED** [review]
Thanks, @VivekBaldha0712. Looks good.

**Pull request merged**
