### PR TITLE
A community member's profile has been successfully added.

### LINKED ISSUE #4812: [Community] Member Profile: Prem Kumar
**Current Behavior**

@Modern-artist  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Modern-artist 
- Twitter: [Modern_a_r_t](https://twitter.com/Modern_a_r_t)
- LinkedIn: [modernartist](https://www.linkedin.com/in/modernartist/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by rj2704**
**Description**

This PR fixes #4812 

Signed-off-by : [jigarrathod2704@gmail.com](mailto:jigarrathod2704@gmail.com)

**Notes for Reviewers**
Added Prem Kumar's profile as a community member.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c098a92b9c9a87a9944c926cf5025a0f29531a87 at: https://64f87d70be2880075e0bde1e--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
LGTM

**Review by hirentimbadiya — APPROVED** [review]
LGTM

**Comment by rj2704** [comment]
Hello, @Modern-artist. Please review these PRs if you have the time. In that case, we can merge it if everything seems fine.

**Comment by leecalcote** [comment]
Yay, @Modern-artist! 🎈

**Comment by abhijeetgauravm** [comment]
> Hello, @Modern-artist. Please review these PRs if you have the time. In that case, we can merge it if everything seems fine.

@Modern-artist

**Review by Modern-artist — APPROVED** [review]

**Comment by abhijeetgauravm** [comment]
@Chadha93 @leecalcote Good to merge!

**Pull request merged**
