### PR TITLE
#2172 - Site Speed : Improves Site speed 

### PR DESCRIPTION
**Pull request by kayceeDev**
Signed-off-by: kayceedev [nwobodoe71@gmail.com](mailto:nwobodoe71@gmail.com)

**Description**

This PR fixes # 
Site speed 

**Notes for Reviewers**
The site speed is expected to improve.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@kayceeDev with the sheer number of changes to files, this will be a difficult PR for maintainers to review. A number of changes seem to be immaterial (just reformatting of whitespace). Will you adjust and have those change removed from this PR/branch?

**Comment by kayceeDev** [comment]
Alright @leecalcote i will do that

**Comment by leecalcote** [comment]
@kayceeDev I ❤️ seeing this effort come through. There are a few files included that don't seem to have any material changes made. In order to ease the review of ~400 files change here, can you 1) remove any changes that aren't material (aren't actually a speed improvement, but are likely just a change in whitespace formatting) and 2) breakdown these changes into a set of a few smaller PRs so as to ease the burden of review and the risk of overlooking negatively impactful changes?

**Comment by leecalcote** [comment]
Merge conflicts...

**Comment by kayceeDev** [comment]
I will resolve the conflicts. I guess some changes were made after I created a PR. I will try and sort everything out this weekend.

**Comment by kayceeDev** [comment]
Changes have been made and PR updated. The enormous amount of changes actually came from fixing merge conflicts I was having. I also tested `make build`  and it worked locally so I am expecting it should work here too.

Hopefully no errors this time.

**Comment by leecalcote** [comment]
PR is still too large for review. Many changes are unnecessary and have no positive affect on the performance of the site.

**Comment by kayceeDev** [comment]
Alright. So now PR has been closed. What's the way forward to still make this contribution.. I saw you created a new issue. Can I make the same change and reference that same issue on performance. I want to know the best way forward for this

**Comment by adithyaakrishna** [comment]
@kayceeDev Instead of making all the changes in one PR, how about if we make separate PRs consisting of like changes in 5-10 files?

It will be like,
- https://github.com/layer5io/layer5/issues/2172 - P1
- https://github.com/layer5io/layer5/issues/2172 - P2 and so on...

**Comment by kayceeDev** [comment]
This is what I intend doing in my next PR since this one is already closed. Thanks for the suggestions bro. Merry Xmas 😁❤️

**Pull request closed without merging**
