### PR TITLE
[Handbook] Added Homepage

### LINKED ISSUE #2135: [UX] Homepage for the handbook
**Description**
The current handbook doesn't have a landing page

**Expected Behavior**
A newly designed handbook landing page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**

This PR fixes #2135 

- Added Homepage for Community Handbook

## After Changes
https://user-images.githubusercontent.com/58226527/133260830-5b6ae712-9075-4850-983c-c5f366f23d26.mp4

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
Looks super good to me, I hope @leecalcote likes it too😄.

**Comment by Nikhil-Ladha** [comment]
Looks good, but few things to update:
- The complete card should be clickable.
- The 'Read More' button background color can be removed instead a hover effect for the "underline" can be given as we have for the nav items.
- Use `h2` (preferred) or `h3` if `h2` looks bolder for the subtitle `Explore the community handbook`

**Comment by leecalcote** [comment]
@NikhilSharma03 please add PR labels as appropriate.

**Review by debo19 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/85789734/133390630-034c9fbb-d1f6-41c9-8b77-522be76bd0d7.mp4

The "About" link on the side bar should redirect to the About Page. Right now it directs back to home page.

**Comment by NikhilSharma03** [comment]
@debo19 @Nikhil-Ladha Could you please review the changes.

**Comment by l5io** [comment]
🚀 Preview for commit eb0a42b3f716f19675114770d522ad0d3acd6da3 at: https://6141c8153b21b4134981aeec--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Seems like a small CSS issue, the white space between the cards is also clickable (looks like an overflow of CSS for the anchor tag).
Also, do resolve the conflicts.

**Comment by NikhilSharma03** [comment]
@Nikhil-Ladha Done

**Comment by l5io** [comment]
🚀 Preview for commit 1ef6ccf0f11d55527c3538f11c9adac45a052b29 at: https://614254f336942000b9de99dc--layer5ng.netlify.app

**Review by debo19 — APPROVED** [review]
LGTM :tada: Thank you @NikhilSharma03

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, @Nikhil-Ladha are we good to merge?

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good 👍🏼

**Pull request merged**
