### PR TITLE
Bind Kubernetes Service Account with ClusterRole blog #863h40347

### PR DESCRIPTION
**Pull request by duckling69**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-863h40347 Blog: Title: How To Bind Kubernetes Service Account with ClusterRole: A Comprehensive Guide](https://app.clickup.com/t/863h40347)

**Comment by l5io** [comment]
🚀 Preview for commit e4a88e9504aee750d13b169c7c4b21eb1f7aa6a2 at: https://649e5372c6f25329cc605062--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
@duckling69 use webp version of blog-post graphic not the SVG please

**Comment by l5io** [comment]
🚀 Preview for commit acdc11140f9db1d35b0fcc94800b1757fa966945 at: https://649f166a1a33a62a3ab26b4d--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for this, @duckling69 and @ritiksaxena124 👍

**Comment by leecalcote** [comment]
A tweet going out on Monday...

**Pull request merged**
