### PR TITLE
fixed typos in <README.md>

### PR DESCRIPTION
**Pull request by hidden-street**
This change fixes some spelling errors that were found in the readme.
Signed-off-by: Marcellus Le <marcellusle@outlook.com>

### CODE REVIEW

**Review by UtkarshMishra12 — APPROVED** [review]

**Comment by UtkarshMishra12** [comment]
@hidden-street Please follow the steps mentioned here to sign off [link](https://github.com/layer5io/layer5/pull/3802/checks?check_run_id=11507442313)

or 

1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
2. In your local branch, run: `git rebase HEAD~2 --signoff`
3. Force push your changes to overwrite the branch: `git push --force-with-lease origin layer5-ng`

**Comment by l5io** [comment]
🚀 Preview for commit b0dd592320ada155fcc13f62f4681a3112b00d31 at: https://63f648e62e55dd05341508b5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d7f419ec7f94cc74bd1e20269f0675239e64d6b9 at: https://63f7f1a5ed99070e7293a305--layer5.netlify.app

**Comment by Chadha93** [comment]
@hidden-street Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Nikhil-Ladha** [comment]
@hidden-street were you able to execute the steps mentioned in the link shared by @UtkarshMishra12 above? Or, did we loose you here?

**Comment by Nikhil-Ladha** [comment]
@hidden-street were you able to execute the steps mentioned in the link shared by @UtkarshMishra12 above? Or, did we loose you here?

**Comment by Chadha93** [comment]
I think we lose @hidden-street here, helping with the DCO, Thank you for your contribution @hidden-street. Let's get this merged.

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
