### PR TITLE
fix `color-contrast` lighthouse-ci error for index

### PR DESCRIPTION
**Pull request by ayushthe1**
**Description**

This PR fixes the [color-contrast](https://dequeuniversity.com/rules/axe/4.4/color-contrast) error for the index.html as present [here](https://github.com/layer5io/layer5/actions/runs/4092520401/jobs/7057312979#step:6:167).

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e565d73e630b45f49f16dba8594261813ee1ae76 at: https://63dfbbd14535cf7460150bc4--layer5.netlify.app

**Review by leecalcote — CHANGES_REQUESTED** [review]
@ayushthe1 the color of the "MeshMap" word is a weird green.

The color of the text in the buttons across the 4 banners is inconsistent.

**Comment by leecalcote** [comment]
a merge conflict popped up

**Comment by ayushthe1** [comment]
@leecalcote I am closing this PR and instead opening PR #3755 for it as i have done many more changes & also since there's a lot of merge conflicts for this pr.

**Comment by leecalcote** [comment]
Ok, sounds real good.

**Pull request closed without merging**
