### PR TITLE
Fixed the unused-css-rules issue reported by lighthouse-ci

### LINKED ISSUE #3672: [Performance] Fix the `unused-css-rules`  issue reported by lighthouse-ci
### Description

Currently, the lighthouse ci github action fails the assertion results for `unused-css-rules` as seen  [here](https://github.com/layer5io/layer5/actions/runs/4026251880/jobs/6920524991#step:6:103) .
### Expected Behavior

The assertion test for the above rules should pass in the lighthouse ci run.
### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #3672 
The `unused-css-rules` error has been removed from most of the pages reported by lighthouse-ci, `gatsby-plugin-purgecss` has been used to achieve this.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 37f6c86d43a1fca70ed05221dcc2c4938e848bea at: https://64475dc250689f7b1608f9ce--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 37f6c86d43a1fca70ed05221dcc2c4938e848bea at: https://644767f09b56c3041544a365--layer5.netlify.app

**Review by ayushthe1 — APPROVED** [review]
Thanks for the changes @AkashS20 . The unused-css test has been fixed on all the pages except 2.  Maybe you can create another pr for that once you find the solution.  This solves the test for most part.  :+1:

**Comment by Nikhil-Ladha** [comment]
@ayushthe1 do we still need this PR? IF so, why do we need to add a new package to fix the issue?

**Comment by thisiskaransgit** [comment]
@ayushthe1 and @AkashS20, How are we moving forward with this PR?

**Comment by Chadha93** [comment]
@AkashS20, Given no response to @Nikhil-Ladha's question, let's close this PR, Feel free to open or create a new one.

**Pull request closed without merging**
