### PR TITLE
feat: add animated terminal

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

Add a terminal that animates on scrolling. 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
URL to check in local - http://localhost:8000/animated-terminal

**Comment by leecalcote** [comment]
What is this?!? 😀

**Comment by Tanuj22** [comment]
> What is this?!? 😀

The animated steps list of https://www.waypointproject.io

**Comment by leecalcote** [comment]
Bad joke on my part. 😆 What I mean is.... "This is awesome 😄 ❗"

**Review by leecalcote — APPROVED** [review]
Very excited about this.

**Pull request merged**
