### PR TITLE
Adding glow & hover effect to the clickable cards

### LINKED ISSUE #5044: [UI] Missing Hover effect on clickable cards
### Description

The cards on: https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers
are clickable but unlike other cards on the website, these do not have the standard glow hover effect.

image

### Expected Behavior

These should have the glow effect like on other pages where the cards are clickable.

image

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by xbelix**
This PR fixes #5044

[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e26105c4f5615a7aa3792b226d0bb2d0d2664755 at: https://652e77d391a45e0a3f35923e--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit edabff02f2f4ada63e34c40319ba51465447c4b2 at: https://652e9a4270ab88101d98f194--layer5.netlify.app

**Review by sandramsc — COMMENTED** [review]
Looks good.

**Review by Mohith234 — CHANGES_REQUESTED** [review]
**Current Behaviour**
The cards had a green border initially and upon hovering, it changed to white

image

**Desired Behaviour**
Initially, the cards must not have any border, Upon hovering the cards should get a green glow effect.

**Comment by sandramsc** [comment]
Just for clarification purposes, based on feedback from @Mohith234 

based on the issue description as I've understood it, the goal is to update the styling on the specified cards so that on hover they have the "whitish-color" glow effect on the border and when **not** hovered (initial state) on they should have a green glowing border.

However @Mohith234 you suggest that initially, the cards should **not** have the green glowing border (remain as they are currently in their pre-hover state) and only have the styling for the green glow effect on the border after hover.

@xbelix perhaps you can **update** the issue description with a **link to the "expected behaviour" cards**, if the goal is to replicate the initial and on-hover styling for the indicated cards? This might make the expectations (if I understood the issue description as stated above) of the end goal clearer, as there are other cards that are styled differently within the same website i.e initial state no glowing border, hover state "whitish-color" glowing border...then initial state no glowing border, hover state no glowing border?

**Comment by xbelix** [comment]
@Mohith234 Alright I got it, I thought they want it to be similar to other cards in the website.


@sandramsc Thank you for your clarifications, I understood it what exactly how to do it

**Comment by l5io** [comment]
🚀 Preview for commit e1bbcd7fb749020d4708fecab93c6488cd519b1f at: https://6530fc61cc1b68044e3f45c4--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @xbelix  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @xbelix  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @xbelix  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by sudhanshutech** [comment]
Due to no response for now i am closing this pr , @xbelix if you want you can get reassigned and create a quick new pr. While making a pr ensure that there should no unnecessary line changes as it takes time for reviewers to review

**Pull request closed without merging**
