### PR TITLE
update kanvas logo in CTA

### PR DESCRIPTION
**Pull request by CalebZoe**
**Description**

This PR 

BEFORE: 
Screenshot from 2024-10-31 10-08-18

AFTER: 
image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by CalebZoe** [comment]
@leecalcote Sir, I replaced the CTA logo // @Touriist @vishalvivekm

**Comment by l5io** [comment]
🚀 Preview for commit a3455a49e06d530494f198394ea8bf271575b098 at: https://67230beba52404e87b8b26ba--layer5.netlify.app

**Review by vishalvivekm — APPROVED** [review]
Thank you, @CalebZoe
Let's find out other such instances as well, where we aren't using the new kanvas logo. // @anand-theertha

**Comment by l5io** [comment]
🚀 Preview for commit df5bb8e79974b6b683d3d5a3c0d1a00204eefd76 at: https://672311e28dba55fb19d11b90--layer5.netlify.app

**Comment by Anand-Theertha** [comment]
Will open a PR fixing them whenever I come across them. @vishalvivekm

**Pull request merged**
