### PR TITLE
Developer-defined Infrastructure page added

### PR DESCRIPTION
**Pull request by iArchitSharma**
screencapture-localhost-8000-solutions-developer-defined-infrastructure-2024-02-08-21_11_48

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9803c16b31258dde11cbd9254dc84a914772312e at: https://65c4f9c6a894a6070a02e3ae--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 228bf4091c325fd76ed533af0375bc294cd234c8 at: https://65cb74be1d799d06042a5897--layer5.netlify.app

**Comment by leecalcote** [comment]
Thank you, @iArchitSharma

**Comment by ritiksaxena124** [comment]
@iArchitSharma, Thank you for this. Fix this animation on other pages as well, please

**Comment by l5io** [comment]
🚀 Preview for commit 8f4b42c3d5ed0ad09b1c269104b811a042915f9f at: https://65cb7ba5a028d80b563150c2--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 810c757945992b0f1509f9ef4e6e88c62e4c1fb1 at: https://65de0794904432007c5f4380--layer5.netlify.app

**Comment by leecalcote** [comment]
We should have another look at this and see what content we might need to update before publishing

**Comment by l5io** [comment]
🚀 Preview for commit 41da655d225313ef210571bc00311b2c7a625d15 at: https://6654ddac3fd68d3322e584b6--layer5.netlify.app

**Pull request merged**
