### PR TITLE
Assigned UI/UX badges 

### PR DESCRIPTION
**Pull request by Anita-ihuman**
**Description**

This PR assigns UI/UX badges to design contributors in the community for their dedicated efforts towards the projects.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 88388a2bb9400cd79fb7087824132e8264e7b21e at: https://63e2272cd0f5a34c47d8a301--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 872b1639a7e6f0c4d302216e6cee14589713f0ee at: https://63e26359f01ed30bb959b211--layer5.netlify.app

**Comment by leecalcote** [comment]
Let's have @geraldmaboshe review.

**Review by geraldmaboshe — APPROVED** [review]
LGTM! Thank you, @Anita-ihuman!

**Review by leecalcote — APPROVED** [review]
yay! 🎉

**Pull request merged**
