### PR TITLE
[DC22] Video for hpe talk DC22

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**

This PR fixes #
Fixes view issues, made it look aesthetic(difference between designer/visualizer), added video for talk with HPE 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e40a2035b88fc669bc8a6801a23bc4e8b5d73081 at: https://6283e1ce11c4d90f5d83ad17--layer5ng.netlify.app

**Review by leecalcote — COMMENTED** [review]
@Chadha93 will you move the text in bold to below the video and have that text as the final CTA?

**Comment by Chadha93** [comment]
> 

Sure I'll do it for HashiCorp Blog too.

**Comment by l5io** [comment]
🚀 Preview for commit ace52c875448705a79a07251a2f1a38237e00a53 at: https://6283ecf1d6b42e0084a59236--layer5ng.netlify.app

**Review by mchurichi — COMMENTED** [review]
Thanks @Chadha93, it looks good to me 💯 I'll push another PR with some minor changes on the content in a bit

**Comment by Chadha93** [comment]
> @Chadha93 will you move the text in bold to below the video and have that text as the final CTA?



> Thanks @Chadha93, it looks good to me 100 I'll push another PR with some minor changes on the content in a bit

Sure @mchurichi 🙌

**Pull request merged**
