### PR TITLE
member profile template and published flag added

### LINKED ISSUE #1256: [NG] Community : Contributor and Community Member Profile Template
**Current Behavior**

Community Members need to mimic a fellow member.

**Desired Situation**

A generic Member Profile Template with instructions to add New Community Members to the new Website.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by pjzzz**
Signed-off-by: Prayag Jain <offpjain@gmail.com>

**Description**

This PR fixes #1256. Took help of already existing branch member-template branch
Let me know of any changes. 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Are we planning to keep focus, tech, and DOJ ?

**Comment by Tanuj22** [comment]
> Are we planning to keep focus, tech, and DOJ ?

I don't think so. @pjzzz can you remove them and add badges instead. Also the build is failing if you can take a look at that

**Comment by pjzzz** [comment]
> > Are we planning to keep focus, tech, and DOJ ?
> 
> I don't think so. @pjzzz can you remove them and add badges instead. Also the build is failing if you can take a look at that

Okay will remove and add badges. Yeah work on the build issue as well. Facing the following error.
layer5

**Comment by Tanuj22** [comment]
@pjzzz can you remove the changes in `package-lock.json` from the commit. Rest looks good

**Comment by pjzzz** [comment]
> @pjzzz can you remove the changes in `package-lock.json` from the commit. Rest looks good

Done. Also was curious why exactly did the package-lock.json change at my system cause primarily it helps me set up the project, correct me if I am wrong.

**Comment by Tanuj22** [comment]
> > @pjzzz can you remove the changes in `package-lock.json` from the commit. Rest looks good
> 
> Done. Also was curious why exactly did the package-lock.json change on my system cause primarily it helps me set up the project, correct me if I am wrong.

This is something we are trying to understand currently. From what I have seen as of now is that Big Sur and other OS are generating different `package-lock.json` file

**Review by Tanuj22 — APPROVED** [review]
LGTM. Thanks for working on this :)

**Pull request merged**
