### PR TITLE
award-badges-to-members

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
**Description**

This PR
⭐ awards badges to members.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
### Congratulations 🎊
@aabidsofi19  @senali-d @Yashsharma1911 @sudhanshutech @saurabh100ni @the-techgurl🎈

Please take a look at the badges on your [profiles](https://layer5.io/community/members).
Thank you for your contributions to the Layer5 community!

**Comment by l5io** [comment]
🚀 Preview for commit 55d3fd1018bf9fb8630505abdd4c270de00ee29f at: https://65290d8f1d133d117d59f435--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
### Congratulations 🎊
@aabidsofi19 @senali-d @Yashsharma1911 @sudhanshutech @saurabh100ni @the-techgurl🎈

Please take a look at the badges on your profiles.
Thank you for your contributions to the Layer5 community!

**Review by sudhanshutech — APPROVED** [review]
LGTM

**Pull request merged**
