### PR TITLE
fixed role options color

### LINKED ISSUE #5232: [BUG] Options not visible in roles dropdown list on meshmap page
### Description
https://layer5.io/cloud-native-management/meshmap
Here at "join the beta" form "select role" options are not visible. 

### Expected Behavior
Text color should be changed

### Screenshots
Screenshot 2023-12-26 112840

### Environment:
- Host OS: windoes
- Browser: chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by akshat-kaushik**
**Description**

This PR fixes #5232 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b96d01a955ba1b2d45622435037b3a4cd1a608b4 at: https://658a773f58d63a6c8d20bee0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b96d01a955ba1b2d45622435037b3a4cd1a608b4 at: https://658a7ed056d73470b2d1a2de--layer5.netlify.app

**Comment by leecalcote** [comment]
Let's avoid mandating white background and black text. Instead, these colors should change (invert) based on light vs dark mode.

Screenshot 2023-12-28 at 8 30 55 AM

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you for tackling this, @akshat-kaushik 👍 

Let's avoid mandating white background and black text. Instead, these colors should change (invert) based on light vs dark mode.

Screenshot 2023-12-28 at 8 30 55 AM

**Comment by saurabh100ni** [comment]
Hey @akshat-kaushik  ,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Pull request closed without merging**
