### PR TITLE
feat: community page

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
I think the radius for the first image can be avoided.

**Comment by Nikhil-Ladha** [comment]
Why are the subtitles are the title listed in the opposite way? 🤔

Also, the callout for the the newcomers can be changed to something like:

Are you new to the community? (A h2 text, center aligned)
Don't worry, we have got you covered. (A h4 text, center aligned)
'Hop In ->' ( This will be button)

**Comment by leecalcote** [comment]
Is it possible to set the image slide to autostart?

**Comment by Tanuj22** [comment]
I noticed that the design in figma charged a bit. So adjusted according to that.

**Comment by Tanuj22** [comment]
> I think the radius for the first image can be avoided.

I just exported the image from figma. Where can I get the original image?

**Comment by Nikhil-Ladha** [comment]
> > I think the radius for the first image can be avoided.
> 
> I just exported the image from figma. Where can I get the original image?

In the Layer5 shared drive itself. Search with the image name mentioned in figma.

**Comment by leecalcote** [comment]
The MeshMate logo is available in SVG, too

**Comment by Tanuj22** [comment]
Done!

**Review by Jashpatel1 — COMMENTED** [review]
The heading sizes are less as compared to other pages.

**Comment by Nikhil-Ladha** [comment]
Typo in newcomers button:
Hope -> Hop

**Comment by Nikhil-Ladha** [comment]
> The heading sizes are less as compared to other pages.

Ignore this for now. I have added the default font sizes for each type of heading but commented out. Let's merge this one and then I would reset the heading sizes globally in the site.

**Comment by Tanuj22** [comment]
Done 

> Typo in newcomers button:
> Hope -> Hop

**Comment by Tanuj22** [comment]
@Nikhil-Ladha @leecalcote any thing more to be done here?

**Comment by Nikhil-Ladha** [comment]
> Why are the subtitles are the title listed in the opposite way? thinking

Any justification for this?

**Comment by Nikhil-Ladha** [comment]
The line `New members are always welcome` below the heading should be in h2 and not p

**Comment by Tanuj22** [comment]
> > Why are the subtitles and the title listed in the opposite way?
> 
> Any justification for this?

What do you mean by opposite way?

**Comment by Nikhil-Ladha** [comment]
> What do you mean by opposite way?

The tagline is being shown first and then the header. For example:

`Jump In! Our Community is warm
Our Community Members`

Instead, it should be:
`Our Community Members
Jump In! Our Community is warm`

**Comment by Tanuj22** [comment]
> > What do you mean by opposite way?
> 
> The tagline is being shown first and then the header. For example:
> 
> ```
> Jump In! Our Community is warm
> Our Community Members
> ```
> 
> Instead, it should be:
> 
> ```
> Our Community Members
> Jump In! Our Community is warm
> ```

I followed what was in the design :sweat_smile: . Should I change it?

**Comment by Nikhil-Ladha** [comment]
I think so, yes 😄

**Comment by Nikhil-Ladha** [comment]
Also, if you could rebase your code so that the header sizes are updated and we can confirm on the same if everything looks good.

I think we might need to add some media queries for screen width less than 575px.
Could you please do that?

**Comment by Tanuj22** [comment]
> Also, if you could rebase your code so that the header sizes are updated and we can confirm on the same if everything looks good.
> 
> I think we might need to add some media queries for screen width less than 575px.
> Could you please do that?

Okay

**Comment by Tanuj22** [comment]
For mobile, I noticed that the font sizes of the headers are different from those in desktop view. Are these written somewhere so that these can also be centrally controlled? @Nikhil-Ladha @leecalcote

**Comment by Nikhil-Ladha** [comment]
> For mobile, I noticed that the font sizes of the headers are different from those in desktop view. Are these written somewhere so that these can also be centrally controlled? @Nikhil-Ladha @leecalcote

I know, they are reduced for mobile view. Currently, they are not centrally controlled but done section wise. Though we would want it to have centrally controlled.

We can proceed in either way for the time being. As you say.

**Comment by Tanuj22** [comment]
> > For mobile, I noticed that the font sizes of the headers are different from those in desktop view. Are these written somewhere so that these can also be centrally controlled? @Nikhil-Ladha @leecalcote
> 
> I know, they are reduced for mobile view. Currently, they are not centrally controlled but done section wise. Though we would want it to have centrally controlled.
> 
> We can proceed in either way for the time being. As you say.

The ratio being used in Figma is the same for the mobile views that we have currently. If they are final I say we centrally define it :thinking:

**Comment by Nikhil-Ladha** [comment]
The cursor doesn't change to a pointer on hovering the button for the link `Open source mentorship program`

**Comment by Nikhil-Ladha** [comment]
> The ratio being used in Figma is the same for the mobile views that we have currently. If they are final I say we centrally define it

Same as in you are saying currently we have the same font-size for mobile view and desktop view? Or something different?

**Comment by Tanuj22** [comment]
> > The ratio being used in Figma is the same for the mobile views that we have currently. If they are final I say we centrally define it
> 
> Same as in you are saying currently we have the same font-size for mobile view and desktop view? Or something different?

I meant that there is consistency for the header sizes for the mobiles views we have

**Comment by Tanuj22** [comment]
Like h1 is `28px` I think in mobile

**Comment by Nikhil-Ladha** [comment]
Ohh....right. Yes, that would be better. If you can update it globally as well as in other areas as well. Please do it.

Or you can do a workaround for this page in this PR and later make a seperate PR for global one. What say?

**Comment by Tanuj22** [comment]
Let's merge this as it is now? Making a separate PR (so that I don't mess up this branch :sweat_smile: ) for global headers next

**Comment by leecalcote** [comment]
Sounds good.

**Pull request merged**
