### PR TITLE
HTML and Markdown Mixing

### PR DESCRIPTION
**Pull request by TUSHAR1651**
I have Removed all the Html tags in the Readme and used the Markdown for the Readme 
It decreases the chance of inconsistent rendering across different platforms or tools

Issue #5778 resolved

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a3cc1cbb79c88426dfef93adc81403f7dd4d9197 at: https://66ae89639e097edcdaed7c13--layer5.netlify.app

**Comment by Ashparshp** [comment]
@TUSHAR1651 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by sudhanshutech** [comment]
@vishalvivekm is this change required?

**Comment by sudhanshutech** [comment]
@TUSHAR1651 none of the links showing the logo

**Comment by sudhanshutech** [comment]
@TUSHAR1651 thanks for contribution but seems like its not required now so lets close this for now and get you some other issues. Please do join our website meet to discuss this if required so we will able to understand your progress and issue more easily

**Pull request closed without merging**
