### PR TITLE
[NG] Add social component

### LINKED ISSUE #896: [NG] Create social links component
**Current Behavior**
Social icons are being used in both footer and about us page.

**Desired Behavior**
Create a separate component for them so that they can be reused. Keep the component in the `component` folder and use that in both the footer and the about us page. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Harshita-Kanal**
Signed-off-by: Harshita-Kanal <harshita.kgv@gmail.com>

**Description**

This PR fixes #896 

**Notes for Reviewers**
Made the social links into a separate component

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Harshita-Kanal** [comment]
I have added the component and used it in about us, in the footer, different images are used, should I follow some other approach?

**Review by Jashpatel1 — COMMENTED** [review]
Nice work. Thanks @Harshita-Kanal 
As the previews are not available, can you just attach a screenshot or a small screen recording video to see the changes made?

**Comment by Tanuj22** [comment]
@Harshita-Kanal you can use the icons used in the footer in the component (use that in both footer and about us)

**Comment by Harshita-Kanal** [comment]
> @Harshita-Kanal you can use the icons used in the footer in the component (use that in both footer and about us)

yeah, but the footer icons are white, and the about us icons are black, is there a way to dynamically change the fill color of svgs

**Comment by Harshita-Kanal** [comment]
> Nice work. Thanks @Harshita-Kanal
> As the previews are not available, can you just attach a screenshot or a small screen recording video to see the changes made?

image

Just the icons.

**Comment by leecalcote** [comment]
@Jashpatel1 this works really well for quick checking out a PR branch and running a quick `make site` - - 

Screen Shot 2020-10-13 at 5 26 54 PM

**Comment by Tanuj22** [comment]
@Harshita-Kanal let's move ahead with this PR and come back to it if we can figure out how to dynamically change the color. Could you run `npm run lint` to fix the linting?

**Comment by Harshita-Kanal** [comment]
I have fixed the linting.

**Comment by Tanuj22** [comment]
> I have fixed the linting.

Can you do the same for about page

**Comment by Harshita-Kanal** [comment]
Added it

**Review by Tanuj22 — APPROVED** [review]
Thanks @Harshita-Kanal

**Pull request merged**
