### PR TITLE
Diagramming and Orchestration component added to Integration pages

### PR DESCRIPTION
**Pull request by iArchitSharma**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5fa0cdc474b1f425523c8fed69b337bd85c83c34 at: https://65b7bff03824260d70886fd5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 61c541ad91128cdda1dc54075b1f7757dcea7259 at: https://65b7cbeb1e675b15707ef156--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3f869918273710bfee4fc7d2873590b5e3dfdda9 at: https://65bbd8a8a917b50a040088e9--layer5.netlify.app

**Review by ritiksaxena124 — APPROVED** [review]
You connected the integrations page with their respective information pages. Thanks @iArchitSharma  🚀

**Pull request merged**
