### PR TITLE
Error boundary component

### PR DESCRIPTION
**Pull request by aayushdhiman01**
**Description**
Added  error boundary component in sistent components .
This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8a7ef7ac8df19c32f206481460b77ae20aa5679e at: https://669ba71909fafc5bcd4788f5--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@aayushdhiman01 i guess its not completed right? Because styles are not good and error boundary component also doesn't show up

**Comment by aayushdhiman01** [comment]
@sudhanshutech yes, how to show the component? I was trying to create a demo component and trigger an error so that it shows error boundary component?

**Comment by Ashparshp** [comment]
@aayushdhiman01 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by sudhanshutech** [comment]
@aayushdhiman01 are you still here? Are you working on this?

**Comment by sudhanshutech** [comment]
@aayushdhiman01 ?

**Comment by aayushdhiman01** [comment]
@sudhanshutech I am not working on this anymore

**Pull request closed without merging**
