### PR TITLE
Rearranged the content within the community & Contributor ladder section

### LINKED ISSUE #2261: [handbook] Rearrange the content within the community & Contributor ladder section
**Description**
There is a repetition that exists in the "community " and "contributor ladder ". The  'manager', meshmate & maintainer are without any subheading.

**Expected Behavior**
We want to separate the role and responsibilities of "Maintainer, Meshmate and manager" to exist in the Contributor ladder instead of Community Guidelines. Refer to[ this doc f](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit?disco=AAAAQ2ziZW0)or a more information

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by YashKamboj**
**Description**
There is a repetition that exists in the "community " and "contributor ladder ". The 'manager', meshmate & maintainer are without any subheading. Updated the "community " and "contributor ladder " as per  https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit#heading=h.22j8crdxnbmv
This PR fixes #2261 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 684587ade3ea2c7ea7ba574860a8c7eb4ac6d54c at: https://6165db06f346d80a48e20e9b--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3d1285336a61383295b2fcea5e97b34a1c97f238 at: https://616d43de74687f02b317ae57--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit dec99d21896a85692912c799b6f6feeab061504a at: https://616eb31638c32e3e1f071e3e--layer5ng.netlify.app

**Comment by YashKamboj** [comment]
@warunicorn19 are the changes good

**Pull request merged**
