### PR TITLE
feat(collections/members): add Yash Kamboj profile

### LINKED ISSUE #2564: [Community] Member Profile: Yash Kamboj
**Current Behavior**

@YashKamboj has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @YashKamboj as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @YashKamboj 
- Twitter: @yashkamboj123
- LinkedIn: https://www.linkedin.com/in/yash-kamboj-9078011b5
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by KXLAA**
Signed-off-by: Kolade Afode <kolade.afode@yahoo.com>

**Description**

This PR fixes #2564

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a60086ff9d0f761db623e2843eb459ac3f43a53e at: https://61fa8933ffb822168ffe977e--layer5ng.netlify.app

**Review by YashKamboj — APPROVED** [review]
LGTM!! Good Work 👌

**Comment by KXLAA** [comment]
> LGTM!! Good Work 👌

Thanks Yash

**Review by warunicorn19 — APPROVED** [review]
Thank you @KXLAA

**Pull request merged**
