### PR TITLE
Add "All Integrations" button

### LINKED ISSUE #5047: Add "All Integrations" button
### Current Behavior
On https://layer5.io/cloud-native-management/meshmap/design, the Built-in Integrations section needs to have a button leading the visitor to the page that displays all integrations.

### Desired Situation
1. Add new button linking to this page: https://layer5.io/cloud-native-management/meshery/integrations
1. Ensure responsive underline image placement in the Built-in Integrations heading.

### Mockup:

Screenshot 2023-10-16 at 9 32 59 PM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vamsi4845**
**Description**

This PR fixes #5047 

**Notes for Reviewers**
1. Added a new button that redirects to: https://layer5.io/cloud-native-management/meshery/integrations
2. Ensured responsiveness of under-line-image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 92ba09c7eecfdac360cc406829a80d573ffdf182 at: https://652eaa6e9aea691b45805392--layer5.netlify.app

**Comment by vamsi4845** [comment]
> Hey @vamsi4845 , please update the PR title to be descriptive of the change and also sign-off your commits to pass DCO check. For signing off your commits you can do this while making commit, git commit -s -m "your_commit_msg".

**Comment by l5io** [comment]
🚀 Preview for commit 43e49e633ebef9bc56e22615b79ae1c41cd3afa0 at: https://652eb5bc36f5982a8d6b1b31--layer5.netlify.app

**Comment by vamsi4845** [comment]
@l5io Can you help me?I'm not able to solve the issue

**Comment by l5io** [comment]
🚀 Preview for commit c5e537a83c44405e870a5f6f13bc727949fce1fb at: https://652f8299d4e1846175121295--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit bc3aad1c239740975f405541696be04ed97fc16d at: https://652fc481f4e7dd20532d3b67--layer5.netlify.app

**Pull request closed without merging**
