### PR TITLE
[Review] Removed repeated entity from quote section

### PR DESCRIPTION
**Pull request by VishrutAggarwal**
**Description**

This PR fixes the issue #4200.

I also noticed another repetition by a different entity as mentioned [here](https://github.com/layer5io/layer5/issues/4200#issuecomment-1538354932). Let me know how to proceed with that.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by thisiskaransgit — APPROVED** [review]

**Comment by thisiskaransgit** [comment]
Looks good to merge, thank you for your contribution :tada:

**Comment by VishrutAggarwal** [comment]
Hi @thisiskaransgit,

Will the PR get merged as it is or is there any procedures left which I might be unaware of? I am new to contributing to layer5 and am not completely aware of the inner workings of the community yet. Would it be possible to let me know what is causing the delay?

**Review by leecalcote — APPROVED** [review]
💯 Thank you, @VishrutAggarwal

**Comment by leecalcote** [comment]
> Hi @thisiskaransgit,
> 
> Will the PR get merged as it is or is there any procedures left which I might be unaware of? I am new to contributing to layer5 and am not completely aware of the inner workings of the community yet. Would it be possible to let me know what is causing the delay?

None. Just that the contributors outweigh the maintainers. Hopefully, you'll be around long enough and become skilled enough to be a maintainer here one day. If you're committed to it, let's set you on that path (warning: it's not for the faint of heart).

**Pull request merged**
