### PR TITLE
feat: wrap interviewee responses in quotes

### LINKED ISSUE #5882: Add Frontmatter for Interviewee/Interviewer and Quotation Styling for Blog Posts
### Current Behavior
This issue is for tracking two enhancements for the upcoming interview-style blog posts on [Layer5.io](https://layer5.io). These enhancements aim to improve the internal references in frontmatter and apply styling to interviewee responses.

### **Enhancements**

1. **Frontmatter Additions:**
   - Add two new frontmatter items: `interviewee` and `interviewer`.
   - These fields will serve as internal references for the blog posts but will not be displayed on the front-end.

2. **CSS Quotation Styling:**
   - Automatically wrap interviewee responses in quotation marks using CSS pseudo-selectors (`::before` and `::after`).
   - The interviewee’s responses should be wrapped in opening and closing quotes to improve readability and maintain a consistent style across all posts.

### **Tasks**
- [ ] Add new frontmatter fields for `interviewee` and `interviewer`.
- [ ] Ensure these fields are only internal references and are not displayed in the blog post content.
- [ ] Use CSS to wrap interviewee responses with quotation marks using pseudo-selectors.
- [ ] Test to ensure consistency across various blog posts.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Sumit2997**
**Description**

This PR fixes #5882 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5ef059532ef211c82ae8bbdc2eff9512dc7864e1 at: https://66fd894b764d0051efd606c8--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Sumit2997 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by leecalcote** [comment]
@hargunkaur286 how does this look?

@hargunkaur286 have you followed through on Meet the Maintainers?

**Comment by l5io** [comment]
🚀 Preview for commit b77bf48ad2185e664465b4c664844fd719581a16 at: https://6707ba7d2c7be2091ee80e77--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4372d0ab2d7d4b0cb8178df31dc1c2bbeb690f2c at: https://670ad2ff88dbea7ed8a99bb0--layer5.netlify.app

**Review by Touriist — APPROVED** [review]
Thanks much for this @Sumit2997. LGTM

**Pull request merged**
