### PR TITLE
Updated the Cert Manager Csi Driver Cacerts under 'How it Works See I…

### LINKED ISSUE #4866: [Screenshots] Cert Manager Csi Driver Cacerts under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/cert-manager-csi-driver-cacerts) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Cert Manager Csi Driver Cacerts](https://layer5.io/cloud-native-management/meshery/integrations/cert-manager-csi-driver-cacerts) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Bprathmesh**
…t in Action' section

**Description**

This PR fixes #4866 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ 
Screenshot 2024-08-12 at 16 52 40
Screenshot 2024-08-12 at 16 54 10
Screenshot 2024-08-12 at 16 55 22
Screenshot 2024-08-12 at 16 55 41
] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 586d0f6fb0f15d7fc0ed49a40225b394e494d976 at: https://66bb19128742a4c48fd6b020--layer5.netlify.app

**Comment by Ashparshp** [comment]
@Bprathmesh, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
Please Refer to : https://github.com/layer5io/layer5/pull/5129#issue-1995493031

**Comment by l5io** [comment]
🚀 Preview for commit d5c8059031db081ce5749f6f009d46fa17d3add9 at: https://66d3997554293187dedc6521--layer5.netlify.app

**Pull request closed without merging**
