### PR TITLE
[community] Member profile : Swathi Loganathan

### LINKED ISSUE #3835: [Community] Member Profile: Swathi Loganathan
**Current Behavior**

@Swathi-L has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Swathi-L as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Swathi-L
- Twitter: 
- LinkedIn: swathi-l
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by roopeshsn**
**Description**
Created a member profile for Swathi Loganathan.

This PR fixes #3835 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 96a953e8e6b0456cde01d83e75d1b157fe075c14 at: https://6401619cda519c6e989cb770--layer5.netlify.app

**Comment by roopeshsn** [comment]
Here you go @Swathi-L https://6401619cda519c6e989cb770--layer5.netlify.app/community/members/swathi-loganathan

**Comment by Swathi-L** [comment]
> Here you go @Swathi-L https://6401619cda519c6e989cb770--layer5.netlify.app/community/members/swathi-loganathan

Thanks @roopeshsn, LGTM!

**Review by Nikhil-Ladha — APPROVED** [review]
There she is!
Nice 🥳

**Pull request merged**
