### PR TITLE
Core: Resource optimization and lang fix

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description**

This PR reduces unwanted js package loading for all the pages and limits it to only the required pages.
Also, somehow the `Layout` component was set to `lang="pt"` earlier (looks like since inception, and nobody checked), updated it `en`.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 88f52e42af0c079f790094519f3b89fb476fd5ef at: https://621724435237e45c93500bbe--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
@Nikhil-Ladha could you please give a brief run-through of what this PR does on today's websites' call?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha could you please give a brief run-through of what this PR does on today's websites' call?

Sure.

**Comment by Nikhil-Ladha** [comment]
Though, the changes completely resolve what was expected out of it initially. But, anyways it is better to have the packages used only where it is needed.

**Pull request merged**
