### PR TITLE
added member profile for meghana

### LINKED ISSUE #2141: [Community] Member Profile: Meghana Varanasi
**Current Behavior**

@Meghana-12  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Meghana-12  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Meghana-12 
- Twitter: meghana_cosmos (https://twitter.com/meghana_cosmos)
- LinkedIn: Meghana Varanasi (https://www.linkedin.com/in/meghana100/)
- Link to profile picture: https://ibb.co/Y0ptzwj

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Added the member profile for @Meghana-12 
This PR fixes #2141

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3286ee1559c05165ea0ebe1117c6c16fa9d47ba1 at: https://612d10eb31e65700bcc792b4--layer5ng.netlify.app

**Comment by Meghana-12** [comment]
I love it! Thank you for working on this :D 

Is it possible to zoom the image though?

**Comment by warunicorn19** [comment]
@Meghana-12 if you have no problem with it, I can crop it a bit and then put that up.😅

**Comment by leecalcote** [comment]
💥 @Meghana-12

**Comment by l5io** [comment]
🚀 Preview for commit dcf9742cb2010d07d31cc96ae86f03c5a9e57ee5 at: https://612d20f7222dc2238d5eb9fd--layer5ng.netlify.app

**Pull request merged**
