### PR TITLE
Added stick-figures section

### LINKED ISSUE #4369: [Add] Section for Stick Figures on /brand page
### Current Behavior
Currently, we don't have a section for Stick Figures on the [layer5.io/brand](https://layer5.io/company/brand) page

### Desired Behavior
Add a section of the layer5.io/brand page with a description and a button to download stick figures.

- **Description**: Introducing stick figures, a playful and dynamic visual language that captures the essence of Layer5.io. These charming and minimalist illustrations serve as the perfect embodiment of our brand's values and offerings.

- **Stick Figures**: [Stick Figures.zip](https://github.com/layer5io/layer5/files/11712776/Stick.Figures.zip)

### Implementation
1. Setup layer5.io website on the local machine
2. Add a section on the layer5.io/brand page with the title "Stick Figures"
3. Download the file stick-figures.zip file provided above, and add a button in the section to allow users to download the file
4. Add the description of the section provided above
5. Make a PR 🙌
6. Wait for maintainers to review the PR ✔
7. Once approved share your experience on socials and celebrate 🎉 (Don't forget to tag layer5)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #4369 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4cc039373de8ed8364bbf754d70d98aba7d6627f at: https://649026b40335764a2768d460--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 94ade12c01123b93ca6c7c5b129f083b3e4c0f37 at: https://6490402012fa58550e402787--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
LGTM 🔥. Nice work @Mohith234

**Review by Shivam-AfA — CHANGES_REQUESTED** [review]
@Mohith234 Thanks for this PR. Some changes to make before we merge this:
- The SVG that is being used does not support dark mode, Please change the background of SVG to dark when theme is changed:
image

- Where are we using the PNG images that you included in this PR? And if we are to use them, lease use WEBP format.

**Comment by Shivam-AfA** [comment]
@Mohith234 You'll have to use the method mentioned in the [contributing guide](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#changing-svg-according-to-theme) to make the svg compatible with dark mode. Please go through it.

**Comment by ritiksaxena124** [comment]
we don't have/support alternative color versions of mascots and the current color won't be visible in dark mode that's why we are using paper in the background. // @Shivam-AfA @Mohith234

**Review by ritiksaxena124 — CHANGES_REQUESTED** [review]
@Mohith234 Please remove the solo stick figures from assets folders as they are already in a zip file so there is no need to put them in here. only keep the SVG with three stick figures combined.

**Comment by l5io** [comment]
🚀 Preview for commit b4f80795b90e7d7f50a9b87e28c304b71cb3d587 at: https://6499450083147617eb371b8c--layer5.netlify.app

**Review by ritiksaxena124 — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]
Nice work @Mohith234

**Pull request merged**
