### PR TITLE
Updated profiles for few members

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
This PR updates the bio, LinkedIn, location, and badges for a few of the members.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Looks good to me. Just a thing if we follow the same order of attributes in frontmatter.

**Comment by Nikhil-Ladha** [comment]
Ohh, like in which order?
Github
Twitter
LinkedIn
Location
Badges
Bio

This way, right?

**Comment by Jashpatel1** [comment]
> Ohh, like in which order?
> Github
> Twitter
> LinkedIn
> Location
> Badges
> Bio
> 
> This way, right?

Maybe the one mentioned in the template. Or you can update the template accordingly.

**Comment by Nikhil-Ladha** [comment]
I think I we should keep the template ad well is the above order which I mentioned, like the status, blurb, MeshMate, maintainer and all should be at last I think.

**Review by Jashpatel1 — APPROVED** [review]
LGTM

**Pull request merged**
