### PR TITLE
Piyush-singariya_profile_added

### LINKED ISSUE #1832: [Community] Member Profile: Piyush Singariya
**Current Behavior**

@piyushsingariya has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @piyushsingariya as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  piyushsingariya 
- Twitter:  piyushsingariya
- LinkedIn:  piyushsingariya
- Link to profile picture: https://drive.google.com/file/d/1LpZfiOxYm5MO4O9Bh3yd6DD5XsJyPj7i/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by sachindavra**
Signed-off-by: Sachin Davra <raju.davra@gmail.com>

**Description**

This PR fixes #1832

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sachindavra** [comment]
Kindly review and merge.

**Comment by Nikhil-Ladha** [comment]
@sachindavra could you please update the issue number in the description like `This PR fixes <issue-number` so that when the PR is merged, the issue is automatically closed?

**Comment by l5io** [comment]
🚀 Preview for commit 49b44e4453cf8e6fca99969e585373ea75e46852 at: https://60903a7841beb400dac73a88--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Also, could you please update this line https://github.com/layer5io/layer5/blob/2d8923f123b41842155221c268c16962384f92b3/src/components/Profile-card/index.js#L17 to `{ meshmate === "yes" && (`

**Comment by Nikhil-Ladha** [comment]
I think in the description you have mentioned the PR number and not the issue number. Please update that.

**Comment by sachindavra** [comment]
> I think in the description you have mentioned the PR number and not the issue number. Please update that.

I have updated with the issue number.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Thank you @sachindavra :)

**Comment by sachindavra** [comment]
> Thank you @sachindavra :)

Welcome!

**Pull request merged**
