### PR TITLE
Updated the smps  logo

### PR DESCRIPTION
**Pull request by Rohan-GD**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Rohan-GD** [comment]
Hey...I'm kinda lost and i think i messed up the forked repo, can you help with the entire process , it's my first time contributing

**Comment by leecalcote** [comment]
@Rohan-GD, no sweat. Jump into http://slack.layer5.io and message @Ruth-ikegah

**Comment by leecalcote** [comment]
Oh, I didn't see @Jashpatel1's comment above. @Rohan-GD when you join the Slack, please message @Jashpatel1 . 😉

**Comment by leecalcote** [comment]
To sign-off on these commits in this PR, you can execute this - https://github.com/layer5io/layer5/pull/613/checks?check_run_id=975262762

**Comment by Rohan-GD** [comment]
Alrighty

**Comment by Ruth-ikegah** [comment]
Hi @Rohan-GD, nice work on the PR. If you still having trouble with the DCO check, you hit me up on Slack! I will be happy to help

**Comment by leecalcote** [comment]
Let me help in getting this one through, @Rohan-GD. I'll update on the backend and let you get onto another issue/PR. 👍

**Pull request merged**
