### PR TITLE
Updated the footer code,css

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
This PR cleans up the code for the footer, updates the font for the footer, and fixes a few small redirects and CSS issues.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
The social links component is also used in the about page where it got central aligned unknowingly. Please look into it.

**Comment by Nikhil-Ladha** [comment]
> The social links component is also used in the about page where it got central aligned unknowingly. Please look into it.

I don't think if it is center aligned, it is causing any issue. Infact, it should have been center aligned previously as well.

**Comment by Nikhil-Ladha** [comment]
Still, I think we can ignore that. Since, a new design is under progress and it would be totally updated. So, it will be fixed at that time.

**Comment by leecalcote** [comment]
4218B983-3279-4E70-8B46-57AADBA89820


I’m not sure that Qanelas is coming though. Does it look like it to you guys?

**Comment by Tanuj22** [comment]
> 4218B983-3279-4E70-8B46-57AADBA89820
> 
> I’m not sure that Qanelas is coming though. Does it look like it to you guys?

It is coming through for the section heading but not for the items under a section. Should that also be in Qanelas?

**Comment by leecalcote** [comment]
@Tanuj22 Oh, I see. Thank you for confirming. It's alright if the menu item font is Open Sans. 👍 

Thank you both for this work!

**Pull request merged**
