### PR TITLE
d-cryptic/sidebar edit

### PR DESCRIPTION
**Pull request by d-cryptic**
I was solving issue #2077
First removed the margin-inline-end
And then renamed Header to "Table of Content"

### CODE REVIEW

**Review by sayantan1413 — COMMENTED** [review]
Great @d-cryptic 💪 You have solved the DCO. I would request @Jashpatel1 @Tanuj22 to verify the frontend changes.

**Review by Anita-ihuman — APPROVED** [review]
This looks great @d-cryptic

**Comment by l5io** [comment]
🚀 Preview for commit 983d311e32f6fe3697beb09f599bd53550b8a8b4 at: https://61164b5d75312c0094d0520b--layer5ng.netlify.app

**Review by Jashpatel1 — APPROVED** [review]
Thanks @d-cryptic

**Pull request merged**
