### PR TITLE
updated the workshop page with 3 new workshops

### PR DESCRIPTION
**Pull request by emmanuellar**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by tripathyprateek** [comment]
image
Hi @emmanuellar the workshop page is not behaving as expected. You might need to look into it. Other than that, great job!

**Comment by leecalcote** [comment]
@emmanuellar, thanks for this. Don't forget to list the issue number that you're addressing in the description of your PR. Please sign your commits, if you can.

**Comment by emmanuellar** [comment]
HI @leecalcote I'd love to be unassigned from this issue as I'm having a rough time running installations on my PC which is required to test out the pages. I'll love to contribute on other tasks that doesn't require me running this installation. Thank you.

**Comment by leecalcote** [comment]
@emmanuellar completely understood. No sweat. Let me have a look here about getting this one tied-off and you onto a fresh issue. 👍

**Review by leecalcote — APPROVED** [review]
Nice work. We're ready for merge, @emmanuellar. 👍 

Onto the next issue. 😄

**Comment by emmanuellar** [comment]
Thank you @leecalcote You're way too kind.

**Pull request merged**
