### PR TITLE
Code Quality Improved: Removed the unused variables

### LINKED ISSUE #4492: Code Quality Improvement: Variable declared but not in use.
### Description
There are several variables in different-different files that are being declared but not in use.
Eslint shows 7 warning and 1 error related to that.

### Expected Behavior
There should be code cleanup and variables that are not in use should be removed.
For reference I've attached a screenshot through which one can understand the files where one needs to the cleanup.

### Screenshots
layer5consoleWarnings

### Environment:
- Host OS: Windows 10
- Browser:Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by RakshitKumar04**
This PR fixes #4492

**Notes for Reviewers**
- Corrected the 6 files which showed warnings, but could not find the indentation error as mentioned in the screenshot.
- Orgs/layer5/src/sections/Community/Member-single/index.js
267:1 already has 18 spaces, in spite of 20.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 454c16495b12d71926281317c75c4c71634884cf at: https://64a723e76555d177f26c476d--layer5.netlify.app

**Comment by Mohith234** [comment]
@RakshitKumar04 Don't raise any PRs unless you get assigned. Please follow the contribution guidelines.

**Comment by l5io** [comment]
🚀 Preview for commit 87452f55007bfe8f3f40503386a37c619db16a4b at: https://64a83b5c48013d00736d48ce--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Looks good to me. Thanks, @RakshitKumar04 👍

**Pull request merged**
