### PR TITLE
"Fix #4324 [Handbook] Text changing to white on hover"

### LINKED ISSUE #4324: [Handbook] Text changing to white on hover
### Description
On this page: https://layer5.io/community/handbook, on hovering over the cards, the heading text changes to white.

[screen-capture.webm](https://github.com/layer5io/layer5/assets/88040318/da04d92a-3a12-4cbe-974b-e8c0376db59c)

### Expected Behavior
The text color should remain the same i.e. black for light mode and white for dark mode.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by strawhatrag**
By changing color: #fff to color: ${props => props.theme.text}, you are making the color value dynamic and based on the text value in the theme object.

**Description**
update layer5\src\components\HandbookCard\HandbookCard.style.js

This PR fixes #
Fix #4324 [Handbook] Text changing to white on hover in light mode

-->

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4e0c2dc0e1fa044225131d34022095c0d881074e at: https://647b867abddc512de0d7bf24--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit af6e42cff009477d6c876f270b79acdeb49be9a8 at: https://647c5566bddc51114dd7c135--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
LGTM ✅

**Comment by l5io** [comment]
🚀 Preview for commit 07ed89b64954056ae085d0245ded8c70353c4582 at: https://647da99a4cd97648d4081557--layer5.netlify.app

**Review by suhail34 — APPROVED** [review]
LGTM

**Comment by suhail34** [comment]
> LGTM

@Chadha93 I think this should be merged as in light mode the text becomes invisible on hover

**Comment by l5io** [comment]
🚀 Preview for commit 72928591a6dd9822eef0cbe1ac36e47719dc9464 at: https://64804d8ffa24824c9c3d3a5f--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b7dbb9801ceabaaa62ac6cc62815ac1319a6ae37 at: https://64842f7e2c003b3421beaa2b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b7dbb9801ceabaaa62ac6cc62815ac1319a6ae37 at: https://64842f7d42bbea36993c9cdc--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Shivam-AfA take a look please.

**Comment by Shivam-AfA** [comment]
Hey @strawhatrag, Thanks for fixing this. I'm not sure if this issue was assigned to you. We follow the procedure of assignments here at Layer5, where a contributor asks to work on the issue first, making sure that they are not overruling the assignment of some other contributor. I hope you will remember this when you work on your next issue. Happy contributing! 🚀

**Comment by strawhatrag** [comment]
Sorry for any confusion. I'm new to open source. I appreciate your understanding, and I'll remember your feedback, @Shivam-AfA

**Pull request merged**
