### PR TITLE
fix: invisibility of text in meet the meshmate blog

### LINKED ISSUE #4482: Invisibility of Text in Meet the Meshmate Blog
### Description

Currently in the [blog](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma) meet the meshmate : @Yashsharma1911 by @vishalvivekm 

The name of our friendly meshmate isnt available in dark mode.

### Expected Behavior

His name should be visible

# Possible Fix
- removing the color attribute from interviewee section of [MeetTheMeshMate.style.js](https://github.com/layer5io/layer5/blob/18114f5603813f9ef5ce6c5226028f8715badc61/src/collections/blog/2023/2023-05-24-meet-the-meshmate-yash-sharma/MeetTheMeshMate.style.js?plain=1#L18)
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by princerajpoot20**
**Description**

This PR fixes #4482 

**Notes for Reviewers**
Removed color attribute.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by princerajpoot20** [comment]
@leecalcote Could you please review this.

**Comment by l5io** [comment]
🚀 Preview for commit c54d533059122c127d6618f920c44989fb28dcb6 at: https://64a48b3282e2f51fb043d088--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach @leecalcote Could you please review this.

Hello @princerajpoot20 , We really appreciate your enthusiasm in contributing to layer5 community.
However This issue was assigned to someone else.

We follow First come First Serve order.
In general , You shouldn't raise PR untill the issue is assigned to you.

Please take care of this things in the future.

**Comment by princerajpoot20** [comment]
@Ghat0tkach Sorry for that, I'm not aware about it as I'm contributing here for the first time. I will take care of this in future.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Sorry for that, I'm not aware about it as I'm contributing here for the first time. I will take care of this in future.

Yes sure , No worries🙌

**Pull request closed without merging**
