### PR TITLE
change heading to - community handbook w/signoff

### PR DESCRIPTION
**Pull request by 5hraddha**
Signed-off-by: Shraddha <mailmeatshraddha@gmail.com>

**Description**

This PR fixes heading: from About to "Community Handbook"

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — COMMENTED** [review]
I think the package-lock.json is not required here for this change. // @warunicorn19

**Comment by warunicorn19** [comment]
@sayantan1413 i don't think it matters. [As mentioned here](https://github.com/layer5io/layer5/pull/2085#issuecomment-899083707)

**Comment by sayantan1413** [comment]
Ahh I see @warunicorn19 there is a gitignore for this file 😅.

**Comment by warunicorn19** [comment]
yup😄.

**Comment by 5hraddha** [comment]
@sayantan1413 Please, let me know if we are good with the changes or is there anything needs to be updated? Thank you.

**Review by warunicorn19 — APPROVED** [review]
Changes look good to me 🎉, thanks @5hraddha

**Comment by leecalcote** [comment]
Thank you, @5hraddha 👍

**Comment by l5io** [comment]
🚀 Preview for commit 4e6db5f38b6b36e700001990171edba6932ae709 at: https://6124f70da75cc720878a1015--layer5ng.netlify.app

**Review by leecalcote — COMMENTED** [review]
Thank you. Could you also have the page title (in the header) updated?

**Comment by 5hraddha** [comment]
> Thank you. Could you also have the page title (in the header) updated?

Sure @leecalcote. I could do that but I need more clarity on exactly where you are looking for a change. Could you please, share a screenshot? That would be helpful. Also, do you want the title to be updated with  "Community Handbook". Am I getting it correct?

**Comment by leecalcote** [comment]
Right, yes: "Community Handbook | Layer5" - the "| Layer5" will be automatically added.

I mean to indicate literally the html page title (`<title>`).

**Comment by 5hraddha** [comment]
> Right, yes: "Community Handbook | Layer5" - the "| Layer5" will be automatically added.
> 
> I mean to indicate literally the html page title (`<title>`).

Got it!! Sure, I will update. Thank you!!

**Comment by warunicorn19** [comment]
@leecalcote you're referring to the SEO title, yes?

**Comment by warunicorn19** [comment]
Any updates @5hraddha ?

**Comment by 5hraddha** [comment]
> Any updates @5hraddha ?

Thanks for your patience @warunicorn19. The SEO Page title has been updated to 'Community Handbook'. Please, have a review and let know if all looks good. Thank you!!

**Comment by Tanuj22** [comment]
@5hraddha can you revert the changes to `package-lock.json` file. (or open a new PR)

**Comment by l5io** [comment]
🚀 Preview for commit 7b9306b9e8c4146570d8a9d6371558946eb10095 at: https://612cb9b65b7167c6ab85da40--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
> @5hraddha can you revert the changes to `package-lock.json` file. (or open a new PR)

@Tanuj22 that is not required as it is in .gitignore, so changes to that won't make any difference.

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
