### PR TITLE
[NG] Footer Refactoring 

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR updates footer with the new design.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Is it complete or WIP?
Two things to add:
- The hover color needs to change
- The Layer5 logo can be shifted a bit towards the left, to be aligned properly with the text.

**Comment by Nikhil-Ladha** [comment]
Looks good, the image is shifted a bit towards the right. But, I think the issue is with the image itself.
Also, any plans for adding hover effects to social icons? Or like different PR or so?

**Comment by Jashpatel1** [comment]
> Looks good, the image is shifted a bit towards the right. But, I think the issue is with the image itself.
> Also, any plans for adding hover effects to social icons? Or like different PR or so?

I will work on the Social Links component and also create the subscribe component in a separate PR.

**Comment by Nikhil-Ladha** [comment]
> I will work on the Social Links component and also create the subscribe component in a separate PR.

Awesome. Just one thing, since now we have the subscribe section in our footer itself, do we really need a seperate component for that anymore?

**Comment by Jashpatel1** [comment]
> > I will work on the Social Links component and also create the subscribe component in a separate PR.
> 
> Awesome. Just one thing, since now we have the subscribe section in our footer itself, do we really need a seperate component for that anymore?

Yaa we can remove that. Views @leecalcote @Tanuj22

**Comment by Jashpatel1** [comment]
> > > I will work on the Social Links component and also create the subscribe component in a separate PR.
> > 
> > 
> > Awesome. Just one thing, since now we have the subscribe section in our footer itself, do we really need a seperate component for that anymore?
> 
> Yaa we can drop the idea of having a component. Views @leecalcote @Tanuj22

**Comment by leecalcote** [comment]
Keep the "subscribe" component. It will see much reuse.

**Comment by Jashpatel1** [comment]
Is this good to go? @leecalcote @Nikhil-Ladha

**Review by Nikhil-Ladha — APPROVED** [review]
Let's go!
Hopefully, that commented code for icons is for future use :thinking:

**Comment by Jashpatel1** [comment]
> Let's go!
> Hopefully, that commented code for icons is for future use 🤔

Yes

**Pull request merged**
