### PR TITLE
Fixed full text for "sign into" call to action not visible in light mode 

### LINKED ISSUE #4931: [UX] Learn - full text for "sign into" call to action not visible in light mode
### Current Behavior

- Link to website: 
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-istio
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-linkerd
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-consul
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-kuma
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-nsm
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-traefik
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-open-service-mesh
https://layer5.io/learn/service-mesh-labs/running-performance-tests
https://layer5.io/learn/service-mesh-labs/traffic-splitting-with-meshery

- [Light mode] Currently when each learning path is opened by clicking on the **arrow in the top right corner**, it reveals the text "Meshery Playground" as text in green color, which does not give much context to the user as to what options/steps they have to navigate the platform further. This only becomes clear if a user turns on dark mode revealing the full action option which states "Sign in to the Meshery Playground (free account) to continue your lab."

#### Screenshots
imageedit_9_6992306970

mesh

### Desired Behavior

Users should be able to see the option to navigate the platform further (before and after color mode is enabled), this enhances user experience as not every user might have the notion to turn on dark mode to reveal the most important call to action/option which is signing up for a free Meshery Playground account to **continue their lab**.

### Screenshots

dmesh

### Implementation

- [Light mode] Consider changing the text color for "Sign in to the Meshery Playground (free account) to continue your lab." to one that is different from its background, so it's visible, in light mode.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VamshiReddy02**
**Description**

This PR fixes #4931

**Notes for Reviewers**
I fixed the full text for the "sign into" call to action not visible in light mode. Please let me know if there are any changes to be made.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 824488eb8a9da2cc6cbc1a9e7b7951f29b4466ee at: https://650d6072af9a10277c07e50a--layer5.netlify.app

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
Hello @VamshiReddy02 ,

When we move our mouse over the link that is in a light green color, it turns black. However, in layer5, all the links that are green in the dark theme becomes white. So, could you please change the way the link behaves when we hover over it?

**link in hover state :** 
image

**Comment by l5io** [comment]
🚀 Preview for commit 4b6acdbf4754c934cf631615072aa3250f16619f at: https://650d83d6bd92d53f52977510--layer5.netlify.app

**Comment by VamshiReddy02** [comment]
Hey @hirentimbadiya, I updated the PR please review it. And let me know if there are any changes to be made.

**Review by hirentimbadiya — APPROVED** [review]
@VamshiReddy02 , looks good to merge now 👍🏻

**Review by leecalcote — APPROVED** [review]
Nice work. 🙂

**Pull request merged**
