### PR TITLE
fixed the date for hacktoberfest

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**

This PR fixes #

image

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8d94f543497f0edd765e86eb4dfe59a497784a5f at: https://6335ee004452383401416142--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks for this. I wonder if this one is still needed...

**Comment by legendarykamal** [comment]
I don't know, Had done it as per the neccesity of the situation :)

**Comment by leecalcote** [comment]
For sure, yes, much appreciated. Rather, the date appears correctly now. I think it must have been updated in another push/pr during the rush to prepare. Thanks for this, though, and your help in organizing today's event.

**Pull request closed without merging**
