### PR TITLE
[NG] Migrated the about page to layer5-ng

### LINKED ISSUE #851: [NG] Migrate the About page to layer5-ng
**Current Behavior**
The current website has an About Us page. The page can be seen [here](https://layer5.io/about).

**Desired Situation**
Migrate the About Us page to layer5-ng.

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Harshita-Kanal**
Signed-off-by: Harshita-Kanal <harshita.kgv@gmail.com>

**Description**

This PR fixes #851 

**Notes for Reviewers**
Migrated the about page

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Harshita-Kanal** [comment]
I have added the about page

**Review by Jashpatel1 — COMMENTED** [review]
All looks good. Thanks @Harshita-Kanal 
Can you add those hover color to contact icons as present in current website if possible?
In the deploy preview, the mail icon shows link to https://deploy-preview-885--layer5ng.netlify.app/mailto:community@layer5.io  . Can you see what the problem is?

**Comment by Harshita-Kanal** [comment]
yes i'll check it out

**Review by Tanuj22 — COMMENTED** [review]
Really awesome work here @Harshita-Kanal :1st_place_medal: . One change I would suggest - There are social media icons in the footer also. So If you would, can you create a separate component out of it and place it in the `components` folder and using that in both the footer and the about us page. You can submit a separate PR for this if you want. Your Call :)

**Comment by Harshita-Kanal** [comment]
> Really awesome work here @Harshita-Kanal  . One change I would suggest - There are social media icons in the footer also. So If you would, can you create a separate component out of it and place it in the `components` folder and using that in both the footer and the about us page. You can submit a separate PR for this if you want. Your Call :)

Sure, I'll submit a separate PR for this :)

**Review by Jashpatel1 — APPROVED** [review]
Nice work here. Thanks @Harshita-Kanal

**Review by Tanuj22 — APPROVED** [review]
Thank You!

**Pull request merged**
