### PR TITLE
Unrelated Inter Page Navigation Removed

### PR DESCRIPTION
**Pull request by dhamkirti21**
**Description**
Added Meaningful Navigation 

This PR fixes ##4968

**Notes for Reviewers**
@Mohith234  @ritiksaxena124  
Please review this PR Now

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4c6fc5508f9fd68887315cb3b02543c7ce269427 at: https://6523bffe83e18d5baafacd6a--layer5.netlify.app

**Comment by vishalvivekm** [comment]
> changes looks good @dhamkirti21 , will you please make transition to inter page navigation smooth, like when we click on any reference and it move to that certain section of page so it should move smoothly not abruptly

@dhamkirti21

**Comment by leecalcote** [comment]
> changes looks good @dhamkirti21 , will you please make transition to inter page navigation smooth, like when we click on any reference and it move to that certain section of page so it should move smoothly not abruptly

This is a good ask, @sudhanshutech. Will you please open a new issue describing this enhancement request?

**Review by leecalcote — APPROVED** [review]
Some good work here, @dhamkirti21 👏

**Comment by leecalcote** [comment]
Yay! 🎈

**Pull request merged**
