### PR TITLE
Adding animations to src/section/Home/Playgrougn-home/index.js

### LINKED ISSUE #5513: [Animation] Add animation to "Manage your Cloud Native mess" section on homepage
### Current Behavior
The integrations shown inside the section are static, There is no animation
image

### Desired Behavior
Add animation such that the integrations integrations at the first column move in a downward direction and integrations in the second column move upward direction infinitely.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by JonathanKoerber**
**Description**

This PR fixes #5513

**Notes for Reviewers**
Added animation using CSS transform. Because the images scroll outside the parent div I had to disable the useInView check.  
layer5-animation

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8b3db1a5130e1178d04da70d1e40987686013b34 at: https://666b623c273aa9ada703b3d6--layer5.netlify.app

**Comment by Deepak0320Singhal** [comment]
@JonathanKoerber Thank you for your contribution.
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
too much of lint changes @JonathanKoerber remove them please. Its become hard to review
and where is styling for animations?

**Comment by iArchitSharma** [comment]
@JonathanKoerber are u still working on this?

**Comment by l5io** [comment]
🚀 Preview for commit e6be463d6990ce8985242f6d8d9c70f47cd68626 at: https://6687e7ad7b536c5712070e8d--layer5.netlify.app

**Comment by JonathanKoerber** [comment]
@sudhanshutech are you meaning the spacing?

**Comment by sudhanshutech** [comment]
> @sudhanshutech are you meaning the spacing?

what is the meaning of linting😅. Unnecessary line changes

**Comment by l5io** [comment]
🚀 Preview for commit 9b218b64846b156e5151a2b9011a9ca496ae35b9 at: https://66922564c9f4c8cbfe474b7d--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@JonathanKoerber this been already fixed , so lets close this for now . Thanks for jumping in this issue though.

**Pull request closed without merging**
