### PR TITLE
Added the space in between the full stop and the next word

### PR DESCRIPTION
**Pull request by csengineer1990**
**Description**
Added the space in between the full stop and the next word

This PR fixes

**Notes for Reviewers**

Meshery spaceissue

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e40be03c2f95b37530ad524b0528690989a59faa at: https://65229f3041955929d0240eb3--layer5.netlify.app

**Review by abhijeetgauravm — CHANGES_REQUESTED** [review]
hey @csengineer1990 seeing a bunch of unnecessary changes instead of only adding the space in between the full stop and the next word.

**Comment by csengineer1990** [comment]
> hey @csengineer1990 seeing a bunch of unnecessary changes instead of only adding the space in between the full stop and the next word.

No sir, I haven't made any unnecessary changes; when I checked it, the prettier feature made unnecessary changes. I have now updated the code.

**Comment by l5io** [comment]
🚀 Preview for commit c44f774c208996682e092476b8e23b0f9ba3f30b at: https://6523fc8ffe875d0dfbeb5a2a--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
