### PR TITLE
fix:support svg image in thumbnail of blogs

### LINKED ISSUE #560: [NG] Support for SVGs as featured images in blog posts
> Whenever an SVG is available, let's choose an SVG over a PNG.  I will provide one that can be used.

There is some predefined properties for blog-grid image. On using a svg image they are failing to work. @Tanuj22 can you tell something about this in case you know.

_Originally posted by @Jashpatel1 in https://github.com/layer5io/layer5/pull/555_

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <tanujagarwal22@gmail.com>

**Description**

This PR fixes #560 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
How has this impacted the support for PNG’s?

**Comment by Nikhil-Ladha** [comment]
I don't think it affects PNG's in any way, as this is a workaround for the svg files. Else, everything will be similar to previous working of the gatsby-image.

**Comment by leecalcote** [comment]
Gotcha. Sounds real good.

**Comment by Nikhil-Ladha** [comment]
> Gotcha. Sounds real good.

Though, if @Tanuj22 could confirm, it will be better. So, that we are good to go with it.

**Comment by Tanuj22** [comment]
> > Gotcha. Sounds real good.
> 
> Though, if @Tanuj22 could confirm, it will be better. So, that we are good to go with it.

Yes. It doesn't impact support for PNGs in any way

**Comment by leecalcote** [comment]
There are some great things that get done with the ImageSharpFluid plugin. Are we removing it entirely in this PR?

**Comment by Nikhil-Ladha** [comment]
No @leecalcote it's not been removed here, instead it has been tweaked a bit support svgs too. I think it has been a issue acknowledged by the gatsby team themselves and they have mentioned this workaround to go with for the time being. Correct me if I am wrong @Tanuj22 .

**Comment by Tanuj22** [comment]
> No @leecalcote it's not been removed here, instead it has been tweaked a bit support svgs too. I think it has been a issue acknowledged by the gatsby team themselves and they have mentioned this workaround to go with for the time being. Correct me if I am wrong @Tanuj22 .

Yes correct. This is what they are saying -  "gatsby-plugin-sharp / gatsby-image doesn't handle SVGs or GIFs. The fluid query (in your case) creates multiple images from 0px to 1060px (+ bigger sizes for retina). That wouldn't make sense with SVGs as they're vector files and don't need different sizes - they can scale indefinitely without loss of quality."

**Comment by leecalcote** [comment]
Thanks for walking me through this, gents. Much of this was fairly obvious from the context that you'd each given previously. Perhaps, it was the filename used (image.js, if I recall) or not knowing if we have a blog template .mdx / set of files that includes example use of both PNG and SVG that left me slightly nervous about it's removal here. 

If we don't have such a sample blog template that uses much of the functionality available (showing examples of use of either SVG or PNG as the feature image and PNG and SVG internal to the post body), will you create an issue to have one?

**Pull request merged**
