### PR TITLE
fixes #1424

### LINKED ISSUE #1424: Implementation of the Making cloud native manageable section on homepage
**Current Behavior**
We currently have no implementation of the Making cloud native manageable section on homepage 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

Checkout the screenshot of design below for easy navigation and identification

making

[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

This PR fixes #1424 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Looks great

**Comment by Nikhil-Ladha** [comment]
It seems incomplete to me, few things are as follows:
 - The image can be hidden at a higher resolution which is around 700px
 - The SVG in the background is missing.
 - The color, font-style, font-weight of the heading `Making cloud native manageable.` is not as per the design.
 - The image top margin can be reduced a bit for smaller resolutions, it takes too much white space o the left.

**Comment by vineethvanga18** [comment]
@vineethvanga18 This PR was incomplete

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha This PR was incomplete

Ohh, I didn't see any such comments so didn't know about that.

**Comment by leecalcote** [comment]
I was in a big hurry here.🤪

Please do open another PR

**Comment by vineethvanga18** [comment]
@leecalcote I couldnt export the svg in the background

**Comment by Nikhil-Ladha** [comment]
> @leecalcote I couldnt export the svg in the background

Did you try moving through the layers using the menu in the left?

**Comment by vineethvanga18** [comment]
@Nikhil-Ladha Got it from other place

**Pull request merged**
