### PR TITLE
Duplicate Meta descriptions fix

### LINKED ISSUE #5109: Duplicate Meta descriptions
### Current Behavior

   The 10 pages have duplicate meta descriptions:
   - 1. https://layer5.io/community/events/hacktoberfest-2022-docker-extensions-show-n-tell
   - 2. https://layer5.io/programs/hacktoberfest
   - 3. https://layer5.io/community/events/kubecon-cloudnative-north-america-2022
   - 4. https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership
   - 5. https://layer5.io/community/events/hacktoberfest-prep-2023-easing-into-cncf-open-source-projects
   - 6. https://layer5.io/community/events/kcd-chennai-2023
   - 7. https://layer5.io/community/events/may-maintainers-circle-2023
   - 8. https://layer5.io/community/events/kubecon-cloudnativecon-eu-amsterdam-2023
   - 9. https://layer5.io/community/events/kubecon-cloudnativecon-north-america-chicago-2023
   - 10. https://layer5.io/community/events/istiocon-virtual-2023

Steps to check : Go to these pages, view the source-code ( CTRL+U) and search for `og:description`

### Desired Situation

The 10 pages should have different meta descriptions.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**
PR adds a unique description to all events pages

This PR fixes #5109 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7fd718710e775ba5503f89eea1fbfe2ca6e675e0 at: https://654fe9a49eb8617894a65d2e--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @iArchitSharma Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by iArchitSharma** [comment]
> Hey @iArchitSharma Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

ya sure!

**Comment by l5io** [comment]
🚀 Preview for commit fa18c429335acc04aa1c08999497380c8f72a633 at: https://6550905f4b848b58b68f77c6--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7b0f5a351417cda4f66ed23f6f14847cc18909f6 at: https://6553171cdc3c12215bdf2e41--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 4da6a153c70e3853a4f2a3c206996b38eea8450c at: https://65546b34f4124d6c8623bbda--layer5.netlify.app

**Review by Mohith234 — APPROVED** [review]
Looks good to me @iArchitSharma. 

Meanwhile, Please add this to the meetings agenda today.

**Comment by iArchitSharma** [comment]
> Looks good to me @iArchitSharma.
> 
> Meanwhile, Please add this to the meetings agenda today.

Wouldn't be able to join today's meeting.

**Comment by l5io** [comment]
🚀 Preview for commit 090116287d67ff5f0aac3850c4962afacea6e51c at: https://655b5a033b89140cb1e543eb--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Thank you, @iArchitSharma

**Pull request merged**
