### PR TITLE
[Site] Fixed Community Handbook Responsiveness

### LINKED ISSUE #2078: [Website] Handbook not mobile responsive
**Description**
The handbook is not is mobile responsive.

**Expected Behavior**
It should be visible in all the views.

**Screenshots**
Screenshot_20210812-115844

**Enviroment:**
- Host OS: MacOs 
- Browser:  Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**
This PR fixes #2078
 
- There were some responsive issues on the Community Handbook page

### Screenshot
129150242-a2e14bad-714b-4616-b133-e33e0bf8f319

## After Changes
Screenshot from 2021-08-12 15-29-24

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d77d09b9a9f602a39ac99a9e6d7c7035bea167db at: https://6114f59edb32edb6dd848dd6--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
> @warunicorn19 I have a doubt. Is it intentional or should I make both of the item centers?
> 
It would be great if you center them😃.

**Comment by NikhilSharma03** [comment]
@warunicorn19 Done. Can you please review?

**Comment by NikhilSharma03** [comment]
@warunicorn19 I was going through the Program page and there's a responsive issue on program/gsod page. Can you please check. If it is, would love to work on it.

**Comment by l5io** [comment]
🚀 Preview for commit 30214f3e4c5e340037178abd45186425950c8c79 at: https://6114f9e7d0cfb49ebbff853a--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
Yes there seems to be a responsiveness issue on the programs page, would you mind fixing it in this PR itself.
All changes till now look great!

**Comment by NikhilSharma03** [comment]
> Yes there seems to be a responsiveness issue on the programs page, would you mind fixing it in this PR itself.
> All changes till now look great!

Yeah Sure.

**Comment by NikhilSharma03** [comment]
## After Changes on GSOD page
- Applied overflow scroll property on smaller devices.

https://user-images.githubusercontent.com/58226527/129189695-ffe9d625-bce0-48b8-9d1c-b2a7ae53e2c9.mp4

**Comment by l5io** [comment]
🚀 Preview for commit 27d97784c92479ebaee1115ead6461e553a8a96a at: https://61150817db32edc927848e74--layer5ng.netlify.app

**Comment by Jashpatel1** [comment]
@NikhilSharma03 The internal pages are not responsive as well. Do you mind adding responsiveness to them as well?

**Comment by warunicorn19** [comment]
@Jashpatel1 I'm working on that

**Comment by NikhilSharma03** [comment]
@warunicorn19 Let me know if there's anything i can help with.

**Comment by warunicorn19** [comment]
@NikhilSharma03 for sure✌️.

**Comment by Tanuj22** [comment]
@warunicorn19 so this should be merged right?

**Comment by warunicorn19** [comment]
@Tanuj22 👍 yup.

**Review by Tanuj22 — APPROVED** [review]
Thanks @NikhilSharma03 @warunicorn19

**Pull request merged**
