### PR TITLE
fixed css for card layout in blog

### LINKED ISSUE #5652: Text alignment and layout issue on blog page
### Description
The text alignment and layout on the blog page do not look good in the mobile view, particularly in the "Tags" section and the blog content cards. This misalignment affects readability and the overall user experience.

### URL
The issue can be observed on the [Layer5 Blog page](https://layer5.io/blog/community/the-mythical-10x-engineer).

### Steps to Reproduce
1. Open the blog page on a mobile device.
2. Observe the text alignment issues in the "Tags" section and the layout of the blog content cards

### Expected Behavior
The text and layout should be properly aligned and formatted for a consistent and visually appealing presentation on mobile devices.
### Screenshots
Screenshot_2024-07-08-17-34-58-082_com android chrome

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShyanRoyChoudhury**
**Description**

This PR fixes #5652 

**Notes for Reviewers**
In this PR I fixed the text alignment and layout issue on blog page.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4bff1d60ef62f94b41a45817c6dc390cd8c5bf61 at: https://66a353cd5db16246a70d0cbf--layer5.netlify.app

**Comment by Ashparshp** [comment]
@ShyanRoyChoudhury Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by l5io** [comment]
🚀 Preview for commit 1ac1c6d87d557ddc3c5951dfa29a0bc82fca529c at: https://66a7825af2394a2fb6bfb804--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b28e269b08780e5d12dd3eff6f0778b466335be7 at: https://66a88842379d18fb88ceb919--layer5.netlify.app

**Comment by Ashparshp** [comment]
@ShyanRoyChoudhury Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by Ashparshp — COMMENTED** [review]
It's a duplicate?

**Comment by ShyanRoyChoudhury** [comment]
Sorry I dont understand. The issue has been fixed before?
@Ashparshp

**Comment by Ashparshp** [comment]
Thanks you @ShyanRoyChoudhury, yes, there is already fixed, so we can close this.

**Pull request closed without merging**
