### PR TITLE
add lighthouse ci workflow

### LINKED ISSUE #3406: [CI] Performance: Configure Lighthouse-CI GitHub Action
#### Current Behavior
The layer5.io site has performance challenges.

#### Desired Behavior
Ideally, the https://github.com/GoogleChrome/lighthouse-ci GitHub Action runs on open of each PR.

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ayushthe1**
Signed-off-by: ayush_gitk <ayushsharmaa101@gmail.com>

**Description**

This PR fixes #3406 

Added lighthouse ci workflow
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ayushthe1** [comment]
hey @eeshaanSA ,can you please review this pr.

**Comment by eeshaanSA** [comment]
@leecalcote @Nikhil-Ladha @Revolyssup

**Comment by leecalcote** [comment]
Workflow run approved. Deploy preview forthcoming.

**Comment by l5io** [comment]
🚀 Preview for commit dfa3cab4354a75154f7469f6ec8132ffdd2a0ad4 at: https://63b5daa7dc7eb3494fd14565--layer5.netlify.app

**Comment by leecalcote** [comment]
@ayushthe1 it looks like we have a list of suggestions to implement. 👍

**Comment by leecalcote** [comment]
@ayushthe1 it'd be nice we were able to knockout the initial set of suggestions before merging this PR. Otherwise, we will immediately have failing build checks on all subsequent PRs. Will you take a crack at addressing the issues described in the output?

**Comment by ayushthe1** [comment]
sure @leecalcote . just to confirm i need to go through all lighthouse audit assertions results which are failing due to low score and fix the corresponding code with the help of link provided in that particular audit report ?

**Comment by leecalcote** [comment]
@ayushthe1, yes. If there are some that you can't figure out, you can open a new GitHub issue for another contributor to pickup.

**Comment by ayushthe1** [comment]
hey @leecalcote ,i can see that the lighthouse ci runs on this file 404.html as below:
```Started a web server on port 43903...
Running Lighthouse 3 time(s) on http://localhost:43903/404.html
Run #1...done.
Run #2...done.
Run #3...done.  
```

Then it reports back the result below as :
``` 
14 result(s) for http://localhost:43903/404.html :

  ✘  button-name failure for minScore assertion
       Buttons do not have an accessible name
       https://web.dev/button-name/

        expected: >=0.9
           found: 0
      all values: 0, 0, 0


  ✘  canonical failure for minScore assertion
       Document does not have a valid `rel=canonical`
       https://web.dev/canonical/

        expected: >=0.9
           found: 0
      all values: 0, 0, 0
```

I need to make changes in the 404.html file to pass the test but i can't find that file .Could you point where the changes need to be made to pass these test.

**Comment by leecalcote** [comment]
@ayushthe1 here you are: `layer5/src/sections/404/index.js`

**Comment by leecalcote** [comment]
@Udit-takkar thoughts?

**Pull request merged**
