### PR TITLE
Added containerssh_white icon

### PR DESCRIPTION
**Pull request by Bhav00**
**Description**

This PR fixes #
This PR adds the white icon and index,mdx for containerssh to `layer5/src/collections/integrations/containerssh/icon/white` folder 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sahilsuman933** [comment]
Could you please sign the DCO, @Bhav00 ?

**Comment by Bhav00** [comment]
> Could you please sign the DCO, @Bhav00 ?

Sorry for the inconvenience. It is done now. Thank you.

**Comment by l5io** [comment]
🚀 Preview for commit 0eb3d3c06464c6c064a82553c3248b365f84b367 at: https://63519e70fff2cc005cd4772b--layer5.netlify.app

**Comment by sahilsuman933** [comment]
You have to update the icon by using `darkModeIntegrationIcon: <Location of your icon>` MDX file present in the `layer5/src/collections/integrations/containerssh`.

**Comment by l5io** [comment]
🚀 Preview for commit 4dc6fe4f208e9210f8951eebb37bc7d12a15f87a at: https://6351a2a80f26920078828f55--layer5.netlify.app

**Review by leecalcote — APPROVED** [review]
Thanks, @Bhav00 👏

**Comment by Bhav00** [comment]
> Thanks, @Bhav00 👏 

Thank you very much.

**Pull request merged**
