### PR TITLE
Added a new member profile

### LINKED ISSUE #2826: [Community] Member Profile: Jerod Culpepper
**Current Behavior**

@cpepper96 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @cpepper96 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: cpepper96
- Twitter: 
- LinkedIn: jerod-culpepper
- Link to profile picture: https://avatars.githubusercontent.com/u/80851353?v=4
- Badge(s): meshery

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by varunwho**
Signed-off-by: Easwaran S <easwaran2806@gmail.com>

**Description**

This PR fixes #2826 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 84bea7b482972d051c136865b5f720ca0ad97dff at: https://628e5abd5f069909c10e9681--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@cpepper96 ready for review...

**Review by leecalcote — APPROVED** [review]
Preview: https://628e5abd5f069909c10e9681--layer5ng.netlify.app/community/members/jerod-culpepper

LGTM, @varunwho 👍

**Comment by cpepper96** [comment]
looks great! thanks @varunwho @leecalcote

**Pull request merged**
