### PR TITLE
aligment fixed

### LINKED ISSUE #5590: The alignment of the pattern picture on the Meshmate page is not accurate.
### Description

The pattern picture with meshmate on the Meshmate page on the Layer5 Community site in not aligned properly.

How to reproduce : Visit this link https://layer5.io/community/meshmates

image
 

### Expected Behavior
The logo should be aligned properly within the green frame.

### Environment:
- Host OS: Linux
- Browser: Chrome, Firefox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #5590 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by narasimha-1511** [comment]
image
Here is the preview after the alignment is fixed

**Comment by l5io** [comment]
🚀 Preview for commit 5082dbaac7dd0abea9d37e80c3f3c118e89290a0 at: https://667e88760c97fb0bae6ea400--layer5.netlify.app

**Comment by iArchitSharma** [comment]
@narasimha-1511 Thank you for your contribution.
Let's discuss this on Websites's call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Review by iArchitSharma — APPROVED** [review]
LGTM thanks @narasimha-1511

**Pull request merged**
