### PR TITLE
#288 multi language support for layer5.io

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>
@leecalcote sir, I have made these changes, if we need something further then I have a plan that is to detect the default browser language of the user and it will automatically translate it.  and I have added this language change section if a user likes to read layer5.io contents in their language.

### CODE REVIEW

**Comment by ashiscs** [comment]
fixes #288

**Comment by leecalcote** [comment]
@gunjanmimo interesting. Yes, I think this could work instead. Can you:

1. ensure all icons retain their aspect ratio, so as to avoid a squishing affect?
1. restyling the svg or png of each flag to be monochromatic (akin to the buttons under the **Contact** section)?

**Comment by gunjanmimo** [comment]
@leecalcote sir, is it correct now?

**Comment by leecalcote** [comment]
Looking good. Let's see how the flags look with only width or height statically specified.

**Pull request merged**
