### PR TITLE
Build: Added 'cache-preserve' flags to optimise build time

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Added flags in the `gatsby.config` file to preserve the cache generated from the previous build to optimize
the time taken during a deploy, or development preview.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Locally I could see a difference of ~60secs for prod build

**Comment by l5io** [comment]
🚀 Preview for commit 84aa66a1d3e1ad9f4a9a9819fcb5bd0229c26a74 at: https://61ef9c63b3854e9d89007121--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Good idea. I wonder what the behaviors are around these caches. I wonder when/if we'll run into weirdness caused by a cache not being busted when it should have been. This wondering doesn't mean that we shouldn't use the caching feature, but that it would be good to understand potential caveats to look out for.

**Review by leecalcote — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
> Good idea. I wonder what the behaviors are around these caches. I wonder when/if we'll run into weirdness caused by a cache not being busted when it should have been. This wondering doesn't mean that we shouldn't use the caching feature, but that it would be good to understand potential caveats to look out for.

Agreed. It actually works keeping that use case in mind, and updates the cache if any data/file/asset has been updated else just skips the re-build of the files.

**Comment by Nikhil-Ladha** [comment]
Merging the PR. If (hopefully we shouldn't) we face any corner issues in future, we can disable/update as per need.

**Pull request merged**
