### PR TITLE
Fixed clearing of blog search bar on changing view from list to grid

### LINKED ISSUE #4148: Clearing of search bar upon changing search result view from list to grid.
### Description
When performing a search on the blog, the search results are displayed in a grid view by default. However, when the user changes the view to list, the search bar is cleared, and any text that was previously entered in the search bar disappears. It would be more intuitive and user-friendly to maintain the searched text even if the user switches between the list and grid view.

Link : https://layer5.io/blog

### Expected Behavior
The searched text should not disappear if you change the view.

### Screenshots
https://user-images.githubusercontent.com/91362589/234633337-f7af795b-5ca5-4b5f-bfec-4e34b67407e5.mp4

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #4148 

[Screencast from 12-06-23 07:17:02 PM IST.webm](https://github.com/layer5io/layer5/assets/92908347/f7dbc8a5-00e9-49a5-b678-ed5b0237af68)

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 08da69d584d5af28040a22e828ab774a54a93af9 at: https://6487251a3cc8363907850774--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Looks Good to me! @AkashS20

**Comment by vishalvivekm** [comment]
@AkashS20 Let's discuss this on websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Thank you, gents.

**Pull request merged**
