### PR TITLE
[Landscape]Replace Maesh Mesh references with Traefik Mesh

### LINKED ISSUE #929: [Landscape] Update Maesh to Traefik Mesh
**Current State:**

Maesh service mesh has officially changed its name to traefikmesh and has a new logo. The name and logo can be sourced from this [PR commit](https://github.com/layer5io/meshery/pull/1659/commits/d15574b91a530790495bd72d89abba6407e27bc6)

**Desired State:**

Update https://layer5.io/meshery page and the https://layer5.io/landscape page with the new logo.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

### PR DESCRIPTION
**Pull request by hexxdump**
Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>

**Description**
Replace the references of Maesh Mesh to Traefik mesh and replace the logos.

This PR fixes #929

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by bartkalanski — APPROVED** [review]
Good job on your first contribution, @hexxdump

**Review by leecalcote — APPROVED** [review]
Very nice, @hexxdump! Thank you. 👍

**Comment by leecalcote** [comment]
Yay, @hexxdump! 🎈 😄

**Comment by PluckyPrecious** [comment]
Yaaay 🥳

**Comment by hexxdump** [comment]
From Meshery site(https://layer5.io/meshery), Maesh reference needs to change from https://github.com/layer5io/meshery-maesh to https://github.com/layer5io/meshery-traefik as well, right ? 
I see meshery-maesh is a  separate git repo and a similar github repo.
May be meshery-traefik github repo needs to be cloned from layer5io/meshery-istio ?

**Comment by PluckyPrecious** [comment]
> From Meshery site(https://layer5.io/meshery), Maesh reference needs to change from https://github.com/layer5io/meshery-maesh to https://github.com/layer5io/meshery-traefik as well, right ?
> I see meshery-maesh is a separate git repo and a similar github repo.
> May be meshery-traefik github repo needs to be cloned from layer5io/meshery-istio ?

> Hey 👋 this is the Layer5 site, meshery site is https://meshery.io/  . I believe you meant to say the meshery page of the Layer5 site? Well yes you’re right that should change too.
> Yes meshery-maesh has a separate repo where you can find all you need to know about maesh now traefik adapter and contribute as well. 
> No there’s no need cloning traefik from istio they’re separate adapters, all that is needed is the repo renamed. Hope the answer is helpful😊 cc// @leecalcote

**Pull request merged**
