### PR TITLE
bring signup confirmation message into view and animate

### LINKED ISSUE #3590: Show a clear successful confirmation message after submitting MeshMap Beta form
**Description**
Upon submission of the signup form on [layer5.io/meshmap](http://layer5.io/meshmap), the page jumps up abruptly and the confirmation message is mostly hidden below the browser’s current view.
image

**Desired Situation**
Bring the browser's view to the existing Signup Confirmation message smoothly or we can word around and show a modal for the confirmation message.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by avikt18**
**Description**
Added a function `scrollElementIntoView()` in the CommonForm component to bring the Thank You message into view after form submission with some CSS animation.

This PR fixes #3590 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by avikt18** [comment]
Hey @Nikhil-Ladha pls check the PR :smile:

**Comment by l5io** [comment]
🚀 Preview for commit f17a8053f13bc900efcec828046f2814bbba3f65 at: https://63bd631ec5c70425c9471c58--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
@Chadha93 do you mind testing in your system as well?
@leecalcote please do a test on Safari, if you would.

**Comment by leecalcote** [comment]
Testing with Safari...

**Comment by leecalcote** [comment]
Performed two tests: one with the submission form low on the browser window and the other with most of the submission form hidden (high in the browser window). In both instances, the focus of the page was gracefully navigated/scrolled to:

Screenshot 2023-01-11 at 11 53 44 AM

**Review by leecalcote — APPROVED** [review]
Good stuff here, @avikt18 👏 

I'm a fan of your use of animation, too. Nice touch.

**Comment by avikt18** [comment]
Yeahhhhhhh!!! Got my first PR merged :partying_face: 
Thanks @leecalcote @Nikhil-Ladha for helping.

**Pull request merged**
