### PR TITLE
[community]initial upload of new contributor profile

### LINKED ISSUE #1944: [Community] Member Profile: Nikhil Sharma
**Current Behavior**

@NikhilSharma03 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @NikhilSharma03 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub : @NikhilSharma03
- LinkedIn : nikhil-sharma-7538961b2
- Twitter : its_nikhil_03
- Profile Picture : https://drive.google.com/file/d/1NMEDZ3EERRMLTG5jyTBUSIQQht1AUFHI/view?=sharing
- About Me :
I'm an undergraduate student at Reva University. I'm well versed in Web development and enjoy exploring new technologies and apply the knowledge in making innovative and interesting projects. I'm passionate about open source, and have learnt a lot through working on a variety of open source projects.
- Location: Rajasthan, India (edited) 

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by josephmidura**
Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR fixes #1944  

**Notes for Reviewers**

https://user-images.githubusercontent.com/11523557/123025992-132f6280-d3a1-11eb-9ce9-744df93e78d8.mov

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f34c578d6f96ceb00b562b47b07b201c7ff9583e at: https://60d29eeddea87843d88572c1--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Ooooh, sweet. A screen recording... nice!

**Comment by NikhilSharma03** [comment]
That's awesome @josephmidura. All social links are correct. Thank you.

**Review by NikhilSharma03 — APPROVED** [review]

**Comment by josephmidura** [comment]
@NikhilSharma03 I'm happy you like it. Congrats 🎉

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
