### PR TITLE
[Sistent] Feat: JSX syntax highlighting on code pages of sistent

### LINKED ISSUE #5534: [Sistent] Code syntax highlighting for sistent components
### Current Behavior

Currently, the code shown for [sistent components](https://layer5.io/projects/sistent/components/button/code), is rendered as plain-text. 

### Desired Behavior
The JSX syntax should be highlighted.

### Screenshots / Mockups

Existing UI:
Screenshot 2024-05-12 at 14 22 07

### Implementation

we can utilize existing libraries for it.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by lakshz**
**Description**

This PR fixes #5534 

### Before
Screenshot 2024-05-12 at 15 20 51

### After
- Light theme
Screenshot 2024-05-12 at 15 21 12

- Dark Theme
Screenshot 2024-05-12 at 15 21 49

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 38b3d7436e946a3e7d636447ae49c01290342994 at: https://66409464683dc4aea8e762ba--layer5.netlify.app

**Comment by ritiksaxena124** [comment]
Hey @lakshz, let's discuss this on today's website meeting at 5:30 PM IST. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please [join](https://meet.layer5.io/websites)[https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

**Comment by sudhanshutech** [comment]
@lakshz can you remove the Sistentthemeprovider wrapped from every component. It should be only mentioned at one place because it is wrapped globally and not on each comps.
It can be mentioned at about or its guidance // @Rexford74 @nebula-aac  your thoughts?

**Comment by leecalcote** [comment]
A merge conflict popped up, @lakshz

**Comment by leecalcote** [comment]
Checking back in. Looks like the merge conflict and response to feedback is needed, @lakshz

**Comment by lakshz** [comment]
When I try to commit after resolving merge conflicts, I see the below error:
Screenshot 2024-06-07 at 13 38 18

Seems like, `eslint` dependency has migrated from using `.eslintrc` files, due to that the pre-commit is failing. 

@leecalcote Should I continue with resolving the eslint issue in this PR?

**Comment by leecalcote** [comment]
@lakshz, PRs generally merge faster the smaller that they are....

**Comment by surajgjadhav** [comment]
> When I try to commit after resolving merge conflicts, I see the below error: Screenshot 2024-06-07 at 13 38 18
> 
> Seems like, `eslint` dependency has migrated from using `.eslintrc` files, due to that the pre-commit is failing.
> 
> @leecalcote Should I continue with resolving the eslint issue in this PR?

HI @lakshz ,
This issue is resolved, 
Could you please take the latest pull and check again?

**Pull request closed without merging**
