### PR TITLE
Added integration icons in homepage animation

### LINKED ISSUE #5899: Increase number of Integration icons in Homepage animation to prevent blank spaces
### Current Behavior

On the homepage (https://layer5.io/), we have an animation of integration icons moving upward in one column and downward in another.
image

### Desired Situation

The number of icons in the columns is not sufficient, resulting in occasional blank spaces. We should continue showing more integration icons.
Note: we have over 320 integrations found in [collections/integrations](https://github.com/layer5io/layer5/tree/master/src/collections/integrations)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Tharanishwaran**
**Description**

This PR fixes #5899

**Notes for Reviewers**
- The number of integration icons in the homepage animation has been increased to minimize empty spaces.

 ### Screenshots
Screenshot from 2024-10-26 00-30-13

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 963b8d69b404e4a230f1605e9ee5b1a17fc04142 at: https://67196b9fbcf328af057d2606--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 22b45eff6e42f19c4631d634c9484adaff35b1b3 at: https://6719b922e5e76e422360f7dd--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]
please avoid using lint changes it makes hard to review

**Comment by Tharanishwaran** [comment]
@sudhanshutech Got it, thanks I will avoid lint changes in future PRs to make reviews easier.
Thanks again for the approval.

**Comment by Tharanishwaran** [comment]
Hi @vishalvivekm could you please review this PR and let me know if any changes are needed for merging? Thanks!

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
Please revert lint change, and adhere to project's eslint conventions

**Comment by leecalcote** [comment]
Thanks, @Tharanishwaran!

**Comment by leecalcote** [comment]
This is a great idea, @Tharanishwaran. No visitor should ever have the sense that Meshery's integrations are limited. Instead, they should have the sense that there are simply too many to list and scroll.

**Comment by Tharanishwaran** [comment]
> Please revert lint change, and adhere to project's eslint conventions

Thanks @vishalvivekm I’ll revert the lint changes to match the project's eslint convention.

**Comment by Tharanishwaran** [comment]
> This is a great idea, @Tharanishwaran. No visitor should ever have the sense that Meshery's integrations are limited. Instead, they should have the sense that there are simply too many to list and scroll.

Thank you, @leecalcote.

**Comment by ritzorama** [comment]
Please don't use the Helm icon or any other that has such a low contrast with the background (at least in dark mode, it does).

**Comment by l5io** [comment]
🚀 Preview for commit 66dc0af4c5b060632fc7071e567408cf9a45455e at: https://671bed2381a5f4be54d48938--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c623ebfbf0ac6f2e5d7c44972a88996194075052 at: https://671bf2ab8a0d53b8887ce3ff--layer5.netlify.app

**Pull request merged**
