### PR TITLE
Created: Learn Page

### LINKED ISSUE #713: [NG] Migrate the site data for the Resources page
**Description**
Currently, the [Resources page](https://layer5ng.netlify.app/learn) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Resources page](https://layer5.io/learn) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes #713 Migrate the site data for the Resources page

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@kishore007k can you attach a screenshot?

**Comment by kishore007k** [comment]
Take a look at the Screenshot
Capture25

**Comment by Tanuj22** [comment]
Decrease the gap between `Books` and `Workshop` section and the path at the top should be `Home > Learn`

**Comment by kishore007k** [comment]
Yeah, I saw that and changed it.

**Comment by kishore007k** [comment]
This seems kind of odd. What do you think? @Tanuj22 
Capture25

**Comment by Tanuj22** [comment]
Yeah this looks odd 😅 . Better would be remove the learn header and just keep the books and workshop header with (no path in both)

**Comment by kishore007k** [comment]
> Yeah this looks odd 😅 . Better would be remove the learn header and just keep the books and workshop header with (no path in both)

But If I remove that It will affect both the Books and Workshops Page since I'm simply importing it here.

**Comment by Tanuj22** [comment]
You can pass a prop from the learn page like `hide_path={true}` from the learn page to books page. And use that path accordingly. I think from something similar is done in the `Career` section

**Comment by kishore007k** [comment]
The space between the Books section and workshops is coming by default. It seems fine to me. Your thoughts?
Capture26

**Comment by Tanuj22** [comment]
Yeah, it looks enough. We can decrease it later on if needed

**Comment by leecalcote** [comment]
Looking good, @kishore007k. Yes, the space between sections is a bit much (can be addressed now or later).

**Comment by kishore007k** [comment]
> Looking good, @kishore007k. Yes, the space between sections is a bit much (can be addressed now or later).

Thank You, @leecalcote. It seems if I decrease the padding it affects other pages too unless I use the prop to change the class accordingly. I think it would be better to leave it as it is for now and once when the page gets populated we can make the changes.

**Comment by Tanuj22** [comment]
> > Looking good, @kishore007k. Yes, the space between sections is a bit much (can be addressed now or later).
> 
> Thank You, @leecalcote. It seems if I decrease the padding it affects other pages too unless I use the prop to change the class accordingly. I think it would be better to leave it as it is for now and once when the page gets populated we can make the changes.

Yeah, you can push the latest changes and we are good to go here :)

**Comment by kishore007k** [comment]
@Tanuj22 could you take a look at the changes and merge them. It seems I can't request for reviewers yet.

**Review by Tanuj22 — APPROVED** [review]
Thanks for working on this @kishore007k :)

**Comment by kishore007k** [comment]
> Thanks for working on this @kishore007k :)

Thanks @Tanuj22

**Pull request merged**
