### PR TITLE
Updated the language of two files. {README.md & CONTRIBUTING.md}

### PR DESCRIPTION
**Pull request by rohan37kumar**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 8aac01dce1b9a4f0347ee0487b424757ef26c18b at: https://653feeabee98850fd9aef42f--layer5.netlify.app

**Comment by sandramsc** [comment]
@rohan37kumar Please remember to indicate which issue this PR closes in the Description section of your PR.

**Comment by saurabh100ni** [comment]
Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) to present it in the Website Meet today at 6:30 pm IST/7:00 am CT

**Comment by sudhanshutech** [comment]
I don't see any valid issue for this and some changes are also not grammatically correct. Thanks for this @rohan37kumar but you can create a issue and point where such mistakes can be corrected

**Pull request closed without merging**
