### PR TITLE
[Home] Service mesh neutral; book styling

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Description**

This PR changes some verbiage and adds a bit of finesse to the book's cover.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 11a3a6d5212068fad86604ee074d942eecb9e955 at: https://62feac018842e6029cf766ef--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Is the skew really needed? 🤔 
I personally feel _no-skew_ looks better 😶

**Comment by leecalcote** [comment]
Well, shoot. Now, I'm of two minds about this.

**Comment by warunicorn19** [comment]
I had the same opinion, just the shadow is better.

**Comment by leecalcote** [comment]
Skew was the problem. I used skew when I meant to use perspective. Have a look-see now. Better?

**Comment by l5io** [comment]
🚀 Preview for commit 361186575c0973938b6631b60e9e06cb83bf1d7d at: https://630e13f75a0cc659c6c28b50--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Much better!
CSS skills on 🔥

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by leecalcote** [comment]
Whew! Ok, good. :)

**Pull request merged**
