### PR TITLE
chore : Added DEVCONF-2022 measuring SMP event

### LINKED ISSUE #2421: [Event] Measuring Service Mesh Performance 101
Please add the following event to layer5.io/events.

**Event:**
- Event Title: Measuring Service Mesh Performance 101
- Event Link: https://sched.co/siKF
- Talk Description: See the event link
- Speaker: [Navendu Pottekkat](https://layer5.io/community/members/navendu-pottekkat)
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**
Added DEVCONF-2022 measuring SMP event

This PR fixes #2421 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
This is related to PR #2425

**Comment by l5io** [comment]
🚀 Preview for commit 59cf258f94bebe92cf2479fec875e5bd56b6d946 at: https://61c84d8e1a10607babb6d662--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Pending @navendu-pottekkat review.

**Comment by leecalcote** [comment]
@navendu-pottekkat look good?

@Abhijay007 please know that this entry needs to be consolidated into a single event listing - https://github.com/layer5io/layer5/pull/2424

**Review by navendu-pottekkat — COMMENTED** [review]
Looks Good. As @leecalcote mentioned, could you consolidate all events for DevConf 2022 in a single page?

You can add the event from [this PR](https://github.com/layer5io/layer5/pull/2424) to your current PR.

**Comment by Abhijay007** [comment]
@navendu-pottekkat @leecalcote I have a doubt, do I need to make a new markdown file in the folder named "devconf-2022-measure-SMP" and that content of [this PR](https://github.com/layer5io/layer5/pull/2424) to it, or do I need to add that content in the same file in order to consolidate those events?

**Comment by navendu-pottekkat** [comment]
The latter. One file/page for DevConf with two events listed. Merge both to a single file.

**Comment by Abhijay007** [comment]
> The latter. One file/page for DevConf with two events listed. Merge both to a single file.

ok, thanks for the confirmation!!

**Comment by Abhijay007** [comment]
@leecalcote @navendu-pottekkat I have doubt that in order to consolidate I need to make two attributes, and add all the three speakers in that one field, right? just like you did for the "Establishing an Open Source Program Office" meetup. 

image

now the question is how can I manage the text for both? can I give the headings that "this (content of measuring-SMP)" content is related to measuring-SMP and "this ( content for Journey Into the World of Service Meshes and Meshery)" is related to the world of service mesh?

am I taking it right or do I need to do something else?

**Comment by leecalcote** [comment]
For now, no new custom attribute. See the KubeCon China 2021 for an example of how to handle this.

**Comment by Abhijay007** [comment]
> For now, no new custom attribute. See the KubeCon China 2021 for an example of how to handle this.

ok thanks

**Comment by l5io** [comment]
🚀 Preview for commit efdefcaf1c3e51d9f59d6ac945be3cf0dd7574ca at: https://61cf253174273b8a6a9a7fad--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Great, @Abhijay007. Will you add an intro sentence or two about finding us at DevConf?

**Comment by Abhijay007** [comment]
> Great, @Abhijay007. Will you add an intro sentence or two about finding us at DevConf?

ya sure, so I need to add those lines above headings right? or in talk-description ?

**Comment by Abhijay007** [comment]
> > Great, @Abhijay007. Will you add an intro sentence or two about finding us at DevConf?
> 
> ya sure, so I need to add those lines above headings right? or in the talk description?

and can you please explain me how someone can find you us at DevConf as I don't have much idea about it 😅

**Comment by Abhijay007** [comment]
> > Great, @Abhijay007. Will you add an intro sentence or two about finding us at DevConf?
> 
> ya sure, so I need to add those lines above headings right? or in the talk description?
> 
> And can you please explain me how someone can find you us at DevConf as I don't have much idea about it 😅

@navendu-pottekkat @leecalcote do I need to add steps to join or something like that ? or how to find our events on DEVCONF 2022 ?

**Comment by leecalcote** [comment]
I'll let @adithyaakrishna @navendu-pottekkat assist here.

**Comment by leecalcote** [comment]
I'm holding out hope that @navendu-pottekkat will chime-in.

**Comment by navendu-pottekkat** [comment]
@Abhijay007 Yes, you can mention that maintainers from Layer5 would be presenting at DevConf and then proceed with what you have for the two events.

**Pull request closed without merging**
