### PR TITLE
Added Callout section for the discussion Forum on the Community Page

### PR DESCRIPTION
**Pull request by iambami**
**Description**

This PR fixes #1925

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e08f0e506f25da373912c7b892ed97529ec7839b at: https://60d614427846877e28ac9b6d--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
The issue number mentioned in the commit-msg is wrong. Please update.
You need to call this component on the community page and update the button at the bottom of the faq page, leading to the discussion forum with a discussion open.
A good item to discuss on Monday's call, @iambami if you are inclined to do so.

**Comment by iambami** [comment]
Okay @Nikhil-Ladha I will discuss it today

**Comment by leecalcote** [comment]
@iambami good stuff. We'll want to identify _where_ to expose this. Do you have suggestions?

**Comment by iambami** [comment]
@leecalcote it's taking the same layout as the call to the community, maybe there could be some sizing?

**Pull request closed without merging**
