### PR TITLE
fix : toc scroll #5594

### LINKED ISSUE #5594: Table of contents not scrollable
### Description

Table of contents not scrollable on https://layer5.io/community/handbook/mentorship-programs

### Expected Behavior

Table of contents should be scrollable on https://layer5.io/community/handbook/mentorship-programs

### Screenshots

image

### Environment:
- Host OS: windows,linux,mac
- Browser:chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by preyanshu**
**Description**

This PR fixes #5594 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
-  Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 43874622870f3f7b7e3703a0d4cc0606e6080a59 at: https://6678583cff107bb11b3e5042--layer5.netlify.app

**Comment by Deepak0320Singhal** [comment]
@preyanshu Thank you for contribution. 
Let's discuss this on Websites's call today 6:30 PM IST. Let's add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by Ashparshp** [comment]
The content is overlapping. Haven't you tested it? Please revisit this issue.

**Comment by preyanshu** [comment]
> The content is overlapping. Haven't you tested it? Please fix this issue.

at which height and widht?

**Comment by preyanshu** [comment]
> The content is overlapping. Haven't you tested it? Please fix this issue.

Hi @Ashparshp,

I have tested it. The issue you see here is from the original Layer5 site. I specifically worked on the navbar scroll issue in this PR. Maybe I should create another issue for the overlapping content and fix it there.
image

**Comment by Ashparshp** [comment]
Layer5

**Comment by Ashparshp** [comment]
Screenshot (8)

Look?

**Comment by Ashparshp** [comment]
None of these are working properly:
- About
- Guidelines
- Roles
- Contribution
- Recognition
- Repository Overview
- Projects
- Writing Program
- UX Contributors
- Learning
- Connect with us
- Code of Conduct
- Security Vulnerabilities
- GitHub Process
- FAQs

Mentorship Programs are working fine. Please check the rest.

**Comment by l5io** [comment]
🚀 Preview for commit bdb6f2c90eb2f6e5d5a0e34e30eca50cd2200640 at: https://66795d76a58cfaadc40137bb--layer5.netlify.app

**Comment by preyanshu** [comment]
> None of these are working properly:
> 
> * About
> * Guidelines
> * Roles
> * Contribution
> * Recognition
> * Repository Overview
> * Projects
> * Writing Program
> * UX Contributors
> * Learning
> * Connect with us
> * Code of Conduct
> * Security Vulnerabilities
> * GitHub Process
> * FAQs
> 
> Mentorship Programs are working fine. Please check the rest.

it should be fine now

**Comment by Ashparshp** [comment]
LGTM!

**Review by iArchitSharma — APPROVED** [review]
thanks @preyanshu

**Pull request merged**
