### PR TITLE
[Community] Acknowledge @warunicorn19 as MeshMate

### LINKED ISSUE #2166: [Community] Member Profile: Acknowledging MeshMate Aditya Chatterjee
**Current Behavior**

Aditya Chatterjee (@warunicorn19) has been invited to the Layer5 MeshMate program. As of today, Sept. 8th, 2021, Aditya is the newest MeshMate to join the existing cohort.

**Desired Situation**
Let's recognize @warunicorn19 as a MeshMate by updating [his profile](https://layer5.io/community/members/aditya-chatterjee) on https://layer5.io/community/members with the MeshMate badge and adding his profile to the /community/meshmates page.

_A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)_

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by CIPHERTron**
Signed-off-by: CIPHERTron <pritish.samal918@gmail.com>

**Description**
Acknowledge @warunicorn19 as MeshMate. Congratulations! 🎉 

This PR fixes #2166 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@warunicorn19 @leecalcote please review it. Thanks!

**Comment by l5io** [comment]
🚀 Preview for commit 8e9acaf94670915ab021a62e7de7ed85a3db527b at: https://613b2618aa9b0793d02a23c3--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, thanks a lot for this @CIPHERTron

**Review by Tanuj22 — APPROVED** [review]
Thanks @CIPHERTron . Congrats @warunicorn19 :partying_face:

**Comment by warunicorn19** [comment]
Thanks @Tanuj22 😅.

**Pull request merged**
