### PR TITLE
Replaced carousel library

### PR DESCRIPTION
**Pull request by OmkarPh**
Signed-off-by: OmkarPh <omkarphansopkar@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by OmkarPh** [comment]
Hi @Jashpatel1 
I realized that react-slick is already in use by component slick.slider.js in reusecore

In the preview, I've shown carousel using both react slick and swiper JS(2nd one)

React slick ( 1st one ) looks better to me.

I tried shifting arrows in Swiper JS outward but it has a overflow hidden property (necessary) which forces to conjest arrows.

**Comment by Jashpatel1** [comment]
> Hi @Jashpatel1
> I realized that react-slick is already in use by component slick.slider.js in reusecore
> 
> In the preview, I've shown carousel using both react slick and swiper JS(2nd one)
> 
> React slick ( 1st one ) looks better to me.
> 
> I tried shifting arrows in Swiper JS outward but it has a overflow hidden property (necessary) which forces to conjest arrows.

@leecalcote @Nikhil-Ladha @Tanuj22 ^^

**Comment by Tanuj22** [comment]
I am not seeing any difference in both of them :sweat_smile:. If you say so we can go with the 1st one. Though the arrows are not looking nice currently. Also, the mobile view needs to be taken care of.

**Comment by OmkarPh** [comment]
I prefer 1st one not because of styling, it can be manipulated as we want (even like 2nd ones)

But in 2nd one the arrows and corner cards are so close and pose problems in wider cards

**Comment by Nikhil-Ladha** [comment]
Okay, so I have a different opinion here. In mobile, the second is better because of the feel/animation while swiping the cards.

>But in 2nd one the arrows and corner cards are so close and pose problems in wider corner cards

I think there should be a way to manipulate that as well, if not directly then you can refer to the class that is being used by inspecting and then add CSS for it. That will work.

**Comment by OmkarPh** [comment]
> But in 2nd one the arrows and corner cards are so close and pose problems in wider corner cards  

There were 2 ways to solve this:

1. Provide a margin for arrows
Coz of this, arrows eventually become invisible partially because of hidden overflow.

2. Reduce size of cards wrapper
 This blog wrapper is overflowed by default in component so modifying its width is useless.

I tried many other things but unsuccessful ☹️

**Comment by leecalcote** [comment]
I agree that the 1st one has a smoother, more desirable swiping animation and that we should try to retain this animation whether the 1st or 2nd one is used.

**Comment by OmkarPh** [comment]
Should i make the arrow of both like second one?
Plain blue or layer5's green

**Comment by Nikhil-Ladha** [comment]
Layer5 green

**Comment by OmkarPh** [comment]
Can you tell me how to view this on mobile within same network ( not available on PC's ip now ) ?
I usually test with dev tools but for proper swipe feeling, wanted to test on my mobile

**Comment by OmkarPh** [comment]
Note - I've used window object for toggling arrows and dots, so reload after changing resolution in dev tools :)

**Review by Jashpatel1 — COMMENTED** [review]
The first one looks good to me.

**Comment by leecalcote** [comment]
Regarding the first implementation, note that the righthand arrow flickers and half hides itself on hover.

**Comment by Nikhil-Ladha** [comment]
I think we would want to use the colors in the following way?
Screenshot from 2020-12-10 11-39-41

**Comment by OmkarPh** [comment]
> I think we would want to use the colors in the following way?

@Tanuj22 @Jashpatel1 @leecalcote ^^

**Comment by Tanuj22** [comment]
> > I think we would want to use the colors in the following way?
> 
> @Tanuj22 @Jashpatel1 @leecalcote ^^

I agree with @Nikhil-Ladha . Rest looks great!. Do remember to take care of the mobile view :)

**Comment by OmkarPh** [comment]
Is current disabled color ok?
image

**Comment by Nikhil-Ladha** [comment]
Not sure if we want to keep the dots or not, is there any way to remove them?
Also, hide the arrow if it's disabled.

**Comment by OmkarPh** [comment]
> Not sure if we want to keep the dots or not, is there any way to remove them?
> Also, hide the arrow if it's disabled.


In mobile view, user would generally prefer a swiping so I disabled arrows there.
Without dots, users might not understand if this is a carousel at all and they can swipe too. So kept dots only for mobile.

**Comment by Nikhil-Ladha** [comment]
> > Not sure if we want to keep the dots or not, is there any way to remove them?
> > Also, hide the arrow if it's disabled.
> 
> In mobile view, user would generally prefer swiping so I disabled arrows there.
> Without dots, users might not understand if this is a carousel at all and they can swipe too. So kept dots only for mobile.

For mobile view, we might keep that. But not for desktop view.
Also, please check the alignment of carousel in mobile view. It's not center aligned.

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks @OmkarPh for this.

**Comment by Tanuj22** [comment]
The mobile view is left ...

**Comment by OmkarPh** [comment]
> The mobile view is left ...

I fixed that, the cards are centred and take up maximum possible space horizontally now.

**Comment by Tanuj22** [comment]
> > The mobile view is left ...
> 
> I fixed that, the cards are centred and take up maximum possible space horizontally now.

Why I am seeing this :thinking: 
Screenshot from 2020-12-11 14-20-45

**Comment by Tanuj22** [comment]
Nevermind it was due to directly switching to mobile from desktop view without reloading :sweat_smile:

**Comment by OmkarPh** [comment]
Also this tablet view is taken care of:
Screenshot_2020-12-11-14-21-28-23

**Comment by OmkarPh** [comment]
> Nevermind it was due to directly switching to mobile from desktop view without reloading

Ya that is a problem due to window obj😅
Do we have anything else that can be used to get innerwidth in gatsby?

**Comment by Tanuj22** [comment]
> > Nevermind it was due to directly switching to mobile from desktop view without reloading
> 
> Ya that is a problem due to window obj
> Do we have anything else that can be used to get innerwidth in gatsby?

Not at the top of my head. Will let you know if I find anything

**Comment by OmkarPh** [comment]
I found this, https://reedbarger.com/how-to-create-a-usewindowsize-react-hook/

**Pull request merged**
