### PR TITLE
[Events] fixed link mismatch bug

### LINKED ISSUE #3399: Link mismatch on Events page
#### Description

Due to pagination, the url changes on moving to older events. Due to this, clicking on the upcoming events from the carousal appends the new event address to this new url, resulting in a 404 error.

https://user-images.githubusercontent.com/85789734/197029228-814b193d-9e37-4147-ae6e-419ca275822b.mov

#### Expected Behavior
The link should direct to that particular event on click.

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Oghene-kevwe**
Signed-off-by: Idise Praise <Idisepraise@gmail.com>

**Description**

This PR fixes #3399 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Oghene-kevwe** [comment]
@utkarsh-pro @legendarykamal  I am done. please review

**Comment by l5io** [comment]
🚀 Preview for commit 6bfbb2b6f887a6ace4921b6fdee4740641bec928 at: https://63b02c9e8592e6170549e9f7--layer5.netlify.app

**Review by legendarykamal — APPROVED** [review]
LGTM 👍

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM  Thanks @Oghene-kevwe 🚀

**Comment by Oghene-kevwe** [comment]
@UtkarshMishra12 @legendarykamal This commit haven't been merged, I hope all is fine

**Comment by Nikhil-Ladha** [comment]
Where exactly do you see this bug @Oghene-kevwe , can you please help me by pointing that out?

**Comment by Oghene-kevwe** [comment]
@Nikhil-Ladha it's on the events page. Clicking on the card events carousel leads to an error 404 page due to pagination

**Comment by Nikhil-Ladha** [comment]
I checked all the links on the page and still can't reproduce the issue. A recording of the same would help.
Or, if anyone else is also able to replicate let me know.

**Comment by Oghene-kevwe** [comment]
@Nikhil-Ladha I tagged you in another section, there's more info on the issue there

**Comment by Nikhil-Ladha** [comment]
Please update the issue number in the PR description. The template is there for a reason 🙂

**Comment by Oghene-kevwe** [comment]
@Nikhil-Ladha have I done it correctly?

**Comment by Nikhil-Ladha** [comment]
Now it's fixed.
The title and the description both updated.

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
