### PR TITLE
fixed margin issue in mobile screen on press-release buttons

### LINKED ISSUE #3813: Coverage and Press release buttons spacing issue in layer5 news on mobile screen
### Description
Coverage and press release buttons need spacing on mobile screen devices 

### Expected Behavior
A horizontal margin should be provided for these buttons when the website is in small screen size

### Screenshots

Screenshot 2023-02-24 at 1 13 41 PM

### Environment:
- Host OS: MacOs
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #3813 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6b7831e33fb383a9b6ab0334863642905dd0fc60 at: https://63ff96ee06ab02160c9d25d4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d9cb354fd8e34cb1a5155ee9da4595e9e2822770 at: https://63ff9eb66b2fa818fe99da7b--layer5.netlify.app

**Comment by ShravaniAK** [comment]
i was told to look on this issue by Lee on slack

**Comment by ShravaniAK** [comment]
Actually the one who has opened the pr had some issue in checks

**Comment by ShravaniAK** [comment]
thats why i created the pr , but no problem , you can close this one

**Pull request closed without merging**
