### PR TITLE
Fix: Blog search bar is cleared when switch to list view 

### LINKED ISSUE #4148: Clearing of search bar upon changing search result view from list to grid.
### Description
When performing a search on the blog, the search results are displayed in a grid view by default. However, when the user changes the view to list, the search bar is cleared, and any text that was previously entered in the search bar disappears. It would be more intuitive and user-friendly to maintain the searched text even if the user switches between the list and grid view.

Link : https://layer5.io/blog

### Expected Behavior
The searched text should not disappear if you change the view.

### Screenshots
https://user-images.githubusercontent.com/91362589/234633337-f7af795b-5ca5-4b5f-bfec-4e34b67407e5.mp4

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by akash1412**
**Description**

This PR fixes #4148

https://user-images.githubusercontent.com/41125658/235231676-5b8db08c-671d-4138-ba28-cf908fe200d8.mov

**Notes 

for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
Please Sign Off your Commits check this out https://github.com/layer5io/layer5/pull/4163/checks?check_run_id=13108649274 and also contributing.md file.

**Comment by l5io** [comment]
🚀 Preview for commit 7fd3db475464d1e91c4aefb8dbc9ce9780655863 at: https://644edf8a847cab177ced1857--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Nice one 👍🏼

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Ok, hold that.
The Categoris, Tags filter broke due to this change because we are not passing these props to the BlogList component from those components. You need to figure out a way for that :/
Check the `src/templates/blog-category-list.js` and `src/templates/blog-tag-list.js` file

**Comment by randychilau** [comment]
Hi @akash1412,

Nice work.

I thought this was an interesting issue, and started researching another feature regarding the blog page. During that research, I also experienced the issue that @Nikhil-Ladha mentioned:
>The Categoris, Tags filter broke due to this change because we are not passing these props to the BlogList component from those components. 

[blog_search_categories.webm](https://github.com/layer5io/layer5/assets/90356410/83dad76b-a247-464c-8658-c8c20c4050ee)

PR Preview:

image

Expected:

image

If you are interested in a couple observations that may help resolve this issue, I left them below.

Good luck on this task, and feel free to ask me any questions.

Cheers.
Randy

---

Observations for Category and Tag Resolution 

<details>
  <summary>Observation #1</summary>
 
If you look at the PR preview with Category/Tag issue, you notice that it says `undefined posts` regardless of which category or tag you click. But you know that it should return a number, for example in the live site, the number is `18` for the `community` category. 

Both the Category and Tag files mentioned by Nikhil pass the following props to the `BlogList` component:

` <BlogList data={data} pageContext={pageContext} />`

So you know that the issue is in the `BlogList` component, and in that code you see how the `data` prop is destructured:

`let { totalCount, nodes } = data.allMdx;`

`totalCount` is the variable that helps determine what number is shown in the `header` variable:

image

if it is saying `undefined`, then the `totalCount` is either not getting destructured from the `data` prop, or something else is happening to the variable. You can use console.log tests to track what is happening to the `totalCount` variable.

</details>

<details>
  <summary>Observation #2</summary>

The BlogList component is much more complicated than the BlogGrid component, why is that?

If you notice, the BlogList component has to be used in two scenarios. First scenario is to display blog items with no specified category or tag. And the second scenario is to display blog items for a specific category or tag.

Where does the number displayed in the header come from in the first scenario? Where does it come from in the second scenario? How can you set up the component to handle both scenarios?

</details>

**Comment by leecalcote** [comment]
merge conflict, @akash1412

**Pull request closed without merging**
