### PR TITLE
Fix workshop card open and close transition

### LINKED ISSUE #1758: Smooth Opening & closing of Workshops Card
**Current Behavior**

Each Workshop Card neither opens smoothly nor does it close.
https://layer5.io/learn/service-mesh-workshops

**Desired Behavior**

Workshop card should open smoothly on clicking ``Read More`` button & close smoothly on clicking ``Read Less`` button.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113560099-17f53d80-9620-11eb-8628-e6b80f9b96b1.mp4

[Optional] **Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Thea10**
Signed-off-by: Cynthia <olucynakin@gmail.com>

**Description**

This PR fixes #1758

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d69d7591bc478f8548c87c489c723018ae240f2a at: https://606b72c3e0659700c203b369--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d69d7591bc478f8548c87c489c723018ae240f2a at: https://606b72bdba940f00a4cb6330--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Whoa, quick work by @Thea10. 😄

**Review by chinmaym07 — COMMENTED** [review]
Hey @Thea10 thankyou for the quick work !! 👍🏻 
Currenlty it is opening smoothly . but closing instantly . Please refer to Cards transition using in this page. It will be helpful if it works like that . 
https://layer5.io/learn/service-mesh-labs

**Comment by Jashpatel1** [comment]
> Hey @Thea10 thankyou for the quick work !! 👍🏻
> Currenlty it is opening smoothly . but closing instantly . Please refer to Cards transition using in this page. It will be helpful if it works like that .
> https://layer5.io/learn/service-mesh-labs

I think the closing transition is smooth as well. But it hides due to auto scroll down. What do you suggest @chinmaym07 ?

**Comment by chinmaym07** [comment]
I think we can go ahead with this .. & yes it does close smoothly .

**Review by Jashpatel1 — APPROVED** [review]
Looks good. We would have to look for an alternative. Till then we can go ahead with this.
@Thea10 please catch up with @chinmaym07 for further updates.

**Pull request merged**
