### PR TITLE
Migrated partners page to layer5-ng

### LINKED ISSUE #709: [NG] Migrate site data for the Partners page
**Description**
Currently, the page dedicated to [Partners](https://layer5ng.netlify.app/contact/partners) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Partners page](https://layer5.io/partners) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ashutosh1401**
Signed-off-by: ashutosh1401 <ashutoshthakur_14@yahoo.com>

**Description**

This PR migrates the partners page in layer5-ng website .
This website is respnsive and fixes #709 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@ashutosh1401 Great work here. But can you give a try for some different and better layout to showcase the data? Please feel free to experiment things out, if possible.

**Comment by leecalcote** [comment]
Oooooh, experimentation! I'll hold my breath for a new design. :)

**Comment by leecalcote** [comment]
@Jashpatel1 are you ok to move forward on this as a first version, knowing that we may come back to revamp it later?

**Comment by leecalcote** [comment]
@ashutosh1401 thanks for jumping in here. 👍

**Review by Jashpatel1 — APPROVED** [review]
Great work here. Thanks @ashutosh1401 . We can move forward with this change and look for some layout revamp in an another PR. @ashutosh1401 If you have something in mind, please let me know

**Pull request merged**
