### PR TITLE
redirection of event link to new tab

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
redirection of event link to a new tab

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
I guess, there is some security issues with using the target attribute directly....please check the details of the test failure and fix it accordingly, so that we can move ahead.

**Comment by Nikhil-Ladha** [comment]
Also, sorry that I didn't check these things in the previous PR but two more changes need to be done
1. The top heading `Events` with the page path is not needed.
2. And, in the cards the `see more` button and the `icon` both perform the same thing, so better to remove the `see more` button in this page.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
^^

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
- Fix warnings about unused imports in line:2
- The `Icon` to redirect the user to a different page should be on the same line as that of date.
- For the meetups, as we don't have a date field simply just remove the icon in that card.
- Change the heading `Events`, `Meetups` to use `<h1>` tags, and remove the margin, increase the padding.

**Comment by vinayaksh42** [comment]
> * Fix warnings about unused imports in line:2
> * The `Icon` to redirect the user to a different page should be on the same line as that of the date.
> * For the meetups, as we don't have a date field simply just remove the icon in that card.
> * Change the heading `Events`, `Meetups` to use `<h1>` tags, and remove the margin, increase the padding.

The meetup card and the event card are utilizing the same card so to remove the date field for the meetup cards would mean to make a separate card component for them. Also in the meetup cards, anything related to dates is not visible

**Comment by Nikhil-Ladha** [comment]
> The meetup card and the event card are utilizing the same card so to remove the date field for the meetup cards would mean to make a separate card component for them. Also in the meetup cards, anything related to dates is not visible

I didn't ask you to remove the date field. Simply, check if the date is there only then show the icon otherwise don't.

**Comment by Nikhil-Ladha** [comment]
Also, while you do so change the top padding to 100px from 80px for the heading.

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @vinayaksh42 👍🏼

**Pull request merged**
