### PR TITLE
typography page content update

### LINKED ISSUE #5528: [Sistent] Page Content Update - Typography: Code
### Current Behavior
The 'Typography' page in the Sistent implementation contains the text tokens that help identify all the defined text intended to be used across Layer5 and its solutions, grouping them as tokens for easy identification. These tokens have been updated recently, however, that change does not yet reflect in the current Sistent implementation.

### Desired Behavior
Update the 'Code' page under typography in Sistent using this [Figma design](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=1720%3A7928&mode=design&t=v09PITdFGPxVhl66-1) as a guide.

### Implementation
Check out the design and then navigate to the corresponding [implemented page](https://layer5.io/projects/sistent/identity/typography/code) on the Layer5 website. Compare both of them and ensure that the implementation matches the design.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #5528

**Notes for Reviewers**
@Rexford74 @Ashparshp I have made the necessary changes, can you have a look at it?

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Rexford74 — APPROVED** [review]
The changes look spot on. And okay to merge. Although I would have liked to see a deployment of what it looks like in your local host to be sure all the necessary content is properly arranged. It will be nice if you could provide that. Other than that, this looks okay from my end.

**Comment by vishalvivekm** [comment]
build previews are failing // @iArchitSharma

**Comment by vishalvivekm** [comment]
Adding this item into meeting minues for Monday's websites call: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by l5io** [comment]
🚀 Preview for commit 9f0ded13c370f70b2efc6d456b354f1176fd9706 at: https://6653d47ea8055ae8231754e4--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
