### PR TITLE
Fixed minor bug in profile

### PR DESCRIPTION
**Pull request by metonymic-smokey**
**Description**
My existing profile wrongly mentioned my location as Chennai. I have corrected that to Bangalore.  

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 117f128ac990fb804e8c863ff1d9fbe4e2b8353f at: https://60cdac4d8fd0a72a6fae3c48--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@metonymic-smokey thanks for the update. Can you please follow the instructions mentioned [here](https://github.com/layer5io/layer5/pull/1939/checks?check_run_id=2864116193), to fix the DCO check?

**Review by Abiola-Farounbi — COMMENTED** [review]
Hi @metonymic-smokey .

One of your checks was not passed, you would have to signoff your commit using this command

`
git commit -m --signoff "commit message"
`

**Comment by metonymic-smokey** [comment]
Thanks!
I usually make changes locally,sign off and then push but since this was a
very minor change, I made it in the browser which is why the lack of sign
off.
I'll fix this when I make the change locally.

**Comment by l5io** [comment]
🚀 Preview for commit 77beef1115addc1e4b0d4c54413577df85db3cf9 at: https://60d00419ebc545e111b6e834--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
