### PR TITLE
improve integration honerycomb structure and effects

### LINKED ISSUE #5311: The Integration Titles Breaks unnecessarily on hover
### Description
Some Titles break to new lines on hover that reducing the responsiveness of the site

### Expected Behavior
The break should be applied to text beforehand and should not break dynamically on hover

### Screenshots

https://github.com/layer5io/layer5/assets/70331875/aca19f1e-5b1f-42f7-869a-67ea8362648f

### Environment:
- Host OS: windows
- Browser: All

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by nikhilkalburgi**
**Description**

I have improved the **:hover** effect performance

This PR fixes #5311 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a3d800a7592ef9bf67e5066348b7ea6338497ff5 at: https://65bd01625795e1996c0d6ed2--layer5.netlify.app

**Comment by Ashparshp** [comment]
Good job, @nikhilkalburgi! The hover effect looks better. Ready to put it in. @saurabh100ni , can you check? Thanks!

**Comment by saurabh100ni** [comment]
LGTM.

**Review by saurabh100ni — APPROVED** [review]

**Review by iArchitSharma — APPROVED** [review]
LGTM, thanks @nikhilkalburgi

**Comment by l5io** [comment]
🚀 Preview for commit 4c5b0671973109fe2cedc39dcb4e9a604a76c36a at: https://65bf60e199ee793cd97e993a--layer5.netlify.app

**Pull request merged**
