### PR TITLE
Rephrase "Community Ladder" title to "Community Journey"

### LINKED ISSUE #2378: [handbook] Rephrase "Community Ladder" title to "Community Journey"
**Current Behavior**

As a Layer5 Contributor, the word "Ladder" communicates a hierarchy to climb up, while  "Journey" interprets better how a Contributor experiences as described in https://layer5.io/community/newcomers

This applies for both:
1. https://layer5.io/community/handbook
Screen Shot 2021-11-26 at 10 54 29

2. https://layer5.io/community/handbook/contributor-ladder
Screen Shot 2021-11-26 at 10 55 13

**Desired Situation**

As a Layer5 Contributor, I want to see "Contributor Journey" in "Contributor Handbook" & Contributor Ladder" pages

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by lpizzinidev**
This PR fixes #2378

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
hey @lpizzinidev looks like you forgot to add a signoff to your commit. You might want to take a look at this https://github.com/layer5io/layer5/pull/2385/checks?check_run_id=4354348879 to signoff now, or if you don't a signoff configured, this might help: https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits


@vedant-kakde the `issue/dco` label commenter seems to have some issue, you might want to take a look.

**Comment by leecalcote** [comment]
That pesky, DCO. 🤕

**Comment by l5io** [comment]
🚀 Preview for commit 0d61c2236e43c51608710b225e29cc6113036542 at: https://61a52dec076a766cf028e38c--layer5ng.netlify.app

**Comment by lpizzinidev** [comment]
@warunicorn19 My bad. Now it should be ok, let me know if other actions are needed.

**Comment by l5io** [comment]
🚀 Preview for commit 25f3ed8c6e7fe574e3d69f87965d768bf8084197 at: https://61a63358116fa71575f8f7e4--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @lpizzinidev

**Pull request merged**
