### PR TITLE
fixed the missing images

### LINKED ISSUE #4303: [Learn] Fix the missing images
**Current State:**
The images are not being displayed at 
https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started
F6579D50-61CC-4487-A3AB-1B0DFAC6436D

**Desired State:**
The images should be displaying at the [page](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started) 
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

### PR DESCRIPTION
**Pull request by shyamtawli**
**Description**

This PR fixes #4303 

**Notes for Reviewers**
I have forgot to sign commits, there is way or should I open a new PR.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
refer this to sign commits [DCO](https://github.com/layer5io/layer5/pull/4338/checks?check_run_id=13998927037)

**Comment by shyamtawli** [comment]
Should I open a new PR?

**Comment by Chadha93** [comment]
> Should I open a new PR?

@shyamtawli The link sahred by @hirentimbadiya has steps mentioned you could follow to fix DCO

**Comment by shyamtawli** [comment]
I have tried above steps you mentioned but some more errors are showing up. I think making a new PR will be good and I will SignOff commits.

**Pull request closed without merging**
