### PR TITLE
[chore] Add Enhanced Integrations

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Tested it. Thank you @theBeginner86 
Just that a comma is missing

current state:
```
components: [
{
"name": "azure-identity"
"colorIcon": "icons/components/azure-identity/icons/color/azure-identity-color.svg"
"whiteIcon": "icons/components/azure-identity/icons/white/azure-identity-white.svg"
"description": ""
},
{
"name": "azure-identity-binding"
"colorIcon": "icons/components/azure-identity-binding/icons/color/azure-identity-binding-color.svg"
"whiteIcon": "icons/components/azure-identity-binding/icons/white/azure-identity-binding-white.svg"
"description": ""
},
{
"name": "azure-pod-identity-exception"
"colorIcon": "icons/components/azure-pod-identity-exception/icons/color/azure-pod-identity-exception-color.svg"
"whiteIcon": "icons/components/azure-pod-identity-exception/icons/white/azure-pod-identity-exception-white.svg"
"description": ""
}]
```
desired state:
```
components: [
{
"name": "azure-assigned-identity",
"colorIcon": "icons/components/azure-assigned-identity/icons/color/azure-assigned-identity-color.svg",
"whiteIcon": "icons/components/azure-assigned-identity/icons/white/azure-assigned-identity-white.svg",
"description": ""
},
{
"name": "azure-identity",
"colorIcon": "icons/components/azure-identity/icons/color/azure-identity-color.svg",
"whiteIcon": "icons/components/azure-identity/icons/white/azure-identity-white.svg",
"description": ""
},
{
"name": "azure-identity-binding",
"colorIcon": "icons/components/azure-identity-binding/icons/color/azure-identity-binding-color.svg",
"whiteIcon": "icons/components/azure-identity-binding/icons/white/azure-identity-binding-white.svg",
"description": "",
},
{
"name": "azure-pod-identity-exception",
"colorIcon": "icons/components/azure-pod-identity-exception/icons/color/azure-pod-identity-exception-color.svg",
"whiteIcon": "icons/components/azure-pod-identity-exception/icons/white/",
"description": ""
}]
```

**Comment by vishalvivekm** [comment]
[will be updating]
I'm adding notes here: 
- value for `howItWorksDetails`  should be enclosed in " " as it previously was. It's multiline and contains, colon, commas, quotes.
-

**Comment by vishalvivekm** [comment]
@theBeginner86, Based on this PR and incorporating [ notes](https://github.com/layer5io/layer5/pull/5288#issuecomment-1896513948): I tried sending a test PR: #5296 and it's successfully building.

Should I now do those changes to this PR?
- Basically enclosing `howItWorksDetails` in quotes helped.

**Comment by leecalcote** [comment]
> @theBeginner86, Based on this PR and incorporating [ notes](https://github.com/layer5io/layer5/pull/5288#issuecomment-1896513948): I tried sending a test PR: #5296 and it's successfully building.
> 
> Should I now do those changes to this PR?
> 
> * Basically enclosing `howItWorksDetails` in quotes helped.

Yes, you can make changes here for testing. Those changes will ultimately need to be propagated into the golang script that generates the pages, though.

**Comment by vishalvivekm** [comment]
> > @theBeginner86, Based on this PR and incorporating [ notes](https://github.com/layer5io/layer5/pull/5288#issuecomment-1896513948): I tried sending a test PR: #5296 and it's successfully building.
> > Should I now do those changes to this PR?
> > 
> > * Basically enclosing `howItWorksDetails` in quotes helped.
> 
> Yes, you can make changes here for testing. Those changes will ultimately need to be propagated into the golang script that generates the pages, though.

done.

**Comment by l5io** [comment]
🚀 Preview for commit 61eb182a8e7fceaa800dafb3b0898b5629046f57 at: https://65aa7b593d2dcb0b582b07d4--layer5.netlify.app

**Pull request merged**
