### PR TITLE
changed the colors for sistent page

### LINKED ISSUE #5527: [Sistent] Page Content Update - Color: Code
### Current Behavior
The 'Color' page in the Sistent implementation contains the color tokens that help identify all the colors intended to be used across Layer5 and its solutions, grouping them as tokens for easy identification. These tokens have been updated recently, however, that change does not yet reflect in the current Sistent implementation.

### Desired Behavior
Update the 'Code' page under color in Sistent using this [Figma design](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=5818%3A18731&mode=design&t=v09PITdFGPxVhl66-1) as a guide.

### Implementation
Check out the design and then navigate to the corresponding [implemented page](https://layer5.io/projects/sistent/identity/color/code) on the Layer5 website. Compare each token in both light and dark mode and ensure that the implementation matches the design.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #5527

**Notes for Reviewers**
Please have a look at the changed colors page. Thanks..

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b2c251dec2569b764334030b98a94d45e2de657c at: https://66434ab1e5cdb708e782e8cb--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@hargunkaur286 
Let's discuss this on Websites's call on Monday. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by psankhe28** [comment]
@hargunkaur286 Can you please add the issue number which you are resolving in this PR?

**Comment by hargunkaur286** [comment]
> @hargunkaur286 Can you please add the issue number that you are resolving in this PR? You can do so, by including fixes # in PR's description above.

I've done it, can you have a look now?

**Review by sudhanshutech — APPROVED** [review]
lgtm

**Pull request merged**
