### PR TITLE
fixed: The logos are not visible in dark mode on page: layer5.io/careers/programs

### LINKED ISSUE #3547: The logos are not visible in dark mode (Need separate Logo for Dark Mode) on page: layer5.io/careers/programs
#### Description

The logos are not visible in dark mode (Need separate Logos for Dark Mode)

#### Page Link:

[Link](https://layer5.io/careers/programs)

#### Screenshots

https://user-images.githubusercontent.com/67385503/209204990-a94cf4c8-8086-426a-9266-eda5901aa03e.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Description**

On page [layer5.io/careers/programs](https://layer5.io/careers/programs) made MLH, SCA, and Layer5 icons dark mode compatible and increased background darkness in light mode, and changed the background color for dark mode of program card

This PR fixes #3547 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey @Nikhil-Ladha I made the changes let me know if the changes are correct

**Comment by l5io** [comment]
🚀 Preview for commit 2b2bd5e9ab69e7a2dadbafb1682afd5f5361350c at: https://63eb7273bf5041154c968f86--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Looking rel good, just one another change could be beneficial and that would be updating a dark theme logo for LFX as well.
Here's the one that you can use.
lf-stacked-white

**Comment by Yashsharma1911** [comment]
Thanks, sure I will do that

**Comment by Yashsharma1911** [comment]
Hey @Nikhil-Ladha  I am little late but here we go let me know again if there is any other changes needed

**Comment by l5io** [comment]
🚀 Preview for commit 737f504fdeb70e9898268898d23b4f5ac96c5f30 at: https://63ed39b2347ea5007b137262--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good.
Good work @Yashsharma1911 🥇

**Pull request merged**
