### PR TITLE
Aligned service mesh homepage logo

### LINKED ISSUE #3763: Service mesh performance home page icon not aligned centered
### Description

The home page of the mesh performance icon is not aligned at centered as others are
image

but the other ones are aligned centered like
image

### Expected Behavior

image

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AkashS20**
**Description**

This PR fixes #3763 

[Video](https://user-images.githubusercontent.com/92908347/230640035-682fbe8e-7f0e-45ae-b844-dbb425d9a7ae.webm)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 405fd3d3d73ef6161c97d7b42e227909b3a110b7 at: https://64304350fd33ef6cb4ae0531--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Looks good to merge.

**Review by Chadha93 — APPROVED** [review]
Smooth, LGTM. Thanks @AkashS20

**Comment by AkashS20** [comment]
@Chadha93 You're welcome! Looking forward to contributing more in the community.

**Pull request merged**
