### PR TITLE
Solved the NewCommers Error

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #
There was a Typo in New Comer form in
This PR fixes https://github.com/layer5io/layer5/issues/4969
**Notes for Reviewers**
This is My first PR

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit fc7986598346c6b11264e0877b6ed59cf7ab89a9 at: https://6516a3c834295b643b4c1be5--layer5.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@narasimha-1511, just a friendly reminder: before you create a pull request, make sure the issue is assigned to you.

**Comment by narasimha-1511** [comment]
> @narasimha-1511, just a friendly reminder: before you create a pull request, make sure the issue is assigned to you.

Sorry for this PR , i am begginer

**Comment by narasimha-1511** [comment]
Hey can someone review this PR , merge or close this??

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
