### PR TITLE
enhancement: improve focus state on links for keyboard users

### LINKED ISSUE #2738: Having focus state on links for keyboard users
**Current Behavior**
It is very difficult for keyboard users to know when a link is focused. Most of the links have no way to know when it's focused.

**Desired Behavior**
There should be a different state for focused links/inputs/buttons.

---
**Screenshots / Mockups**
Current

Screenshot (428)_LI

Desired

Screenshot (429)

**Alternatives**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
**Description**

This PR fixes #2738

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 576456147fd5872779b8abca2a30eb6a88033d96 at: https://62721706539bcf4b4b88f6e1--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Doesn't seem like it is working.
Probably, because of the nested way how the buttons are used.

**Comment by leecalcote** [comment]
Testing with Safari, there seems to be no effect.

What do you think, @Olaleye-Blessing?

**Comment by Olaleye-Blessing** [comment]
I guess I can create another pull request after #2740 has been resolved.

**Comment by leecalcote** [comment]
@Olaleye-Blessing my hunch is that #2740 isn't going to be resolved. Where does that leave us?

**Comment by Olaleye-Blessing** [comment]
It has been assigned to someone else but can I work on it?

**Pull request closed without merging**
