### PR TITLE
Added a common form component and Techstrong interview

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>

**Description**

1. Added TechStrong TV Interview under `resources`
2. Since we were using the same form on 3 different pages, I've created a common component to avoid repetition.
3. Changed instances of images with "Service Mesh Company" tagline.
4. Fixed dark mode error on `/events` page and prevent event template from showing

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
"prevent event template from showing" 😬

**Comment by leecalcote** [comment]
" Since we were using the same form on 3 different pages, I've created a common component to avoid repetition." 👏

**Comment by l5io** [comment]
🚀 Preview for commit 3f5922e0024e5173098aab045374e04387ce7aec at: https://62ec3b4f8e24d638d6d92ac2--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
This is much better!
Nice 👌🏼

**Pull request merged**
