### PR TITLE
Redirecting the Sign-off link in Handbook to appropriate section

### LINKED ISSUE #2914: The link to Sign-off in Community Handbook
**Description**

The link to [**Sign-off**](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) in Community handbook's [Contribution](https://layer5.io/community/handbook/contribution) section redirects to the beginning of CONTRIBUTION.md. 

**Expected Behavior**

The link should lead to *Signing-off on Commits* section of CONTRIBUTION.md page.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Santosh1176**
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

**Description**
Redirects the Sign-off link in the Contribution section of the Handbook to the appropriate section in the CONTIBUTION.md file.

This PR fixes #2914

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Santosh1176 I believe that you'll need to update your formatter/lint settings to leave the double quotes in place. Unless I'm mistaken, we're using double quotes across the site and will leave these in place.

**Comment by l5io** [comment]
🚀 Preview for commit 36da8f860a741419e7333527fbd549c2ad549d3b at: https://62b49d8ec357030094e364c1--layer5.netlify.app

**Comment by Santosh1176** [comment]
> @Santosh1176 I believe that you'll need to update your formatter/lint settings to leave the double quotes in place. Unless I'm mistaken, we're using double quotes across the site and will leave these in place.

Sorry! I had to change the settings for a different project. Should I commit again with the doc saved with double quotes?

**Comment by l5io** [comment]
🚀 Preview for commit f91ac1ae40306079363e1cf2cbb1f0f4593b28e2 at: https://62b5c9ac82b9e0061ec436ac--layer5.netlify.app

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
There are still unwanted/incorrect linting changes. Please revert them.

**Comment by Santosh1176** [comment]
> There are still unwanted/incorrect linting changes. Please revert them.

Could you please check again, hope, I've fixed it this time.

**Comment by l5io** [comment]
🚀 Preview for commit c5415f0f08d76ec2ccdf17826e361ecb8d8792c1 at: https://62b88a3dc02323669ddf4fd2--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
Nope, still the same.

**Comment by Santosh1176** [comment]
@Nikhil-Ladha are these and some more in the page with double-quotes causing the issue?

C9891FD0-A79F-4213-891F-805ED0FE98F2

**Comment by l5io** [comment]
🚀 Preview for commit 7312a3a09761fffb4aa292aad787cae031eeb9e4 at: https://62bd7073fb82536cfef8b857--layer5.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @Santosh1176

**Pull request merged**
