### PR TITLE
Corrected typographic errors

### PR DESCRIPTION
**Pull request by b0id**
**Description**

Several files had typos, so I am submitting corrections. 

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by b0id** [comment]
Working on a virtual terminal from work, I have to edit my gitconfig to submit DCO.  Will append.

**Comment by l5io** [comment]
🚀 Preview for commit 5a76249b610180025997b9e1ae0fc755c76612e2 at: https://63e73ce4c29eb2795f1b8f0d--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 22e371c103580a4db20266ee32c137e9e97aad22 at: https://63e743f717cc777bbcfda1a8--layer5.netlify.app

**Comment by b0id** [comment]
I Git meshed up bad here, closing.

**Pull request closed without merging**
