### PR TITLE
Added a global program navigator in programs page

### LINKED ISSUE #2416: Dropdown enhancement on programs page
**Current Behavior**
Films   TV 13-12-2021 19_50_07 (2)

Most programs pages do not have any record of the previous year's events. This causes the dropdown on each page to only display one item. The purpose of the dropdown isn't quite clear.

**Desired Behavior**
- The dropdown should only be visible on pages where we have past records to navigate to.
- It should be hidden in programs where only one year's information is available.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Ciggzy1312**
Signed-off-by: Deepayan <deepayanmukherjee1312@gmail.com>

**Description**

This PR fixes #2416

**Notes for Reviewers**
Added a global program navigator using which a user can jump across single programs page without having to repeatedly go back to the multi programs page

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Ciggzy1312 build failure. Please have a look and ensure that this code change successfully builds.

**Comment by Ciggzy1312** [comment]
@leecalcote now it's ready to be reviewed

**Comment by l5io** [comment]
🚀 Preview for commit 0b24d06431175d59801c730540ae2f94356cd723 at: https://61d1e9492bc6cb8f8e4e4896--layer5ng.netlify.app

**Review by debo19 — CHANGES_REQUESTED** [review]
dropdown
There are two drop downs visible right now. It should be just one and instead of saying "Select..." the default should be the page it is on.

**Comment by leecalcote** [comment]
@Ciggzy1312 what do you think?

**Comment by Ciggzy1312** [comment]
Me and @debo19 had a discussion about it and I think we need some of your suggestion to be on the same page
How about I bring this up in Monday's website call ?

**Comment by l5io** [comment]
🚀 Preview for commit 3e5f85710159c3ec094db5ead1e14fce2757c787 at: https://61e1b8454a83ab479443ab40--layer5ng.netlify.app

**Review by debo19 — CHANGES_REQUESTED** [review]
Looks good, just some minor changes to look at 🚀

**Comment by warunicorn19** [comment]
@Ciggzy1312 any chance you could squash your commits? 14 commits seem to be a lot.

**Comment by l5io** [comment]
🚀 Preview for commit 2153ab427e3ec0714e6326241086e6185af8dda8 at: https://61e278fbc5b566d8b27d3be5--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3c1ff80722091d297b8d58d258200867e7e1b396 at: https://61e27ed59f4ef3df844f8329--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9478c2dfbb1f6496697e86507c87cc620acf3e52 at: https://61e5705cfe272fc49da3ac31--layer5ng.netlify.app

**Comment by debo19** [comment]
@Ciggzy1312 this PR has too many unnecessary commits. Do you mind opening a new PR with only the required change?

**Comment by leecalcote** [comment]
> @Ciggzy1312 this PR has too many unnecessary commits. Do you mind opening a new PR with only the required change?

(or syncing your fork with `master` on this PR's branch)

**Comment by Nikhil-Ladha** [comment]
Ref: #2513

**Pull request closed without merging**
