### PR TITLE
Add Social Media recognition section

### PR DESCRIPTION
**Pull request by tinniaru3005**
**Description**
- This PR is a follow up on #3724 
- Added a Social Media recognition section on [Recognition page](https://layer5.io/community/handbook/recognition)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e040b6c3e7ab4c9b0e8bcb8638a2a3ffeeab0d5d at: https://63ec05716b07a7232cdc1cc6--layer5.netlify.app

**Comment by leecalcote** [comment]
@Anita-ihuman @utkarsh-pro @Chadha93 @eeshaanSA

**Comment by eeshaanSA** [comment]
Some lines are repetitive. If we are to add this, the sentenced can be framed better.

**Review by Chadha93 — APPROVED** [review]
LGTM @tinniaru3005

**Pull request merged**
