### PR TITLE
[UI] Fixed Text and Image Alignment - Docker Extension Page

### LINKED ISSUE #3112: [UI] Change Text and Image alignment
#### Current Behavior

Currently, for mobile view or small screen view in [docker extension page](https://layer5.io/docker-extension-meshery), the feature section is not properly aligned
#### Desired Behavior

For mobile or small screen view, the image should come first and then the relevant text. (See the large screen view, to know which text is for which image)
#### Screenshots / Mockups

Current
Screenshot from 2022-08-23 19-13-09

Mockup for Desired behavior
Group 2

#### Acceptance Tests

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Jonathan-Foo**
Signed-off-by: Jonathan Foo <jonathan.foozh@gmail.com>

**Description**
Fixed the image alignment to the correct order for docker extension page.

This PR fixes #3112 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jonathan-Foo** [comment]
The final result:

image

**Comment by l5io** [comment]
🚀 Preview for commit dd29ba28fa53d3edb8241fb56b4c679f7bfdbd6e at: https://630780d5074b260584b2d45c--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Looking good!

**Comment by Nikhil-Ladha** [comment]
@subhradwip01 hopefully, you will have a peaceful sleep tonight :p

**Comment by subhradwip01** [comment]
> @subhradwip01 hopefully, you will have a peaceful sleep now :p

Ya ... 😅😂

**Comment by Jonathan-Foo** [comment]
Thank you! :) @Nikhil-Ladha @subhradwip01

**Pull request merged**
