### PR TITLE
ananya gautam profile added to members

### LINKED ISSUE #4725: [Community] Member Profile: Ananya Gautam
**Current Behavior**

@Boombag0607 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Boombag0607 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Boombag0607
- Twitter: [boombagtwt](https://twitter.com/boombagtwt)
- LinkedIn: [ananya-gautam-7342b4201](https://www.linkedin.com/in/ananya-gautam-7342b4201/) 
- Meshery Cloud: [04079145-d65d-4d0f-a40e-533d358bea83 ](https://meshery.layer5.io/user/04079145-d65d-4d0f-a40e-533d358bea83)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by shivankurchavan**
**Description**

This PR fixes #4725

**Notes for Reviewers**
Added Ananya Gautam's profile in members 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e15863fba0e6dd0914f0c5ac6627909a0d99542b at: https://64d8eee69435f81d370b5931--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
hey @shivankurchavan Looks good! Bt use img in .webp format !

**Comment by shivankurchavan** [comment]
@abhijeetgauravm noted

**Comment by Ghat0tkach** [comment]
@shivankurchavan 
Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Review by Boombag0607 — APPROVED** [review]
LGTM!

**Comment by l5io** [comment]
🚀 Preview for commit 7eb8908b8d80e82b48fdcb56c1c7d2ad4622e6d1 at: https://64db5153695b0f49318205f5--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
Looks Good @shivankurchavan !

**Review by VivekBaldha0712 — COMMENTED** [review]
LGTM

**Review by Chadha93 — APPROVED** [review]

**Review by Chadha93 — APPROVED** [review]
@shivankurchavan Please remove `.png ` as only webp is used. I'm merging this for now.

**Pull request merged**
