### PR TITLE
fix: unexpected closing of nav bar

### LINKED ISSUE #725: [NG] Mega Menu Losing Focus
**Description**
The mega menu appears and disappears undesirably. 

**Expected Behavior**
Once the menu appears, it should remain visible so long as the user's mouse is in the same menu area.

**Screenshots**
Untitled

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off-by: Tanuj22 <tanujagarwal22@gmail.com>

**Description**

This PR fixes #725

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Oooh! I'm excited about this one.

**Comment by leecalcote** [comment]
@Tanuj22, I see new commits. Is this ready for review again or should I hold off for the moment?

**Comment by Tanuj22** [comment]
> @Tanuj22, I see new commits. Is this ready for review again or should I hold off for the moment?

Hold off for the moment. There are still some issues to be resolved yet

**Comment by leecalcote** [comment]
@shivaylamba current set of issues with the mega menu - https://youtu.be/DP1LCHVQHdM

**Comment by leecalcote** [comment]
@shivaylamba any luck so far?

**Review by leecalcote — APPROVED** [review]
Quality improvements.

**Pull request merged**
