### PR TITLE
 adding the table

### LINKED ISSUE #5671: [sistent] Add `Data-tables` component in sistent project
### Current Behavior

We use a standard data table everywhere 
Example:
image

### Desired Behavior

Add this component under layer5/project/sistent/component
This component can be found here: https://github.com/layer5io/sistent/blob/master/src/custom/ResponsiveDataTable.tsx

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by NareshBiradar1**
**Description**

This PR fixes #5671 

### Description

This pull request adds a `ResponsiveDataTable` component to the Sistent project. It introduces a table with sample data and columns designed to be responsive and adaptable to different screen sizes.

**Key Changes:**
- **Added Columns and Sample Data:** Defined columns for displaying name, ISO code, population, size, and density of various countries.
- **Component Integration:** Integrated the `ResponsiveDataTable` component into the `SistentComponentsPage`, showcasing how to use it with the provided sample data.
- **Column Visibility Control:** Included a `columnVisibility` object to manage the visibility of columns.
- **Update Function:** Added a placeholder `updateColumns` function to demonstrate how column updates can be handled.

**Components Updated:**
- `SistentComponentsPage`: Added the `ResponsiveDataTable` component and updated the component structure.

**Note:** The `ResponsiveDataTable` component is currently commented out but can be enabled by uncommenting the relevant lines of code.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 39373b5d3c5b135aa9a11c051d2571cabcef0735 at: https://66afc9ed9e097ee72fed7c3b--layer5.netlify.app

**Comment by Ashparshp** [comment]
@NareshBiradar1 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk). The call is scheduled for Monday at 5:30 PM IST.

**Comment by sudhanshutech** [comment]
@NareshBiradar1 why its commented out  ?

**Comment by sudhanshutech** [comment]
@NareshBiradar1 this table is need to be represented as a sistent custom component. It will added here https://layer5.io/projects/sistent/components.

**Comment by sudhanshutech** [comment]
This is not ready to merge now...

**Comment by sudhanshutech** [comment]
@NareshBiradar1 ?

**Comment by Ashparshp** [comment]
@NareshBiradar1, please respond when you get some time.

**Comment by Ashparshp** [comment]
@NareshBiradar1, any luck?

**Comment by Ashparshp** [comment]
@vishalvivekm, as we haven't heard back from @NareshBiradar1 we can close this PR?

**Comment by vishalvivekm** [comment]
> @vishalvivekm, as we haven't heard back from @NareshBiradar1 we can close this PR?

Yes, please make a call for volunteers on next websites call @Ashparshp

**Pull request closed without merging**
