### PR TITLE
Issue/guide

### PR DESCRIPTION
**Pull request by adekanyetomie**
This PR updates the command in the guide to checkout to the layer5-ng branch from the master branch

### CODE REVIEW

**Comment by Tanuj22** [comment]
@adekanyetomie I think you sent a PR by mistake to the master branch

**Comment by Nikhil-Ladha** [comment]
@adekanyetomie you are referring to the wrong branch in this PR. It should be the `layer5-ng` branch and **NOT** the `master` branch.

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good!

**Comment by Nikhil-Ladha** [comment]
Yeaaa @adekanyetomie . Finally!

**Comment by leecalcote** [comment]
Haha! Yay, @adekanyetomie! 🎈

**Pull request merged**
