### PR TITLE
Fixed honeycomb CPU usage issue #3809

### LINKED ISSUE #3809: Optimization of Honeycomb component's animation in integrations page
# Description
While conducting performance test the CPU usage increases to more than 100% in Safari browser especially.

### Expected Behavior
The CPU usage should be in considerable limits.

### Screenshots
Image

### Environment:
- Host OS: MacOS
- Browser: Safari

I am taking up this issue.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by divz-codess**
**Description**
While conducting performance test the CPU usage increases to more than 100% in Safari browser especially therefore this PR  optimizes it.

This PR fixes #3809 
- Optimized Honeycomb component in Safari. 
- Decreased CPU usage from more than 100% to 77%.
- Added will change property to Honeycomb list.

Following Screenshot shows the current CPU utilization in Safari browser upon interacting with honeycomb component.
img

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4513ed59d4a36157b0dd6d93c06aaebe400145b2 at: https://640247882ae93310e73b682c--layer5.netlify.app

**Comment by GaganpreetKaurKalsi** [comment]
**For https://640247882ae93310e73b682c--layer5.netlify.app/cloud-native-management/meshery/integrations**

image


**For https://layer5.io/cloud-native-management/meshery/integrations**

image


Hey @divz-codess, I tried checking the CPU usage. For me the current website shows better performance compared to the preview for this PR. Having will-change isn't making much of a difference.

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
`will-change` is kind of a [risky property](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change). Don't know if we should be going forward with it as there isn't much of a difference on my machine. 

Maybe people with a little low performing machines, will be able to give a better feedback here.

**Comment by Udit-takkar** [comment]
agree with @GaganpreetKaurKalsi . we will have to look for other ways to optimize this.

**Review by Udit-takkar — COMMENTED** [review]
agree with @GaganpreetKaurKalsi . we will have to look for other ways to optimize this.

**Comment by divz-codess** [comment]
@GaganpreetKaurKalsi have you tried recording the performance when we hover over the honeycomb structure?

**Comment by Udit-takkar** [comment]
@divz-codess any update on this ?

**Pull request closed without merging**
