### PR TITLE
Issue/newcomers page

### PR DESCRIPTION
**Pull request by adekanyetomie**
Implemented the approved design to the newcomer's page

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Change the head to 'layer5-ng' branch.

**Comment by Tanuj22** [comment]
@adekanyetomie you have made a PR against the master branch, Can you make it against the `layer5-ng` branch

**Comment by Tanuj22** [comment]
> @adekanyetomie you have made a PR against the master branch, Can you make it against the `layer5-ng` branch

Nevermind :sweat_smile:

**Comment by Tanuj22** [comment]
To trigger a deployment of `layer5-ng` now on netlify can you push a commit here? Probally you can merge the latest changes from `upstream/layer-5ng` to this branch to trigger a deployment. Or open a new PR. Your wish :smile:

**Comment by adekanyetomie** [comment]
> To trigger a deployment of `layer5-ng` now on netlify can you push a commit here? Probally you can merge the latest changes from `upstream/layer-5ng` to this branch to trigger a deployment. Or open a new PR. Your wish 😄

Finally!!!

**Comment by leecalcote** [comment]
@adekanyetomie thank you for this revised page. Will you have another look at the three photos on the page? Each of them have a slightly skewed aspect ratio.

**Comment by leecalcote** [comment]
@adekanyetomie Does this PR include interactivity in the contributor's journey map?

**Comment by leecalcote** [comment]
> @adekanyetomie Does this PR include interactivity in the contributor's journey map?

@Neil-140301 if you have link handy to point to @adekanyetomie, please do.

**Comment by adekanyetomie** [comment]
> > @adekanyetomie Does this PR include interactivity in the contributor's journey map?
> 
> @Neil-140301 if you have link handy to point to @adekanyetomie, please do.

No

> @adekanyetomie Does this PR include interactivity in the contributor's journey map?

No

**Comment by adekanyetomie** [comment]
> @adekanyetomie thank you for this revised page. Will you have another look at the three photos on the page? Each of them have a slightly skewed aspect ratio.

will fix it now

**Comment by Neil-140301** [comment]
> > @adekanyetomie Does this PR include interactivity in the contributor's journey map?
> 
> @Neil-140301 if you have a link handy to point to @adekanyetomie, please do.

I had only created a draft on Figma here's a screenshot @adekanyetomie 
you can find it in section: community of the Figma file
image

**Comment by Tanuj22** [comment]
@adekanyetomie Everything on the page is shifted to the left. Please take a look at that also. Probably can be fixed easily by wrapping the content in the `Container` component 
Screenshot from 2020-12-31 18-24-25

**Comment by leecalcote** [comment]
> > > @adekanyetomie Does this PR include interactivity in the contributor's journey map?
> > 
> > 
> > @Neil-140301 if you have a link handy to point to @adekanyetomie, please do.
> 
> I had only created a draft on Figma here's a screenshot @adekanyetomie
> you can find it in section: community of the Figma file
> image

Good work, @Neil-140301!

**Review by Jashpatel1 — APPROVED** [review]
As Tomi cannot continue, I will be taking it from here. Thanks @adekanyetomie.

**Pull request merged**
