### PR TITLE
Added Kanvas link to dropdown menu

### LINKED ISSUE #5894: add link to Kanvas
### Current Behavior

image

### Desired Behavior

Also add a `Kanvas` link here pointing to https://playground.meshery.io/extension/meshmap?mode=visualize&view=default
### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Tharanishwaran**
**Description**

This PR fixes #5894 by adding a "Kanvas" link to the dropdown menu in the Navigation component.

**Notes for Reviewers**
- The link points to: [Kanvas](https://playground.meshery.io/extension/meshmap?mode=visualize&view=default).
- It uses the `KanvasIcon`.

#### Here’s the screenshot of the dropdown menu with the new Kanvas link: 
Screenshot from 2024-09-25 14-35-06

#### [Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 82e6032587b56962d73ae25613763a63dba362c6 at: https://66f4117f6afcd819f3d685a7--layer5.netlify.app

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@vishalvivekm it seems odd to have two same icons right? // @Tharanishwaran

**Comment by Tharanishwaran** [comment]
@sudhanshutech Thanks for pointing that out! Could you please suggest which icon to use instead?

**Review by Ashparshp — APPROVED** [review]
Thank you @Tharanishwaran,
@sudhanshutech, 
The current icon is indeed for Kanvas, which seems appropriate. If you're suggesting an alternative, could you please propose one for Playground instead? It would help to have a solution along with the suggestion. If not, let's move with the current changes for now, and it would be great if you could help design a suitable icon when possible.

**Comment by Ashparshp** [comment]
@vishalvivekm //

**Pull request merged**
