### PR TITLE
Fixed Alignment Issues with Landscape Page

### LINKED ISSUE #1779: [BUG] Meshery Landscape Page Distorted
**Description**

image
image

**Expected Behavior**

**Screenshots**

**Enviroment:**
- Host OS: Ubuntu 20.04.2 LTS
- Kubernetes Version: 
- Browser: Chrome 89.0.4389.114

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/service-mesh-landscape

Is this only me, or is it a common issue?

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by dhruv0000**
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>

**Description**
Added `justify-content: center` to `Row Wrapper`

This PR fixes #1779

**Notes for Reviewers**.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by dhruv0000** [comment]
@Nikhil-Ladha I checked all the other pages for any distortion due to this PR, and couldn't find any. But it would be great if you can confirm it too. Extra pair of eyes never hurts.

**Comment by Nikhil-Ladha** [comment]
I don't get it, how does adding justify-content fixes that issue 🤔. That seems more like a responsive issue.

**Comment by Nikhil-Ladha** [comment]
Ha e tou tried anything else as well? Or try to see what happens if you remove this CSS and does the issue reappear?

**Comment by Nikhil-Ladha** [comment]
Also, can you sahre the resolution at which this is happening?

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
