### PR TITLE
Transited Kelechi Nwachukwu to Meshmate Emeritus

### LINKED ISSUE #1837: [Community] Transition of Kelechi Nwachukwu to Meshmate Emeritus
**Current Behavior**

@PluckyPrecious has been an amazing contributor and Meshmate. Due to some other engagements, she is graduating to Meshmate Emeritus Status. 

**Desired Situation**

Move @PluckyPrecious profile from the [Meshmate section](https://layer5.io/community/meshmates) to the Meshmate Emeritus section following the same pattern.

[Optional] **Additional context**

Meshmates-Layer5-The-Service-Mesh-Company

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by iamrajiv**
Signed-off-by: Rajiv Ranjan Singh <rajivperfect007@gmail.com>

**Description**
Transited Kelechi Nwachukwu to Meshmate Emeritus

This PR fixes #1837

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iamrajiv** [comment]
@leecalcote Please review.

**Comment by Tanuj22** [comment]
@iamrajiv replace `meshmate: yes` with `emeritus: yes`

**Comment by l5io** [comment]
🚀 Preview for commit f6514a1a5a1bfc1b901375c235c940a335e8f689 at: https://60917658062edf4c8a214594--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2f6f609050c9bda20f4be13d55f4695ef6855499 at: https://60917f95dab3d800c9a3b7ea--layer5ng.netlify.app

**Review by Tanuj22 — APPROVED** [review]
Thank you @iamrajiv

**Pull request merged**
