### PR TITLE
Changed SMP logo in readme

### LINKED ISSUE #3596: Replace SMP logo with it's light version on Layer5's readme
#### Description
Replace SMP logo on Layer5's readme with it's white version(the lettering should be white)
image

#### Page Link:
Find a copy of that version at layer5.io/brand

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Adi-ty**
Signed-off-by: Aditya Singh <92062352+Adi-ty@users.noreply.github.com>

I have changed the SMP logo in the readme 

This PR fixes #3596 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 60f23a5658ed588444180d1a695cb499d3c186f3 at: https://63b9818f594968207bf52ccb--layer5.netlify.app

**Comment by Adi-ty** [comment]
Please review this PR and suggest if you want any

**Comment by Adi-ty** [comment]
@leecalcote @GaganpreetKaurKalsi please review this

**Review by UtkarshMishra12 — CHANGES_REQUESTED** [review]
Dark Mode:
image

Light Mode:
image

It's fine for dark mode but for the light mode the image is not correct please set it according to the theme.

**Comment by Adi-ty** [comment]
@UtkarshMishra12 should I change it back to previous logo as the issue itself asked for the white text logo what should I do?

**Comment by UtkarshMishra12** [comment]
@Adi-ty  You can try to find the solution in this way 👀. Using two different images for both modes.
image

**Comment by Adi-ty** [comment]
ok thankyou @UtkarshMishra12 let me try doing it

**Review by AgniveshChaubey — COMMENTED** [review]
Can you provide the link to the output?

**Comment by Adi-ty** [comment]
In Dark mode 

image

In light mode 

image

Now I hope I have done the desired changes please review it

**Comment by l5io** [comment]
🚀 Preview for commit 0dd8ccb321207884940c8fd537ccffe18658c999 at: https://63b9c9982674445bd4ede917--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM 🚀🥇 Thanks @Adi-ty

**Comment by Adi-ty** [comment]
@AgniveshChaubey waiting for your review

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks good 👍

**Review by leecalcote — APPROVED** [review]
Great job on including light and dark mode versions, @Adi-ty

**Pull request merged**
