### PR TITLE
Add RSS feed plugin

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0731600043424d949dc0d782b1e49d4513542c0b at: https://604bd3f2ba1d7d28a88b181a--layer5ng.netlify.app

**Review by leecalcote — APPROVED** [review]
good to go
Screen Shot 2021-03-12 at 2 55 53 PM
Screen Shot 2021-03-12 at 2 55 22 PM

**Comment by leecalcote** [comment]
You're last update might fix the `[no content]` note in the screenshot.

**Comment by Nikhil-Ladha** [comment]
> Your last update might fix the `[no content]` note in the screenshot.

Most probably, yes.

**Comment by l5io** [comment]
🚀 Preview for commit 3feea5f293c26008cfd30c19d436fad1703bad36 at: https://604bd6a810dbf0234e077620--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Yikes

Screen Shot 2021-03-12 at 3 05 59 PM

**Comment by Nikhil-Ladha** [comment]
I feared this would happen,  found a hack for this. Let's see if that works.

**Comment by l5io** [comment]
🚀 Preview for commit 9d9facbaa1a548b8fb90748fd4f90d5f104f65cf at: https://604c5e1b3849e584d737422e--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cb33a132780ef12c9e7e5ae3f4c6dddfe6d868c8 at: https://604c685a3849e594183742aa--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f70bfc088a9d207fd0641a6a905c0776f6794b67 at: https://604c73e153c698cbc6efee0b--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit faf3f182a52ca07ae6f388c724f49a1ce05d6772 at: https://604c7acd294defabd536b4b0--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit eaa74c7e8a671372ac4a5bc31cc3674809e21914 at: https://604c85a364e222cf4b8ef9ff--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9abfcb7ef2ba5014571940696b9d6072cf3d9634 at: https://604c888f648d6caf0e9ccd74--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 462aa820da2e8fccfa7afdcdefce6a857e78be2b at: https://604ca8a2b50517e6af5b3b4b--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b835dd949849d6dd621e29d4bf68fb415a721064 at: https://604cacef99765afe480fccb9--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 3d501ffee6296118b158c7accc8c3aa3c34303c0 at: https://604cb0e3e81318218a4bbe87--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9250055c05014828de247c37c049b8530799ee80 at: https://604cb61fc49ff7fc4e0e3a51--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d941b77b3d940079e2e2dbf9762dab06e519e265 at: https://604cbb378d3ab1f9f7d39153--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0a94a66d6bae32c77c5ca16f66d144a12c8f7d40 at: https://604cbe5f99765a0ec60fcd64--layer5ng.netlify.app

**Pull request merged**
