### PR TITLE
Fix z-index of stewards section

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
This PR fixes the z-index in the Stewards section of the home page

Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
Believe it not, I have the Cloud Native Leaders bleeding into Proudly Maintaining and Industry Stewards on purpose. Understanding that this is on purpose, wdyt about how this looks?

**Comment by Nikhil-Ladha** [comment]
It is still bleeding into the stewards section. The issue is that when you try to hover on the `See out projects` button in the steward's section that is not working, because the z-index is lesser than 0, and the base/body has a higher z-index.

**Comment by Nikhil-Ladha** [comment]
> Believe it not, I have the Cloud Native Leaders bleeding into Proudly Maintaining and Industry Stewards on purpose. Understanding that this is on purpose, wdyt about how this looks?

Currently, it doesn't bleed into the proud maintainers section

**Comment by Nikhil-Ladha** [comment]
Can we get this merged? Considering the issue being on the homepage itself.

**Review by Tanuj22 — APPROVED** [review]

**Comment by leecalcote** [comment]
Gents, thank you for moving forward here. 👍

**Pull request merged**
