### PR TITLE
Grumpyyash/my changes

### PR DESCRIPTION
**Pull request by Grumpyyash**
**Solve issues #1360 and #1357**

This PR fixes the overlapping text issue on pricing list and events page carousel overlap with button

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for this @Grumpyyash. Note that you'll need to open this PR against the `layer5-ng` branch.

Screen Shot 2021-01-16 at 11 02 20 AM

I'll make this update now...

**Comment by Grumpyyash** [comment]
This PR addresses two issues #1360 and #1357.
The correct fixes are described in the screenshots below
solved
solved-1

**Comment by leecalcote** [comment]
@Grumpyyash, take a moment to edit this PR's description to include the issue that it fixes, if you would. In this way, reviewers will have context for the changes in the PR and the associated issue will auto close when the PR is merged.

**Comment by Grumpyyash** [comment]
Sure, I will

**Comment by Jashpatel1** [comment]
@Grumpyyash Can you please revert the changes in package-lock.json?

**Comment by Grumpyyash** [comment]
@Jashpatel1 I have reverted the package-lock.json back, please review.

**Review by Jashpatel1 — APPROVED** [review]
Great work here. Thanks @Grumpyyash

**Pull request merged**
