### PR TITLE
[ESlint] Clear errors and warnings after running a new npm install without a package-lock.json

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes a number of eslint errors and warnings that appear 
- after the [package-lock.json page gets rewritten](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json)
- then the user attempts to commit local changes (triggering the script `"checklint": "eslint ."`).

image

The errors prevent the ability to commit changes in VSCode (not sure about other IDEs or using command line) indicated by the [husky - pre-commit hook exited with code 1 (error)](https://chat.openai.com/share/b03ed494-8f87-43c6-88a8-81fda2db9f1c).

---

Additional changes:
- package.json for `gatsby-plugin-robots-txt` is because the [latest version 1.8.x currently requires Gatsby v5](https://github.com/mdreizin/gatsby-plugin-robots-txt/issues/692) and is a blocker for doing a `npm install` when there is no `package-lock.json` file, until resolved v1.7.x  is the latest version that works with Gatsby v4

- edit to `src/collections/resources/articles/hpes-adoption-of-meshery-and-meshmap/index.mdx` file 
  - to resolve an unused import causing a console error: `export 'theme' (imported as 'theme') was not found in '../../../../src/theme/app/themeStyles.js' (possible exports: darktheme, default)`
  - to update component name to match imported name

- edit `/learn` page for arrows displaying incorrectly
  before:
  image

  after: 
  image

---

**Notes for Reviewers**

The errors and warnings were legitimate issues that were not detected earlier, however with the latest version of `eslint` installed these errors were recorded. (note: the latest eslint version installed "8.43.0" after a `new install` command without package-lock.json, current [package-lock.json](https://github.com/layer5io/layer5/blob/master/package-lock.json) has eslint version "8.28.0").

Here are the pages and eslint errors that appeared:

`src/components/ConformanceTest-Table/index.js`
`src/components/Landscape-Table/index.js`
`src/components/SMI-Table/index.js`
>error  Missing "key" prop for element in iterator  react/jsx-key

`src/sections/Community/Handbook/security-vulnerabilities.js`
>error  Unknown property 'hrf' found  react/no-unknown-property

`src/sections/Company/Legal/code-of-conduct/index.js`
`src/sections/Company/Legal/privacy/index.js`
`src/sections/Company/Legal/terms-of-service/index.js`
>error  Unknown property 'leftAlign' found  react/no-unknown-property

`src/sections/Learn-Layer5/Courses-List/index.js`
>error  Unknown property 'sm' found  react/no-unknown-property
>error  Unknown property 'lg' found  react/no-unknown-property
>error  Unknown property 'xl' found  react/no-unknown-property

Happy to answer any questions on this.

Cheers,
Randy

---

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 946c612151e078676f5b805f95f0b133175b8fc0 at: https://649243f0fdb81e00837a821e--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2566ab1facdffccbd96f5adce3a47cf6f445ab99 at: https://64ae36f322f2e87fbd00aedf--layer5.netlify.app

**Comment by Nikhil-Ladha** [comment]
@randychilau signal if you would prefer to get this PR merged before the the MDX changes, or the vice versa. I think the other one would be better to have lesses merge conflicts.

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Thanks for taking the time to review this PR.

Please merge this PR first. I am still doing some more documentation and testing regarding the MDX PR.

These warnings/errors appeared when I was working on the MDX PR and thought it should be a separate PR (changes are also in the MDX PR, so there should be no merge conflicts).

Thanks again!

Cheers,
Randy

**Pull request merged**
