### PR TITLE
[Resources]Display only those categories which have at least one post

### LINKED ISSUE #2746: [Resources] Do not display filter categories that have no post
**Current Behavior**

Currently, in the resource filter section, all the categories are listed down. But some of the categories that do not have any posts are also listed down, which is not required.
**Desired Behavior**

Make the category list dynamic such that if a particular category has at least one post then only show it.
---
**Screenshots / Mockups**

https://user-images.githubusercontent.com/88609894/166153703-a2d78451-8077-40f6-bc73-f18dc29d535d.mp4

**Alternatives**

---

<h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by subhradwip01**
Signed-off-by: subhradwip01 <subhradwip01@gmail.com>

**Description**

This PR fixes #2746

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by subhradwip01** [comment]
Output:

Uploading Screencast from 01-05-22 09:03:11 PM IST.mp4…

**Comment by l5io** [comment]
🚀 Preview for commit 13274dd75fa1af63b5ed730876eea82caa7c0ecf at: https://626eaf85ecf3976d39e61ee2--layer5ng.netlify.app

**Comment by subhradwip01** [comment]
Output:
https://user-images.githubusercontent.com/88609894/166154368-fa85100c-aabd-40a7-ada1-621b68c21e39.mp4

**Review by Chadha93 — APPROVED** [review]
Good one, It's a nice update @subhradwip01

**Pull request merged**
