### PR TITLE
performance project page: Added KubeCon EU talk video.

### LINKED ISSUE #719: [SMP] Add KubeCon EU talk to performance project page
**Current Behavior**
KubeCon EU talks are out. [This talk](https://www.youtube.com/watch?v=rgnb0-ntPko&list=PL3A-A6hPO2IOpTbdH89qR-4AE0ON13Zie) needs to be added to the second section of this page - https://layer5.io/projects/service-mesh-performance.

It would be nice if this talk is embedded as a Youtube video on this page  - https://github.com/layer5io/layer5/blob/master/collections/_projects/service-mesh-performance.md. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by abadon7**
**Description**

This PR fixes #719 

**Notes for Reviewers**
There is a lot of "noise" because Prettier tool was applied to them. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Jashpatel1 — COMMENTED** [review]
Thanks for jumping in here, can you please look into the responsiveness of the image?  
image

**Review by leecalcote — APPROVED** [review]
This is great, @abadon7. 👍 Nice work.

**Comment by leecalcote** [comment]
Whoo-hoo, @abadon7! 🎈

**Comment by abadon7** [comment]
> Whoo-hoo, @abadon7! 🎈

Ooh, Thank you. I'm glad to help. :smiley:

**Pull request merged**
