### PR TITLE
[Blog]: New blog post

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

This PR will add Sudeep Batra's post on `Service Mesh (Istio) patterns for Multitenancy` to the Layer5 blog.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@sudeepbatra will you give this a review?

**Comment by sb1975** [comment]
https://www.linkedin.com/in/sudeep-batra/
https://github.com/sb1975
Twitter @sudeepbatra

**Comment by leecalcote** [comment]
Post updated - https://layer5.io/blog/service-mesh-patterns-for-multitenancy

It's so nice to have you here, @sb1975. Thank you for allowing us to be a part of your journey.

**Pull request merged**
