### PR TITLE
[Meshery] Updated Integrations MDX Files

### PR DESCRIPTION
**Pull request by sahilsuman933**
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>

**Description**

- Updated Integrations category

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sahilsuman933** [comment]
Could you please tell me which integrations will go on which category @leecalcote?

**Comment by l5io** [comment]
🚀 Preview for commit 1df8093972a8ed314453d27af76665fcecfec228 at: https://63049215328c314480ef4090--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e0220403b02a2ea870241bc028e431ca12ec67e5 at: https://6304aba527eb165d7503d3e9--layer5.netlify.app

**Comment by leecalcote** [comment]
@asubedy will you take a look at the Safari-specific issue, please?

**Comment by l5io** [comment]
🚀 Preview for commit d43538bb62b96f969f404941c82332fadbcd5ca2 at: https://630d4382b1b09739f57b6889--layer5.netlify.app

**Pull request merged**
