### PR TITLE
Center_Component

### LINKED ISSUE #5775: Components is not center for larger screen
### Description
On this [link](https://layer5.io/projects/sistent/components) the component section is not centered on larger screens, although it is centered on normal screens.

### Expected Behavior
The component section should be centered on all screen sizes.

### Screenshots
image

### Addtional Information
If you find this issue valid, I would like to fix it.

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Sushant9473**
_**Description**_

This PR fixes #5775 

_**Notes for Reviewers**_

View the change [here](https://66ae49db64f3fca67c3776ac--layer5.netlify.app/projects/sistent/components)

Centered the components for larger screen .
Screenshot 2024-08-03 at 8 04 03 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Sushant9473** [comment]
@Ashparshp Can you please review this PR.

**Comment by l5io** [comment]
🚀 Preview for commit dc49e0626991ff4e0e6ede1ea5e6dc023419aceb at: https://66ae49db64f3fca67c3776ac--layer5.netlify.app

**Comment by Ashparshp** [comment]
@Sushant9473 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by narasimha-1511** [comment]
LGTM !

**Review by narasimha-1511 — COMMENTED** [review]
It Looks good to me , Hey @hargunkaur286 once have a look at this!

**Review by hargunkaur286 — APPROVED** [review]

**Comment by sudhanshutech** [comment]
@Sushant9473 joining today's call? Are you in layer5 slack?

**Comment by Sushant9473** [comment]
> @Sushant9473 joining today's call? Are you in layer5 slack?

sorry i forgot to attend it .

**Review by Ashparshp — APPROVED** [review]
Thank you, @Sushant9473! LGTM!

**Pull request merged**
