### PR TITLE
[NG] uniform size for partner logos 

### PR DESCRIPTION
**Pull request by vineethvanga18**
**Description**

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@vineethvanga18 Is this complete?

**Comment by vineethvanga18** [comment]
Yes. According to me.
@leecalcote has the final say

**Comment by leecalcote** [comment]
@vineethvanga18 a small request - not critical, but please consider the following format for branch names:

`<username>/[name of feature or bugfix or area]/<issue number, if a bugfix>`?

The `#` in branch names gives either my cli or my brain grief.

**Review by leecalcote — APPROVED** [review]
Logos look good. thank you, @vineethvanga18 

We're in need of having the partners alternate and the expander from @shubhank-saxena

**Comment by vineethvanga18** [comment]
I realised I didn't switch to a new branch after making this PR😶

**Pull request merged**
