### PR TITLE
Feature tag fixed in Events page

### LINKED ISSUE #5521: [Events] Feature tag not working as expected
### Current Behavior
If the frontmatter of the `index.mdx` file of an event contains a tag `featured: false`, the event should not feature on the events page but the event is still featured.  [[Refer to this event](https://github.com/layer5io/layer5/blob/e4bb69a314e7b14e41ab8e14bb9eb360f4fddf39/src/collections/events/making-the-cncf-landscape-interactive-with-meshery/index.mdx?plain=1#L11)] code for reference.

### Desired Behavior
If any event has `featured: false` in frontmatter, the event should not be featured.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Aryakoste**
**Description**

This PR fixes #5521 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [*] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Thank you for your contribution @Aryakoste ,
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by l5io** [comment]
🚀 Preview for commit 215a1f1adfb4df7da9b24bae57cda91ea6f0d7d6 at: https://6653d497a8055ae8231754f2--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@iArchitSharma

**Review by iArchitSharma — APPROVED** [review]
Thanks! @Aryakoste

**Pull request merged**
