### PR TITLE
Add Member

### LINKED ISSUE #4556: [Community] Member Profile: Harsh Dobariya
**Current Behavior**

@HarshDobariya79 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @HarshDobariya79  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @HarshDobariya79
- Twitter: HarshDobariya79
- LinkedIn: harshdobariya79
- Meshery Cloud: 27ba20ed-4012-490e-ab2e-a937173283c4
- Link to profile picture: https://drive.google.com/file/d/1Mru2IfCGvXQ0sMV2u0XTN7DGQVMWFRK_/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by devarsh10**
**Description**
Signed-off-by: devarsh10 <devarshshah2608@gmail.com>
This PR fixes #4556

**Notes for Reviewers**
Add @[HarshDobariya47](https://github.com/HarshDobariya79) as a Member.

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit de109cc9cc1ca01a93e5ff36f03ca78356f5409a at: https://64b623d8374e6d28373d9926--layer5.netlify.app

**Review by HetviSoni — APPROVED** [review]
LGTM

**Review by samyakshah3008 — COMMENTED** [review]
Looks good, nice work @devarsh10 
But can you please change the title of the PR? It is not relevant to what issue you are working on.

**Comment by samyakshah3008** [comment]
@HarshDobariya79 can you review this so we can call for the final checks to get this PR merged?

**Review by HarshDobariya79 — APPROVED** [review]
Thank you @devarsh10 for the PR. Nice work.

**Comment by devarsh10** [comment]
> Thank you @devarsh10 for the PR. Nice work.

My pleasure Harsh.

**Comment by l5io** [comment]
🚀 Preview for commit 177fa984d112e7b066dd0cbe14cd1f231d3f13a8 at: https://64b7e42106e65a1272e006c7--layer5.netlify.app

**Review by vishalvivekm — APPROVED** [review]
### Yay! :balloon: [Harsh](https://github.com/HarshDobariya79) :guitar: 

Thank you @devarsh10 :sunglasses:

**Review by Chadha93 — APPROVED** [review]
Let's go. :rocket:

**Pull request merged**
