### PR TITLE
[Community] Member Status Update

### PR DESCRIPTION
**Pull request by hamza-mohd**
**Description**

This PR adjusts the active status for one of the community members to accurately reflect inactivity.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit 9267d906e18427c1daf32e7caecd803e3f4e7c05 at: https://6585c15956d734f269d1a1cb--layer5.netlify.app

**Comment by leecalcote** [comment]
@abhijeetgauravm merge at-will.

**Review by abhijeetgauravm — APPROVED** [review]
LGTM!

**Pull request merged**
