### PR TITLE
Jome #1040

### LINKED ISSUE #1040: [NG] Remove .vscode folder
**Current Behavior**

.vscode folder is used for local IDE config, it is something to be pushed upstream.
**Desired Situation**

Remove .vscode folder
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by jomefavourite**
**Description**
Removed .vscode folder

This PR fixes #1040 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@jomefavourite DCO is failing

**Comment by jomefavourite** [comment]
> @jomefavourite DCO is failing 

But I signed off this time

**Comment by tripathyprateek** [comment]
@jomefavourite rum these 2 commands to pass DCO https://github.com/layer5io/layer5/pull/1052/checks?check_run_id=1336073982

**Comment by jomefavourite** [comment]
new PR at https://github.com/layer5io/layer5/pull/1083

**Comment by leecalcote** [comment]
@jomefavourite when you're ready, you may want to close this PR.

**Pull request closed without merging**
