### PR TITLE
[News] Meshery a new member of CNCF family.

### LINKED ISSUE #428: [News] Meshery listed in CNCF Landscape
Meshery is now listed in the CNCF Landscape. A new [News article](https://layer5.io/news) should be created to highlight this milestone.

**Article:**
- Title: Meshery accepted into CNCF Landscape
- Link: https://landscape.cncf.io/category=service-mesh&format=card-mode&grouping=category&selected=meshery

**Contributor Resources**
- [Instructions for updating news items](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#news)

---

**Screenshot**

Meshery in CNCF Landscape

### PR DESCRIPTION
**Pull request by NupurThakur27**
Fixes #428

### CODE REVIEW

**Comment by NupurThakur27** [comment]
@leecalcote, I am sorry for updating such a great news so late but here it is have a look.

**Comment by leecalcote** [comment]
@NupurThakur27 thank you for this. As a quick update, would you mind swapping in this logo? https://github.com/cncf/artwork/blob/master/other/cncf-landscape/stacked/color/cncf-landscape-stacked-color.svg

**Comment by NupurThakur27** [comment]
> @NupurThakur27 thank you for this. As a quick update, would you mind swapping in this logo? https://github.com/cncf/artwork/blob/master/other/cncf-landscape/stacked/color/cncf-landscape-stacked-color.svg

@leecalcote Sir, I am not able to download the .svg format so can I use the URL of the image?

**Comment by leecalcote** [comment]
@NupurThakur27 you bet. Here we are - https://raw.githubusercontent.com/cncf/artwork/master/other/cncf-landscape/stacked/color/cncf-landscape-stacked-color.svg

**Comment by NupurThakur27** [comment]
@leecalcote Sir, I made the change have a look.

**Pull request merged**
