### PR TITLE
Change code block text from 'Copy' to 'Copied!' when user copy the code

### PR DESCRIPTION
**Pull request by arsen1c**
**Description**

This PR fixes #
#1753

**Notes for Reviewers**
Now the text in the code block changes from **Copy** to **Copied!** whenever a user copy the code from the code block.

https://user-images.githubusercontent.com/46086050/113521223-b5ffee00-95b5-11eb-8464-b92ed679f582.mp4

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a8c6682d9619d5351e067a1e288286cdc8b7c758 at: https://606a3238593270963881331f--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit a8c6682d9619d5351e067a1e288286cdc8b7c758 at: https://606a32665c2ee1aac571ecea--layer5ng.netlify.app

**Comment by arsen1c** [comment]
Hey @chinmaym07 have a look at this and let me know if that's fine or not.

**Comment by Nikhil-Ladha** [comment]
@arsen1c reduce the time to 1000, that would be enough.

**Comment by arsen1c** [comment]
@Nikhil-Ladha Okay :)

**Comment by l5io** [comment]
🚀 Preview for commit 84358f6315f012aab1df7caad7990dfc8eba8a08 at: https://606abbda1c37acb522cc732e--layer5ng.netlify.app

**Comment by arsen1c** [comment]
Hey @Nikhil-Ladha I think it's done, have a look

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good!

**Pull request merged**
