### PR TITLE
Chore[Site Performance] : Home page Image optimization

### LINKED ISSUE #2172: [Site Speed] Currently a 40% rating
**Current Behavior**
https://layer5.io isn't nearly as fast loading as it could be. See the recommendations on this report - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flayer5.io%2F

**Desired Situation**
Take each recommendation one at-a-time, implementing suggestions to improve page speed. These individual speed enhancements can be broken into separate issues or all tracked against this same epic issue.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Replaced   to <StaticImages/> for improving image optimization and site performance, and also moved images to the respected folders in order to achieve the same.

This PR fixes #2172

**Notes for Reviewers**

Multiple PR to be opened related to site performance, so don't close the issue with this PR associated with, for now !!

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ad8ac362d31067f494e0fa47dfe60d8dfbe630fa at: https://61edded30c553c84218142c3--layer5ng.netlify.app

**Comment by Abhijay007** [comment]
Note: I am also working on replacing `partners` images on the same page with ` static image`,  the reason why I didn't include that in this PR is the `gatsby-plugin-image` doesn't allow us to pass images props like this for ex: `src = {partners.imagelink}` in short it doesn't support props chaining/drilling so I am figuring out a way by which I can able to pass those images form `partners-home-data.js` to the home page in `StaticImage` format.

**Comment by Nikhil-Ladha** [comment]
Correct.
So, use a similar approach i.e, save the path value in a variable and then pass that variable to the src attribute.

**Comment by Abhijay007** [comment]
Closing this PR for now, due to merge conflicts in local env which, will open a new PR soon !!

**Pull request closed without merging**
