### PR TITLE
Fix Catalog link

### LINKED ISSUE #4283: Link catalog icon to catalog page
### Description

Link the Catalog icon in project page to catalog page. Right now it is link to the same page.

### Expected Behavior

Link to [catalog](https://layer5.io/catalog) page.

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by goldfishdolphin**
**Description**

This PR fixes #4283 

**Notes for Reviewers**
I have rectified the link for the recently added catalog project on the projects grid.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — APPROVED** [review]
Yay @goldfishdolphin :zap:

**Comment by Chadha93** [comment]
@goldfishdolphin Will you also toss the link to the main page card for the catalog?
image

**Comment by Chadha93** [comment]
Currently it's directing to landscape.

**Comment by goldfishdolphin** [comment]
> Currently it's directing to landscape.

sure I ll fix it.

**Comment by l5io** [comment]
🚀 Preview for commit a62acac4a72b4d672200d07ec18b424e9fab0e3d at: https://646e4fe62be5f200798c32ad--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
@Chadha93 I have fixed the Catalog link on home page as well.

**Comment by l5io** [comment]
🚀 Preview for commit 15d8bf5b05826580dd7169d37d76f2852f0eeb89 at: https://646e56cdadf0ce0717b182f6--layer5.netlify.app

**Pull request merged**
