### PR TITLE
Refactored MeshmapPage component to improve readability and performance

### PR DESCRIPTION
**Pull request by AbhisekOmkar**
- Simplified destructuring of location object
- Removed unused variables and imports
- Fixed linting warnings
- Updated comments for clarity
Signed-off-by: Author Name abhisekprasad8@gmail.com

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4c2167af6a969e87977c2ae07c290bbe6f99a0eb at: https://66091b83773f528eec5ea2f6--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thank you @AbhisekOmkar for this.
I don't see a corresponding issue open for which, this pull request is a proposed fix.
I understand that you may not have had the chance to go through the [contributing guidelines](https://layer5.io/community/handbook/contribution#:~:text=Contributor%20Guidance%3A) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). 
Please go through these documents and always first open issue, ask for assignment, and once assigned, proceed with raising a fix. I hope you'll keep them in mind for future contributions.
Also, this PR is missing the [DCO](https://github.com/layer5io/layer5/pull/5470#issuecomment-2028864957).

**Comment by vishalvivekm** [comment]
Also, We've our weekly websites meeting tomorrow. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would like to discuss the changes made.

**Comment by dragon-slayer875** [comment]
Hello @AbhisekOmkar. It seems that your commit is not signed.
To pass the DCO check, you need to sign your commit. 
You can find more information about signing  commits [here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).

**Comment by leecalcote** [comment]
Thank you, @AbhisekOmkar 👍

**Review by iArchitSharma — APPROVED** [review]
@AbhisekOmkar Thank you

**Pull request merged**
