### PR TITLE
Much spaces between contribution and General contribution flow

### PR DESCRIPTION
**Pull request by sarkartanmay393**
**Description**

Issue: #4636

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d0f3c874d78ea0c412f275afb42a80f2f1537a69 at: https://64c77fcf6d214d0b2bbe1fab--layer5.netlify.app

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393, I'd like to give advise: please refrain from creating a pull request until the respective issue has been assigned to you.

I haven't seen any activity for the last 2 days, that's why. Sure I will keep in mind.

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
We probably dont need these many lines of code for this issue , 
Could you please discard the unnecessary changes?

**Comment by sarkartanmay393** [comment]
> We probably dont need these many lines of code for this issue , Could you please discard the unnecessary changes?

Should I revert changes back to the previous in `faq.js` and `security-vulnerabilities`?

**Comment by Ghat0tkach** [comment]
@sarkartanmay393 I'm asking about the extra spaces on unrelated sections

**Comment by l5io** [comment]
🚀 Preview for commit f7ba91d4175de437a6a2a5978021824ad1a53429 at: https://64cd2f55842a6d359597c7c0--layer5.netlify.app

**Comment by sarkartanmay393** [comment]
@Ghat0tkach I messed up this branch, so raising a new PR with minimal code chagnes.

**Pull request closed without merging**
