### PR TITLE
New blog: Contributing to Layer5

### PR DESCRIPTION
**Pull request by nwanduka**
New blog highlighting my experience contributing to Layer5 as a design intern

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7707df976462fd376f62dbf62c2b79f525684a76 at: https://6593334173b2160936441bd9--layer5.netlify.app

**Review by iArchitSharma — CHANGES_REQUESTED** [review]
@nwanduka please change directory name from `Contributing as a designer` to  
 `Contributing-as-a-designer`

**Comment by leecalcote** [comment]
I tweaked a couple of small items, which should put this post in good shape and building successfully.

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit d6d07074bc10e3780d1b281254ce91e73f5731d6 at: https://66074df60a8a026c9ccbf53b--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e076f8cd31a39431376edf7bb7b8671ffe9df6aa at: https://6607545c0a8a027129cbf1b2--layer5.netlify.app

**Comment by leecalcote** [comment]
👩‍🎤

**Pull request merged**
