### PR TITLE
Grammatical issues fixed 

### LINKED ISSUE #5028: [Grammar Adjustment] Community - Community Membership
**Current State:**

- Link to website: https://layer5.io/community/members
- Currently, there's a sentence in the paragraph next to the **Community Membership** heading reads as follows: "We also spend a great deal of time trying to recognize and uplift contributors on the Layer5 and Meshery Twitter accounts whether "contribution" means code or any of the other various forms of being involved int the projects and community."

**Desired State:**

- The suggested change is to adjust the sentence so it reads as: "We also spend a great deal of time trying to recognize and uplift contributors on the Layer5 and Meshery Twitter accounts whether "contribution" means code or any of the other various forms of being involved in the projects and community."

---
**Screenshot**

imageedit_2_8919288326

### PR DESCRIPTION
**Pull request by geetika005**
**Description**

This PR fixes #5028 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by geetika005** [comment]
Screenshot
Before

Screenshot_2023-10-12-17-09-06-80_40deb401b9ffe8e1df2f1cc5ba480b12

After 

Screenshot_2023-10-12-17-03-17-16_40deb401b9ffe8e1df2f1cc5ba480b12

**Review by Gautam-04 — COMMENTED** [review]
The PR looks good. Just a suggestion: Rather than naming your PR "Fixes Issue xyz," try writing what the issue fixes, something like "Grammatical issues fixed." It will be easier for reviewers to understand.

**Comment by geetika005** [comment]
> The PR looks good. Just a suggestion: Rather than naming your PR "Fixes Issue xyz," try writing what the issue fixes, something like "Grammatical issues fixed." It will be easier for reviewers to understand.

Sure,i"ll keep that in mind

**Review by sandramsc — APPROVED** [review]
LGTM!

**Review by abhijeetgauravm — APPROVED** [review]
Thanks for the contribution @geetika005 LGTM!

**Comment by Mohith234** [comment]
@sudhanshutech Ready to merge..

Thanks for your contribution @geetika005 🚀

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
