### PR TITLE
Add description prop to books, careers, integrations and workshops pages SEO

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

Follow up PR for #4836 ( [Comment](https://github.com/layer5io/layer5/pull/4836#issuecomment-1710581649) )

**Notes for Reviewers**
- I have checked all the templates for a field to add as a description to the SEO component
- Found some fields suitable in the `books`, `careers`, `integrations`, and `workshops` pages.
- The `news` pages have a field `subtitle` as a suitable field for description but when I look into the `.mdx` files there are majority of empty strings as subtitles so they were not included here.
- Let me know If I need to add `description` to any other pages

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eb5d40d9123ad99dac92a0f0bb3d51dc565525c9 at: https://64ff6ff600d9d548e58e1352--layer5.netlify.app

**Review by randychilau — APPROVED** [review]
Hi @Mohith234,

Nice job expanding your previous work into this PR. The changes look good and will help the SEO for current and future MDX pages using these templates.

LGTM!

Cheers,
Randy

**Comment by randychilau** [comment]
Hi @Mohith234,

If you wanted expand your previous work even further in another PR, here are some possible tasks:

As you mentioned in your notes regarding the `news` pages, there was a field `subtitle` not being used.
   - to improve SEO for these pages, update the `news` mdx files with a proper `frontmatter` field and content to be shown in the `head` section. Options may include adding content for the `subtitle` field or adding a `description` field and using the first two sentences of the post as content.
  - find the instructions for creating MDX files in each collection (e.g. `news`) and review/update them to make sure it indicates which fields should be required before publishing and why.

Other mdx page collections that could benefit from better SEO:
  - there are MDX files in folders `src/collections/members` and `content-learn` that are using templates that could also be improved. (note: if the content for a potential field may seem too long (e.g. `bio`), you can use javascript techniques to only include a portion of that content in the field).

Cheers,
Randy

**Comment by l5io** [comment]
🚀 Preview for commit d9023f0a03c7ad37541e622c97d675b35b5fe632 at: https://65044eb17d7cc51b242a1af2--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
hey @Mohith234 
Let's discuss it on the websites call.
I have already added your agenda as part of today's meeting minutes

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by leecalcote** [comment]
If @randychilau approves, then I approve. 👏

**Pull request merged**
