### PR TITLE
Member profile: Mario Arriaga

### LINKED ISSUE #2379: [Community] Member Profile: Mario Arriaga
**Current Behavior**

@MarioArriaga92  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @MarioArriaga92  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: MarioArriaga92
- Twitter: 
- LinkedIn: mario-arriaga-29a600b5
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Abusayid693**
**Description**

This PR fixes #2379

Community Member profile: Mario Arriaga

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f21ee1e7211f0f1b122b5675315ed4d817b586a4 at: https://61a8c9ba6cfbea00acc8175f--layer5ng.netlify.app

**Comment by leecalcote** [comment]
@MarioArriaga92! Looking good!

**Comment by leecalcote** [comment]
https://61a8c9ba6cfbea00acc8175f--layer5ng.netlify.app/community/members/mario-arriaga

**Review by leecalcote — APPROVED** [review]

**Review by MarioArriaga92 — APPROVED** [review]
Looks awesome, thanks @Abusayid693

**Comment by leecalcote** [comment]
Yay! 🎈

**Pull request merged**
