### PR TITLE
Fixed issue with safari

### LINKED ISSUE #2027: Safari specific issue on Community Member page on Layer5.io
**Description**
The newly added drop-down on the community member page doesn't work on safari.

**Screenshots**
Screenshot 2021-07-26 at 7 10 41 PM

**Expected Behavior**
Should have the same behaviour as the page on Chrome.
Screenshot 2021-07-26 at 7 16 10 PM

**Enviroment:**
- Host OS: MacOS
- Meshery Version: 
- Kubernetes Version: 
- Browser: Safar

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Changes made should fix the problem thats occurring on safari
This PR fixes #2027

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6145d581db14cb0d1c7d2e99dba7020253671fbb at: https://6103bcc375027e26e4e92721--layer5ng.netlify.app

**Review by sudo-NithishKarthik — CHANGES_REQUESTED** [review]
Good work @warunicorn19 , since we are here, can you also fix those spacing issues ?

Screenshot 2021-07-30 at 2 23 23 PM

**Comment by warunicorn19** [comment]
okayy @sudo-NithishKarthik

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik 
Screenshot 2021-07-30 at 2 36 10 PM

does this look okay?

**Review by sudo-NithishKarthik — CHANGES_REQUESTED** [review]
Screenshot 2021-07-30 at 2 47 36 PM

Its been bugging me for quite some time 😅

**Comment by l5io** [comment]
🚀 Preview for commit dba32d6cbefef38e4f48aaa5e0af1924a382e1a4 at: https://6103c44afe90511e4acfbc3c--layer5ng.netlify.app

**Comment by warunicorn19** [comment]
Ohh okay that, @sudo-NithishKarthik  , so the thing with word Service Mesh Performance is that it's huge, so if I put that in one line a horizontal scroll appears, which Tanuj said we need to avoid, I'll take a look at what I can do about the spacing at the top.

**Comment by l5io** [comment]
🚀 Preview for commit 396427403f9881e5dab75414922c99e18a182b3a at: https://6103ded2e8288d48199195ab--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9624b201c69dd19793091791446c348de05b16b7 at: https://610445b2ba5c3716f56843a4--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 534341b335f6ce0b7f43a869919565aa96bcf168 at: https://6104485e79da0a1a4ac48e16--layer5ng.netlify.app

**Comment by leecalcote** [comment]
This works in my Safari. ✔️ 

Would you be so kind as to swap out the non-fill version of the Meshery Operator logo with the filled version? https://raw.githubusercontent.com/layer5io/meshery-operator/master/img/readme/meshery-operator-dark.svg

**Comment by warunicorn19** [comment]
> This works in my Safari. ✔️
> 
> Would you be so kind as to swap out the non-fill version of the Meshery Operator logo with the filled version? https://raw.githubusercontent.com/layer5io/meshery-operator/master/img/readme/meshery-operator-dark.svg
> 
> This SVG should already be in an assets/logos folder in the layer5 repo somewhere.

Yes sir, right away.

**Comment by l5io** [comment]
🚀 Preview for commit b54bf0b3da798aaef410a89583b04f46fa6f092d at: https://6105922121527d2b91fb4077--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
All looks good to me, just one thing though.... better to have some white space around other times rather than cutting of the `Service Mesh Performance` filter.

**Comment by warunicorn19** [comment]
> All looks good to me, just one thing though.... better to have some white space around other times rather than cutting of the `Service Mesh Performance` filter. Because, anyways some whitespace is always there not matter what you do.

Okay, So I'll shift the `service mesh performance` towards the left so it doesn't get cut off right?

**Comment by Nikhil-Ladha** [comment]
It's already starting from the left, so I think increasing the width like before is the only solution.

**Comment by Nikhil-Ladha** [comment]
Also, I think `center` alignment looks better. But, will consider the majority's view.

**Comment by warunicorn19** [comment]
So bringing back the horizontal roll?

**Comment by Nikhil-Ladha** [comment]
Why will there be a horizontal scroll? 🤔

**Comment by warunicorn19** [comment]
I actually thought so too about the center align, maybe we can discuss this in the websites call tomorrow at length?

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
