### PR TITLE
added cncf logo and solved issue #4017

### LINKED ISSUE #4017: Add CNCF logo to Home page carousel
### Desired Behavior
In the "ENGAGING AND COLLABORATING WITH" section, add the CNCF logo (SVG is already present as an asset in the site) to the carousel.

Screenshot 2023-03-28 at 10 29 06 AM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ayushgupta4002**
**Description**

This PR fixes #4017

**Notes for Reviewers**
Reopening a PR with CNCF logo added in home page carousel 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
@Chadha93 Please check

**Review by hirentimbadiya — COMMENTED** [review]
please write [x] inorder to tick the checkbox in PR description and LGTM.

**Comment by ayushgupta4002** [comment]
> please write [x] inorder to tick the checkbox in PR description and LGTM.

Oh sorry , I have corrected it ,kindly check again

**Comment by l5io** [comment]
🚀 Preview for commit 052685b9c61db481e96f8a42073ef5b23e39d190 at: https://642bb665f888335d9763cff5--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
LGTM

**Pull request merged**
