### PR TITLE
paging dots color changed in darkmode

### LINKED ISSUE #3847: Scroll slider not visible in dark mode
### Description
On the Meshery project page here [https://layer5.io/cloud-native-management/meshery](https://layer5.io/cloud-native-management/meshery), scroll slider in the features section (for small sized screens) is not visible in dark mode.

### Expected Behavior
The slider dots need to be changed to a lighter color for dark mode. 

### Screenshots
Scroll slider visible in light mode.
image

But not visible in dark mode.
image

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShravaniAK**
**Description**

This PR fixes #3847 

Screenshot 2023-03-05 at 11 53 28 PM

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b4102d65ebe6816e55c8e949632df17bdd31ebcc at: https://6404e37f29b76141d737791c--layer5.netlify.app

**Review by Shivam-AfA — APPROVED** [review]
Looks good to me. 👍

**Comment by ShravaniAK** [comment]
yes i was going to remove it but it was giving an hover type effect like clicked event type , should i still remove it ?

**Comment by Chadha93** [comment]
> yes i was going to remove it but it was giving an hover type effect like clicked event type , should i still remove it ?

Yes please, rest looks good.

**Comment by ShravaniAK** [comment]
ok will do the changes

**Comment by l5io** [comment]
🚀 Preview for commit c489c7882317c18bfb000bf257e699bc49bbfcba at: https://6405fd929e10cf1bf9cb6f14--layer5.netlify.app

**Comment by ShravaniAK** [comment]
@Chadha93 is this fine now ?

**Review by Nikhil-Ladha — COMMENTED** [review]
While you are there, could you please center align the image/text as well?
Screenshot 2023-03-10 at 12 26 45 PM

**Comment by l5io** [comment]
🚀 Preview for commit 45c29ccfe692feadd2e8bed46f4e001aa9d646e8 at: https://640d45781a438e1e5b297abc--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 45caf30755fe38852ae02b6e5ddb4b0191c72a47 at: https://640d4c9876710f215f103274--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
