### PR TITLE
5usana/contribution

### PR DESCRIPTION
**Pull request by 5usana**
added a BBC news article to this repository!

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — COMMENTED** [review]
Hello @5usana , thank you for jumping in here. Unfortunately, we don't support 'General' news article on our site, yet. So, please close out this PR and you can look into open issues to work upon and contribute.

**Comment by 5usana** [comment]
> Hello @5usana , thank you for jumping in here. Unfortunately, we don't support 'General' news article on our site, yet. So, please close out this PR and you can look into open issues to work upon and contribute.

Hello @Nikhil-Ladha thank you for your feedback. did I completely misinterpret this repo, where was I supposed to pull news reports from?

**Comment by Nikhil-Ladha** [comment]
> > Hello @5usana , thank you for jumping in here. Unfortunately, we don't support 'General' news article on our site, yet. So, please close out this PR and you can look into open issues to work upon and contribute.
> 
> Hello @Nikhil-Ladha thank you for your feedback. did I completely misinterpret this repo, where was I supposed to pull news reports from?

This repo contains the code for the Layer5 website. It contains news article related to Layer5 itself and not other general news articles.
And, this news article doesn't relate to Layer5 itself. Hence, the request to close the PR.

And, you don't need to pull news report form other sources into Layer5, if there would be one you could find an open issue.

**Comment by leecalcote** [comment]
@5usana, teasing out what is between the lines in @Nikhil-Ladha's comments:

- yes, your PR is slightly off to the side of the goal of the new items published through this repo, but let's be very clear: **we love** having you jump in here. ❤️ Please don't let this initial miss deter you from continuing to engage here. 
- You're most welcome to grab an [open issue](https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+) across any of the projects here and most encouraged to join the Layer5 community (https://layer5.io/community) - http://slack.layer5.io
- examples of prior [`news` PRs:](https://github.com/layer5io/layer5/pulls?q=is%3Apr+is%3Aclosed+news+label%3Aarea%2Fnews)
- news in this case is as related to people and projects in the Layer5 community --> https://layer5.io/news

**Comment by 5usana** [comment]
@Nikhil-Ladha @leecalcote
Thank you both for your feedback, I wanted to better understand what went wrong and how I could correct it (I wasn't ready for defeat). I'll take a look at the other open issues. Looking forward to making my own contributions the layer5 community!

**Comment by leecalcote** [comment]
Haha! Excellent, @5usana. 😄

**Pull request closed without merging**
