### PR TITLE
notify when copied

### LINKED ISSUE #1753: Notify user when the code block content is copied
**Current Behavior**

Currently When clicking on Copy button ,the command is getting copied ,but there is no notification to the user that the command is copied. 

**Desired Behavior**

Notify user On Clicking Copy Button on CodeBlock component that the command is copied.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113516703-598ed580-9599-11eb-891c-729a1057f9e2.mp4

[Optional] **Alternatives**

Refer to [mehery.io](https://meshery.io/) Codeblock Component.

https://user-images.githubusercontent.com/44670961/113516816-ffdadb00-9599-11eb-8a0e-bdbc65fddc37.mp4

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by rijusougata13**
**Description**

This PR fixes #
Fix #1753 
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e6ef138da0d3e2b0f0ac51bb7ae93ae47d32c44d at: https://606a2fc0e40310c76789612b--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e6ef138da0d3e2b0f0ac51bb7ae93ae47d32c44d at: https://606a2fe53520339e138e0eec--layer5ng.netlify.app

**Comment by chinmaym07** [comment]
Hey @rijusougata13 Copy button doesn't work here 
https://606a2fe53520339e138e0eec--layer5ng.netlify.app/blog/meshery/functional-testing-with-cypress-in-meshery-ui
when you click on multiple copy button ..only one element's text gets changed .. Other element's text doesn't change .

**Comment by rijusougata13** [comment]
i changed that component/codeblock/index.js.. It should effect all of the copy button . Let me check one more time @chinmaym07

**Comment by rijusougata13** [comment]
@chinmaym07  fixed the problem.. sending the pr

**Comment by rijusougata13** [comment]
can you check why this check failing @chinmaym07

**Comment by l5io** [comment]
🚀 Preview for commit 711a34bd950e08609d6263ef48a3234d0796e534 at: https://606aad538b93a4ac6f662e72--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@rijusougata13 thanks for the PR but since we already have PR #1755 which fixes the issue. I would request you to close this and comment on any other open issue which you would like to work upon and  I will see if it can be assigned to you.

**Comment by leecalcote** [comment]
@rijusougata13 thanks for jumping in. It's great to have you engaged here. 😄

**Comment by rijusougata13** [comment]
> @rijusougata13 thanks for jumping in. It's great to have you engaged here. 😄

@leecalcote  Thanks...Closing this PR then

**Comment by leecalcote** [comment]
@rijusougata13, ok, sounds good. There are plenty of other issues where this one comes from - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+. If you don't see a fitting / interesting one unassigned, I encourage to you to check with the current assignee - time might have gotten the better of their good intentions and they might not be actively implementing. Let me know if you don't find one or jump into the community Slack and we'll help you get a foothold on an active project - http://slack.layer5.io

**Comment by rijusougata13** [comment]
> @rijusougata13, ok, sounds good. There are plenty of other issues where this one comes from - [https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+). If you don't see a fitting / interesting one unassigned, I encourage to you to check with the current assignee - time might have gotten the better of their good intentions and they might not be actively implementing. Let me know if you don't find one or jump into the community Slack and we'll help you get a foothold on an active project - http://slack.layer5.io

sure i will take a look there @leecalcote

**Comment by leecalcote** [comment]
Fantastic to see that you're taking on a couple other issues, @rijusougata13 👍. Closing this one out...

**Pull request closed without merging**
