### PR TITLE
Updated Screen Shots of Cdk8s for Kubernetes

### LINKED ISSUE #4863: [Screenshots] Cdk For Kubernetes (Cdk8S) under 'How it Works See It in Action' section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/cdk-for-kubernetes-cdk8s) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Cdk For Kubernetes (Cdk8S)](https://layer5.io/cloud-native-management/meshery/integrations/cdk-for-kubernetes-cdk8s) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #4863

**Notes for Reviewers**
Changed the previous ScreenShots

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 7fab0d7975ec608d6f5b63595fb6b98a940ae184 at: https://653213a9185e4f5e3f4a6f8b--layer5.netlify.app

**Comment by sandramsc** [comment]
The screenshots look good to me. However based on previous feedback [here](https://github.com/layer5io/layer5/pull/4914#issuecomment-1721769023)  @Mohith234 , would you still suggest that the subcategory icons in the sidebar be made visible? It might help to include this requirement in the issue template to reduce repetition.

**Review by sandramsc — COMMENTED** [review]
The screenshots look good to me. However based on previous feedback [here](https://github.com/layer5io/layer5/pull/4914#issuecomment-1721769023)  @Mohith234 , would you still suggest that the subcategory icons in the sidebar be made visible? It might help to include this requirement in the issue template to reduce repetition.

**Comment by Mohith234** [comment]
I don't think the subcategories are necessary @sandramsc, The feedback provided [here](https://github.com/layer5io/layer5/pull/4914#issuecomment-1721769023) was about the normal sidebar icons which weren't present on your initial commit of the PR. 

Also, I suggest the screenshots in this current PR be only of the browser and not the whole screen (including the desktop icons on the side ).

// @narasimha-1511

**Comment by sandramsc** [comment]
> I don't think the subcategories are necessary @sandramsc, The feedback provided [here](https://github.com/layer5io/layer5/pull/4914#issuecomment-1721769023) was about the normal sidebar icons which weren't present on your initial commit of the PR.
> 
> Also, I suggest the screenshots in this current PR be only of the browser and not the whole screen (including the desktop icons on the side ).
> 
> // @narasimha-1511

I see which screenshot you were reffering to now. This clears up that misunderstanding on my end.

**Comment by sandramsc** [comment]
@narasimha-1511 in addition to what @Mohith234 mentioned, please take note of the following:

- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

These points have been stated in the issue description.

**Comment by narasimha-1511** [comment]
@sandramsc 
Hey , I will again Upload these Images with Incongito ..
Thanks For the feedback

**Comment by Mohith234** [comment]
@narasimha-1511 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by narasimha-1511** [comment]
I have added today @Mohith234

**Comment by sudhanshutech** [comment]
any update @narasimha-1511 ?

**Comment by narasimha-1511** [comment]
@sudhanshutech  I will Update the screen shots removing the task bar .

**Comment by narasimha-1511** [comment]
@leecalcote I have made mistake while pushing the commits so i created a new pr

**Pull request closed without merging**
