### PR TITLE
Updates in proud maintainers section and faq section

### LINKED ISSUE #1451: [Landscape] Timeline: Change timeline expander button
**Current Behavior**
The [service mesh landscape](https://layer5ng.netlify.app/service-mesh-landscape/) has a timeline with an expander at the bottom of the timeline.

Screen Shot 2021-01-31 at 3 50 16 PM

**Desired Behavior**
Please update the button coloring and behavior. Invert button colors so that:

Inactive State:
- bright yellow background color 
- downward pointing arrow is white 

Active State:
- dull yellow background color 
- downward pointing arrow is dark jungle green 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR fixes #1532 and also fixes #1451
This PR adds Contact Modal in the FAQ page as well.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Done and dusted ✔️

**Review by leecalcote — DISMISSED** [review]

**Comment by Tanuj22** [comment]
@Nikhil-Ladha The text is not fitting 
Screenshot from 2021-02-13 00-47-46

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha The text is not fitting
> Screenshot from 2021-02-13 00-47-46

Resolution?
For me, everything looks fine up to 350px.

**Comment by Tanuj22** [comment]
Used the iPhone X from Chrome dev tools

**Comment by leecalcote** [comment]
The shadow under the Ask Us button is getting cutoff.

**Review by leecalcote — DISMISSED** [review]

**Pull request merged**
