### PR TITLE
fixed:typo in community's handbook writing program

### LINKED ISSUE #4626: Typos in Writing Programme.
### Description

There is a typo for the word documentation in the 
Writing programme for handbook [page](https://layer5.io/community/handbook/writing-program)
And also the spelling of vulnerabilities.
[Here](https://layer5.io/community/handbook/contributor-journey)
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
**Description**
This PR fixes #4626 

**Notes for Reviewers**
fixed:typo in community's handbook writing program

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 0b0ed3916b25afb9ecb912c8f6dfb07b52ab6387 at: https://64c10cefb92a5763697d0aab--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2e9ce408b3a52d6190a91df6dfe1cda8c8c87a69 at: https://64c11e46fdb32d0072bf6d5a--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
LGTM @abhijeetgauravm ✨

**Review by leecalcote — APPROVED** [review]
Thanks!

**Pull request merged**
