### PR TITLE
Fixed the color issue

### LINKED ISSUE #5232: [BUG] Options not visible in roles dropdown list on meshmap page
### Description
https://layer5.io/cloud-native-management/meshmap
Here at "join the beta" form "select role" options are not visible. 

### Expected Behavior
Text color should be changed

### Screenshots
Screenshot 2023-12-26 112840

### Environment:
- Host OS: windoes
- Browser: chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by narasimha-1511**
**Description**

This PR fixes #5232 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f73c22372168545e86e7a5542ee793f4f96600ed at: https://66374be3a93f24b169cbe639--layer5.netlify.app

**Comment by narasimha-1511** [comment]
The issue is fixed 

image

**Comment by vishalvivekm** [comment]
@narasimha-1511 Let's discuss this on Websites's call. 
Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by narasimha-1511** [comment]
SURE DONE @vishalvivekm

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
