### PR TITLE
Introducing a blog for layer5.

### PR DESCRIPTION
**Pull request by Shubhf**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit eff718507ba5e3699e85395ece304534eacbe132 at: https://66b449fa9cf9468ca204dab2--layer5.netlify.app

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@Shubhf this is not the right place to add blogs. See other blogs for example where its been added. It is under [here](https://github.com/layer5io/layer5/tree/master/src/collections/blog).
There is a template also to give you help.
If you are writing this blog you should be the author

**Comment by Shubhf** [comment]
Thanks for giving me feedback ..I will make necessary changes ..and get
back to u

**Comment by Shubhf** [comment]
This is the issue I am targeting , here Author name is Anita iHuman

**Comment by Shubhf** [comment]
https://github.com/layer5io/layer5/issues/2323#issuecomment-2271978825
This is the given link

**Comment by Ashparshp** [comment]
@Shubhf Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
@Shubhf https://layer5.io/blog.

**Comment by Shubhf** [comment]
Thanks a lot.

**Comment by sudhanshutech** [comment]
@Shubhf done ?

**Comment by Shubhf** [comment]
It will be done by the evening

**Comment by Shubhf** [comment]
I have done the changes only final forking is left .. will do it by 6 or
before that

**Comment by Shubhf** [comment]
My net is not working

**Comment by Ashparshp** [comment]
@Shubhf, any updates?

**Comment by Shubhf** [comment]
I have already done that on. 14 th August

**Comment by Shubhf** [comment]
I think there are some errors in workflow .. I ll get back to you by the 3 pm

**Comment by l5io** [comment]
🚀 Preview for commit e9377f2ab0802ca36a2285f0574983ef2966ca44 at: https://66bef40151ea82c38f6ba281--layer5.netlify.app

**Comment by sudhanshutech** [comment]
This is still in wrong place. // @Ashparshp

**Comment by Shubhf** [comment]
Ok, I'll check it out.

**Comment by l5io** [comment]
🚀 Preview for commit bca9361efb0319a6e670636a02c03f040d5c2b81 at: https://66c1d5e0d0dc706a6cd12bbf--layer5.netlify.app

**Comment by Shubhf** [comment]
I am trying my best to resolve it ..I ll give a final word by the evening

**Comment by Shubhf** [comment]
Yes, it is working. Now I have made desired changes #5841 check @Sudhanshu

**Pull request closed without merging**
