### PR TITLE
Added Suruchi Kumari to members

### LINKED ISSUE #5099: [Community] Member Profile: Suruchi Kumari
**Current Behavior**

@coder12git  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @coder12git as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @coder12git 
- Twitter: [Suruchi18591098
](https://twitter.com/Suruchi18591098)
- LinkedIn: [in/suruchi-kumari-5b3445230](https://www.linkedin.com/in/suruchi-kumari-5b3445230/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Harsha-10**
**Description**

This PR fixes #5099

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2b46d66e545464fd5eae2bc1483a315ad7279f48 at: https://65465daef165511f6626231e--layer5.netlify.app

**Comment by Harsha-10** [comment]
please review @coder12git

**Comment by coder12git** [comment]
> please review @coder12git 

Also add the Layer5 icon after meshery icon, because I am member of both

**Review by sudhanshutech — APPROVED** [review]
LGTM, @coder12git the meshery badge is project badge not an org. We don't have any layer5 badge for now.

**Pull request merged**
