### PR TITLE
Add new events

### LINKED ISSUE #889: [Events] Add KubeCon NA 2020 talk to /events collection
**Current Behavior**
Layer5 is speaking at KubeCon NA 2020

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by chandrashritii**
**Description**

This PR fixes #889 and #898 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by chandrashritii** [comment]
@leecalcote Don't have event links yet for the CCOSS workshop or Kubecon NA. It will tentatively take about a week to get both the links. Can the cards be updated when the links are available?

**Review by kushthedude — CHANGES_REQUESTED** [review]
Sign off your commits

**Review by leecalcote — CHANGES_REQUESTED** [review]
> @leecalcote Don't have event links yet for the CCOSS workshop or Kubecon NA. It will tentatively take about a week to get both the links. Can the cards be updated when the links are available?

Thank you, @chandrashritii. Yes, that'll work. Please review the current behavior of these two cards. When clicked they do not navigate the user to the event. Temporarily, the should navigate the user to the event and once the talk is published, that link should be updated to point to the talk specifically.

**Comment by leecalcote** [comment]
Link to one of the KubeCon NA 2020 talks sent.

**Comment by chandrashritii** [comment]
Event links have been updated.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
