### PR TITLE
removed Writing Programs issue no :#4917

### PR DESCRIPTION
**Pull request by bunnyDasari**
shorten to simply "Internship Programs" issue no :#4917

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4982cc3517fa33d98a35f1947d14ada189ba2d01 at: https://6522594bd713cf0b7062c3d6--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Hi @bunnyDasari 
Please note:

> Implementation


    1. Consolidate "Internship and Writing Programs" into one line. If this combined text is too long, then shorten to simply "Internship Programs"
  2.   Add new section for Writing Program in the [Internships page](https://layer5.io/careers/programs)

Acceptance Tests

   1. layer5.io/community/handook is a new "Handbook" link in the footer under the Community section.
   2. Writing program is represented on the Internships page.

**Comment by abhijeetgauravm** [comment]
Hey @bunnyDasari, we appreciate your enthusiasm to contribute. However, please refrain from creating direct PRs without being assigned first. Kindly read the contributing guidelines beforehand. Since your PR is already up, let's incorporate the changes suggested by @vishalvivekm. Also, please sign off your commits to avoid DCO check failures.

**Comment by abhijeetgauravm** [comment]
Hey @bunnyDasari Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Pleasde add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by abhijeetgauravm** [comment]
Hey @bunnyDasari  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Mohith234** [comment]
Closing this as there is no response and the issue is assigned to another contributor

**Pull request closed without merging**
