### PR TITLE
added parthib-datta profile

### LINKED ISSUE #5034: [Community] Member Profile: Parthib Datta
**Current Behavior**

@ptdatta has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ptdatta as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @ptdatta
- Twitter: [@parthibdatta123](https://twitter.com/parthibdatta123)
- LinkedIn: [parthib-datta-90b29b1b4](https://www.linkedin.com/in/parthib-datta-90b29b1b4/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by milinddethe15**
**Description**

This PR fixes #5034 

**Notes for Reviewers**
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 6ef5cae126b452c5d29477a2839a23ea5084d4c6 at: https://65293fd61d133d386c59f206--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
@ptdatta your review would be appreciated!

**Comment by ptdatta** [comment]
Awsome work @milinddethe15. Thank you. ♥♥

**Review by abhijeetgauravm — APPROVED** [review]
Thanks for the contribution @milinddethe15 LGTM!

**Comment by abhijeetgauravm** [comment]
> Awsome work @milinddethe15. Thank you. ♥♥

// @ritiksaxena124 @sudhanshutech

**Comment by ritiksaxena124** [comment]
LGTM 🚀

**Pull request merged**
