### PR TITLE
Khanjasir90/add osm lab

### LINKED ISSUE #2189: [Learn] Add Open Service Mesh lab
Current Behavior
The newly created Open Service Mesh lab hasn't been added to https://layer5.io/learn .

Desired Situation
Let's put up the Open Service Mesh lab [here](https://layer5.io/learn/service-mesh-labs) .

https://github.com/layer5io/layer5/blob/master/src/sections/Learn/Service-Mesh-Labs/courseData.js

https://github.com/layer5io/layer5/tree/master/src/collections/service-mesh-labs

Contributor Resources

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the master branch.

See contributing instructions
See Layer5 site designs in this Figma project. Join the Layer5 Community for access.

### PR DESCRIPTION
**Pull request by khanjasir90**
**Description**

This PR fixes #2189 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 4811e574026ef579e0c7f8b26477dd04220102c0 at: https://614778b92bf54e4a7892651b--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@khanjasir90 could you please change this file name `working_with_open_service_mesh` to `working_with_meshery_and_open_service_mesh` and also change it in the link. And, if you could please test out the changes locally before committing, right now the link of the lab doesn't work, it is showing a 404 error.

**Comment by warunicorn19** [comment]
Also, you could just add and commit the changes to this PR itself, no need to create another one.

**Comment by khanjasir90** [comment]
@warunicorn19 done with the changes can u pls check it !

**Comment by l5io** [comment]
🚀 Preview for commit 956d232352c26ce583d8eec760f2c75ec2bdcdf0 at: https://614789efd1832a4fa613e749--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ba08d1a77ad7e68c269ba8be57335e3297ea4c21 at: https://61478c9ac3e2e2d0f71bfb0c--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, thanks for this @khanjasir90.

**Pull request merged**
