### PR TITLE
Member Profile of Jerens Lensun

### LINKED ISSUE #5835: [Community] Member Profile of Jerens Lensun
**Current Behavior**

@jerensl has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @jerensl as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/jerensl
- Twitter: https://x.com/jerensl22
- LinkedIn: https://www.linkedin.com/in/jerensl
- Layer5 Cloud: https://meshery.layer5.io/user/2e246a4a-11e3-4b99-8c79-e42f8565e4be
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Spoorthy1423**
#5835 [Community]  Created member profile of Jerens Lensun

**Description**

This PR fixes #5835 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3d88f2c7e01282d047fdc29a6202a19f94ac09cc at: https://66ca4d76f02c1b50bf16b85b--layer5.netlify.app

**Comment by amitamrutiya** [comment]
Hey @Spoorthy1423, thanks for making this PR. It's highly appreciated.

The DCO workflow is failing. Please fix this before we can proceed. For more info, check [this](https://docs.meshery.io/project/contributing/contributing-docs#:~:text=Create%20a%20Pull%20Request,off%20flag%20(%2Ds)!&text=Once%20all%20changes%20have%20been%20committed%2C%20push%20the%20changes.&text=Then%20on%20Github%2C%20navigate%20to,from%20your%20recently%20pushed%20changes!).

**Comment by Ashparshp** [comment]
@Spoorthy1423, not worling?

**Comment by Spoorthy1423** [comment]
@Ashparshp i am still working on this and by eod i will raise another pr with DCO workflow

**Comment by Ashparshp** [comment]
For dco you can open vs code (if using) 

Open press ctrl + ,

then in search of setting search sign-off
and tick after this you do not need to include manually.

**Pull request closed without merging**
