### PR TITLE
Blog List View Changes

### PR DESCRIPTION
**Pull request by Jashpatel1**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
@Jashpatel1 can you format the code my running `npm run lint`

**Comment by Tanuj22** [comment]
The tooltips are looking different. Also the icons have more space at the bottom?
ezgif-7-3ba0943b468f

**Comment by Jashpatel1** [comment]
> The tooltips are looking different. Also the icons have more space at the bottom?
> ezgif-7-3ba0943b468f

I havent changed anything to the icons or spacing even, just added a border and changed colours a bit.

**Comment by Nikhil-Ladha** [comment]
The divider in the middle looks a bit odd, like there is a gap in the bottom. 
Also, if the box can be filled with color on selection and hover. It will make it look better.

**Comment by leecalcote** [comment]
Gents, I will submit to you that a border here is a misstep - overkill.  A `|` might do the trick or some other softer approach.

**Comment by Nikhil-Ladha** [comment]
Actually, yeah. Here, it looks like that but the picture I had in mind was something different. So, I will try if I can do something to create it visually and then take some feedback on that.

**Review by leecalcote — CHANGES_REQUESTED** [review]
https://github.com/layer5io/layer5/pull/754#issuecomment-690618566

**Comment by leecalcote** [comment]
I don't think we got a chance to review this on yesterday's call, @Jashpatel1, but I'm hoping that you have the feedback you need to move forward.

**Comment by Nikhil-Ladha** [comment]
Oops, if you don't get anything from me by tonight please do make the changes Lee mentioned. Otherwise, can you please wait until tomorrow.

**Comment by Nikhil-Ladha** [comment]
So, here it is what I wanted to say in the first place
Screenshot from 2020-09-15 19-14-10
Screenshot from 2020-09-15 19-12-13

Does this look better?
@leecalcote @Jashpatel1 @Tanuj22 ?

**Comment by Tanuj22** [comment]
Yeah. This does look nice!

**Comment by Nikhil-Ladha** [comment]
Then, I think @Jashpatel1 you can implement this, preferably the first one I guess.

**Comment by leecalcote** [comment]
It'll be helpful to see this new style in-context of the rest of the page.

**Comment by leecalcote** [comment]
@Jashpatel1 I hate to be the bearer of bad news. The coloring is ... well, off. I don't know that I have better direction to give here other than to suggest that this isn't quite the design that we would like to have. We can accept this PR and move on for now with the intent return to style these buttons later.

**Review by leecalcote — DISMISSED** [review]

**Comment by Nikhil-Ladha** [comment]
Just a small change would be good, on hovering the colors should just revert and the gray should come up. Like, we have for the `Grid` icon when the page loads, it should remain as it is on hovering, and the other one should become the same.

**Comment by Jashpatel1** [comment]
> Just a small change would be good, on hovering the colors should just revert and the gray should come up. Like, we have for the `Grid` icon when the page loads, it should remain as it is on hovering, and the other one should become the same.

I didn't quite understand what you are trying to convey. Can you please elaborate?

**Comment by Nikhil-Ladha** [comment]
Basically, what I meant was to remove the gray😅.
And ,on hovering it should look similar to what it looks when the button is `active`

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
