### PR TITLE
fix spelling mistake in getting started guide

### PR DESCRIPTION
**Pull request by KaranJagtiani**
**Description**

This PR fixes a small spelling mistake in the patterns section in [getting started guide](https://layer5.io/cloud-native-management/meshery/getting-started).

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c1a10bdf8f6059e2510e8b96f7af36cece1be0cf at: https://649708c093d7076e281f1eb8--layer5.netlify.app

**Review by hirentimbadiya — COMMENTED** [review]
@KaranJagtiani  First, create an issue and ensure it is assigned to you before directly submitting a pull request.

**Comment by KaranJagtiani** [comment]
@hirentimbadiya sure thing! I will keep that in mind from next time :) Have created the issue [here](https://github.com/layer5io/layer5/issues/4432)

**Review by duckling69 — APPROVED** [review]
LGTM

**Review by hirentimbadiya — APPROVED** [review]
Good to Go 👍🏻

**Comment by vishalvivekm** [comment]
Thank you gents!

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
