### PR TITLE
 Hanged coming soon on enterprise  card

### PR DESCRIPTION
**Pull request by kushvahasumit**
**Description**

This PR fixes #

l9

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b1999ff9008b64a001ba318e106ef806af3d68a9 at: https://640cd1f73b6a78515da9ede7--layer5.netlify.app

**Comment by Shivam-AfA** [comment]
@kushvahasumit What's the issue here?

**Comment by kushvahasumit** [comment]
@Shivam-AfA why is showing 2 cross here dco and lighthouse???

**Comment by leecalcote** [comment]
Looking good, @kushvahasumit

**Pull request merged**
