### PR TITLE
In layer5/learn page slick-slider(carousel) arrows are not aligned.

### LINKED ISSUE #4525: [UI] In layer5/learn Carousel arrows are not aligned properly.
### **Description:** 
 In layer5/learn page slick-slider(carousel) arrows are not aligned properly.

**Desired State:** 
Arrow would be on center and bigger too.
**Screenshot**
Screenshot 2023-07-11 at 9 05 41 AM

**Evironment:**
Host OS: macOS
Browser: Firefox
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

### PR DESCRIPTION
**Pull request by Modern-artist**
### **Description:**
In layer5/learn page slick-slider(carousel) arrows are not aligned properly and icon are different. So I have aligned it properly and changed icon to desired icon issue #4525

This PR fixes #4525
Screenshot 2023-07-11 at 4 00 39 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c2400496c38c0e2dc93a7f33da208af588b3a3c9 at: https://64ad532e3f9f010ad1bc8afe--layer5.netlify.app

**Review by saaagarsingh — COMMENTED** [review]
After reviewing the codebase changes and subsequent UI changes. I'm satisfied that the PR resolves the mentioned issue and enhances the UI. Maintainers must check it once for approval.

**Comment by Saksham294** [comment]
LGTM🚀 Good work @Modern-artist

**Comment by Modern-artist** [comment]
Thank you Sir, It's my first step to opensource.

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Please take care of the merge conflicts @Modern-artist

**Review by DarrenDsouza7273 — APPROVED** [review]
LGTM @Modern-artist

**Comment by l5io** [comment]
🚀 Preview for commit e38a3d445bad5d513dc37e487de834ad4e96574f at: https://64b34e93bebe4967920a8944--layer5.netlify.app

**Pull request merged**
