### PR TITLE
changes for go live 

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**
- Fix some urls 
- Newcomers map
- Comment out the search box in the blog 
- Remove unused packages
- Clean some code
- 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Tanuj22** [comment]
I wasn't able to find a good way for downloading the brand files without the site taking a performance hit. The best would be to add a drive link I think. Maybe that's why they do the same here https://www.hashicorp.com/brand

**Review by Nikhil-Ladha — APPROVED** [review]
Then, the only way which seems possible is by using pure JS.

**Comment by leecalcote** [comment]
Hold your horses.... you're saying that you can't signal to a web browser to not preload any resources referenced by an anchor tag?

**Comment by Nikhil-Ladha** [comment]
It seems like that...🤔

**Pull request merged**
