### PR TITLE
Career page

### LINKED ISSUE #710: [NG] Migrate site data for the Careers page
**Description**
Currently, the page dedicated to [Careers](https://layer5ng.netlify.app/careers) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Careers](https://layer5.io/careers) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by vinayaksh42**
Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

**Description**
Migration of careers page from previous layer5 website to layer5-ng
 [previouse website](https://layer5.io/careers) ---> [layer5-ng](https://5f63810c65a5a300079ab255--layer5ng.netlify.app/careers)
This PR fixes #710 

**Notes for Reviewers**
I have made some ui changes while migrating from the previous layer5 Website to the current layer5-ng website according to my own thought process. So kindly guide on that and suggest any changes if needed

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vinayaksh42** [comment]
@Tanuj22 @Nikhil-Ladha can you review my pr?

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Looks good. But few improvements can be done:
- The `What is Layer5` section, can be moved above the video.
- In the opportunities section, all the internship cards can be moved below the internship subheading and a new `Full-Time Opportunities` subheading can be created and the other cards can be put below it.
- The design of the cards for the programs can be improved a bit, like the border can be made a bit more prominent.
- Also, `See our careers page...` line can be removed as we are already on the careers page

Also, @leecalcote any text or info that can be added for Full time opportunities like internship ?

**Comment by vinayaksh42** [comment]
@Nikhil-Ladha ,let me know if there is any content to be added under the full time sections. For the time being i have just added it without any description

**Comment by Nikhil-Ladha** [comment]
Okay, so for the time being do one thing move the text part below the internship section, above it below the `Available Opportunities` heading.
- Move the subheading Full time opportunities a bit down, more towards the below displayed cards rathwr than the top.
Screenshot_20200918-094616__01

- The bottom and top borders of the cards in the middle can be made more prominent.
Also, on hovering the card in mobile view the zoom effect is good, but it leads the card to overlap with the other cards.
Screenshot_20200918-094631__01

**Comment by vinayaksh42** [comment]
Made the changes you requested @Nikhil-Ladha . Tho i am not able to understand what you mean by making the borders more prominent.

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good now.
Nice work :rocket: @vinayaksh42

**Pull request merged**
