### PR TITLE
fix: events, workshops, meetups sort datewise

### LINKED ISSUE #4546: Events and Workshops listed in random order
### Description

The 'Events and Workshops' tab section on the Events page does not follow the correct order, as it does not display the most recent events or workshops in the first position. Instead, they are listed randomly. 
### Expected Behavior

They should be listed according to their dates i.e., the most recent event comes first.
### Screenshots

Screenshot (92)

Screenshot (91)

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by GitsOfVivek**
**Description**

This PR fixes #4546

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c4325c9d3ff80876bde4b55dc99b5f5b2951c6aa at: https://64bd124191c0a3141df95346--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d369276695a41244f0255787c3d959162bbba774 at: https://64bd1b6074de0818f28c551d--layer5.netlify.app

**Review by hirentimbadiya — APPROVED** [review]
Excellent, @GitsOfVivek! looks impressive for merging. Thank you for your valuable input 🎈✨!

**Comment by vishalvivekm** [comment]
@GitsOfVivek Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Review by leecalcote — APPROVED** [review]
Excellent. Thanks, @GitsOfVivek, @hirentimbadiya, @vishalvivekm

**Pull request merged**
