### PR TITLE
[Site Performance] Image optimization for the Community Page Image Carousel

### PR DESCRIPTION
**Pull request by sidd-oo**
Signed-off-by: sidd-oo <sahoosiddharth3@gmail.com>

**Description**
This PR is related to the Optimization of the Community Page Image Carousel using a prewritten `Image` component which resides inside `src/components/image.js`, which basically uses `GatsbyImage` to render the image to generate all the sizes and formats that you need to support a responsive image. So I updated the graphQL query to return a `childimagesharp` node, then passed it to the `Image` component.

This PR updates #2172 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@sidd-oo most of the images are fine but some images like GSoC Tee and is Istio is getting cut. 

can you try to edit these images? ( if possible )

Screenshot (23)


Screenshot (25)

**Comment by l5io** [comment]
🚀 Preview for commit 3de6ec9c24f0bf527db59835c86ddaa76993896b at: https://6214dbdd2f75d98d31795cdf--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Agree with @Abhijay007 . See, if those can be fixed.

**Comment by sidd-oo** [comment]
> Agree with @Abhijay007 . See, if those can be fixed.

I tried fixing this image cropping issue with a bunch of CSS properties, especially `object-fit: contain` but couldn't able to as, after optimization of the images, some images are cropped out and can't be styled to regain the cropped part. So the possible solution in my mind is to provide some aspect ratio before the image optimization. But I am unable to do it, can somebody offer me a little help in providing aspect ratio to prevent the cropping.

Also, do tell me if there are some other better workarounds?  @Nikhil-Ladha @Abhijay007 @YashKamboj @kayceeDev

**Comment by warunicorn19** [comment]
Let's discuss this on the websites' call today.

**Comment by Nikhil-Ladha** [comment]
@sidd-oo were you able to resolve the image size issue?

**Comment by warunicorn19** [comment]
Where are we at with this @sidd-oo

**Comment by leecalcote** [comment]
@sidd-oo final check-in...

**Pull request closed without merging**
