### PR TITLE
making image responsive

### PR DESCRIPTION
**Pull request by harshit-senpai**
made the image responsive on the blog landscape 

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit bcb66ceec803373d8e38ffffbca5c5ee1b395608 at: https://648ff9d238df293209152249--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@harshit-senpai  Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Comment by harshit-senpai** [comment]
@vishalvivekm Ok i will add it there

**Comment by l5io** [comment]
🚀 Preview for commit c67addea7a054ba299467320ff5ab5052dead089 at: https://64a2fe084d751634032338f1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c67addea7a054ba299467320ff5ab5052dead089 at: https://64a3044eac33f73975fd495c--layer5.netlify.app

**Comment by Ghat0tkach** [comment]
Hey @harshit-senpai , please write the issue number so it would be easy for us to review.


Looks good to me ,however there should be some breathing space between  search-bar and the first post  

Good work by the way🚀🙌

**Comment by harshit-senpai** [comment]
> Hey @harshit-senpai , please write the issue number so it would be easy for us to review. 
> 
> Looks good to me ,however there should be some breathing space between search-bar and the first post
> 
> Good work by the way🚀🙌

yeah sure i can do that.

**Comment by l5io** [comment]
🚀 Preview for commit b3deda81e298678e71d013c5c273aec3bad42be5 at: https://64a3e011bc21f70550cde4f8--layer5.netlify.app

**Comment by harshit-senpai** [comment]
hey i am closing this pull request and making a new one there seems to be some issue with the local setup will that work @Ghat0tkach

**Comment by Ghat0tkach** [comment]
> hey i am closing this pull request and making a new one there seems to be some issue with the local setup will that work @Ghat0tkach 

Sure , no worries🙌

**Pull request closed without merging**
