### PR TITLE
Added navbar component for learn layer5

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Adding the new navbar component for learn layer5.
This is the initial design of the navbar as per Figma, changes can be done as required with time.
Also, added a temporary page `learn-ng` which can act as a home page for `learn layer5`

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
To check the component go to `/learn-ng`.

**Comment by leecalcote** [comment]
Oh, no... @Nikhil-Ladha, is this a Learn Layer5 navbar different from the mega menu navbar? // @austinogiza

**Comment by Nikhil-Ladha** [comment]
> Oh, no... @Nikhil-Ladha, is this a Learn Layer5 navbar different from the mega menu navbar? // @austinogiza

Hmm, yeah. The Figma design seems like that. And, I think up to some extent it's correct as well.
We can discuss more on this at Monday's call if we shall do so or not.

**Comment by leecalcote** [comment]
`/learn-ng` - I love it. :)

**Comment by l5io** [comment]
🚀 Preview for commit e414e7f1973e5e811f1373d78935b10ce9f6d4da at: https://609032ab04b87e00d916c535--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
@leecalcote we are good to take this in...

**Comment by leecalcote** [comment]
Good, good, good

**Pull request merged**
