### PR TITLE
Animations added

### LINKED ISSUE #5344: [UI] Add animations to a section
### Current Behavior
When the site loads we show all the content at once and there are not many animations for different components/sections of the site pages.

### Desired Behavior
Add animations to the section shown below screenshot [present on the homepage of layer5.io]. 
See the [site1](https://www.rejouice.com/) or [site2](https://brainboard.co/) for inspiration on what animation we can use.

image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Ashparshp**
**Description**

This PR fixes #5344

**Notes for Reviewers**
Added some animations.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@saurabh100ni I'm encountering a conflict. Could you assist me in resolving it?

**Comment by saurabh100ni** [comment]
@iArchitSharma , you available for the help?

**Comment by leecalcote** [comment]
Merge conflict

**Comment by leecalcote** [comment]
@Ashparshp, there's a merge conflict to address here. Will you kindly drop a link to the deployment preview with the specific page / section that you've changed?

**Comment by leecalcote** [comment]
Not quite.

**Comment by Ashparshp** [comment]
Sorry for the confusion. Can you please provide more guidance on what you need from me?

I'm really really sorry for not getting..

**Comment by sudhanshutech** [comment]
@Ashparshp ask is give some recording or  link to the deployment preview where the changes can be visible

**Comment by Ashparshp** [comment]
@sudhanshutech Thank you for your assistance!
@leecalcote Apologies for the delayed response; I was unwell and couldn't get back to you sooner.

https://github.com/layer5io/layer5/assets/150526286/4c4544c1-bd11-459a-afe8-40a66efa2a20

**Comment by iArchitSharma** [comment]
@Ashparshp merge conflict fixed, @ritiksaxena124 feedback?

**Comment by Ashparshp** [comment]
Hey @iArchitSharma, what was the issue you fixed? Just curious to learn more. Thanks!

**Comment by ritiksaxena124** [comment]
Thanks for taking up @Ashparshp 🙌
The user will scroll from top to bottom so you can reverse the effect of the title to show up not from top to bottom but from bottom to top. 

See the effect on site1 mentioned in the issue description how they are showing the title

**Comment by Ashparshp** [comment]
@ritiksaxena124 Will do! I'll reverse the title animation.

**Comment by saurabh100ni** [comment]
Hi @Ashparshp  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by Ashparshp** [comment]
Hey @ritiksaxena124,
Following your feedback, I've made some adjustments to the options we discussed. I've also explored four additional alternatives. I've attached a video showcasing these changes. Could you please review and let me know which option you prefer, or if there are any other adjustments you'd like to see implemented? Your input is greatly appreciated. Thanks!

https://github.com/layer5io/layer5/assets/150526286/dd7db096-11bd-48a3-8ab3-f3b2f0a2b308

**Comment by l5io** [comment]
🚀 Preview for commit 94f13db7790ec0e3354a334610f4e0c22bb33e30 at: https://65ca11c25289eee318113548--layer5.netlify.app

**Comment by Ashparshp** [comment]
This issue has been resolved through another PR update, so I'll go ahead and close it.

**Pull request closed without merging**
