### PR TITLE
MeshMap: fix opa-agent card

### PR DESCRIPTION
**Pull request by leecalcote**
**Description**

@debo19, while this card now only contains vector elements, it does not display in the carousel.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 2bd62c1a36af2297e502a10bfbd1a57d3c9371a9 at: https://629cb4736e0c1b46711c1720--layer5.netlify.app

**Comment by leecalcote** [comment]
@debo19, I'll hand this off to you...

**Comment by debo19** [comment]
@leecalcote I changed all cards in #2867 , we can close this PR now

**Comment by leecalcote** [comment]
THanks, @debo19. The small service mesh pattern logo is still rasterized.

**Pull request closed without merging**
