### PR TITLE
Add Kanvas-Snapshot project to repository overview

### LINKED ISSUE #5929: [Handbook] Repository Overview: Add new project - kanvas-snapshot
### Current Behavior
The [Repository Overview page](https://layer5.io/community/handbook/repository-overview) found in the Community Handbook lists most of the projects that are steward by the community and their respective GitHub repositories.

### Desired Situation
A new project with new repository has recently been created at https://github.com/layer5labs/kanvas-snapshot. An entry in the backend projects table is needed. This [repo-data.js file](https://github.com/layer5io/layer5/blob/master/src/sections/Community/Handbook/repo-data.js) provides the data used to populate the tables on the repository overview page.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Denish3436**
**Description**

This PR fixes #5929

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 19b9b93a48355ca0f223d1e3f7b5dbd403522943 at: https://670eeade06ee757d0cdb7375--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 482afb288268ac24d8f2a8046f3617cc6b9cedf7 at: https://670ef2afe217128de82771cc--layer5.netlify.app

**Review by hargunkaur286 — CHANGES_REQUESTED** [review]
Thank you for your contribution @Denish3436 
But if you read the issue description, it states that _"An entry in the backend projects table is needed"_ but I see that you have added the project in "Frontend Projects" table. Do you please mind changing the entry to the backend table?

**Comment by Denish3436** [comment]
> Thank you for your contribution @Denish3436 But if you read the issue description, it states that _"An entry in the backend projects table is needed"_ but I see that you have added the project in "Frontend Projects" table. Do you please mind changing the entry to the backend table?

Sorry  @hargunkaur286 it's my bad now i will refine it

**Comment by l5io** [comment]
🚀 Preview for commit 639bc53ad62ed5bf89bb21e1fb7bd919883f164b at: https://67144a4a08647743f1b7984e--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Denish3436 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
