### PR TITLE
feat: third meshery page 

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Tossed in a couple minor updates. More content needed.

**Comment by Tanuj22** [comment]
Icons and images need to be changed

**Comment by Nikhil-Ladha** [comment]
Is the deploy preview still failing?

**Comment by Tanuj22** [comment]
> Is the deploy preview still failing?

Yes. Check this https://layer5io.slack.com/archives/C011VPREG2Z/p1612352663028300?thread_ts=1612325427.023100&cid=C011VPREG2Z

**Comment by leecalcote** [comment]
@Tanuj22, deep breath.... 

...will you add AppMesh as the 11th logo? https://meshery.io/images/aws-app-mesh.svg

**Comment by Tanuj22** [comment]
> @Tanuj22, deep breath....
> 
> ...will you add AppMesh as the 11th logo? https://meshery.io/images/aws-app-mesh.svg

Okay. WIll get to it soon.

**Comment by leecalcote** [comment]
Screen Shot 2021-02-05 at 2 15 46 PM

Additional margin needed here.

**Comment by Tanuj22** [comment]
@leecalcote There is still an issue with the workflow. It is not checking out the changes from the PR

**Comment by leecalcote** [comment]
OOoohh

**Comment by leecalcote** [comment]
We can skip the build previews for now, if they are distracting too much time. I'll let you make this determination.

**Comment by Tanuj22** [comment]
Merging this PR so I can find a way to fix this. The changes will be visible on layer5ng.netlify.app

**Comment by leecalcote** [comment]
I'm not sure what the current issue is, but know that if a long-lived branch for a few contributors helps in the short-term, we can do that, too.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
