### PR TITLE
Projects Page: Make the services responsive

### LINKED ISSUE #3292: Projects Page: Most of the services are hidden after width is less than 550px.
#### Description
Projects Page: Most of the services are hidden after width is less than 550px.
Screenshot 2022-10-09 135740

#### Expected Behavior
Screenshot 2022-10-09 135715

#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by tinniaru3005**
**Description**
Make the service meshes part of the projects page responsive

This PR fixes #3292 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1019efd26dd3fcc4eda418a941f33c2dbaebda39 at: https://6395a74ee5a7ff66eaab4e93--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 61164085cd0b49281f8faece1df86843c69a7f71 at: https://6395b0545893fc7013a4638e--layer5.netlify.app

**Comment by tinniaru3005** [comment]
@leecalcote does it look good to you?

**Comment by leecalcote** [comment]
Here’s a recording of the page experience on  an iPhone. 

https://user-images.githubusercontent.com/7570704/206906270-d94729c6-2c00-44db-9d5e-11bc26626aa0.MOV

Notice that the logos in our project cards are top aligned and would look nicer in the vertical center. 

Notice that some of the names of projects in the grid at the bottom of the screen spill off the right hand side of their small card.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Only removing the `margin` for screen < 550px is needed. None of the other changes made in this PR is required.

**Comment by tinniaru3005** [comment]
> Only removing the `margin` for screen < 550px is needed. None of the other changes made in this PR is required.

Hey, I checked it but it is not working. I guess converting the rows and columns to div gives more flexibility on making the contents flexible

**Comment by Nikhil-Ladha** [comment]
First, I don't see the changes updated. And secondly, what do you mean by "more flexibility"? `Row` and `Col` components render a div element so what additional flexibility do you get on using `div` directly?
Secondly, the aim is not to fix the cutoff, it is only to remove that blank space at the edges for screen width < 550px.

**Comment by tinniaru3005** [comment]
> First, I don't see the changes updated. And secondly, what do you mean by "more flexibility"? `Row` and `Col` components render a div element so what additional flexibility do you get on using `div` directly? Secondly, the aim is not to fix the cutoff, it is only to remove that blank space at the edges for screen width < 550px.

Okay, I got it. I am closing this PR and opening a new one only fixing that issue. Will that be fine?

**Comment by Nikhil-Ladha** [comment]
Sure, as you deem fit.

**Comment by tinniaru3005** [comment]
> Sure, as you deem fit.

Thanks, @Nikhil-Ladha, I have not used rows and cols much. So I was not aware of it.

**Comment by tinniaru3005** [comment]
> Only removing the `margin` for screen < 550px is needed. None of the other changes made in this PR is required.

Hey can you please elaborate on how to solve it and in which class to remobe the margin. If I am removing the margin of `.project__card-container` it is looking a bit odd. May be I am not able to figure out removing marging from which class will solve the issue and make all the service mesh projects visible on all screen sizes.

**Comment by Nikhil-Ladha** [comment]
Again, as I have said it the **the cut-off is intentional, we don't need to show the service meshes at all screen sizes**, only remove the extra margin that we have for screen-width less than 550px.
Notice the white space at the edges of the service meshes section, in the below screenshot, we want to avoid that. That's it.
Screenshot from 2022-12-16 11-01-02

And, to do that you just need to remove these `margin` https://github.com/layer5io/layer5/blob/master/src/sections/Projects/Project-grid/projectGrid.style.js#L391-L392

**Pull request closed without merging**
