### PR TITLE
PR Overflow issues on Layer5 website #5231 solve

### LINKED ISSUE #5231: [Bug] Overflow issues on Layer5 website
### Description
Because of occasional Overflow issues, the Navbar isn't of complete width which needs to be fixed on [Layer5.io](https://layer5.io/)

### Screenshots
image

The width on which it is tested in chrome:
image

Width
### Environment:
- Host OS: Windows
- Browser: Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by anshitmishra**
**Description**
it just extra  margin that i remove i have check on different size of screen it solved now 

This PR fixes #5231

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Signed-off-by: Anshit Mishra <anshitmishra03@gmail.com>

### CODE REVIEW

**Comment by anshitmishra** [comment]
Screenshot 2024-01-07 134757

@saurabh100ni

**Comment by l5io** [comment]
🚀 Preview for commit 34ac4d3d9cdd2c46a07237fbcca1970cc3c62927 at: https://659a61b1b1117067e148d065--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@anshitmishra

**Comment by Yashsharma1911** [comment]
@anshitmishra thanks for jumping on it, please see the failed DCO error

**Comment by anshitmishra** [comment]
@Yashsharma1911 done 🚀🚀

**Comment by l5io** [comment]
🚀 Preview for commit c1578213e991f4b494d6bb7abfabe837f02db260 at: https://659c6053c836b21e2452f4c0--layer5.netlify.app

**Review by VamshiReddy02 — APPROVED** [review]

**Review by iArchitSharma — APPROVED** [review]
Thanks @anshitmishra

**Pull request merged**
