### PR TITLE
Improved Related posts section

### LINKED ISSUE #1166: [NG] Add related blog post section
**Desired Behavior**
Add a section of related blog posts below a single blog post. The related post are posts having the same tags
For eg. in [this](https://layer5ng.netlify.app/blog/performance-benchmarking-using-meshery-and-nighthawk) blog post, the tags are `community`, `Projects`, `News`. So 4-5 blog posts having the same tags should be shown. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by OmkarPh**
Signed-off-by: OmkarPh <omkarphansopkar@gmail.com>

**Description**
- Added caraousel

This PR fixes #1166 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by OmkarPh** [comment]
The More posts Link at end of caraousel will be improved :)

**Comment by Tanuj22** [comment]
Nice going @OmkarPh :)

**Comment by Jashpatel1** [comment]
@OmkarPh Cool work here. Please see if you could reduce the width of the carousel so as to move the arrows out or something similar.

**Comment by OmkarPh** [comment]
Ya, I'm trying that

**Review by Jashpatel1 — COMMENTED** [review]
Thanks @OmkarPh Looks good to me. Just a couple of things:
Can you change the purple color used by green/yellow used in layer5 sites?
Fix the conflicts.

**Comment by Nikhil-Ladha** [comment]
Good going @OmkarPh . Few things to add along with @Jashpatel1 points:
When we add a carousel, I suppose it's better to either only add 1 blog at a time to the view, to all the 3. Currently, it shifts 2 blogs, which I don't think is correct. 
Any comments for this @leecalcote @Jashpatel1 @Tanuj22 ?

**Comment by Nikhil-Ladha** [comment]
Also, not sure if the 3 dots below, is needed or not.
And, no need to show the `Not-allowed` pointer or whatever that is called when the carousel is at the end. It should be evident from the colors itself, is what I feel.
Suggestions are welcome :slightly_smiling_face:

**Comment by OmkarPh** [comment]
Ya, I thought 1 would be enough, but it took quite some time to reach the end, so went for 2 at a time

**Comment by OmkarPh** [comment]
> Also, not sure if the 3 dots below, is needed or not.
> And, no need to show the `Not-allowed` pointer or whatever that is called when the carousel is at the end. It should be evident from the colors itself, is what I feel.
> Suggestions are welcome 🙂

It's a part of npm library I used, I don't think I can manipulate that

**Comment by OmkarPh** [comment]
I would change colors of arrow and dots below and remove dots if you want.

I know it's a silly q, but I have to fetch upstream code and merge to my branch to resolve conflicts right..

**Comment by Nikhil-Ladha** [comment]
> I would change colors of arrow and dots below and remove dots if you want.

For removing the dots, let's wait for others inputs. Colors should be changed.

> I know it's a silly q, but I have to fetch upstream code and merge to my branch to resolve conflicts right..

Not at all silly. Good that you asked.
You will have to checkout to the `upstream/layer-ng` branch. Then do a `git fetch upstream` then you will have to update your fork as well with `git merge upstream/layer5-ng` then checkout to the dev branch and then do `git rebase origin/layer5-ng`. That should do.

**Comment by OmkarPh** [comment]
I also had this question, is using git pull upstream a good practice?

It almost seems to be working similarly..

**Comment by Nikhil-Ladha** [comment]
I don't think that matters, but not sure if there are any possible adverse effects.

**Comment by OmkarPh** [comment]
Is it ok if I remove the arrow when it is disabled?
See a demo on their website: https://sag1v.github.io/react-elastic-carousel/styling

**Comment by Nikhil-Ladha** [comment]
> Is it ok if I remove the arrow when it is disabled?
> See a demo on their website: https://sag1v.github.io/react-elastic-carousel/styling

Much better. Yes, we can do that :+1:

**Review by Jashpatel1 — APPROVED** [review]
Looks good for the first iteration. More changes can be done in another PR after logic for related posts comes up. Thanks @OmkarPh

**Comment by OmkarPh** [comment]
I was actually working on improving mobile view, it's a bit congested.
Anyways, would include that in a different PR ✌️

**Pull request merged**
