### PR TITLE
[Handbook] Fix broken link of recognition page

### LINKED ISSUE #3796: [Handbook] Recognition page
### Description
The recognition page on the handbook seems to be throwing an error.

### Expected Behavior
Fix the broken link to the [recognition page ](https://layer5.io/community/handbook/recogition)on the community handbook

### Screenshots
Screenshot 2023-02-21 at 3 46 57 AM

### Environment:
- Host OS: 
- Browser: 

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Aditya-A-G**
**Description**

This PR fixes #3796 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [&#10004; ] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@Chadha93 @leecalcote Please approve the workflow

**Comment by leecalcote** [comment]
Workflow approved.

**Comment by leecalcote** [comment]
@UtkarshMishra12, I have changed the repository setting to run workflows by default w/o need for approval now.

**Comment by leecalcote** [comment]
@Aditya-A-G thanks for this PR. Please take a moment to address the merge conflict.

**Comment by l5io** [comment]
🚀 Preview for commit b240b6917950dd383ba778696e56bd138a3e1d2e at: https://63f91010c728260ac9edd1cd--layer5.netlify.app

**Review by ayushthe1 — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit c0138cef00c10cb767055069f47fda658c280b90 at: https://63f9927cb4ccc24a9c672ae5--layer5.netlify.app

**Comment by Aditya-A-G** [comment]
Merge conflicts resolved

**Review by leecalcote — APPROVED** [review]
Thank you, @Aditya-A-G. 

Things seem to work a lot better when they get spelled right. 🤪

**Comment by Aditya-A-G** [comment]
Thank you for merging my pull request, and I'm glad I could help fix the typo. I appreciate your support of my contributions to this project.

**Pull request merged**
