### PR TITLE
community form UI improvment for progress bar and form

### PR DESCRIPTION
**Pull request by Lezette**
Signed-off-by: Elizabeth <leezeelola@gmail.com>

**Description**
Improved community form UI (CSS)
The form can be found at - /community/webform

**Notes for Reviewers**
Things remaining to be added in order to make this form fully functional

- backend connection with integromat
- storing all the fields data in the frontend

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ede7fad63d702ded9dc98a2f2d3a684b9ae7f832 at: https://6082fa5f61b2256bc1b0a501--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ede7fad63d702ded9dc98a2f2d3a684b9ae7f832 at: https://6082fa862fd4687d60eee278--layer5ng.netlify.app

**Comment by vinayaksh42** [comment]
@Lezette the preview looks good, the step-wise bar is much better now. Just one thing on the different path selection form step. Is the 2 step change of colors on the cards intentional?

**Comment by Lezette** [comment]
> @Lezette the preview looks good, the step-wise bar is much better now. Just one thing on the different path selection form step. Is the 2 step change of colors on the cards intentional?

Yes it is

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Few changes:
- Dropdown needs to be modified to look better. The arrow is off, and the dropdown should either have a curved border or the selector itself should not have.
- The text `Ok` beside the `checkbox` is not aligned properly.
- The font size for the text inside the input field needs to be increased.
- Why isn't there a `Previous` and `Next` button on the second step of the form. And, that animation is overkill on that card. The single color transition is enough, and the time needs to be reduced too.
- The required fields are not actually "required" as of now.

On a second note, will this PR not cover the leftover items if not then why or who will do it?

**Comment by Nikhil-Ladha** [comment]
Also in mobile view,
- The `step-wise` bar breaks
- The `next` and `previous` buttons are not center aligned.

**Comment by Lezette** [comment]
On it

**Comment by Lezette** [comment]
> Few changes:
> 
> * Dropdown needs to be modified to look better. The arrow is off, and the dropdown should either have a curved border or the selector itself should not have.
> * The text `Ok` beside the `checkbox` is not aligned properly.
> * The font size for the text inside the input field needs to be increased.
> * Why isn't there a `Previous` and `Next` button on the second step of the form. And, that animation is overkill on that card. The single color transition is enough, and the time needs to be reduced too.
> * The required fields are not actually "required" as of now.
> 
> On a second note, will this PR not cover the leftover items if not then why or who will do it?

@Nikhil-Ladha I was hoping to do that in another PR since I currently don't know how the backend is connected

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I was hoping to do that in another PR since I currently don't know how the backend is connected. Also please do you have any tip on how to make those form fields required because using just required isn't working

For the blackened part, even I am not sure. @leecalcote how did you set up the google form, to pass the data to Integromat?

And, required isn't working because you are technically not submitting the form anywhere so that it will prevent you from doing so, you are simply moving to the next page using the `Next Step` button, which is always allowed.

**Comment by l5io** [comment]
🚀 Preview for commit 17db4822bd5b3cb0890c72b9a102bcb1296371cd at: https://60895510a3f38a0be9dc9ed1--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Few of the issues highlighted above are still left.
I wonder this combination looks better on the cards:
Screenshot from 2021-04-28 18-07-31
Also, the `Next Step` on the 2nd page seems to be broken.

**Comment by Lezette** [comment]
@Nikhil-Ladha this actually looks better, can I get the color code used? also the I think I'll remove the `next step` on the second section because it actually doesn't have a use, once the user selects their option they're taken straight to the next step based on the selection. Also, I think I'll change the next step function for each step to work on validation

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha this actually looks better, can I get the color code used? also the I think I'll remove the `next step` on the second section because it actually doesn't have a use, once the user selects their option they're taken straight to the next step based on the selection. Also, I think I'll change the next step function for each step to work on validation

The color code is the same which you are using currently for the cards background color. Just in case of 'non-hover' scenario, I have reduced the transparency of the same. And, on hovering the background color is updated to that color.

**Comment by vinayaksh42** [comment]
> > @Nikhil-Ladha I was hoping to do that in another PR since I currently don't know how the backend is connected. Also please do you have any tip on how to make those form fields required because using just required isn't working
> 
> For the backend part, even I am not sure. @leecalcote how did you set up the google form, to pass the data to Integromat?
> 
> And, required isn't working because you are technically not submitting the form anywhere so that it will prevent you from doing so, you are simply moving to the next page using the `Next Step` button, which is always allowed.

@Nikhil-Ladha I will connect this web form to integromat using webhooks (same as the /deploy-service-mesh form)

**Comment by l5io** [comment]
🚀 Preview for commit 10b693a6d5d40e46c3f36626bbc66c57521b2aff at: https://608b5a0232fa5600a1fd07d1--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Hi @Lezette, will you kindly have another look at the flow and questions in the design in Figma?

It seems that the Last Name field needs to be set to required.

**Comment by l5io** [comment]
🚀 Preview for commit 4227e4922315716000965d43f62e9a4b1288f4e0 at: https://608c2460e0366234e3ecf41d--layer5ng.netlify.app

**Comment by Lezette** [comment]
Hello @Nikhil-Ladha, I noticed a bug with the form using chrome. When I type a character into the form, it loses focus, I think this is because of useState rerendering the component. I have tried several things and it still doesn't work, Have you ever encountered such issue before?

**Comment by Nikhil-Ladha** [comment]
> Hello @Nikhil-Ladha, I noticed a bug with the form using chrome. When I type a character into the form, it loses focus, I think this is because of useState rerendering the component. I have tried several things and it still doesn't work, Have you ever encountered such a bug before? I'm thinking it has to do with the fact that the components are in one file and they are maybe interfering with each other, do you think I should rearrange the components into different files?

I don't think it's chrome specific. The issue is that you have added this attribute to the `<input>` elements `value={formData.<field>`, and what this does is that whenever it gets updated it resets the value of the `<input>` field, based on the value it has, hence you are losing focus because the component is rendered again on doing so.

**Comment by Lezette** [comment]
Okay thanks! I'll remove it

**Comment by adithyaakrishna** [comment]
@Lezette Any update here?

**Comment by Lezette** [comment]
> @Lezette Any update here?

Hi not yet. Waiting for some UI but I’ll make some changes this weekend

**Comment by l5io** [comment]
🚀 Preview for commit f606feecf6ae334fc87b5537e12e83673ba97467 at: https://60bccb78a151b694465ee9ba--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0c08af95df0445b7401f10709da60b5369038d98 at: https://60bcd37f17675113bbfd6783--layer5ng.netlify.app

**Comment by Lezette** [comment]
@leecalcote  I have updated the changes I remember you saying during the meeting, can you check and let me know if there's any other thing I need to change or direct me to a UI?

**Review by Anita-ihuman — COMMENTED** [review]
- I think the Layer.io/community link should appear as a link.
Screenshot 2021-06-28 at 11 16 58
- These input boxes look really big and excessively long. 
Screenshot 2021-06-28 at 11 24 28
- The contributor's path also need some questions on what tutorials that they would like to receive to help them on their path
- Also there should be a provision for subscribing to the mailing list
- Contributors need to be asked if they would like a MeshMates too

**Comment by leecalcote** [comment]
All, @vinayaksh42 has been positively reflecting on the work here and suggests that we merge as-is, understanding another PR or two will ensue, but at least doing so moves us along and unblocks other aspects of the automation behind the form. Since the form isn't linked to from anywhere, it doesn’t hurt to merge.

**Pull request merged**
