### PR TITLE
Update member status to inactive

### PR DESCRIPTION
**Pull request by Ashparshp**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 51737f3f3d12c70e4f92231f5c0999c79ad9c52b at: https://66b8c0422c58d158e723cb68--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@Ashparshp 
will you transition Dahyeon Kang to inactive as well ?

**Comment by Ashparshp** [comment]
@vishalvivekm Yes..

**Comment by vishalvivekm** [comment]
> @vishalvivekm Yes..

Thank you, I think saw it's done.

**Comment by Ashparshp** [comment]
@vishalvivekm, Yes, it's!

**Pull request merged**
