### PR TITLE
Added Community Member Shravani Kaware

### LINKED ISSUE #4938: [Community] Member Profile: Shravani Kaware
**Current Behavior**

@ShravaniAK has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ShravaniAK as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @ShravaniAK
- Twitter: [@ShravaniKaware](https://twitter.com/ShravaniKaware)
- LinkedIn: [in/shravani-kaware-b3620022a](https://www.linkedin.com/in/shravani-kaware-b3620022a/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by malaviya-parth**
**Description**

This PR fixes #4938 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d4263236ca64b7507bad38f9d51cc53589942fa3 at: https://650d6c34da78163378326a3a--layer5.netlify.app

**Review by ShravaniAK — APPROVED** [review]

**Review by abhijeetgauravm — APPROVED** [review]
LGTM! Thanks for the contribution @malaviya-parth

**Comment by l5io** [comment]
🚀 Preview for commit f87843fe53b0abd254ee386cfb70c990be2635b9 at: https://650e37a579d05858f26fc262--layer5.netlify.app

**Review by Chadha93 — APPROVED** [review]
Lets go @ShravaniAK :clap:

**Pull request merged**
