### PR TITLE
improve smoothness of scroll-to-top transition issue #5243

### PR DESCRIPTION
**Pull request by Ashparshp**
**Description**
I changed the constant value from 16 to 8 in the formula const translateY = scrollPosition / 8;. This modification seems to have significantly improved the smoothness and reduced lag.

This PR fixes #
Remove delay / improve smoothness of scroll-to-top transition https://github.com/layer5io/layer5/issues/5243

**Notes for Reviewers**
[Video.webm](https://github.com/layer5io/layer5/assets/150526286/2503b85e-4ad1-4e0c-b0b3-b3c7767bf039)

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ffbb0cce28bfc3d152ca55d23e57f45427441a14 at: https://6594749a7a8e950ca4fd7f8a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit d6c28a4bc34dae691ee78f77225fbf67c90fbf47 at: https://659517ccb0759372e382f9c0--layer5.netlify.app

**Comment by leecalcote** [comment]
Yes, I do see the same issue in Safari still. I believe the issue is in part caused by the top banner bar. I try to capture this in the recording, which demonstrates a glitch when the top banner comes into play.


https://github.com/layer5io/layer5/assets/7570704/46ad0bf1-358e-4c31-8485-f89dc9d31fa3

**Comment by saurabh100ni** [comment]
@Ashparshp Let us know If you are still working on this, if not, then we can open this for new contributors.

**Comment by Ashparshp** [comment]
Hi @saurabh100ni , I'm currently unable to address the issue in Safari as I don't have access to it. Please feel free to unassign me, and if someone with Safari access is available, they can take over. Thanks!

**Comment by narasimha-1511** [comment]
i have access to safari i will take over from here

**Comment by Ashparshp** [comment]
@narasimha-1511, could you kindly request @saurabh100ni to assign you to this task before you begin working on it? Thanks!

**Comment by narasimha-1511** [comment]
@saurabh100ni  can you please assign me this issue..

**Comment by iArchitSharma** [comment]
As the animation for the hero image has been changed, I am closing this PR

**Pull request closed without merging**
