### PR TITLE
Commenting out those categories which don't have any itegrations now 

### LINKED ISSUE #3340: [Meshery] Integrations: Do not show empty categories
**Current Behavior**
A list of Meshery integrations is displayed in a honeycomb-like grid of cells. These integrations are categorized. [Categories](Some categories have zero integrations. ) are displays and available for users to use as filters. Some categories have zero integrations. 

Screen Shot 2022-10-16 at 9 56 22 PM

**Desired Behavior**
Empty categories should not be displayed. Integrations will be added in the future.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**
Fully dynamic code which removes the need of manually storing the list of categories, which was earlier stored up.
eg:- 

`
    let [categoryList, setCategoryList] = useState([

    { id: 1, name: "All", isSelected: false },

    { id: 2, name: "Platforms", isSelected: false },
`

This PR fixes #3340

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you. Better yet, leave the categories included, but add logic to not display them unless they contain one or more published:true integrations.

**Comment by legendarykamal** [comment]
> Thank you. Better yet, leave the categories included, but add logic to not display them unless they contain one or more published:true integrations.

oh yes @leecalcote this was a potential fix , that could be even better 👍

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please leave categories uncommented, but update GraphQL query not to display categories w/zero published entries.

**Comment by l5io** [comment]
🚀 Preview for commit 12115ba1df3ea59798648e81dae7ca303035ca26 at: https://634f069823e5ea2d32307405--layer5.netlify.app

**Comment by sahilsuman933** [comment]
You can solve this problem by fetching the category from the GraphQL query. We already use this to display the Integration. So, you can directly use the `IntegrationList` variable and grab all the categories from them. After grabbing all the categories, you need to filter those data and remove the duplicate category name. 

Now you need to make an object similar to the `categoryList` in this format `{id: 1, name: "category name that you got from the integration", isSelected: false}` after this update categoryList using useState. This will solve this problem. 

Note: Use ` { id: 1, name: "All", isSelected: false }` as the initial value of the categoryList. As we need `ALL` category too. 

If you need some additional help, then feel free to DM me :) 

// @legendarykamal

**Comment by legendarykamal** [comment]
thankyou for the heads up but why are you mentioning about removing duplicate category names, 

I am currently trying to modify the filter itself.

**Comment by l5io** [comment]
🚀 Preview for commit c1e1f04f21c4445e110bbe2d5d2df295080f0c4d at: https://634f8314d01977454d01152c--layer5.netlify.app

**Comment by sahilsuman933** [comment]
The approach you are using won't help you fix this problem. 

I am telling you to remove the duplicate category because when you fetch the type from the `IntegrationList` variable you will see many identical category names, as multiple integrations can belong to one category. 

// @legendarykamal

**Comment by sahilsuman933** [comment]
The approach you are using won't help you fix this problem. 

I am telling you to remove the duplicate category because when you fetch the type from the `IntegrationList` variable you will see many identical category names, as multiple integrations can belong to one category. 

// @legendarykamal

**Comment by legendarykamal** [comment]
Ok makes sense @sahilsuman933 .

**Comment by legendarykamal** [comment]
@sahilsuman933 I used your suggestion and messed for some time with filtering but eventually solved it :) .
Up for review @leecalcote @sahilsuman933 .

**Comment by l5io** [comment]
🚀 Preview for commit e3f107195a0a7d92a10da9da8813f1641fdd6bb3 at: https://634fcd9c424851007da48f64--layer5.netlify.app

**Comment by sahilsuman933** [comment]
@legendarykamal could you please clean up the code by removing console log and the category filter that you added in GraphQL query.

**Comment by sahilsuman933** [comment]
Also, set `isSelected:true` for All category.

**Comment by l5io** [comment]
🚀 Preview for commit 70297a270f066ed25a3da00613af2a1033a174a4 at: https://634fff4a947a640f977833e8--layer5.netlify.app

**Comment by sahilsuman933** [comment]
Can you please add one more condition that the category should not be equal to null because of that, we are getting this 
image

**Comment by l5io** [comment]
🚀 Preview for commit fbb79c37cf72cca6837322220751570d9ba21ae0 at: https://635006a37c99961b63c00967--layer5.netlify.app

**Comment by legendarykamal** [comment]
@sahilsuman933 I saw that already , But considering that every integration will be in 1 or othe other categories,
I found here that `istio` didn't had any category which should have been `service mesh` hence included it in a recent PR .

**Comment by sahilsuman933** [comment]
Then we are good to merge this PR @legendarykamal 🚀

**Pull request merged**
