### PR TITLE
Fixing the Line height issue in Five and Friends CTA

### LINKED ISSUE #4915: [Community] Line height issue in Five and Friends CTA
### Description
This new Call to Action (CTA) is displayed on one or more pages, including the [community page](https://layer5.io/community). It is in need of some fine-tuning. 

Screenshot 2023-09-15 at 11 31 01 AM

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by VamshiReddy02**
**Description**

This PR fixes #4915

**Notes for Reviewers**
I reduced the "line-height" in Five and Friends CTA. Please let me know if there are any changes to be made.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d3b5a8f1abd85e8f6fc1e8d909f51f2cf63fc37d at: https://6505784fe9886275e5e70962--layer5.netlify.app

**Review by abhijeetgauravm — APPROVED** [review]
Looks Good!

**Comment by Ghat0tkach** [comment]
hey @VamshiReddy02 
Let's discuss it on the websites call.
I have already added your agenda as part of today's meeting minutes

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by VamshiReddy02** [comment]
Hey @Chadha93, and @leecalcote, can you review this PR, and let me know of any changes?

**Review by leecalcote — APPROVED** [review]
Good! Thanks, @VamshiReddy02

**Pull request merged**
