### PR TITLE
corrected carousel slider disable property #5115

### LINKED ISSUE #5115: Carousel slider button dissable property is not proper
### Description
Carousel right slider button disable property is not working properly after reaching the end of carousel in project page

### Expected Behavior
Should be disabled after reaching the end of the carousel 

### Screenshots
Screenshot 2023-11-12 at 1 00 20 PM

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by balagowda**
fixes carousel slider disability

This PR fixes #5115 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a70f3f3ea5bf5749d044e0c659e18aa2f8ed8cf2 at: https://655091569a84fd571a8cf5e6--layer5.netlify.app

**Comment by captain-Akshay** [comment]
LGTM! @balagowda

**Review by abhijeetgauravm — APPROVED** [review]
Looks good! Thanks for the contribution @balagowda

**Comment by balagowda** [comment]
Thanks for the opportunity 🚀

**Pull request merged**
