### PR TITLE
Higlighted selected handbook menu item

### LINKED ISSUE #2075: Merge the Handbook  and side menu
**Description**
Currently,  the handbook has a first page that makes it hide the main content of the handbook. 

**Expected Behavior**
- We need the handbook header and the side menu to appear on the same page, while users navigate the items on the side menu. 
- Also, the selected menu should be highlighted and bold upon selection.
**Screenshots**
Screenshot 2021-08-11 at 21 15 32

**Enviroment:**
- Host OS: 
-o help explain your problem. -->Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by kg-kartik**
**Description**
Highlights selected menu item in handbook side navbar

This PR fixes #2075

### CODE REVIEW

**Comment by leecalcote** [comment]
@kg-kartik heads up - you'll want to sign-off on your commits. To do so for this PR, execute these commands - https://github.com/layer5io/layer5/pull/2150/checks?check_run_id=3499128885

**Comment by l5io** [comment]
🚀 Preview for commit bf2d8e53a44140d60fab846af443dc9ea3651b44 at: https://61311e1521e0dd00e3a0e58c--layer5ng.netlify.app

**Comment by kg-kartik** [comment]
I have signed off on my commits

**Comment by l5io** [comment]
🚀 Preview for commit 318129a7ad0541a93f051e0aeee3f6d84e4bbfc8 at: https://6131e62dbac5ddecbfaf37cd--layer5ng.netlify.app

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@kg-kartik could you please change the active color to light keppel green, i.e., the color it becomes on hover.

**Comment by l5io** [comment]
🚀 Preview for commit fb6ffc56133638e4685a280f6afcf3ba16d0afb7 at: https://61320bd2a4f021252d43ae46--layer5ng.netlify.app

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thanks @kg-kartik

**Review by Tanuj22 — APPROVED** [review]
Thank you @kg-kartik

**Pull request merged**
