### PR TITLE
Adding community manager

### LINKED ISSUE #3159: [Community] Members: Add "Community Managers" as a role
#### Current Behavior
This profile filter on https://layer5.io/community/members is missing the "Community Managers" role.

Screen Shot 2022-09-07 at 9 33 29 PM

#### Desired Behavior
1. Ensure a new selection is available and filters on CM profiles.
1. Use  the three-person, green community badge as the icon.

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by sam1code**
**Description**

This PR fixes #3159

**Notes for Reviewers**
1. Now if any one want to add the community manager they just need to write the line "community_manager: yes" in the index file of member profile.
2. There is no community_manager profiles added for now, so if you want to give the community manager rules to some then you can add the above line to existing ones.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit c9b25d0abf56eff0b03776fff81ccfa422db175b at: https://631cbc0d75384563701e37d3--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f8ff6d65d50fe176d6bdf6011889d16fb41757e1 at: https://631f673e10486845ec65d560--layer5.netlify.app

**Review by legendarykamal — CHANGES_REQUESTED** [review]
Just to ensure that everything is working smoothly please add  @leecalcote as a community manager and lets see everything works out nicely .

**Comment by legendarykamal** [comment]
@sam1code  
It would be good to replace this with Community Manager instead of CM profiles 

image

**Comment by sam1code** [comment]
Ok @legendarykamal actually I was also thinking the same but from the above issue message I made this...
I'm changing in a moment will update in 5-10 minutes

**Comment by l5io** [comment]
🚀 Preview for commit f20eea81558dec84d7e26beafa9d795dc177e073 at: https://631f8368a25d585efb70c527--layer5.netlify.app

**Comment by sam1code** [comment]
@legendarykamal please review it and please proceed before it get conflict

**Comment by legendarykamal** [comment]
> Just to ensure that everything is working smoothly please add @leecalcote as a community manager and lets see everything works out nicely .

Would have been helpful if you had done this, 
Anyways I had to manually test and yes everything works pretty well. 

image

**Review by legendarykamal — APPROVED** [review]
> Just to ensure that everything is working smoothly please add @leecalcote as a community manager and lets see everything works out nicely .

Would have been helpful if you had done this, 
Anyways I had to manually test and yes everything works pretty well. 

image

**Comment by sam1code** [comment]
Thankyou @legendarykamal and also sorry actually I don't know about the role 😅 like who are actually the CMs

**Comment by sam1code** [comment]
I hope it can be merged now!

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Pull request merged**
