### PR TITLE
CI: Site preview

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@Tanuj22 any idea why the second workflow is not starting after one of the workflow finishes?

**Comment by Tanuj22** [comment]
> @Tanuj22 any idea why the second workflow is not starting after one of the workflow finishes?

It needs to be merged first? Should I merge this?

**Comment by Nikhil-Ladha** [comment]
Oh, so if we merge and then I modify both the workflows then it should work, right?

**Comment by Nikhil-Ladha** [comment]
Or, again it will work after a merge?

**Comment by Tanuj22** [comment]
Not sure

**Comment by Nikhil-Ladha** [comment]
> Not sure

Okay, let's merge then we can check that..

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
