### PR TITLE
moazzam07/update handbook

### LINKED ISSUE #2153: [Handbook] Update the Repository Overview, Projects, & Mentorship Programs
**Current Behavior**
These sections are missing some content from the newly updated Handbook draft.

**Desired Behavior**
Update the Repository Overview, Projects & Mentorship Programs section with the details from the [new draft](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit#heading=h.vtdtai5j3tq7) of the handbook.

---
**Screenshots / Mockups**

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by moazzam07**
**Description**

This PR fixes #2153 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — COMMENTED** [review]
@moazzam07  you need to sign off the last commit also to pass the DCO, you should not directly delete(modify) readme from Github.

**Comment by l5io** [comment]
🚀 Preview for commit 8e00f009790226d39492e7103f6d010a09c000ec at: https://614cbf5d644fdb00a2bba7d5--layer5ng.netlify.app

**Comment by moazzam07** [comment]
@Chadha93 that was a mistake I mistakenly add readme file

**Comment by moazzam07** [comment]
@Chadha93 what should I have to do

**Comment by warunicorn19** [comment]
https://github.com/layer5io/layer5/pull/2216/checks?check_run_id=3690975581 try following this to signoff your commit now.

**Comment by moazzam07** [comment]
it is showing something like this
image

**Comment by Chadha93** [comment]
@moazzam07 you can also use `git reset Head~` to remove your last commit and push new changes from your branch or revert your commit (if the commit is not required).

**Pull request closed without merging**
