### PR TITLE
Code syntax highlighting for sistent components

### LINKED ISSUE #5534: [Sistent] Code syntax highlighting for sistent components
### Current Behavior

Currently, the code shown for [sistent components](https://layer5.io/projects/sistent/components/button/code), is rendered as plain-text. 

### Desired Behavior
The JSX syntax should be highlighted.

### Screenshots / Mockups

Existing UI:
Screenshot 2024-05-12 at 14 22 07

### Implementation

we can utilize existing libraries for it.

### Acceptance Tests

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by mannika763**
**Description**

This PR fixes #5534

**Notes for Reviewers**
Before 
image

After
image
image

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit b535cf991a71408816da5d95196a9acc9f9bd360 at: https://66901d61127f7223902beba3--layer5.netlify.app

**Comment by hargunkaur286** [comment]
@mannika763 It shouldn't use white colour for dark theme.

**Comment by mannika763** [comment]
@hargunkaur286 react-syntax-highlighter provides this type of color for the dark theme. i just want to confirm if that is okay?
image

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@mannika763 we don't want to use a another package, There is a package already that prism-react-render. Use this reusable [component](https://github.com/layer5io/layer5/blob/5ce57850f50a946655b2f1ad766861aa0294fe94/src/components/CodeBlock/index.js) here and see how it looks, pass the correct language props.

**Comment by mannika763** [comment]
Hey @sudhanshutech 
I have made the necessary changes, but I am getting an error while pushing. Can you please help me with that?
image

**Comment by sudhanshutech** [comment]
i am not getting this issue, and you are pulling not pushing

**Comment by l5io** [comment]
🚀 Preview for commit 0c58839340a9d98eb9f51d4a43b5d4ed0386e06f at: https://6692c7a42ae3bd6bd03aa118--layer5.netlify.app

**Comment by sudhanshutech** [comment]
@mannika763 its your internal issue you are facing, this particular package is already upgraded. You can try to reclone the repo and make a new pr as per my suggestion

**Comment by mannika763** [comment]
okay, i'll try this.
Thanks

**Pull request closed without merging**
