### PR TITLE
Fix: #3693 [Meshmap] "save time with patterns" section

### LINKED ISSUE #3693: [MeshMap] Issues with spacing in "Save time with patterns" section
A few padding / spacing issues in mobile view:

Screenshot 2023-02-03 at 3 32 53 PM

The line height / padding between lines is a bit too much in small to medium window sizes. Please reduce the whitespace.

Screenshot 2023-02-03 at 3 34 52 PM

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/3690#issuecomment-1416427185_

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**

This PR fixes #3693 
Changed some CSS in the 'Save time with Patterns section"

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 1882adcb706c6c651b5c89f2265b3c72b0082dfc at: https://63e37c1259d7db151059d9f4--layer5.netlify.app

**Review by Shivam-AfA — COMMENTED** [review]
@ritiksaxena124 There is still the issue of font too small and too much space on medium sized screens. 
image

**Comment by ritiksaxena124** [comment]
Hey, I have made some changes, please have a look, and If it looks good then I will make a PR. 

Screenshot from 2023-02-10 01-03-39

Screen shot taken when Screen Size (656 X 726)

**Comment by Shivam-AfA** [comment]
@ritiksaxena124 the mobile view sure looks good. Nice work here. Speaking of the medium sized screens, it was not causing problem on the resolution that you have mentioned. Best is to open a PR, so that a dynamic preview is rendered.

**Pull request closed without merging**
