### PR TITLE
Moved background image to category section

### LINKED ISSUE #684: [Landscape] Move background image to behind the Categories table.
**Current Behavior**

Currently, there is a background image behind the service mesh timeline.

Screen Shot 2020-08-27 at 9 06 27 PM

The colors of the timeline and the background image overlap too much, causing them to conflict.

**Desired Behavior**
This background image should be relocated to the section below the timeline, the Categories section. This image should show up behind the table in this section.

Screen Shot 2020-08-27 at 9 09 33 PM

### PR DESCRIPTION
**Pull request by SkyC0der**
Signed-off-by: Emmanuel Ezenwigbo <emmanuelezenwigbo@gmail.com>

**Description**

This PR fixes #684 

**Notes for Reviewers**
Moved the background image in the landscape page to the category section of the landscape page

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ruth-ikegah** [comment]
Nice work @SkyC0der

**Comment by leecalcote** [comment]
Haha! 😎 @SkyC0der

**Comment by SkyC0der** [comment]
Thank you @leecalcote  and @Ruth-ikegah :-)

**Comment by Ruth-ikegah** [comment]
Congratulations on you first PR @SkyC0der  you can join our slack channel too and solve more issues

**Pull request merged**
