### PR TITLE
[NG] SEO Updates

### LINKED ISSUE #1395: [NG] SEO Mechanics and Process
### [NG] SEO Mechanics and Process

The website needs to espouse the culture and values of Layer5 and it needs to attract, serve, and sell to visitors. Visitors come in different forms:

1. Contributors evaluating and participating in our community.
1. Adopters evaluating and using our projects.
1. Customers evaluating and using our products.

#### Goal: Attracting visitors
Layer5.io should be the epitome of where people find helpful service mesh resources. Ultimately, thousands of pages need to be created in order to realize this vision. Search Engine Optimization and visitor analytics will be important. A thoughtful approach to facilitating the sourcing of this content will be important.

#### Objectives

1. Consider for search engine optimization. 
1. Use maximally efficient information architecture to improve domain authority and domain relevance for service mesh technology keywords.
1. Ensure framework adheres to SEO best practices, so that content contributors follow these guidelines.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Jashpatel1**
Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>

**Description**

This PR fixes #1395

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Looking good so far.

**Comment by leecalcote** [comment]
@Jashpatel1 I may not be reading this correctly, but to be sure, here's our desired situation:

- each page has the same favicon specified - the "5" icon
- each page has a the following meta tags, specific to the page content:

```
<meta property="og:title" content="LAYER5 PAGE SPECIFIC SHORT DESCR">
<meta property="og:description" content="LAYER5 PAGE SPECIFIC LONG DESCRIPTION">
<meta property="og:image" content="LAYER5 PAGE SPECIFIC IMAGE">
<meta property="og:url" content="LINK TO PAGE">
<meta name="twitter:card" content="SOCIAL IMAGE FOR TWITTER, USUALLY SAME AS OG:IMAGE">
```

- if specific page image isn't specified, a default Layer5 logo (src/assets/images/layer5/layer5-tagline/png/layer5-tag-dark-bg.png) should be used.

Do review the current layer5.io site's meta tags. They are pretty well done.

Test out a few of the individual pages with the Twitter Card Validator - https://cards-dev.twitter.com/validator and the LinkedIn Post Inspector - https://www.linkedin.com/post-inspector/

Every page should have an image loading, ideally an image unique to that page.

**Review by leecalcote — DISMISSED** [review]
Approving so that you can test these changes out, if needed, Jash.

**Review by Nikhil-Ladha — DISMISSED** [review]

**Comment by Nikhil-Ladha** [comment]
Aahh...there is a conflict @Jashpatel1

**Comment by Jashpatel1** [comment]
@Nikhil-Ladha @Tanuj22 can you merge this?

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
