### PR TITLE
Update CODE_OF_CONDUCT.md

### LINKED ISSUE #5766: Update Code_Of_Conduct.md
## Enhance Code of Conduct
The current CODE_OF_CONDUCT.md file requires updates to better reflect our community standards. This pull request aims to improve the code of conduct, ensuring a more inclusive and respectful environment for all contributors.

### Expected Changes

    Revise the code of conduct to align with industry best practices
    Clarify expectations for behavior and communication
    Add or remove sections as necessary to ensure comprehensive coverage

Reference
Please review the current CODE_OF_CONDUCT.md file: 
image

### PR DESCRIPTION
**Pull request by Swarnim114**
closes #5766 
**Description**
This PR updates the Layer5 Community Code of Conduct to improve clarity, structure, and accessibility. It addresses #[issue number] by enhancing the presentation and content of our community guidelines.

**Changes include:**
- Restructured the Code of Conduct for better readability
- Added more detailed information on reporting violations
- Clarified community expectations and commitments
- Improved formatting and organization of the document
- Updated links to reporting channels

**Notes for Reviewers**
Please review the changes to ensure they align with Layer5's values and community standards. Pay particular attention to:
- The clarity of language used
- The completeness of reporting procedures
- The overall tone and inclusivity of the document

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a5ba58b1a5a14d5e6eaba94c595869f889ff0176 at: https://66aca08695b597ff92e46a9a--layer5.netlify.app

**Review by Ashparshp — APPROVED** [review]
Nice enhancement! Thank you @Swarnim114!

**Comment by Ashparshp** [comment]
@Swarnim114 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Swarnim114** [comment]
> @Swarnim114 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

Do i need to be there on the call? (the time conflicts with my college hours)
can i still add this as an agenda if i cant attend?

**Comment by Ashparshp** [comment]
@Swarnim114 Aren't you available this evening at 5:30 PM IST?

**Comment by Swarnim114** [comment]
Hey @Ashparshp, can't make it . Bad timing on my end. Sorry!

**Comment by Ashparshp** [comment]
@Swarnim114 No sweat! Thanks for sending words..

**Comment by sudhanshutech** [comment]
@Swarnim114 please do join our next website meet on monday to discuss this item .

**Pull request closed without merging**
