### PR TITLE
fix: #5120 Fixed Uneven Size Of Cards in Community Page

### LINKED ISSUE #5120: Uneven Height of Cards in the Community Page
### Description
The Two Cards At the Bottom of the page are of not the same height

### Expected Behavior
Expecting the two cards to be in the same size.

### Screenshots
Screenshot 2023-11-13 205139

### Environment:
- Host OS: Windows 11
- Browser: Google Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Raj100679**
**Description**
I have fixed uneven size of cards in community page

This PR fixes #5120 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Raj100679** [comment]
@abhijeetgauravm Signed off commits, Thanks.

**Comment by l5io** [comment]
🚀 Preview for commit b4f8ab041eeb7b9d293073e90d75e42255aa97ce at: https://655e6793d54de970324e30d7--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
Looks good! However please refrain from creating direct PRs without getting assigned first .

**Review by hirentimbadiya — COMMENTED** [review]
@Raj100679, please make sure that issue is assigned to you before creating a PR

**Comment by abhijeetgauravm** [comment]
Hey @Raj100679  Let's discuss this on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Raj100679** [comment]
@abhijeetgauravm  I am travelling today, can’t attend the meeting

**Comment by Raj100679** [comment]
@abhijeetgauravm , Is this issue resolved or needs work?

**Comment by leecalcote** [comment]
Looking good, @Raj100679 👍

**Pull request merged**
