### PR TITLE
Repository update

### PR DESCRIPTION
**Pull request by Debaditya-Som**
Updating the repository

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
@Debaditya-Som ??

**Comment by l5io** [comment]
🚀 Preview for commit 5d114e9a4f61bfba9f58737257dae66d5d9f7555 at: https://64d65beb16cca67cb4ac70f6--layer5.netlify.app

**Comment by goldfishdolphin** [comment]
@Debaditya-Som can you please explain your pull request?

**Comment by thisiskaransgit** [comment]
I'll be closing this @Debaditya-Som, I hope this was unintentional and you did not mean to open an empty PR

**Comment by Debaditya-Som** [comment]
I tried to sync my own repo and maybe it created a PR. It was unintentional. Sorry for the inconvenience

**Comment by thisiskaransgit** [comment]
@Debaditya-Som no worries, hiccups happen. You've cloned the Repo which shows you're interested in making an impact. I  encourage you to join our [slack.layer5.io](https://slack.layer5.io/) community and we'll help you by providing the newcomer resources that will kickstart your journey. The community has helped many newbies to get started with open-source contributions.

**Pull request closed without merging**
