### PR TITLE
Updated Hacktberfest event. 

### LINKED ISSUE #881: [Programs] Schedule another Hacktoberfest meetup
**Current Behavior**
Each Thursday this month, the Layer5 community will host a Hacktoberfest meetup at the Newcomers call.

**Desired Situation**
A new Hacktoberfest meetup (akin to this one - https://organize.mlh.io/participants/events/4796) should be scheduled for each Thursday.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by tripathyprateek**
**Description**

This PR fixes #881 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by jesuslerma — DISMISSED** [review]
LGTM!

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@tripathyprateek 😄

**Comment by tripathyprateek** [comment]
The only thing I can see that went wrong is possibly my VS Code didnt recognise paragraphs properly. I had only updated the links and added a line regarding new rules in Hacktoberfest from my side.

**Comment by leecalcote** [comment]
@tripathyprateek, understood. No sweat. That makes sense. Thanks much for this update.

**Pull request merged**
