### PR TITLE
Fixing #2714 Issue

### LINKED ISSUE #2714: [UX] Visual Design: call to action for Docker Extension
#### _Note: This issue can be broken into two issues, if needed._

**Current Behavior**
[Docker Extension for Meshery](https://layer5.io/docker-extension-meshery) is a forthcoming extension to Meshery.

**Desired Behavior**
A new call to action (find an example of what a CTA is on this page - https://layer5.io/learn/service-mesh-books/service-mesh-patterns)

**Implementation**
1. Visual design of the call to action using elements from Layer5's asset library in Figma projects and the community shared drive.
1. Implementation of the new call to action. 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by SURAJITSHAW**
Description
I add maintainer section as others also had the section and set the value as 'true'. I think this will fix the issue.

This PR fixes #2714
[Community] Rudraksh Parekh as a maintainer

Notes for Reviewers
I don't know much about contributions, So if you find anything imappropritate please let me know.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by debo19 — CHANGES_REQUESTED** [review]
@SURAJITSHAW Can you please follow the same order given in [Community Member Profile template](https://github.com/layer5io/layer5/tree/master/src/collections/members/_member-profile-template). 
I noticed this issue was already assigned to someone else, if you solve already assigned issues they might be working on it and their effort would go to vain. Please make sure to comment under the issues you want to solve hereafter so that we can assign them to you if no one else is working on it already.

**Comment by SURAJITSHAW** [comment]
@debo19 thank you for your feedback, from here on  I'll follow your instructions. But I had a question if I wanna to change few things in a particular file I had to clone whole reprositary in my local machine. Is there any way to just clone a particular file and change it, then how could I do the pull request. I actually watching a lot of videos but didn't understand anything. So could you please help me. And also this time I make the changes in github with a editing option.

**Comment by debo19** [comment]
@SURAJITSHAW You'll have to [sign-off](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) your commits for the DCO test to pass.

**Comment by debo19** [comment]
@SURAJITSHAW It is advisable to clone the entire repo for any sort of changes. Please refrain from using the github editing option. You can follow this [contributing guide ](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) this has all the steps you need to follow . Let me know if you face any problem.

**Pull request closed without merging**
