### PR TITLE
correct the position of image issue#3338

### PR DESCRIPTION
**Pull request by aditi5050**
the solution to the Image is not aligned with the text on the page: /projects/nighthawk #3338

@legendarykamal please have look

### CODE REVIEW

**Comment by legendarykamal** [comment]
@Nikhil-Ladha or can you please approve the workflow.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
NO!
This is not how you fix issues like these. Please use CSS

**Comment by Nikhil-Ladha** [comment]
Also, when opening a PR you see a template on how the description should be. Obey it and have the description updated like that.
It is there for a reason.

**Comment by legendarykamal** [comment]
yes , I too think that this will not fix the issue. I doubted so I asked for workflow thanks @Nikhil-Ladha for stepping in .

**Comment by aditi5050** [comment]
yeah sure I'll work on the CSS part and make a PR according to the required description

**Pull request closed without merging**
