### PR TITLE
Service Mesh Performance Logo on BRAND PAGE

### PR DESCRIPTION
**Pull request by manishkrjha**
**Description**
This PR is solution of issue #636 {<a href="https://github.com/layer5io/layer5/issues/636">issue link</a>}

This PR fixes #
The unavailability of ***Service Mesh Performance section*** on <a href="https://layer5.io/brand">Brand Page</a>. Now it has a section for the SMP project and its logos. The pictures are taken from <a href="https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smp-brand-kit.zip">SMP Brand Kit</a> and a download option for the same is provided for users as well.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✓] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Can you please make the brand colors display horizontally, as it will reduce the empty white space around it.

**Comment by manishkrjha** [comment]
@Nikhil-Ladha Sure but I'll have to crop and add all five colours individually because adding 'this' photo horizontally will make it difficult for users to read the colour code. I hope there is no issue if I crop this photo?

**Comment by Nikhil-Ladha** [comment]
Ohh, @leecalcote any suggestions?

**Comment by leecalcote** [comment]
No issue with cropping the color scheme photo. Alternatively, you might choose to not use the photo at all an just display the colors and their codes in CSS and HTML.

**Comment by manishkrjha** [comment]
> Also, please follow [this](https://github.com/layer5io/layer5/pull/666/checks?check_run_id=1012730419) link to pass the DCO check.

@Nikhil-Ladha I followed the commands and the terminal is showing ```everything up-to-date```

**Comment by Nikhil-Ladha** [comment]
The commands listed over there are rebase and push commands. I am pretty sure that after running both the commands you won't get this output. After running rebase you may get as it just adds the signoff, but push will add some changes.

**Comment by manishkrjha** [comment]
Well I'm getting this only.

Screenshot (227)

**Comment by Nikhil-Ladha** [comment]
> Well I'm getting this only.
> 
> Screenshot (227)

Where is the rebase command?

**Comment by leecalcote** [comment]
DCO can be a pain the rear. This repo `layer5` is one of the very few where we are ok to occasionally relax the DCO requirements. @manishkrjha given that you are clearly trying to sign-off/are signing-off, I'll update the backend of this PR to pass this DCO check.

**Comment by leecalcote** [comment]
@Nikhil-Ladha outside of the DCO item, is this PR good to merge or do we have a few small changes left? @manishkrjha, it would be good to reduce the width of the color scheme image equal to that of it's original size in order to avoid pixelation.

**Comment by Nikhil-Ladha** [comment]
Actually, the changes made here are fine, but in general some other issues are there in the brand page which I noticed while checking this PR. The issue is with responsiveness of above brand colors and images. And, that can be addressed in a separate PR mentioning a seperate issue.

**Comment by leecalcote** [comment]
@manishkrjha I think the only thing have left here is to reduce the size of the color scheme images. Alternatively, you can color-fill a box-shaped div with each color code and color.

**Comment by leecalcote** [comment]
@manishkrjha just by looking at the # on this PR, you can tell this PR is going to be a doozy. 👿 Let me jump in to assist a little. Great work so far.

**Comment by manishkrjha** [comment]
@leecalcote 

Screenshot (231)

Is this okay??

I'll centre the text

**Comment by leecalcote** [comment]
@manishkrjha you beat me to it! Nice, yes, that'll work well.

**Comment by manishkrjha** [comment]
@leecalcote fine then! I'm centring the text and committing this change.

**Pull request merged**
