### PR TITLE
Abdullah rafi community member added

### LINKED ISSUE #3669: [Community] Member Profile: Abdullah Rafi
**Current Behavior**

@abdullah1308  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @abdullah1308  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/abdullah1308
- Twitter: N/A
- LinkedIn: https://www.linkedin.com/in/abdullah-rafi/
- Link to profile picture: https://drive.google.com/file/d/1GuTV7LFlfWuO6iQj2q2RrKjHpt4W5XNE/view?usp=share_link
- Short Bio: I'm an undergrad student majoring in Information Technology at NIT Karnataka. My interests in cloud systems, open source, and software development led me to be a part of the Layer5 organization where I have been able to work on projects that align with my interests and contribute to the community.  I take great satisfaction in building stuff that is useful to others and Layer5 has enabled me to do so.
- Location: Mangalore, India

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Jittojoyes98**
Signed-off-by: Jittojoyes98 <jittojoyes77@gmail.com>

**Description**

This PR fixes #3669 

**Notes for Reviewers**
@UtkarshMishra12 
Screenshot from 2023-02-02 16-44-30

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@abdullah1308 Please have a look and let us know your thoughts 👀

**Comment by abdullah1308** [comment]
@UtkarshMishra12 @Jittojoyes98 Looks good 😄

**Comment by l5io** [comment]
🚀 Preview for commit df3c1343aca349390f0a78e40b8f0013ce24841c at: https://63dcc6bea646562e8b231989--layer5.netlify.app

**Review by UtkarshMishra12 — APPROVED** [review]
LGMT Thanks @Jittojoyes98 🚀🥇

**Pull request merged**
