### PR TITLE
Built New Version of SMI  Table

### LINKED ISSUE #1031: [Landscape] Build a New Version of SMI table on Service Mesh Landscape
**Current State:**
The current [Service Mesh Interface Compatibility](https://layer5.io/landscape#smi) table has some missing items
**Desired State:**
Build a new version using the following JSON:

```
{
    "results": [
        {
            "id": "0dd368be-745f-4433-a356-f717aac40457",
            "date": "2020-10-14T20:14:48+05:30",
            "mesh_name": "Open Service Mesh",
            "mesh_version": "v0.3.0",
            "cases_passed": "0",
            "passing_percentage": "0",
            "status": "completed",
            "more_details": [
                {
                    "smi_specification": "traffic-access",
                    "time": "2m5.607711181s",
                    "assertions": "10",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-beloved-alpaca/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }, {
                    "smi_specification": "traffic-split",
                    "time": "4m10.378728809s",
                    "assertions": "8",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-dominant-tuna/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }, {
                    "smi_specification": "traffic-spec",
                    "time": "6m16.323837714s",
                    "assertions": "10",
                    "result": "failed in step 2-install",
                    "reason": "resource Deployment:kudo-test-honest-mallard/app-c-deployment: .status.readyReplicas: key is missing from map",
                    "capability": "Half",
                    "status": "Failing"
                }
            ]
        }
    ]
}
```

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

### PR DESCRIPTION
**Pull request by geraldmaboshe**
**Description**

This PR fixes #1031 

**Notes for Reviewers**
N/A

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @geraldmaboshe. With this PR, we're good to remove the "based on servicemesh.es by INNOQ" statement.

Will you have a look at the lack of padding within the tables cells and timeline?

**Comment by geraldmaboshe** [comment]
> Thank you, @geraldmaboshe. With this PR, we're good to remove the "based on servicemesh.es by INNOQ" statement.
> 
> Will you have a look at the lack of padding within the tables cells and timeline?

Thanks for the feedback, Lee. How much padding do we need?

**Comment by leecalcote** [comment]
Good question. If the other tables and timeline remain as there currently are, that would be good.

Ideally, only the SMI table changes in the current gen of the landscape. In layer5-NG, the timeline, tables, and other visuals are ok to change. A new look and visuals is ideal there.

**Comment by geraldmaboshe** [comment]
> Good question. If the other tables and timeline remain as there currently are, that would be good. Ideally, only the SMI table changes in the current gen of the landscape.
> 
> In layer5-NG, the timeline, tables, and other visuals are ok to change. A new look and visuals is ideal there.

Cool

**Pull request merged**
