### PR TITLE
Updated the Twiiter Logo to X Logo

### LINKED ISSUE #4631: Twitter's logo has been changed to X
### Current Behavior
Twitter's logo has been changed to X .I was thinking if we need to update the logo on the layer5 website.
What are the views on this/Any comments?
@leecalcote 
I made some changes it will look somewhat as in the video.
It can be assigned to me if it needs to be changed.

### Screenshots / Mockups

https://github.com/layer5io/layer5/assets/91942072/fc24b4eb-2018-43b7-9f78-b30fe88340f1

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Navansh**
**Description**

This PR fixes #4631 

**Notes for Reviewers**
Updated the Twiiter Logo, to the new X Logo

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 963a953458c4b4493e49b405984e8f7f085c331a at: https://64df6575cb5135065756d4ed--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
Looks good @Navansh but also need to update in commmunity handbook page , community members page etc wherever there is old twitter logo.

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
Please also replace old twitter logo in following pages : 
 - in community members page .
 - in community handbook page.
 - also replace in other pages if there is old twitter logo being used.
 
tx1
tz2

**Review by Debaditya-Som — COMMENTED** [review]
**Code Review - Pull Request #4755: Updated the Twitter Logo to X Logo**
- The update to the X logo has been successfully updated.
- The new X logo matches the current branding and design of "Twitter".
- The code changes appear clean and follow the coding standards.

**Comment by Navansh** [comment]
> @Navansh, kindly replace old twitter logo in following pages :
> 
> * in community members page.
> * in community handbook page.
> * also replace in other pages if there is old twitter logo being used.
> 
> tx1 tz2

Should I create a new PR for this ?

**Comment by abhijeetgauravm** [comment]
> > @Navansh, kindly replace old twitter logo in following pages :
> > 
> > * in community members page.
> > * in community handbook page.
> > * also replace in other pages if there is old twitter logo being used.
> > 
> > tx1 tz2
> 
> Should I create a new PR for this ?

You can add commits to the same branch @Navansh !

**Comment by Ghat0tkach** [comment]
hey @Navansh 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by l5io** [comment]
🚀 Preview for commit d9203441eab4b87430fa11030978faac0444e300 at: https://64e59421315b7f1b5ad5b62a--layer5.netlify.app

**Comment by Chadha93** [comment]
@Navansh Few items left...

**Comment by Ghat0tkach** [comment]
hii @Navansh 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by abhijeetgauravm** [comment]
@Navansh updates?

**Comment by Navansh** [comment]
How do I find the file where the Twitter logo is put for the page : 
"/coomunity/members"

**Review by Chadha93 — COMMENTED** [review]
@Navansh Here's the single member profile's link where you can find Twitter icon. https://github.com/layer5io/layer5/blob/69c903060fe17209fa6499943775a76066975ac9/src/sections/Community/Member-single/index.js#L257.

**Comment by abhijeetgauravm** [comment]
> @Navansh Here's the single member profile's link where you can find Twitter icon.
> 
> https://github.com/layer5io/layer5/blob/69c903060fe17209fa6499943775a76066975ac9/src/sections/Community/Member-single/index.js#L257
> 
> .

// @Navansh

**Comment by l5io** [comment]
🚀 Preview for commit f61c53c9148e1fce981130a2149da125e28e5f54 at: https://6511834070ade61f67c634bc--layer5.netlify.app

**Review by Mohith234 — CHANGES_REQUESTED** [review]
@Navansh There are some changes that need to be done, I've listed them here. Do look into them

- The logo is not visible in the light mode. ( In each page where it is modified )
- On the community members page, the logo isn't visible whenever we hover on top of it.
- Remove the imports of the previously used Twitter icon on the single member's profile pages.
- Please signoff your commits so that the DCO check don't get failed

**Comment by Navansh** [comment]
> @Navansh There are some changes that need to be done, I've listed them here. Do look into them
> 
> * The logo is not visible in the light mode. ( In each page where it is modified )
> * On the community members page, the logo isn't visible whenever we hover on top of it.
> * Remove the imports of the previously used Twitter icon on the single member's profile pages.
> * Please signoff your commits so that the DCO check don't get failed

Well, how do I enable Twitter logo for both dark and light mode ?

**Comment by Mohith234** [comment]
@ritiksaxena124 ^^ might help you here.

**Comment by captain-Akshay** [comment]
is this what we want achieve :-
 
[Screencast from 2023-10-02 23-46-56.webm](https://github.com/layer5io/layer5/assets/59491379/1f4e97e1-53dd-44b9-a314-4cb1126cff96)

**Comment by ritiksaxena124** [comment]
> > @Navansh There are some changes that need to be done, I've listed them here. Do look into them
> > 
> > * The logo is not visible in the light mode. ( In each page where it is modified )
> > * On the community members page, the logo isn't visible whenever we hover on top of it.
> > * Remove the imports of the previously used Twitter icon on the single member's profile pages.
> > * Please signoff your commits so that the DCO check don't get failed
> 
> Well, how do I enable Twitter logo for both dark and light mode ?

yes @captain-Akshay you are on the right path could you please make sure all the icons are of the same size?

**Comment by captain-Akshay** [comment]
@ritiksaxena124 should I work on my own pr or suggest some changes to current one(this will take more time to setup)

**Comment by Mohith234** [comment]
@captain-Akshay you can work on your own PR as @Navansh is inactive due to his other commitments, you are welcome to create a PR as soon as possible. So that we can fix this issue and close it

**Comment by captain-Akshay** [comment]
Alright 👍🏻 assign it to me

**Comment by abhijeetgauravm** [comment]
Closing it as the issue is fixed by #5001. Thanks for the contribution.

**Pull request closed without merging**
