### PR TITLE
Fixes #5690 - added margin b/w 2 sections in the page "solutions/gitops" (mobile view)

### LINKED ISSUE #5690: Improve the page layout on mobile view
### Description

Improve the mobile view of [this](https://layer5.io/solutions/gitops) page

### Expected Behavior

Make sure that the two sections do not overlap with each other and the heading of the next section(What is GitOps) starts after the end of the first section like it is in the Desktop view.

### Screenshots

Screenshot 2024-07-17 at 4 22 08 PM

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by yaten2302**
**Description**
This PR makes sure that the 2 sections in the mobile view don't overlap.

Fixes #5690 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 43c7331c3a9302e328a174a980101422bd5c056a at: https://66e8786b5b65a15613fbf5d4--layer5.netlify.app

**Comment by leecalcote** [comment]
Thanks! Will you add a more descriptive title to this PR?

**Comment by yaten2302** [comment]
Made the changes @leecalcote 👍

**Comment by l5io** [comment]
🚀 Preview for commit e79d9354d6c9f2e04be459083b463d7733623191 at: https://66e965f81de1e2f1513987b9--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@yaten2302 Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by vishalvivekm** [comment]
Adding to the meeting minutes // @yaten2302

**Comment by yaten2302** [comment]
@vishalvivekm , thanks for adding this PR in the agenda of the meeting, we'll surely discuss about it in the call 👍
Apologies, I forgot to add about this to the google doc 🙏

**Comment by l5io** [comment]
🚀 Preview for commit df3b456b20bbed25b3edb5a4484421d62f275378 at: https://66f1495233a5bbdf093d37f2--layer5.netlify.app

**Pull request merged**
