### PR TITLE
add learn service mesh CTA

### LINKED ISSUE #1509: Implementation of Learn Service Mesh CTA Section above footer
**Current Behavior**
There is currently no CTA on the bottom of /books page and as such, we have made a design/section for it
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=4028%3A62

**Desired Situation**
To create a section for the learn service mesh CTA at the bottom of the / book section
Below is how the section should look
Learn Service Mesh CTA

Below is the asset for the visual topology 
https://drive.google.com/file/d/1sPovcFq4NzF_Qd4y9a3K3D1zwNZMrnen/view?usp=sharing

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Tanuj22**
**Description**

This PR fixes #1509 

**Notes for Reviewers**
Also, remove some CSS and fix links 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Kickass. Great job, @Tanuj22

**Comment by Nikhil-Ladha** [comment]
Phew.....there were some issues @leecalcote 😫 ......

**Comment by Nikhil-Ladha** [comment]
One being, the CTA should be center-aligned in mobile view.
Second, we can keep the `service mesh` SVG for the mobile view as well, just reverse the `flex-direction` with center alignement.

**Comment by leecalcote** [comment]
Ok. 😀 pre-go-live all is fair. I looked at how one CTA looked on the /books page, but didn’t look at the rest.

**Comment by leecalcote** [comment]
I missed those, @Nikhil-Ladha. Good eye. Yes, please, @Tanuj22

**Pull request merged**
