### PR TITLE
Added sorting and global filter in the landscape table

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Unrelated issue - the images in these rows:
Screen Shot 2021-02-20 at 1 08 29 PM

**Comment by Nikhil-Ladha** [comment]
> Unrelated issue - the images in these rows:
> Screen Shot 2021-02-20 at 1 08 29 PM
> 
> Browser: Safari

Don't use safari 🤣 .....let me see what can be done

**Comment by leecalcote** [comment]
On Safari, it's a jungle out there.

**Comment by Nikhil-Ladha** [comment]
See if that helps 😶

**Comment by leecalcote** [comment]
New screenshot:
Screen Shot 2021-02-20 at 1 37 40 PM

**Comment by Nikhil-Ladha** [comment]
I can't figure out the area of issue 🤔 .....someone with a mac needs to look after this.

**Comment by leecalcote** [comment]
Roger that. Will take the baton here....

**Comment by EmperorYP7** [comment]
@leecalcote may I have the baton? **gazes with starry eyes**

**Comment by leecalcote** [comment]
hahaha! Yes, that would be great. _stretches to hand off baton_

**Pull request merged**
