### PR TITLE
Change the links of contributors and License

### LINKED ISSUE #4031: Changes in README.md
### Current Behavior
The options below the Layer5 logo in README.md such as License and contributors when clicked redirect users back to the repository itself.

image

### Desired Situation
The options below the Layer5 logo in README.md such as License and contributors should redirect users to their respective locations for easier access.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Jamir2412**
This PR fixes #4031 
I have change the links of contributor and license that redirect the users to their respective locations for easier access.

Signed-off-by: Jamir Ahmed <jamir.ahmed.ghtwtrlkdn@gmail.com>

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 35999b8cbe3f4f101d9537704703b0a5ab637ce7 at: https://642e60452e190a58370561f2--layer5.netlify.app

**Comment by Jamir2412** [comment]
@Chadha93 
can you please tell me How to signed off the commit?

**Comment by samyakshah3008** [comment]
@Jamir2412  You can follow below potential solutions to sign off your commits: 

image
image

As you have already committed without signing off, you can use: 
`git commit --amend` and follow the signing process again from above image. 

Read more on `git commit --amend` command here: 
https://www.atlassian.com/git/tutorials/rewriting-history#:~:text=The%20git%20commit%20%2D%2Damend,message%20without%20changing%20its%20snapshot. 

@Chadha93 Please correct me if I am missing out any point.

**Review by samyakshah3008 — APPROVED** [review]
Looks good to merge, 
Please first sign-off your commits.

**Review by leecalcote — APPROVED** [review]
Thanks for this review, @samyakshah3008 👍

**Comment by leecalcote** [comment]
Thanks, @Jamir2412

**Comment by Jamir2412** [comment]
@leecalcote 
You're Welcome. Looking forward to contribute more in the community.

**Pull request merged**
