### PR TITLE
Add member profile for Eeshaan Sawant

### LINKED ISSUE #3478: [Community] Member Profile: Eeshaan Sawant
**Current Behavior**

@eeshaanSA has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @eeshaanSA as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @eeshaanSA 
- LinkedIn: sawanteesh
- Link to profile picture: https://drive.google.com/file/d/13Wx8jzaRPSW0oUHXmfShfLNEogjAeU-V/view?usp=drivesdk

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by deepeshaburse**
Signed-off-by: Deepesha Burse <87636253+deepeshaburse@users.noreply.github.com>

**Description**

This PR fixes #3478 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 5452fa4c4a7368a4de150aa7ea8da0086929eb1f at: https://63a223d0a8fc311320f5e1b1--layer5.netlify.app

**Comment by eeshaanSA** [comment]
Twitter: https://twitter.com/sawanteeshaan

**Comment by l5io** [comment]
🚀 Preview for commit 464b451c5d25331af025c7e93366d2611470f4e1 at: https://63a323a51ff61f22f6961136--layer5.netlify.app

**Review by eeshaanSA — APPROVED** [review]
Lgtm🚀

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
