### PR TITLE
[Blog] - Created Buf Protocol Blog/Post

### LINKED ISSUE #1244: [NG] [Blog] New Post Wanted: Buf protocols
**Current Behavior**

@kalradev presented a highly informative presentation on Buf, followed by a demo.

**Desired Situation**

A post to follow up and elaborate on the topic, with insights from the [original presentation](https://docs.google.com/presentation/d/1lnZq-d-Q__Mxhay0psJ-TAuKOLHApxOC1xeLy4HxCxE/edit?usp=sharing)

Tentative Title: Buf - Rethinking Protocol Buffers 
Content: 
- What is Buf?
- Features
- Comparison between Protobuf and Buf
- What caught our eye?
- Roadmap to adopting Buf
- An invitation and call to action to join @kalradev in the community and engage in Layer5 projects

Slides from the deck can directly be used as info-graphics for the post

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description**

This PR Fixes #1244 

**Notes for Reviewers**

This PR is still a **WIP**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Can you please review this, do let me know if any changes are necessary as this is still a WIP :)

**Comment by l5io** [comment]
🚀 Preview for commit 68153ac0f273004da2bb463902bf97003043b1d2 at: https://608467e3ce9d7fd0a9f0a6e0--layer5ng.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 68153ac0f273004da2bb463902bf97003043b1d2 at: https://608468035d40b5be9ab724cf--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Not sure about the content, but the UI looks fine to me.
Just one thing,`center` align the "problems" image in mobile view.

**Comment by leecalcote** [comment]
@adithyaakrishna I'll reach out to chat with you about this post. Good of you to pick up this exercise.

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha @leecalcote There's a slide here, which says about phase 2 which contains Buf Schema Registry. But that content is outdated according to [Buf Site Here](https://docs.buf.build/roadmap/#features)
That's the last part of the blog remaining. Could you please lmk how I can proceed with this, whether to update or not?

**Comment by l5io** [comment]
🚀 Preview for commit 8e2409e9af64fe65652fe9a00da46e01c6801075 at: https://6087c22ef2b6ccd71d4dfc5e--layer5ng.netlify.app

**Comment by Jashpatel1** [comment]
@leecalcote @adithyaakrishna @Nikhil-Ladha Any updates here?

**Comment by adithyaakrishna** [comment]
@Jashpatel1 Waiting for @leecalcote 's review on this 👀

**Comment by adithyaakrishna** [comment]
Thanks @leecalcote 💯🎉

**Comment by leecalcote** [comment]
😀

**Pull request merged**
