### PR TITLE
Fixes [Newsletter Alignment] Center-align "Subscribe to our Newsletter"

### LINKED ISSUE #4822: Misalignment in
### Description

This "Subscribe to our News Letter" is rightly aligned. It should be in the center.
### Screenshots

image

### Environment:
- Host OS: Windows 10
- Browser:Chrome

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Kkotiswar**
**Description**
This pull request addresses the bug where the "Subscribe to our Newsletter" element is currently right-aligned and should be centered.
previously -> 
image
After Fix -> 
image

This PR fixes #4822 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 13b6ef4d26e4cb5528fd31fef8fabd918d340240 at: https://64fa55c444ff32007ce93bab--layer5.netlify.app

**Review by Mohith234 — COMMENTED** [review]
A quick heads up @Kkotiswar. The issue is neither approved as valid nor assigned to you. 

Please be patient until the maintainers respond. Creating PRs without getting assigned is completely against the contributing guidelines. Also, it is not a good practice. 

Follow the contributing guidelines or else your work will not be considered.

**Comment by Kkotiswar** [comment]
> A quick heads up @Kkotiswar. The issue is neither approved as valid nor assigned to you.
> 
> Please be patient until the maintainers respond. Creating PRs without getting assigned is completely against the contributing guidelines. Also, it is not a good practice.
> 
> Follow the contributing guidelines or else your work will not be considered.

**Comment by l5io** [comment]
🚀 Preview for commit 387c65081632db80b1626ef6227a51b9cb7532e4 at: https://64fb0eaa7c8f0978590d40fc--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thanks @Kkotiswar for this.
Please do take a look:  https://github.com/layer5io/layer5/issues/4822#issuecomment-1711684976

**Review by Mohith234 — CHANGES_REQUESTED** [review]
- The changes made have affected misalignment at the other breakpoints. 
- Find the below screenshot for reference
- Do check it and fix them @Kkotiswar 

image

**Review by Mohith234 — APPROVED** [review]
LGTM 🚀 @Kkotiswar 

P.S Please do follow the contributing guidelines

**Comment by Kkotiswar** [comment]
Certainly, I acknowledge and appreciate your reminder to follow the contributing guidelines. Rest assured, I will diligently adhere to the guidelines from now on. Thank you for the guidance, and I look forward to contributing positively to the community.

**Comment by Ghat0tkach** [comment]
hey @Kkotiswar 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Kkotiswar** [comment]
Hi @Ghat0tkach,

I've created an agenda item for the upcoming website call regarding the pull request I submitted.

Thanks!

**Comment by Mohith234** [comment]
@Kkotiswar what were the results of the poll that you've conducted? Please post an update so that we can complete this issue as soon as possible.

**Comment by Kkotiswar** [comment]
> @Kkotiswar what were the results of the poll that you've conducted? Please post an update so that we can complete this issue as soon as possible.

Yeah, these are the results for the poll I have created. 
Screenshot_2023-09-28-19-58-43-218-edit_com brave browser

**Comment by Mohith234** [comment]
@Kkotiswar No one has voted really and I think let's keep the design as it is in the current website. Wdyt?

Let's close this issue as soon as possible

**Comment by Mohith234** [comment]
Closing as this is not planned.

**Pull request closed without merging**
