### PR TITLE
adding-updated design-to-how-it-works-section-akri

### LINKED ISSUE #4830: [Screenshots] Akri under "How it Works See It in Action” section
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/akri) has only two old screenshots of the designer and visualizer in the "How it Works See It in Action” section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Akri](https://layer5.io/cloud-native-management/meshery/integrations/akri) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by PRANJALRANA11**
**Description**

This PR fixes 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by PRANJALRANA11** [comment]
@abhijeetgauravm thanks for helping

**Comment by l5io** [comment]
🚀 Preview for commit a709b323218df9aa060dfcab430eb58dc6334648 at: https://6507157e851b2749b421947f--layer5.netlify.app

**Review by abhijeetgauravm — COMMENTED** [review]
Good work but need enhancement as discussed in websites call!

**Comment by Ghat0tkach** [comment]
hey @PRANJALRANA11 
Let's discuss it on the websites call.
I have already added your agenda as part of today's meeting minutes

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by Mohith234 — CHANGES_REQUESTED** [review]
- These are not the actual screenshots that are required @PRANJALRANA11 
- Do check out the [Akri](https://layer5.io/cloud-native-management/meshery/integrations/akri) integration and replace it with the existing images.

**Comment by PRANJALRANA11** [comment]
But I think in website call meeting lee had said that these are good as there is no screenshot reference provided in spreadsheets

**Comment by PRANJALRANA11** [comment]
and I think every integration have same screenshot

**Comment by leecalcote** [comment]
Both of you fine gentlemen are correct, @Mohith234 and @PRANJALRANA11. 

Having these screenshots, while not of Akri (which is the ideal - what the issue calls for) puts us in a better position that reusing the same screenshots that most of the rest of the pages have. We could merge this PR as a short-term stop gap until Akri-specific screenshots are taken.

**Comment by PRANJALRANA11** [comment]
@leecalcote please merge this pr

**Comment by leecalcote** [comment]
@PRANJALRANA11 when will you have appropriate screenshots?

**Comment by leecalcote** [comment]
Instead of pressuring to merge the PR, how about you provide a genuine fix? Otherwise, remove the "fixes ####" in the PR description so that the issue doesn't close upon merge and unassign yourself from the issue, so that someone else has a chance to sign up to  provide an accurate fix.

**Comment by PRANJALRANA11** [comment]
@leecalcote but in above comment you have said that We could merge this PR as a short-term stop gap until Akri-specific screenshots are taken so that's why I was asking is there is a mistake in my understanding please tell

**Comment by leecalcote** [comment]
Yes, you’re right. I’m also recognizing that when this PR is merged, so too will be the issue tracking the continued need for screenshots of the actual technology be closed. 

Again, you’re asking for the PR to be merged, and still not answering my question, which is precisely the thing that gives me pause here. Your concern is with getting a PR merged and not with resolving the actual issue. This reinforces in my mind that you will not come back to fix the actual issue. So, I will ask again the same question that I just asked…

**Comment by PRANJALRANA11** [comment]
@leecalcote I think I took that all wrong sorry for that but I was unable to find the Akri integration in the components of playground could you tell me where it is once I find it I just have to make a design with I am right

**Comment by PRANJALRANA11** [comment]
and also I was not answering the question because I was confused with the past messages.  so now I will fix that issue fully

**Comment by l5io** [comment]
🚀 Preview for commit ec8e52c52bfdfeedb7224a981267bdc2868587be at: https://6548f7d39c2cf20f1d129d55--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 8b51026c95c233c90b02fd166116183456f8926d at: https://65504b8d51f89631098cf905--layer5.netlify.app

**Pull request merged**
